### ISSUE TITLE
Translating Solasta CE

### ISSUE THREAD

**Issue by Tloz** [SolastaMods/SolastaUnfinishedBusiness#1628]
Hello.

I'm interested in contributing to Solasta CE by translating it to French.
How can I do that? I assume it would be after the Inner Strength DLC release

Thanks for your answer, and the amazing work

**Comment by ThyWoof** [comment]
Sorry for the delay and thanks for offering. Our DEV branch is already set to the next release. You can start the translations from files under Translations folder. Thanks again for the help.
