### ISSUE TITLE
Tinkerer Flash of Genius Sound

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#1694]
The Tinkerer's Flash of Genius has a sound effect taken from Bless whenever a character enters or exits their aura. It is very distracting and loud.

In TinkererClass.cs it's on line 360 or so:

```cs
flashEffect.SetParticleEffectParameters(SpellDefinitions.Bless.EffectDescription.EffectParticleParameters);
```

Please either remove it, or replace it with something more subtle like the Paladin auras.

**Comment by EnderWiggin** [comment]
Tinkerer class has been reworked from ground-up as Inventor and Flash of Genius now works differently.

**Comment by Andargor** [comment]
Ok thanks, will close and open another if there are other issues.
