### ISSUE TITLE
Circle of the Night Druid and Path of the Spirits Barbarian

### ISSUE THREAD

**Issue by tivie** [SolastaMods/SolastaUnfinishedBusiness#1726]
I've created two subclasses: **Circle of the Night** for Druid (inspired by the Circle of the Moon) and **Path of the Spirits** for Barbarians (inspired by the Path of the Spirit Totem).

Would you be interested in a PR implementing both classes?

**Comment by ThyWoof** [comment]
Opa, Estevao, tudo na paz? Pode enviar sim! Eh um mod comunitario.

**Comment by tivie** [comment]
Fantástico. Vou então testar tudo direitinho e fazer um PR em breve.

**Comment by ThyWoof** [comment]
Finalizei o review do codigo do Circle of The Night. Na realidade nao precisava setar novamente o efeito. Bastava copiar do mesmo efeito do WildShape.

Aguardando agora a outra classe para ver se ainda entra no release. Mod sera congelado na sexta para QA.

**Comment by tivie** [comment]
Acho que o wild shape partiu. testei agora mesmo e as formas não estão a aparecer.

![image](https://user-images.githubusercontent.com/1608730/203405800-deed728b-f785-4c56-a5a8-75990df63eb7.png)

**Comment by tivie** [comment]
@ThyWoof Não te preocupes, vou trabalhar e testar a subclasse e ver se consigo ter algo satisfatório pronto antes de sexta feira.

**Comment by ThyWoof** [comment]
consegui resolver ambos os problemas. O botao voltou a funcionar corretamente _ assim como o status dos slots _ e os monstros que voce criou regressaram. Parece bastante solida agora.

pode focar-se no Barbaro.

**Comment by tivie** [comment]
Também encontrei o problema. Era preciso fazer clear da list antes de adicionar os novos monstros.

Obrigado!

**Comment by ThyWoof** [comment]
Obrigado pelo Water Elemental. No Wild Master precisei criar monstros com poderes. Penso em criar uma interface `IModifyShapeOrSummon' que permita de forma mais simples adicionar poderes ou modificar qualquer caracteristica do monstro antes da finalizacao.

Devo trabalhar nisso hoje. Uma vez criada voce podera alterar os monstros da lua.

**Comment by ThyWoof** [comment]
Criei tambem um patch para a janela de Shapes voltar a enquadrar se a quantidade for muito grande.

**Comment by tivie** [comment]
> Obrigado pelo Water Elemental. No Wild Master precisei criar monstros com poderes. Penso em criar uma interface `IModifyShapeOrSummon' que permita de forma mais simples adicionar poderes ou modificar qualquer caracteristica do monstro antes da finalizacao.
> 
> Devo trabalhar nisso hoje. Uma vez criada voce podera alterar os monstros da lua.

Isso é muito útil. Obrigado!

Entretanto, estive a testar o PathOfTheSpirits Barbarian, e já está a funcionar muito bem. Acho que está um pouquito overpowered, sobretudo se for escolhido o Bear.  Talvez diminuir o HP concedido (mudar para 1 hit point per level em vez de 2).
Porque se for escolhido com o feat Tough, em nível 10 são mais 40 pontos de HP.
