### ISSUE TITLE
Aksha fight bug

### ISSUE THREAD

**Issue by Myrdo** [SolastaMods/SolastaUnfinishedBusiness#1777]
Game freezes during the Aksha fight, using version 1.4.28.P
would be great if you could fix this...
[Solasta_Bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10099040/Solasta_Bug.zip)

**Comment by ThyWoof** [comment]
There was indeed a null exception in one of our patches but I wasn’t able to get exactly the same effect to happen for testing. I put an additional check there and played about 10 rounds without issues. Please check on your end on next update and let me know.

**Comment by Myrdo** [comment]
Ok, thx for the info...will check later

**Comment by Myrdo** [comment]
Thank you very much for fixing this bug. Aksha is history now ;)
