### ISSUE TITLE
PathOfTheSpirits: Wolf Leadership is broken again

### ISSUE THREAD

**Issue by tivie** [SolastaMods/SolastaUnfinishedBusiness#1801]
## Barbarian (Wolf) rages. Friends get Wolf Spirit. (correct)
![image](https://user-images.githubusercontent.com/1608730/204833046-5fc54302-00c1-43e8-bc10-2f30496bde8f.png)

## Barbarian stops raging
![image](https://user-images.githubusercontent.com/1608730/204833667-b16f551e-9440-46c2-a9c5-2c77dd4f3e5a.png)
Log says friends lose wolf Spirit. However...

## Friend Turn (Elisa). Says she has Wolf Spirit again and has advantage
![image](https://user-images.githubusercontent.com/1608730/204834125-9cd083b0-4fdf-45bb-96a4-8f632571456d.png)

![image](https://user-images.githubusercontent.com/1608730/204834280-8b371308-7eb5-417d-be36-6a0c083f1386.png)

**Comment by tivie** [comment]
As an added note, it seems that, in Solasta, Round = Turn.

**Comment by ThyWoof** [comment]
Was this after today’s changes?

**Comment by tivie** [comment]
> Was this after today’s changes? This is getting a nightmare to fix. Original one was loosing power after first round. Reason why we wrote this fix.

yes. It was after today's fix.

**Comment by tivie** [comment]
It's super weird. Allies are "notified" to remove Wolf Spirit, but then as soon as their turn starts, they get the condition again.

**Comment by ThyWoof** [comment]
Problem is the aura. I’m still researching alternatives but no luck yet

**Comment by ThyWoof** [comment]
best I can do now is: The spirit of the wolf makes you a leader of hunters. When you start raging, any friend within 15 feet that can see you will have advantage on melee attack rolls for 1 minute.

**Comment by tivie** [comment]
It's good enough.
