### ISSUE TITLE
Improved Pact Weapon does nothing

### ISSUE THREAD

**Issue by Correction1** [SolastaMods/SolastaUnfinishedBusiness#1820]
The Warlock Invocations: Improved Pact Weapon, Superior Pact Weapon and Ultimate Pact Weapon do absolutely nothing of whats stated in the description. It does not add the attack, damage or allow the use of the weapon being used as a focus.

On version 1.4.30.8

Save file posted for convenience.

[LV1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10146636/LV1.zip)

**Comment by ThyWoof** [comment]
fixed on dev branch. thanks for save.
