### ISSUE TITLE
Multiclass Blade-dancer / Raven conflict

### ISSUE THREAD

**Issue by guard65** [SolastaMods/SolastaUnfinishedBusiness#1827]
Just FYI on multiclassing a Blade-dancer with a Raven subclass. 

Note that the The Blade Dancer skill shows up on the multiclass until you select select the Raven subclass. 
Then bladedancer skill will no longer show up as an action or bonus action only the Heart Seeking Shot shows up.  
It seems to be a menu conflict of some sort in the UI.

**Comment by ThyWoof** [comment]
Save?

**Comment by ThyWoof** [comment]
not a bug.
