### ISSUE TITLE
Warlock Patrons are not adding Spells

### ISSUE THREAD

**Issue by Correction1** [SolastaMods/SolastaUnfinishedBusiness#1828]
Any warlock patron added in this mod does not properly add the spells to the spell list. My warlock is a Soul Blade and he is missing all the spells granted through the patron (False Life, Shield, etc). I have also double checked this on the character creator, and it does not work for Elementalist  and Rift Walker. I have not testing moon lit but I am assuming it does not work as well.

Save file posted for convenience.
[LV6.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10149666/LV6.zip)

**Comment by ThyWoof** [comment]
What is your game version?

**Comment by Correction1** [comment]
Latest version of Solasta, and then version 1.4.30.8 of UnfinishedBusiness.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/205526828-35539676-8500-4a0e-a580-acbb1398bdbe.png)
Warlocks don't get auto prepared spells. They get additional spells they can learn in their list. It's working as expected.
