### ISSUE TITLE
6 Character party can't exit the residences (Caer Cyflen)

### ISSUE THREAD

**Issue by Khabes31** [SolastaMods/SolastaUnfinishedBusiness#1829]
A 6 party can't go out the residence of Caer Cyflen, the exit portail don't work : 

![Capture](https://user-images.githubusercontent.com/101841161/205523804-1c7766e8-7e92-4760-a5c8-f85b229a88be.PNG)

The save for more convenience : 
[Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10149772/Test.zip)

**Comment by ThyWoof** [comment]
You need to use the pause trick. There is a big chance I'll disable this on official campaigns.
