### ISSUE TITLE
After Updating from 1.14.30.7 to 1.14.30.11 casting spells freezes characters

### ISSUE THREAD

**Issue by sztrzask** [SolastaMods/SolastaUnfinishedBusiness#1838]
After updating from 1.14.30.7 to 1.14.30.11 casting any spell or cantrip freezes character. Attached is the Player.log. As you can see there seems to be something wrong with few of the patches.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10176813/Player.log)

I'm on Windows, not opted-in to any betas, I have all DLCs

**Comment by sztrzask** [comment]
Oh, it's because there's a new patch today.

**Comment by ThyWoof** [comment]
Correct. Don’t auto update your games if using mods.

**Comment by sztrzask** [comment]
@ThyWoof, I have a fix, but I'm unable to push a branch to this repo - could you add me as collaborator or smthing?

**Comment by sztrzask** [comment]
Nevermind - forked and pushed via PR from there: https://github.com/SolastaMods/SolastaUnfinishedBusiness/pull/1839
