### ISSUE TITLE
The Warlock: Superior and Ultimate Pact Weapon invocations

### ISSUE THREAD

**Issue by Knitby** [SolastaMods/SolastaUnfinishedBusiness#1863]
Hi there, is there supposed to be something else they can do? Because from what I'm reading it looks like it does the same thing as the Improved Pact Weapon invocation.

**Comment by Knitby** [comment]
I should add more clarification. I'm referring to the +1 to attack and damage rolls that each Pact Weapon invocation gives.

**Comment by Knitby** [comment]
In that case, I would like to report a bug. My Dragonborn SoulBlade Warlock has both the Improved and Superior Pact Weapon invocations learned but his attack and damage rolls only count as if he only has learned one of them (excluding other bonuses of course).
The save file with the hero included:
[IM_hsIF5IaVCEawJifAju8IBQQ_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10199592/IM_hsIF5IaVCEawJifAju8IBQQ_1.zip)

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/5388087d70610b267dafbe32d4fafc31c6b2a9bc). Thanks.
