### ISSUE TITLE
Path of the Spirits: Spirit Walker DC is 0

### ISSUE THREAD

**Issue by Knitby** [SolastaMods/SolastaUnfinishedBusiness#1870]
Game Version: Solasta 1.4.31
UB Version: 1.4.31.3

The Spirit barb's Spirit Guardians ability has the DC set to 0, making all enemies save against it.

Playing a Snow Dwarf Path of the Spirits Barbarian, save file with the hero included:
[IM_hsIF5IaVCEawJifAju8IBQM_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10201029/IM_hsIF5IaVCEawJifAju8IBQM_3.zip)

**Comment by ThyWoof** [comment]
Fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/56b1efc5eb01854052169d254abb39761e8be304). Thanks.
