### ISSUE TITLE
[Bug?] Sunlit Blade and Twinned spell

### ISSUE THREAD

**Issue by Zenbanner** [SolastaMods/SolastaUnfinishedBusiness#1874]
Sunlit blade is available for Twinned spell, but the second attack does not activate for me. Perhaps this is a bug?

**Comment by ThyWoof** [comment]
We fixed this before [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/7d36a8ece1954ff0bd1054693b96d8d6d4432876). Not sure why it's happening again. Can you please share a save?

FYI, @EnderWiggin

**Comment by Zenbanner** [comment]
> We fixed this before [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/7d36a8ece1954ff0bd1054693b96d8d6d4432876). Not sure why it's happening again. Can you please share a save?
> 
> FYI, @EnderWiggin

Of course. Sorry for the delay, wanted to get into combat and make sure I wasn't doing anything wrong. 

For reference, I am in "Temple of Evil" Campaign. The save is in the middle of a fight so you can quickly reproduce it. 

Github is saying that it does not support the file type? How do I upload the save?

**Comment by ThyWoof** [comment]
Hmm, can you paste a Google drive link or similar?

**Comment by Zenbanner** [comment]
Check if this works!

https://drive.google.com/drive/folders/15lTItqlDmVSERyyX6OMTawwoUNqRJAXj?usp=sharing

**Comment by ThyWoof** [comment]
Fixed on DEV branch. Thanks.
