### ISSUE TITLE
1.4.31.4 Druid Shapeshift with all classes bug?

### ISSUE THREAD

**Issue by OkamiKoromaru** [SolastaMods/SolastaUnfinishedBusiness#1876]
When updating to the latest version and loading up a save, when progressing into a fight all my characters have access to druid shapeshifting bonus action, and unsure what has caused this and curious to if it will cause any issues when leveling up

**Comment by ThyWoof** [comment]
It won’t cause any issues on level up but don’t use it on non Druid heroes

**Comment by ThyWoof** [comment]
fixed on 1.4.30.5
