### ISSUE TITLE
Level Bug: Main Campaign Max Level

### ISSUE THREAD

**Issue by Knitby** [SolastaMods/SolastaUnfinishedBusiness#1881]
Game Version: Solasta 1.4.31
UB Version: 1.4.31.5

Playing in the COTM campaign, even with the 'Level 20' option enabled, the game still thinks that Level 12 is the max. However, you're still able to earn XP enough to level up to 13, 14, and so on. This causes my PCs to be able to level up way past the amount of XP they needed to level up.

For example, currently, the party has enough XP to be in the 13th level. Since the game thinks that level 12 is the max and that our XP is past the amount of level 12, they're able to continually level up to 14, then 15, and so on.

The save file (they're conveniently placed next to a long rest safe area so you can see the bug for yourself immediately):
[IM_hsIF5IaVCEawJifAju8IBQM_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10201484/IM_hsIF5IaVCEawJifAju8IBQM_1.zip)

**Comment by Knitby** [comment]
Should also add that a temporary workaround to display the correct level would be to click the 'LEVEL UP' button and then cancel out of it. The button disappears after that.

**Comment by ThyWoof** [comment]
did you enable level 20 before or after starting the campaign?

**Comment by ThyWoof** [comment]
Thanks. I was able to fix it. On next release.
