### ISSUE TITLE
Softlock when resting with 5 players multiplayer

### ISSUE THREAD

**Issue by vicbois390** [SolastaMods/SolastaUnfinishedBusiness#1890]
Resting causes the game to softlock with inconsistent feedback to each player on who is waiting to finish resting. Sometimes the rest will appear to finish but open the rest UI again immediately. Some players may finish but others will be waiting. The game can continue by having all players leave, allowing the host to save and remake the lobby. Please see uploaded logs, appears to be an array index issue.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10203273/Player.log)
[Player-prev.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10203274/Player-prev.log)

**Comment by ThyWoof** [comment]
5 players or 5 heroes with 4 or less players?

**Comment by vicbois390** [comment]
> 5 players or 5 heroes with 4 or less players?

5 human players with 5 heroes.

**Comment by ThyWoof** [comment]
UAU! It means the last patch I wrote to fix the room worked. UHAY. One more to fix.

**Comment by vicbois390** [comment]
> UAU! It means the last patch I wrote to fix the room worked. UHAY. One more to fix.
It sure did! We did get an error in the lobby one time when starting the campaign, but when loading a save it seemed to work every time.

**Comment by ThyWoof** [comment]
I believe I found the reason for this one and also ended up patching 2 other related screens in addition to the Wait one: Kick and Vote.

Have you tried vote in your gameplay? Did it break as well?

**Comment by ThyWoof** [comment]
Please check again on .6 and share logs if bug persists.

**Comment by vicbois390** [comment]
By Vote, do you just mean having each player vote on a conversation option? If so, that seemed to work correctly (or close enough that we didn't notice an issue). If it's some sort of vote kick I am unfortunately unfamiliar, we only use private lobbies.

Thanks for being so responsive, it will likely be a few days before we can get the whole crew together again but we will definitely test.

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/334d0f5b32f56468874a71a8a81eb111a963a4fc). please test it again and reopen case if issue still there...

**Comment by vicbois390** [comment]
Tested and confirmed fixed, thank you!

**Comment by ThyWoof** [comment]
@EnderWiggin , check this. Awesome news.
