### ISSUE TITLE
Bug raise shield and twin blade

### ISSUE THREAD

**Issue by Graham198011** [SolastaMods/SolastaUnfinishedBusiness#1892]
Raise shield doesnt seem to be functioning for me, i have tried with a few characters and it is not triggering. Here is a save file with ready access to it 

https://drive.google.com/file/d/1TrLbyN5LnFlDv_mO0-7Al-FmSZbTbBFm/view?usp=sharing

Here is a link for a save using twin blade 

https://drive.google.com/file/d/1icJL6JU-SVcU_bfeH7s_5rFreTxpq-ad/view?usp=sharing

**Comment by dolenam317** [comment]
They are official feats from the game. Could you please confirm that without the mod they are working normally ?

**Comment by Graham198011** [comment]
so did some checking, twin blade did trigger without the mod, but not with it, so not sure what interaction is happening in my game. But raise shield didnt even without the mod so i will report that to TA

thanks.

**Comment by dolenam317** [comment]
No we should thank you for reporting and did a regression test for us as well. Now please provide your save file please let me know what is the delta between your AC and the attack that you assume they should trigger twin blade and raise shield ?

**Comment by Graham198011** [comment]
did some more testing my self and i think the issue is taking cloak and dagger with twin blade is the issue, the 2 do not interact.

**Comment by ThyWoof** [comment]
Is it OK to close this one then?

**Comment by dolenam317** [comment]
Isn't raise shield still broken ?

**Comment by ThyWoof** [comment]
I tested without the mod. It’s broken there too

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/207105423-24931484-8efc-4f83-85ed-c50c95a3a757.png)
update. It isn't broken with or without mod. It's really the AC difference there that will make it trigger so it might take a while. We forced a higher AC to test.

**Comment by ThyWoof** [comment]
Raise Shield fixed on Dev branch.

**Comment by ThyWoof** [comment]
@Graham198011 , can you please test twin blades again using 1.4.31.7? I believe the fix for Raise Shield should fix that as well.

**Comment by Graham198011** [comment]
OK so testing so far, raise shield works with throwing axes now, about to check javelins and test twin blade.

**Comment by Graham198011** [comment]
ok twinblade works now with throwing weapons equipped, raise shield now works with javelins equipped too, had to wait 41 turns for the damn mob to roll an attack roll in the right window. but yeah looks good, thank man.

If you want me to test any other bug fixes let me know, im happy to help hard working modders, wish i had the talent to do it too.

**Comment by ThyWoof** [comment]
Do you have a Discord account? Would love to add you to our internal team.

**Comment by Graham198011** [comment]
1mm0rtAl1#8975 here you go, still to set up discord on my steam deck yet though

**Comment by Graham198011** [comment]
and now i have

**Comment by ThyWoof** [comment]
Perfect. Open the mod UI and go to Credits. There is a Discord button there with an invite. Once there find us in general-modding

**Comment by Graham198011** [comment]
hmmm cant find a discord button on there. only a long list of credits. sadly i cant take a screen shot to show you on the steam deck

**Comment by ThyWoof** [comment]
https://discord.gg/KvArYEG7

**Comment by Graham198011** [comment]
ok im in,

**Comment by ThyWoof** [comment]
ping Zappastuff there. Will close this one.
