### ISSUE TITLE
Vampiric Touch and Life Drain are ranged now

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#1894]
The 3rd level spell "Vampiric Touch" as well as the wight ability "Life Drain" are now ranged spells whereas they used to be melee spells. The description even still says "melee" under range.

It's happened consistently across different campaigns. Unfortunately I don't have a save file ready atm to showcase this but I can work towards getting one soon if needed. This is just kinda one of those things that I acknowledged wasn't working correctly a while ago and finally got around to reporting it :P

If the spells were changed intentionally then I guess the description just needs to be changed.

Let me know if you need any more info or files.

**Comment by ThyWoof** [comment]
no need. I have a guess on what might be going on.

**Comment by lovemachine44** [comment]
Ok, give me some time and I'll get a save to you. On a side note I was wondering if it had anything to do with the cantrip minor lifesteal being ranged since that is a cantrip from this mod.

**Comment by lovemachine44** [comment]
https://drive.google.com/drive/folders/1bmRV3gi_NUJJbrTFYIwT_ayDVIRDx5_E?usp=sharing
Save file and included settings file just in case.

Just an fyi this is only for the vampiric touch spell. Since life drain is an enemy only ability it may take longer for me to get a save with a wight who's ready to use it.

**Comment by lovemachine44** [comment]
Just uploaded a different save file that has ally wights to test life drain too. Replaced old file in the folder from the link ^

**Comment by lovemachine44** [comment]
Thank you.
