### ISSUE TITLE
Ranged Expert, the Light Property, and Hand Crossbows

### ISSUE THREAD

**Issue by HydrallUrakan** [SolastaMods/SolastaUnfinishedBusiness#1906]
I picked up Ranged Expert for my rogue, wanting to do the classic sword and hand crossbow look, but I noticed something odd - the bonus action attack always showed up, and did not add my character's ability modifier. This was strange, but I figured it was a change on the mod's part since I lacked Two Weapon Fighting.

However, I eventually checked, and realized that it was actually the Crossbow's Light property that was doing this; with just a hand crossbow in my character's hands, the bonus action attack only shows up one I actually take the attack action, and more importantly adds the ability modifier as usual. It seems like the Light property on the hand crossbow is being interpreted like a melee weapon would, allowing TWF, and this is overriding the usual bonus action attack from Ranged Expert.

Unsure if this is intended behavior or not.

**Comment by ThyWoof** [comment]
Thanks for the detailed explanation. Will share with @EnderWiggin

**Comment by ThyWoof** [comment]
do you have a save we can use for QA?

**Comment by EnderWiggin** [comment]
Ranged expert adds bonus attack with one handed ranged weapon after you make an attack, so that's why attack appears then. It isn't present before because you can dual wield fight only with melee

**Comment by HydrallUrakan** [comment]
That's what I'm saying, though - when I equip a light melee weapon and a hand crossbow, both attacks show up immediately, and it acts like I'm using TWF with two melee weapons. I'm not sure if it's because I've respecced the character, because they're multiclassed, or what - but it's consistent. 

Equipping a rapier instead of a shortsword fixes the problem, so it appears to be connected to the melee weapon. Though then I can't use the crossbow until that bonus action attack is enabled, which is a bit of a shame.

[handcrossbow.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10218336/handcrossbow.zip)

**Comment by EnderWiggin** [comment]
oh... Game doesn't actually check if weapon is melee or not when deciding to add dual-wield bonus attack - it just checks if they are light

**Comment by ThyWoof** [comment]
@EnderWiggin , as we already patch `RefreshFightingStyles()` I added a test to deactivate TWF is main or off hand are one handed ranged:

```
                    if (mainHandSlot.EquipedItem != null && ValidatorsWeapon.IsRanged(mainHandSlot.EquipedItem) &&
                        ValidatorsWeapon.IsOneHanded(mainHandSlot.EquipedItem))
                    {
                        isActive = false;
                    }

                    if (offHandSlot.EquipedItem != null && ValidatorsWeapon.IsRanged(offHandSlot.EquipedItem) &&
                        ValidatorsWeapon.IsOneHanded(offHandSlot.EquipedItem))
                    {
                        isActive = false;
                    }
```
