### ISSUE TITLE
Arcane Precision feat not making weapon magic

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#1909]
The Arcane Precision feat seems be working correctly in every aspect _except_ making the selected weapon count as magical. Provided is a save file fighting the werewolf guy in the main campaign who is immune to all physical damage unless the weapon counts as magical. The fighter has a magic javelin which works however the wizard using a weapon buffed by arcane precision is still doing no damage.

https://drive.google.com/drive/folders/1bmRV3gi_NUJJbrTFYIwT_ayDVIRDx5_E?usp=sharing

**Comment by ThyWoof** [comment]
I believe we nerfed it at some point and forgot to update translations. Will check.

**Comment by lovemachine44** [comment]
Ohhh ok. English translation still reads:
"When active on a weapon, its attacks count as magical and you use your Intelligence for your attack and damage rolls."

**Comment by ThyWoof** [comment]
confirmed they're supposed to be magic but we only added the magical tag. fixed, thanks.

**Comment by lovemachine44** [comment]
Thank you.
