### ISSUE TITLE
Issue: Post Rest panel can grow too large to fit on screen

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaUnfinishedBusiness#1910]
In this example I can't level up some characters due to the extra details, Identify and Level Up buttons cropped off.
Suggest capping the number of items displayed or adding options to mod setting so select what categories are displayed.

![Clipboard01](https://user-images.githubusercontent.com/82082343/207203493-aa1ec499-5d26-4dd9-b44d-49ba85c19710.png)

**Comment by ThyWoof** [comment]
Can I have your save before rest please?

**Comment by WolffHobbitStomper** [comment]
Unfortunately I'm trying Iron Man Mode so that save is history. But I can tell you where everything comes from.
Arcane (recovery + depth) from Spell Master Wizard, multiclass with Riftwalker Warlock to pick up Blink, Arcane Precision from Feat and 2x Spell slots from class and racial (Half dark elf)

**Comment by WolffHobbitStomper** [comment]
I've made a test build to show the problem.
Just ask for  room!
NB. Change the extension back to .sav

[IM_hqdXDCmYa0S8WN6u1CMnmgM_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10215068/IM_hqdXDCmYa0S8WN6u1CMnmgM_1.zip)

**Comment by WolffHobbitStomper** [comment]
Save was made with mod ver 1.4.31.7

**Comment by EnderWiggin** [comment]
We can try adding scrollbars there (although not sure how hard it would be on our end). Ideally ask TA to add them - it would be a perfect solution

**Comment by ThyWoof** [comment]
I was considering a toggle to hide / show that section. Will ask TA as well.

**Comment by WolffHobbitStomper** [comment]
I vote for swapping the sections - seems least likely to have side effects.
