### ISSUE TITLE
Cantrip attack not working

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#1912]
After using a weapon attack the _cantrip attack_ feature on the arcane fighter subclass for the wizard isn't allowing a cantrip or even the cast option to be used at all, only a 2nd weapon attack. Unless I'm misunderstanding how it works but seems pretty straightforward.

https://drive.google.com/drive/folders/1bmRV3gi_NUJJbrTFYIwT_ayDVIRDx5_E?usp=sharing

**Comment by ThyWoof** [comment]
@dolenam317 , any ideas?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/207221496-c1db621c-3cc6-459d-ae9a-5846bfe34b85.png)
cannot reproduce.

**Comment by lovemachine44** [comment]
Not even with the save file?

**Comment by lovemachine44** [comment]
![image](https://user-images.githubusercontent.com/120349569/207222213-e8f8949b-61f7-469a-8f2f-a19b04be3b4a.png)
Just did some more testing and it seems it may only be related to defeating an enemy with 1 weapon attack which doesn't allow the followup cantrip on a different enemy. Guessing it might have something to do with the level 10 feature.
