### ISSUE TITLE
Inspiring Leader is broken

### ISSUE THREAD

**Issue by 0m1ch** [SolastaMods/SolastaUnfinishedBusiness#1913]
2nd lvl paladin with 18 charisma supposed to give +6 temp hp, but gives only +1.
https://drive.google.com/drive/folders/1E53u8lA6rIoGiXSDMkG8WyV_L5btboWb?usp=sharing
Game version 1.4.31
Mod version 1.4.31.7

**Comment by ThyWoof** [comment]
fixed on 1.4.31.8, DEV branch. Thanks.
