### ISSUE TITLE
Heavy Armor Master only reducing 2 points of damage rather than 3 points

### ISSUE THREAD

**Issue by Darkstar6996** [SolastaMods/SolastaUnfinishedBusiness#1924]
For starters, I am having a lot of fun with your mod and I very much appreciate what you guys are doing here!

Hello, I was playing a module on Solasta when I noticed that Heavy Armor Master is only reducing 2 points on damage rather than 3 points on the damage log. 

I have posted a link to the save file. It is in a module, do I need to make another save in the main game (original campaign, lost valley,etc)?

Please let me know, thank you guys very much!

**Comment by Darkstar6996** [comment]
[https://drive.google.com/file/d/1Wg4xBeqMfvtM0x2lxt7Pe6hzbbYoVRCN/view?usp=share_link](url)

**Comment by Darkstar6996** [comment]
In the save file, there are two level 1 characters with heavy armor mastery (fighter and paladin) wearing chainmail. Just to clarify, all damage reduction should be the same with all heavy armor, there wouldn't be a difference between chainmail and plate mail?

**Comment by Darkstar6996** [comment]
[https://drive.google.com/file/d/1w_jIc0MatBSMAOQSNKOlA5V6SVJS3E4D/view?usp=share_link](url)

Also, I have noticed that sometimes there is only 1 point of damage reduction, or none at all as far as I can tell (when there are two rolls [e.g. d6 +d6] for a single damage roll I did not see any damage reduction at all in the log. 

Another save is above from another module.

**Comment by EnderWiggin** [comment]
how are you determining how much damage was reduced by?

**Comment by ThyWoof** [comment]
I tested this with a damage reduction of 1000 and never got any damage applied so can confirm the Bonus decrement even works for the rolled dices. Cannot reproduce.

**Comment by Darkstar6996** [comment]
Hello guys, thank you for looking into this. I am sorry for the late response, I was away from home for a bit. 

I am using the in-game combat log and looking at the damage determination. Is this not accurate? Is the damage that is reduced not reflected in the log? Is there another way I should be checking this/ is there something I am missing?

I am confused as for some attacks it does not seem to deduct at all (1st screenshot), and then in other circumstances it is reflected but only deducts two points of damage (2nd, 3rd screenshot) as far as I can tell. I believe I may have seen a circumstance in which damage was added (I don't have a screenshot of this unfortunately at the moment)?

Thanks guys!

![image](https://user-images.githubusercontent.com/120471401/207753744-9b60e592-d2ec-453d-af37-06669f6fd4c7.png)

![image](https://user-images.githubusercontent.com/120471401/207753785-fc1c4523-ed91-41d4-8481-42fb41510297.png)

![image](https://user-images.githubusercontent.com/120471401/207753819-19fe2e67-e13a-4e98-a716-0c94c1509c01.png)
