### ISSUE TITLE
Ranged Expert and Inventor Armorer Infiltrator

### ISSUE THREAD

**Issue by halo99** [SolastaMods/SolastaUnfinishedBusiness#1927]
The Inventor subclass Armorer can choose the Infiltrator armored up mode which provides a Ranged Weapon attack.

This however does not provide the Bonus Action follow-up that is granted when using a One-Handed or Thrown weapon. Is this correct or is this due to the Lightning Launcher being a No-handed weapon?

**Comment by EnderWiggin** [comment]
Launcher is technically a no-hand weapon, yes. So it not counting for that feat is intended. Can be changed, I guess, but not sure if necessary.
