### ISSUE TITLE
NullReferenceException on failed save against spell (fireball???) out of combat

### ISSUE THREAD

**Issue by RedSec-Shay** [SolastaMods/SolastaUnfinishedBusiness#1929]
NullReferenceException on failed save against spell (fireball???) out of comabt
To reproduce - cast fireball *outside of combat" on your own team (move the caster away).
It seems to be related to HandleFailedSavingThrow_Patch on a failed save (either that or it is a race condition)

you might need to try a few times in order to reproduce since you need to fail your saves.

NullReferenceException: Object reference not set to an instance of an object
at SolastaUnfinishedBusiness.Patches.GameLocationBattleManagerPatcher+HandleFailedSavingThrow_Patch+d__4.MoveNext () [0x003da] in <5f2800130e9e4aac97bbd3f8fae74574>:0
at TA.Coroutine.Run () [0x00019] in <158c69421105427a91c61fc907c04fef>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:Update()

**Comment by ThyWoof** [comment]
fixed on DEV branch.
