### ISSUE TITLE
Arcane Fighter "arcane weapon" feature

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#1932]
![image](https://user-images.githubusercontent.com/120349569/207466942-78d38d35-9502-456c-a44a-46e59fc50bd4.png)

The precision feats still grant the old power named "X Weapon" that **doesn't** work correctly in addition to the new version named "X Precision" which **does** work correctly.

Also it should be noted that anyone with an existing character using a precision feat will need to RESPEC, otherwise only the old version of the power is available to use.

**Comment by Graham198011** [comment]
hmm i cant replicate that error with arcane precision, please upload your save for the modders to take a look.

**Comment by dolenam317** [comment]
Arcane weapon is level 2 feature of arcane fighter ? What was wrong with it ?

**Comment by lovemachine44** [comment]
Yes that was my mistake. The bug had nothing to do with the feat but rather the arcane fighter feature. The arcane fighter version is still working the way the feat version did where it's still not counting the weapon as magical.

**Comment by ThyWoof** [comment]
It's set to magical on DEV. Closing this one.
