### ISSUE TITLE
Grey Dwarf Stone Strength 

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaUnfinishedBusiness#1933]
The Stone Strength ability is supposed to only apply to melee weapons.
I have observed it being applied to spells (Guiding Bolt) and ranged weapons (Crossbow)

**Comment by ThyWoof** [comment]
Very strange. Official game engine has a property to set the scope to melee strength weapon. Will have to check their code to see what’s going on.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/003eac94b16fea1d94317509c3de54f410034634/SolastaUnfinishedBusiness/Races/GrayDwarf.cs#L96

**Comment by ThyWoof** [comment]
fixed on DEV branch. you won't see a message on log anymore but an additional dice on weapon.
![image](https://user-images.githubusercontent.com/13087646/207515299-21d349ec-f3ad-4077-a61f-2d475856357d.png)

no dice on finesse.
![image](https://user-images.githubusercontent.com/13087646/207515340-b4661f68-cfec-47dd-be5e-7ab32b615b05.png)
