### ISSUE TITLE
Racial spells on also on class spell list

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaUnfinishedBusiness#1938]
When leveling up a class that has auto prepared spells (eg. sorcerer) and you have been granted a racial spell that is also on your class spell list you can gain a free spell known.

eg. Dark elf sorcerer
At Level 3 you get Faerie Fire & at Level 5 you get Darkness as racial spells.
Up to level 4 you didn't learn Darkness as a class spell.
When leveling to level 5 you can choose to unlearn Darkness and effectively gain 2 spells for that level.
You still have the racial version of Darkness.
This doesn't happen with Faerie Fire as it's not on the sorcerer class list.

**Comment by ThyWoof** [comment]
fixed. Thanks.
![image](https://user-images.githubusercontent.com/13087646/207603287-05d7a6e7-45ec-4ce9-9bb6-8d4d99f23af5.png)
