### ISSUE TITLE
Flexible Races buged in 1.4.31.10

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaUnfinishedBusiness#1943]
For all races except human when "Enable Flexible Races" is enabled during character creation I'm getting both the fixed racial bonuses in addition to the flexible modifiers for a double dose of goodness. 
I thought I was rolling really well ;)

**Comment by Graham198011** [comment]
hmmm did some thorough checking for this. It triggers on all default races that did not have flexi stats to begin with. so half orc gets their default +2 str and +1 con and the variant boni, for half elf and variant half elves it locks them into thier default un modified stats. so only +2 cha and 2 flexi boost. humans remain as their normal variant.

**Comment by WolffHobbitStomper** [comment]
No save as this is observed in character creation.
Races I tried Dragonborn, Hill Dwarf, High Elf, Halfling, Kobold, Dark Elf, Grey Dwarf and they are all showing the same behaviour. 
See the example
![CharCreation](https://user-images.githubusercontent.com/82082343/207742208-4334812d-78a0-4723-8cb0-0b79e6e93d97.png)

**Comment by Graham198011** [comment]
its a funny bug thats for sure.

**Comment by ThyWoof** [comment]
fixed on dev.
