### ISSUE TITLE
Unable to learn Spells known from another class when leveling up

### ISSUE THREAD

**Issue by ShavesInTheCaves** [SolastaMods/SolastaUnfinishedBusiness#1944]
![image_2022-12-15_101321944](https://user-images.githubusercontent.com/120614370/207756308-e38cf502-9dc3-4ca4-a412-a453b5919be3.png)

Life Cleric 1 / Lore Bard 3

I cant learn Enhance Ability (and other spells shared between the classes) on my 3rd level of bard. I have the option enabled for "can learn cantrips and spells learned from other classes" 

edit: this is on version 1.4.31.10

**Comment by WolffHobbitStomper** [comment]
I have an observation that may be related.
On my (non multiclass) mage leveling from from 1-> 2 or 2->3 I see that any spells I learned at lower levels are indicated as "Multiclass" in the leveling screen.
But when viewed via the inventory/ class spells page they appear without the multiclass indicator.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/207799625-347f9dc0-1440-4e89-a1f1-e1ed96f8fff8.png)
not a bug. I can learn Enhance Ability on Bard 3.

**Comment by Tichrimo** [comment]
![image](https://user-images.githubusercontent.com/88252772/209456673-54158fc7-ac00-469a-844d-a08d114908e7.png)
This is on a Cleric 1 / Sorcerer 3 in version 1.4.32.7.  Any idea how you are able to work around it while the OP and I cannot?
