### ISSUE TITLE
Unable to load save game after the 10th Dec

### ISSUE THREAD

**Issue by 0uthouse** [SolastaMods/SolastaUnfinishedBusiness#1951]
Objective - load existing main campaign game. 
Steps
1 - Start with fully update 1.4.32 Unfinished Business
2 -click either - Continue current campaign or Load Game 

Results: Error: Loading Failed "The game could not load properly. Please verify the integrity of your game files" 

Verification Steps: 
1. Verified Integrity of files, all are fine. 
2. Loaded old save from last week - Results: worked fine
3. Tested each save to see how current I could get.  - Results: closest i could get was 12/10/22, anything after that fails to load.

**Comment by Graham198011** [comment]
TA also updated solasta so the issue may be with them as i have no issues loading save games. Just to be sure roll back your ub version to an earlier version here https://github.com/SolastaMods/SolastaUnfinishedBusiness/releases 
and make sure you have the latest version of mod manager. here 
https://www.nexusmods.com/site/mods/21

If the problem persists, please upload a save file and the modders will take a look.

Thanks

**Comment by 0uthouse** [comment]
Will do, appreciate the quick follow up!

**Comment by ThyWoof** [comment]
Which heroes do you have on your save? Races, classes and levels please. We also need your save file which you can ZIP and attach to an answer.

**Comment by 0uthouse** [comment]
I was tinkering around with Inventor, so almost the whole party had a splash or fully Invent.  Specifically playing with return weapon feat of the class, Using javelins, spears, axes and daggers. 

Classes:
1 Thief/ Invent
2 Inventor
1 fighter / invent
1 battle - cleric
1 shock - wizard 

Races:
4 Human, except Fighter Invent is an half orc, 1 straight inventor is a kobold

**Comment by 0uthouse** [comment]
[Inventors Guild - Solasta Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10250700/Inventors.Guild.-.Solasta.Save.zip)

**Comment by 0uthouse** [comment]
OK I saw the comment in the other issue specifically about Inventor, which I obviously am.  I'll try to rollback to previous version respec and then update.

**Comment by ThyWoof** [comment]
We got confirmation from the other user that using an older version to RESPEC all heroes to 1st level and then upgrade fixed the issue. Closing this. Sorry for the inconvenience.
