### ISSUE TITLE
Corrupted savefiles

### ISSUE THREAD

**Issue by Bislacco** [SolastaMods/SolastaUnfinishedBusiness#1952]
![Immagine](https://user-images.githubusercontent.com/1644153/208077755-967b2e5d-0268-47c6-9744-9bbe1683ff81.png)

I updated game and mod to the latest version, and this happened. I'm 30 hours into a campaign so I would just roll back to the last version if it is not solvable. Could it be because I used RESPEC on 2 characters? Or can it be something else?

[FILES.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10244869/FILES.zip)

**Comment by Graham198011** [comment]
TA also updated solasta so the issue may be with them as i have no issues loading save games. Just to be sure roll back your ub version to an earlier version here https://github.com/SolastaMods/SolastaUnfinishedBusiness/releases
and make sure you have the latest version of mod manager. here
https://www.nexusmods.com/site/mods/21

If the problem persists, please upload a save file and the modders will take a look.

Thanks

**Comment by Bislacco** [comment]
Game is still updated (didn't find the old version) but tried with the rollback of UB.
Version 1.4.30.7 and everything work, if I update to 1.4.32 it brakes all old saves :(

I already uploaded a savefile and all characters used as requested in the FAQs

**Comment by ThyWoof** [comment]
I won’t be able to check that until tonight. Do you have an inventor on that save? If so I suggest you RESPEC off inventor using older version, upgrade, RESPEC into inventor again

**Comment by ThyWoof** [comment]
Also if you took any improved pact weapon with Warlocks. These are the 2 we had to change blueprint names over the last update.

**Comment by Bislacco** [comment]
No inventor, and a warlock but with pact of tome. No problem, I can wait, Great work guys, thanks even only for replying!

**Comment by Bislacco** [comment]
I rolled back, tried RESPEC the rogue only but disn't work, then used it on every character (all 6 into female dwarf barbarian to be sure) and it worked.
I updated UB to 1.32 and then used RESPEC on everyone again to get back my team. Now it all works fine!
