### ISSUE TITLE
revanant great sword and rage interaction

### ISSUE THREAD

**Issue by Graham198011** [SolastaMods/SolastaUnfinishedBusiness#1963]
https://drive.google.com/file/d/1CSonpZ2zeavjJ1rx2sL-ainz54FwIpwh/view?usp=share_link
up to date on mod and main game. Rage damage does not appear to be applying while using revanant greatsword and dexterity. scrap that, doesnt work with other weapons, also a spirit of the bear barbarian, i shall try again without the revenant feat to see if its that or just spirit barbarian

**Comment by ThyWoof** [comment]
Rage won’t apply if you use your DEX mod instead of STR.
