### ISSUE TITLE
Grenadier Int based attacks not working with Elven Accuracy

### ISSUE THREAD

**Issue by night44** [SolastaMods/SolastaUnfinishedBusiness#1972]
I have a Half High Elf Grenadier Inventor with Elven Accuracy. Even when attacking with Advantage, none of his cantrips, spells, or Precise bombs reroll like they should. 

I see that Elven Accuracy does indeed work correctly for multiple other characters though.

**Comment by night44** [comment]
[Ruins.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10254321/Ruins.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/208313533-7efeca5b-a5d5-46c4-9f58-51bfa73cf6d6.png)
I cannot find a Grenadier on this save with Elven Accuracy.

**Comment by night44** [comment]
![grenadier](https://user-images.githubusercontent.com/98411902/208314657-74f6070e-ec50-4f6b-bf7f-8de65575f4b9.jpg)

He does, this is from that save. It's "Eleven Precision" here.

**Comment by ThyWoof** [comment]
Given that I opened the same save and couldn’t find it please RESPEC

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/208315452-d6a6f0b8-c77d-46d3-b07e-25aed29b336e.png)
did a 2nd time just in case. I can see the hero has the Trained Feats in the collection but still not displaying here. Only suggestion again is a RESPEC.

**Comment by night44** [comment]
Did respec, still not working

[Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10254504/Test.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/208316486-8d51ddc8-03d2-45ca-aa0b-91a506628ff8.png)
this is very strange. Please share your settings.xml as well.

**Comment by night44** [comment]
[Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10254566/Settings.zip)

Mod and game are up to date. Both Grenadiers (the original from "Ruins" file and this respecced one from "Test") also have the improved crit Feats, and those work and have always worked. So I know both character have Feats and the majority of Feats are working... just not Elven Accuracy for either one.

**Comment by ThyWoof** [comment]
@EnderWiggin , we did some internal tests and were able to finally confirm this is indeed not working. Took a quick look at the code and all that comes to mind is a wrong interaction with Mirror Image patches as they are on the same code sequence in game: RollMagicAttack > RollAttack > RollDie (where we patch Elven).

**Comment by ThyWoof** [comment]
fixed on DEV branch.
