### ISSUE TITLE
Inventor Mind Sharpener not working on Druid ally

### ISSUE THREAD

**Issue by night44** [SolastaMods/SolastaUnfinishedBusiness#1973]
My Inventor used Mind Sharpener on my Druid's Druid Armor and I see the icon there. But when my Druid is channeling Flame Blade and gets attacked for under 10 damage, he has to roll for Concentration and doesn't get advantage on that roll.

**Comment by ThyWoof** [comment]
For how long do you have these heroes? Given that I wasn’t able to find Elven Accuracy on your inventor for the other bug, would you please fully RESPEC all heroes and test again?

**Comment by ThyWoof** [comment]
There were significant changes on inventor that will only be considered after a full RESPEC.

**Comment by night44** [comment]
I've only been playing this one about 3 days. And that Inventor does have Elven Accuracy (Precision), I posted a screenshot of it from that save.

**Comment by ThyWoof** [comment]
@EnderWiggin , FYI. Can you give a hand here?

**Comment by night44** [comment]
Did respec, still not working

[Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10254507/Test.zip)

**Comment by ThyWoof** [comment]
Sorry it’s taking longer to fix this. After latest breaking changes I believe above save won’t open anymore. Can you test it again on latest release and share a new save if still an issue?

**Comment by night44** [comment]
Might take a day or two to get to it but yeah.

**Comment by night44** [comment]
[test2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10297394/test2.zip)

New game, newly created Inventor and Druid and it still doesn't seem to work.

**Comment by ThyWoof** [comment]
finally fixed. to be on next release.
![image](https://user-images.githubusercontent.com/13087646/210459064-4ab0065c-67ef-4f83-981c-34274c8175a1.png)
