### ISSUE TITLE
Way of the Distant Hand Stunning Arrows not working

### ISSUE THREAD

**Issue by night44** [SolastaMods/SolastaUnfinishedBusiness#1974]
My Way of the Distant Hand Monk has Stunning Arrows, yet they cannot be activated under any circumstances I can find. I'm using the Stunning Blow modal because I don't see another one, but the ability never seems to work or consume Ki.

**Comment by night44** [comment]
[Ruins.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10254325/Ruins.zip)

**Comment by ThyWoof** [comment]
@EnderWiggin , FYI. Can you give a hand here?

**Comment by ThyWoof** [comment]
fixed on DEV branch.
