### ISSUE TITLE
Additional charges feature of Grenadier freezes the game while used in multiplayer

### ISSUE THREAD

**Issue by yauaustin202** [SolastaMods/SolastaUnfinishedBusiness#1984]
Solasta version 1.43.2 Unfinished Business version 1.4.32.2
When using the concentrated bombs of Grenadier Inventor (Aka using multiple charges) while in multiplayer, the game will freeze and nobody can interact or progress the game.

We do not have a log file because the game just permanently hangs as the inventor loses their HUD
(note: this function works perfectly fine while in singleplayer)

[Character and Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10260231/Character.and.Save.zip)

**Comment by ThyWoof** [comment]
We really need logs. Next time it happens, Alt-F4 to close the game. Navigate to folder where logs are (check hints on wiki) and get both player.log and player-previous.log. Even better if you can get these from all players machines.

Thanks.

**Comment by yauaustin202** [comment]
Apologies, it took a while for me to figure out how to grab player logs
Here they are:
[Playerlog.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10270343/Playerlog.zip)

**Comment by ThyWoof** [comment]
@EnderWiggin , FYI

```
NullReferenceException: Object reference not set to an instance of an object
  at CharacterActionUsePower.GetBaseDefinition () [0x00000] in <1416e8444d2d4395ac5b8761ff526a8d>:0 
  at SolastaUnfinishedBusiness.Patches.CharacterActionMagicEffectPatcher+ExecuteImpl_Patch.Prefix (CharacterActionMagicEffect __instance) [0x00000] in <9f84106d85284bc6b7adc73ba42e6610>:0 
  at (wrapper dynamic-method) CharacterActionMagicEffect.CharacterActionMagicEffect.ExecuteImpl_Patch2(CharacterActionMagicEffect)
  at CharacterAction+<Execute>d__96.MoveNext () [0x0010f] in <1416e8444d2d4395ac5b8761ff526a8d>:0 
  at SolastaUnfinishedBusiness.Patches.CharacterActionPatcher+Execute_Patch+<Postfix>d__0.MoveNext () [0x0003a] in <9f84106d85284bc6b7adc73ba42e6610>:0 
  at TA.Coroutine.Run () [0x00019] in <1416e8444d2d4395ac5b8761ff526a8d>:0 
```

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10271785/SolastaUnfinishedBusiness.zip)

@yauaustin202 , can you please test this one?

**Comment by ThyWoof** [comment]
@EnderWiggin , I added more protection [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/f9a0917c5cba684255244bbdadd1000d2114e990) but not sure why __instance would ever be null here. Sounds like an original MP bug.

**Comment by yauaustin202** [comment]
![image](https://user-images.githubusercontent.com/121026382/208832111-548d8463-edf0-45ac-8afe-996d95086b6e.png)
Sadly it didn't work.

Here's the logs, still same character and save file.
[Log.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10274874/Log.zip)

**Comment by EnderWiggin** [comment]
Sent PR that _should_ fix this issue
