### ISSUE TITLE
Spiritual Pact Weapon (Soulblade 6th level feature) attack bonus not applying

### ISSUE THREAD

**Issue by jeftahx** [SolastaMods/SolastaUnfinishedBusiness#1988]
https://cdn.discordapp.com/attachments/774339139444670494/1054449367597187092/image.png

Spiritual pact weapon is attacking foe with a fixed +2 bonus to attack, even though it lists all the other sources to attack bonus.

To reproduce, simply attack with the spiritual pact weapon (already summoned in the save).

Save is right next to an enemy to easily reproduce.

[Spiritual Pact Weapon Issues.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10261536/Spiritual.Pact.Weapon.Issues.zip)

**Comment by ThyWoof** [comment]
This is turning me nuts…

**Comment by ThyWoof** [comment]
tooltip is indeed incorrect. fixed on DEV branch.
