### ISSUE TITLE
inventor melee feats dont affect lightning gauntlet

### ISSUE THREAD

**Issue by mrghrin** [SolastaMods/SolastaUnfinishedBusiness#2005]
title

**Comment by ThyWoof** [comment]
Please reopen the ticket with proper context and a save.

**Comment by mrghrin** [comment]
literlly 0 reason to. I asked in the nexus page if melee feats work with the lightning and thunder gauntlet and you said yes, which was a lie
It's not hard to check if the game sees the gloves as a weapon or not, which it doesn't. When the gloves are equipped there's also unarmed strike as an option which makes me think the game reads the gloves as literally nothing. Just add a weapon with placeholder icon (which you dont need since you already have a 2d icon) into the melee slot as if it was Flame Blade or something similar so it's not just an empty slot. Don't need a physical model either though it would be a little nice if there was a lightning-type effect around the hand with the gauntlets active

**Comment by mrghrin** [comment]
Context: I leveled to level 2 with the feats setting active for feats every 2 levels. I took Dueling feat with the thunder gauntlet. I went to next combat with both the feat and the gauntlet active. I hit the enemy and didn't get +2 damage

**Comment by ThyWoof** [comment]
` you said yes, which was a lie`, seriously? Please stop using the mod.

**Comment by mrghrin** [comment]
Didn't even bother to address what I said, typical
