### ISSUE TITLE
Path of the Spirits, Barbarian. There's a Bug with the 3rd Level Feature, Wolf Spirit Condition, and "Power".

### ISSUE THREAD

**Issue by FabricateDElysiuM** [SolastaMods/SolastaUnfinishedBusiness#2006]
So, I'd found an issue, but this time it's with the Path of the Spirits, Barbarian. 
The Wolf Spirit Animal Pact thing or whatever it was called, lol, that you could choose as your 3rd Level Feature, the Condition only applies for 1 round/turn only, and not 10 rounds/turns, and it disabled itself once it became my Barbarian's turn again. A little birdie told me something, (AKA, Zappa, but we don't talk about that, 😉) but pretty much, it just ended the Wolf Spirit Condition on my Barbarian's next turn, when it's the "Power" that's supposed to end on my next turn, not the Condition, since the Condition should last 10 turns, (AKA, 1 Minute.) but based off of what Zappa said, the "Power" should only last until your next turn. (The "Power" that grants the Wolf Spirit Condition to your allies.) So, I'm assuming that once the Wolf Spirit "Power" ends on your next turn, it ends up disabling the Condition that applies to your allies, too. Kind of like how if you break or cancel a Concentration Spell, it ends the effects of it, too. I have a picture, but no clue if it explains/shows much of the issue.

![image](https://user-images.githubusercontent.com/121084997/208796526-5f687a4e-f558-4330-b983-fdbb60dea7ff.png)

It also seems like @anergyboy, from Discord, is having a similar issue? Image is down below.

![image](https://user-images.githubusercontent.com/121084997/208796867-bfd19a86-4aee-4aff-ba01-65215f4e15bc.png)

Here's another Image below, if this explains the issue more in-depth.

![image](https://user-images.githubusercontent.com/121084997/208806749-a286b6bc-10da-49c5-9585-72f951d1a3a9.png)

**Comment by ThyWoof** [comment]
fixed on DEV branch and also changed behavior a bit:

The spirit of the wolf makes you a leader of hunters. Any friend within 15 feet that can see you raging at the end of your turn will have advantage on melee attack rolls during their turn.

**Comment by ThyWoof** [comment]
.
