### ISSUE TITLE
Hero stats tooltip vanishes and doesn't record wildshaped characters 

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2007]
I don't know if this is just the base game's fault. But the Hero statistics tooltip disappears when wildshaped and doesn't seem to track any of the stats. Are they being recorded separately or not at all?

**Comment by ThyWoof** [comment]
Screenshots and saves always help.

**Comment by ViridianDoom** [comment]
![Untitled2](https://user-images.githubusercontent.com/35788909/208830706-27b1a175-dfd3-4ca8-a41d-adfcbf8c2c0f.png)
 It updates in human form, doesn't when transformed.

**Comment by ThyWoof** [comment]
By design.
