### ISSUE TITLE
Spell Shield Fighter Level 7 Feature not working with Cantrips?

### ISSUE THREAD

**Issue by Zenbanner** [SolastaMods/SolastaUnfinishedBusiness#2008]
The War Magic Feature says that you can use your bonus action to attack using the weapon in your main hand after casting a spell. I tried with Scorching ray, and it works properly. Similarly if you use shield as a reaction. However, when I use cantrips (Resonating strike, Sunlit Blade, or even Light) the Bonus action attack does not become available.  Is this intended? 

Here is the save. Using the modded campaign "Champion of Ages"

https://drive.google.com/file/d/10Eds9tLd05aXjD9LzPSGyMldeU_v55x4/view?usp=share_link

**Comment by Graham198011** [comment]
I have done some checking. i think you have misunderstood how the level 7 feature works. the cantrips cant be cast in place of one fo your attacks, so you can attack then cast a cantrip or cast a cantrip then attack. the other feature lets you just cast a leveled spell then attack using a bonus action.

**Comment by Zenbanner** [comment]
> I have done some checking. i think you have misunderstood how the level 7 feature works. the cantrips cant be cast in place of one fo your attacks, so you can attack then cast a cantrip or cast a cantrip then attack. the other feature lets you just cast a leveled spell then attack using a bonus action.

Alright, figured I misunderstood. My apologies.
