### ISSUE TITLE
Wildshaping with any multi class causes vision based racial abilities/invocations to disappear

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2009]
~~Tested it and in the dark my character was hitting fine, but because of wild shape they now get disadvantage because of the dark. It should be working when transformed.~~

Okay I did some investigating it's not just Devil's Sight, but Dark vision too. I think the problem is being caused by multi classing.

The problem is when you wild shape with multi classing you will lose Dark vision and maybe any racial ability you have. (I can't check in game because the character sheet gets disabled when you are wildshaped) This might extend to other racial abilities too, but I'm not sure what I can test to prove it.

**Comment by ThyWoof** [comment]
Do you have a save I can test?

**Comment by ViridianDoom** [comment]
[bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10279957/bug.zip)

**Comment by ThyWoof** [comment]
I also need your JSON user location file in order to be able to open above save.

**Comment by ViridianDoom** [comment]
Where do I find that?

**Comment by ViridianDoom** [comment]
Okay I did some investigating it's not just Devil's Sight, but Dark vision too. I think the problem is being caused by multi classing.

The problem is when you wild shape with multi classing you will lose Dark vision and maybe any racial ability you have. (I can't check in game because the character sheet gets disabled when you are wildshaped) This might extend to other racial abilities too, but I'm not sure what I can test to prove it.

**Comment by ViridianDoom** [comment]
New thread
