### ISSUE TITLE
Poison Skin feat, has no name in combat log and DC 0

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2010]
No name and DC is 0? Not sure what it's actually supposed to be

![Untitled](https://user-images.githubusercontent.com/35788909/208829732-2b63a06b-94fc-401e-954d-92dba98a21b4.png)

**Comment by ThyWoof** [comment]
Do you have a save I can use to test?

**Comment by ViridianDoom** [comment]
[bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10279955/bug.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/209026312-7be1aa6e-3746-481b-b8b6-c7cf5efcfaee.png)
fixed on DEV branch.
