### ISSUE TITLE
Unity Mod Manager does not open after UB uninstall/reinstall

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#2025]
I had UB working fine until I uninstalled to play with an unmodded buddy. The log showed my reinstall was clean and the status OK. The .json was loaded into the Mods folder. However, when I start the game, the Unity Mod Manager overlay does not appear and the game does not have the mods. As best I can tell, Unity is properly installed in the Managed and Streaming Assets folders.

Here is the Unity log:
[Manager] Initialize.
[Manager] Version: 0.25.2.0.
[Manager] OS: Microsoft Windows NT 10.0.19044.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] Mods path: C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods.
[Manager] Injection successful.
[Manager] Parsing mods.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.4.32.2'. Loading.
[SolastaUnfinishedBusiness] Active.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.
[Manager] Spawning.
[Manager] Checking updates.
[SolastaUnfinishedBusiness] 2083 en translation terms loaded.
[SolastaUnfinishedBusiness] 0 en translation fixes loaded.
[SolastaUnfinishedBusiness] enabled.
[SolastaUnfinishedBusiness] Game Created
[Manager] Destroying when exit.

Any ideas on how to fix this or where to go for help?

**Comment by ThyWoof** [comment]
Mod seems to be loading correctly. Have you tried CTRL-F10?

**Comment by charlesewatkins** [comment]
Thanks, Paul. CTRL-F10 has no effect. The problem seems to be that the 
mechanism Unity uses to place the overlay on the Solasta startup screen 
is not working. It worked fine until I did the uninstall/reinstall of 
UB. The .json is in the Mods folder, and the Solasta_Data folder 
contains Unity files in Managed and StreamingAssets.

My buddy had this problem when he went to install UB. CE2 was working 
fine, but when he installed UB the Unity overlay stopped appearing. 
Something about the UB installation is messing up UMM. Any idea what 
might be the problem?

Clear skies, my friend
Charles Watkins

**Comment by ThyWoof** [comment]
I suggest you to fully delete anything under the Mods folder (under game folder).

Download the latest binary release, open the zip and drag the SolastaUnfinishedBusiness folder in there.

You might also need to run UMM again and reinstall it in the game. Prefer doorproxy as it’s more resilient on game updates vs assembly.

**Comment by charlesewatkins** [comment]
I deleted all the Unity files in Solasta_Data and did a complete reinstall of UMM. That did the trick.

Stay in the light, my friends
