### ISSUE TITLE
The Improved Flurry of Blows, from Freedom Monk, and the Dash version of Step of the Wind, doesn't trigger the "Freedom" Condition from the Mobile Feat.

### ISSUE THREAD

**Issue by FabricateDElysiuM** [SolastaMods/SolastaUnfinishedBusiness#2030]
I'd noticed that when you're using the Improved Flurry of Blows, from Way of Freedom Monk, it doesn't trigger the "No movement restrictions while Dashing" part of the Mobile Feat, AKA, the "Freedom" Condition. Same for when using the Step of the Wind, Dash version, from Monk. It only seemed to work when you're using the Main Action for Dashing, but I haven't tried Cunning Action, yet, but I'm assuming it works for it, but just not the Monk Powers. The only problem that I'd noticed is that Dashing either by using the Improved Flurry of Blows, from Freedom Monk, and even by using the Dash version of Step of the Wind, it doesn't trigger the "Freedom" Condition. It seems like it only triggers it by using the actual Dash Action. I'm assuming it's cause of Step of the Wind/Improved Flurry of Blows, it just grants you double Movement "Points", but the Dash Action seems to have these weird Blue "Sectors", that separate them between the regular movement Grid, and the Dash movement Grid, if that makes sense? 🤣 And it seems like you only gain/trigger the "Freedom" Condition upon entering the "Dashing Side" of the movement Grid. If possible, or if it isn't too much of a hassle: Just make it so that when you're using the Improved Flurry of Blows Power, while also when you're using the Dash version of the Step of the Wind Power, it grants you/triggers the "Freedom" Condition upon the first time you activate those, Powers. Since it'll still consume your Bonus Action by doing so, so I don't think it would be too overpowered/cause any issues. If it does become modified in this way, I think it would be great!

![image](https://user-images.githubusercontent.com/121084997/209299511-dd3c4351-cf0c-43be-b44f-3e1e32c609e3.png)

(I don't know if the above image shows that much of what happened, but I hope it does, lol.)

By using the Mobile Feat, me gaining/triggering the "Freedom" Condition, was from me actually activating the Dash from the Main Action, not by me using the Improved Flurry of Blows Power, or by me using the Dash version of Step of the Wind. The above image is me showcasing the Combat Log, in that image, it shows that it ONLY triggers the "Freedom" Condition by using the actual Dash Action, when it's also supposed to work with the Monk Powers.

**Comment by ThyWoof** [comment]
Do you have a save?

**Comment by FabricateDElysiuM** [comment]
> Do you have a save?

Not at the moment, but I could make one. That image was from an old testing Save File that I'd made awhile back, but I'll have to make a new one since it's probably broken from the new Updates.

**Comment by Graham198011** [comment]
> Do you have a save?

https://drive.google.com/file/d/1bJyCKomWh2v4kQBLB-mzXzSK1U29DNeF/view?usp=share_link
you will need ultimate dungeon to test the save but the char is here 
https://drive.google.com/file/d/19zU16Z5LvZZVzhjG68uV7Bm9jbAWNZBf/view?usp=share_link

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/209420444-2a6dcd25-1df5-43b2-b5df-e35c2b19f9e0.png)
seems to be fixed.

**Comment by FabricateDElysiuM** [comment]
> ![image](https://user-images.githubusercontent.com/13087646/209420444-2a6dcd25-1df5-43b2-b5df-e35c2b19f9e0.png) seems to be fixed.

Sorry if this is hard to explain, since I'd seen y'all talking about the issue on Discord, too. (I'd seen you guys having some issues "deciphering" what I'm talking about, lol.) It's all good.
I wasn't talking about the additional Disengage Action, because that seems to be working as intended now. Because originally, when the Feat was first released, it never granted you an additional/extra Disengage Action, it just allowed you to use your Bonus Action to do so, but now it actually grants an additional/extra Disengage Action, which is good! 👍 The issue that I'm having is that the "Freedom" Condition, the Condition that you'd obtain from using the Dash Action, isn't working as intended. It doesn't work when you're using any of these Powers, the ones called Improved - Flurry of Blows, (From the Way of Freedom, Monk Subclass.) and the Dash version of Step of the Wind. The problem is that when you're using the actual Dash Action, it only triggers the "Freedom" Condition on the "Dashing Side" of the Movement Grid/Blue Section, but since the Monk Powers don't have a separate Movement Grid/Blue Section for Dashing, but instead they just grant you double Movement "Points", which doesn't trigger/grant you the "Freedom" Condition, when it's supposed to do so, since it claims that it does the "Dash Action" in its Feature Description. Look below for more information. I hope this helps!

![image](https://user-images.githubusercontent.com/121084997/209423608-9f6ac611-6429-4ece-bd72-6c41fec26576.png)

![image](https://user-images.githubusercontent.com/121084997/209423635-481aa532-9a26-4aad-a768-e8f4b5707190.png)

Btw, when I'd mentioned the "Freedom" Condition, I'm talking about this specific mention of the Mobile Feat's Description, the "Movement Restriction" one.

![image](https://user-images.githubusercontent.com/121084997/209423283-5d3b0fb0-8bf8-4db3-a093-348b93575bbf.png)

**Comment by FabricateDElysiuM** [comment]
> > Do you have a save?
> 
> https://drive.google.com/file/d/1bJyCKomWh2v4kQBLB-mzXzSK1U29DNeF/view?usp=share_link you will need ultimate dungeon to test the save but the char is here https://drive.google.com/file/d/19zU16Z5LvZZVzhjG68uV7Bm9jbAWNZBf/view?usp=share_link

Btw, thank you for posting a Save for me. It made it a lot easier for me, since I didn't feel like getting on at the time Zappa asked, lol.
