### ISSUE TITLE
Can't use bonus attack Unarmed Strikes when Wildshaped multi-classed with Monk

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2036]
Not sure if bug or incorrect design, but far as I'm aware, According to PHB:

The description of the druid's Wild Shape feature says, in part (PHB, p. 67)

"_You retain the benefit of any features from your class, race, or other source and can use them if the new form is physically capable of doing so._"
"_Melee Attacks (p. 195). The rule on unarmed strikes should read as follows: “Instead of using a weapon to make a melee weapon attack, you can use an unarmed strike: a punch, kick, head-butt, or similar forceful blow (none of which count as weapons)._ ”

So I think in the scenario of being wildshaped, the user should be able to use Flurry of Blows to get 2 bonus attack Unarmed Strikes. But it's not available:
![monkwolf](https://user-images.githubusercontent.com/35788909/209418744-e8835aec-36e5-404b-9864-d49e084ca514.png)

**Comment by ThyWoof** [comment]
Unfortunately TA didn't do a good Druid implementation and some scenarios are very hard to achieve.
