### ISSUE TITLE
No way to consume Warlock’s pact slots with Sorcerer’s flexible casting

### ISSUE THREAD

**Issue by DylanRJohnston** [SolastaMods/SolastaUnfinishedBusiness#2041]
There doesn’t appear to be any way with the UI to select a Warlock Pact Slot when using the Sorcerer’s Flexible Casting class ability. I usually like to burn any pact slots left into sorcerer points before short resting but that only works if I’ve already spent all the sorcerer spell slots of the same level.

**Comment by DylanRJohnston** [comment]
This used to work pre Inner Strength where Warlock Pact Slots would always be consumed before Sorcerer Spell Slots

**Comment by ThyWoof** [comment]
Please read all the info on Mod UI after you enable MC. This scenario is covered and there is a tip on how.

**Comment by DylanRJohnston** [comment]
Apologies, I did read all of it before posting. I found the part talking about using Shift Click when casting to invert the default behaviour of Sorcerer Spells / Warlock Spells consuming their respective slots but I couldn’t find anything about Flexible Casting. I’ll take another read through.

**Comment by ThyWoof** [comment]
It’s the same for any place that consumes slots. Only ensure that you keep shift pressed until you see effect starting.
