### ISSUE TITLE
Power Attack not working on 1.4.32.8

### ISSUE THREAD

**Issue by Fabio-32** [SolastaMods/SolastaUnfinishedBusiness#2050]
As stated in the title, power attack does not work for me with this version. Dead Eye works fine tho.

**Comment by ThyWoof** [comment]
No save?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/209477969-ed797790-04ae-4b89-96ca-7930c019624e.png)
There is a lot of frustration when we get issues without saves or screenshots. We end up putting time we don't have to confirm it's indeed working.

**Comment by Fabio-32** [comment]
I'm glad that the issue is on my end only, still it was working like a charm on the previous version. here are some screenshots, i'll provide you the save.

![Immagine 2022-12-25 190946](https://user-images.githubusercontent.com/82377414/209478293-a6f7e207-891e-480e-b4f2-faef5ed78713.png)

![Immagine 2022-12-25 191132](https://user-images.githubusercontent.com/82377414/209478296-d3a4bd64-66fe-4f11-b3d8-d2544ffd763d.png)

![Immagine 2022-12-25 191201](https://user-images.githubusercontent.com/82377414/209478300-895f6b72-7f75-4a97-9f62-edcb321c3a0f.png)

![Immagine 2022-12-25 191248](https://user-images.githubusercontent.com/82377414/209478307-f39825d8-fa02-4384-9b83-cb89f269ed72.png)

**Comment by Fabio-32** [comment]
[Partita 1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10300471/Partita.1.zip)

**Comment by Fabio-32** [comment]
rolling back to the previous version fixes it

![Immagine 2022-12-25 193059](https://user-images.githubusercontent.com/82377414/209478779-0981d130-5cde-4d8a-bb86-17ee13e5d736.png)
