### ISSUE TITLE
class spells not showing up and mobile feat not working 1.4.32.8

### ISSUE THREAD

**Issue by WillofTheGold** [SolastaMods/SolastaUnfinishedBusiness#2051]
the game version is 1.4.32 and the mod is 1.4.32.8
when making a new character none of the spells the class would normally get in the game shows up however all the spells when selected in the spells section of the mod will show up for it instead. 

also it seems the mobile feat doesn't work as intended. when attacking with melee attacks the option to disengage doesn't show up anymore however the speed increase still does work.

**Comment by ThyWoof** [comment]
No save?

**Comment by WillofTheGold** [comment]
i see one second for the saves and screenshots, also i found that it happens when i have modui/&modui/&allowassigningofficalspells option on for the spells dispersing and only showing what you have marked off. also note i used both existing characters and brand new characters that I made with the mobile feat.

**Comment by WillofTheGold** [comment]
[Saves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10300377/Saves.zip)
![20221225114106_1](https://user-images.githubusercontent.com/121395191/209476178-31e391b8-2389-43dd-bc3c-c49e2211c6bb.jpg)
![20221225114153_1](https://user-images.githubusercontent.com/121395191/209476179-bf574c84-3f8f-48c8-a702-5debfb449a57.jpg)
![20221225115248_1](https://user-images.githubusercontent.com/121395191/209476202-43ffcc8c-779b-4500-888f-95b2f9019384.jpg)
![20221225115304_1](https://user-images.githubusercontent.com/121395191/209476204-6e603bb3-1c8f-47a4-9d31-11468679db4a.jpg)
![20221225115602_1](https://user-images.githubusercontent.com/121395191/209476232-fb10f167-e7df-4f1f-be19-f7de55bbcc1e.jpg)
![20221225115609_1](https://user-images.githubusercontent.com/121395191/209476233-8c1252e0-9a4f-4d05-ab29-491e902a805b.jpg)

**Comment by WillofTheGold** [comment]
hope this is enough

![20221225120212_1](https://user-images.githubusercontent.com/121395191/209476389-fd26a0a5-7b9c-47d7-b226-891b9d9b8822.jpg)
![20221225120229_1](https://user-images.githubusercontent.com/121395191/209476390-b1d49b53-aac3-453e-821c-f284c9f84d7a.jpg)
![20221225120307_1](https://user-images.githubusercontent.com/121395191/209476402-1038a355-ff9a-4bba-8db3-bbfa7d2bcd5f.jpg)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10300393/Player.log)

**Comment by ThyWoof** [comment]
mobile feat and others fixed on DEV. checking spells.

**Comment by WillofTheGold** [comment]
good to know also have a happy holiday. if you need anything else let me know.

**Comment by ThyWoof** [comment]
Merry Christmas to you too.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/209478906-9d697ad7-f07c-4399-ade3-ba4677372d73.png)
spells also fixed on DEV branch.
