### ISSUE TITLE
INT Warlock can't get level 5+ invocations

### ISSUE THREAD

**Issue by KalaamNozalys** [SolastaMods/SolastaUnfinishedBusiness#2055]
In the current version, an intelligence warlock cannot gain invocations of level 5 or higher. The tooltip indicates not having the required level, even when it is the case.

It may be due to Smarlock being renamed Occultist, which is also the base french name for Warlock.

**Comment by ThyWoof** [comment]
Now that I think about it there will be many others cases like this. Might need to demote this class and take another approach .

**Comment by KalaamNozalys** [comment]
I can't remember if it works while it was still classed as smarlock so don't know if the name causes the confusion. But since taking it already prevents you from taking normal warlock levels, maybe there is something that can be done so it counts as actual warlock levels too ?
