### ISSUE TITLE
Classes are now missing spells due to spell toggles missing

### ISSUE THREAD

**Issue by Arcesious** [SolastaMods/SolastaUnfinishedBusiness#2056]
I noticed this trying to make new spellcaster characters today. Regardless of what settings are now used in the spells tab of the mod (turning every toggle off or on), classes are missing cantrips and spells that originally they had default access to in their class lists. I think this is because due to recent changes in the mod, not every spell is in every list of every class for the selection filters, resulting in the missing ones being turned off entirely.

**Comment by ThyWoof** [comment]
Fixed on DEV branch.
