### ISSUE TITLE
Deadeye feat modifier broken

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2073]
The modifier for Deadeye is broken. I changed the modifier to 4 from 3. But even changing it back it seems to just revert to 0 in combat

![2](https://user-images.githubusercontent.com/35788909/209735147-8cf5d87e-6516-4d4a-adea-0e6cc66cfb0b.png)

**Comment by Graham198011** [comment]
the descriptions are bugged atm (power attack is the same), to find out your actual modifiers, go into you inventory and mouse over your bow damage and to hit modifier.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/209740402-88fc586c-58e7-46ca-a1e4-cc2d149b7961.png)

not something we can reproduce. this used to be an issue many versions before. I suggest you to reinstall the mod from scratch.
