### ISSUE TITLE
GUI disappears after casting a spell (impossible to continue combat)

### ISSUE THREAD

**Issue by friendlynihilist** [SolastaMods/SolastaUnfinishedBusiness#2076]
It seems that, with UB activated and after casting a spell ~~if you load an already started campaign (Crown of the Maigster in Iron Man mode in my case)~~, the GUI disappears and it is not possible to End turn or continue the fight. 

Also, a message about a stability issues with mods appears after casting the spell.

~~It's probably common sense to start a campaign from scratch after installing UB, but I haven't found anything about it and was curious to try the Respec feature.~~

**EDIT**: I've just started Ruins of Ilthismar
 campaign with fresh new character and the issue still persists.

Here's the log:
[Log.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10315032/Log.txt)

Thank you very much for your support. :)

**Comment by ThyWoof** [comment]
Don’t use a pirate copy of the game.
