### ISSUE TITLE
Merciless has a DC of 0

### ISSUE THREAD

**Issue by jonjrhr** [SolastaMods/SolastaUnfinishedBusiness#2080]
which makes it never work. I have the most current version of solasta and UB and no other mods.

**Comment by ThyWoof** [comment]
Do you have a save file?

**Comment by jonjrhr** [comment]
yes but github doesn't support them, how do i import?

**Comment by ThyWoof** [comment]
Zip the file first.

**Comment by jonjrhr** [comment]
hrmm. it seems to be working on my current playthrough, it didn't on the last 2 but its working now!

**Comment by ThyWoof** [comment]
Thanks for confirming.
