### ISSUE TITLE
Pact of The Soulblade Warlock Spiritual Pact Weapon

### ISSUE THREAD

**Issue by Kangaroosta** [SolastaMods/SolastaUnfinishedBusiness#2083]
I'm not sure if it's intended to be like this but, the Spiritual weapon you summon from the Spiritual Pact Weapon feature from being a soulblade warlock appears to use your wisdom modifier to hit instead of what would be expected to be charisma as a warlock. It also doesn't display its roll properly when mousing over it displaying such things as "slam attack +10" or attack modifiers that the fighter in our party uses to attack with.

**Comment by ThyWoof** [comment]
It reuses ProxySpiritualWeapon which is set to use caster ability. Reason why I need a save.

**Comment by Kangaroosta** [comment]
I hope this is what you're asking for. This would be the save im playing this warlock on currently.
[Solasta Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10322101/Solasta.Save.zip)

**Comment by ThyWoof** [comment]
Thanks for the save. Hard one to tackle but will keep trying.

**Comment by ThyWoof** [comment]
fixed on DEV [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/c1171003d644726468bf152e21b0f70c3f6094db).
