### ISSUE TITLE
Repo being used by spammers

### ISSUE THREAD

**Issue by shinroo** [SolastaMods/SolastaUnfinishedBusiness#2084]
Dear SolastaMods community,

I've opened this issue to inform you that your repository discussions have been used to send spam to myself and many other users.

Here are some screenshots (with PII obfuscated)
![Screenshot 2022-12-29 214425](https://user-images.githubusercontent.com/15915453/210009526-ffd9f25a-d25a-4078-a9a1-982fbfffc328.png)
![Screenshot 2022-12-29 214511](https://user-images.githubusercontent.com/15915453/210009529-68e5f884-f147-418e-a814-b7e98075c578.png)

I'm not sure if you are able to take action on this, but I thought it best to inform you in any case.

**Comment by Graham198011** [comment]
the discussions page was closed for a few hours today because of this very thing, the moderaters were looking into it to remove these people of the server and find a way to block them in future.

**Comment by ThyWoof** [comment]
Thanks for reporting but we believe this was on git itself. We suspended our discussion pages for a bit and it doesn’t seem to be happening anymore.
