### ISSUE TITLE
Hand and a Half feat issue

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2085]
Hi there, the fighter feat Hand and a Half text said it only gives +1 attack and +1 damage to versatile weapon only if no other offhand, but my fighter still gained these bonuses with a shield equipped. The mod I am playing with UB is the custom campaign Against the Cult.

**Comment by NathanNN** [comment]
[Against.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10322935/Against.zip)

Save attached

**Comment by ThyWoof** [comment]
fixed. thanks for save.
