### ISSUE TITLE
Path of the Light Barbarian's Light Protection doesn't recover health

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2089]
Description says you recover health equal to half your barbarian level (kinda weak buff tbh) when illuminated target dies. Can't get it to ever trigger. Not sure if multi-class is maybe causing the issue or maybe the temp hp?

![bug](https://user-images.githubusercontent.com/35788909/210037332-2a483a6d-d35b-4d65-9edd-ab15f214f1e5.png)

**Comment by ThyWoof** [comment]
Please always share a save on any bug report.

**Comment by ViridianDoom** [comment]
[QuickSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10325869/QuickSave_2.zip)

Tried again with no multi-class still happening

**Comment by ThyWoof** [comment]
I believe it's indeed related to temp HP. Have you checked without this scenario?

**Comment by ThyWoof** [comment]
I cannot use saves created on standard locations. I would need the location JSON file in that case.

**Comment by ViridianDoom** [comment]
Making any level 6 Path of barbarian and using the mod's monster spawner gives same results. Even with 6 levels just as barbarian the health recovery never triggers
[QuickSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329523/QuickSave_1.zip)
Save from the steam Emporium mod level

**Comment by ThyWoof** [comment]
yep, it's not working indeed. This class might require a full review as it hasn't been touched for more than a year now. will add to our todo list.
