### ISSUE TITLE
Wrong text message for Piercer feat

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2092]
Hello! My ranger has the Piercer (Dex) feat but the text that pop up during combat say Piercer (Str) along with the description for Str version (you can check in combat log). I think mechanically the feat is fine though. Save is from Solasta newest version, UB .14 and Against the Cult custom campaign.
[Against.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10326126/Against.zip)

**Comment by ThyWoof** [comment]
Only the text. Will fix.
