### ISSUE TITLE
Blink with rift walker blink

### ISSUE THREAD

**Issue by Graham198011** [SolastaMods/SolastaUnfinishedBusiness#2101]
Upon using blink, character returns having lost any concentration spells. 

Using latest mod and game version, included is a save for testing. 

If you cast blur then blink out you will see what i mean.

https://drive.google.com/file/d/16vXSHgRzlYv7Xn1rrGIBEVTFSkY0K-TV/view?usp=share_link

thanks

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/210179469-54751eed-9dbe-4326-9d11-ec662b563972.png)
 fixed on dev.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/210179493-78d801ee-92f7-47ae-894b-6219848d8af4.png)
although there is a wrong message on log. concentration wasn't lost. not sure wanna fix that.
