### ISSUE TITLE
Warlock's Eldritch Blast bolts number only 3 at level 20

### ISSUE THREAD

**Issue by Spuriouslogic** [SolastaMods/SolastaUnfinishedBusiness#2108]
Warlock's Eldritch Blast bolts number only 3 at level 20.

Created 3 characters and tested. At level 20 you only cast 3 Eldritch bolts.

BTW. LOVE this mod.

**Comment by ThyWoof** [comment]
Share your save please.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/210200383-1126018e-7a16-45fe-93c8-058862034739.png)
It works on my end.

**Comment by Spuriouslogic** [comment]
Thanks for the reply.
 When I create the character it is level obviously level 1. I then use UB to boost it to level 20.
Then somewhere after I save and come back it reverts the character to level 12 (something in the save game?). This is why there are only 3 bolts and not 4.
Would it be that I am using WeMods and there is some sort of conflict?
I will test without having WeMods on at all to see if this is the cause and get back to you if that is ok?
    On Monday, 2 January 2023 at 02:28:49 pm AWST, Paulo Monteiro ***@***.***> wrote:  
 
 



It works on my end.

**Comment by Spuriouslogic** [comment]
I have tested with nothing else open at all except steam, my antivirus and Solasta (with Unfinished Business - Love this mod) :)
When you save the warlock (after boosting them to level 20) and reload they are level 12. Quitting out and trying again they are still Level 12.

From the Keyboard of Jonathon Clark 
May this missive find you well.
 

    On Monday, 2 January 2023 at 11:59:20 pm AWST, Paulo Monteiro ***@***.***> wrote:  
 
 


Closed #2108 as completed.
