### ISSUE TITLE
Dead Master update minor issues

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2109]
The updated version works pretty well, but with the limited time summons it looks like they disappear if your not looking. Ideally the combat log would say the summon has expired to stop player confusion and erroneous bug reports.

The spells info have the concentration tag, but they don't use actually it.

**Comment by ThyWoof** [comment]
Dead Master won’t require concentration but the spells will still show the tag as they originally require. Not an issue.
