### ISSUE TITLE
Way of the distant hand - flurry of arrows problem

### ISSUE THREAD

**Issue by Agimamif** [SolastaMods/SolastaUnfinishedBusiness#2110]
When using the flurry of blows feature, only the first attack can be done with a bow, the other is a bare hands attack, even when i choose the ranged attack option.

[Monk WOTDH bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329864/Monk.WOTDH.bug.zip)

**Comment by Drakhos** [comment]
If you reselect the bow attack after the first shoot of flurry of blows it seems to be working. For some reason you do a melee attack by default. I have the same issue on my game.

**Comment by ThyWoof** [comment]
first bow attack:
![image](https://user-images.githubusercontent.com/13087646/210278505-b5e7efc1-3f58-41e3-8d3a-1907d8931749.png)
after flurry:
![image](https://user-images.githubusercontent.com/13087646/210278524-91a29c17-e788-4f60-b827-224209794416.png)

indeed it selects the bonus unarmed attack by the default. not an issue.
