### ISSUE TITLE
Light cantrip not working

### ISSUE THREAD

**Issue by Franmillon** [SolastaMods/SolastaUnfinishedBusiness#2111]
The light cantrip spell doesn´t work and stucks the character casting it, not allowing it to do any thing, even move. At least with inventor and warlock classes
[AutoSave_5.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329947/AutoSave_5.txt)
[bardoso.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329948/bardoso.txt)
[cleruida.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329949/cleruida.txt)
[gerrarbaro.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329951/gerrarbaro.txt)
[magnominventor.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329952/magnominventor.txt)
[picor.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329953/picor.txt)
[warloka.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10329954/warloka.txt)

**Comment by ThyWoof** [comment]
Please zip the files and share again.

**Comment by Franmillon** [comment]
The light cantrip spell doesn´t work and stucks the character casting it, not allowing it to do any thing, even move. At least with inventor and bard classes. Happens in normal and crown campaigns
[solasta bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10331298/solasta.bug.zip)
[solasta bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10331307/solasta.bug.zip)

**Comment by ThyWoof** [comment]
I asked you to get me a zip as Github doesn't allow many file types attached and all you did was zip the previously uploaded files. Unfortunately I cannot open your save even renaming TXT to SAV.

Did my best to help, cannot reproduce on my end, and already put too much time I don't have.

Please don't open issues if you cannot correctly share saves or logs.
