### ISSUE TITLE
Haste action not able to be used on anything by Spell Shield fighter after using main action to attack and use a cantrip

### ISSUE THREAD

**Issue by Swizzle13** [SolastaMods/SolastaUnfinishedBusiness#2112]
I just hit level 7 on my party and got the feature for the Spell Shield subclass of fighter that allows you to replace one of your attacks with a cantrip. However, when I do this, it does not allow me to use my secondary Haste action from my wizard or bard casting Haste on my fighter for anything at all. Everything is grayed out and it says under the Attack action when you scroll over it "Action unavailable - out of uses/ammo"
[QuickSave_6.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10330870/QuickSave_6.zip)
Thank you for your time!

**Comment by Swizzle13** [comment]
It also kind of does this with action surge I just found out. The only things it will let you do with action surge is 1 single additional cantrip or the shove action. So it doesn't let you attack twice more like it should.

**Comment by ThyWoof** [comment]
@dolenam317

**Comment by ThyWoof** [comment]
just to confirm if you first cast the cantrip everything else works fine...

**Comment by dolenam317** [comment]
[PR ](https://github.com/SolastaMods/SolastaUnfinishedBusiness/pull/2114) sent.
