### ISSUE TITLE
ranger wolf companion don't attack enemy

### ISSUE THREAD

**Issue by plesommer** [SolastaMods/SolastaUnfinishedBusiness#2117]
I chosed at level 3 for my ranger beastmaster. I summoned a wolf . I can'tt attack enemy.

After resting, I summoned an eagle that can. I see two types of attack instead of none for the wolf.

**Comment by plesommer** [comment]
I have a six party ; paladin tiefling barbarian orc dwarf war cleric dwarf druid with a bear companion and a gnome mage undead specialisation. I take the ranger hireling because I play on cataclysm.

**Comment by ThyWoof** [comment]
Do you have a save to confirm that?

**Comment by plesommer** [comment]
I can send you a save the evening (I live in France). How I do that ? I never uploaded a file on github.

**Comment by ThyWoof** [comment]
Zip and attach.

**Comment by plesommer** [comment]
I send you a save after a fight with bandits. The wolf seem normal after the fight. But during the fight. itwas always dodging. I can't use it attacking.
[bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10338886/bug.zip)
I apologize for my question.

With an another party, I'll make another ranger with a pet. I'll try the bird

**Comment by ThyWoof** [comment]
cannot reproduce:
![image](https://user-images.githubusercontent.com/13087646/210419281-a5d5f017-e507-477a-b2c2-8330b534791e.png)

both normal attack and cone of cold work:
![image](https://user-images.githubusercontent.com/13087646/210419413-7f53a959-213e-41c4-a2e2-274a6cc57904.png)

you should learn how this pet works... Check first screenshot for reason why you cannot attack.

**Comment by plesommer** [comment]
I understand. It is quite limitating. I have no this problem with the pet of the druid who does not need order.

I'll try this evening.

Thank you very mutch.
