### ISSUE TITLE
Other player cannot load game in multiplayer

### ISSUE THREAD

**Issue by gregoryfl** [SolastaMods/SolastaUnfinishedBusiness#2123]
We are both using Mod Manager 0.25.4.0 and have the Unfinished Business 1.4.32.18 installed. We are both also running Solasta version 1.4.32. I am able to log in just fine and get multiplayer game up and running. When my friend tries to do the same thing, she gets this message and has to exit the game.
![mod_manager](https://user-images.githubusercontent.com/53844413/210437348-97c8925f-5a9b-498a-bcce-7b319639da80.png)

**Comment by ThyWoof** [comment]
Share her player.log

**Comment by gregoryfl** [comment]
I actually got it to work. I had to uninstall and reinstall the mod and it ended up working. I will go ahead and delete this ticket.
