### ISSUE TITLE
Bug in Aksha Fight

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#2126]
I am not sure what the bug is, but during the Aksha fight, Aksha casts Dark Veil a second time and the game freezes in the legendary action screen.
I get an error saying the Solasta mod is unstable.

Solasta version 1.4.32
Mod version 1.4.32.19
[IM_l5xQHgWmYEqhkaHfkFId4gA_1.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10347623/IM_l5xQHgWmYEqhkaHfkFId4gA_1.txt)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10347628/Player.log)
[Player-prev.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10347629/Player-prev.log)
[CrashCheckFile.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10347630/CrashCheckFile.txt)

Let me know, if you need any more information

**Comment by ThyWoof** [comment]
Please properly zip and attach the save file. Cannot open once you rename to txt and upload.

**Comment by Werewind1e** [comment]
[IM_l5xQHgWmYEqhkaHfkFId4gM_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10347791/IM_l5xQHgWmYEqhkaHfkFId4gM_1.zip)

Here you go

**Comment by Jayshua83** [comment]
We had this issue too but I reloaded a save and didn't have it happen a second time... I don't have a save from the first time it happened. :(

**Comment by ThyWoof** [comment]
yep, I remember trying reproduce this one before without any luck. keep in mind it also happens on unmodded games. the message about a mod instability will always display on a game error, regardless if us or game developer. Not fair.

I tested this save twice and wasn't able to trigger the problem.

**Comment by Werewind1e** [comment]
Foolishly, I was playing Ironman Mode and it crashes each time I try to reload.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10350123/SolastaUnfinishedBusiness.zip)
damm! let me know if attached works for you.

**Comment by Werewind1e** [comment]
donated to your cause.
Thanks!
