### ISSUE TITLE
Calm Emotions: Calm Enemy does nothing

### ISSUE THREAD

**Issue by ViridianDoom** [SolastaMods/SolastaUnfinishedBusiness#2129]
Tried using the mods Calm Enemy spell on the enemies. The combat log shows no rolls and there is no UI dice roll, but action is used.

![Untitled](https://user-images.githubusercontent.com/35788909/210723986-9c7c15a3-7f41-4e1a-bde6-914e32e853b1.png)
![Untitle2d](https://user-images.githubusercontent.com/35788909/210724001-1c326a9b-49f0-43ae-9150-f3ae06ad73da.png)

**Comment by dolenam317** [comment]
calm emotion only work with humanoid.

**Comment by dolenam317** [comment]
and this spell is not from the mod ? why create an issue for this ?

**Comment by ThyWoof** [comment]
Open a bug with game dev

**Comment by ViridianDoom** [comment]
Apologies the UB properties tag on spells that are base game was confusing me. Is that an issue itself?

**Comment by dolenam317** [comment]
Hmm this seems like a bug ? Any other spell has this tag ?

**Comment by ThyWoof** [comment]
It’s indeed a bug. Probably after we allowed spells from official lists to be added.
