### ISSUE TITLE
Spirit Shroud not applying extra damage

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2132]
Game version: 1.4.33 Public
Mod version 1.4.33.0

Bug: When casting Spirit Shroud, extra 1d8 damage is not being applied for any of the 3 damage types, even though other spell effects (slowing and prevention from healing) seem to be working fine.  (Note: Was working in the AM of 2023-01-05 before the update to 1.4.33.0, but not after the update)

Recreating should be easy, as I've tried to cast the spell - both in and before starting combat - and the same thing happens.

Attached are the Save and Character files, but the "Logs" folder is empty, and I'm not much of a tech person, so I'm not sure how I'm supposed to generate one.

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10360475/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
not a bug. Only hero on that save that can cast Spirit has max level 3 slots... How could you upcast?

**Comment by kosocku** [comment]
It's not about upcasting.  It should be adding 1d8 radiant/cold/necrotic damage when cast at lvl 3.  From the spell description: 

 **Until the spell ends, any attack you make deals 1d8 extra damage when you hit a creature within 10 feet of you**. This damage is radiant, necrotic, or cold (your choice when you cast the spell). Any creature that takes this damage can't regain hit points until the start of your next turn. In addition, any enemy creature within 10ft of you when you cast, or that enters or starts its turn in that range has its movement speed lowered by 10ft until start of its next turn.

It's the initial 1d8 damage that is not being added when you cast the spell at lvl 3.  I apologize if I didn't clarify well enough in my initial post
