### ISSUE TITLE
Corrupted character file 5/1/2023

### ISSUE THREAD

**Issue by IlliteratePig** [SolastaMods/SolastaUnfinishedBusiness#2133]
The two saves are almost identical; Fire spider ambush in the pillar-temple looking map near the cradle of fire. In the first, the file seems to be corrupted. In the fight, I'd blinded both spiders and used Anathema on one of them under a stone block, then spent a bunch of turns going up to the block to drop it on the spider for fun. I also had Guidance cast on the cleric in an attempt to get a better Survival check, if that's relevant. After reloading the autosave, i'd been notified that the file was corrupted and not to use the mod. 

In the second attempt, I reloaded the game from the autosave at the beginning of the fight. I had my PCs climb the central tower in an attempt to force the spiders to move in specific ways and drop them off with telekinetic occasionally. Lost fewer resources, took less time, and the save wasn't corrupted. No Guidance, because the enemies died too quickly and I didn't spend like 3 rounds trying to drop a rock on it

At a later point in time on the same day that I didn't bother to save, my file was also corrupted when loading the autosave after the Arrok fight, but then I updated the version of both the mod and the game then reloaded from the start of the fight, so it's possible that the initial problem also had something to do with the update.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10360479/Player.log)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10360480/Player.log)

**Comment by ThyWoof** [comment]
You missed the save file. There isn’t anything relevant on these logs.
