### ISSUE TITLE
Numerous spell slot issues on Dead Master Wizard (Counterspell) and Soul Blade multi-class

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2144]
Playing custom campaign with 5-member party.  Only 2 classes I seem to have an issue with are the Dead Master Wizard and Soul Blade Warlock Multi-class (5 Warlock/2 Paladin/1 Divine Soul Sorcerer/1 Fighter)

Wizard: I was able to cast Counterspell using any of my spell slots, regardless of level.  I know I should have been able to choose between my lvl 3 and lvl 4 spell slots for the cast, but I was also able to choose my 1st and 2nd lvl slots as well, and it would successfully cast.

Warlock: After the issues with Spirit Shroud yesterday (which seems to work fine again now, and thanks again for the fix!) today I noticed that, even after using up my 2 3rd lvl Warlock slots, I was still able to cast my 2nd and 3rd lvl spells while in combat.  I couldn't use the slots for Eldritch Smite anymore, but I could cast spells.  With my multi-class, I only have 3 1st lvl slots and my 2 3rd lvl Warlock slots, but was able to cast Misty Step using it after having to cast Spirit Shroud twice (first time my Warlock was KOd and had to recast)

Currently running 1.4.33 (game) and 1.4.33.1 (UB).  Custom Campaign is "Path of a Hero"

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10367351/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/211176091-93a8face-b05d-40e6-b3af-1aad8e157733.png)
Warlock issue is fixed. I also believe I fixed the counter spell one but wasn't able to test yet.

**Comment by ThyWoof** [comment]
Counter Spell confirmed fixed as well.
![image](https://user-images.githubusercontent.com/13087646/211178175-483f1a6e-05c4-4e25-b1fa-ee1f7fc0f4a2.png)

**Comment by dolenam317** [comment]
How could you have 3/5 spell slot ?
