### ISSUE TITLE
Piercer feat bug

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#2145]
Same issue as what I mentioned in the discussion thread. Piercer feat not re-rolling 1's or at least I can't tell if 1's are being re-rolled or not (no indicator in text box). Finally got a save file where I rolled a 1 for damage while "preserve random seed" setting is on. Loading in the save should have the same settings I believe.

[Save file.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10367426/Save.file.zip)

**Comment by ThyWoof** [comment]
Fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/f78c2d325620a1e212baa574a3f4614c559098c0).

![image](https://user-images.githubusercontent.com/13087646/211178670-7286b1b0-20f6-46ef-b7d5-6fa4fa15bfca.png)

**Comment by lovemachine44** [comment]
Sweet, thanks.
