### ISSUE TITLE
Sorcerer not getting spell slots back when trying to convert from Sorcery Points

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2146]
lvl 9 Multiclass SorLock (6 Divine Heart/3 The Timekeeper).  I used Prayer of Healing to top off my party, tried to convert Sorcery Points to regain the lvl 2 spell slot.  Sorcery points dropped by 3, but didn't create the spell slot.  Tried converting the other way, converting a lvl 2 slot to points and it worked fine, but once again tried to convert points to a lvl 2 spell slot and it didn't work (still showed as having used two lvl 2 spell slots (prayer of healing and converting to points).

Game Version: 1.4.33  Mod version 1.4.33.1

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10367512/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Can you double check? You won't see an used slot go away but you'll get one additional free slot at that level. This usually confuse people as they focus on the red X.

**Comment by ThyWoof** [comment]
any updates?

**Comment by kosocku** [comment]
Sorry, due to vehicle issues I was away for 2 nights without access to the game.  I'll open another issue for this.
