### ISSUE TITLE
Plane Magic feat spells

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#2155]
This is a pretty niche issue but still an issue. In this case I'd like to use the Shadow Touched feat. My character is not a prepared caster (Shadowcaster subclass) and has the option to unlearn a spell in order to learn an extra spell on a level up (like the warlock).

My character already has a spell that Shadow Touched grants (False Life).
![image](https://user-images.githubusercontent.com/120349569/211227530-87b9b230-2f4c-4ba4-9abd-73500e45b41f.png)

In this case I'm trying to remove the spell so I can pick 2 new spells instead of 1. The problem is I'm trying to perform this on the same level up as getting the feat Shadow Touched which results in not being able to unlearn False Life, i.e. missing out on learning 2 new spells.

*the same level up but after picking Shadow Touched*
![image](https://user-images.githubusercontent.com/120349569/211228228-834348a3-7d0d-4646-9771-8da9b0e1e75a.png)

The problem summed up is that I can't select False Life to unlearn after picking this feat.
A proposed solution could be creating a duplicate of the spell if it is already learned on the character.
_Something that only shows up if the caster learned the spell already so that it can be unlearned._
![image](https://user-images.githubusercontent.com/120349569/211229020-486093b5-dae9-4789-b452-99d53aeb9253.png)

I imagine this issue is probably consistent with all Plane Magic feat added spells and any class/subclass that is not a prepared caster (Ranger, Warlock, Spell Shield).
I realize that this could be a TA issue but I posted here since Shadow Touched is a UB feat.
I also realize that this can be worked around pretty easily with either planning ahead or a Respec but thought it worth bringing attention to.

**Comment by ThyWoof** [comment]
Fixed on [dev](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/be3d5aac97889e9dcc48ba8c17ff580c23e94ce5).
