### ISSUE TITLE
Flat rooms regain fog of war after reentry

### ISSUE THREAD

**Issue by Xyrmes** [SolastaMods/SolastaUnfinishedBusiness#2156]
Re-posting this here from Reddit. Game version is the most recent (as of this post), 1.4.31. Mod version is 1.4.33.2. No other mods are installed.

A minor inconvenience arises when I make a map in the dungeon maker with a flat room, enabled by the mod. See, if you clear out the fog of war on such a map and leave, usually two or more maps away, the fog returns. This means that fast travel spots will become hidden again, and you'll have to manually walk to them again as if having never been in there.

This isn't game-breaking, as far as I can tell. But it can be a major annoyance, especially on larger or more maze-like maps. Unless this is caused by something else, which I can't see how as only maps with flat rooms have this issue. It doesn't seem fully consistent, as one room I've made has flat rooms, but it has more normal rooms than flat ones so maybe that's why?

To reproduce it, you'd need to make a map in the dungeon maker with (more than one) flat room in it. Explore around to clear out the fog of war, and then either go a map or two away, or save, exit to the main menu, and reload the game. Either way, any parts of the map outside of where you spawn in are obscured, though anything you've gathered or fought remains as it was when you quit.

I had to copy/paste as text files since it wouldn't accept JSON or SAV files.
[Campaign.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10370903/Campaign.txt)
[SaveFile.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10370904/SaveFile.txt)

**Comment by ThyWoof** [comment]
Please don’t rename to txt. Zip original files and attach again.

**Comment by Xyrmes** [comment]
[FlatRoom.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10371407/FlatRoom.zip)

Does that work?

**Comment by ThyWoof** [comment]
What happens if you have normal rooms around flat ones?

**Comment by Xyrmes** [comment]
> What happens if you have normal rooms around flat ones?

I am just guessing, but I think the more normal rooms are around the flat ones, the longer it takes for the fog of war to return.

It seems kind of inconsistent. Sometimes the fog comes back, or comes back after a longer period away. Other times, it comes back as soon as the area is reloaded. In one room, it didn't come back at all even after leaving for a while.

**Comment by ThyWoof** [comment]
Are you using standard map sizes or the ones introduced by the mod? Wondering if this only happens on extended areas of the map, above the 100x100 mark.

**Comment by Xyrmes** [comment]
> Are you using standard map sizes or the ones introduced by the mod? Wondering if this only happens on extended areas of the map, above the 100x100 mark.

A combination. Two rooms, that seem to never get the fog back, are Huge. But one that does get it back is Gargantuan, and several others that get it back are Large. I haven't checked every room that includes flat room tiles yet, but it looks like only Huge (150x150) rooms never get the fog back.
