### ISSUE TITLE
Spells Icon Out Of Screen

### ISSUE THREAD

**Issue by codetmrrw** [SolastaMods/SolastaUnfinishedBusiness#2157]
This issue is present only when the character have quite a bit of spells available to cast, because level 4 spells icons and above appear over the lower level spells, it become impossible to select some of them, as they are being rendered off screen.

The old version of "community expansion" had an option to move spells icons on the right after the third level, preventing this issue

**Comment by codetmrrw** [comment]
![Uploading Lev4outofscreen.jpg…]()
[Admetos Char.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10374559/Admetos.Char.zip)
Here is the screenshot where the level 4 spells are only half rendered, and 2 spells are rendered out of screen entirely, plus the character file, savegame is irrelevant as this problem appear in any condition regardless, as long as the char can memorize this many spells

Id like to clarify that i am playing by enabling all spells for wizard class, and a personal modification that allow this char to keep memorized 80 spells or so at the same time, 72 here. The char level is 7 so to show the problem i encountered while playing a custom campaign, this issue do not appear with the normal memorization limit, as the game simply do not allow to have enough spells active to fill up the screen

**Comment by codetmrrw** [comment]
Weird Error With screenshot, trying again as zip
[Lev4outofscreen.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10374633/Lev4outofscreen.zip)

**Comment by ThyWoof** [comment]
I cannot support you on custom modifications. That screen was never meant to have 80+ spells. Nothing we can do to help here.
