### ISSUE TITLE
Dead master spells not extending when upcast

### ISSUE THREAD

**Issue by meowmixnix** [SolastaMods/SolastaUnfinishedBusiness#2158]
Dead master spells are not extending when upcast

tested with raise skeleton/skeleton archer upcast from lvl 2 to lvl 3/4/5

Upcast correclty removes concentration requirement but it only lasts for 1 min as opposed to 10mins/8hrs/24hrs as per the spell description

**Comment by ThyWoof** [comment]
This was changed after and description is incorrect.

**Comment by ThyWoof** [comment]
Thanks. Fixed on [dev](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/8360ea7aebe5cdc4ef843b52c88ade909fe47b2b).
