### ISSUE TITLE
Not getting spell slots back via Sorcery Points (updated)

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2160]
I opened a "ticket" for this a few days ago, but due to vehicular issues I was away without access to get back to you, so here goes again with what will "hopefully" help

lvl 9 Multiclass SorLock (6 Divine Heart/3 The Timekeeper). Since my last ticket I decided to play with it a little and see what I could figure out, and I've come to this conclusion: For 2nd- and 3rd-lvl spell slots (I didn't try 1st), it will allow you to create 1 extra until you have a total of 4 sorcerer slots.  Once you have those 4, you cannot create any more of that lvl slot, even if you've used all the available slots.  So, at lvl 6 sorcerer you have 3 3rd-lvl slots.  I cast 3 fireballs to use them all, and used 5 sorcery points to create a 4th lvl 3 slot.  Cast fireball again, and burned a couple 2nd-lvl slots to get me back to 5 sorcery points.  Tried to create another 3rd-lvl slot.  It burned the sorcery points (bringing my total to 0), but didn't create a new 3rd-lvl slot.  

I also tried with 2nd-lvl slots (thinking it was the 2 Warlock slots that were screwing it up) casting to use all 5 (3 sorcerer+2 warlock) 2nd-lvl slots.  It let me create 1 more with sorcery points(bringing my sorcerer slots to a total of 4 including the 3 I cast), cast again to use that one, but when I tried to create another 2nd-lvl slot it once again burned the sorcery points, but I didn't get another 2nd-lvl slot I could cast with.

Game Version: 1.4.33 Mod version 1.4.33.2

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10388116/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Thanks for the detailed explanation. Found the issue on code.

**Comment by kosocku** [comment]
Thanks muchly!  I tried to learn from my lack of details on earlier bug reports and make things as clear as I could.  And, once again, your quick responses and the work you do is greatly appreciated!
