### ISSUE TITLE
Enabling Level 20 allows for free levels after reaching Level 13

### ISSUE THREAD

**Issue by Xyrmes** [SolastaMods/SolastaUnfinishedBusiness#2162]
Game version 1.4.31 and mod version 1.4.33.2. No other mods installed.

It seems that when levelling up past Level 12, if you save after and load a new save file, you'll be able to level up again, even if no XP has been acquired. It seems this can be repeated indefinitely, up to Level 20, though I stopped at 15.

To reproduce, enable levelling past the base game cap and reach Level 13, finish the level-up process, save, quit to main menu, then load the save. You'll be able to level up again, as stated above. Repeat and you'll be able to keep gaining levels.

[Overlevel.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10390038/Overlevel.zip)

**Comment by ThyWoof** [comment]
Try disabling bypass min/max levels under gameplay > tools and let me know.

**Comment by Xyrmes** [comment]
> 

I had it off before, but when I turned it on, they weren't able to level up for free.
