### ISSUE TITLE
Saves won't load since update

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2165]
Just updated mod version to 1.4.33.3.  Since the update, none of my saved games will load.  (Note: by "none" I mean the 2 current saved games I have, and both are 5-man parties).

Was playing just hours ago no problem and no problems loading at that time.

Game version 1.4.33  UB 1.4.33.3 
[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10397330/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Sorry. I messed up on caster feats changes. You might need to rollback, Respec and then update. Sorry again but if I try to fix that now the mess I create might be bigger. Added a note to changelog.
