### ISSUE TITLE
Celestial Touched and Telekinetic feats do not add the releated spells and bonus action

### ISSUE THREAD

**Issue by jdcai** [SolastaMods/SolastaUnfinishedBusiness#2168]
Celestial Touched[Int] gave the +1 int but did not add the related spells.
Telekinetic[Int] gave the +1 int but did not add the bonus action.

Happened with Wizard and Inventor. Both Gnomes.
v1.4.33.3

**Comment by ThyWoof** [comment]
Fixed on 1.4.33.4

**Comment by jdcai** [comment]
Updated to 1.4.33.4
Multiplayer

We tried respecing in single player and adding the feats.
Would crash during loading screen when trying to join as the character with Celestial touched.

We tried reloading to before the level up and got the feats.
Celestial touched adds the related spells but does not add the plane magic option.
Telekinetic does not add the plane magic option either.

I tested it in singleplayer on my own and it seems to work.
Will try loading the single player game in multiplayer later to see if it works.
