### ISSUE TITLE
Circle of the Night Druid Wildshaped into a Gorilla can't range attack without melee attack first

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2173]
lvl 9 Night Druid.  When you Wildshape into a Gorilla (which you can do at lvl 6) you have 2 attacks: a Fist attack and a Throw Rock attack.  The Fist attack is obviously a melee attack, and the Throw Rock is a ranged attack that gets disadvantage if throwing while in melee.

When you try to attack a target in melee range, it does a single Fist attack, and then you can make a separate Throw Rock, but you're in melee and will take an Attack of Opportunity if you try to step back to throw.

If you are not able to get into melee range within your movement speed, it forces a Fist attack before you can Throw Rock, meaning you can't attack at all.

Is this working as intended?  Or a bug?

Game V. 1.4.33
UB 1.4.33.4

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10415820/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/212485460-704e401f-1ce8-4f7c-9e67-90cdc8eb1b2f.png)

this is an engine limitation. best I could do was reorder the attacks to start with range first but not sure if I should enforce this without a setting. I understand same might happen for deep spider as it's a web attack.

**Comment by ThyWoof** [comment]
@EnderWiggin , is this something we could fix?

**Comment by kosocku** [comment]
Personally, at least if it's Throw Rock first you could throw a rock and then move into melee.  With it being the Fist attack first, you have no choice but to run into melee and then either attack at disadvantage or take the OA to try and move back for the Throw Rock.

That being said, if it was able to be fixed to be 2 separate buttons (like the Armorer Tinker with it's Thunder Gauntlets having a separate attack from Unarmed Strike) it would certainly allow for more strategies

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/212487404-a0283d9f-9c11-4fb6-ba6b-afa4a4041829.png)
This is what I'm trying to do. After debugging realized the game is setting the melee attack to be a reaction, reason why we end up with only one button.

Fixed that but now the max attack counts on buttons is incorrect but I can only attack twice which is correct.

**Comment by kosocku** [comment]
the text on the button is a very minor inconvenience compared to not being able to attack at all because I didn't have enough movement.

**Comment by ThyWoof** [comment]
Too much work to fix this particular collateral case. Will stick with the reordering solution. Better is enemy of good.
