### ISSUE TITLE
Tinkerer (Armorer) infusions persisting through multiple uses on multiple pieces of equipment

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2176]
I'm sure there are people who are gonna hate me for reporting  this one :(

The easiest way I can clarify this bug is by referencing the old Tinkerer on previous incarnations of this mod: 

In CE2, the Tinkerer Infusions would reset after every Long Rest, meaning they had to be re-applied after every visit to a campfire.  This is the way the description for infusions suggests they are supposed to work.

When UB was released, the text for Tinkerer infusions didn't change, but they would persist through a long rest, which is much more convenient.  However, the text also says that an infusion can only be on one piece of equipment at a time, and applying it to a new piece would remove the infusion from the old.  This is not happening.

I recently hit lvl 10 on my Tinkerer, and wasn't sure if my Enhanced Defence and Enhanced Weapon infusions were automatically applied, or if I would have to apply them again to get the +2 instead of +1 from the infusion.  In trying to re-apply the Enhanced Defense infusion to my shield, it wouldn't let me (due to there already being a Enhanced Defense infusion on it).  So, I figured I would just apply it to my Armor (where my Enhanced Weapon infusion was) to reset it, and it would reset my Weapon infusion too (meaning I could re-apply the Weapon infusion on my armor afterwards, removing the Defense infusion and allowing me to add the Defense back to my shield)

However, I now have a Shield with +2 defense infusion on it, a set of +1 Plate Armor with the +2 defense infusion also on it, and my +2 Weapon infusion is ALSO on my Plate Armor, meaning I'm now currently "doubling up" on my Defense infusion, getting +4 from it (+2 from shield, +2 from plate armor) and still have my +2 weapon

There doesn't seem to be a way to reset the infusions so you can start it fresh either.

Please don't get me wrong, it would be very nice if we could keep the persisting through a long rest so you don't have to re-apply every infusion every time you sleep.  That's just a convenience.  However, the infusions also def shouldn't be able to be applied to more than one item each (or have multiple on a single item).  Breaks and unbalances the point of 'em when every party member has +2 def, +2 weapon, +2 focus, and mind sharpener.

Game V 1.4.33
UN V 1.4.33.4

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10418635/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
@EnderWiggin

**Comment by ThyWoof** [comment]
Armorer can stack up to 6 infusions at the same time at that level. It doesn't work exactly as the Tinkerer class.

**Comment by EnderWiggin** [comment]
About a month ago I've specifically removed most limits on infusion application and updated descriptions accordingly - you just can't apply same infusion to same item twice, and there's limit of only 1 infusion that grants +1 on a single weapon. I personally don't think that's too big of a buff, since infusions are still limited (or _should be_ limited, clarify if this is not true) by amount that can be active at one time.
As for being unable to reset infusions - I'll add ability to stop all infusions, although this may require respec, not sure yet.
