### ISSUE TITLE
Monk Initiate feat doesn't work

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2179]
As you can see in the images, my Druid is barehand and has the feat, but damage is not increased as advertised.

![20230114111104_1](https://user-images.githubusercontent.com/9156490/212497123-49a2cbe2-b3d7-494d-890c-69f394edd94a.jpg)
![20230114111112_1](https://user-images.githubusercontent.com/9156490/212497125-e3259441-a012-4d42-95a2-8ef069a82581.jpg)

**Comment by ThyWoof** [comment]
Removed that part from the feat. It's still very good without the extra damage.
