### ISSUE TITLE
6 player character Crown failure to activate in Dark Castle Maze

### ISSUE THREAD

**Issue by Jharryl** [SolastaMods/SolastaUnfinishedBusiness#2190]
Doing a YT playthrough showing the 6 player option in the official Crown campaign, and go past Aksha into the Maze. It took 3 or 4 "tries", before standing 1 character on each of the 4 tiles around the circle on the floor, activated the transition box in front of the steps image AND to touch the image and have the steps in the circle light up.

Then having done that, I proceeded to kill the ghost and move to the transition box in front of the DOWN arrow, enter that box, touch theDOWN arrow, and we get teleported to where you start the maze however, the DOWN arrow in the circle on the floor does not light up, nor does the transition box in font of the UP

https://user-images.githubusercontent.com/123037015/213332154-6f4bfcae-3be7-43d0-bdc8-00ceacce7b3a.mp4

https://user-images.githubusercontent.com/123037015/213332168-9827cdad-7b31-4dab-a18f-a17064fe2e1e.mp4

 arrow (the next step in the maze) activate. Stuck there with no way to progress.

4 times I have reloaded and retried. It takes repeated attempts to get past the STAIRS part, and then you can do the DOWN arrow, but that is absolutely it. You are not going any further.

I suppose I could use the command prompts to bypass the maze, but I do not know what if any flags for upcoming events, are set in/BY the maze.

**Comment by ThyWoof** [comment]
Thanks. Can I have your save file?

**Comment by Jharryl** [comment]
save file sent by email, will attach here as well. This is the save file from where the party just teleported by the Gate behind Aksha's room:

[start the maze.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10452979/start.the.maze.zip)

**Comment by ThyWoof** [comment]
Thanks, mind share a step by step from this save to simplify debugging ?

**Comment by Jharryl** [comment]
step by step to what? 

You put someone on that block in front of you, to open the gate in front of you, send your rogue to clear the trap in front of the gate, then send someone else thru the gate to move the boxes the your left.  Send the rogue to the door to the left of the block and clear that trap, then pick the door open and clear the trap inside the room. Pick up the Journal and read the sequence for the maze. Move the party into that room, and then thru the hole in the wall you cleared by moving the boxes; and this puts the party in the room with the circle on the floor and the STAIRS image. Stand 1 character on each of the 4 blocks in that room, and the transition box is supposed to appear in front of the STAIRS image. It might, and it might not. I had to move and occupy the 4 blocks 3 or 4 times, before the transition box in front of the STAIRS image appeared. Once the box is there, move everyone into it and the STAIRS image should glow. Touch it, and the STAIRS image in the circle on the floor should light up, and you should be teleported into a room with a gate that is locked and a crawl space at the end of the gate, and a RUNE on the wall. Get the RUNE, go thru the crawl space, and approach the goody bag on the ground, and a GHOST should appear,. Kill the GHOST, pick up the goodies, and now you can open the gate. Go thru it, and crawl thru the hole in the wall opposite the gate you just opened. Find the DOWN arrow, and a blue transition box should be there. Put everyone in the box and the DOWN arrow should light up. Touch it, and you should get teleported back into the room with the circle on the floor, and the DOWN arrow in that circle should be lit (it wont be), and there should be a blue transition box in front of the UP arrow, there wont be. This is where you are stuck.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213532496-2615ca11-a06b-40d0-9bb5-31004ec4c455.png)
What should I do from here? This is after killing the ghost...

I also realized this maze works correctly if you ALWAYS use first 4 heroes in party to enable those runes.

**Comment by Jharryl** [comment]
Oh I did use the 1st 4 characters, and it took repeated tries. I'll re-edit the video and see if I can get it to fit the uplkaod 10 mb requirement.

After you kill the ghost and pick up the loot part of which is a book...read the book, then you exit the barred room and across from the gate you go thru the walls pass thru. Now find the DOWN arrow symbol. It SHOULD have a blue transition box in front of it. 
Get everyone in that box and the DOWN arrow symbol should light up, like the STAIRS symbol did when you got everyone in that transition box. Touch the DOWN arrow and you should see 3 things happen...
...a cut scene where the DOWN arrow symbol in the floors circle lights up and...
...you get teleported to a spot close to w3here you started the maze...
...there should now be a blue transition box in front of the UP arrow.

The 1st and 3rd item in that list, do not happen. You can not advance, without them.

**Comment by Jharryl** [comment]
using the 1st 4 characters, and getting the STAIRS transition box


https://user-images.githubusercontent.com/123037015/213541643-18bf8b62-1f96-4933-a69b-8eaed87da020.mp4

**Comment by ThyWoof** [comment]
There is a button inside a room I still cannot access. Is this part of the puzzle?

**Comment by Jharryl** [comment]
here is the entire MAZE with a 4 player party (the battle with the ghost ends at 6:03)

https://youtu.be/wLTS6P74I8w

**Comment by ThyWoof** [comment]
![Uploading image.png…]()
so far...

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213569696-123d3eb6-bd02-4e0b-b55c-49c052ad99c5.png)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213569916-9926a513-6a56-4cf5-b030-2a618f63c406.png)
have you got this far?

All I did was follow the puzzle and once all heroes are on blue squares I select individually the hero closer to the buttons on wall.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213570021-a15eb75c-6914-46d5-8448-6e139a8dae14.png)
[MAZE_WORKING.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10461390/MAZE_WORKING.zip)

Let me know if you can continue from here.

**Comment by Jharryl** [comment]
I am beyond confused then. As you can see from my original 2 short clips, when I did the DOWN arrow, it did not light in the circle, and the UP arrow did not get a transition box. *shrug* I'll try it again....TY very much for your effort.

**Comment by ThyWoof** [comment]
I didn’t do anything special except for the mentioned trick. Get save I’ve shared and take from there.

**Comment by Volk1911** [comment]
I've tried the same thing with 1st 4 PC and no luck even activating the circle.  I did not even move my 2 other PCs. I only used the 1st 4 in this room.  Does it matter than one of the PCs is a Drow and not part of original character options. I've played this puzzle before but not with 6 PCs. 
<img width="1280" alt="Screenshot 2023-04-16 110444" src="https://user-images.githubusercontent.com/86846947/232321969-176e5463-1c9c-44fa-9dca-154652ebd394.png">

**Comment by Volk1911** [comment]
My save at that moment. Thank you for any help. 

https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2F1drv.ms%2Fu%2Fs!AuO1_bamObn0zkm3HK-yvaYklJ2V&data=05%7C01%7C%7C15343de8b8fc42e4089508db3e8d1568%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638172547882370568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K1%2FIbk99jo%2BQTwUzCuv7wb2RoGIMnbM7LSSK4JnOADU%3D&reserved=0
