### ISSUE TITLE
Druid Wildshape crash, Repeatable

### ISSUE THREAD

**Issue by Onyxhand** [SolastaMods/SolastaUnfinishedBusiness#2192]
Druids that have the Umbral Cloak ability from either cross classing as a Moonlit Warlock or a Way of the Silhouette Monk crash while Wild Shaping.

**Comment by ThyWoof** [comment]
No save no bug.

**Comment by Onyxhand** [comment]
[EASY TO REPRODUCE.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10462048/EASY.TO.REPRODUCE.zip)

No further reports will be made.

**Comment by ThyWoof** [comment]
Thanks. This is exactly what we need. If we have to setup a new hero, open a campaign, and test for every single reported issue...

You got it.
