### ISSUE TITLE
Hellish Rebuke caused mod instability

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2194]
In this save playing with Vel Leverage custom campaign, if you just wait around for the High Priest to cast the Flame Pillar spell or whatever that is on my Warlock, you will see the "mod instability" message pop up and the game will hang. This Warlock has Asmodeus origin so that might have been the issue because this origin and the Warlock class have Hellish Rebuke,

You might want to test the Flame Touched feat as well because that feat also give Hellish Rebuke. I didn't pick that feat for this character yet.

![20230120052350_1](https://user-images.githubusercontent.com/9156490/213735847-5350bcf4-b457-4f69-83f1-d9e4e22488ab.jpg)

[Leverage.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10467616/Leverage.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213809279-5057c278-ecb5-4135-9b93-0307838a567a.png)
so far wasn't able to reproduce but found out an issue displaying race slots with single class Warlocks. Fixed as you can see on image. Yours won't show these slots.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213822216-e0fde847-79ac-4cef-8328-1faaf78ebee3.png)
interesting we only get offered class slots after race ones. Also, Hellish should not allow upcast when from race.

**Comment by ThyWoof** [comment]
Are you able to reproduce this one consistently? Not one single instability on my end. Only minor UI issues mentioned above.

**Comment by NathanNN** [comment]
hmm its weird so yesterday the mod instability pop-up happen 2x after the Flame Strike from the High Priest on my Warlock like in this image. But just now under the same circumstance there is no mod instability pop-up anymore and game is fine. Ah well..... thanks for looking into it
![Uploading 20230120162515_1.jpg…]()

**Comment by ThyWoof** [comment]
It’s useful to fix the minor UI issues. Thanks for the save.
