### ISSUE TITLE
Inventor Grenadier Infinite Alchemical Bombs

### ISSUE THREAD

**Issue by Serphirot** [SolastaMods/SolastaUnfinishedBusiness#2202]
Gameversion 1.4.31
Mod Version 1.4.33.9

I play at the moment the Lost Valley Campaign with a friend and we noticed that the Inventor does´t use up his Charges to throw Bombs so he can throw two Bombs per turn without ever running out of charges.

**Comment by ThyWoof** [comment]
How to Report Bugs:

- The versions of Solasta and this mod.
- A short description of the bug.
- A step-by-step procedure to reproduce it.
**- The save, character and log files.**

HINT: Check the folder C:\Users*YOUR_USER_NAME\AppData\LocalLow\Tactical Adventures\Solasta* for the info we need.

**Comment by Serphirot** [comment]
Step-by-Step to reproduce
Play an Inventor and take Grenadier Subclass to get Alchemical Bombs.
Since Using Bombs doesn´t spend Alchemical Points you can throw as many Bombs as you want without taking any rest.


[Mod Multiplayer.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10472437/Mod.Multiplayer.zip)
[Roy.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10472438/Roy.zip)

**Comment by ThyWoof** [comment]
Yep, for an unknown reason Grenadier is having a hard time in MP games. I believe I found a fix for this one.

**Comment by ThyWoof** [comment]
Fixed on dev.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/45ea6094ae9167b44864ce91020be7a38237a606

**Comment by Serphirot** [comment]
Ty for the fast update
