### ISSUE TITLE
Moon Druid Wildshape are medium in size even with the rule turned off.

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2207]
Moon Druid Wildshape are medium in size even with the rule turned off. We tried to make it right by the mod manager, but it seems to be a problem with the code or something. Our Direwolf is medium and so is our Gorilla

**Comment by ThyWoof** [comment]
That setting requires restart whenever you touch it.

**Comment by Aelyx93** [comment]
We did restart the game several times

**Comment by ThyWoof** [comment]
cannot reproduce.

![image](https://user-images.githubusercontent.com/13087646/213939895-5163f7f9-c0d3-4b6c-87f3-6904c29f7c5d.png)
this is medium.

![image](https://user-images.githubusercontent.com/13087646/213939926-fe483824-ae55-4d96-a81d-2aa1cb9cc35b.png)
this is large.

model size won't change. only the square area it occupies.

**Comment by Aelyx93** [comment]
That's our problem. Our Direwolf is supposed to occupies 2x2. It doesnt.

**Comment by Aelyx93** [comment]
The fact that the model doesnt get bigger is not important to us
