### ISSUE TITLE
[1-Member Team] Crown of Magister: Infinite dialog loading

### ISSUE THREAD

**Issue by Maestro-Gibli** [SolastaMods/SolastaUnfinishedBusiness#2208]
I am playing with a Size 1 team (so, only one character), and when I got to Ergof in the Volcano (Crown of the Magister campaign), the screen turn black before the dialog scene, music continuing as normal, but a popup appear about Solasta's instability due to mods, and when I validate it the screen stays black indefinitely (and music not stopping).

I also encountered this issue through the quest in the Manacalon Ruins before you obtain the Crown, where you have to search for clues, all the statues worked fine, but the one dialog scene around the encrypted spellbook had the exact same issue. As it did not block me from going forward with the campaign, I simply ignored it at the time.

On another note, not quite an issue, but there are some difficulties with solo-character team, as there is some quests that you have to trick around (Madracht's Maze, I used Dimension Door, but it would be impossible without such a spell) or simply cannot do (there is this one quest for the Arcaneum from the Quest Board where you have to fetch something in the Manacalon Ruins, and to do so you have to place your characters on various Runes on the ground, which you can't do with only one character).

I wonder if some kind of special power allowing to temporarily put the Size of the Team to 4 with some random pre-generated characters could be doable as to work around such issues.

ZIP of my savefile below, I can give more data if need be ;)

Gib'.
[Mystis.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10475422/Mystis.zip)

**Comment by ThyWoof** [comment]
Party size was never meant for official campaigns but even so we added some patches to support the most common scenarios like teleport, dialogs, etc. It's feature complete.

Will check why game is aborting on above scenario and try to fix it.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/213940710-687f1033-6f41-4fd5-9b85-0952a77f1d80.png)
fixed.

DLL on zip below so you can continue your gameplay. replace the one inside your game_folder/Mods/SolastaUnfinishedBusiness.

[SolastaUnfinishedBusiness-DLL_ONLY.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10475505/SolastaUnfinishedBusiness-DLL_ONLY.zip)

**Comment by Maestro-Gibli** [comment]
Thank you very much !
