### ISSUE TITLE
Need more assistance.

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2210]
We still have an issue with wildshapes not being the size they are supose to be. We tried restarting the game, updating the mod, verifying the rules. Large creatures still occupies 1 square instead of 2x2. Dont close this tread too fast plz.

**Comment by ThyWoof** [comment]
Wildshape dire wolf are medium. I shared screenshots. I can keep it open but there is nothing else to do here.

**Comment by Aelyx93** [comment]
Ok, well if it's a mod dev. decision, i get that. But both Solasta's and DnD's dire wolf are large...

Also, Artificer's armorer armor mod doesnt seem to work? I've gots smiths tools, we did plenty of rests... cant choose my armor's mod

**Comment by ThyWoof** [comment]
It’s not a mod dev decision. The official game has dire wolf WS as medium. The dire wolf enemy is large.

you are making a huge confusion here. If you don’t like medium WS go ask for it on TA discord and register as a bug.
