### ISSUE TITLE
6 person party gets stuck entering or exiting certain maps

### ISSUE THREAD

**Issue by lahjar** [SolastaMods/SolastaUnfinishedBusiness#2218]
There are certain maps, like the one in the attached image, where the party is stuck and cannot progress because the exit square is only enough for 4 people, and the party is made of 6, so cannot trigger the square

![Bug](https://user-images.githubusercontent.com/8567423/214147534-ecf120fb-d243-4490-9fea-e3c88c9a02d6.jpg)

**Comment by ThyWoof** [comment]
Pause the game, individually select each individual to be on any given 4 squares, unpause. That’s the trick.

Won’t be fixed as good enough like this.
