### ISSUE TITLE
Monk unable to use Ki

### ISSUE THREAD

**Issue by Ragniz** [SolastaMods/SolastaUnfinishedBusiness#2228]
I just updated to  1.4.33.12 and my level 7 monk can't use her ki at all, no stunning strike, flurry of blows, step of the wind etc.. even at full ki right after resting.
The moves are greyed out with a message saying I'm out of ki.

Rolling back to  1.4.33.11 fixed the problem

**Comment by ThyWoof** [comment]
We haven’t touched monks on latest? Do you have a save? Do you use the ki points toggle?

**Comment by ThyWoof** [comment]
Let me know if enabling the monk toggle solves it. If so I believe I found the issue by reading the code. Again a save can make it much faster on my end.

**Comment by Thergin** [comment]
I also just updated and cant use my Ki for anything 5 points, Monk/Warrior

**Comment by ThyWoof** [comment]
Open Mod UI, enable ki points toggle under interface / game UI. This should fix it until next release.

**Comment by ThyWoof** [comment]
fixed on DEV.
