### ISSUE TITLE
Smite spellslots, multiclass

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2233]
According to 5E RAW Paladin should be able to use other classes' spellslots to smite. I understand that there may probably be an engine limitation here, but the actual issue I am reporting is that while having spellslots from other classes the smite will sometimes show available spellslots after exhausting your paladin spells.

**Comment by ThyWoof** [comment]
Can you please attach a save and step by step to reproduce?

**Comment by ThyWoof** [comment]
We follow the rules to create shared slots. Need to know what the MC is as Paladin can also use pact slots from Warlock on smites but should not be able to use any Race slots. Really need a save on this one.

**Comment by MartinBrandstrup** [comment]
Sorry I had to run an errand, I'll try to get some saves lined up.

**Comment by MartinBrandstrup** [comment]
I shall try to recreate the bug. I only saw it happen once, so it could just be an edge case.

**Comment by MartinBrandstrup** [comment]
I have been unable to recreate. I suppose it either got fixed or it was an extreme edge case that after all just affected display. Feel free to close this issue
