### ISSUE TITLE
Sentinel Style + Ready Action

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2234]
When preparing a ready action and having the Sentinel weapon style you will not get your attack of opportunity if the ready action triggers. This may very well be a core game issue that just wasn't possible before; I imagine it is not possible to "queue" reaction type actions, but I feel like it may be worth reporting for nothing else than listing it under known issues or somewhere on the wiki.

**Comment by ThyWoof** [comment]
Can you please attach a save and step by step to reproduce?

**Comment by ThyWoof** [comment]
@EnderWiggin

**Comment by EnderWiggin** [comment]
AFAIK, ready Action consumes your reaction, so sentinel can't trigger as it requires reaction to be available. RAW you should be able to react if your ready action has not triggered yet, but Solasta has different implementation.

**Comment by MartinBrandstrup** [comment]
Ah that makes sense. My bad for missing that :)
