### ISSUE TITLE
Sentinel Style + Crusher Feat

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2235]
This may be a misrepresentation as the 5e RAW (I am not 100% about the attack order here), but if you have both the crusher feat and the Sentinel fighting style & using a, after getting the aoo from Sentinel, proccing Crusher the aoo triggers first, pushing the enemy away, yet the enemy still gets to perform a melee swing from 2 cells away despite not being in reach. Granted I have only seen this occur using a polearm trying to cover for another character in front of the Sentinel, but I imagine it would also work with non-reach weapons when the Sentinel is getting attacked.

**Comment by ThyWoof** [comment]
Can you please attach a save and step by step to reproduce?

**Comment by ThyWoof** [comment]
@EnderWiggin , this one sounds like a nightmare to fix. What’s your take?

**Comment by EnderWiggin** [comment]
This is base game issue. I couldn't find a way to fix. Can be reproduced on vanilla game with repelling blast. Sent bug report to TA couple months ago. Not sure what I can do more.

**Comment by MartinBrandstrup** [comment]
Gotcha, not surprised it's a basegame issue. Prior to warlock being added I don't think this case was ever relevant
