### ISSUE TITLE
Crippling Fighting Style: Tooltip

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2237]
The Crippling Fighting Style only applies Hindered effect, which does not mention the supposedly -1 AC in the tooltip. Is the issue in the feat description, a lacking debuff or a misrepresentated tooltip?

**Comment by ThyWoof** [comment]
Looks like a tooltip issue. What is your take on balancing here? Would -1 AC be OP?

**Comment by ThyWoof** [comment]
Need a save here too. Checked the code and we indeed apply -1 AC to enemy.

**Comment by MartinBrandstrup** [comment]
Sorry I had to run an errand, I'll try to get some saves lined up.

**Comment by MartinBrandstrup** [comment]
Pooled the save with the one in issue #2232

**Comment by ThyWoof** [comment]
Read the comments there and indeed I’m reusing the condition description from hindered and not adding any description to the AC debuff. Maybe this is cause the confusion but the game is correctly doing the math. Will add better logging.

**Comment by dolenam317** [comment]
Actually AC debuff wont display on monsters. If you hover on their avatar it is always diplays the static AC from bestiary. However the debuff -1 AC works properly.

**Comment by ThyWoof** [comment]
fixed condition description on DEV.
