### ISSUE TITLE
Item: Helm of Awareness has no description of what it does

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2239]
Title ^

**Comment by ThyWoof** [comment]
That’s strange. We have a static diagnostics check on missing translations and nothing is reported there.

Double checked the code as well. Please share a screenshot and save. They always help.

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/04a7ec64218ecff9555e423b486e4f673be0df53/SolastaUnfinishedBusiness/Translations/en/Items-en.txt#L162

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/214750962-749340e4-a16b-459e-9730-8e5863382eb1.png)
cannot reproduce.
