### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by DanWolanski** [SolastaMods/SolastaUnfinishedBusiness#2243]
I encountered an issue where I managed to softlock myself.  It was stuck on monster turn.   I think the issue was the interaction with the crusher knockback , sentinal movement stop and polearm master.  The creature attacking me was a minitour who was using its charge ability.   When it entered into my threat range, it triggered the Aoo for Polearm, this then hit which triggered the 0 move from sentinal and knocked it back via crusher.   I suspect what happened is that the moster was not able to complete the charge move because it could not get into melee anymore with 0 movement so was hung.  I had this happen twice in a row in the new Marrows Deep.   I have a save at the fight if you need me to do some testing.

I don't know if there needs to be some check in there to force end the monster turn or maybe a timeout for it to complete.  The other could be just add some hotkey to force the turn to roll over to prevent softlocking.

Version I was playing on is 1.4.32.11

**Comment by ThyWoof** [comment]
This is an original game bug that was reported. Nothing we can do.
