### ISSUE TITLE
6 person party, final Temple of Einar

### ISSUE THREAD

**Issue by lahjar** [SolastaMods/SolastaUnfinishedBusiness#2245]
2 people get stuck behind the closed door (beside Sunblaze), and the party can't move ahead, because the entire party needs to step on the blue exit square

**Comment by lahjar** [comment]
![bug 1](https://user-images.githubusercontent.com/8567423/214861921-a5ad0c24-3baf-4622-a942-fd0511c9f7d9.jpg)
![bug](https://user-images.githubusercontent.com/8567423/214861930-baf182e7-6406-45c0-8c3f-77dbfefa7a0a.jpg)

**Comment by ThyWoof** [comment]
Enable CTRL-SHIFT-R on Interface / Game UI to allow rejoin the party.

**Comment by lahjar** [comment]
I don't seem to have that option unfortunately. Has it been introduced in a particular version of the game?
![bug](https://user-images.githubusercontent.com/8567423/214891736-1ad18972-b4ca-4a11-8791-c474ed30795c.jpg)
