### ISSUE TITLE
Metamagic, no longer have resource after update

### ISSUE THREAD

**Issue by Pigoletto** [SolastaMods/SolastaUnfinishedBusiness#2248]
With the recent update, my multiplayer character unfortunately seems broken. The mod appears to have changed how metamagic works, and since she is part of a multiplayer playthrough, I can't change the character and respeccing does not work in multiplayer.

The end result is an entirely wasted feat that I have no way of fixing (she has no points with which to use the twinned magic - though the metamagic button still remains for her).

I assume I can go back to the earlier version of the mod to avoid this, but I thought I should mention the problem.

**Comment by ThyWoof** [comment]
Indeed you need to Respec and you can do that opening the same MP save from the load menu in single player mode.

**Comment by Pigoletto** [comment]
> Indeed you need to Respec and you can do that opening the same MP save from the load menu in single player mode.

How? Even when I open it from the main menu without ever going into multiplayer, it still claims I can't respec in multiplayer. Is there some other way to open a save game than 'load game'? This is without ever going into the multiplayer menu.

**Comment by ThyWoof** [comment]
Can I have your save?

**Comment by Pigoletto** [comment]
)Of course, thank you!

I’ll attach 2 files. The save called test is saved on the road after we’d first tried respeccing, both of us while starting a singleplayer game from the menu. Test2 is where we’re currently at in the story (the volcano), but it’s an inconvenient place to take a long rest. 

It’s our first run of the game so my characters are probably not the best...
[Saves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10518065/Saves.zip)

**Comment by ThyWoof** [comment]
will try to rollback some changes to get backward compatibility on these feats. fixed on dev.
