### ISSUE TITLE
Wardancer Momentum + Haste

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2252]
Having the haste effect applied while using the Wardance does not interact well.
Save uploaded. Note that the Wardancer have the Haste buff as well as 3 momentum stacks. She has currently used up all the Wardance attack and is now left with the bonus Main Action from the Haste potion. If hitting the nearest enemy you will see that the attack bonus is not reduced by Momentum (-13) but the damage bonus from Momentum (4d8) is still applied.

[Momentum + Haste.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10518866/Momentum.%2B.Haste.zip)

**Comment by ThyWoof** [comment]
Thanks. Fixed on dev.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/67b6acdd4c181d046a93a31c2c6b6e26d1bb7039
