### ISSUE TITLE
Telekinetic feat bonus action not being spent properly when used on self

### ISSUE THREAD

**Issue by Microchaton** [SolastaMods/SolastaUnfinishedBusiness#2260]
Game version 1.4.33, Mod version 1.4.33.15, no other mods

When a character with the Telekinetic feat uses the bonus action to move someone, the bonus action is only spent whent it is used on an enemy or party member. When used on self, you can use it a seemingly infinite amount of times. 

https://i.imgur.com/9zB8oRI.jpeg

**Comment by EnderWiggin** [comment]
That's weird. It shouldn't behave differently for self or others. Will look into it

**Comment by EnderWiggin** [comment]
Hm... looks like game interrupts your current action (using the telekinetic power) when you are pushed, which leads to bonus action point not being consumed.

**Comment by ThyWoof** [comment]
This is a very colateral case. Why would you push yourself in battle? No easy fix here.
