### ISSUE TITLE
Marshal's Coordinated Attack Feature not procced by the Marshal's Attack of Opportunity

### ISSUE THREAD

**Issue by Microchaton** [SolastaMods/SolastaUnfinishedBusiness#2261]
Game version 1.4.33, Mod version 1.4.33.15, no other mods

This may be intended but as written, it should proc on AoO. Change should either make the feature proc on AoO or modify the wording of the feature to reflect that not proccing on AoO is the intended design, for example:                                            
 "When you hit with a melee attack _on your turn_"

https://i.imgur.com/yaJqcm8.png

The feature otherwise works as written with main action and bonus action attacks.

**Comment by dolenam317** [comment]
It is intended because the game softlock if you triggers reaction within the context of another reaction. The description will be updated.

**Comment by ThyWoof** [comment]
Cannot fix because of engine limitations.
