### ISSUE TITLE
Grenadier bombs' "use +1 charge for an additional effect" effects do not seem to work

### ISSUE THREAD

**Issue by Microchaton** [SolastaMods/SolastaUnfinishedBusiness#2262]
Game version 1.4.33, Mod version 1.4.33.15, no other mods

When selecting the "+1 charge" to have additional effects such as cone bombs having an additional die or aoe bombs having a higher radius, neither effect seem to work.

**Comment by EnderWiggin** [comment]
Is this multiplayer or single player? Can you attach zip file with save?

**Comment by Microchaton** [comment]
This is on a singleplayer save in the "lair of the lich" workshop campaign (used to test high level chars). Bug still appears present in 1.4.33.17.    
[GrenadierBug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10529637/GrenadierBug.zip)

**Comment by EnderWiggin** [comment]
Can't reproduce on that save - splash bomb had bigger radius, precise bomb extra target and cone bomb had extra die. Any specific circumstances when this happens?

**Comment by Microchaton** [comment]
Oops that one's on me, I didn't realize you needed to click on the + button and THEN on the "+1 charge", I thought clicking on the + was enough. My bad.
