### ISSUE TITLE
College of life bard, some abilities that should be upcasted by Reality Bending are not.

### ISSUE THREAD

**Issue by Microchaton** [SolastaMods/SolastaUnfinishedBusiness#2263]
Game version 1.4.33, Mod version 1.4.33.15, no other mods

Neither Magic Weapon nor Enhance Ability are upcasted properly by Reality Bending. Longstrider & Blind work as intended. Didn't test Heat Metal.

When multiclassed with a Dead Master Wizard, the special Necromancy summons are NOT upcasted.
However, when upcasted manually, the Scatter effect (not requiring concentration on upcasted summons) does work as expected.

**Comment by ThyWoof** [comment]
Can you please share a save? What is reality bending?
