### ISSUE TITLE
Some say flat rooms lead to the void

### ISSUE THREAD

**Issue by Xyrmes** [SolastaMods/SolastaUnfinishedBusiness#2272]
I can't say what version of the game or mod is being used because I'm getting reports from others. However, they all seem to be the same.

In the first dungeon, I used flat rooms beyond the entry and some people are reporting that they only see a void where a room should be. I've told them to enable the dungeon maker pro options, and to try starting the game via the dungeon maker and not the new game menu. Some say it fixes the problem, but some say it hasn't.

I'm not sure what might be causing the issue. All say they have this mod installed.

https://www.nexusmods.com/solastacrownofthemagister/mods/229?tab=bugs
https://steamcommunity.com/sharedfiles/filedetails/?id=2923817332

**Comment by ThyWoof** [comment]
Can you please share a copy of the campaign here? Or point me out to where I can download?

**Comment by Xyrmes** [comment]
> Can you please share a copy of the campaign here? Or point me out to where I can download?

In addition to the above links, here's the zip folder:
[Terminal_Reverie_v1-0-0.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10530358/Terminal_Reverie_v1-0-0.zip)

**Comment by ThyWoof** [comment]
I was able to load the Dungeon. Where should I go to reproduce?
![image](https://user-images.githubusercontent.com/13087646/215345195-edde0f77-810c-4cfd-9729-8bcc87ae3338.png)

**Comment by ThyWoof** [comment]
Do you know if these players are using a party greater than 4? A good tip is always leave spaces around the entrance and exit gadgets.

**Comment by Xyrmes** [comment]
> Do you know if these players are using a party greater than 4? A good tip is always leave spaces around the entrance and exit gadgets.

I don't know for certain but I did recommend they use 6.

The "Gate Temple" map is the one they're talking about, it's the first one using flat rooms.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/215348534-9260945d-e77a-4c19-9c5e-d6e587e4a6b3.png)
changed the campaign to start there. Cannot reproduce. Can you move this entrance to the middle of the room?

**Comment by ThyWoof** [comment]
I believe I know what might be going on. Standard game code will delete anything it cannot find on DB by the time you open the menu to browse custom dungeons. If uses don't have the "Enable DMP" on beforehand, most likely these assets will be removed from location, causing heroes to fall into void.

Please tell them to first enable DMP, and if they face this, redownload the dungeon to fix the issue.
