### ISSUE TITLE
Dark Elf Ancestry Cantrips

### ISSUE THREAD

**Issue by AidennXI** [SolastaMods/SolastaUnfinishedBusiness#2273]
![cantripissue](https://user-images.githubusercontent.com/123876296/215328230-88bfc56c-517a-4f52-b315-d32f8fdb3b45.png)
On trying to level up as a level 2 Dark Elf Warlock of the moonlit it asks me to learn 2 ancestry cantrips and then only lists dancing lights (which I already know) backing out and attempting to level a different class extrapolates the issue for some reason, and trying to take a level in cleric resulted in the game wanting me to select 26 ancestry cantrips, essentially locking the character out of leveling up.

**Comment by ThyWoof** [comment]
This is a game engine limitation. Best you can do now is add more cantrips to this class on spell menu to bypass this screen.
