### ISSUE TITLE
Telekinetic and Fey touch dont seem to work properly

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2281]
I cant use any bonus action or action (powers or whatever) to activate telekinesis or Fey Touch feat abilities. Is it a known issue

**Comment by EnderWiggin** [comment]
Can you post more detailed description of what you are doing? Any screenshots or saves?

**Comment by Aelyx93** [comment]
Detailed description, well i took telekinetic feat with one of my characters and Fey touched with the other. Both gained the +1 stat, that's fine. The one with fey touched gained access to misty step in her spell list, but cant use it as a ''free'' spell without expending a spell slot. The one with telekinetic has no way to use it (In or Out of combat). I dont know why. I can post screenshots if you want, but there is nothing to see that's the point. Only ''power'' available for both characters in combat is help action or something class related.

**Comment by Aelyx93** [comment]
![image](https://user-images.githubusercontent.com/123326957/215550415-b1fa5892-75cf-4165-b073-61fb5e5cc477.png)
![image](https://user-images.githubusercontent.com/123326957/215550454-b2dfdac8-cd87-43c2-8cb3-34d08ad2ca18.png)
![image](https://user-images.githubusercontent.com/123326957/215550484-0758bed7-183d-4954-b41b-b6ba526e0ddd.png)
![image](https://user-images.githubusercontent.com/123326957/215550512-ddedce5b-96ff-417c-8eca-4190fb291cdb.png)
![image](https://user-images.githubusercontent.com/123326957/215550550-f9f6496c-0619-4b96-8548-69d1c6968d9d.png)

**Comment by Aelyx93** [comment]
![20230130121729_1](https://user-images.githubusercontent.com/123326957/215552791-a35dfaab-7bfe-4942-bfa8-643721f267cc.jpg)
![20230130121744_1](https://user-images.githubusercontent.com/123326957/215552803-f7f0e229-471e-4824-9e5b-96e7b31255a1.jpg)
![20230130121749_1](https://user-images.githubusercontent.com/123326957/215552823-ec684c91-c10a-4b0b-a4c9-3837f12f1a91.jpg)
![20230130122511_1](https://user-images.githubusercontent.com/123326957/215552848-25396eac-a253-4cfc-806d-8f650a537314.jpg)

![20230130122507_1](https://user-images.githubusercontent.com/123326957/215552827-e5128e3d-af4d-48fe-8b57-90df053b386c.jpg)

**Comment by Aelyx93** [comment]
@EnderWiggin  so, i've been messing around to find why this happens... and seems like the feat wont work in multiplayer, but does work on single player campaign ? I can use the feat without any problem with a lvl 1 variant human on single player.... Any idea why and how to fix ?

**Comment by ThyWoof** [comment]
@EnderWiggin , might be the same issue with grenadier bombs we fixed in MP. Might be worthy look at that commit.

**Comment by Aelyx93** [comment]
@EnderWiggin @ThyWoof  I fixed it by loading the game in solo, using Respec tool and then reloading it in multiplayer. It works now, thx for your support.

**Comment by ThyWoof** [comment]
Thanks for the update. Closing this one.
