### ISSUE TITLE
Lightning Launchers cant  be used as a ready action

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2282]
Armorer's Lightning Launchers cannot be used as a ready action. You can use Guardian's armor mode gauntlets punch as a ready action but not the launchers'... can it be fixed ?

**Comment by EnderWiggin** [comment]
That's weird - they both are created in same manner, so both should behave similarly. Maybe game has some different checks for ranged ready attacks? Need to check.

**Comment by Aelyx93** [comment]
@EnderWiggin i tried to equip a ranged weapon, still wont work. I have a theory tho. Gauntlets appears to be considered as a ''main weapon'' when you use them, they are first in the ''attack'' action order. For example, if i have nothing else in hand, i have first option : gauntlet, second option bare hand. Launcher always appears as a second choice. I have fist (or whatever in main hand) then i have lightning launcher. Can it be the problem?
