### ISSUE TITLE
Character model not updating after respec

### ISSUE THREAD

**Issue by Billabong1985** [SolastaMods/SolastaUnfinishedBusiness#2287]
I'm trying out the mod for the first time, primarily because I want to try multiclassing on one of the characters I'm using in a fairly recently started campaign with a friend (He hosts the game but I take a copy of the save too). Options I have enabled are all subclasses, recommended spells, multiclassing, and respec on long rest, don't think I have anything else. It seems to work, but after a respec, my chracter's model and icon on the left don't update, and switching weapon slots doesn't change appearance either. Is this a known bug with respec on an existing save file?

**Comment by ThyWoof** [comment]
Save and reload.

**Comment by Billabong1985** [comment]
> Save and reload.

Oh is it really that simple? Can't believe I didn't think to try that, I'll test it in the morning, thank you for the quick reply!
