### ISSUE TITLE
Charm VS Elf Enemies

### ISSUE THREAD

**Issue by Girafz** [SolastaMods/SolastaUnfinishedBusiness#2290]
Charm effects vs elf enemies properly have advantage but the reason why is listed as "none." It was making it very confusing to figure out why certain enemies had advantage. I'm not sure if this is a solasta or mod thing. Either way maybe the mod can help with a clarification.
![image](https://user-images.githubusercontent.com/83099397/215672043-1aed2d3d-4137-4d09-b9b5-380b9f92727d.png)

**Comment by ThyWoof** [comment]
You should report this to TA. Let them know MovementAffinityConditionRestrained need a title and description.
