### ISSUE TITLE
Attacks missing over AC

### ISSUE THREAD

**Issue by Girafz** [SolastaMods/SolastaUnfinishedBusiness#2291]
Sometimes an enemy misses an attack even though the character has lower AC than the hit. The target has  AC but a 24 and 23 miss but a 22 hits. It only happens on this one character. The character is raging, reckless attack, and is hasted. We are unable to determine what the cause is.
![image](https://user-images.githubusercontent.com/83099397/215677847-5c870a49-d312-4682-9e1d-c3bb9a3e8fa8.png)
![image](https://user-images.githubusercontent.com/83099397/215678045-9115d71e-8088-4302-8a6b-ac3cbf61b197.png)

**Comment by ThyWoof** [comment]
Can you consistently reproduce? Do you have. Save?

**Comment by Girafz** [comment]
Yes it happens fairly consistently. I can post save tonight.

**Comment by ThyWoof** [comment]
Thanks. Saw your report on the missing text on discord. I pinged Miz on top of that.

**Comment by Reaveler1331** [comment]
[DLC.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10552848/DLC.zip)
This should be the save file, let me know if you have any issues opening it

**Comment by ThyWoof** [comment]
Thanks. Can you please also recheck on your end on latest 1.4.33.21? I commented out a bugfix on original TA code. Wondering if that was the cause.

**Comment by Reaveler1331** [comment]
So it seems like it might be fixed, fixed a fight so i could test all potential hits from 18-25. with my AC at 20, 18-19 missed, while 20+ all hit as intended. the new patch must've fixed some interaction that was going on. I'll let you know if it happens again, but otherwise things look good
