### ISSUE TITLE
Mod Manager Change Log History not updated with latest changes

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#2301]
In the Mod Manager, the Change Log History doesn't show anything past 1.4.32.16.  I like to read the change history and I sometimes skip updates.

**Comment by ThyWoof** [comment]
Use https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaUnfinishedBusiness/ChangelogHistory.txt
