### ISSUE TITLE
Metamagic Adept Sorc points not appearing on Warlock

### ISSUE THREAD

**Issue by Berwind24** [SolastaMods/SolastaUnfinishedBusiness#2309]
Version 1.4.33.23
Playing a Warlock in multiplayer campaign and took the Metamagic Adept feat; the sorcery points are not appearing and I am unable to use Metamagic at all.
Screenshot and save file:
![image](https://user-images.githubusercontent.com/73523410/216514012-8d80a3ed-b933-4e79-a9d3-73bf0f7053e6.png)
[Solastasave.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10575583/Solastasave.zip)

**Comment by ThyWoof** [comment]
Rollback to .22 please.
