### ISSUE TITLE
Combat freezes when Asmodeus Tiefling SoulBlade Warlock gets hit in battle when empty of Spellslots

### ISSUE THREAD

**Issue by SurpriseChan** [SolastaMods/SolastaUnfinishedBusiness#2358]
The Asmodeus Tiefling on Standard has Hellish Rebuke, and when she gets hit the Pop-Up to activate comes up.
My SoulBlade Warlock has Spell slots of lvl 3, the Hellish rebuke can only be activated with lvl 2 or 1 Spell slots, which means that no Spell slot is expended, but when the Warlock is out of Spell slots then the Pop-Up will still come up but regardless of what you choose the combat will freeze requiring a restart from a previous Save. This Freeze will not happen when the Warlock has at least 1 Spell slot left.

The Current Version of Solasta and Version 1.4.33.25 of Unfinished Business, no other mods.

[Bugreport.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10610969/Bugreport.zip)

**Comment by ThyWoof** [comment]
This is an engine limitation. Will try to prevent Hellish rebuke offering on warlock if race is Tiefling to avoid that.
