### ISSUE TITLE
Giant Insect spell ... just isnt what it's supposed to be

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2362]
First, you cant control the summon (even with the option turned on), second, you summon a deep spider (cr 2) with a 4th lvl spell ? that's quite bad isnt it ? Is it just me or it's underwhelming ?

**Comment by ThyWoof** [comment]
You do realize the Giant Insect isn't provided by the mod, right? You do also realize that any mod content as a "Unfinished Business" tag?

If not please don't open issues here but on TA discord.

Thanks.

**Comment by Aelyx93** [comment]
@ThyWoof  wow dude, chill ... I just asked a question. I'm sorry if i'm bothering you, i did not realized it wasnt UB. If you dont want people suggesting ideas or asking questions ... why even bother with github

**Comment by ThyWoof** [comment]
Just having a hard time fixing a lot of bugs. Open a discussion instead.
