### ISSUE TITLE
Level 11 Moonlit Warlock can't far step

### ISSUE THREAD

**Issue by Zolar67** [SolastaMods/SolastaUnfinishedBusiness#2384]
I apologize if I'm doing this wrong. I'm a noob when it comes to Github or reporting game issues. I love Solasta with Unfinished Business. I donated once so far with link that comes up when updating and will again.

I currently have a lvl 11 The Moonlit Warlock with pact of the chain with Voice of the Chain and Abilities of the Chain  invocations. Recently when I try to use the Far Step spell the game completely freezes. My Bard in same game can use Far Step no problem.  I'm playing in a user made campaign called Morrows Deep (one of the best community campaigns I've tried so far).

Hope this is some way helpful.
[QuickSave_9.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10680109/QuickSave_9.zip)

**Comment by ThyWoof** [comment]
Please zip and attach your save file.

**Comment by Zolar67** [comment]
I uploaded my saved game. Hope I did it right.

Is the donate link that comes up when Unity Engine updates Unfinished Business when starting Solasta the best way to support your work? Unfinished Business and the community development mod before it doubles the value of Solasta.

**Comment by ThyWoof** [comment]
Yep, that's the link or the one under Character / General. Thanks for the support.

Fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/8be61edd406f21f97bdf33d86f6b976d9d97118a).

**Comment by Zolar67** [comment]
Thank you! Warlocks my favorite. I will send some $$$ your way soon.
