### ISSUE TITLE
Revenant Blade not working with greatswords from workshop campaigns

### ISSUE THREAD

**Issue by Kazzius** [SolastaMods/SolastaUnfinishedBusiness#2385]
When putting a custom greatsword onto a character with the revenant blade feat, it used strength for attack and damage with the weapon. The feat worked to use dexterity when using regular greatswords, but not the custom one. Opened up the custom greatsword in the dungeon builder to confirm that it was a greatsword, and it was based on the vanilla +1 greatsword.

![image](https://user-images.githubusercontent.com/26793034/217387058-95f7099f-8cff-4d05-abd1-8d27b933045e.png)
![image](https://user-images.githubusercontent.com/26793034/217387111-91c6bcc7-0c22-44ba-83fa-c746ce8ce7a6.png)

taken from the 'curse of an orphan' campaign, and the 'holy fierce' greatsword

**Comment by ThyWoof** [comment]
Fixed on dev. Thanks for save.
