### ISSUE TITLE
Sentinel + Polearm master does not stop movement.

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#2386]
I have a fighter with polearm master and sentinel.  I am using a Polearm.  I get the opportunity attack when something comes into range, but I don't reduce it's movement to 0.

Mod Version 1.4.33.29
Game version 1.4.33
[logs.7z.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10680588/logs.7z.zip)

** added.zip to .7z file name

**Comment by ThyWoof** [comment]
Fixed on dev. Thanks for save.

**Comment by Werewind1e** [comment]
Hey, so a very technical thing and maybe we are playing it wrong.
If you get to attack an enemy because it attacks your ally in range, you do not reduce their movement.  Currently, it is "stopping" the enemy.

- When you hit a creature with an opportunity attack, the creature's speed becomes 0 for the rest of the turn.
- Creatures provoke opportunity attacks from you even if they take the Disengage action before leaving your reach.
- When a creature makes an attack against a target other than you (and that target doesn't have this feat), you can use your reaction to make a melee weapon attack against the attacking creature."

Bullet 3 does not say it's an "opportunity attack".  Bullet 1 says when you hit with an "opportunity attack".

Again, I may be playing it wrong. 

Thanks,

John
