### ISSUE TITLE
Intern and wizard class

### ISSUE THREAD

**Issue by guard65** [SolastaMods/SolastaUnfinishedBusiness#2393]
Just a note that if a wizard picks up intern in any class it completely opens up that classes entire spell vertical. The Wizard can then learn from scroll every spell from say the Cleric class if they picked up Cleric Intern. Just an FYI.

**Comment by ThyWoof** [comment]
Will check how hard to prevent that. Thanks for reporting. Got any easy save I can use on tests?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/217681913-94037413-e90f-49f9-8346-71b343fe5711.png)

**Comment by ThyWoof** [comment]
fixed on dev.
