### ISSUE TITLE
Ranger Deep Integration ability not working on Eagle Spirit Companion

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2412]
The Eagle companion does not seem to be getting the advantage of the ranger pack tactic ability Deep Integration, unlike the wolf and the bear.

[No Advantage.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10713852/No.Advantage.zip)

**Comment by ThyWoof** [comment]
Only reason I can think of is it’s a flying creature. Will take a look.

**Comment by ThyWoof** [comment]
fixed on DEV but you'll need to re-summon for pack tactics to get applied correctly.
