### ISSUE TITLE
Multiclassed casters can upcast to non-existent spell slots

### ISSUE THREAD

**Issue by Cypher121** [SolastaMods/SolastaUnfinishedBusiness#2413]
Setup: character with 1 level in Divine Heart Sorc, Bard at any level 1 short of a new spell level, e.g. 8. Likely also works with any other full caster.

The game will now let you upcast spells to slots of the level you'd unlock if you weren't multiclassing.

**Comment by ThyWoof** [comment]
Not sure if I understood. Please share screenshots.

**Comment by Cypher121** [comment]
![image](https://user-images.githubusercontent.com/8020624/218270750-74f95e3e-8a68-4a3d-aadd-15f7c2c0ca24.png)
![image](https://user-images.githubusercontent.com/8020624/218270757-36b8dd08-a963-4e4a-aac5-652930b7da1e.png)

Bard 9 would've unlocked level 5 slots, so game lets me upcast to them on bard 8/sorc 1

**Comment by ThyWoof** [comment]
This is how shared slots work. You are a level 5 caster in this scenario. Google for Multiclass calculator

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/218272122-28eb7205-e154-41d1-aae1-a8244bcf1fcb.png)
