### ISSUE TITLE
Game stuck after Crusher Feat on reaction

### ISSUE THREAD

**Issue by armageddondrake** [SolastaMods/SolastaUnfinishedBusiness#2423]
The game hangs it self after Crusher gets used on a reaction from sentinel and polearm master, and the enemy gets repositioned. The game seems to try to attack or calculate some new thing to do, but can't seem to handle the repositioning and the logic of the Ai seems like stuck in a loop and does nothing.

It seems related to the lag that happens after crusher with the repositioning get used on an action.

**Comment by ThyWoof** [comment]
Hmm. So in SP there is this 6s lag that ends up resolving but in MP becomes an infinity loop?

**Comment by armageddondrake** [comment]
Yes, when it is players turn and crusher is used, there is this 6s lag that ends. When it is the Ai turn and the player uses a reaction with crusher the 6s lag never resolves and the Ai does nothing stuck on its turn.

**Comment by armageddondrake** [comment]
I should add, that this bug happens when the movement speed is not reduced to 0 by sentinel. I think it is not reducing the movement to 0 because the reaction is not labeled as an opportunity attack.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/218334779-dcaab0b4-3a59-4614-aa2e-2c01e626256f.png)
I have a hunch why this is happening so did a simple fix and tested. Haven't tested extensively but was able to use Crusher on MP.

**Comment by armageddondrake** [comment]
Hmmm, try how it interacts with multia-attack. The enemy unit attacks once gets a reaction attack that crushes it 1 field from the target. Than it is stuck, presumably because it can't issue the second attack on a target. 
First I realized this bug against brood of blood in a 2 field narrow corridor where they could come down the from the edge and could immediately attack my front row, while my other units were in attack range with pole weapons.
Later I had this bug when the enemy moved right infront of my front row attacked once my back row crushed with the long mace and the enemy couldn't attack any thourther with their second attack

**Comment by ThyWoof** [comment]
Fixed on DEV. Can I have your save to test their as well?

**Comment by armageddondrake** [comment]
Now the game doesnt issue reaction properly. After the first Reaction when an enemy enters the attack range, all other instances of entering the attack range do not trigger a reaction in all following turns.

**Comment by armageddondrake** [comment]
[dimiSolo2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10722294/dimiSolo2.zip)
Here is my safe file
[dimi 2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10722306/dimi.2.zip)
and this is the safe file of the first bug if it helps
