### ISSUE TITLE
EB activating Crusher

### ISSUE THREAD

**Issue by SeanGDonohue** [SolastaMods/SolastaUnfinishedBusiness#2448]
he is also a multiclass warlock with Eldritch Blast and Repelling invocation, and the Crusher option appears when he hits someone with Eldritch Blast!

Save file attached, from the Lost Valley campaign..
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10726911/AutoSave_1.zip)

**Comment by ThyWoof** [comment]
fixed shield bash but this EB thing is really odd.

**Comment by ThyWoof** [comment]
fixed on dev.
