### ISSUE TITLE
Cannot Export Settings

### ISSUE THREAD

**Issue by DoctorMidnight** [SolastaMods/SolastaUnfinishedBusiness#2450]
Exporting settings gives the following error:

![Error](https://user-images.githubusercontent.com/124534142/218627128-4d26e549-da9f-4f5f-bb3c-255da7c7f849.JPG)

**Comment by ThyWoof** [comment]
Which OS do you use?

**Comment by DoctorMidnight** [comment]
Windows 10

**Comment by ThyWoof** [comment]
gaming platform? GOG, Steam, etc?

**Comment by DoctorMidnight** [comment]
SteamSent from my iPhoneOn Feb 13, 2023, at 8:23 PM, Paulo Monteiro ***@***.***> wrote:﻿
gaming platform? GOG, Steam, etc?

**Comment by ThyWoof** [comment]
Given this works on all computers I test: Mac OS, Windows Steam, Windows GOG, my best hunch is the folder <GAME_FOLDER>/Mods/SolastaUnfinishedBusiness/Settings is read-only causing this error.
