### ISSUE TITLE
Fighter class 6th level bonus feats not working

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2481]
At level 6, Fighter get the Ability Score/Bonus Feat and the 2 extra bonus feats. The 2 bonus feats part work fine. The ability score also works fine. However, if you pick Bonus Feat instead of Ability Score the next screen still only show 2, not 3, bonus feats. Example shown below of my fighter picking Bonus Feat option. Save also included latest version .39 and game is played with Vel Leverage custom campaign.

[Leverage.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10753288/Leverage.zip)

![20230215213134_1](https://user-images.githubusercontent.com/9156490/219298081-421d378a-5c39-4977-afa0-91c118ea92b4.jpg)

**Comment by ThyWoof** [comment]
In reality the max number of feats you can take is 2. If you take ability score only then you should take 1 feat. This is incorrect as mod is offering 2. It'll happen on Fighter 6, 14 and Rogue 10. A bit hard to fix so I suggest you play with the mod options to avoid getting more feats than you should.

Won't fix as a very collateral scenario.
