### ISSUE TITLE
Scorching Ray shows up in Spell Sniper feat list

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#2516]
All the other cantrips show up correctly after taking the Spell Sniper feat, except the level 2 Scorching Ray shows up for some reason...
![20230219154614_1](https://user-images.githubusercontent.com/9156490/219991268-7a8b0c93-259a-4edd-8611-a77c5f77ce91.jpg)

**Comment by ThyWoof** [comment]
Which mod version? This was fixed a while ago.

**Comment by ThyWoof** [comment]
fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/853f46dbcd7bf498fa3e04f69a23d1293f009bde).
