### ISSUE TITLE
The Feat "Astral reach" doesnt seem to work as intended

### ISSUE THREAD

**Issue by TennoSerra** [SolastaMods/SolastaUnfinishedBusiness#2535]
I was trying to make work a Sentinel+Astral Reach build on my Discordance monk (Great Sub-Class BTW) and the part of the feat that is supposed to trigger an opportunity attack at 10 feet doesnt do anything?

Maybe I am actually wrong? and dont understand how it is supposed to work?

![image](https://user-images.githubusercontent.com/68448913/220476857-4aecf19d-84b4-4619-80e5-1abb83018d29.png)

**Comment by ThyWoof** [comment]
Please add screenshots and your game save.

**Comment by TennoSerra** [comment]
[Location.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10798953/Location.zip)
This is my save, A screenshot would prob not help at all cause you have to see how the enemies get into range for it to "Trigger"
Its not a campaign save, because I was testing the whole interaction on a Test Character and Test Campaign before doing it in my actual playthrough.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/220494544-4b9d8272-55ce-42f0-b66c-a258a1ba3dfd.png)
Only with Unarmed. working as intended.

**Comment by TennoSerra** [comment]
Oh it doesnt apply when you have a monk weapon in your hand, I thought it would just use an "unarmed strike" for the reaction instead of the weapon. Didnt know it would simply not work when a monk weapon was in my hand. Thank you anyway!
