### ISSUE TITLE
Dance of war issues description issues

### ISSUE THREAD

**Issue by armageddondrake** [SolastaMods/SolastaUnfinishedBusiness#2539]
Heart seeking shot tiggers on melee bar handed attacks.
Ranged attacks are considered by dance of war as auto misses. 
If both behavios are intended to work like that, the description doesnt fit them.
here is a save to see more
[dimsven2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10808538/dimsven2.zip)

**Comment by ThyWoof** [comment]
Heart Seeking is a bug. Need a screenshot to description you're suggesting to change on Dance of War.

**Comment by armageddondrake** [comment]
I would just add this little thing to make it clearer.
![Dance_of_War_edit](https://user-images.githubusercontent.com/44398396/220839774-dd93c1d8-cb4c-44f8-8797-273d924c1cbc.png)

Raven Rogue attacking with Dance of War multiple times a round and criting the momentum bonus sounded too good to be true

**Comment by ThyWoof** [comment]
thanks. updated on dev.
