### ISSUE TITLE
smite spells showing up on classes that should not have it on spell list. 

### ISSUE THREAD

**Issue by radium989** [SolastaMods/SolastaUnfinishedBusiness#2544]
Was creating a sorcerer and saw smite skills like thunderous smite in the spell selection screen.

**Comment by ThyWoof** [comment]
This isn't a bug. It sounds like you simply selected everything under the mod UI spells panel... Or you're multiclassing with a Paladin.

Also, next time you report a possible bug, adding a screenshot is always useful.
