### ISSUE TITLE
Combat ending loop

### ISSUE THREAD

**Issue by jmauro** [SolastaMods/SolastaUnfinishedBusiness#2547]
Hello,

I am using the last release of UnfinishedBusiness (French version) and each time I load your Mod when fighting there is a Popup saying that a mod is unstable then the combat starts, the first action triggers, but it seems stock waiting the dice to roll...

Here are the logs
[Crash solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10813481/Crash.solasta.zip)

Let me know if you need something else.

Kind regards,
JM

**Comment by EnderWiggin** [comment]
Can you elaborate on which save is broken? Or what steps you do before saving when it breaks? That archive has lots of them. Tried loading auto save that was made at the start of combat with the ranger and the wolves. Also tried saving in that combat and loading - no errors.

**Comment by jmauro** [comment]
> Can you elaborate on which save is broken? Or what steps you do before saving when it breaks? That archive has lots of them. Tried loading auto save that was made at the start of combat with the ranger and the wolves. Also tried saving in that combat and loading - no errors.

That is exactly my issue, when loading the save just before the wolves fight. The fight starts, then I try to launch a light spell with my wizard the animation starts then nothing happen, the game is not frozen but nothing happen, I am forced to kill the game.

Is there a way to record the sequence?

**Comment by EnderWiggin** [comment]
So error happens not when loading a save, but when casting Light cantrip?

**Comment by jmauro** [comment]
Here is the [link](https://filetransfer.io/data-package/Zl9j1KP4/1wbF4UlgTr0CBU9IVSliwP) with the video

**Comment by EnderWiggin** [comment]
Is your game up to date? What's game version and mod version?

**Comment by jmauro** [comment]
The mod version is 1.4.33.46 and the game version is 1.4.25

**Comment by EnderWiggin** [comment]
that's your problem - your game version is too old. Update to the latest. First 3 numbers in mod version is version of a game we support.

**Comment by jmauro** [comment]
Oh ok, didn't know, and thanks for the tip... 

Sorry for the noise.

Kind regards,
JM

**Comment by jmauro** [comment]
BTW, thanks for the mod, and thanks for taking the time to look at my issue.

Kind regards,
JM

**Comment by ThyWoof** [comment]
Can you please buy the game? Not cool to use a pirated version.

**Comment by jmauro** [comment]
> Can you please buy the game? Not cool to use a pirated version.

It was for testing purposes and I intend to buy it. Does it answer your question?
