### ISSUE TITLE
[1.4.33.49] Advancing game time does not advance crafting

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#2581]
Under Gameplay > Tools > Adventure, using "Increase game time by" correctly advances the clock, but does not progress crafting (or other time-based resource usage, such as food).

It might be a feature request, but perhaps a checkbox option could be added to actually advance progress when this feature is used?

An alternative would be to allow Short Rests to last longer than 1 hour to avoid doing a dozen of them when crafting something that doesn't take 24 hours. Maybe add 6 hour and 12 hour Short Rest buttons to the game UI? Not sure what is easier.

**Comment by ThyWoof** [comment]
Use the other option to reduce crafting time if that is your use case. Not a bug.

**Comment by Andargor** [comment]
> Use the other option to reduce crafting time if that is your use case. Not a bug.

That is a workaround, which from my understanding requires the following steps to perform if one does not wish to simply avoid crafting and spawn the item in question:
- Click Increase game time as desired
- Reduce crafting time by a percentage calculated according to the time increased
- Perform a Short Rest to complete crafting
- Reduce Crafting time by 0% to go back to normal

This would need to be performed every day if you wish your party to adventure at night and use crafting.

Does this require a separate feature request?

**Comment by ThyWoof** [comment]
It’s simpler than that. Waiting on crafting on custom dungeons suck and doesn’t add much to game. Simply reduce the time and call it done.
