### ISSUE TITLE
[1.4.33.49] Divine Favor damage is added to spells

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#2585]
If the intention was to emulate the 5e Divine Favor spell, damage should only be applied to weapon attacks. Instead, it is currently also applied to spell damage. For example, it adds 1d4 to each Eldritch Blast beam (see attachment).

![0K7PnwF](https://user-images.githubusercontent.com/3580755/221375460-7dd08194-0c47-4b97-ae15-a02e8686b50f.png)

**Comment by ThyWoof** [comment]
Thanks for reporting. We found out this is caused by a vanilla game bug. We will check if there is an easy fix but will share as well with TA developers.

**Comment by EnderWiggin** [comment]
Isn't Divine Favor a vanilla spell?
