### ISSUE TITLE
Execution Fighting Style: applying on all attacks

### ISSUE THREAD

**Issue by dropthedie** [SolastaMods/SolastaUnfinishedBusiness#2606]
The **Executioner** fighting style is supposed to "You add your proficiency bonus to damage against creatures that are blinded, frightened, restrained, incapacitated, paralyzed, prone, or stunned."

I tested 3 different characters in the official campaign, the "Isle of Domination" third party release, and an empty combat room I made for the purposes of testing. On melee and ranged attacks, regardless of circumstances, a bonus to damage equal to the character's proficiency bonus is being applied. (+2 at 1st level, +4 at 10th level, etc).

I tested against badland spiders, giant crows, bandits, black bears. Tested with fighters, clerics, paladins, rangers. Tested with multiple races and combinations - they seem to apply all a flat bonus to damage instead of requiring any ailment on 
![1](https://user-images.githubusercontent.com/86467719/221442798-32cc85b6-9181-4291-96fc-71c1726f0079.PNG)
![2](https://user-images.githubusercontent.com/86467719/221442800-d3647825-5c7f-4913-aa7f-79a628f25aa9.PNG)
![3](https://user-images.githubusercontent.com/86467719/221442803-75e9d519-79b2-407b-a1a2-24e3d697c5d3.PNG)
![4](https://user-images.githubusercontent.com/86467719/221442807-2e69c6ac-716f-4efc-8863-5912ba83f05b.PNG)
the target.

**Comment by ThyWoof** [comment]
can I have a save as well as the location used?

**Comment by ThyWoof** [comment]
Fixed on dev.
