### ISSUE TITLE
Undead summoning issue

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2609]
Whenever I upcast a undead, duration wont increase. It stays for 1 minute even with a spellslot lvl 8 (for exemple, I upcasted a Skeleton Marksman (spell lvl 5) with a spellslot lvl 8 and it still vanishes after 1 min. (no rests)

**Comment by Aelyx93** [comment]
I can get you screenshots if you want, but the issue is quite straightfoward... The upcast wont make the creature last longer as it should in the spell description. I did work before this week's patches. Also, I still have that issue with the studdedleather armor that wont count in my UB crafting recipe... even if you said it work. It does not :/ is it one of my mod settings or something?

**Comment by ThyWoof** [comment]
We always need save files on any bug report as well as your settings file. It isn’t strait forward if we have to create a hero, an encounter, etc for every single report.

**Comment by Aelyx93** [comment]
Fine, can you help me with that then ? Where can i get those and send em to you.

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/wiki

**Comment by ThyWoof** [comment]
On crafting: are you referring to https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/2514 where we did our diligence and shared screenshots? None from your end?

**Comment by Aelyx93** [comment]
So here's for that save about undead summoning issues.
[https://drive.google.com/file/d/1o0bqkWwzflYiHktkADTeIdKZUhwDBa5K/view?usp=share_link](url)

here's my mod settings (i'm not using any other mods btw)
[https://drive.google.com/file/d/11BI31I2rDuvXivvpJZd5GVNOOSTyvW9P/view?usp=share_link](url)

For the crafting issue, I cant give you those screenshot for I dropped the studded leather some games ago and dont have the save anymore. If you load the save linked above and add a studded leather armor to your inventory, you'll see that any UB crafting involving it wont work. Thanks again for your help, our gaming community love your mod.

**Comment by ThyWoof** [comment]
Upcasting time in solasta is bugged as hell. So changed it again…

it should now increase number of summons every 2 upcast levels, remove concentration on any upcast, have the durations set to 1, 10, 60, 8 hrs, 1 day depending on level

**Comment by Aelyx93** [comment]
Thanks for your trouble.

**Comment by Aelyx93** [comment]
Close the issue whenever the mod is updated, thx again. If you find anything for my crafting issue, feel free to let me know. Good night!

**Comment by ThyWoof** [comment]
All I can suggest is check all boxes under the crafting section and double check you're not using any modified Studded Leather on custom campaigns. Recipe requires a standard Studded Leather. Not even prime.
![image](https://user-images.githubusercontent.com/13087646/221760780-2c194f32-d122-42f7-9c95-dca0de159c86.png)

You should have access to this same debugging screen on your end that lists all game blueprints in case you get in trouble again.
