### ISSUE TITLE
Rage not working consistently (possibly due to multiclass)

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#2610]
I have a Fighter to 5, then Barbarian 1.  When I rage in combat (most the time and always for piecing) it's not halving the damage. 

It should be noted that we are playing multiplayer.
[Solasta Bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10835701/Solasta.Bug.zip)

**Comment by ThyWoof** [comment]
I cannot reproduce on a local save.
![image](https://user-images.githubusercontent.com/13087646/221481707-ab0773f0-7403-4e97-89c2-c6e59ba87c2b.png)
Rage is there in the hero.
![image](https://user-images.githubusercontent.com/13087646/221482099-3a2297b0-7e4a-4cad-94c5-0e7e520f79b1.png)
Finally I exported your hero to test on a custom campaign and all works.
![image](https://user-images.githubusercontent.com/13087646/221482910-1f690a78-3867-4913-80eb-cd3b11a706ec.png)

**Comment by Werewind1e** [comment]
It mostly does not work when you are hit with piercing damage.  It is not consistent.  It almost never works for piercing and some times does not work for bludgeoing/slashing.  Next time it happens, I'll get a screenshot.

**Comment by Werewind1e** [comment]
![Combat log - Activating Rage](https://user-images.githubusercontent.com/55240348/221582925-1c4282c3-9b3d-4eda-8d84-d8780b831593.PNG)
![Combat log - Rage full damage](https://user-images.githubusercontent.com/55240348/221582952-00a8e2d0-11a8-4c93-9a50-8d1229b6962d.PNG)
![Screenshot Malk Raging](https://user-images.githubusercontent.com/55240348/221582963-a8c28a84-4f36-4aee-bac7-c3011575a3ca.PNG)


It didn't take much effort to find it not work.  Here are the screenshots.

**Comment by Werewind1e** [comment]
![image](https://user-images.githubusercontent.com/55240348/221583323-439becf9-e892-41f6-a946-7452e1abb7b7.png)

We are playing on the hardest difficulty and there is a damage modifier.

**Comment by Werewind1e** [comment]
Meaning that it's something you cannot fix?

**Comment by ThyWoof** [comment]
I suggest you setup a safe without the mod using one of the custom campaigns, a pure Barbarian and high difficulty settings to reproduce and share with TA.

Resistance is exactly the same logic regardless of damage so it isn’t that.

**Comment by ThyWoof** [comment]
Found some notes from TA where they keep fixing Barb resistance. Can you double check if this is not triggering on magical piercing, bludgeon, etc?

**Comment by Werewind1e** [comment]
I am not sure how to do that, but Rage works on all piercing, slashing and bludgeoning regardless of magic.

**Comment by dropthedie** [comment]
I did some testing:

Spy attacking with crossbow: Working
![image](https://user-images.githubusercontent.com/86467719/221655784-27f531ba-fe55-4acd-85ac-0c3b151b854d.png)

Giant Crow attacking with beak: Working
![image](https://user-images.githubusercontent.com/86467719/221656623-798e819e-8499-4d9e-9489-f7d2ba9e4c04.png)

Spy attacking with +40 to hit dealing piercing and bludgeoning damage: Working
![image](https://user-images.githubusercontent.com/86467719/221658923-92bd54b4-eae4-459d-994a-5be63ceeecca.png)

I tested each for 8-10 attacks and they all seem to be working correctly for a standard Barbarian.

Multiclass (Barbarian 3, Fighter 1) also works:
![image](https://user-images.githubusercontent.com/86467719/221660367-0e7ddd97-637a-4d63-a581-b08a7f5d3a24.png)

And on the highest difficulty (Cataclysm) with a damage multiplier, it still works:
![image](https://user-images.githubusercontent.com/86467719/221661741-687a45b5-8523-40c9-97ed-0d07d4412a8d.png)


No one's saying it's not happening to you, just that we can't seem to recreate it. I tried for about an hour.

**Comment by ThyWoof** [comment]
please reopen this one if you have a consistent way to reproduce the issue.
