### ISSUE TITLE
Druid can't use bonus action attacks while in wildshape form.

### ISSUE THREAD

**Issue by CaduMaverick** [SolastaMods/SolastaUnfinishedBusiness#2619]
The following features that provide a way to attack with bonus action don't work when a Druid is in wildshape form:
Monk bonus unarmed strike (it kinda works if you use Flurry of Blows. When you use Flurry of Blows, you just repeat the Multiattack action that the beast has. Ex: If you use Flurry of Blows while in a Dire Wolf form, you perform a total of 2 attacks, but if you use Flurry of Blows in a Brown Bear form, you perform a total of 4 attacks).
Barbarian Path of the Berseker Frenzy.
Pugilist (It adds the bonus 1d4 damage to the strike, but it doesn't let you attack/shove using a bonus action).

Version of Solasta: 1.4.33 - Public (according to the title screen), last official steam release.
Version of Solasta UB: 1.4.33.52, last release
No other mods.
My "AppData\LocalLow\Tactical Adventures\Solasta" Folter: [Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10852082/Solasta.zip)

**Comment by EnderWiggin** [comment]
I assume it doesn't work with feature disabled too?
