### ISSUE TITLE
Healer feat works when in Druid Wildshape

### ISSUE THREAD

**Issue by eido71** [SolastaMods/SolastaUnfinishedBusiness#2626]
Version 1.4.33.51

Currently a Druid with the Healer feat is able to Use Medicine, Resuscitate and Stabilize while in wildshape form.  While the wildshape rules as written state that any action that requires hands is "limited to the capabilities of your beast form". This probably means the Healer feat should be denied to the druid in wildshape form.  There is a possible exception for the Gorilla (L10 wildshape). May not be a bug, may be working as intended and/or within constraints of the game.

**Comment by ThyWoof** [comment]
Can you help us here: https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/2627

**Comment by ThyWoof** [comment]
closing this as we're collecting more info on #2627
