### ISSUE TITLE
Cannot use SoulBlade Warlock's Soul Empower on Two-Handed Weapons

### ISSUE THREAD

**Issue by DeuzenFIN** [SolastaMods/SolastaUnfinishedBusiness#2634]
Soulblade Warlocks cannot use their Soul Empower -power (CHA modifiers to hit and dmg) on two-handed weapons.
Missing info from description, or a bug? Arcane Fighter Wizards, for comparison, can use their Arcane Weapon -power on two-handed weapons without issue.

Solasta v1.4.33
UB v1.4.33.54

**Comment by ThyWoof** [comment]
By rules. Only if you get pact of blade.
