### ISSUE TITLE
Law Cleric hits self with Holy Retribution

### ISSUE THREAD

**Issue by SilversmithFara** [SolastaMods/SolastaUnfinishedBusiness#2648]
Vona attacked herself with her Holy Retribution. (Vona channels divinity to activate Holy Retribution. Vona sustains damage: 19 Psychic.) Can anyone help me figure out why? Screenshot and save file attached.

![Vona sustains 19 Psychic Screenshot](https://user-images.githubusercontent.com/126917948/222852502-97bbfc4a-c190-4c62-9c21-08ee6f174a28.jpg)

[Imogen Vona Moonsilver James 11.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10886843/Imogen.Vona.Moonsilver.James.11.zip)

**Comment by ThyWoof** [comment]
I don’t know. You should ask the game developers as this is a well known bug. Google for “Solasta Holy Retribution bug”. It exists for almost a year now.

**Comment by SilversmithFara** [comment]
Oh... Fair enough!
