### ISSUE TITLE
Mod Instability error during Inventor (grenadier) character export

### ISSUE THREAD

**Issue by SolitonMan** [SolastaMods/SolastaUnfinishedBusiness#2667]
Hello,

I've been playing through the A1-A4 slavers series of modules with the same four characters that I created at the start of A1.  I noticed at the end of A2 that the final save on exiting the module resulted in an error for the inventor character.  The fighter, bard and sorcerer were all ok.  I used the character level feature on the Solasta home screen to get the inventor to the right level for the A3 adventure, and I experienced the same error for saving the character at the end of that module.  Again I used the level screen and the Unfinished Business inventory to get the character where I wanted and now have started module A4.  Because of the discrepancy in gaining levels the inventor started behind in XP from the other characters, but I found that you've added a Party Editor and I was able to use that to set the XP in game to the same value as the rest of the party.  On making that change I decided to export all the characters as a test, and again the fighter, bard and sorcerer all exported fine, but the inventor gave the mod instability warning.  If you'd like further info on this please let me know.

**Comment by ThyWoof** [comment]
Please share the save file and the exported CHR one.

**Comment by SolitonMan** [comment]
[save_and_character.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10912336/save_and_character.zip)

**Comment by ThyWoof** [comment]
are you exporting at the end of the campaign or using the mod CTRL-SHIFT-E export feature?

**Comment by SolitonMan** [comment]
I exported at the end of the campaign for the attached save for the third module.  I'm currently playing the fourth module and did the CTRL-SHIFT-E feature to try an export which lead to me posting this, though I didn't attach my latest save from that previously, but I will now in case it's useful.

**Comment by SolitonMan** [comment]
[a4_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10915365/a4_1.zip)

**Comment by ThyWoof** [comment]
fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/6a1b973f46e29c88fe82d4adddae25cb30e14294). Thanks
