### ISSUE TITLE
Cant put repeating shot on any ranged weapon, can only use enhance weapon on them.

### ISSUE THREAD

**Issue by AstartesFanboy** [SolastaMods/SolastaUnfinishedBusiness#2668]
So, the game isnt letting me put repeating shot on any of my ranged weapons for some reason, not sure why. It is letting me put enhance weapon on it though. This is an issue that popped up partway through the campaign i was playing, after I crafted a longbow of accuracy and got the bow master feat is when it stopped working.

**Comment by ThyWoof** [comment]
We need a save please.

**Comment by AstartesFanboy** [comment]
> 

so i started a new game and i figured out what the problem was. When you take the bow mastery feat you no longer can put repeating shot on your ranged weapons, ill send the save file of the new game right now. 
[james save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10914587/james.save.zip)

**Comment by AstartesFanboy** [comment]
i uh wasnt sure how to put a save besides a zip so hope it works

**Comment by ThyWoof** [comment]
The repeating shot feature can only be applied to weapons with the Loading tag. These are crosbows only. Working as designed. You indeed have a crossbow on that save with repeating shot.

**Comment by AstartesFanboy** [comment]
oh ok my bad thought it worked for all ranged weapons.
