### ISSUE TITLE
Bow Mastery - Incorrectly provides bonus shortbow attack after melee attack

### ISSUE THREAD

**Issue by eido71** [SolastaMods/SolastaUnfinishedBusiness#2676]
version 1.4.33.56

The Bow Mastery feat incorrectly awards a bonus Shortbow attack when the first attack is a melee attack but the player then weapon switches to a Shortbow.  The feat description indicates this bonus attack is only awarded if the first attack is a Shortbow ranged attack.

Screenshot 1 - melee weapon equipped - first attack is executed with melee weapon

![image](https://user-images.githubusercontent.com/1198250/223878711-1c877178-fc3b-4aef-88a7-dc7736ea4054.png)

Screenshot 2 - ranged weapon equipped - bonus shortbow attack activated

![image](https://user-images.githubusercontent.com/1198250/223878758-e0af098e-3b40-4f69-bb38-0d72e026e834.png)

**Comment by eido71** [comment]
Tester IRL, paid to break things 🥇 

Also, I have not tried if this is also happens if the first attack is a longbow (or a thrown weapon) then you switch weapons to a shortbow (don't know why you'd do this).

Thank you and the other devs for all the hard work you do to make UB such an awesome mod.

**Comment by ThyWoof** [comment]
This might be happening with other feats and features so will do a full review and check how we can do a better validation.

for now use honor mode.

**Comment by ThyWoof** [comment]
Fixed and tested on my local dev box but cannot push as no internet on computer.
