### ISSUE TITLE
Fighter - Marshal - Encouragement effect active for companions beyond 10 feet

### ISSUE THREAD

**Issue by ThyWoof** [SolastaMods/SolastaUnfinishedBusiness#2678]
### Discussed in https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/2677

<div type='discussions-op-text'>

<sup>Originally posted by **eido71** March  9, 2023</sup>
version 1.4.33.57

The Encouragement ability / effect is active on all players well beyond the 10 feet stated in the description.  That may be a result of how it was coded as it appears to work more like Bless than say a paladin aura.

Screenshot - I moved as far away from the marshal as I was able and still had the effect.
![image](https://user-images.githubusercontent.com/1198250/223967518-8f83ccfe-01e0-45f6-b515-a2cfb8ae9faf.png)
</div>

**Comment by eido71** [comment]
Save attached (from game session in screenshot above, but in the next area) - CoTM - Mind of the Master questline.
[GitHub Export 3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10936535/GitHub.Export.3.zip)

**Comment by ThyWoof** [comment]
fixed but unfortunately you might need to get into a battle for things to get back to normal. on next release.
