### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by FloydNex** [SolastaMods/SolastaUnfinishedBusiness#2680]
Hi,

First I wanted to thank you for your awesome mod, a real bag of tricks :)

I've done my new dlc run with it (only to respec 1 character and few quality of life option) and now that I am level 5/6 the spell selection is broken.
I know it's weird but no problem without it with a non moded save and it can be reproduced easilly.

The problem is I have to restart the whole dlc, so if you have any idea for a easy fix, you'll be my hero

Thank you very much

**Comment by ThyWoof** [comment]
“Spell selection is broken” isn’t very helpful. Screenshots, saves, etc.

We are Warriors here, not Wizards

**Comment by ThyWoof** [comment]
Not bugging at all but we need a save as it’s very time consuming to create one.

**Comment by ThyWoof** [comment]
Any chances you can share a save? I got a controller ready to test?

**Comment by FloydNex** [comment]
Sure, sorry for the delay, you can find it here, 
[](https://mega.nz/file/sKhllYKR#FrLuTPD3t_78sTvkfOzQoMI96mTqbwV8penVOTFW25E)

**Comment by ThyWoof** [comment]
I passed this to TA as it will also happen once they release the DLC. Meanwhile we will have to wait.
