### ISSUE TITLE
Bow Mastery null exception

### ISSUE THREAD

**Issue by XxGeorge** [SolastaMods/SolastaUnfinishedBusiness#2704]
With the latest update there is a bug with Deadeye, the second shot zooms in and never zooms back out. Sometimes it pops up the mod did something wrong messages but not always. Happens if I have deadeye turned on or not and doesn't happen with cleaving attack. I tried three different campaign saves, one from CotM, one from lost valley, and one from a custom campaign, all showing the same behavior.

**Comment by XxGeorge** [comment]
Also tried respecing to see if that might resolve it but it did not.

**Comment by ThyWoof** [comment]
Please share a save.

**Comment by XxGeorge** [comment]
You know what, now that I think about it, it's likely Bow Mastery not Deadeye that has the bug, anyway, save is attached
[Valley.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10952924/Valley.zip)

**Comment by ThyWoof** [comment]
Yep, most likely bow mastery as I’ve touched it on 58. Thanks for the save.

**Comment by ThyWoof** [comment]
This was fixed in DEV.
