### ISSUE TITLE
Spell Bug: Sanctuary (( Currently can not target Self ))

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2705]
Just tried this in the current UB mod.  I was unable to target myself, but I could target other party members.

Official ruling on Sanctuary is that you should be able to target yourself.

<img width="785" alt="Screen Shot 2023-03-12 at 11 11 31 PM" src="https://user-images.githubusercontent.com/4615479/224599967-6f14d3dc-26ba-4a26-9fad-434841b69ec4.png">

**Comment by ThyWoof** [comment]
used same attributes as bless to allow self. fixed on DEV.
