### ISSUE TITLE
Spell Bug:  Sanctuary (( Spell description lacks important details ))

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2706]
The spell description currently says nothing about how attacking ends the spell.   

Could we please add the following to the spell description:

> 
> "If the warded creature makes an Attack or casts a spell that affects an enemy creature, this spell ends."
> -

-----

![santuary](https://user-images.githubusercontent.com/4615479/224602113-c935157c-a32d-4f49-9f37-950c8534db69.png)

**Comment by ThyWoof** [comment]
fixed.
