### ISSUE TITLE
UI layout error

### ISSUE THREAD

**Issue by legendaryhero1981** [SolastaMods/SolastaUnfinishedBusiness#2708]
Hello, author!
First of all, thank you for making such an interesting MOD for this game, but there is a big problem with the interface layout of this MOD, which leads to many functions that can not be operated at all. The fonts are piled together. Please fix it!
![image](https://user-images.githubusercontent.com/8306501/224609842-1b087ebb-63e2-4be1-a115-eb0ee54bcb2c.png)
![image](https://user-images.githubusercontent.com/8306501/224609960-dc5948e8-4355-4b5c-af72-61c9e36cd621.png)
![image](https://user-images.githubusercontent.com/8306501/224610058-92cd6788-d8d3-4030-9e10-183a4eb9fe3d.png)
![image](https://user-images.githubusercontent.com/8306501/224610120-89edbaba-788f-43dc-80c7-eb5528acc86d.png)
![image](https://user-images.githubusercontent.com/8306501/224610209-95dcd6c9-a6bf-4775-90e4-d97d845304f8.png)

**Comment by ThyWoof** [comment]
Bring back your UMM window to 1.0 zoom under settings. There’s nothing we can do to support that.
