### ISSUE TITLE
Possible issue with bow mastery feat and the extra attack with short bow

### ISSUE THREAD

**Issue by randyandsue2131** [SolastaMods/SolastaUnfinishedBusiness#2720]
Playing as multiclass rouge/ranger using short bow for the extra attack that come from the feat bow mastery.  I use hunter's mark, get off the 2 shots allowed because hunters mark was my bonus action.  Character then freezes and I am not allowed to end the character's turn.  I call this out because I noted in the update log today that something had been updated for bow mastery.  This same issue happens if I kill an enemy and apply hunter mark to another character freezes after all shot taken and not able to end turn.  I got a mod instability warning after applying hunter's mark and taking first shot.  I am only using the unfinished business mod.

**Comment by ThyWoof** [comment]
Fixed on dev. Meanwhile rollback.
