### ISSUE TITLE
Acid Claws (melee cantrip) is getting ranged attack penalty

### ISSUE THREAD

**Issue by xanthics** [SolastaMods/SolastaUnfinishedBusiness#2725]
[edit] The ranged attack penalty appears inconsistent.  I had be a non-disadvantage in another fight with my first attack.

![image](https://user-images.githubusercontent.com/3137623/225003202-14b0f010-0248-4492-bb23-b93dedaf38b9.png)

![image](https://user-images.githubusercontent.com/3137623/225003307-ce1d65e4-2433-4183-b3a7-8bd492610a08.png)

As this is a melee range cantrip, should it have disadvantage?

**Comment by ThyWoof** [comment]
Fixed on dev. Thanks.
