### ISSUE TITLE
off-hand crossbows issue

### ISSUE THREAD

**Issue by Lordbat75** [SolastaMods/SolastaUnfinishedBusiness#2726]
off-hand crossbow does not reflect ability damage for **_two weapon fighting style_** in **ranger** characters (possibly **fighters** characters too, i do not test it). All offhands weapons add ability damage with two weapons fighting styles.

Good work with the mod! 
Thank you!

**Comment by ThyWoof** [comment]
this is by design unless you share a trustable source that says otherwise.

```
                    // Make One Handed Crossbow not benefit from Two Weapon Fighting Style
                    if (mainHandSlot.EquipedItem != null && ValidatorsWeapon.IsRanged(mainHandSlot.EquipedItem) &&
                        ValidatorsWeapon.IsOneHanded(mainHandSlot.EquipedItem))
                    {
                        isActive = false;
                    }
```

**Comment by Lordbat75** [comment]
Thank you for your quick response!

The third benefit for the feat **_crossbow expert_** says:

"_When  you  use  the Attack  action  and attack with  a one - 
handed  weapon , you  can  use  a bonus  action  to attack 
with a loaded  hand crossbow  you  are holding_."

It does not says that negates the off hand ability bonus if you gain it via another feat or style
like the two weapon fighting style

In the Sage Advide Compendium from wizard of the coast ( https://www.dndbeyond.com/ ),
(here is the link for the compendium https://media.wizards.com/2016/downloads/DND/SA-Compendium.pdf ) page 7 , crossbow expert, talk about hand crossbows, and it says that you can fire as a bonus action: 

"_**Does Crossbow Expert let you fire a hand crossbow and 
then fire it again as a bonus action?** It does! Take a look 
at the feat’s third benefit. It says you can attack with a hand 
crossbow as a bonus action when you use the Attack action 
to attack with a one-handed weapon. A hand crossbow is 
a one-handed weapon, so it can, indeed, be used for both 
attacks, assuming you have a hand free to load the hand 
crossbow between the two attacks_"

Maybe you can allow instead firing it as a bonus action... Anyway surely it is allowed, at least with two hand crossbows, fire the off hand crossbow once adding the ability damage if you have the propper feature...

Thank you for your time!

**Comment by ThyWoof** [comment]
Thanks. Will remove that logic on next release. Unfortunately it didn’t make on v59 just released

**Comment by Lordbat75** [comment]
Thank you for your time!
I love this mod so much that I donated time ago

**Comment by Lordbat75** [comment]
Sorry for disturbing you again, 
I have just tested that if you have the _ranged expert_ feat equipped you CAN shoot as a bonus action with the **offhand hand crossbow,** and it ADD the ability modifier. 
If you **DO NOT** have the feat and **not** have the _two weapon fighting style_, you can for example shoot a **dagger** (lefting empty your main hand), and it **allow!** you shoot the **offhand hand-crossbow** ONLY if/_when_ you reequip another light weapon in the _empty hand_, and **it does not add the ability damage.**

So possibly the mechanic is right IF you have the _two weapon fighting style,_ and have the _ranged expert_ feat
