### ISSUE TITLE
Mod instability from Flurry of Blows

### ISSUE THREAD

**Issue by SolitonMan** [SolastaMods/SolastaUnfinishedBusiness#2732]
I just started getting a mod instability warning that breaks the game when activating Flurry of Blows while adjacent to an enemy.  I'm attaching a save that is just before I engaged in combat, and three times I've had to hard quit the game because the instability occurred - when it happens the menu is disabled and only the journal button is active.  I did use Flurry with my bow while not adjacent to an enemy and that didn't cause an issue.  I had thought it was related to the Badlands Wraith I'd engaged in the first two runs through the combat, but the third time it was the regular Wraith the monk was next to when I activated Flurry and the instability occurred.  
[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10979962/AutoSave_3.zip)

**Comment by ThyWoof** [comment]
Thanks for the save. Fixed in [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/b6c1e86f766d0b4898686b3d66042b8d1dceb99d).
