### ISSUE TITLE
Barbarian Path Of The Spirits - Bear resistance is currently bugged

### ISSUE THREAD

**Issue by QuantumOwl** [SolastaMods/SolastaUnfinishedBusiness#2736]
It reads
"While raging you have resistance to all damage except psychic damage (Same thing as DND 5e book). It does not provide said resistance if the user is wearing heavy armor. Which should apply RAW even in the tabletop game. 
This one may be due to the devs flawed implementation of Rage and not the mod itself, but i would still love for it to work like in the tabletop game if there is any way of doing it.

**Comment by ThyWoof** [comment]
This is how Solasta implemented Rage in the game. No plans to change that.
