### ISSUE TITLE
Polearm Master Bonus Attack

### ISSUE THREAD

**Issue by XxGeorge** [SolastaMods/SolastaUnfinishedBusiness#2746]
So not sure when this broke or why as it was working before, maybe it has to do with the interaction with cleaving attack as that bonus one does work when I kill someone. Attached a save right before my polearm master character, tried it with cleaving attack active and without and in neither case does it give the bonus attack option.
[QuickSave_6.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10992305/QuickSave_6.zip)

**Comment by rockybutler** [comment]
I just noticed this with a level 2 Fighter.
The Polearm Expert bonus attack does show up if using a spear/quarterstaff, but not with halberd/pike/long mace.

**Comment by ThyWoof** [comment]
I know. already fixed in dev. thanks.
