### ISSUE TITLE
Polearm Mastery fighting style not getting Bonus Action attack

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2747]
I have a 3 Soul Blade/2 Pally with Pact of the Blade to allow for Soul Empower on 2h weapons.  Started with 1 Pally for armor prof, then 3 Soul Blade for the Pact of the Blade, and then 2 Pally for Smite.  Since getting Pally 2, I can't us the Bonus Action attack from Polearm Mastery.

Game version 1.4.33
UB 1.4.33.59

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10993166/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
I know. It’s fixed on DEV.

**Comment by kosocku** [comment]
My apologies.  Shoulda checked the "Closed" issues before I opened mine.  Sorry again :(

**Comment by ThyWoof** [comment]
No worries at all. V60 is out. Can you confirm it’s fixed?
