### ISSUE TITLE
Skin of retribution bug | Reopening #2734

### ISSUE THREAD

**Issue by QuantumOwl** [SolastaMods/SolastaUnfinishedBusiness#2752]
I updated to 1.4.33.60 and Skin of retribution still doesnt seem to be working when casting it on two characters (using Shared Spell metamagic). I created two new characters and leveled the sorcerer up to 3, went into a custom campaign (a simple room with 1 low level enemy I control) and Skin of retribution still only applies to the sorcerer and not the second character. (Both characters get the Temp HP, but the second character does not get the reflect damage applied to him)

Attached a save with 2 characters
Sorcerer with Shared Spell Metamagic + Skin of Retribution Spell
Cleric 1/ Barbarian 3

Steps to recreate
1) Cast Skin of Retribution with the sorcerer
2)Use Shared Spell Metamagic that only targets the ally 
3)Apply Skin of Retribution to Cleric/Barbarian

Results
Cleric/Barbarian will get the temporary HP but not the Skin of Retribution Buff
Sorcerer will not get Temp HP BUT still will get the Skin of Retribution buff

Also attached UB settings xml file in case there is an issue there

[testing chamber.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10997656/testing.chamber.zip)
[settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10997657/settings.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/226081245-93b87ffc-4244-479c-8864-a5c449341aff.png)

now it's fixed for real, lol.
