### ISSUE TITLE
Barbarian Bear resistance outside of rage

### ISSUE THREAD

**Issue by Nerevaristan** [SolastaMods/SolastaUnfinishedBusiness#2753]
The resistance is always working, even not raging.
I respected into Totem Barb midgame and noticed im always resisting against dmg even im not raging, changed armor, restarted the game, nothing changed.

**Comment by ThyWoof** [comment]
Fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/ed81c9826ef055caf04d34e7c88c5558fc718189). Thanks.
