### ISSUE TITLE
Monk level-up issue

### ISSUE THREAD

**Issue by SorceProject** [SolastaMods/SolastaUnfinishedBusiness#2756]
Solasta and Unfinished Business versions CURRENT as of March 17, 2023, 2:00AM.

UB version 1.4.33.60
No other mods.

My main character is a Ranger/Rogue/Monk. Rest at the fire and attempt to level up: all three classes appear to be available for level 10, but Monk 2 is "blocked": upon attempting to take Monk 2, I see a blank level-up screen with no details about HP, proficiencies, feats, etc (just an image of the character: "Previous" and "Finish" are unresponsive). I must 'cancel' and return to choose Ranger or Rogue instead.

My guess is that Monk 2 contains a feat that conflicts with other feats on the character, but I can't think of what. I doubt it is because he is an old vanilla-made character who has suddenly introduced a new compatibility issue after 20+ hours of play, and only for one class, but you never know. Removing all equipment before leveling didn't help. This save follows an ambush battle, but I tested the issue at other fires and got the same result.

[SolastaBugReport.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10999824/SolastaBugReport.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/225945291-1f750854-7be2-4fb4-8dff-60278fcb3815.png)
Tried with a brand new hero and couldn't reproduce. Please RESPEC this hero.

**Comment by SorceProject** [comment]
Thank you for the help!
