### ISSUE TITLE
Crit rules #1 doing too much damage

### ISSUE THREAD

**Issue by ImAkemi** [SolastaMods/SolastaUnfinishedBusiness#2760]
To my understanding when you select the optional number 1 critical rule, where you take the maximum possible roll and add it to the attack. Using firebolt at first level as an example it should deal 1d10+10 fire damage, but instead the game is rolling double the dice, maximum value of the damage, and adding a mod (if applicable) So firebolt is instead dealing 2d10+10 damage as shown

![Solasta_2023-03-17_16-03-01](https://user-images.githubusercontent.com/57920314/226048134-bbe6477a-1524-4bbf-a166-449b914f8ae2.png)

**Comment by ThyWoof** [comment]
Fixed in [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/a8c82a9d1c09621e768f8a2c19bb45e875b3624b). Thanks.
