### ISSUE TITLE
Barbarian Path at lev 3

### ISSUE THREAD

**Issue by WeekendWarriorr** [SolastaMods/SolastaUnfinishedBusiness#2767]
Barbarian level 3 Path (Spirit Path) (Wolf Spirit) Only gives allies advantage and not barbarian. It is supposed to give barbarian advantage
on attacks when raging.

**Comment by ThyWoof** [comment]
We indeed filter Barb on that feature. What does description say?

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/ece2396635689c6a5c2cec768b8d7bea5c139186/SolastaUnfinishedBusiness/Subclasses/PathOfTheSpirits.cs#L305

**Comment by ThyWoof** [comment]
Fixed in [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/a4acc153e6343bb242973f3ec92642143779ee72). Thanks.

**Comment by WeekendWarriorr** [comment]
Thank you for responding and for fixing that.
