### ISSUE TITLE
Spirit Eagle Eye Bite is DC 0

### ISSUE THREAD

**Issue by xanthics** [SolastaMods/SolastaUnfinishedBusiness#2772]
![image](https://user-images.githubusercontent.com/3137623/226164917-40b56773-477f-42d7-8698-76d9fb40ee2a.png)

Once the Wild Master Ranger gets Free Will for their pet, Spirit Eagle -> Eye Bite is DC 0 (always fail).

-----------------------------

Additionally, possibly related, there is a misspelling on the ability it inflicts.

![image](https://user-images.githubusercontent.com/3137623/226165016-d0033300-9183-4409-a468-3dfe392722fa.png)

**Comment by xanthics** [comment]
Spirit Wolf is also DC 0

![image](https://user-images.githubusercontent.com/3137623/226166602-9511a9cd-def6-4156-beee-151d16180f53.png)

**Comment by ThyWoof** [comment]
May I have your save?

**Comment by xanthics** [comment]
UFB Version: 1.4.33.60 [Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11013313/Settings.zip)

Map: [Path of a Hero Campaign.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11013317/Path.of.a.Hero.Campaign.zip)

Save: [bug_eye_bite.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11013319/bug_eye_bite.zip)

Save is on the wolf's turn

I have save by campaign/location enabled so the save file was in `%USERPROFILE%\AppData\LocalLow\Tactical Adventures\Solasta\Saves\CE\Campaign\Path of a Hero Campaign`

**Comment by ThyWoof** [comment]
Is this single or multiplayer?

**Comment by xanthics** [comment]
Multiplayer, 3 people total.  Although I was able to verify it misbehaving in a local game.

**Comment by ThyWoof** [comment]
fixed in DEV to fixed DC 15.
