### ISSUE TITLE
Soul Empower

### ISSUE THREAD

**Issue by Sabamonster** [SolastaMods/SolastaUnfinishedBusiness#2779]
So, I'm not sure if this is intended and I couldn't find specifics listed anywhere in that regard so I figured I would post this in the event it's *not* intended.

Soul Empower for the Warlock will not let me choose any weapon but a one-handed melee.  The power itself says "You can empower a weapon with souls" but makes no specification that it must be a one-handed weapon.  Made a build specifically revolving around GS with the hopes of utilizing it in combination with this ability but to my chagrin it's not an option.

**Comment by ThyWoof** [comment]
You need Pact of Blade to use on 2H.
