### ISSUE TITLE
Warlock Mystic Arcanum problems

### ISSUE THREAD

**Issue by SolitonMan** [SolastaMods/SolastaUnfinishedBusiness#2780]
I noticed when leveling my warlock that there was a glitch during the selection of my 7th level Mystic Arcanum option - no spells were displayed at the time.  I chose Auto to get through the screen, then kind of forgot about it.  Now I'm noticing that I don't have the option to cast my MA spells anywhere.  While my 6th level Circle of Death shows in my Warlock spell screen, nothing shows for level 7.  And the Mystic Arcanum symbol is showing for level five spells when it should be six and seven.  I hope this save helps.
[md_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11023250/md_1.zip)

**Comment by ThyWoof** [comment]
You should have level 7 spells by next DLC. Meanwhile open the spells selection panel and grant the ones we have at level 7 to it.

Not a bug but simply lack of content.

**Comment by SolitonMan** [comment]
I see what you're saying about the lack of content.  But allowing me to select the spells during level up still doesn't give me an option to use them.  I was able to assign a level 8 MA spell but when I select cast a spell, nothing above level 5 is showing.
