### ISSUE TITLE
Main campaign progression stopper

### ISSUE THREAD

**Issue by ImAkemi** [SolastaMods/SolastaUnfinishedBusiness#2789]
I was playing with mod version 1.4.33.60 and was doing Gem Quest: Cradle of Fire. Right after rescuing Brok I got off, and later started the game back up and updated the mod to 1.4.33.62. Each time I attempted to progress and go through the elevator loading screen, the game hit a mod instability and softlocked. I did not have other mods installed. I tried backtracking to the volcano exterior and was able to do so

When reverting to 1.4.33.60 I was able to continue with no issue.

**Comment by ThyWoof** [comment]
Can I have a save before the elevator loading screen?

**Comment by ImAkemi** [comment]
This was when I updated to 1.4.33.62, this should be before the elevator.  The save on 1.4.33.60 is overwritten as I forgot to archive that one.
[QuickSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11025995/QuickSave_3.zip)
