### ISSUE TITLE
Chrashing + extra Use Button with some characters

### ISSUE THREAD

**Issue by Nerzer** [SolastaMods/SolastaUnfinishedBusiness#2790]
The game comes up with a mod warning and a little time after the game crashes, its after the .62 update.

also, some of my characters have 2 Use item buttons with one of the 2 "greyed out".

Attaching save file just before the chrashes.

[QuickSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11026985/QuickSave_1.zip)

**Comment by ThyWoof** [comment]
Fixed on DEV. Will have a new fix release today.
