### ISSUE TITLE
.62 Update causes never-ending turn

### ISSUE THREAD

**Issue by AsmodeusUltima** [SolastaMods/SolastaUnfinishedBusiness#2791]
After installing this update every time I attacked with the Spiritual Weapon spell the attack would occur normally but then the cleric's turn would not end. Game is not really frozen, as I can still access the Esc menu and such, but I have to reload save because the turn just hangs indefinitely. Rolled back to previous update and the problem no longer occurred.

**Comment by kosocku** [comment]
I'd like to add to this that I, too, have the same issue with regards to moving maps being a black screen.  In my case, I was re-running Crown before the new stuff comes out in May.  I'm running UB with a 6-person party (to try to get through some of the longer fights faster and wanted to finish up side quests I didn't do the first time around.)

I am in the Tirmarian Ruins where you get Kythaela.  She asks you to "escort" her to the Copper Vale of Remembrance.  When you leave the ruins, the next place is Coparann, and you are stopped part-way there as she asks you to stop at some ruins.  When the new map loads, it's just a black screen, though you can still hear the game sounds (birds, for example).

1.4.33 game
1.4.33.62 MOD
[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11029030/UB.Bug.reports.zip)
