### ISSUE TITLE
please re-add option to have feats every even level

### ISSUE THREAD

**Issue by geolas94** [SolastaMods/SolastaUnfinishedBusiness#2795]
Update 1.4.33.62 changed the levels you get extra feats on from 2, 6, 10 and 14 to 4, 10 and 16. i preferred the previous version as it resulted in getting a feat at every even level. please re-add this as a option.

**Comment by ThyWoof** [comment]
Thanks for using the mod but it won’t happen for balance reasons. You can always compile your own version of the mod with other feat progression.
