### ISSUE TITLE
Kythaela loses control panel during combat

### ISSUE THREAD

**Issue by AckImDead** [SolastaMods/SolastaUnfinishedBusiness#2799]
![Solasta Error 1 ](https://user-images.githubusercontent.com/128507768/226675516-d610d54d-1819-499a-bfad-975b2d579ac8.png)
![Solasta Error 2](https://user-images.githubusercontent.com/128507768/226675547-7098f38f-efc4-4a93-b30e-32b138009b6b.png)
In error 1 you can see that the control panel is below the screen. 
In error 2 you can see that while I am able to cast spells by using keyboard shortcuts, I am unable to multi-target. 
Version 1.4.33.62 - new Ranger features turned on but not used yet to my knowledge. 
Images and detailed logs included. 
[Player 2023-03-21-1232.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11031106/Player.2023-03-21-1232.zip)

**Comment by mortetm** [comment]
Same thing happens to Lord Hammond

![image](https://user-images.githubusercontent.com/7782845/226679044-dec639da-d9bc-4fc2-ac67-87bd64cc459d.png)

**Comment by ThyWoof** [comment]
Fixed in v63
