### ISSUE TITLE
Game won't continue after using hellish rebuke

### ISSUE THREAD

**Issue by mortetm** [SolastaMods/SolastaUnfinishedBusiness#2802]
When in combat and an enemy attacks the warlock, there is a popup saying "Instability detected" and when my warlock uses hellish rebuke, the enemy's turn never ends. The same happens if the warlock does not use hellish rebuke from the prompt. Everyone is standing there, doing default animations, with "Enemy turn" printed in big friendly letters at the bottom of the screen.

![image](https://user-images.githubusercontent.com/7782845/226754549-c4f05701-83b2-429d-980d-3166a6bd9768.png)

**Comment by ThyWoof** [comment]
What is your game and mod versions? Care to share a save?

**Comment by ThyWoof** [comment]
This is a known issue if you get Hellish on both class and race. Same problem currently exists on next DLC beta build. I shared the problem with TA and will wait for them to fix it.

thanks for reporting. Meanwhile I suggest Respec the warlock to not take Hellish or choose a race that doesn’t have it

**Comment by mortetm** [comment]
Ah, ok! Thank you for all your efforts! Highly appreciated.
