### ISSUE TITLE
Grenadier fast hands broken

### ISSUE THREAD

**Issue by caudaite** [SolastaMods/SolastaUnfinishedBusiness#2815]
The Inventor - Grenadier fast hands was working a couple days ago, but I think a recent update broke it. The bonus action is greyed out and says 'This creature cannot perform this kind of action'

![image](https://user-images.githubusercontent.com/128648177/227050815-80811ae9-70e7-4949-9b87-73a237bf0fb2.png)

[grenadier.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11045128/grenadier.zip)

**Comment by ThyWoof** [comment]
This is already fixed in dev. Thanks for reporting.
