### ISSUE TITLE
Leveling up multi-class

### ISSUE THREAD

**Issue by WeekendWarriorr** [SolastaMods/SolastaUnfinishedBusiness#2819]
i am running a fighter7/inventor4/barbarian1 I aslo have feats with sorcery points and ki points so altogether i  have 7 boxes in the feature and ability recovery box . when i get to the level up screen I cannot level up because the feature and ability recovery box is so long that it pushes the level up button below the bottom of the screen not allowing me to put my cursor on it in order to choose it.

**Comment by ThyWoof** [comment]
Check the mod option under interface / game UI to make this UI a bit better.

**Comment by WeekendWarriorr** [comment]
Thank you very much. Your answer has solved my problem
