### ISSUE TITLE
Elemental Adept benefiting incorrect spells

### ISSUE THREAD

**Issue by xanthics** [SolastaMods/SolastaUnfinishedBusiness#2822]
Latest version of UB1

![image](https://user-images.githubusercontent.com/3137623/227074897-dcdd94aa-f4be-4e19-b41f-2a66d30025f5.png)

![image](https://user-images.githubusercontent.com/3137623/227074953-d314ee01-8687-4e7b-8009-d5755410eaba.png)

**Comment by ThyWoof** [comment]
Can I have a save? Saves (no pun intended) a lot of time on our end.

**Comment by xanthics** [comment]
Multiplayer, 3 people, I'm the host (Xa).

Settings: [Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11046663/Settings.zip)

Map: [Shadows over Brightreach.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11046668/Shadows.over.Brightreach.zip)

Save: [EA_bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11046673/EA_bug.zip)

**Comment by ThyWoof** [comment]
it's not rerolling but there is this UI glitch I'll try to fix.

**Comment by ThyWoof** [comment]
fixed in [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/c21f577118fe7f4fc05d58e462fdd8afaa8ac380). Thanks.
