### ISSUE TITLE
Sanctuary is still bugged.  Can not cast it on yourself

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2823]
UB Version: 1.4.33.63

![santuary-bugged](https://user-images.githubusercontent.com/4615479/227102903-355fa4ec-adf5-4af0-8c42-94198021f855.png)

**Comment by ThyWoof** [comment]
fixed. https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/51551ca9fca7a1e1312c91a5cc57d3e1d369e02a
