### ISSUE TITLE
Critical rule 1 still doing too much damage

### ISSUE THREAD

**Issue by ImAkemi** [SolastaMods/SolastaUnfinishedBusiness#2831]
In the example I am firing a +1 shortbow with 14 dex, I should be doing 1d6+6+3 but instead I am doing 2d6+6+3. 
The mod version is 1.4.33.63

![Solasta_2023-03-23_14-22-06](https://user-images.githubusercontent.com/57920314/227326072-535f4458-51a4-4fca-b0a2-c446e4b61629.png)

**Comment by ThyWoof** [comment]
Tried another fix. In dev
