### ISSUE TITLE
Warlock advanced bind quasit wrong action type

### ISSUE THREAD

**Issue by geolas94** [SolastaMods/SolastaUnfinishedBusiness#2832]
The Invocation description of "Abilities of the Chain Master" states that binding the quasit gives an additional main action, but when used it only gives a limited action like haste, instead of the expected full action, like from action surge. if this is not a bug please reword the description

**Comment by ThyWoof** [comment]
Thanks. Will fix for next release.

**Comment by ThyWoof** [comment]
fixed to be only 1 additional main attack and set desc.
