### ISSUE TITLE
Trapped in Ravensworth Mansion

### ISSUE THREAD

**Issue by ItWasTheWind** [SolastaMods/SolastaUnfinishedBusiness#2842]
When my party (expanded to 6 with UB) is on the Path to Glory quest and has to accept the princess' invitation to Ravensworth Mansion, the Ravensworth exit door is too small to accommodate the expanded party, leaving us trapped there.

BTW just as a side note I thought I should say that UB has been wonderful to use so far and aside from this one issue it has greatly improved my enjoyment of Solasta.

**Comment by ThyWoof** [comment]
Please enable the rejoin party hotkey, ctrl-shift-r under interface / game ui. Use the hotkey to rejoin the party around the first member whenever it happens.

**Comment by ThyWoof** [comment]
Get them all of the blue area, pause, click on each one and set them to move into the blue area, unpause. That should do it.
