### ISSUE TITLE
Improved Terrific Performance - Passive Icon displaying

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2847]
Passive ability.  Icon should be set to "Hidden".

<img width="661" alt="ImprovedPerfBug" src="https://user-images.githubusercontent.com/4615479/227699254-362d550b-d421-4564-aa73-3cedf3a01e7e.png">

**Comment by ThyWoof** [comment]
no need. this will most likely be fixed on next DLC.
