### ISSUE TITLE
Path of Altruism:  Improved Aura of Courage: Passive abilities showing as needing icons

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2848]
Looks like two improved aura's are showing up on the icon bar that should be "hidden":

<img width="569" alt="Screen Shot 2023-03-25 at 5 44 25 AM" src="https://user-images.githubusercontent.com/4615479/227709944-84d03ce4-50f5-40d0-a76a-5e57002e593d.png">

**Comment by jackal242** [comment]
Let me know if this is on my todo list or not.  I think the second icon there would have been Improved Aura of the Guardian, but i need confirmation.

**Comment by ThyWoof** [comment]
no need. this will most likely be fixed on next DLC.
