### ISSUE TITLE
Stuck in Adrasteia's room

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#2850]
Playing Crown with a party of 6.  Just finished the fight with Razan in Adrasteia's room and went through the cut scene to get the gem.  Once the scene finishes, I'm stuck with half of the party outside the room, and the other half stuck in the room still.  The ones inside the room are unable to move, and I'm unable to teleport them, neither using the "return to party" teleport (CTRL-SHIFT-R) or the full-party teleport (CTRL-SHIFT-T).  Also, not sure if it's related or not, but when you hold the ALT key inside the room with the trapped members, Razan's Nameplate still shows off to the side of the room, even though there's no sprite there to interact with.

I've attached all characters as well as the save file in the off-chance that one of those are causing the problem.

Game 1.4.33
UB 1.4.33.64

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11068792/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
do you have a save before the battle? when all heroes are still behind the door?

**Comment by kosocku** [comment]
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11070026/Save.zip)
 This save is from the start of the fight.  2 of my people started outside the door and I had to teleport them to rejoin the party to get them part of the fight.

**Comment by kosocku** [comment]
re-reading your post this morning and I think I misunderstood what you were asking for.  So, here is another autosave file, from before I started the cut scene that starts the fight.
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11071451/Save.zip)

**Comment by kosocku** [comment]
Apparently I was smart enough to save my game right before I started the cut scene (before entering the room), so I've attached that too.
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11094647/Save.zip)

**Comment by kosocku** [comment]
If it helps, I've tried redoing the fight, but this time NOT teleporting the people stuck outside into the room with the rest of the party.  Same issue when the fight is resolved.  I think part of the problem is that the room becomes sealed once you finish the fight so you can't enter it again, so maybe it's trapping the rest of the party in some kind of "null zone" where you can interact with the party (since you have control of them), but it's still outside the boundaries of the playable space?  My programming skills are 20+ years out of date, so ignore me if I don't know what I'm talking about.

**Comment by ThyWoof** [comment]
I’m wondering if there is any variable to force open that door

**Comment by kosocku** [comment]
Or maybe a way to force a teleport at the end of that particular cut scene, before the "null zone" (for lack of a better term) gets implemented?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/230392378-5515d6a4-95ed-42a1-802b-60d110c22dbc.png)
was able to get the party outside the room but not sure if this is the right outcome or if they should rejoin inside the room.

can someone confirm?

**Comment by kosocku** [comment]
At the end of the fight and cut scenes, the room should be blocked off and all party members should be outside the room on the platform, as shown in the pic you posted

Sorry, only now getting a chance to respond.  Don't have access at work

**Comment by ThyWoof** [comment]
Nice. I believe I fixed it then. Would you like to have a new save posted here or a dll you can use to test?

**Comment by ThyWoof** [comment]
Change in code was very subtle. Instead of always trying to rejoin around 1st party member it will first check if any party member is selected and rejoin around him/her. Only if no hero is selected it will rejoin around first member.

On your save I selected one of the 3 heroes outside and used ctrl shift R.

**Comment by kosocku** [comment]
A new save would be fine

**Comment by ThyWoof** [comment]
[FortressOfTheShield-FIXED.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11174894/FortressOfTheShield-FIXED.zip)

here. fix will be on next release. sorry it took so long.

**Comment by kosocku** [comment]
I'm just glad it was figured out.  I can't express enough how much I appreciate the time and effort you put into helping with our issues.  You truly rock!
