### ISSUE TITLE
Can't Level Up Inventor (Armorer)

### ISSUE THREAD

**Issue by johncmcdonough-gl** [SolastaMods/SolastaUnfinishedBusiness#2853]
I went to test out the Inventor in a custom Dungeon, but every time I go to level up, I can't seem to select any infusions. I'm unsure if this  is broken in the main CoTM campaign as well. I'll update this comment when I find out.

**Comment by johncmcdonough-gl** [comment]
It doesn't not appear to be broken in the main campaign, only in the dungeon!

**Comment by ThyWoof** [comment]
As we usual we need a save to act.

**Comment by ThyWoof** [comment]
cannot reproduce at all. is this a brand new hero? if not please RESPEC.

![image](https://user-images.githubusercontent.com/13087646/227736788-58b2a7f4-7779-4616-b6f4-caadd71e9b21.png)
![image](https://user-images.githubusercontent.com/13087646/227736792-954af2fd-dd89-40d0-b13d-b850dd5e8a4d.png)
