### ISSUE TITLE
Weapon Master Momentum taking actions from later action surge

### ISSUE THREAD

**Issue by xanthics** [SolastaMods/SolastaUnfinishedBusiness#2856]
If you Use your Momentum attack (extra attack after killing an enemy) before using action surge, the action surge will grant fewer attacks than expected (but always at least 1).  If you exhaust available attacks, action surge (killing an enemy during the action surge), and then use momentum, you get the expected number of attacks.

UB1 settings: [Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11071666/Settings.zip)

Map: [Terminal Reverie.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11071660/Terminal.Reverie.zip)

Save: [QuickSave_25.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11071661/QuickSave_25.zip)

**Comment by ThyWoof** [comment]
Action surge is odd and I believe happens with vanilla as well. Will check

**Comment by ThyWoof** [comment]
@EnderWiggin , I believe this might be happening with anything that grants an extra attack using our custom behaviors. Any idea on how to tackle it? Maybe attackModes sort order?

**Comment by ThyWoof** [comment]
confirmed this also happens with Haste. Engine limitation.
