### ISSUE TITLE
Rename request for "Harlequin" subclass

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2862]
I feel like the College of Harlequin is pretty much misnamed.  I had assumed it would be like my Jester Class since it's a name is "Harlequin" but after reading the class, it's really just a fighter bard.  Which has nothing to do with the name "Harlequin".

So could we rename it to something that makes since?   Harlequin implies a jester, mime, comic fool.     The Harlequin subclass, as written, is the opposite of that.  He's a fighter with fighter abilities.

A couple suggestions:
* Combat Bard
* Battle Poet
* Sparring Songsmith
* Heroic Bard

**Comment by kosocku** [comment]
For what it's worth, I like the "Battle Poet"

**Comment by jackal242** [comment]
College of the Battle Poet
College of the Battle Bard
College of the Sparring Songsmith
...etc.

**Comment by ThyWoof** [comment]
I'm not the subclass author. It wouldn't be correct to make this change without contacting the author first. Can you find ND on Discord?

**Comment by jackal242** [comment]
Not completed.
