### ISSUE TITLE
Blind Sight Stops Working Sometimes

### ISSUE THREAD

**Issue by delizin** [SolastaMods/SolastaUnfinishedBusiness#2863]
I am playing a multiplayer game with a friend. We both have this mod, and only this mod, installed with the same settings.xml file. Our entire party has blind sight from one thing or another.  

In this screenshot the character is a Moonlit Warlock trying to cast eldritch blast through a fog. It was working previously, then suddenly all of our characters can't see more than one tile through the fog. None of our range attacks or polearm attacks from 2 tiles work. 

![image](https://user-images.githubusercontent.com/6344447/227835140-0bc284df-c1d9-46d6-bd34-d99e82fd35de.png)

Edit: We did some more testing and it seems like it is tied to light effects such as faerie fire on the target. When the enemy has a light effect then it breaks the blind sight.

**Comment by ThyWoof** [comment]
do you have a save?

**Comment by ThyWoof** [comment]
It looks like vanilla isn't considering the polearm range. Can you confirm with another weapon?
