### ISSUE TITLE
Telekinetic refreshes Bonus Action when casting it on yourself, allowing for infinite repositioning.

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#2866]
As the title says. Using the Telekinetic feat on the caster allows the caster to move themselves freely, as the action seems to not cost a Bonus Action as it should. This allows anyone with a Telekinetic feat to infinitely move themselves around at will, with Telekinetic.

Fairly low priority as the user can simply choose not to abuse it, but a unwitting player might not know its unintended.

**Comment by ThyWoof** [comment]
This is a game engine limitation. Won’t fix.

**Comment by Milliuna** [comment]
That's a pity. Would you be open to disallowing it on the caster?
