### ISSUE TITLE
Impossible Load all My Save Game since UB V1.4.33.65

### ISSUE THREAD

**Issue by Exaercase** [SolastaMods/SolastaUnfinishedBusiness#2875]
Hello,

    I've Done the Update of the New Version of the UB. But All My Saves are KO. I Begin the Load of the Save Take a "Mod Instaballity" Message and after some time of load Take a Crash to Desktop With Message "Verify Integrty of Files" (Steam Files Inegrity Check).

     I Put for you my PlayerLog And My UB Mod Config. (NB : The Logs and Setting are Before All Trying Correction Actions i Do below)

    If i Could i  Just Want Add Some Info of what i try before Write here  :
0. I have do an Steam Integrity Check (After Uninstall By UMM The Mod and The UMM Solasta Mod Manger File)
1. I have Remove All Cache in UB Mod Folder
2. Clean the "AppData\LocalLow\TacticalAvanture\Solasta" of All I Could Clean.
3. In my Last Play (with Previous UB Mod), i Have Use the New Fonctions of Modfy in Live Caracter (Only in a Game not the Root Character). I have : Rename (First and Last Name), Remove Two Feats, Lower Root Stats Dex and Wis (Root for Say Not the Stats With Bonus) of One of My Too OverPower Carachter. (NB : i have after no pb too play, save, or load)
4. For test I Have Remove The New File (? i Think) in "AppData\LocalLow\TAv\Solasta\Characters" Folder That have Appears and Had His FileName of The New FirstName of The Modfied Caracther.

Nothing Have Work :'(

Thxs for Any Help
Best REgards, ExA

NB : I Could not Copy directly the Text of Log and Config cause Caracters Number so i put link to my shared part of Drive sorry :(

---------------------------------------------------------------------------------------------------------------------------------------------------

The "Player.log" :

[https://drive.google.com/file/d/1sejeOw6hZ0W6yv3tX36WU6tAgzX4LsuA/view?usp=share_link](url)

----------------------------------------------------------------------------------------------------------------------------------------

My UB Settings.xml (In Root UB, not Save .ini in Settings Folder ;) ) :

[https://drive.google.com/file/d/1XVdRX-urMVxiXLoEGi6Dlv_tN-1eWaWt/view?usp=share_link](url)
-----------------------------------------------------------------------------------------------------------------------------------------------

Thxs for Any Help
Best REgards, ExA

**Comment by Jarrod-L** [comment]
I noticed the same issue today. If you need more data (logs/versions) I'd be happy to provide mine if it would help.

**Comment by ThyWoof** [comment]
Please

**Comment by randyandsue2131** [comment]
Think I am having the same issue here. Since last update I am unable to load saved game.  I get a message that says corupted character file and save does load at all.  Message says this happen because of a mod being used.  The only mod I am using is the current version of UB and I had no issues prior to the update.  I am not sure how to find the save file and character file to upload.

**Comment by ThyWoof** [comment]
I suggest rolling back the mod from gameplay / tools, RESPEC the heroes to level 1, save, update mod again.

**Comment by jeffstokes72** [comment]
Same thing happened to me. I notice it triggers Unity crash handler when I try to load the save game

**Comment by randyandsue2131** [comment]
> I suggest rolling back the mod from gameplay / tools, RESPEC the heroes to level 1, save, update mod again.

This worked perfectly for me!!!!!  Thank you very much for the suggestion!!!  Really didn't want to lose all progress.

**Comment by ThyWoof** [comment]
Everybody else please follow the suggested solution above. Thanks.

**Comment by Exaercase** [comment]
Hello,

   I just read about your solution if i understand (cause my english is bad) : 
1. Revert (already do and all work)
2. Load a save with the updated Charater
3. Respec to Level 1 (I don't want to do that it's like to crate a caracter .......... and i take many time on apprence of my character so i'll never could do it still look like before Respec for me must evoluated to let you choose what you want to stay and what you whant change before that i'll don't repspec .... )
4. In case id do it you say LVL 1 but i'm not LVL 1 so What ?????
5. If i do LVL 1 or LVL X Respec i save and reboot
6. I do the update
7. Change if somthing have to change in UB Conf.
8. Save UB and Reboot
9. And it's you are rigth i could load ALLLLLLLLLLLLLLLLL my save (Cause my pb is i change caracter i One save but none still work after update)

Thank for any help
Best REgards
ExA
