### ISSUE TITLE
Lighting Launcher not activating ranged Expert bonus attack

### ISSUE THREAD

**Issue by Valensfd37** [SolastaMods/SolastaUnfinishedBusiness#2878]
Hi, I noticed in the last update changelog it mentioned that the ranged Expert feat was made to function with the Inventor Lighting Launcher, So I went to try it and it doesn't seem to work.  I'm on the latest Main version, updated through the in-game prompt.

I've included a save right during the artificer turn so you can test it
[RangedExpertLightingLauncher.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11111426/RangedExpertLightingLauncher.zip)

Thank you!

**Comment by IlliteratePig** [comment]
I can second this issue and it seems very reproducible - lightning launcher _never_ works with the bonus action from ranged expert. Notably, it does benefit from being able to attack at 1 square with no penalty.

It doesn't interact well with other feats and fighting styles which should work with the lightning launcher, either, assuming we're using Lightning Launcher as it appears in tabletop 5e.

Regarding the wording, Ranged Expert should unambiguously work with lightning launcher - the wording of Ranged Expert indicates "you can make a one-handed ranged bonus attack." The lightning launcher is one-handed, makes an attack (even a weapon attack, based on tabletop), and uses the attack action.

Archery and deadeye can be somewhat more ambiguous in their function. Archery works with "attack rolls with ranged weapons," and the damage portion of deadeye works "when attacking with a ranged weapon." This means that they absolutely should be testing for if the weapon being used is "a ranged weapon." 

(the cover- and long range penalty-ignoring aspects of deadeye work just fine, as I've tested, which would potentially imply that the Lightning Launcher is a ranged weapon, as 'ranged weapon attack ignores half cover and three-quarters cover")

There isn't much to actually indicate what the lightning launcher _is_ in Solasta, but in tabletop, 
-"Each model includes a special weapon." The attacks granted by armoursmith are unambiguously weapons.
-" It counts as a simple ranged weapon," The lightning launcher is unambiguously a _ranged_ weapon. This would easily and unambiguously satisfy the requirements of both archery and deadeye.

A simple solution may be to grant an item that cannot be dropped (like a wizard's spellbook) whenever activating the Infiltrator mode, which is a one-handed ranged weapon that has the same stats as normal. Using the weapon in a hand will allow it to qualify for all of these interactions without trying to programme special loopholes to check if the armour is a weapon or the attack is a lightning launcher attack, or something.

**Comment by ThyWoof** [comment]
fixed in dev.
