### ISSUE TITLE
Minotaurs cause "mod instability detected" soft-crash on charge

### ISSUE THREAD

**Issue by UWImban** [SolastaMods/SolastaUnfinishedBusiness#2880]
Not sure how to replicate it as it doesn't seem to happen all the time, but Minotaurs and Minotaur Elites often cause the game to soft-crash when they charge. Potential theories: 
- I'm currently playing the custom module Terminal Reverie and I had this issue in multiple maps (both the orc caves and temple of earth so far), both of which were using the DM Pro flat rooms.
- It could be something to do with party members being in stealth and having it cancelled by enemy movement, since it's only happened towards the start of fights the few times it has happened.

Regardless, it pops up the "an instability related to mods you have installed has occurred" popup and the game soft-locks and I need to quit out and retry the fight when it occurs.

**Comment by ThyWoof** [comment]
This is a vanilla game bug we hope TA fixes on DLC. Nothing we can do.
