### ISSUE TITLE
Critical hit with Raven Rogues Heart shot makes action bar disappear

### ISSUE THREAD

**Issue by geolas94** [SolastaMods/SolastaUnfinishedBusiness#2882]
whenever my Raven Rogue gets a critical hit with Heart Shot active the dice look somewhat blurry or shifted, not sure how to describe it, and after the dice disappear the action bar does not reappear. so far i only had crits from the expanded range and not a nat 20, so i cant confirm it also happens on a nat 20.

**Comment by geolas94** [comment]
edit: i just had the disappearing action bar happen on a nat 20 crit of a 1st level chromatic orb from a bard.
some additional info: i am using the critical hit rule 1 and playing a workshop campaign

**Comment by ThyWoof** [comment]
This is the problem. Critical hit 1 is broken and will be fixed on next release.

**Comment by geolas94** [comment]
is there a list of known bugs anywhere so i can check that before opening an issue?
