### ISSUE TITLE
Instability warning selecting gambits at Fighter 3

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#2885]
New run of Lost Valley. After reaching level 3 and long resting, my fighter was the first character to level up. I selected Tactician, Medicine, and Perception Expertise.

I received a mod instability warning trying to choose my first gambit. I tried canceling out and resting again. I also tried reloading an older save. I don't get additional errors, but I can't choose any gambits at all. The Counter-Attack gambit has a minus sign as if I've already taken it.

[Saves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11127327/Saves.zip)

AutoSave_1 in the zip file I believe is the oldest one

Edit to add: I completely quit the game and reloaded AutoSave_1. I was able to level up successfully.

[level 3_good.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11127383/level.3_good.zip)

**Comment by ThyWoof** [comment]
Thanks. Will check in the weekend. Only change gambits had were the new sprites

**Comment by ThyWoof** [comment]
I wasn’t able to reproduce either so probably some other issue that happened before and prevented the level up. Will close this one. If it ever happens again please share a log as well.
