### ISSUE TITLE
Mod instability warning - Minotaur charge

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#2886]
Happened in a random encounter. I was not able to get a save because the game hung, but this should be the autosave from the start of combat.

[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11127932/AutoSave_3.zip)

**Comment by ThyWoof** [comment]
This is a known vanilla game bug we hope it gets fixed on DLC. Nothing we can do on our end.
