### ISSUE TITLE
Darkness cannot be cast on an object

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#2893]
I can attach files, if need be.  Darkness cannot be cast on an object, only a point.

**Comment by ThyWoof** [comment]
Does it work in vanilla?

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/Diagnostics/OfficialBlueprints/SpellDefinition/Darkness.json

**Comment by Werewind1e** [comment]
It does not work on vanilla, but it is supposed to.


   - Magical darkness spreads from a point you choose within range to fill
   a 15-foot-radius sphere for the duration. The darkness spreads around
   corners. A creature with darkvision can’t see through this darkness, and
   nonmagical light can’t illuminate it.
   If the point you choose is on an object you are holding or one that
   isn’t being worn or carried, the darkness emanates from the object and
   moves with it. Completely covering the source of the darkness with an
   opaque object, such as a bowl or a helm, blocks the darkness.
   If any of this spell’s area overlaps with an area of light created by a
   spell of 2nd level or lower, the spell that created the light is dispelled.

**Comment by ThyWoof** [comment]
Please report to official game dec
