### ISSUE TITLE
Can't load any saves after latest update (1.4.33.66)

### ISSUE THREAD

**Issue by HoboZone** [SolastaMods/SolastaUnfinishedBusiness#2896]
As of the latest update, I am unable to load any saves that utilized this mod. I get an instability error at the loading screen after selecting a file and then the game loads indefinitely. It's a Crown playthrough that has been using the mod from the start.

Here are the saves if it helps: [Saves.zip](https://drive.google.com/file/d/1HwspICx5iy3dMEQuRp27cHfuO67uu2gI/view?usp=sharing) 

Not sure if this is something that can be fixed but I thought I would submit this here to see if it's just a problem I'm having or if it is an issue with the mod.

**Comment by MartinBrandstrup** [comment]
I have the same issue

**Comment by MartinBrandstrup** [comment]
Also cannot start a new game

**Comment by ThyWoof** [comment]
1.4.33.67 fixed one hour after.
