### ISSUE TITLE
No Areas will load following latest update

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#2897]
I'm having an issue with in DM. Any area I've made or make, I can't get to load when I try to play test the area. It brings up the splash screen and looks like it's loading, but then it just sits there. The zone never load. Was working before the latest update.

**Comment by ThyWoof** [comment]
Are you on v66 or v67?

**Comment by ThyWoof** [comment]
Update to v67 and reopen if still an issue.

**Comment by TragicSeriously** [comment]
You're right. I had to uninstall and reinstall the Mod to get it to grab the newer update, but one I did everything is working once again. Thank you. Love this Mod.
