### ISSUE TITLE
Summon getting attacked by a Minotaur while under Sanctuary breaks the game

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2898]
It is my suspicion that these conditions are the ones that breaks the game. It could be that the minion or the minotaur part is irrelevant but some kind of combination of Sanctuary + Minion or Sanctuary + Minotaur crashes the game. More testing is required.
Mod version 1.4.33.67, custom campaign Forsaken Isle, game version 1.4.33

[Sanctuary on Minion.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11132900/Sanctuary.on.Minion.zip)

**Comment by ThyWoof** [comment]
This is a vanilla bug. Minotaurs break the game when a charge is attempted. Happens on vanilla too.

**Comment by MartinBrandstrup** [comment]
It is not a charge though it is a melee swing. And it clearly states mod instability in a big dialogue box and then proceeds to hang the game. I am pretty certain it is not the same issue. Same scenario without the Sanctuary buff does not pose any issues

**Comment by ThyWoof** [comment]
Will take a look at the save

**Comment by MartinBrandstrup** [comment]
I saved right before the situation in question. Just end the turn on the current character and the Minotaur is almost guaranteed to hit the skeleton in front of it and crash the game

**Comment by ThyWoof** [comment]
I found the issue and was able to fix the null exception. It’s caused by trying to fetch PB from a summon. It’ll now default to zero which isn’t the best resolution here as the save DC won’t be that high.

how does DnD tackle situations like this?

**Comment by MartinBrandstrup** [comment]
I am not sure I understand the question. Per dnd rules (and I believe as it is worded in this mod too) Sanctuary should take the dc from the caster and should not interact with the target's attributes at all.
Also as a side note, per dnd rules Sanctuary is not supposed to be a concentration spell

And a last ps that has little to do with this exact issue, I have noticed that Sanctuary is missing a buff icon on the portrait on the initative order

**Comment by ThyWoof** [comment]
Cool. So if a summon I better find who casted if for proper DC. Will check if doable

**Comment by ThyWoof** [comment]
fixed condition icon, removed concentration and also suggested to inventor. had to find an intermediate solution for summons DC...

**Comment by UWImban** [comment]
> how does DnD tackle situations like this?

If the summon is a "normal monster" (Conjure Minor Elementals from the PHB, as an example) its proficiency bonus = the proficiency bonus of the monster in question, which is determined by its Challenge Rating. If the summon isn't a normal monster but rather has stats dependent on the spell slot used to cast it (Summon Undead from Tasha's, as an example) its proficiency bonus = the proficiency bonus of the spellcaster.
