### ISSUE TITLE
Feats that are "Class Bound" selectable by any class bug  [[ Hardy and Primate Rage bugged ]]

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#2903]
<img width="1118" alt="Hardy-and-primal" src="https://user-images.githubusercontent.com/4615479/229403680-d5f337e1-7335-4f11-a916-209ea22d4a2d.png">

Hardy is a Fighter only feat.   Notice how it is presenting itself as an option for my Sorcerer.  It should only be presented as option for the Fighter class.

Primal Rage is a Barbarian only feat.  Notice how it is presenting itself as an option for my Sorcerer.  It should only be presented as an option to the Barbarian class.

I believe they should say "Requirement: 4 levels in Fighter class" and "Requirement: 4 levels in Barbarian class" respectfully.   (( So you could select them upon reaching 4th level in either class. ))

**Comment by ThyWoof** [comment]
Fixed
