### ISSUE TITLE
Loot Drop Internal Name Issue

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#2904]
Hi, so in the campaign I'm working on I'm seeing an issue with the loot drop bundles. No matter what internal name I use it tells me the name conflicts with another users internal name or an internal name used by Solasta. To make sure I wasn't just getting very unlucky I tried naming them really off the wall and random names, but no matter what it's named it tells me the name conflicts. I'm using the same format I see already in use in the game for the names. Something like "loot_drop_bandit_two" but have also tried different formats like no spacing, with special characters, without them, adding a long random number to both the beginning and the end of the names. Nothing works.

**Comment by ThyWoof** [comment]
are you sure this is related to this mod?

**Comment by TragicSeriously** [comment]
This is the only mod I run.

**Comment by ThyWoof** [comment]
The fact you use the mod doesn’t mean every single issue is caused by it. The mod doesn’t touch loots in DM. Please try this without the mod and open a ticket with TA dev team.

**Comment by TragicSeriously** [comment]
I suppose it could be something wrong with the game itself. I'll research that and see what I find.
