### ISSUE TITLE
Inventor Armorer - Being knocked unconscious removes the armor model

### ISSUE THREAD

**Issue by johncmcdonough-gl** [SolastaMods/SolastaUnfinishedBusiness#2912]
When being knocked unconscious, it removes the armor model with no way to reapply it mid-combat.

**Comment by ThyWoof** [comment]
As usual we need a save please.

**Comment by johncmcdonough-gl** [comment]
I don't actually have a save for it. I can try to reproduce it tomorrow.

**Comment by ThyWoof** [comment]
added same behavior as soulblade elemental weapon.
