### ISSUE TITLE
Unable to Add Feats from Mod when Creating or Leveling up characters

### ISSUE THREAD

**Issue by zmasiello** [SolastaMods/SolastaUnfinishedBusiness#2921]
Solasta Version: 1.4.33
Unfinished Business Version: 1.4.33.68

When trying to add feats added by Unfinished Business, you can select it, but then the UI goes weird (see screenshot below), and then you can click again and it just goes back to the select a Feat Screen.

Trying to select "Revenant Great Sword"
![image](https://user-images.githubusercontent.com/76893636/230213310-8e8d13d6-df5d-46a6-998c-3246b58ed38d.png)

Selected it
![image](https://user-images.githubusercontent.com/76893636/230213436-55b9c5d4-9a97-4d97-8787-8dab0d87fae4.png)

Clicking anywhere brings you back with the feat not chosen
![image](https://user-images.githubusercontent.com/76893636/230213544-3f701fab-b677-45b4-95f3-d8f31cf16093.png)

**Comment by ThyWoof** [comment]
Not a bug. It looks like you only enabled the group but none of the feats underneath. Enable at least one of the group feats on mod UI.

**Comment by zmasiello** [comment]
A, thanks for the info, spent way too much time trying to get it to work :-)
