### ISSUE TITLE
Description Typo - Elusive Target - Mischief Cleric Lvl 6 Class Feature

### ISSUE THREAD

**Issue by Iggloovortex** [SolastaMods/SolastaUnfinishedBusiness#2928]
Given at level 6 but description says level 8

![image](https://user-images.githubusercontent.com/7705192/230590444-5e9a9cdc-3887-4a9f-8fd9-1949b8313795.png)

**Comment by ThyWoof** [comment]
Please report this to game developer. Vanilla subclass.

**Comment by Iggloovortex** [comment]
ahh my error
