### ISSUE TITLE
[1.4.33.71] Flawless Concentration not working while Wildshaped

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#2936]
We have a Circle of the Night druid with Flawless Concentration. When he is not wildshaped, Flawless Concentration works OK, but when he is wildshaped, it does not give advantage nor ignore damage < 10 HP.

![HvunMk3](https://user-images.githubusercontent.com/3580755/230746683-0c3932a8-c537-4719-8a64-195695bb333c.png)

![bDWCuVv](https://user-images.githubusercontent.com/3580755/230746700-0976ffb2-fb3f-44d7-b211-7c84e3c39e10.png)

![JrSBMQf](https://user-images.githubusercontent.com/3580755/230746704-fcbd04c6-5168-4bc9-9cd6-b3f4b4312afb.jpg)

**Comment by ThyWoof** [comment]
Please report this to original game developer. Flawless Concentration isn’t provided by this mod.

**Comment by Andargor** [comment]
> Please report this to original game developer. Flawless Concentration isn’t provided by this mod.

I reported here because it did not use to happen until a recent release of UB, and Circle of the Night is a UB subclass. The original dev will ask if there are any mods installed, and if yes will also close the issue.

**Comment by ThyWoof** [comment]
Share a save here but I don’t believe related with circle of the night

**Comment by Andargor** [comment]
> Share a save here but I don’t believe related with circle of the night

I posted a save in #2937 and I agree it doesn't seem to be related to the Circle of Night itself, I tested the characters that I used for the test in vanilla, and with UB loaded the bug appeared even if the druid was Circle of the Land
