### ISSUE TITLE
[1.4.33.71] UB is causing Flawless Concentration to not work while Wildshaped

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#2937]
This is a clarification of the previous issue reported #2936

In a vanilla game without UB, Flawless Concentration works both outside and while Wildshaped. With UB installed, Flawless Concentration does not work while Wildshaped.

# Vanilla

![2mVBmlR](https://user-images.githubusercontent.com/3580755/230747365-80be6570-518a-4fa6-bd93-f8d4fcf579ee.png)

# With UB

![w44Cpij](https://user-images.githubusercontent.com/3580755/230747736-781737cf-2b0c-42a9-8600-ca19b04c871c.png)

EDIT: Updated last image with new test after reinstalling UB to confirm

**Comment by Andargor** [comment]
Additional info: Settings.xml and save file (main campaign)

[Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11184502/Settings.zip)

The druid name is Faelar
[druid-flawless-wildshape.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11184503/druid-flawless-wildshape.zip)

**Comment by ThyWoof** [comment]
We have a discussion collecting all cases for wildshape. Will close this one and refer to the issue there.
