### ISSUE TITLE
Barbarian (Path of Light) won't die.

### ISSUE THREAD

**Issue by Sinriel** [SolastaMods/SolastaUnfinishedBusiness#2940]
[AutoSave_8.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11186065/AutoSave_8.zip)

I'm pretty sure you could replicate this with any other save, but no problems - Mephisto won't die! Cheers guys.

**Comment by ThyWoof** [comment]
fixed in DEV.
