### ISSUE TITLE
Multiclass Spellcaster UI conflict

### ISSUE THREAD

**Issue by ViciousMockery** [SolastaMods/SolastaUnfinishedBusiness#2957]
After updating UB and restarting the game today, my first level Warlock spells are where my third level Sorcerer spells used to be.

This morning, the Sorcerer spells were sitting across the top of the action bar (lvls 1-2-3), while the Warlock spells were above the Sorcerer spells.

Now the Sorcerer spells directly above the action bar are 1,2 WARLOCK. It's weird because there is another empty WARLOCK tag still sitting where those spells used to be. I've tried reloading to a save from earlier today before the UB update, but that is doing the same thing. Any suggestions?

![20230411203458_1](https://user-images.githubusercontent.com/130518252/231317989-9ef608d6-c495-4f76-8cbb-eb08a39e37c0.jpg)

**Comment by ThyWoof** [comment]
I’ve indeed touched that to add controller support. To be fixed on next release. Meanwhile you can use the rollback feature under gameplay / tools.

**Comment by ViciousMockery** [comment]
> I’ve indeed touched that to add controller support. To be fixed on next release. Meanwhile you can use the rollback feature under gameplay / tools.

Thanks! I thought that might have been related, but I didn't know how the controller support was supposed to change things.
