### ISSUE TITLE
Monk Way of Distant Hand bow monk weapon broke 

### ISSUE THREAD

**Issue by tyrannodorkus** [SolastaMods/SolastaUnfinishedBusiness#2960]
Currently having issue with the Monk subclass Way of Distant Hand. I'm level 7 and using a Longbow +1, but the bow no longer counts as a monk weapon for the feature Distant Hand Combat.

Solasta version: 
Mod version: 1.4.33.72
No other mods installed
[NewGame++++++.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11207313/NewGame%2B%2B%2B%2B%2B%2B.zip)

**Comment by ThyWoof** [comment]
RESPEC the hero. It’ll fix it.
