### ISSUE TITLE
Way of Distant Hand - Stunning Arrows doesn't function

### ISSUE THREAD

**Issue by taigenraine** [SolastaMods/SolastaUnfinishedBusiness#2967]
I have tried every way I can think of to use this feature.  I have turned the normal stunning strike toggle on and off, I have used the distant hand technique and I have passed.  The ki for the feature never gets spent, I never see a save from a monster, and I never get an option to use the ability.

**Comment by ThyWoof** [comment]
Indeed they are broken. Will try to get it fixed before DLC.
