### ISSUE TITLE
Torch bearer feat crash

### ISSUE THREAD

**Issue by Wildust** [SolastaMods/SolastaUnfinishedBusiness#2970]
Hi, 
First time i try the torch bearer feat (to bonus attack with a torch in hand), and it crashes the game. 
After the main attack of my character, HUD doesn't come back. I'm forced to reload the save.
While loading the save, i got a warning saying that i have an unstability issue with a mod (i only use UB, currently in 1.72). 
Then another warning saying the game is unable to load the savegame, and everything closes to desktop.
Relaunched the game, reload the save, same thing. Back to desktop.

**Comment by ThyWoof** [comment]
We need your save.

**Comment by ThyWoof** [comment]
most likely caused by the DM tool not the mod. Unfortunately the error message will always point us.
