### ISSUE TITLE
Spell selection incomplete when multiclassing in 2 spellcasting classes

### ISSUE THREAD

**Issue by uberj63** [SolastaMods/SolastaUnfinishedBusiness#2971]
Hi,

I created a sorcerer/warlock multiclassed character and pushed it to level 9 (sorcerer 6 / warlock 3) and when I want to cast a spell, my 3rd level sorcerer spells don't display on the HUD.
My 1st and 2nd level display correctly on the bottom row for both by sorcerer and warlock class, but I only get a sorcerer label on the top row with no spell icon next to it.

Can someone do something about it ? I was very excited to be able to twin spell a fireball with this character ! :-)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/231843589-215e0961-a98e-4fe9-aa84-6954df444f94.png)

I assume you are using v72 but you haven't shared that. Update to v73.

**Comment by uberj63** [comment]
You're right, I juste updated to the latest release and it's fine, thanks a
lot !

Le jeu. 13 avr. 2023, 19:54, Paulo Monteiro ***@***.***> a
écrit :
