### ISSUE TITLE
Strange behavior when granting skills or expertise

### ISSUE THREAD

**Issue by ThyWoof** [SolastaMods/SolastaUnfinishedBusiness#2991]
1. Pick rogue (don't take academic for arcana proficiency or take it yourself)
2. Level to 3 and pick Arcane Scoundrel (you should now have Arcana proficiency from Scoundrel)
3. Level Scoundrel to 6, and you will see you have Arcana proficiency but cannot take expertise

**Comment by HiddenHax** [comment]
[Samariah.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11238212/Samariah.zip)
(Level 5 rogue with relevant bugged proficiencies/expertise)

Bugged character that shows Acrobatics expertise upon inspection, but doesn't show expertise on Acrobatics when leveling from 5 to 6.

**Comment by EnderWiggin** [comment]
Happens because game treats any feature that grants 'Proficiency or Expertise' as player having expertise (even if player only got proficiency from it) in the `CharacterBuildingManager.sExpertiseKnownOrTrained`, which makes levelup stage mark it as having static mode (not being able to select it)
