### ISSUE TITLE
About Party Editor

### ISSUE THREAD

**Issue by Codetalker1988** [SolastaMods/SolastaUnfinishedBusiness#2992]
It has no effect when I add the fighting style feats such as 'featTwoWeapon, featDueling' using Party Editor.
But it works when I choose these fight style feats when level up normally.

**Comment by Codetalker1988** [comment]
When I use Ranger's Slay Enemy2 ability attacking Ranger's favor enemy,  It deal 200~400 damage one hit, is it a bug?

**Comment by ThyWoof** [comment]
Oh yeah. Share a save please.

**Comment by ThyWoof** [comment]
There is no difference adding these feats or adding the fighting styles directly. Currently it’s a party editor limitation which I’m not planning to tackle until after DLC. Will close this one but rest assured party editor will be improved later. We have higher DLC priorities.
