### ISSUE TITLE
Multiclass Warlock does not regain spell slots on a short rest.

### ISSUE THREAD

**Issue by NoCrazyShet** [SolastaMods/SolastaUnfinishedBusiness#3005]
In my current game, I'm using the Eldritch Knight build as detailed on the wiki page. When I short rest, I do not regain Warlock spell slots at all. I took 1 lvl Paladin first, then went into Warlock.

Reproduction steps:
1. Create a Paladin
2. Level to lvl 2 and take Warlock
3. Go use a Warlock spell
4. Short rest

No slots are regained, it seems.

**Comment by ThyWoof** [comment]
As usual the possibilities are infinity so nothing we can do unless you zip and share a save.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/232331980-24c8f030-b1d6-4bfa-9f3d-c1486e139267.png)
![image](https://user-images.githubusercontent.com/13087646/232331998-cde5dac5-c2b8-4ae0-ad13-ec1f13edf150.png)

as you can see on sequence not able to reproduce at all.

**Comment by NoCrazyShet** [comment]
Added save here, playing the custom campaign "Island of Domination" - not sure if that is pertinent or not.
Weird that it doesn't affect you. It affects me in multiplayer and in single games, the regular campaign and the custom one. Could it be a mod settings thing? The only mod installed is this one.

[Sewer.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11243078/Sewer.zip)

**Comment by ThyWoof** [comment]
There is nothing wrong. You don't recover spell slots on a short rest. Only pact slots. Your Paladin/Warlock have used 3 spell slots and still has one pact slot avail. Slot colors have meaning.

![image](https://user-images.githubusercontent.com/13087646/232348944-adc1c94c-b055-47e5-8319-fdae62b7e8a4.png)

**Comment by NoCrazyShet** [comment]
> There is nothing wrong. You don't recover spell slots on a short rest. Only pact slots. Your Paladin/Warlock have used 3 spell slots and still has one pact slot avail. Slot colors have meaning.
> 
> ![image](https://user-images.githubusercontent.com/13087646/232348944-adc1c94c-b055-47e5-8319-fdae62b7e8a4.png)

.... My bad, I completely miffed this one. Apologies for wasting everyone's time!
