### ISSUE TITLE
Cleric - protect threshold casts spike growth/thorns instead with no option to break concentration

### ISSUE THREAD

**Issue by chivasRegal3** [SolastaMods/SolastaUnfinishedBusiness#3013]

**Comment by ThyWoof** [comment]
We cannot act if you don’t share screenshots, a save and step by step to reproduce. Help us help you.

**Comment by chivasRegal3** [comment]
![image](https://user-images.githubusercontent.com/130607017/232581187-8cacaa92-418e-4384-8ac8-a72fabc3057d.png)
![image](https://user-images.githubusercontent.com/130607017/232581236-61fba1c0-b953-4e3c-852d-1de80d5a7119.png)
![image](https://user-images.githubusercontent.com/130607017/232581606-4434f841-f00d-4dc3-b91b-34295431e7d3.png)

![image](https://user-images.githubusercontent.com/130607017/232581302-408847fc-0f74-46e4-9933-7ea23a34e059.png)

**Comment by ThyWoof** [comment]
I still need a save and step by step to reproduce in that save. Thanks
