### ISSUE TITLE
Suddenly! Missing Eyes!

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3015]
For some reason all our characters in our current campaign (not the character files, only the instances in the savegame) lost their eyes. This is visible both on the loading lobby and ingame portraits.

Screenshot attached, save game if needed can be grabbed from the other issue I am about to post (multiclass spell slot thing)
![Capture](https://user-images.githubusercontent.com/44898614/232589696-3ac5c515-e593-49fa-b1db-d031770b94b5.PNG)

**Comment by MartinBrandstrup** [comment]
As a note, they are using the expanded eye selection, but not the glowing eye option

**Comment by ThyWoof** [comment]
I wasn't able to reproduce with the other save. In worst case scenario try a long rest, save/reload and if none work, respec.
