### ISSUE TITLE
Warlock/Wizard Multiclass Spell Slots

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3016]
A slightly peculiar situation where I am able to use wizard spell slots to cast pact magic, which I believe is not supposed to work. Furthermore it shows these spell slots as being actual warlock spells and does not make it clear it is using wizard spell slots.

In the attached save file all 3 (campaign item adding a third spell slot) pact magic slots are spent, which can be confirmed by hovering the mouse over the spell slots it claims are available, yet I am still able to cast spells.

If I am mistaken and it is actually raw to cast pact magic with multiclass spell slots, then my bad, but the interface is still misleading.
[Pact Multiclass Spells Slots.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11255106/Pact.Multiclass.Spells.Slots.zip)

**Comment by MartinBrandstrup** [comment]
Also note that since I have Sanctuary as both a warlock and wizard spell, the game gets confused and thinks I have 5 casts of Sanctuary in wizard catergory, though I only have 2 wizard spell slots

**Comment by ThyWoof** [comment]
This is working 100% by the rules. Please get acquainted with them: https://5thsrd.org/rules/multiclassing/
