### ISSUE TITLE
CotM Wildshape- Unable to use actions

### ISSUE THREAD

**Issue by FALK0R3** [SolastaMods/SolastaUnfinishedBusiness#3020]
We have a Circle of the Night Druid that turns into a gorilla and after taking an attack action, cannot move or take any other kind of actions.

**Comment by ThyWoof** [comment]
Only way I can help is if you share a save.

**Comment by FALK0R3** [comment]
https://drive.google.com/file/d/1iZVCTFUKeYqKWM1UEYohTCSNotBMHSEc/view?usp=sharing

**Comment by FALK0R3** [comment]
Hopefully that does it.

**Comment by ThyWoof** [comment]
Please make the link open or simply zip the save and attach here

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/233144809-fcd6d3b9-ce00-48d9-b08c-e9cbab8e753f.png)

I cannot reproduce at all using the same Druid I exported from your save. I need a save in combat as well as all steps you took until you got the soft lock. Impossible to help without this intel.

**Comment by ThyWoof** [comment]
closing...
