### ISSUE TITLE
Feat: Magic Initiate - casting cantrips causes hang

### ISSUE THREAD

**Issue by crucifux** [SolastaMods/SolastaUnfinishedBusiness#3021]
1. took Magic Initiate (Warlock) feat on a new character for a new game. 
2. during the tutorial (wolves combat), casted the cantrip Eldrich Blast
3. log states 'casts Eldrich Blast', and then stops - the combat round will not move forward

**Comment by crucifux** [comment]
[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11267144/AutoSave_3.zip)
Here is the save - try casting eldrich blast on the wolves

**Comment by ThyWoof** [comment]
Can you reproduce this issue outside the tutorial? Reason I ask is it has a bunch of hard coded stuff happening there.

**Comment by crucifux** [comment]
I tried to just attack the wolves with melee and get past the tutorial, but the same thing happens - my round never resolves, and their attack can never begin. I suppose the title of this issue is no longer accurate, as it appears that any action at all will cause the combat to hang. I will try running past or using push, if I can get through it somehow, I'll see if I can repro outside the tut.

**Comment by ThyWoof** [comment]
I cannot reproduce at all on my end using your save so I suggest you check the game files. Not a bug.

![image](https://user-images.githubusercontent.com/13087646/232941039-0ea948cb-8f11-4f19-8098-d61b1b6a2e9c.png)

**Comment by crucifux** [comment]
omg you're right, I was still on v1.432. Updated and now working - sorry for the hassle
