### ISSUE TITLE
Web spell acting weird

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3037]
For some reason these zombies (probably all creatures) gets to keep rolling strength without spending their action (set to free action perhaps?) when restrained until they succeed.

[Web Being Wacky.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11301331/Web.Being.Wacky.zip)

**Comment by ThyWoof** [comment]
This has already been fixed in dev. Will test on your save as well.

**Comment by MartinBrandstrup** [comment]
Cool! You were on top of it I see

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/233804226-353bc0eb-cf7c-4656-af19-8d7844a75512.png)
confirmed with your save as well.
