### ISSUE TITLE
could not find sentinel feat in group 

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3038]
On leveling up, I could not find the sentinel feat in any of the feat groups. Once I deactivated the groups, I could select it as normal.
Is it possible, that sentinel is not assigned to any group?

**Comment by ThyWoof** [comment]
Sentinel is a fighting style so it’s under fighting style adept.

**Comment by ZheToralf** [comment]
I looked through all feat groups, but I couldn't find it.
