### ISSUE TITLE
Trouble with Book of Ancient Secrets eldrich invocation

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3040]
I'fe got the Book of Ancient Secrets eldrich invocation for my Warlock. When I try to learn new rituals from scrolls, nothing happens. I left klick the scroll and say "learn spell". What am I doing wrong?

**Comment by ThyWoof** [comment]
We don't touch book of secrets at all. Can you test without the mod and confirm if us or vanilla?

**Comment by ZheToralf** [comment]
Oh, sorry. I couldn't find it in the wiki, so I assumed it was the mod. Found it now, my bad.
