### ISSUE TITLE
Possibly wrong dice roll for unarmed Monk atk at character lvl 6 

### ISSUE THREAD

**Issue by wtfzambo** [SolastaMods/SolastaUnfinishedBusiness#3044]
Hello, first of all thanks for the work you all put into this mod because it's fantastic.

I'm reporting a potential issue: I have character who's 5 levels into monk and 1 level into fighter.
As far as I understand from the description, monk's unarmed attack should change from a D4 to a D6 after hitting lvl 6 in the monk class.

However, my character is already rolling a D6 for attacks, even if he's just level 5 in the monk class. Screenshots attached:

![image](https://user-images.githubusercontent.com/47462792/233844914-d0e7aec9-bc6b-4a3a-abda-423501981596.png)
![image](https://user-images.githubusercontent.com/47462792/233844985-d9ba795b-fd68-4d02-b4de-5c15058ac531.png)

**Comment by ThyWoof** [comment]
Yep, this is incorrect. Can I have your safe to simplify tests?

**Comment by ThyWoof** [comment]
fixed in [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/f56165ce56d0445f20a51ebf1a3aa58e60bee21f).
