### ISSUE TITLE
Awkward Shapeshift double Mirror Images

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3046]
I don't think you need a save for this, but if you do let me know and I shall try and replicate it.

Shapeshifting under Mirror Image spell doubles the amount of Mirror Images you have (at least the buffs on the portrait, could be a visual bug).

![image](https://user-images.githubusercontent.com/44898614/233856139-dcb18c92-fe71-4b4e-84db-066b4945bb0a.png)

**Comment by ThyWoof** [comment]
Thanks. Can you please add this to the pinned discussion on wildshape? We plan to revisit it after DLC.
