### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by Daard** [SolastaMods/SolastaUnfinishedBusiness#3050]
Used this [guide](https://github.com/SolastaMods/SolastaUnfinishedBusiness/wiki/Install) for installation 

Tried this [solution](https://www.reddit.com/r/CrownOfTheMagister/comments/zo0o0i/anyone_gotten_unfinished_business_to_work_on_a_mac/) also. 

But still it does not work. 

My Mac OS version is 12.3.1 Monterey. 

Can you help me?

**Comment by ThyWoof** [comment]
Share screenshots or a QuickTime video of all steps you are taking.

**Comment by Daard** [comment]
<img width="409" alt="Screenshot 2023-04-24 at 16 18 59" src="https://user-images.githubusercontent.com/4972277/234009224-f6c9cbd0-b803-474e-9d24-e0a288d1ad89.png">

![Screenshot 2023-04-24 at 16 17 48](https://user-images.githubusercontent.com/4972277/234009231-c1388a0f-165c-4502-b77e-da7e132bfdb3.png)

![Screenshot 2023-04-24 at 16 16 57](https://user-images.githubusercontent.com/4972277/234009235-09320771-b2b0-41cb-b039-8408194ecdaf.png)

![Screenshot 2023-04-24 at 16 20 12](https://user-images.githubusercontent.com/4972277/234009239-81911837-5246-49ba-91fb-1a33b3302df4.png)

![Screenshot 2023-04-24 at 16 20 01](https://user-images.githubusercontent.com/4972277/234009241-992101fc-36ae-4ea8-be33-c612f02f8cd2.png)

**Comment by ThyWoof** [comment]
Can you show the Game App contents and ensure that Contents\Resources\Data\Managed has a sub folder UnityModManager and 2 files: UnityEngine.UIModule.dll and UnityEngine.UIModule.dll.original_?

Share a screenshot of this folder please.

**Comment by Daard** [comment]
<img width="594" alt="Screenshot 2023-04-25 at 04 20 29" src="https://user-images.githubusercontent.com/4972277/234151521-a6c25f40-c110-4b5d-8d06-11ac9c2979b2.png">

**Comment by ThyWoof** [comment]
What’s your game version? Can you see the UMM UI when starting the game?

**Comment by Daard** [comment]
<img width="841" alt="Screenshot 2023-04-25 at 04 25 40" src="https://user-images.githubusercontent.com/4972277/234152094-8159155b-a843-4b51-8e9a-ce245c64441d.png">

**Comment by Daard** [comment]
Version is 1.4.33

**Comment by Daard** [comment]
Nope.

**Comment by ThyWoof** [comment]
The DLL there has the same timestamp as all other game files. This tells me the merge didn’t happen correctly. Copy the same DLL I mentioned above from zip and overwrite.

**Comment by Daard** [comment]
Thanks. 

I have copied this files in the Solasta directory not in the Contents. This was a reason why I can't use the mod.
