### ISSUE TITLE
Minor Elemental Options hidden behind other Infusion

### ISSUE THREAD

**Issue by prkrj316** [SolastaMods/SolastaUnfinishedBusiness#3051]
After getting 6 infusions for the Inventor class, part of the slide-up options for Minor Elemental get hidden behind another infusion above it so you cannot select lightning or thunder.  See the screenshot, the options lightning and thunder are hidden behind Replica Boots of Striding and Springing. 
![Infusions Issue](https://user-images.githubusercontent.com/131686259/234034167-040940a7-89f7-46fb-bf51-9bf62d448339.png)

**Comment by ThyWoof** [comment]
Share your save please. You can zip and attach here.

**Comment by prkrj316** [comment]
> Share your save please. You can zip and attach here.

Here you go.
[New Adventure - Lost Valley.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11312412/New.Adventure.-.Lost.Valley.zip)

**Comment by ThyWoof** [comment]
Thanks. Fixed.
