### ISSUE TITLE
Low Performance and wrong charactor choised for Ability check

### ISSUE THREAD

**Issue by tyker1** [SolastaMods/SolastaUnfinishedBusiness#3052]
Once installed and played on multiplay with friends, we have the issue that the performance drops dramaticly, checked the task manager, it seems that the mod causes the game not to use all GPU and CPU resources.

Second issue is that when used on an existing save game, the mod causes the game to choose wrong charactor for ability check rolls, like my main charactor which is a mage with +13 on history and my friend uses a clecric with only 2 history. For a history ability check, his charactor was choosed to perform the check, which of course results in a failed attempt.

**Comment by ThyWoof** [comment]
None of these are caused by the mod. Please check tons of discussions online what you can do to avoid this.
