### ISSUE TITLE
Bow Mastery does not grant its Bonus Action Attack when the Attack Action is prevented with Shield

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#3053]
As the title says, when you use your Action to Attack a spell-caster who can use the 1st-level spell Shield, them using their reaction to cast Shield and avoid being hit will cause you unable to use Bow Mastery's Bonus Action Attack. 

It may apply to all enemy reaction abilities, but I haven't tested that extensively. On current mod/game version.

**Comment by MartinBrandstrup** [comment]
I can confirm that this also happens to me.

**Comment by ThyWoof** [comment]
Save please.

**Comment by ThyWoof** [comment]
Changed the weapon used registration to happen a bit before attack impact on. Couldn't test as no save were provided. Probably fixed.
