### ISSUE TITLE
The 'Powerful Spell' Metamagic doesn't apply to damaging abilities, only to buff abilities, and has no effect.

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#3054]
The newly added 'Powerful Spell' Metamagic doesn't seem to be usable with damaging spells/cantrips, and seems to only be usable with buff abilities like Bless. Even then, attempting to use Powerful Spell with Bless doesn't result in any additional bonuses despite successfully  deducting the Sorcery Points.

Tested on latest patch and game version.

**Comment by ThyWoof** [comment]
Save please

**Comment by ThyWoof** [comment]
fixed in dev.
