### ISSUE TITLE
Multiplayer instability Soul Hex

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3055]
The ability Soul Hex from the warlock subclass Soulblade will always fail to apply the proficiency to damage for both clients in a multiplayer game leading to consistent instabilities.
Not sure if this is fixable, but I will try to upload a good save where this can be consistently reproduced next time I play a multiplayer session with my friend. Just wanted to give a headsup in case it can be easily detected in the code.

**Comment by ThyWoof** [comment]
Save please

**Comment by MartinBrandstrup** [comment]
Followup: Quick saving -> Load makes both client ignore Soul Hex now. Janky

**Comment by ThyWoof** [comment]
fixed the health piece.
