### ISSUE TITLE
Multiplayer desync weapon swap feature

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3058]
When using the weapon swap feature the game often desyncs. Suspicions point towards the one client not controlling the relevant character does not register the weapon swap properly.
As seen in this save, which after loading claims that the first attack of the gorilla is a punch, although in reality it was a rock throw. With one attack remaining after the save was made it should only be punch, but since weapon swap was activated to do the rock throw first, this is now the only remaining attack and the combat log interprets it as a punch despite it being ranged.
... I hope I explained this well enough
[Weapon Swap.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11326194/Weapon.Swap.zip)

**Comment by ThyWoof** [comment]
I’ll have to disable this feature unfortunately. It’s very specific for apes only.
