### ISSUE TITLE
Bow Mastery wackery?

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3059]
I am not 100% certain that it is Bow Mastery causing this, but I just suddenly noticed a bit of an odd situation.
As I don't know when exactly it happened I cannot upload an exact save to replicate it, but if you feel like experimenting you can use the save I posted in issue #3058 which is right before this situation before leaving combat.

![image](https://user-images.githubusercontent.com/44898614/234385678-cb4e2b21-af64-4ae6-9410-9b77e072cdd2.png)

**Comment by ThyWoof** [comment]
this was probably caused by the other reported issues. couldn't reproduce.
