### ISSUE TITLE
Quick Math (Wit)

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3063]
Quick Wit from Artificer might not actually be as quick as advertised? Or am I misunderstanding something here? :)

![image](https://user-images.githubusercontent.com/44898614/234687672-1cf688fc-b9fa-473b-89af-3b9b72f073c8.png)

**Comment by ThyWoof** [comment]
Have you checked the total damage on tooltip? Claw do half damage on saves so although it’s saved you still get some damage.

**Comment by ThyWoof** [comment]
I believe only the new result tooltip is incorrect. Will fix.

**Comment by ThyWoof** [comment]
Confirmed it’s tooltip only. Line 428 should be after we set the rolled variable.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/8c8d60785a1935e789a6f3e4d6cf7592627b19ed/SolastaUnfinishedBusiness/Classes/InventorClass.cs#L924

**Comment by MartinBrandstrup** [comment]
Yeah sorry I was trying to be witty and might not have clarified issue clearly enough.
I was referring to the roll of 1+5 = 6 failure add 4 and get 14

**Comment by ThyWoof** [comment]
Can I have your save to test the fix?

**Comment by ThyWoof** [comment]
Fixed in dev.
