### ISSUE TITLE
Elemental Forms elements list popup stopped showing in .79

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3064]
![image](https://user-images.githubusercontent.com/6001560/234717130-2ed69695-d312-449a-8932-8f23d0b93ba5.png)
Hi, I'm on a multiplayer-coop campaign using a...fairy Warlock.

As soon as I updated to v .79 I can no longer use the mentioned warlock ability as the list of elements doesn't seem to appear anymore.
I believe it could be a consequence of one of the related changes that appeared in .79

**Comment by ThyWoof** [comment]
Share your save please

**Comment by NeatWolf** [comment]
Here it is - could be useful for the other issue (LOS) as well.
[Fairy-Warlock.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11337929/Fairy-Warlock.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/234723060-9c115259-a749-4c0f-820d-a14e8103da7d.png)
fixed.
