### ISSUE TITLE
Fairy Race: Unable to target enemies - line of sight starting height is too close to the ground or beneath it

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3065]
While playing with a warlock fairy, I progressively (v.76-v.79) noticed the fairy has probably some issues when calculating the LOS to other enemies.

I'm assuming it's because the race is a scaled down version of another race and its LOS got pushed a bit too low, to the point of being unusable unless you fly - and move upwards (flying at ground height doesn't fix the issue).

Steps to reproduce:
1-create a new fairy warlock
2-in the Lost Valley campaign, not too consistently among maps, try to target an enemy with any area or target (enemy) spell or invocation. 
3-The game forbids you so as there's no line of target to the spell area/target

Related issue:
There's no line of effect between the fairy warlock and a creature standing on top of a 1"block" unit stair, even when trying to watch it from 3-4 blocks away.

Expected behaviour:
Fairies can target spells and creatures without any extra disadvantage (RAW). Or, at least, without any unreasonable disadvantage (even if the eye height of the race is lower than 1.5ft, a character should still be able to see, even with some cover, creature on a 1,5 block)

Workaround:
- Cast fly
- Fly 1,5ft upwards. This enforces the hypothesis that the origin of the LOS is lower than normal.
- you can now cast and target spells as normal

Related issue:
When the racial feature of fly ends up, there's no feather fall post-effect. All fairies crush to the ground after 1 minute

**Comment by ThyWoof** [comment]
I'll change the flight duration to permanent. Indeed game has strange LOS calculation. Not much we can do about it.

**Comment by NeatWolf** [comment]
> I'll change the flight duration to permanent. Indeed game has strange LOS calculation. Not much we can do about it.

Thanks!
Beware tho: in certain maps you can't use Fly to reach some location(e.g. the map requiring to reach the "animated cube" holding one of the gems, but there are others) - the game forbids it and jumping/climbing is the only solution. So it probably needs a way to dismiss it.

that was really making all encounters very frustrating - I was so tempted to force-add the Draconic wings feat to my list(a bonus action) One of the two requires concentration IIRC, and probably Fairy's Flight had casting time - 1 action contrary to its description. 

I should really record a video next time something happens - I swear, apologies for the reports, I'm not actively trying to break the game! 😅

Some weird stuff is definitely going on - another time I was perfectly able to spot a spider by peeking from a wall; as soon as another player positioned himself near the corner my LOS was fully occluded. So something else is happening when calculating cover and such.

May I suggest, to tackle it from being dispelled/requiring concentration (which would kill most spellcasting combos):
Casting: not an action/free action. No concentration is needed. Can't be dispelled. Can be dismissed by re-casting it.
Or, maybe, make it a toggle ability (such as metamagic). Whatever works, really 😅. Draconic Wings is 2 times faster, as a comparison.
