### ISSUE TITLE
Multiplayer desync after .78: Party members enter a random encounter - same map, different enemy encounter.

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3066]
I can't tell if it's a Solasta thing but I've been playing the full campaign + lost valleys with the same people and this issue only popped up recently.
Could be a coincidence but - Maybe the new random system does not propagate properly in multiplayer?

Steps:
1 - Enter a random encounter in multiplayer, Lost Valley campaign
2 - all players load the same map but one is facing a green dragon, the other a duo of Hill giants.
3 - The game doesn't desync and we don't realize what's happening for a while but at some point the turns soft-lock as the initiative order is different
- it can be fixed by saving the game and reloading it.

I'm unable to reproduce it atm. It hasn't happened yet in .79

**Comment by ThyWoof** [comment]
Probably this. Don't use the new random system in MP.
