### ISSUE TITLE
Slay The Enemies Feat not working.

### ISSUE THREAD

**Issue by ZiadCharif** [SolastaMods/SolastaUnfinishedBusiness#3068]
On going campaign, before the latest patch the feat was working when clicking on "Powers"  then pressing "Slay The Enemies" it will show up a small menu to select the level of the slot to burn.

After new patch, same process yields no menu to select level of the slot to burn..

Tested in various environments including out of combat, no concentration on a spell, with concentration on a spell, first thing in combat before taking any action, at the end, etc. No solution.

**Comment by ThyWoof** [comment]
Already fixed in dev. Thanks
