### ISSUE TITLE
Monk in pre-existing party after update 1.4.33.78 still has D6 dmg roll

### ISSUE THREAD

**Issue by wtfzambo** [SolastaMods/SolastaUnfinishedBusiness#3070]
Hello, 

I have an active single player campaign that has a monk in party with a total character lvl of 6 (5 monk 1 fighter). His unarmed damage roll is still set to D6, is it possible to make the fix work to the current campaign?

I tried respec-ing after a long rest during a travel between location, to see if the fix would be applied, but as I clicked the "respec" button I got a message saying that it's not possible to respec in multiplayer campaigns (which is pretty weird, considering it's a single player one). This never happened before.

Ninja edit: I tried to respec at a campfire and this time I was allowed to, but even after respec it seems the dice roll is still set to D6:

![image](https://user-images.githubusercontent.com/47462792/234939955-c50b8969-49a8-4af3-ac86-6738b3328b92.png)

**Comment by ThyWoof** [comment]
Aren’t monks at level 5 supposed to do D6? D8 only at 11 and it’s monk level not char level.

**Comment by wtfzambo** [comment]
> Aren’t monks at level 5 supposed to do D6? D8 only at 11 and it’s monk level not char level.

Pardon, I was under the impression that the dice lvl up was supposed to be at monk lvl 6 not lvl 5. My mistake.
