### ISSUE TITLE
Level 9 Armorer perk Armor Modification not working with weapon infusions

### ISSUE THREAD

**Issue by prkrj316** [SolastaMods/SolastaUnfinishedBusiness#3076]
I have tried adding the Minor Elemental(Acid for those pesky trolls) weapon infusion to my Armorer's Guardian model armor. And it isn't working. It still only does Thunder damage. I had the Enhance Armor and Minor Elemental on it simultaneously and thought that was the issue but today I changed things around and only put the M.E. infusion on it. I'm including the save of a fight in progress where I just hit someone and it only dealt the gauntlet's thunder damage.
![2023-04-28 07 36 28](https://user-images.githubusercontent.com/131686259/235152065-097e0798-0f41-41a7-8def-c71990e46bcf.png)
[Armorer Lvl9 Armor Modification Bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11353627/Armorer.Lvl9.Armor.Modification.Bug.zip)

**Comment by ThyWoof** [comment]
This is an engine limitation. Lightning is an attack mode not an item reason why.

**Comment by prkrj316** [comment]
I guess you are saying that the Thunder Gauntlet is considered a power so you can't add the weapon infusion to it.  If that is the case then that line should probably be removed from the level 9 ability description.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/235329652-0bc62c02-15e8-4e47-8712-7fe961982010.png)
was able to find a workaround for that. happy camper.

**Comment by prkrj316** [comment]
Nice! Thank you!
