### ISSUE TITLE
Lagging and characters won't load :(

### ISSUE THREAD

**Issue by MilenaHari** [SolastaMods/SolastaUnfinishedBusiness#3077]
I've been playing the 6 character version of Morrows Deep with UB for like 10 hours and everything ran perfectly. Then I was fighting these orcs in the sewers and suddenly started lagging a lot. When I logged back in I couldn't start and I could see my characters in the character menu but couldn't select them. I tried loading saves from my vanilla campaign but there was the same issue. I tried to follow your debugging steps and got to the last step but I couldn't figure the visual studio stuff out. 

I'm not really sure if this is the right place to post this but I would really appreciate the help.

I have the latest update of Solasta with this version of "UB: 1.4.33.79" and no other mods.
[MilenaSaves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11354954/MilenaSaves.zip)
[MilenaChar.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11354973/MilenaChar.zip)
When I went to check my logs folder it was empty so I left it out.

**Comment by ThyWoof** [comment]
You should rollback to a version where it’s working and fully read the release log to check if any Respec is required.
