### ISSUE TITLE
Wildmaster's 'Beast Companion' can't currently summon any of its Spirit Beasts

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#3078]
Not sure if this is an issue specific to my settings or something, but trying to summon Ranger Wildmaster's Beast Companion doesn't currently have any effect. Clicking the power only makes the game hitch momentarily, but nothing happens. I swear it worked only last week, so I can only theorize a recent change broke it.

Tested on latest patch and version. Example character provided.

[Freya.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11355548/Freya.zip)

**Comment by ThyWoof** [comment]
This is fixed in dev. Thanks
