### ISSUE TITLE
Monk's Optional Feature 'Weapon Specialization' doesn't make weapons Dexerity based

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#3079]
Monk's Optionally enabled 'Weapon Specialization' feature currently doesn't appear to be making weapons Dexterity based as intended, which is a provision that's supposed to occur when they become viable Monk Weapons. The 2nd-Level prompt works perfectly fine, but just doesn't apply in-game.

Played on latest patch and version. Example character provided.

[Hena.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11355567/Hena.zip)

**Comment by ThyWoof** [comment]
Do you mean finesse weapons aren’t using DEX when specialized by monk?

**Comment by ThyWoof** [comment]
I cannot reproduce. Please RESPEC your hero:
![image](https://user-images.githubusercontent.com/13087646/235207166-891f9858-2ccc-48d3-a56e-fb940c1a9a70.png)

**Comment by Milliuna** [comment]
You're using a Rapier, which is already Finesse. I mean something like a Longsword - which doesn't have Finesse.

Monk Weapons (and thus Monk Weapon Specialization) should make weapons scale with Dexterity.

**Comment by ThyWoof** [comment]
This is based on optional monk rule on 2nd level. There isn’t anything there about finesse. Take the long sword feat instead.

**Comment by Milliuna** [comment]
Forgive me if I'm not explaining this well. Let me re-phrase it in a way that's as clear as I can make it to avoid confusion:

- At 1st Level, Monks get an ability called 'Martial Arts', that specifies they can use 'Monk Weapons' (specified as Simple Weapons and Short Swords) with Dexterity instead of Strength:

![exhibita](https://user-images.githubusercontent.com/128595789/235285089-c698be55-c077-4725-8aab-daccd51da5ea.png)

- Monk Weapon Specializing lets you choose one weapon and make it a 'Monk Weapon', even if it falls outside of the scope of Simple Weapons and Short Swords:

![exhibitb](https://user-images.githubusercontent.com/128595789/235285100-a42fed88-673f-4743-a9f3-fa0ed0df997d.png)

Therefore, for a Monk to use a Longsword with Dexterity, they shouldn't need the Longsword Finesse feat, due to Martial Arts. I hope that's a little clearer, and if not, please ask if you'd like further clarification.

**Comment by ThyWoof** [comment]
added finesse to monk chosen weapons.
![image](https://user-images.githubusercontent.com/13087646/235314534-7a2a12c0-096f-4b75-a5ce-a948b0d3d79b.png)

**Comment by Milliuna** [comment]
Thank you. :)
