### ISSUE TITLE
Helm of Awareness doesn't seem to prevent "surprised"

### ISSUE THREAD

**Issue by wtfzambo** [SolastaMods/SolastaUnfinishedBusiness#3084]
Hello,

just today I bought Helm of Awareness, attuned one of my characters to it and equipped, and went on a fast travel. As I was traveling (not sleeping), I got surprised by an Archmage, 2 veterans and a bunch of scouts.

So unless it's a programmed event that forces the party to be surprised (I don't know if this is actually a thing), I believe that the helm didn't work properly.

The reason I mention the programmed event is because, contrary to any other ambush I had, this one had some character interactions after the fight, saying something along the lines of "These were not bandits, we need to be careful". (See screenshot from the questlog):

![image](https://user-images.githubusercontent.com/47462792/235308066-2ce48f45-b4ab-4d49-b3b0-b5c0521ee06b.png)

To provide more information, I was playing the main campaign, my party is lvl 7, I am on the quest "Heritage of Distrust" at the step "Go to the Notary", traveling between Caer Cyflen and Tanneron Estate.

**Comment by ThyWoof** [comment]
Please report vanilla game bugs directly to game developer.

**Comment by wtfzambo** [comment]
How is it vanilla? The object is tagged with "Unfinished business":

![image](https://user-images.githubusercontent.com/47462792/235313976-9d4ceab2-f3c7-48d2-92db-62d01b22211c.png)

**Comment by ThyWoof** [comment]
Damm. I cannot remember when I added it. Anyways checked the helmet and all correct in there. It gotta be indeed this particular scripted interaction.

**Comment by wtfzambo** [comment]
Alright, that's what I supposed. Thanks for clarifying!
