### ISSUE TITLE
Field Manipulator - Displacement feature immediately desyncs MP lobby

### ISSUE THREAD

**Issue by HellKnightX** [SolastaMods/SolastaUnfinishedBusiness#3085]
The new reworked Field Manipulator's Displacement ability, when used, prompts _every_ player in the lobby where to target the cast. This will immediately desync the game for all players.

**Comment by ThyWoof** [comment]
I really like the new sub and not sure how to make displacement work under MP. Unfortunately won't fix.

**Comment by HellKnightX** [comment]
Is there a way to make it so that the targeting prompt only asks the casting player for a target?

**Comment by ThyWoof** [comment]
This will break the entire idea behind the class. Ideally a brand new cursor that allows one target and one location needs to be coded. Which is a bit above my knowledge.

**Comment by ThyWoof** [comment]
Good news. I believe I found a workaround that won’t require that.

**Comment by ThyWoof** [comment]
Hopefully fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/65cc58aa7c5989e2fb12cc8d6dce918db650ef49). Otherwise won't be able to fix..
