### ISSUE TITLE
Spell Sniper feat removed from character after reloading save

### ISSUE THREAD

**Issue by HellKnightX** [SolastaMods/SolastaUnfinishedBusiness#3086]
In my current MP game, our party's Field Manipulator Sorcerer picked the Spell Sniper - Warlock - Eldritch blast feat. When reloading the save, the feat is deleted from the character. After multiple respecs, the issue persists. The feat stays on the character until the save file is reloaded, upon which it disappears. Have tested it in both MP and SP.

**Comment by ThyWoof** [comment]
can I have the save before it happens?

**Comment by HellKnightX** [comment]
I'll upload a save later today. I need to set it up again with another respec.
