### ISSUE TITLE
Inventor Artillerist Force Ballista always hits without making an attack roll

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#3091]
I haven't seen the Inventor's Force Ballista ever miss its shot, and there's nothing in the log showing that it's making a spell attack roll. It's capable of attacking teammates too, so I spammed it against my 20 AC Fighter several times, and it seems to always hit.

![image](https://user-images.githubusercontent.com/8569010/235331295-a156dd60-d021-442c-b1d8-5a524327782f.png)

**Comment by ThyWoof** [comment]
Please share a save for easy fix on my end.

**Comment by ThyWoof** [comment]
it's indeed set to distance instead of range hit. fixed.
