### ISSUE TITLE
Inventor Artillerist Arcane Firearm damage isn't correct for AoE spells

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#3093]
The bonus damage from the Arcane Firearm feature should be applied to all targets of an AoE spell (like Shatter). At least, this is how it's ruled in [the tabletop rules](https://rpg.stackexchange.com/a/177034).

Currently, the feature applies to only one target in an AoE group, or it is not applied at all if an ally is included in the AoE.

Example where Arcane Firearm is applied to only one enemy:
![image](https://user-images.githubusercontent.com/8569010/235338997-664e3613-224a-4da2-b196-5c748cd7c18c.png)

Example where Arcane Firearm is not applied at all when an ally is included in the AoE:
![image](https://user-images.githubusercontent.com/8569010/235338317-72f25c27-2e27-4ab8-bc64-e5f93e848030.png)

Save and Custom Campaign
[firearm_repro.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11360719/firearm_repro.zip)

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/235340523-114a196c-2a4e-4174-a05e-d3cead0404e5.png)
fixed in DEV. thanks.
