### ISSUE TITLE
Warlock lvl 13: No Mystic Arcanum 7th level spells available for selection

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3094]
(in the suggested spell list at least)

Steps:
- Level up a warlock up to lvl 13. Use the suggested/default spell list.
![image](https://user-images.githubusercontent.com/6001560/235340455-4402e2ba-68db-4676-829a-fe26c5ae9778.png)
![image](https://user-images.githubusercontent.com/6001560/235340529-e23e2389-788d-408f-8357-931fea69988d.png)

By enabling -all- SuBusiness spells, it potentially gets 2:
![image](https://user-images.githubusercontent.com/6001560/235340609-43c54088-a78d-405e-bf43-2a7acab9f0ff.png)

Here's a tiny snippet from Tasha's Cauldron of Everything as inspiration to what could potentially be included in the list (unless we're going strictly with the SRD 5.1, in which case I should double-check if there are other options of the 6th level Arcanum as well.
It's just... to have a bit more variety among high level warlocks, unless we want to have all 13th level warlocks flipping gravity as signature skill :D 
![image](https://user-images.githubusercontent.com/6001560/235341000-0ee35249-7c69-4fdd-95cf-c2f5b04fc44f.png)
Warlock's canon Arcanum progression is 1 extra arcanum at levels 11-13-15-17, respectively of level 6, 7, 8, 9.

I can send a save if helps.

**Comment by ThyWoof** [comment]
Add any level 7 spell meanwhile to warlock on UI panel. This will work better once DLC is out with official spells.

**Comment by NeatWolf** [comment]
> Add any level 7 spell meanwhile to warlock on UI panel. This will work better once DLC is out with official spells.

Will do :)
I was just...surprised it wasn't already in the suggested spell and required some manual intervention.
(I'm ok with the fix but I can easily imagine other less... "moddy-inclined" people asking why there's no choice and struggling to add those spells.).

I'm guessing also this is going to potentially get addressed in the DLC:
Mentioning an article, "Thanks to the optional Eldritch Versatility feature introduced in Tasha's Cauldron of Everything, Warlocks actually have a means of changing their Mystic Arcanum. Once they gain access to Mystic Arcanum, on subsequent level-ups in which the Warlock can increase their ability scores such as level 12, a Warlock can opt to change one spell from their Mystic Arcanum feature. This means that if a Warlock isn't enjoying a spell they selected as much as they'd hoped, they can try out a different available option by simply gaining levels."
