### ISSUE TITLE
Minor: Elementalist's Enhanced Elemental Forms feature Element list popup is misplaced on the screen

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3095]
Definitely not gamebreaking but still - I can't know if it's an isolated issue or risks propagating somewhere else in the code:

Steps: 

- Get the Enhanced Elemental Forms feature of the Warlock (Elementalist)
- As soon as the UI is displayed for that character, use the skill to make the popup appear
- The popup position is misplaced in the screen
- The description stays in place instead of moving elsewhere (or disappearing?)

Note: Doesn't happen again until the game UI for that character gets hidden (my guess). So it happens at least once per turn.

![image](https://user-images.githubusercontent.com/6001560/235341673-e8f96793-f8ab-490f-8a37-964aa9c8fcbf.png)

Note: I haven't tested if the non-Enhanced version of Elemental Forms has the same issue.

**Comment by ThyWoof** [comment]
AFAIK it only happens the very first time a submenu is displayed. From there on it’s rendered correctly. Escape hides the menu.

**Comment by ThyWoof** [comment]
tested it again and indeed it only happens the very first time this menu is rendered in game. from that point on all works as normal. Honestly I have no idea why this is happening as code flows through same path on first time it's rendered and subsequent ones.

Unfortunately won't fix.
