### ISSUE TITLE
BladeDance Constitution check bonus not working

### ISSUE THREAD

**Issue by Newrite** [SolastaMods/SolastaUnfinishedBusiness#3100]
Looks like BladeDance's Constitution check bonus isn't working.

From description:
`You have a +4 bonus on Constitution checks.`

![image](https://user-images.githubusercontent.com/55597311/235363422-e1d02856-b6b0-4733-849f-d81fa3f29cb8.png)

On the screenshot
+2: CON
+1: Lucky stone
+1: Blessing

The wizard is under the effect of BladeDance, I can not provide a screenshot, I watched the log after the battle.

**Comment by ThyWoof** [comment]
Can I have your save?

**Comment by Newrite** [comment]
> Can I have your save? What are the game and mod versions? GOG or Steam?

it's custom compain with auto translate form UB, but i can send save

UB version 1.4.33.80
Steam

**Comment by ThyWoof** [comment]
Just checked code and it’s only giving advantage on ability checks instead of savings. Easy fix but save will help me confirm. Share please.

**Comment by Newrite** [comment]
> Just checked code and it’s only giving advantage on ability checks instead of savings. Easy fix but save will help me confirm. Share please.
Sure
[QuickSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11362104/QuickSave_2.zip)

**Comment by ThyWoof** [comment]
Fixed on dev.
