### ISSUE TITLE
Mod Warning When Starting a New Game

### ISSUE THREAD

**Issue by templar1138** [SolastaMods/SolastaUnfinishedBusiness#3108]
I've been playing Solasta with Unfinished Business for months, and I've had no issues with it until now. When I try to start a new campaign of the base game, I get the errors shown in the screenshots below. I've been keeping UB up to date (1.4.33.81), I verified the file integrity through Steam, and I updated UMM (0.25.5.0), but this still happens. For recreation purposes: All the characters are level 1, none are pregen, they're all races of official TA content, and include a warlock with the moonlit patron. The campaign I'm attempting to start is set to Authentic Mode with neither the Iron Man Mode nor Skip Intro boxes checked (I tried skipping the intro, but it didn't make any difference). UMM log included below.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11368585/Player.log)

![20230501185204_1](https://user-images.githubusercontent.com/129412612/235545507-c0a78bb6-c018-4c2d-99fa-321aa3e1ae0e.jpg)
![20230501185505_1](https://user-images.githubusercontent.com/129412612/235545519-82565617-a1c3-40c1-a26a-6746b1a6d062.jpg)

**Comment by ThyWoof** [comment]
This is fixed in dev. Rollback to v80 or don’t use the moonlit Patron.

**Comment by templar1138** [comment]
> This is fixed in dev. Rollback to v80 or don’t use the moonlit Patron.

Copy that. Thanks for the quick reply.
