### ISSUE TITLE
Subclass: Paladin - Oath of Dread: Aura of Domination rooting self

### ISSUE THREAD

**Issue by ZeuS531** [SolastaMods/SolastaUnfinishedBusiness#3109]
-A paladin at level 7 gains the aura of domination. As per the information text, a frightened enemy within 10ft has their speed set to 0 and takes psychic damage.

-Issue: the paladin is rooted by his own aura

-Currently (1.4.33.81) when a creature is frightened within the aura's range the paladin will be rooted, the creature will take psychic damage and will flee according to the frightened status

-What should happen: The enemy creature should be rooted and behave accordingly (probably dodge)

**Comment by ThyWoof** [comment]
please share your save.

**Comment by ThyWoof** [comment]
no need. fixed in DEV. https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/672971e4bfc30934cf2d149b10dd5bddc1032d7b
