### ISSUE TITLE
Inventor Artillerist Force Ballista attack roll doesn't include spell attack bonus and HP is incorrect

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#3112]
Save: [cannon_spellattack.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11371865/cannon_spellattack.zip)

Version 1.4.33.81 changed Force Ballista to use an attack roll, but the attack currently doesn't include the character's spell attack bonus. This issue affects both the tiny cannon and small cannon.
![image](https://user-images.githubusercontent.com/8569010/235633722-dd1f1838-ed4b-43b9-b29e-a9aa06c91714.png)

Additionally, HP of the summoned small cannons should be 5 * Inventor Level, but it currently seems to be wrong and also inconsistent between the cannon types. (Screenshots show Lv 6 character, so it should be 30 HP)
![image](https://user-images.githubusercontent.com/8569010/235633841-d946c98c-86af-439a-b351-e708f513a453.png)

![image](https://user-images.githubusercontent.com/8569010/235633921-31467a73-a762-4286-b801-656383f95f5f.png)

**Comment by HIEROT** [comment]
I noticed this too. Now I am messing up with the source code, hoping I fix this before the devs do

**Comment by HIEROT** [comment]
After some several minutes of inspection, the problem may be caused by the prototype of this power is eldritch blast but the modifier is not properly set:
file:\SolastaUnfinishedBusiness\Subclasses\InnovationArtillerist.cs
code:
```csharp
        var powerForceBallista = FeatureDefinitionPowerBuilder
            .Create($"Power{Name}{ForceBallista}")
            .SetGuiPresentation(Category.Feature, EldritchBlast)
            .SetUsesFixed(ActivationTime.Action)
            .SetEffectDescription(
                EffectDescriptionBuilder
                    .Create(EldritchBlast)
                    .SetDurationData(DurationType.Instantaneous)
                    .SetTargetingData(Side.All, RangeType.RangeHit, 12, TargetType.IndividualsUnique)
                    .SetParticleEffectParameters(EldritchBlast)
                    .SetEffectForms(
                        EffectFormBuilder
                            .Create()
                            .SetDamageForm(DamageTypeForce, 2, DieType.D8)
                            .SetDiceAdvancement(LevelSourceType.ClassLevel, 0, 1, 6, 3)
                            .Build(),
                        EffectFormBuilder
                            .Create()
                            .SetMotionForm(MotionForm.MotionType.PushFromOrigin, 1)
                            .Build())
                    .Build())
            .AddToDB();
```

**Comment by ThyWoof** [comment]
EB is only used as effect prototype. Issue has been identified and will fix soon.

**Comment by HIEROT** [comment]
> EB is only used as effect prototype. Issue has been identified and will fix soon.

Ok. just curious, is it caused by no implementation of this custom action？

**Comment by ThyWoof** [comment]
The custom action is implemented. Something deeper on how powers cannot leverage spell attacks. On top of that it’s a monster not a caster.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/235808425-99260bec-a0b6-4137-b697-2e5f599cb840.png)

**Comment by ThyWoof** [comment]
had to first implement a new interface here: https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/7d41a284d4ad62c388c340d8cd548381e3ab4d54

once so fix was easy here:
https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/6ba3ebacd3ae295dba752d123a0e4ee4636a18c4
