### ISSUE TITLE
Quest [Spoiler]: NPC not spawning or getting killed does not cause the quest to fail or complete

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3113]
[Spoilers]

Lost Valley campaign:
Steps:
- Kill Orenetis early in the game (-100 to faction)
- Get the Prisoners quest in the secret complex
- Stage of the quest: "Escort the prestigious prisoner"
- Sitenero (the prisoner) either gets killed in a fight or never spawns in the lower level of the secret complex
- The quest never fails nor completes (maybe causing a chain of side effects?)

I can provide a save if the Community mod also patches quest bugs.

**Comment by ThyWoof** [comment]
Please report this to TA. It’s beyond the mod scope.

**Comment by NeatWolf** [comment]
Ok, I was unsure. This is the only "community patch/mod" I know that kind of fixes issues - while the game's still in development.  Had to ask just in case  :)
