### ISSUE TITLE
Auto Party Select Resets on Module Switch

### ISSUE THREAD

**Issue by Axeborne** [SolastaMods/SolastaUnfinishedBusiness#3114]
How to report issues
The versions of Solasta and this mod.
Solasta Version 1.4.33 Public
Unfinished Business 1.4.33.81- 

A list of other mods you have installed [you shouldn't have any]. 
Unfinished Business

A short description of the bug. 
I'm not sure if it is a bug or simply doesn't work on other modules accepting the original Crown of the Magister story, but the toggles on character pool to set default play & test party & auto-selecting slow down loading & resets completely when switching to another module such as some that are on workshop like Forsaken Island (6-man).

This isn't hindering my gameplay, but I thought it worth mentioning for improvement :D 
  
A step-by-step procedure to reproduce it. 
Enable toggles on character pool & select any module other than Crown of the Magister.

The save, character and log files.
HINT: Check the folder C:\Users*YOUR_USER_NAME\AppData\LocalLow\Tactical Adventures\Solasta* for the info we need.
Github is refusing the drag & drop files options for those requested (character, saves).  I zipped them to allow for upload. 

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378410/Player.log)
[Dragonborne Socrata 7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378458/Dragonborne.Socrata.7.zip)
[Eirini.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378459/Eirini.zip)
[Ianthe.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378460/Ianthe.zip)
[Kava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378461/Kava.zip)
[Sora.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378462/Sora.zip)
[Stasia.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378463/Stasia.zip)
[Thava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378464/Thava.zip)

**Comment by ThyWoof** [comment]
This works as expected on my end as it’s the single tool I use for tests. What are the hero levels?

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/c8614d3010c1290e5ccb6ab477f283a74de43357). Thanks for reporting. On next release.

**Comment by Axeborne** [comment]
level 1 starting the modules.  It is the 2 character select options on Unfinished Business that are not working as expected for me.

Enable on character pool to set your default play & test party
Enable character button checker on the main screen>characters (I am disabling this to see if it is causing some conflict.)


Noel Dean Calvert & Jessy Guevara Biojo

GueCal Vivero Colombiano SAS

GueCal Colombian Tropicals

NIT: 900652986-9

Colombia: 57(317)687-6154

USA/Canada: 1(602)774-0753

________________________________

**Comment by Axeborne** [comment]
So this will be implemented in the next update fixing the problem?

Assuming I understand, thank you very much for taking the time to look at this! :D


Noel Dean Calvert & Jessy Guevara Biojo

GueCal Vivero Colombiano SAS

GueCal Colombian Tropicals

NIT: 900652986-9

Colombia: 57(317)687-6154

USA/Canada: 1(602)774-0753

________________________________

**Comment by ThyWoof** [comment]
Eso. El próximo release está bien chevere. 🤔

**Comment by Axeborne** [comment]
> fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/c8614d3010c1290e5ccb6ab477f283a74de43357). Thanks for reporting. On next release.

Thank you ThyWoof

**Comment by Axeborne** [comment]
Perfecto!  Miraste que estoy en Colombia y cambiaste a Espanol 🙂  Chevre.


Noel Dean Calvert & Jessy Guevara Biojo

GueCal Vivero Colombiano SAS

GueCal Colombian Tropicals

NIT: 900652986-9

Colombia: 57(317)687-6154

USA/Canada: 1(602)774-0753

________________________________

**Comment by ThyWoof** [comment]
Colombia is one of the countries I support. I’m in bogota / Medellin every Q.

**Comment by Axeborne** [comment]
I live in Tumaco, Narino, Colombia.

I've been here for 10 years 😄


Noel Dean Calvert & Jessy Guevara Biojo

GueCal Vivero Colombiano SAS

GueCal Colombian Tropicals

NIT: 900652986-9

Colombia: 57(317)687-6154

USA/Canada: 1(602)774-0753

________________________________
