### ISSUE TITLE
QoL RESPEC issue

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaUnfinishedBusiness#3115]
A quality of life improvement to the RESPEC option would be to regurgitate any ability increase Tomes associated with the character being de-leveled.  Tomes are pretty rare and expensive.  So it's sad to see those +2 ability scores permanently lost due to either a forced RESPEC, bugged character, or mistake during character leveling.  I don't know if consuming these Tomes leaves some kind of hidden feat or flag on the character.  If it doesn't, I imagine your mod would have to introduce a way to track Tomes consumed before you could ever hope to refund them.

**Comment by ThyWoof** [comment]
Use tools - items to grant any item back to your hero, including tomes.
