### ISSUE TITLE
Icons Too Big

### ISSUE THREAD

**Issue by Dimensionist29101991** [SolastaMods/SolastaUnfinishedBusiness#3116]
When using the mod to add spells and feats to level 20, the icons are too big to fit the screen in spell levels beyond 6 or with the additional metamagic options, if you add them all. Is there a way to make the text and icons smaller?

**Comment by ThyWoof** [comment]
Screenshots for each described issue.

**Comment by Dimensionist29101991** [comment]
![Solasta Metamagic UI Break](https://user-images.githubusercontent.com/43776930/235841946-82800e64-aeff-4c88-a969-6fb680ebcabe.jpg)
![Solasta Spell UI Break](https://user-images.githubusercontent.com/43776930/235841951-b68e4b48-fb93-4889-a6b1-292d216885fa.jpg)

Problems with spells, and problems with metamagic. There's also a problem with the character's UI getting too big if you add metamagic and other non-class options as well through feats, and likely through multiclassing.

**Comment by ThyWoof** [comment]
Metamagic I’ll fix. Spells no as sorcerer shouldn’t have that amount of spells and is unsupported.
