### ISSUE TITLE
Tactician Combat Maneuvers

### ISSUE THREAD

**Issue by Ethan-Joiner** [SolastaMods/SolastaUnfinishedBusiness#3117]
I believe I've found a bug with the combat maneuvers for the tactician subclass. The save DC for the abilities is supposed to be 8 + prof + dex/str but is instead using intelligence as the modifier. My multiclassed barb/fighter has 20 str but 8 int so he has a DC of 11 (8 + 4 - 1) on these abilities which makes them worthless on Cataclysm difficulty.

**Comment by ThyWoof** [comment]
Can I have your save? Zip and attach.

**Comment by Ethan-Joiner** [comment]
I am not at my PC right now but I actually just re-read the wiki and it looks like it is working correctly. In 5e the battlemaster uses str/dex for DC but for some reason this mod changed it to int? I must have skipped over reading that part when choosing the subclass in game. I don't understand the logic behind the change but that is irrelevant to the issue and it looks like it isn't a bug. Thank you for the quick response though!

**Comment by Ethan-Joiner** [comment]
Is there a general feedback/non bug related issues area?

**Comment by ThyWoof** [comment]
Discussions. Meanwhile will close this one.
