### ISSUE TITLE
Poison Expert did not give me proficiency in the Poisoners kit.

### ISSUE THREAD

**Issue by prkrj316** [SolastaMods/SolastaUnfinishedBusiness#3119]
I had my rogue take the feat Poison Expert and it did not give him proficiency in the poisoner's kit. 
[Poison Expert issue.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11391415/Poison.Expert.issue.zip)
![Poison Expert issue](https://user-images.githubusercontent.com/131686259/236055215-d69b760b-7361-4868-97e5-64a3badf36f7.png)

**Comment by ThyWoof** [comment]
fixed in dev. thanks.
