### ISSUE TITLE
Innovator Artillerist Tiny Cannon power should use bonus action not action

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#3122]
Running on dev branch currently.

Commit [6ba3eba](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/6ba3ebacd3ae295dba752d123a0e4ee4636a18c4) changed the cannon power to use an Action. This is correct for summoned cannons, but this power is also re-used for the Tiny Cannon. It therefore has an unintended side effect of causing the Tiny Cannon to use the player's main action to activate, when it should instead be a Bonus Action.

Not too familiar with tricks in the code, but I guess this might require duplicating the action definition for a "tiny" version that uses a bonus action.

**Comment by ThyWoof** [comment]
shit. had to duplicate a lot of stuff but fixed.

![image](https://user-images.githubusercontent.com/13087646/236282716-758c07c1-885f-4e9f-966f-4af79d4fb813.png)
