### ISSUE TITLE
Deadeye feat cannot turn off

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3128]
Please inspect this, as the title says, once turned on, the -5+10 state cannot be turned off
[bugreport.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11401490/bugreport.sav.zip)
In this save the feature is already on, and there is not an option off
Thank you.

**Comment by ThyWoof** [comment]
Yes there is one. Check the hero portrait on bottom left and click the Deadeye icon there.

**Comment by HIEROT** [comment]
THANKS!
