### ISSUE TITLE
Splint Armor of Survival has no base AC stat

### ISSUE THREAD

**Issue by Axeborne** [SolastaMods/SolastaUnfinishedBusiness#3129]
How to report issues
The versions of Solasta and this mod.
Solasta Version 1.4.33 Public
Unfinished Business 1.4.33.82-

A list of other mods you have installed [you shouldn't have any].
Unfinished Business

A short description of the bug.
updated Survival Armor of splint armor has no base AC.  Also, having the armor in the inventory causes crashes or difficulty loading.  Easily avoided, but could be fixed hopefully. 

I am also curious where to suggest options to be added for Unfinished Business? Please advise. 

This isn't hindering my gameplay, but could hinder others.

A step-by-step procedure to reproduce it.
learning the recipe will show the armor when inspected in your crafting window without AC.  I would not suggest creating it as it causes problems after as mentioned above.  If you want to reproduce the problem, craft the armor & equip it. 

The save, character and log files.
HINT: Check the folder C:\UsersYOUR_USER_NAME\AppData\LocalLow\Tactical Adventures\Solasta for the info we need.
Github is refusing the drag & drop files options for those requested (character, saves). I zipped them to allow for upload.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378410/Player.log)
[Dragonborne Socrata 7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402577/Dragonborne.Socrata.7.zip)
[Eirini.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402578/Eirini.zip)
[Ianthe.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402579/Ianthe.zip)
[Kava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402580/Kava.zip)
[Sora.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402581/Sora.zip)
[Stasia.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402582/Stasia.zip)
[Thava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402583/Thava.zip)

**Comment by ThyWoof** [comment]
Good catch. In fact all splint armors lost their armor definition. Will check why.

**Comment by ThyWoof** [comment]
This isn't UB. It looks like the base splint armor blueprint is missing the Armor Definition form. I shared with the game developer and will add a fix for that in the mod.
