### ISSUE TITLE
Bug: Casting Guidance cantrip in 1.4.33.83 causes a null reference error

### ISSUE THREAD

**Issue by WolffHobbitStomper** [SolastaMods/SolastaUnfinishedBusiness#3137]
Create a vanilla cleric with the Guidance cantrip.
Start new game
Try to cast Guidance :  Crash.  (also observed with level 2 Enhance Ability spell)

Roll back CursorLocationSelectTargetPatcher.cs file to version from 1.4.33.82.

Recompile mod and the crash goes away

**Comment by ThyWoof** [comment]
Can I have your save?

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/22f8be8bff2a388d12bebb2b024e900dd8f2c558). You can recompile again and use latest. Thanks for the report.
