### ISSUE TITLE
[1.4.33.83] Soul Hex issues in multiplayer

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#3138]
Same issue as in #3055 

Specifically:
- The player with the warlock sees the damage from Soul Hex being applied
- The other players do not (e.g. target killed for the warlock, but not for the other players)
- Consistently desyncs all players when used, save/reload to continue fight

Save game (during fight):

[QuickSave_13.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11410878/QuickSave_13.zip)

**Comment by ThyWoof** [comment]
Thanks. It makes sense as Hex was using a weapon attack modifier trigger to add a condition. This was causing the condition to only be added to the warlock client and no others. Changed trigger now to `AttackInitiated` as it'll correctly add the cond on all MP clients. Well I hope as I cannot test MP but this one is used in many more places with similar logic.

Fixed [here]

Can you please test this one for me and post results? Attached is a new DLL. Ask all players to replace the mod DLL with this one and test. Thanks.

(https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/010a0c0b038e0e8be31389d1daf8f05860e79783).

**Comment by Andargor** [comment]
Thanks for the quick response, we'll give it a shot this weekend.

**Comment by Andargor** [comment]
We tried this morning, and in game all of our characters we switched with other player's, not the ones that we assigned in the lobby. We switched back to the release DLL.

**Comment by ThyWoof** [comment]
What do you mean?

**Comment by Andargor** [comment]
The characters are assigned to each player in the lobby. When we ready up and start the game, the characters each player has was someone else's instead, different from the ones assigned.

**Comment by Andargor** [comment]
We will try again with that DLL, the host did a respec in single player in the meantime and that may have messed up the multiplayer order. We will use the save I sent you.

**Comment by ThyWoof** [comment]
Thanks. My changes wouldn’t have caused that reason why I asked.

**Comment by Andargor** [comment]
We played for a while with the new DLL, and Soul Hex doesn't seem to work:
- The extra damage does not appear
- The Soul Hex healing does happen on kill
- We would get a few desyncs anyway

Warlock hitting target with Malediction and Soul Hex (no Soul Hex damage)
![ba9BF55](https://user-images.githubusercontent.com/3580755/236653459-f8068cd9-aa61-4bfa-8de7-410e18e9c3cc.png)

Soul Hex target hit with a sword and killed (Soul Hex healing applied to the warlock)
![P8kIAgZ](https://user-images.githubusercontent.com/3580755/236653473-a8699f8a-17c1-4b25-abc3-b36e44b78099.png)

**Comment by ThyWoof** [comment]
Original desyncs were related to damage not appearing. Are these desyncs still there?

indeed did a mistake and hex damage only applied on melee attack. Will fix that

**Comment by Andargor** [comment]
Honestly, we are not sure, we don't know what the source of desyncs is. Before the DLL you posted, a target was killed for some people and not for others because of Soul Hex, in one example. Coincidence? Perhaps.

We have two games with somewhat different people and classes, and they behave differently (disconnects in the non-warlock game but very rare or no desyncs, but desyncs in the warlock game and no disconnects). 5 players in a game is almost assured desyncs continually. Is it the base game, people's connections or specific classes/abilities? No idea.

I almost feel that there should be a separate network layer that bypasses the base game that implements master/client hierarchy, the master actually runs the combat and the slaves just play it back. But I wouldn't know where to start to do that. We are even considering using Steam Remote Play Together if it gets too bad... But then you remove some player agency.

I'm guessing the ranged fix for Soul Hex will be in the next release?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/236657952-86d09d33-aec4-4e01-a04d-0a2dc48ed3b0.png)
yep. Will close this one as nothing else I can do. Desyncs can come from vanilla and many other factors.
