### ISSUE TITLE
Wild Shape and Mirror Image

### ISSUE THREAD

**Issue by 1stSemada** [SolastaMods/SolastaUnfinishedBusiness#3139]
When concentrating on Mirror Image then wild shaping, the spell seems to reapply after the change but keeps the existing number of charges, so you end up with 6. Ending the wild shape does the same thing again, so you would end up with 9 if you entered wild shape then immediately left.

**Comment by ThyWoof** [comment]
We have a discussion topic collecting all wildshape non sense behaviors. Please report this one there as WS won’t be fixed until after the DLC.
