### ISSUE TITLE
Moonlit Warlock Umbral Cloak not dropping.

### ISSUE THREAD

**Issue by Kyzane** [SolastaMods/SolastaUnfinishedBusiness#3140]
Invis not dropping after first attack with Warlock Improved Umbral cloak not dropping after first attack in combat. Version 1.4.33.83

this was using The Lunar Assassin build from the Wiki

**Comment by ThyWoof** [comment]
Can I have your save?

**Comment by Kyzane** [comment]
sure thing , save and current settings we are using for UB

https://drive.google.com/file/d/16VuKyD53tjaJogXGvtGVRB1XhSJjQkVC/view?usp=share_link

**Comment by ThyWoof** [comment]
Thanks. Fixed in DEV. New release later today.
