### ISSUE TITLE
Touch spells not working on Bard/Sorc

### ISSUE THREAD

**Issue by ManBroCalrissian** [SolastaMods/SolastaUnfinishedBusiness#3141]
Game version 1.4.33. Updated UB to 1.4.33.83. Have a 4 Sorc (Divine Heart) / 3 Bard (Life). After the update, tried to cast Longstrider on the party and the targeting reticule would not pop up and I was unable to target anyone or cast the spell. It seemed to do the same with Cure Wounds but no one was injured. Healing Word would target and give the message that uninjured targets can't be healed. This leads me to believe it is only an issue with touch target spells. Rolled back to 1.4.33.82 and the targeting worked perfectly.

**Comment by ManBroCalrissian** [comment]
This bug happened in multiplayer. I went back and checked in single player. Identical behavior that was corrected with a rollback to 1.4.33.82.

Also, the character is a Fairy with Charismatic Defense and Inspiring Leader. I tried to cast while flying and standing. Not sure if any of that matters though.

**Comment by Swofty** [comment]
I think this might already be fixed in dev with [22f8be8](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/22f8be8bff2a388d12bebb2b024e900dd8f2c558).

The Find Familiar code patch was causing a short circuit before reaching the final `IsFilteringValidMeleeCantrip`.

**Comment by ManBroCalrissian** [comment]
I'll just run .82 until .84 is out then. I thought it was important that this was known

**Comment by Swofty** [comment]
I'm running on the dev branch (but not part of the team). If you want to help verify, you can drop this in overriding the file in Mods\SolastaUnfinishedBusiness.

[SolastaUnfinishedBusiness_79902d7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11411850/SolastaUnfinishedBusiness_79902d7.zip)

**Comment by ManBroCalrissian** [comment]
I updated to 1.4.33.83 to reconfirm broken behavior. Logged out and used SolastaUnfinishedBusiness_79902d7. Worked perfectly!

I also tried it with Find Familiar checked and unchecked with no problems. Looking forward to the next update. Thanks!

**Comment by ThyWoof** [comment]
Thanks folks. I'll have a new release today as this is a bug that makes game unplayable. Doing a full QA this morning on other 2 issues before release. Closing this as fixed in DEV.
