### ISSUE TITLE
Cannot Use Buffs Out of Combat After 1.4.33.83 Update

### ISSUE THREAD

**Issue by HellKnightX** [SolastaMods/SolastaUnfinishedBusiness#3151]
Since the last update, I have no longer been able to cast several buffs outside of combat, including Longstrider, Guidance, Fly, and both forms of Invisibility. They can be cast once combat starts, but trying to do so out of combat asks for a target selection, but does not actually allow you to select any friendly targets.

Uploaded a Lost Valley save with the bug:
[Group 2 LV.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11413668/Group.2.LV.zip)

**Comment by ThyWoof** [comment]
fixed in dev. thanks
