### ISSUE TITLE
Enemy initial rolls without dex bonus

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3154]
I recently noticed that when rolling initials all enemies have 0 modifier, and obviously they should add their dex (and other) bonus

**Comment by ThyWoof** [comment]
this is how the vanilla engine works. screenshot taken without the mod.

![image](https://user-images.githubusercontent.com/13087646/236658279-e1add460-e531-40cf-8c7a-9bd38966c63b.png)


not a bug.

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/236659567-6e8f8121-2818-4fda-b419-e1c2dfc5316c.png)

seems to be a vanilla bug. report this one to them please.

**Comment by HIEROT** [comment]
@ThyWoof This is the issue for initial rolls
