### ISSUE TITLE
Updates missing from the Changelog.txt

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#3155]
Missing from the [changelog.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/releases/tag/1.4.33.84)/update screen:

New Sprites added in the last 2 days:
1- Redo of Winter's Breath sprite to recenter so it's not covered by the game's overlay
2- New icon for the Sonic Boom spell
3- New icon for the Color Burst spell
4- New icon for the Caustic Zap spell
5- New icon for the Brain Bulwark spell
6- New icon for the Burst of Radiance spell.

@Zappastuff if you are gonna use my work, you could at least give me credit for it in the changelog.txt.

**Comment by ThyWoof** [comment]
Seriously? Your name is on credits.

**Comment by jackal242** [comment]
Yes - seriously.  

Previously you **always** included any new sprites as part of the changelog.txt which is included in the pop-up notice when you go to update UB.

This time, you left all those items out of the changelog.txt, even though all those items changed.
 
So yes - seriously, could you please update the changelog.txt to include the changes of this release, including all the new sprites.
