### ISSUE TITLE
The Changelog.txt with this release does not reflect the changes made to the package with this release

### ISSUE THREAD

**Issue by jackal242** [SolastaMods/SolastaUnfinishedBusiness#3156]
Yes - seriously.

Previously you always included any new sprites as part of the changelog.txt which is included in the pop-up notice when you go to update UB.

This time, you left all those items out of the changelog.txt, even though all those items changed.

So yes - seriously, could you please update the changelog.txt to include the changes of this release, including all the new sprites.

**Comment by ThyWoof** [comment]
There won’t be a new release for a changelog. Your name is on credits. I’ll report GitHub as abuse if you open a 3rd issue on same topic. There are real issues and game breaking bugs to fix.
