### ISSUE TITLE
Crusader's Mantle preventing player movement/input

### ISSUE THREAD

**Issue by Ekallo** [SolastaMods/SolastaUnfinishedBusiness#3157]
When casting Crusader's Mantle with a Circle of the Kindred Spirit druid, I'm having issues that the druid is unable to perform any sort of input (moving, ending turn, etc) after doing so and basically soft locks the game because of it.

Game version: 1.4.33
Mod version: 1.4.33.84

**Comment by ThyWoof** [comment]
There isn’t much we can look at without your save.

**Comment by ThyWoof** [comment]
Fixed at https://github.com/SolastaMods/SolastaUnfinishedBusiness/pull/3159
