### ISSUE TITLE
Elemental descriptions

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3158]
![image](https://user-images.githubusercontent.com/44898614/236683761-ab345bec-4f7f-4312-9a82-5895eda70f5e.png)
Screenshot should explain the issues

**Comment by ThyWoof** [comment]
These are vanilla terms that should be there in POI as we are using an ice elemental that wasn’t released yet 🤣. Will close this one. Please remind me if it happens again after dlc
