### ISSUE TITLE
Game starts so lag when I open proficiencies / crafting

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3160]
Hi there. My friend and I have the problem that the game has some kind of lag/freeze when we open the crafting or proficiencies tabs. After we do that for the first time in a session, the game will always take a few seconds before opening any inventory (character / trader / loot).
Before opening that panel for the first time, everything is fine.
This has been happening for a while now, but it did not used to happen. I think it started happening somewhere around 1.4.33.80

We have changed nothing in our setup, which is why I suspect the mod.

**Comment by ThyWoof** [comment]
That panel will get slower as your heroes get more features. Really nothing we can do about it. We haven’t touched it for a long time so nothing that was added recently on the mod could have caused it.
