### ISSUE TITLE
Question about "Official Advantage/Disadvantage rules"

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3165]
The wiki doesn't include (correct me if i am wrong) the details of this part so i cannot confirm if it is intended. At least one thing I noticed different from official rules is about combat in the dark.
According to PHB rules (I also checked it in other explanations such as [darkvision](https://blackcitadelrpg.com/darkvision-5e/)), the basics here is if a creature cannot see his attacker or target, the attack roll to and from him has disadvantage, and this includes the mechanics of light condition.
In a dark scene, if both the attacker and target don't have the ability to see in the dark, then the advantage and disadvantage cancel and they attack each other normally. If only one with it and the other not, then they are granted with advantage and disadvantage in attack rolls, respectively. This also applies to magic darkness and other sight obscuring effects.
In the vanilla game the case is the lack of ability to see a creature won't grant advantage to attackers to him (apart from stealth and invisibility), so in the first scenario both attack with disadvantage, and in the second, the one  who can see through darkness attack normally. And with the mod "Official Advantage/Disadvantage rules" on ,this doesn't change.
So this might be a bug or an unimplemented feature, hence the issue here above.

**Comment by ThyWoof** [comment]
Game calculates advantage / disadvantage as sum[ADV] - sum[DIS]. If positive ADV, negative DIS, zero NEUTRAL.

All this setting does is force neutral if there is at least 1 ADV and 1 DIS as official rules.

Darkness and anything related to light is another issue as TA doesn’t follow the rules. Nothing we can do about it.
