### ISSUE TITLE
Shadow blade not granting adv vs target in darkness and its attack roll not using highest attribute modifier

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3190]
[QuickSave_2.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11443831/QuickSave_2.sav.zip)
in this save, when attacking an enemy in the dark, the character has no adv. And I noticed when calculating ab and dmg, CHA is used instead of DEX, which is higher.

**Comment by HIEROT** [comment]
> 

Fair enough, but the first issue is still there, perhaps.

**Comment by ThyWoof** [comment]
yeah, will check the first one.

**Comment by ThyWoof** [comment]
I cannot test any save on a location. Tests must be made on campaigns otherwise I won't be able to open the save.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/00332888-cf87-42bc-ac15-1b58acadf69d)
fixed. I'll tweak that NONE on ADV to say Shadow Blade.
