### ISSUE TITLE
Inventor Artillerist Cannon action missing in 1.4.33.86

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#3201]
The Artillerist's cannon actions seem to be missing in 1.4.33.86. This was not an issue in 1.4.33.85.

1. Summon a Flamethrower cannon (medium)
2. Use the Command Cannon bonus action
3. End turn
4. On cannon's turn, the Flamethrower action is not there

Force Ballista is also affected. Tiny Flamethrower is also affected, as it does not show the bonus action.

[cannon_action_repro.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11461111/cannon_action_repro.zip)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8569010/63406141-7060-4d7b-bed1-6900fbfc33e6)

**Comment by Smite-Sion** [comment]
(Tiny) Protector is also affected by this

**Comment by ThyWoof** [comment]
fixed in [dev](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/d7b6b8b4f43df9e4e0de3a704d6dc036c78455f3). thanks.
