### ISSUE TITLE
Pact slots to sorcery points?

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#3204]
Was there a change to the ability to use Pact slots to get Sorcery points back on Warlock/Sorcerer multiclass builds?

I recently updated to 1.4.33.86 after not playing for a while. I played for a bit, but when I tried to use my pact slots to get points back, I ended up burning one of my Sorcerer slots.  Verified I had to hold Shift while doing so (which worked the last time I played, but that was ages ago), tried again, burned another regular slot.  Tried again without holding the shift key, again burned a regular slot.

1.4.33
1.4.33.86

The CrownNuke character is the MC

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11468550/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
It’s the same feature since lost valley was released. some users report it but usually is because you need to keep shift pressed until the effects finish.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1c9d9396-e421-4e4b-93ec-a8acc697df09)
on this particular scenario you don't press shift at all. simply convert using the second button.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/b8d36f5f-d981-4d69-ae25-116217ef300f)

not a bug.
