### ISSUE TITLE
Lunger functionality question

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3209]
Fighting Style Dueling: "When you are wielding a melee weapon in one hand and no other weapons..."
Fighting Style Lunger: "While wielding only one melee weapon without the heavy tag..."

Dueling works while using a shield but Lunger doesn't. The description does not lead me to believe it shouldn't. Is it an oversight in the description or in the coding that makes Lunger not work with sword and board? The feat it is based on does not provide any information as that works with all weapon configurations, but does other stuff instead.

If it is working as intended maybe add "and no item in the offhand" to the description or something similar.

**Comment by MartinBrandstrup** [comment]
Followup: It seems that cantrip attacks such as Sunlit Blade does not benefit from the reach granted by Lunger, unlike the reach you get from polearm weapons. Is this a bug or intended?

[Vertical Reach.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11469550/Vertical.Reach.zip)

**Comment by ThyWoof** [comment]
Lunger is a FS so on purpose it’s weapon only.

**Comment by ThyWoof** [comment]
EN is my third language so I would rather get help from native speakers to fix any term.

Can you please share a suggestion on what the description should be?

**Comment by ThyWoof** [comment]
Got input from other EN native. Changed on dev.
