### ISSUE TITLE
Merciless FS

### ISSUE THREAD

**Issue by Smite-Sion** [SolastaMods/SolastaUnfinishedBusiness#3210]
"When you reduce a target to 0 HP using a melee weapon attack on your turn, enemies within a radius of the downed target equal to half of your proficiency bonus (rounded up) who can see the target must make a Wisdom save (DC equal to 8 + your proficiency bonus + your Strength modifier) or become frightened of you **until the end of their next turn**. If the triggering attack is a critical hit, the radius is instead equal to your proficiency bonus."

I can safely say, that this doesn't work. It is until they are dead currently :)

**Comment by ThyWoof** [comment]
Won't look into this one unless I have a save and a screenshot with the condition tooltip displaying.

**Comment by Smite-Sion** [comment]
Tooltip:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/127842385/5fd79036-8d2b-4da5-a59c-a142c8d5ce4e)
Send you a pm with the save file

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/72c8baf3-2113-4197-81dc-e01b9a5e00ee)
fixed in dev.
