### ISSUE TITLE
Inventor Quick Wit auto succeeds

### ISSUE THREAD

**Issue by Smite-Sion** [SolastaMods/SolastaUnfinishedBusiness#3214]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/127842385/2379f8f0-e2ea-4c02-a2ef-7c88005fc168)

Tink = Inventor
Robert = Druid

Whenever someone fails a save, the inventor can make it auto succeed.

**Comment by Smite-Sion** [comment]
Update:
It still fails, but it says it succeeds:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/127842385/9f61d56c-441b-4745-ad24-1a677b27f8d1)

**Comment by ThyWoof** [comment]
as usual I cannot do anything without a save.

**Comment by Smite-Sion** [comment]
Save has been provided with the character, the behavior seems 100% consistent and everything seems to work, it is purely presentation.

Also when it does help to succeed it does the following:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/127842385/2de39eb1-3e5e-41e9-9bf6-c0b94ce7b4e0)

**Comment by ThyWoof** [comment]
fixed in dev.
