### ISSUE TITLE
5th and 6th Character not recognized in Dialog

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#3229]
So I'm not sure if anyone else has noticed this or not, but in a dialog it's not assigning roles to, or considering the skills of, the 5th and 6th character in the party. I'll explain how I discovered this. I setup a dialog that assigns the role "Rogue" to any Rogue in the party. Then it tests them to see if they can beat a roll of a 4 vs Stealth. Cake walk for any Rogue. Rogue is character #6 in the party. Attempt dialog and because there is no one assigned to the role of Rogue, it skips that part of the dialog. I move Rogue up in the party list to slot #4 and presto, Rogue now rolls vs the Stealth check. I've tried a couple other tests to confirm and it's the 5th and 6th Characters that are ignored in Role selection or taking part in the dialog.

**Comment by ThyWoof** [comment]
This is currently a limitation on how campaigns are written. Unfortunately there is no fix for that.
