### ISSUE TITLE
Power Word Kill wrong spell school

### ISSUE THREAD

**Issue by Redst0neFlux** [SolastaMods/SolastaUnfinishedBusiness#3235]
PWK is listed as transmutation. It's enchantment in the SRD

**Comment by Redst0neFlux** [comment]
weird is also the wrong school

**Comment by ThyWoof** [comment]
Any other?

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/b5a2ca7151b1b135a760285ff6d5b5915702407e).
