### ISSUE TITLE
Missing Images/Text for additional wild shape options

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3244]
![20230519191633_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131542731/2e3c3db4-459f-4621-a229-bcff08ef9d59)
![20230519191637_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131542731/ae060036-8042-43a7-a21c-0f008be42665)
See screenshots
Edit: Attacks are also missing:
![20230519192441_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131542731/df9bed7a-1950-4968-9dba-b75a0e7e2830)

**Comment by ThyWoof** [comment]
It isn’t a bug. POI will only release on the 25th. It’ll magically fix from that date on.
