### ISSUE TITLE
Bard College of Life subclass ability upcasting spells

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3246]
Ability is supposed to upcast Necromancy and Transmutation spells, but the Summon Skeleton spell is not getting upcast Raise Skeleton Archer. To reproduce just pass the turn until Pace (the Kobold)
This is also an issue for Heat Metal; initial damage is upcast but reapplying is not. Unfortunately I do not currently have a save that can reproduce this conveniently.

Reusing this save for ticket #3245 & #3247 
[Summon Skellington & Web Dex.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11519234/Summon.Skellington.Web.Dex.zip)

**Comment by ThyWoof** [comment]
Heat Metal is a vanilla game bug. Bard can only upcast spells on its own repertoire. Is this the case here or did you MC into Dead Master?

**Comment by MartinBrandstrup** [comment]
That would be the issue then. My bad didn't realize

**Comment by ThyWoof** [comment]
These spells were made exclusively for Dead Master. Unfortunately the game engine goes wack here. Given this is a very particular case and I need to focus on DLC there won’t be any attempt to fix in the short / medium term.

**Comment by artem-mateush** [comment]
>  Bard can only upcast spells on its own repertoire.

You should be aware I'm able to upcast inflict Wounds gained through multiclassing.

**Comment by ThyWoof** [comment]
if you check on latest version, raise skeleton spells now are correctly tagged as war list. still couldn't make them work as expected.
