### ISSUE TITLE
Telekinetic Feat does not use up bonus action when used on self

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3247]
Is it even supposed to be usable on self?
To reproduce just pass turn to Pace (Kobold) and start throwing Telekinetic on yourself.
Aside from this it can also act a bit wacky in general with auto targeting and direction not always acting as supposed. Needs experimenting

Ps: It seems Telekinetic does not work on restrained (by web) enemies, which I suppose is intended is how it should work; but it still works on the "Held by ice" debuff from Bounden Ice spell, which theoretically should be the same? Logically?

Reusing this save for tickets #3245 & #3246 
[Summon Skellington & Web Dex.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11519266/Summon.Skellington.Web.Dex.zip)

**Comment by ThyWoof** [comment]
Using on self is by design and having unlimited uses is a game engine limitation. Use honor mode here.

Web and ice bound have only differences on the conds applied. Will check the second part of the report

**Comment by ThyWoof** [comment]
Also bound by ice should not do any ability check

**Comment by ThyWoof** [comment]
Was able to move the enemy under web or ice bound. probably when you tested the enemy saved on the telekinetic power. not a bug.
