### ISSUE TITLE
UI dropping below screen

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#3255]
Just tonight updated to 1.4.33.91.  Loaded my CotM save and got into a random encounter while travelling on the map.  Everything seems fine until I get to my Paladin/Warlock.  On his turn, the UI drops below the bottom edge of the screen, just enough that you can barely see the top of the character section (bottom-left corner of the screen), and because of this I was unable to click anything, not even to end his turn.  Nothing I did changed anything until I used the "C" shortcut to cast a spell (eldritch blast).  Once the cast animation was finished, UI was back where it should be.

Continued on to my destination (imperial ruin) for one of the side quests.  Started a fight to get the item I needed and once again the Pal/Lock's UI was below the screen.  This time I thought to save it before doing anything, and then cast a spell (aid this time, I believe).  Once again, as soon as the spell animation was over, the UI was back to normal

game 1.4.33
UB 1.4.33.91

I am, as always, incredibly creative when it comes to character names.  The Pal/Lock is named "CrownSmite"
[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11523455/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Screenshots?

**Comment by kosocku** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/122100625/e2050f51-fd05-4d78-9c18-e54c0f56c6a9)

**Comment by ThyWoof** [comment]
This is something I cannot reproduce on my end. Sorry.
