### ISSUE TITLE
Warlock (The Soulblade): Soul Empower not providing bonus to damage

### ISSUE THREAD

**Issue by rpherbig** [SolastaMods/SolastaUnfinishedBusiness#3256]
My character is Paladin 3/Warlock 1. Strength is 16 (+3) and Charisma is 20 (+5).

I have taken `The Soulblade` for Warlock. I have cast `Soul Empower` on my Longsword.

See attached images. The to-hit bonus appears to be calculated correctly. However, the damage bonus seems to be using my Strength modifier, not Charisma modifier. Based on the description of Soul Empower, I expect damage to get the +5 bonus from Charisma.

![Solasta_2023-05-20_20-50-42](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/f4b086e5-9712-4485-8ca4-8384c9efd1dd)

![Solasta_2023-05-20_20-54-43](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/9b0ff0da-95dd-4fbe-abbd-7f4227a6ec08)

![Solasta_2023-05-20_20-55-14](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/c9280826-5d6e-4871-802f-9c9280c80750)

**Comment by rpherbig** [comment]
Interestingly, I switched my Soul Empower to a maul (2-hander). Now the damage modifier appears to be calculated correctly.

Normal attack
![Solasta_2023-05-20_21-07-56](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/61e39a4f-b605-4f7c-944c-f3f2931c2aab)

Opportunity attack
![Solasta_2023-05-20_21-18-09](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/8b7024b5-5e49-4485-a3c2-a0229d61077b)

Attack via `Sunlit Blade`
![Solasta_2023-05-20_21-20-11](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/15a29213-b3f1-4bc7-a1dd-bdc5c4aa5935)

**Comment by rpherbig** [comment]
I just took a long rest and the Maul lost its bonuses from Soul Empower. I cast it again and they came back.

Is it wearing off after resting? That is definitely **NOT** what I expect since the duration of the power is "Permanent".

After rest
![Solasta_2023-05-20_21-52-30](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/792f1d14-6eb5-427a-b88a-f623269b97b4)

After recast
![Solasta_2023-05-20_21-56-02](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1181607/de8f8476-5a56-4361-963a-624769d3049d)

**Comment by ThyWoof** [comment]
This has been refactored in dev.
