### ISSUE TITLE
Sanctuary not working

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3257]
I've used Sanctuary on my characters against ghosts who attacjed with some life drain ability, and ordinary skeletons. Not one of them made a wisdom saving throw.

**Comment by ThyWoof** [comment]
There isn’t anything I can do without screenshots, save file, etc. check how other issues are reported please.

**Comment by ThyWoof** [comment]
Tested on my end and couldn’t reproduce. If you ever get a save and screenshots please open a new issue.
