### ISSUE TITLE
Unstable Mod Error

### ISSUE THREAD

**Issue by Isolveth** [SolastaMods/SolastaUnfinishedBusiness#3269]
I have followed all the directions for updating my mod. This includes ensuring that my game is updated to the latest version before updating the mod. I have the Palace of Ice DLC and whenever I try to import a saved game I get the attached error message. This also occurs if I try to just simply load a previously saved game. I am unsure what is happening. I have attached screenshots of my mod version, game version and the error message. 
![Error Message](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/71534187/c724bd3e-b2b0-487f-bf4f-c011f9ebee02)
![Solasta Version](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/71534187/ccf8601f-3382-4b72-996c-e62d2b90fcd7)
![Mod Version](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/71534187/2c098a4f-95c8-4e0a-b46c-80c883a06de2)

**Comment by Isolveth** [comment]
Confirmed that I was able to start a new game and make a save file but I am unable to load a new game from the main menu. I get the same error message.

**Comment by ThyWoof** [comment]
You haven’t read the changelog on previous Respec requirements. Not a bug.
