### ISSUE TITLE
Reserved character in multiplayer set up.

### ISSUE THREAD

**Issue by Cassianne** [SolastaMods/SolastaUnfinishedBusiness#3272]
Solasta Build ID 11316338 (palace of Ice update)
UB install 1.5.46.1

No other mods.

In the creation of any multiplayer game utilizing 6 member party option. One character is always reserved for all players and cannot be selected.

Fresh install of UB, settings for UB shared by party lead, Multiplayer, New adventure. The party leader is only able to use two character slots. The problem remains after reinstalling fresh settings, for all players attempting to host the game.

No logs to share sadly.
![20230525203623_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/134645681/bee85399-218f-4d93-b0dd-53578fe0094b)
![20230525203711_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/134645681/10ec28dd-c6
![20230525203718_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/134645681/596799f0-e611-45e3-8b74-fcac1416f901)
fc-4d99-a9d2-a834c2c4a93b)

**Comment by grantpanda** [comment]
same coming with this problem

**Comment by ThyWoof** [comment]
Unfortunately won’t be able to fix this one until TA fixes stuff on their end. Probably after their second patch. Meanwhile the alternative is to start a single player adventure, save and load it under MP menu.

**Comment by ThyWoof** [comment]
It looks like TA is now blocking more than 4 players in MP…

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c73f225e-ae4a-4c4e-bec6-3761869fda23)
vanilla bug. nothing I can do about it.

**Comment by charlesewatkins** [comment]
I have a similar problem. When my partner joins, he always gets one of my own characters. Fixed with a restart, until next time we play.
