### ISSUE TITLE
Palace of ice, one player computer crash, game breaks for all

### ISSUE THREAD

**Issue by Lyondes776** [SolastaMods/SolastaUnfinishedBusiness#3276]
ncountered a new bug as we tried to start palace of ice. We imported save, selected characters, started campaign and were playing just fine. Then one of the players computers crashed so we saved and quit, When we tried to load back in we found that our game had been broken (all of us except the player who's computer died). Anytime we try to load or create any game, single or multiplayer, we get a mod warning screen and then are unable to do anything. It'll highlight what we click on but won't actually do anything. Both the game and unfinished business are fully updated, we have the same xml file imported and active to ensure settings match.
![Mod Warning](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131220768/a1d8de24-2892-4e12-959f-71f73726b492)
![game broken](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131220768/76b19456-264f-48c4-a95a-0ef8f9a2a18e)

**Comment by ThyWoof** [comment]
Not the mod. Unfortunately that message is misleading and will pop up on any error, even vanilla ones if you use mods. Your save broke most likely because of the bugs on this release from TA.
