### ISSUE TITLE
Ritual Caster removed for Shock Arcanist Wizard

### ISSUE THREAD

**Issue by Werewind1e** [SolastaMods/SolastaUnfinishedBusiness#3279]
The versions of Solasta and this mod. 
 - Solasta = 1.5.46
 - Unfinished business = 1.5.46.1
A list of other mods you have installed [you shouldn't have any].
 - None
A short description of the bug.
 - I started a new game of Ice Palace and I noticed that my wizard (Shock Arcanist) does not have a button for Ritual Caster.  If I go to the character screen, I do in fact have Ritual Caster under class features.  Strangely my druid still has the button.
 - All of my characters were made new for this adventure.
A step-by-step procedure to reproduce it.
The save, character and log files.

Vanilla:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55240348/1a7f081b-a649-48a1-9864-17264567d7e3)

Unfinished business mod:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55240348/109dc85e-fa9a-4029-8fd7-26c2d8ab9ca5)

Saves, Character files and logs.  The Character in question is Juliette
[logs.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11575973/logs.zip)

**Comment by ThyWoof** [comment]
Do you have any ritual spell memorized on Wiz?

**Comment by Werewind1e** [comment]
I did, but when I rested I removed them.  Both before and after the button wasn't there.
Note that wizards don't have to have them memorized.

**Comment by ThyWoof** [comment]
Can you please attach both heroes and save as well?

**Comment by Werewind1e** [comment]
[Keavith.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11576155/Keavith.zip)

The save is attached already. Do you want the vanilla save?  I never saved that game. I can regenerate it if you like.

This is the other hero with the vanilla Wizard.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c186c430-0431-4436-aef1-9e074a69cf84)
Indeed your save doesn't show the button but cannot reproduce with a brand hew hero. Please RESPEC.

**Comment by ThyWoof** [comment]
Can you test this without UB? It feels like a vanilla bug.

**Comment by Werewind1e** [comment]
I already did that. (See first post)

I can test again, if you like.

**Comment by Werewind1e** [comment]
I did give myself 1 feat at level 1.  Maybe that is it.  I can test.

**Comment by Werewind1e** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/55240348/a72965b3-9efe-462b-89e6-4c52bae555e7)

That is what is causing the issue.  If I turn that off and respec, I retain Ritual Caster.  If I turn that on, for some reason it no longer works.

thanks
