### ISSUE TITLE
Spell Sniper Missing Cantrips

### ISSUE THREAD

**Issue by Hanyo99** [SolastaMods/SolastaUnfinishedBusiness#3280]
Game Version : Steam 1.5.46
Unfinished BUsiness: 1.5.46.1 (Current pull as of this post)

When choosing spell sniper for a character, that cantrip appears as though it's chosen but does not in fact show up on your cast list. 
Example: I generated a Mesastopholes Tiefling Sorcer with Draconic ancestory. Also took Spell Sniper - In this case it seemed that the firebolt racial cantrip was missing and in limbo. In another instance, with a Human Wizard who took spell Sniper (warlock) found that his cantrip was not on his cast list, but he could choose it if he readied a cantrip attack. 

This feat was working as intended as far as I could tell, prior to the most recent update for Palace of Ice. I apologize, I didn't havew time to upload sample saves, but added as much information as I could.

**Comment by ThyWoof** [comment]
fixed in DEV. thanks.
