### ISSUE TITLE
Opening inventory causes stutter

### ISSUE THREAD

**Issue by sztrzask** [SolastaMods/SolastaUnfinishedBusiness#3282]
Mod: 1.5.46.1, all dlc included

Mod settings - spells, classes, multiclassing enabled, all UI options related to inventory disabled (I've also checked them enabled, same issue), like sorting etc.

Issue:
Opening inventory takes ~1-2 seconds and is stuttering.

**Comment by ThyWoof** [comment]
Please report it to TA. If you disabled anything inventory related and still stuttering it isn’t us. I suggest you wait at least until TA releases the 2nd patch to play the game. Lots of bugs on release.

**Comment by sztrzask** [comment]
Uninstalling the mod helps the issue, thats why I reported it.
