### ISSUE TITLE
Spell for Spell Sniper not available

### ISSUE THREAD

**Issue by prkrj316** [SolastaMods/SolastaUnfinishedBusiness#3283]
[Spell Sniper Issue.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11580030/Spell.Sniper.Issue.zip)
![Spell Sniper Issue](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131686259/614285b4-ac89-4e5f-a1d9-280eeb462a07)
Since the update for Palace of Ice, the spell I selected for spell sniper feat is not working.

**Comment by ThyWoof** [comment]
Already fixed in dev. Thanks.
