### ISSUE TITLE
Race based cantrip not listed for Bolgriff

### ISSUE THREAD

**Issue by seameth** [SolastaMods/SolastaUnfinishedBusiness#3286]
Race Cantrip not listed and not available for casting.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/bb93d607-8c69-45f2-aef1-478aa9dafd97)

Have done a RESPEC, no change.

**Comment by ThyWoof** [comment]
fixed on 1.5.46.2.
