### ISSUE TITLE
Inventor (armorer) unable to apply Minor Elemental Infusion to Armor/Ranged attack

### ISSUE THREAD

**Issue by seameth** [SolastaMods/SolastaUnfinishedBusiness#3288]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/163e93de-e1d1-4212-955b-7b44a73b6230)

I was able to apply my Inventor's Minor Elemental Infusion to my armor and effect my Infiltrator Armor Ranged attack in the previous build of UB, prior to the new 1.5.46.1 update. If this is something that's been removed, that's fine, but incase it's still supposed to be there, it's not working right at the moment. 

Also, the Infusion: Repeating Shot appears to not be working.  

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/1f1f4eca-8eb4-46ca-a41b-ba8a561b7ede)

**Comment by ThyWoof** [comment]
@EnderWiggin , have anything changed with level 15 Armorer feature?

**Comment by seameth** [comment]
I may have been playing a high level campaign with my other inventor. pls, disregard if I misunderstood a level pre-requisite.

**Comment by ThyWoof** [comment]
@seameth , may I have your save anyways?

**Comment by seameth** [comment]
[bug report save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11580954/bug.report.save.zip)

**Comment by EnderWiggin** [comment]
Your character is level 3. `Armor Modification` feature (the one that allows applying weapon infusions on armor) is granted on level 9.

**Comment by seameth** [comment]
I feel embarrassed but informed. thank you for your time and patience. 

I'm still having trouble with my Gnome Wizard not being able to cast ritual spells though.
