### ISSUE TITLE
[1.5.46.2] Respec causes game crash

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#3289]
Playing Forsaken Isle with a ranger in multiplayer, when leveling up I could not see any classes other than Ranger. Other players could multiclass just fine (setting enabled)

I tried a Respec in single player, and consistently get a crash, see video: https://youtu.be/4fKSp1mE6xY

Save file: 

[x21beforerespec.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11580644/x21beforerespec.zip)

EDIT: Creating this character as a new character for a new game works fine

**Comment by Andargor** [comment]
Sorry, forgot the log file:

[Player-prev.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11580668/Player-prev.zip)

**Comment by ThyWoof** [comment]
Are you aware of Multiclass min attribute rules?

**Comment by Andargor** [comment]
> Are you aware of Multiclass min attribute rules? Is the Multiclass setting enabled? Did you restart after that?
> 
> Cannot reproduce on my end.

Of course, I was trying to multiclass as Rogue, and it's Dex 13, the ranger is Dex 20. But it's the respec that crashes the game.

**Comment by Andargor** [comment]
> Are you aware of Multiclass min attribute rules? Is the Multiclass setting enabled? Did you restart after that?
> 
> Cannot reproduce on my end.

For future reference, it was fixed. I uninstalled both the mod and then UMM, and then reinstalled, no more crash after this.

For the multiclass requirements, you were right, I had neglected to consider that you need both the prerequisites for the new class as well as the current class, and I only had 10 on the ranger, so no multiclass options. I sit corrected.
