### ISSUE TITLE
Spell Sniper and Sorcerer Soulblade

### ISSUE THREAD

**Issue by Eyequ** [SolastaMods/SolastaUnfinishedBusiness#3291]
After the latest dlc, the Spell Sniper spell will stop showing after you cast it once.  It will select it with the ready cantrip action automatically, however, the icon to manually select the spell is no longer there, nor does the spell show up under the Spell Sniper spell list.  Also, the create Arcane Weapon under use powers is no longer there, so the Sorcerer can not make his weapon an Arcane one.

**Comment by ThyWoof** [comment]
Save please.

**Comment by Eyequ** [comment]
It is UB 1.5.46.2. Where do I send the save file. wont let me move it here.  I changed the .sav to .log maybe changing it back to .sav will help
[COTM Multi - Copy.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11582524/COTM.Multi.-.Copy.log)

**Comment by ThyWoof** [comment]
Zip the save and attach again.

**Comment by ThyWoof** [comment]
Sorcerer arcane became a passive power. It tells me you have an older hero that needs Respec. Please do so and try again both issue.

**Comment by ThyWoof** [comment]
I cannot reproduce on a new hero so please try a RESPEC.
