### ISSUE TITLE
Druids/ Clerics have Wizard /Sorc /Bard Cantrips and Vice versa

### ISSUE THREAD

**Issue by johnbamf** [SolastaMods/SolastaUnfinishedBusiness#3293]
Looks like the cantrips somehow got swapped in the Wizard vs Cleric/Druid lists.

<img width="453" alt="Screenshot 2023-05-27 at 8 19 16 AM" src="https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/2654177/be61d06a-7d47-4118-ae88-e8bd5ed133c2">

**Comment by ThyWoof** [comment]
All mod cantrips are offered here. Not a bug.

**Comment by ThyWoof** [comment]
It’s a game bug. Need to wait for TA to fix it. Not this mod.
