### ISSUE TITLE
Bestow Curse should be auto-upcasted for College of Life Bard when the corresponding rule is on 

### ISSUE THREAD

**Issue by artem-mateush** [SolastaMods/SolastaUnfinishedBusiness#3299]
This is by no means urgent compared to various PoI bugs. 

But the option BestowCurseNoConcentrationRequiredForSlotLevel5OrAbove disables concentration [if the slot level of Bestow Curse >= 5](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/fad91d893a2c30f0ca0ed4425bcf66338907248e/SolastaUnfinishedBusiness/Patches/CharacterActionCastSpellPatcher.cs#L141). 
Bestow Curse is a Necromancy spell however, and College of Life Bard should get it 2 levels higher when cast. i.e. it should not require concentration/ 
Could you use effectLevel in that comparison instead?

Also thanks for your work Zappa! I'm a big fan of UB, love how much content is there, subbed to Patreon.

**Comment by ThyWoof** [comment]
That’s easy. The action has the ruleset effect which should have the effect level and upcast flag.

**Comment by ThyWoof** [comment]
After reading the rules and some discussions on the web it’s clear you must use a spell slot of 5th level or higher. That’s not the case here so won’t code it.

**Comment by artem-mateush** [comment]
Can I ask for that to be reflected in the feature text then? It's not obvious to me how Bestow Curse:

> If you **cast this spell using a spell slot** of 4th level or higher, the duration is concentration, up to 10 minutes. If you **use a spell slot** of 5th level or higher, the duration is 8 hours. 

(the different wording is just WotC saving on space, no?)

is different from Blindness

> [...] When you **cast this spell using a spell slot** of 3rd level or higher, you can target one additional creature for each slot level above 2nd

For the purpose of:
> When casting Transmutation or Necromancy spells they are cast at a spell slot 2 levels higher **than the one used**.

Maybe list specific spells in the feature?
