### ISSUE TITLE
Share spell metamagic does not work with Shadow Blade spell

### ISSUE THREAD

**Issue by AllYourBranchAreBelongToUs** [SolastaMods/SolastaUnfinishedBusiness#3300]
Game version: 1.5.46
Mod version: 1.5.46.3

No other mods are installed.

A sorcerer with the share spell metamagic should be able to share the spell shadow blade with allies but the option is greyed out when casting.
[ShadowBladeShareSpell.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583124/ShadowBladeShareSpell.zip)

Tried to fix it myself by setting the TargetType to self in the SpellBuilder which lets me use metamagic as expected, but I get a NullReferenceException after casting and I'm not experienced enoguh with the mod/unity debugging to fix it.
[NullRefException.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583142/NullRefException.txt)

**Comment by ThyWoof** [comment]
This is a game engine limitation. By design.
