### ISSUE TITLE
Random number generator is generating an inordinate number of 20s and 1s

### ISSUE THREAD

**Issue by GrayTechGH** [SolastaMods/SolastaUnfinishedBusiness#3303]
I Selected 'Enable better random generator  algorithm'
Confirmed I am running 'Authentic Mode' in the difficulty settings

I've went through three combats I rolled some 8s but mostly both I and the enemy rolled either 1 or 20s on combat rolls and skill checks.  At first I thought it could be chance  but after three combats I can longer believe it.

UB: 1.5.56.2
Solasta:  1.5.46

[Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583284/Settings.zip)
[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583315/Solasta.zip)

**Comment by Xurtan** [comment]
I've been noticing this too actually, when I've been testing various builds. It's ridiculously heavy on the 1s or 20s.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f59ce0e8-b2b1-4fa9-951f-1a627d1be4b0)
I did a minor tweak on how the state is saved and run above sequence. any better?

**Comment by HIEROT** [comment]
I turned the dice in the game to true random and solved this. Maybe it is some chemical of vanilla game and mod random number algorithms

**Comment by GrayTechGH** [comment]
I believe @HIEROT has shown where the issue lies.  For ALL preset difficulties the game is now selecting karmic dice when creating a new campaign.    I will go on the Discord and try to see if that was intentional on their part.

**Comment by ThyWoof** [comment]
It was intentional per game changelog. Anyways I have improved how to save my random state using marshaling.
