### ISSUE TITLE
Weaponsmiths defending blade despawns on location change

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3304]
Whenever we change location, my defending blade despawns.

**Comment by ThyWoof** [comment]
I need way more context than that. Mod version? single or multiplayer? save file?

**Comment by ZheToralf** [comment]
Multiplayer, 1.5.46.3

**Comment by ZheToralf** [comment]
[BUG_SAVE.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583475/BUG_SAVE.zip)
