### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Heresyrac** [SolastaMods/SolastaUnfinishedBusiness#3305]
1. Resonating Strike  & Sunlit Blade can‘t gain advantage from Ready or Not feat. 
2. The help action of Familiar can't  curse advantage。
3. Sanctuary doesn't work when the target get attacked.

**Comment by Heresyrac** [comment]
Game version 1.5.46
mod version 1.5.46.2

**Comment by ThyWoof** [comment]
These are all vanilla bugs affecting UB. Need to wait for a TA patch.
