### ISSUE TITLE
Poison application not working

### ISSUE THREAD

**Issue by dusky81** [SolastaMods/SolastaUnfinishedBusiness#3307]
When attempting to apply poisons, an error box pops up announcing that Solasta has detected a mod instability.  No response when you click on the poison subsequently.
![solasta poison bug](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/134831451/5113a036-0318-4aea-9a3f-6019184f3d31)

**Comment by ThyWoof** [comment]
Solasta will pop up that message even on vanilla bugs if a mod is installed. They broke this on release. Need to wait for a patch.
