### ISSUE TITLE
Bug Report: Thorn Whip

### ISSUE THREAD

**Issue by adurkee93** [SolastaMods/SolastaUnfinishedBusiness#3308]
1.5.46.3

The equivalent to Thorn Whip is treated as a ranged spell attack in UB currently, when RAW it should be a melee spell attack. This is causing disadvantage to the attack while in melee range of an enemy. It is also mentioned in the spell's description, so it seems like it might be intentional.

Is this something that cannot be fixed to match RAW because of the game's limitations? If it can be changed, it would improve the spell's viability significantly (especially for Druids, who only get two cantrips to begin with).

**Comment by ThyWoof** [comment]
fixed on Dev. on next release.
