### ISSUE TITLE
GiveMeItem utility not showing all items

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3310]
When playing custom campaigns, the merchants have a limited supplies, and I want to reward the party with magic items suitable for their classes and levels. But the Give Item Panel doen't list full of possible items as in the dungeon designer. Is it possible to fix this?

**Comment by ThyWoof** [comment]
Unfortunately no.

**Comment by HIEROT** [comment]
Sad story
