### ISSUE TITLE
Spell shield lvl7 feature war magic not count cantrip casting

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3313]
I read through the descriptions of this feature and it doesn't say non-cantrip spell. Maybe a cantrip is allowed as well?
Besides, the code relevant identified in the assembly-csharp may be at GameLocationBattleManager.HandleSpellCastt(), where it states selectedSpellDefinition.SpellLevel >= 1.

```csharp
		if (selectedSpellDefinition.SpellLevel >= 1 && !castAction.Countered)
		{
			using (List<RulesetUsablePower>.Enumerator enumerator3 = caster.RulesetCharacter.UsablePowers.GetEnumerator())
			{
				while (enumerator3.MoveNext())
				{
					RulesetUsablePower rulesetUsablePower3 = enumerator3.Current;
					if (caster.RulesetCharacter.GetRemainingUsesOfPower(rulesetUsablePower3) > 0 && rulesetUsablePower3.PowerDefinition.ActivationTime == RuleDefinitions.ActivationTime.OnSpellCast)
					{
						CharacterActionParams characterActionParams3 = new CharacterActionParams(caster, rulesetUsablePower3.PowerDefinition.ShowCasting ? ActionDefinitions.Id.PowerNoCost : ActionDefinitions.Id.SpendPower);
						characterActionParams3.StringParameter = rulesetUsablePower3.PowerDefinition.Name;
						IRulesetImplementationService service3 = ServiceRepository.GetService<IRulesetImplementationService>();
						characterActionParams3.RulesetEffect = service3.InstantiateEffectPower(caster.RulesetCharacter, rulesetUsablePower3, false);
						characterActionParams3.TargetCharacters.Add(caster);
						characterActionParams3.ActionModifiers.Add(new ActionModifier());
						actionService.ExecuteAction(characterActionParams3, null, true);
					}
				}
				yield break;
			}
		}
```

**Comment by ThyWoof** [comment]
Can you add more context here? Do we have anything on TT that is similar?

**Comment by HIEROT** [comment]
this is much as a PHB eldritch knight: http://dnd5e.wikidot.com/fighter:eldritch-knight war magic feature.

**Comment by HIEROT** [comment]
And in the vanilla game fighter subclass spellblade, the lvl 15 arcane escape feature also stated that when you cast spell, blabla. Though I haven't yet tested whether it will work after casting a cantrip.

**Comment by ThyWoof** [comment]
> And in the vanilla game fighter subclass spellblade, the lvl 15 arcane escape feature also stated that when you cast spell, blabla. Though I haven't yet tested whether it will work after casting a cantrip.

It won’t if using a power. I won’t touch that one as it’s against out design goals. First one might be much simpler to implement than writing another patch.

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/c908749cab136d353ca09573979dc43a326723fd
