### ISSUE TITLE
Spear Mastery's spear brace, and the opportunity attack from polearm master conflict

### ISSUE THREAD

**Issue by Kazzius** [SolastaMods/SolastaUnfinishedBusiness#3315]
If you have both polearm master fighting style, and the spear mastery feat then the polearm master's opportunity attack when an enemy enters your reach takes priority over the opportunity attack you get from spear brace that activates when an enemy enters your attack. Now when you use spear brace you don't get to add the extra die of damage to the opportunity attack damage.

**Comment by ThyWoof** [comment]
This is a very particular scenario. If both reactions are popping up this is the correct behavior.
