### ISSUE TITLE
Warlock Mystic Arcanum 9th Level overlapping with 7th Level

### ISSUE THREAD

**Issue by femmrich** [SolastaMods/SolastaUnfinishedBusiness#3316]
- Solasta version 1.5.45 - Public
- UB version 1.5.46.4

When leveling up my Warlock from 16 to 17, I am presented with the selection for a Mystic Arcanum spell. As per RAW this should be a 9th Level spell, but it is currently only listing two 7th Level spells instead (one of which I had already selected at level 13).
Aside from some other (probably) unrelated options of the mod, I am using the `Enable level 20` option and I've also added all suggested spells and specifically two 9th Level spells to the Warlock class (Time Stop and Weird).

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/35921818/9fa77031-4cc6-41a3-9795-c9fb0d4c5be4)

**Comment by ThyWoof** [comment]
Thanks for the screenshot but I also need your save.

**Comment by femmrich** [comment]
Sure, here you go. 

[16to17.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11585457/16to17.zip)

**Comment by ThyWoof** [comment]
Did you get offer 8th at 15th?

**Comment by femmrich** [comment]
Yes, the 8th Level worked fine.

**Comment by ThyWoof** [comment]
Thanks. Fixed.
