### ISSUE TITLE
Can't show options in Mod Manager

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3317]
I don't know if this is a bug with the mod, or the mod manager. I just don't know where to ask this question.
I have mod version 1.5.46.3 and Mod Manager 0.25.5.0. When I open the Mod Manager overlay in Solasta, I cannot expand the Unfinished Business entry to show the options for update.

Can I just download the newest version and install it manually? 

![grafik](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131542731/18ae3572-29f7-4f65-a6ac-0f208e73d2ca)

**Comment by HIEROT** [comment]
Please re-install the mod through mod manager, instead of updating it in the game.

**Comment by ZheToralf** [comment]
> Please re-install the mod through mod manager, instead of updating it in the game.

Why? I've always updated it through the mod manager until now. Is there an issue with that?

**Comment by ThyWoof** [comment]
Yes. This is the only workaround and auto update will start working again after that.
