### ISSUE TITLE
Voracious Fury from Barbarian Path of the reaver doesnt work

### ISSUE THREAD

**Issue by Cairnos** [SolastaMods/SolastaUnfinishedBusiness#3320]
Tried with Halberd and Battleaxe. Enemies dont take necrotic damage and you are not healed while raging (tested on human target mostly).

**Comment by ThyWoof** [comment]
this has been tested. Are you sure you have the right conditions to trigger:

```
            var isValid =
                (ValidatorsWeapon.IsMelee(attackMode) || ValidatorsWeapon.IsUnarmed(rulesetCharacter, attackMode)) &&
                ValidatorsCharacter.DoesNotHaveHeavyArmor(rulesetCharacter) &&
                ValidatorsCharacter.HasAnyOfConditions(ConditionRaging)(rulesetCharacter);
```

**Comment by Cairnos** [comment]
I'm using heavy armor indeed, it isnt written that it doesnt work with Heavy on the skill description (though it's wrote on the basic rage feature).
