### ISSUE TITLE
Crafting component not matching recipe

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaUnfinishedBusiness#3325]
Just ran into an issue where I'm unable to craft Mithral Stone because the recipe requires a crafting diamond, of which I have two.

![Recipe](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/101536157/0ae5bb26-d799-45c0-be96-dd2bbeab0e9f)

![Diamond](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/101536157/9c92b567-97e0-4990-b540-5851f5689e2c)

**Comment by ThyWoof** [comment]
Please report so to proper game forums. Game is currently full of minor issues and this is DLC content AFAIK.
