### ISSUE TITLE
Elemental Adept not functioning correctly

### ISSUE THREAD

**Issue by Rex-Draconum** [SolastaMods/SolastaUnfinishedBusiness#3328]
I only have UB 1.5.46.4 and no other mods. The feat Elemental Adept(Lightning) say "Lightning damage type spells you cast ignore target's resistance to damage. In addition, when you roll damage with these spells, you can reroll 1s." I have a Lv. 9 Circle of Night druid that took this feat and casts Call Lightning but the feat does not seem to reroll or ignore resistance. I am unsure if I just misunderstood how it work, or that it does not work with this spell but if not I thought I would make you all aware. Thank you!

**Comment by ThyWoof** [comment]
Can you zip and attach your save?

**Comment by Rex-Draconum** [comment]
How would I do that? Where would that data be located?

**Comment by ThyWoof** [comment]
Check wiki on how to report bugs.

**Comment by ThyWoof** [comment]
fixed in DEV. thanks.
