### ISSUE TITLE
Greater restoration showing error msg and stucks the game

### ISSUE THREAD

**Issue by Xelloss-CZ** [SolastaMods/SolastaUnfinishedBusiness#3333]
After casting greater restoration (after the animation finishes) I get the mod error msg and afterwards I can't move the character like it is stuck in target selection, but no selection is shown on the screen (and cannot be cancelled or something) and game cannot be saved at this point (ESC does bring up the pause menu, but save game is greyed out)

At first I thought it might be caused by the option to add bleeding to the greater restoration, but I've tried with and without this option on with multiple game restarts and still getting the same issue.

**Comment by ThyWoof** [comment]
Save and logs always help otherwise there isn’t much I can do to help.

**Comment by Xelloss-CZ** [comment]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11592972/Player.log)
[testing2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11592991/testing2.zip)

Hope this is the log you've had in mind, tried to attach save as zip file as well, this is using the premade characters for palace of ice to avoid any custom feats and such. Was hoping it would be global issue and not something I did...

**Comment by ThyWoof** [comment]
Can you try with 1.5.48.1 and share results?

**Comment by Xelloss-CZ** [comment]
[Player2.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11593196/Player2.log)

Behaves the same way

**Comment by Xelloss-CZ** [comment]
I've tried deleting the mod, loading the save and greater restoration works. I've installed the mod again, didn't turn anything on in the mod and greater restoration is not working again. (even tried to restart the campaign with nothing turned on and still not working)

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11593375/SolastaUnfinishedBusiness.zip)
can you replace the DLL in the mods folder with this one and let me know if it makes any difference?

**Comment by ThyWoof** [comment]
Don’t use above but fixed in dev.
