### ISSUE TITLE
Frozen in the upgrade screen when using an upgrade in multiplayer

### ISSUE THREAD

**Issue by DreamToCode** [SolastaMods/SolastaUnfinishedBusiness#3336]
/// The versions of Solasta and this mod.
Solasta Ver：1.5.48
MOD Ver：1.5.48.1

/// A list of other mods you have installed [you shouldn't have any].
No other modules used

/// A short description of the bug.
Game exceptions when using multiplayer archived respec characters in certain situations

/// A step-by-step procedure to reproduce it.
Use of translation, long narrative and possible syntax errors
I will try to deliver as much content as possible

1. This save is in the original version (no mods, no DLC) 

2. It is read by the host single player and uses respec to help all players respec their characters and keep the level at 1, allowing players to upgrade themselves when they enter multiplayer.

3. After a multiplayer game, when upgrading from a hotel or mod, the last page will always get stuck at the end of a level up and the page will error out. A red warning pops up at the same time.

4. You can go back and cancel the upgrade at this point, but it seems that the mod has already made a serious error and all sorts of strange things happen, such as inexplicable deaths.

[savedata.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11593468/savedata.zip)

[Characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11593466/Characters.zip)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11593470/Player.log)

**Comment by ThyWoof** [comment]
Are we talking about importing this save on POI campaign?

I can get here:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/353d25ef-1b6c-4fd8-9f2c-5a15aca502b1)

Once you get to level 10 you must cancel level up:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/ccb7049a-3882-45ea-af7a-952993227856)

They should all be at level 10:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/38b83208-dea6-4aaf-a71f-5d6033b95cd6)

Here is the game started without any issues:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/97b383bb-7be6-4af7-93fd-013158a2d70a)

Please try this sequence. Not a bug.

**Comment by DreamToCode** [comment]
雖然我不清楚POI是什麼. 但也許以下資訊可以對你有所幫助
我們決定重頭開始遊玩，如果這些資訊無法幫到你，很抱歉


1.這是一個僅限多人連線遊玩並且在此狀況時才會發生的問題

2.這個issue 是在遊玩原版官方劇情時，中途裝了mod
並使用了respec，將等級降回1等後並未直接提升等級直接進行多人遊戲

3.在多人遊戲中因為在respec後有原本的經驗值可以提升等級，進行長休後升級就出錯了

(原本的經驗值足夠提升至5)
