### ISSUE TITLE
Casting Ranger lv 4 spell >Freedom of Movement< causes "Solasta has detected mod incompatibility[...]" issue

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3340]
As the title says. When I cast Freedom of Movement with my ranger (lv 13) with UB x.x.48.1 installed, the typical Solasta error box pops up indicating a mod incompatibility. The spell's icon does not appear afterwards on the character portrait and the game cannot be saved.

I am solely running Unfinished Buisiness as a mod.

**Comment by ThyWoof** [comment]
Share your save please.

**Comment by Frobbles12** [comment]
Savegame: https://www.dropbox.com/s/wrui8etftohzl9k/POI%20-%20Elven%20City.sav?dl=0

The error occurs when you start up the game, load the save and cast Freedom of Movement on character #1 with UB 1.5.48.1 installed. Funny enough when I reload the savegame a second time and only then cast the spell, the error does not occur, but also the spell doesn't spell to have been cast correctly since no icon (Freedom of Movement) appears on the character. Also, this seems to happen only when quick weapon slot #3 (usually torch or candle) is selected.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/82675fc9-fbe0-4815-ac3d-805499ede84b)
wasn't able to reproduce on latest 1.4.49 game version and mod version in dev. wait for next mod release and test again.
