### ISSUE TITLE
Doing a short rest after character respec while crafting is in process causes mod incompatibility

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3341]
1. Start a crafting process.
2. Respec your character.
3. Do a short rest.
==> "Solasta has detected a mod incompatibility[...]" -> Game is stuck. The savegame I had made after the respec (with the crafting in process) has been unusable for me afterwards.

**Comment by ThyWoof** [comment]
Well, don’t Respec then while doing crafting. Won’t fix.
