### ISSUE TITLE
Automatic application of Arcane Weapon/Soul Empower prevents application to off-hand weapon

### ISSUE THREAD

**Issue by applefritter2** [SolastaMods/SolastaUnfinishedBusiness#3345]
Heya.  While this is not strictly a bug, I noticed that Forceblade Sorcerer's and Soulblade Warlock's (and possibly Arcane Fighter Wizard's) Arcane Weapon abilities automatically apply to the main-hand weapon now.  While handy, this prevents dual wielders from utilizing the feature if they multiclass to have two of the features (i.e. Forceblade Sorc + Soulblade Warlock).

I also noticed, with automatic application;  If one's Strength score is equivalent to the stat utilized for Arcane Weapon, the game indicates it will use Strength for the to-hit and damage, possibly preventing certain features (like the Elven Accuracy feat) from functioning.
(I haven't been able to test this yet, the game just lists Str as the weapon to-hit in the tooltip whilst having Arcane Weapon.)

**Comment by ThyWoof** [comment]
What I can do is follow same behavior as SoulBlade and allow the modifier on off hand only if TWF is taken

**Comment by applefritter2** [comment]
That sounds fair enough.  I did see an allusion in prior UB patch notes about the chang of these features to more closely reflect tabletop rules, but was unsure what that entailed or where to find such info.  I wouldn't want to stray too far from tabletop, as Solasta's strength is it's fidelity to the 5e system.

**Comment by ThyWoof** [comment]
changed in local dev. description also updated to reflect the behavior:

"Your non two-handed weapon attacks count as magical and you use your spell casting modifier for your attack and damage rolls. If you have the Two Weapon fighting style these changes also apply to your offhand attack."
