### ISSUE TITLE
Hit dice on MC heroes don't display correct usage in UI but results are correct

### ISSUE THREAD

**Issue by Kiloku** [SolastaMods/SolastaUnfinishedBusiness#3346]
When a multiclass character has different sized hit dice, you can roll the bigger dice while spending the smaller.
If I click a d10 in the UI, it rolls the d10 but consumes the dice in the order they're displayed (so the d8 go first in this example):
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/4577144/d1113709-ab81-4765-b5a6-a523c3ddadac)

The dice are ordered according to when each class level was acquired:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/4577144/30f0f698-68ff-4167-bb02-d4225a6b3781)

**Comment by ThyWoof** [comment]
I've tried to fix it but this modal is a bit complex. Will give it a try again in the future.

**Comment by ThyWoof** [comment]
fixed in dev.
