### ISSUE TITLE
RESPEC in POI stops at 12 but has a workaround

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3353]
With UB 1.5.49 respeccing a lv 14 character in Palace of Ice gives her only 120k EXP and not the actual amount the other party members have. Furthermore, this character will never again gain new EXP after the respec respectively no more than 120k rendering respec basically a "game stopper" (character is limited to lv 12 - main campaign limit wongfully checked maybe?) once you have very high levels.

**Comment by Frobbles12** [comment]
Thanks for the workaround, nirdish11, appreachiate it! Should be fixed nevertheless.

**Comment by ThyWoof** [comment]
I need a hero / save to test.

**Comment by Frobbles12** [comment]
Palace of Ice savegame: https://www.dropbox.com/s/td700ycecs6qqu2/Respec%202nd%20character-Paladin.sav?dl=0

You need to take a room at the tavern; the savegame is located there, then respec the half orc female paladin (2nd character).

In UB I activated the option to gain a feat at lv 1, for the leveling I used 27 point buy. Leveling after respec stops at lv 12 - 120k EXP.

**Comment by ThyWoof** [comment]
yep. it reuses the char creation screen and swaps them in the end. As main screen panel is fixed at 12 regardless of campaign this happens. I believe fix is easy.

**Comment by WolffHobbitStomper** [comment]
For me this issue has nothing to do with RESPEC.
Created new characters, and proceeded through game to the elven city. Characters have progressed to level 14, BUT the character sheet shows them as only having 100k experience (Level 12 value)  and needing 65k to next level.
Can't give a save game as I have some local mods.

Enabled "Allow  level 20" in gameplay/general. 
Reload save and characters are ready to level up (experience now shows 172k).
Quit and changed  line 40 of Level20Context.cs  :     
       internal const int GameMaxExperience = 195000;
Recompiled mod, reload game  disable "Allow  level 20".
Restart game and load save and characters are ready to level up correctly. :)

**Comment by ThyWoof** [comment]
Thanks, I ended up setting max experience to level 20 one
