### ISSUE TITLE
Bug Report: dual flurry

### ISSUE THREAD

**Issue by Dravolution** [SolastaMods/SolastaUnfinishedBusiness#3356]
After triggering the dual flurry feat, the monk can use 4 unarmed strikes with 1 Flurry of Blows.

**Comment by ThyWoof** [comment]
save please.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11617054/SolastaUnfinishedBusiness.zip)

Replace your mod DLL with this one and let me know if any better.

**Comment by Dravolution** [comment]
> save please.

https://www.dropbox.com/s/ytr1zzs5sr3c4zd/QuickSave_3.sav?dl=0

**Comment by Dravolution** [comment]
> [SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11617054/SolastaUnfinishedBusiness.zip)
> 
> Replace your mod DLL with this one and let me know if any better.

It's fixed. thank you for your quick work!
