### ISSUE TITLE
War magic not triggered on spell

### ISSUE THREAD

**Issue by RocketCrocodile7** [SolastaMods/SolastaUnfinishedBusiness#3357]
UB version 1.5.49.0. Solasta on Steam updated to the latest version.
Tested with spellshield fighter lv10 in first bandit fight in Ice Palace DLC.
If "Enable cantrip to trigger War Magic extra bonus action attack" mod option is OFF.
-- Neither Cantrip nor spell triggers War magic. 
If the above setting is ON.
-- Cantrip triggers War magic. Spell does not trigger war magic.
Screenshot of a battle log when the above setting is ON. 
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135159072/ae34b42d-4eb3-4512-91ca-db0209806c97)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135159072/51dde8f1-7ff3-44be-ab2d-fefb4eadec8f)

**Comment by RocketCrocodile7** [comment]
Save file for testing
https://www.dropbox.com/s/2c13iwayqm68wf3/war%20magic.sav?dl=0

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/3120fc12-0713-4242-8d34-704418219e86)
I suggest a RESPEC if not working for you. Cannot reproduce on my end.
