### ISSUE TITLE
wildshape while flying causes permanent prone

### ISSUE THREAD

**Issue by Daieumon** [SolastaMods/SolastaUnfinishedBusiness#3358]
1. cast fly on a druid
2. fly upwards
3. cast wildshape

It doesn't show prone on the wildshape portrait, and they can still attack, but the game treats them as prone for attack advantage/disadvantage. The only way to remove it is by removing wildshape and removing fly. Then the druid actually becomes prone and can stand up.

**Comment by ThyWoof** [comment]
Please report this to game developer. Not this mod.
