### ISSUE TITLE
Eldritch blast ends war dance

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3366]
with 6 lvl war dance bard and 2 lvl warlock. it seems that casting eldritch blast ends momentum of war dance. I know cantrips with melee weapon attack will mot end it, so this might be a intended.

**Comment by HIEROT** [comment]
This arguement is baed on that:
- The description doesn't  forbid it
- If you use war dance and then cast a spellwith your main action, it doesn't end. I noticed that a cantrip with attack roll (but without a weapon) with end it, which shouldn't.

**Comment by ThyWoof** [comment]
Can you test with other cantrips? Game distinguishes spells and cantrips so wanna confirm if Eb only or any cantrip

**Comment by HIEROT** [comment]
Based on what my bard has, light, vicious mockery, shocking grasp, chill touch and so on. It seems other than that 2 which makes a melee attack, all end the momentum. As for implementation, I suggest no ab penalty and no extra damage if you cast these cantrips that doesn't require a melee attack.

**Comment by ThyWoof** [comment]
@dolenam317 , can you add your thoughts here?

**Comment by ThyWoof** [comment]
Author confirmed this is working as intended.

**Comment by HIEROT** [comment]
aoh. I thought it would be fun to blast your way out lol)
