### ISSUE TITLE
Wrath and Fury feat not working

### ISSUE THREAD

**Issue by Danjeroo** [SolastaMods/SolastaUnfinishedBusiness#3368]
Wrath and Fury feat from Path of the Savagery barb doesn't seem to be working at all - Not getting the increased size category for weapons or the incapacitate trigger on critical hit.

Been dual wielding two battle axes and they're still doing 1d8 base damage and I haven't triggered the incapacitate effect a single time after critting a bunch.

Unless I'm misunderstanding how it should be working - Sorry if that's the case

Thanks

**Comment by ThyWoof** [comment]
@hiddenhax, fyi

**Comment by Danjeroo** [comment]
I've checked my feats on this character an it's not actually listed even though I'm a 12 path of savagery Barb - not sure why it's not there but I'm guessing this is why its never worked
