### ISSUE TITLE
POI Softlock

### ISSUE THREAD

**Issue by MiserableMeme** [SolastaMods/SolastaUnfinishedBusiness#3373]
In the quest The Wyvern's Nest when you have more than 4 party members and leave the castle the extra characters get stuck inside the castle and thus prevent you from continuing the campaign.

**Comment by ThyWoof** [comment]
Enable the rejoin hotkey under interface / game UI.

**Comment by MiserableMeme** [comment]
i looked all over the mod settings to see if there was something for this, can't believe i'm blind.
thank you
