### ISSUE TITLE
Widen Spell metamagic not functioning properly

### ISSUE THREAD

**Issue by ManBroCalrissian** [SolastaMods/SolastaUnfinishedBusiness#3378]
Game version: 1.5.49
UB Mod Version: 1.5.49.1

Widen Spell only works with targeted spells by adding an additional target. If a cone, cube, or sphere is selected, the Widen metamagic button is grayed out. Alerting you guys to this bug will probably upset some people but being able to Twin a 7th level Disintegrate for 2 points instead of 9 is pretty broken.

 
![Screenshot (651)](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/132740498/e1ee1d99-7f94-4f21-85d3-4064b59db430)

P. S. I didn't have a cylinder spell to test, but cone, cube, and sphere definitely don't work.

**Comment by ThyWoof** [comment]
Please share your save to simplify debugging.

**Comment by ManBroCalrissian** [comment]
This is from the moment before I created the screenshot above.

[AutoSave_10.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11633585/AutoSave_10.zip)
