### ISSUE TITLE
Is this wrong text?

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#3388]
wis-[You gain proficiency with herbalism kit and Arcana, or medicine if already proficient.]
But in the game, it's medicine, not arcana.
cha, int -[You gain proficiency with herbalism kit and medicine, or expertise if already proficient.]
It works fine here, and what is written in the text is different from wis.

**Comment by EnderWiggin** [comment]
which feat?

**Comment by kdgmo** [comment]
Apothecary [Wis]

**Comment by ThyWoof** [comment]
Update you mod version. This has been fixed a long time ago.
