### ISSUE TITLE
Softlock When Leveling Multiclassed Character

### ISSUE THREAD

**Issue by Nerdnub** [SolastaMods/SolastaUnfinishedBusiness#3389]
Solasta Version: 1.5.49
UB Version: 1.5.49.3

One of my characters is a multiclass Rogue 3 (Arcane Scoundrel)/Inventor 1. Upon leveling to 5, I'm given the option to forget a known spell and learn a new subclass spell. Unfortunately, I can't forget any spells (all greyed out), and I'm unable to choose any new spells (nothing I click on registers, and auto select doesn't do anything). Because of this, I'm stuck in the leveling process and unable to continue. I can cancel out of the level process, but you can hardly beat the game with a level 4 character. Choosing another class to level in doesn't seem to bypass the issue.
[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11642277/Solasta.zip)

Saves, characters, and log uploaded.

**Comment by EnderWiggin** [comment]
How your rogue knows both Malediction and Hunter's mark spells? None of them are in the wizard spell list (for arcane scoundrel) nor in the Inventor spell list

**Comment by EnderWiggin** [comment]
When I tried re- creating same character from scratch or levelling attached character I had no such problems with unlearn or learn.

**Comment by ThyWoof** [comment]
Whenever it happens, Respec. You probably missed the changelog.

**Comment by Nerdnub** [comment]
The issue is easily reproducible if I level up the character (or any character as I tried on multiple test ones) the same every time (Rogue for first three levels, Inventor for level 4). Every time picking a 5th level with any spellcasting ability (including another level of rogue with Arcane Scoundrel), you can't get past picking a subclass spell. 

I believe there's a conflict that occurs if you level in Inventor on the next level after you take the Arcane Scoundrel subclass. Leveling to Rogue 4 (and picking Arcane Scoundrel) and then picking Inventor for the 5th level doesn't trigger this issue on subsequent levels. This issue does not trigger if you level a different spellcasting class on the level after you pick up Arcane Scoundrel (tried with Wizard, Sorcerer, and Warlock).
