### ISSUE TITLE
instability when extinguishing fire

### ISSUE THREAD

**Issue by ThorgenIronside** [SolastaMods/SolastaUnfinishedBusiness#3392]
Unsure if it is mod related or game related.  Get "soft" crash when extinguishing fire, get mod instability dialogue...then game is "soft" crashed as it is stuck at the last action given as the extinguish action. 

If relevant occurred twice in boss battle "Lost Valley" expansion ... mission "Manacalon Riches"

:) As always the work you put in on this mod is top notch.

**Comment by ThyWoof** [comment]
it's the mod. got a save I can use to debug?

**Comment by ThyWoof** [comment]
Fixed on dev
