### ISSUE TITLE
Chinese unofficial translation can't wrap lines

### ISSUE THREAD

**Issue by YuanHuaiYu** [SolastaMods/SolastaUnfinishedBusiness#3394]
Chinese unofficial translation can't wrap lines, please check and read notes, letters, books in the game.
This is also happened on the official version too, but it's even worse on this unofficial one.
A lots of text overflow and not able to read.

EX:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/26790754/fe8d038a-34a3-4727-ae44-6f00f907b698)

中文非官方翻譯不能自動換行，在筆記、信件、書籍中大量發生。
官方版本上偶爾也能看到類似的情況，但在非官方版本上幾乎到處都是。
只要單行文本一長就直接溢出，無法閱讀。

**Comment by ThyWoof** [comment]
@magicskysword , FYI.

**Comment by magicskysword** [comment]
So far, it seems that Solasta's line break calculation was wrong for Chinese or any CJK language, an unspaced language.I will try to see if I can make a patch to fix the problem.

目前索拉斯塔对中文（或者日文、韩语）的换行计算有问题。我去试试做个补丁看看能不能修复一下。
