### ISSUE TITLE
Inventor Minor Elemental Infusion

### ISSUE THREAD

**Issue by XxGeorge** [SolastaMods/SolastaUnfinishedBusiness#3396]
Not sure if this an issue with the infusion itself or just the tooltip for it, the tooltip says it increases to 2d6 at level 9 and 3d6 at level 15 however my characters are level 10 and are still getting only d6. I lean toward it being more of a tooltip issues because otherwise minor is better then Major Elemental because that only give d4 all be it to all attacks instead of just the first each round but its tooltip doesn't say anything about an increase.

**Comment by ThyWoof** [comment]
Share your save please.

**Comment by ThyWoof** [comment]
changed both to use character level as infusions can be taken off an inventor. also bumped major a bit with similar dice progression.
