### ISSUE TITLE
Blade Mastery is broken v2

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3397]
After the latest change to the Blade Mastery feat it appears you do not lose the +1 ac after unequipping a bladed weapon.

**Comment by ThyWoof** [comment]
by design. it became a +1 passive.

**Comment by MartinBrandstrup** [comment]
But isn't it supposed to just be +1 passive while having a bladed weapon equipped?
