### ISSUE TITLE
Barbarian Path of Savagery Grievous Wound missing icon on portraits

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3398]
Another one! Helps to keep track of debuffs.

**Comment by ThyWoof** [comment]
are you sure? share screenshot. It uses bleeding icon. this was tested.

```
        var conditionGrievousWound = ConditionDefinitionBuilder
            .Create($"Condition{Name}GrievousWound")
            .SetGuiPresentation(Category.Condition, ConditionDefinitions.ConditionBleeding)
            .SetPossessive()
            .CopyParticleReferences(ConditionDefinitions.ConditionBleeding)
            .SetConditionType(ConditionType.Detrimental)
            .CopyParticleReferences(ConditionDefinitions.ConditionStunned)
            .SetParentCondition(ConditionDefinitions.ConditionIncapacitated)
            .AddFeatures(ConditionDefinitions.ConditionIncapacitated.Features.ToArray())
            .AddToDB();
```

**Comment by ThyWoof** [comment]
blueprint dump also confirms a [reference ](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/a19733afffae1b4dee8c0458bf4c363242cf8392/Diagnostics/UnfinishedBusinessBlueprints/ConditionDefinition/ConditionPathOfTheSavageryGrievousWound.json#L144)to bleeding icon. If not displaying then it's a vanilla bug they might fix on next patch. Many assets got corrupted on 1.5.49.

**Comment by MartinBrandstrup** [comment]
Hmm actually yeah you are right it turned up later. I did have one situation where it did not show up, but did not manage to catch a save.
