### ISSUE TITLE
Repeating shot infusion depletes specialized bolts when used.

### ISSUE THREAD

**Issue by AngerSalt** [SolastaMods/SolastaUnfinishedBusiness#3410]
As far as I can tell, the repeating shot infusion for the inventor is depleting specialized bolts like the title says. I know for a fact it doesn't do it with regular bolts, and thus far I've only tried with acid bolts specifically. As such I can't be sure if it's happening across the board or not, but I figured I'd let you guys know about it. Thanks!

**Comment by dolenam317** [comment]
This is work as expected. No infinite special arrow.

**Comment by AngerSalt** [comment]
Sorry, i just looked at it again and you're right. The ammo property
contradicts what I was saying.
