### ISSUE TITLE
Rest/Level up screen needs scroll option

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3417]
Thankfully I was able to remove the "Attune" option so I could finish my level up, but if this Pace guy gets any more features, it is going to become an issue. Is it possible to add a scroll bar or something similar to this screen?

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44898614/b1526421-77f2-4850-a6c2-61e66449cafc)

**Comment by ThyWoof** [comment]
Check the setting under interface / game ui that was created for this scenario.

**Comment by EnderWiggin** [comment]
In mod settings there's `Interface => Allow more real estate on rest panel` option. It will help a bit by hiding post-rest actions before rest, and pre-rest actions after rest.

**Comment by MartinBrandstrup** [comment]
Ah cheers. Was not aware that was what that did
