### ISSUE TITLE
Switch for unofficial fixes of vanilla subclasses introduced first in 1.5.4.93?

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3418]
Maybe we can add options for the changes made to oath of judement and swiftblade (though I am not aware of details)? Are these fixes made to better follow their descriptions or something?

**Comment by ThyWoof** [comment]
These are indeed bugs that most likely will get fixed on future patches. No need for an UI option for that.
