### ISSUE TITLE
5th party member doesn't travel with group

### ISSUE THREAD

**Issue by captmac7** [SolastaMods/SolastaUnfinishedBusiness#3420]
The issue is related to playing with a party size of 5 and the bug is game breaking and prevents me from progressing. 

In Glendale Castle, after killing the General and trying to exit the Castle, my 5th party member stays behind and there is no way for him to meet back up with the party.  
I've tried reloading prior saves before I entered the zone, changing the layout of the group, killing the party member.  There are no fast travel locations on the map and the character is too far to try a short rest or anything to see if it would group them back together. No vendors either to start a conversation.  I tried to see if there were any mods or cheats to force teleport the character to the group but I've been unsuccessful.  
If not also obvious, I'm running the latest version of the mod. 
Edit: Wanted to mention there is no way to travel back to this area once you leave.

**Comment by captmac7** [comment]
Adding a couple screen shots to show what I mean. 
![20230605200629_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1341821/0295d8ff-8a79-4ee3-9f55-534c1b3252f9)
![20230605200703_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/1341821/9cb3093e-d85a-46cf-af34-69ec8b8db365)

**Comment by kosocku** [comment]
Have you tried CTRL+SHIFT+R while selecting a character that's already in the new area to teleport the party to them?

**Comment by captmac7** [comment]
Omg you are my hero! I was so upset that I've potentially lost all this progress.

**Comment by kosocku** [comment]
Glad it worked out!  Cheers!
