### ISSUE TITLE
Re Issue #2717

### ISSUE THREAD

**Issue by rbhauen** [SolastaMods/SolastaUnfinishedBusiness#3430]
This appears to be related to issue 2717
https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/2717

Hello! Firstly, thanks so much for creating and supporting this mod, loving it so far. 

I have also encountered this looting issue. This occurs with both controller and mouse/kb. I can easily reproduce this issue by dropping an item on the ground and trying to pick it up. Usually I can pick up loot after a few tries, but sometimes it just doesnt want to work. In these cases I have to make a character stand on the loot bag so that the loot action appears on the ui. I have attached a save with an item dropped on the ground, let me know what else I can do to help!

[Cant loot.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11677514/Cant.loot.zip)

**Comment by ThyWoof** [comment]
this is a limitation on how custom formations work. we've changed the default formation to minimize that. nothing else we can do.
