### ISSUE TITLE
POI Save Load

### ISSUE THREAD

**Issue by XxGeorge** [SolastaMods/SolastaUnfinishedBusiness#3432]
Not sure if there is something wrong with my save or if it doesn't like the inventor, when I click import the button changes to loading and just sits there forever, if I hit esc to go back and try and select a character it has loaded three of the save characters but not the last, which is the inventor. I searched around and didn't find anything of anyone else have a similar issue, figured I would share my save, if you can find something great, if not thanks for trying :) 
[End_NrNObYWdBUCT6yxAZdzO5A.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11679837/End_NrNObYWdBUCT6yxAZdzO5A.zip)

**Comment by ThyWoof** [comment]
Have you tried on a long rest cancel all inventory infusions and save? Try this other save?

**Comment by XxGeorge** [comment]
I had not, but that worked, thank you!
