### ISSUE TITLE
Uinity not starting after Solasta patch (Game Pass)

### ISSUE THREAD

**Issue by Dejf27** [SolastaMods/SolastaUnfinishedBusiness#3435]
Hi guys, I have the Gamepass version of Solasta and today, after the patch to the version 1.5.52.0 the unfished business mod is not starting after starting the game. This means that I'm not able to load any saved game etc.  The UnitymodManger shows me the following:
Version 1.5.9.0
Manager 0.24.0
Status: OK

I don't see any error massages in the logs of the UnitymodManger.

**Comment by ThyWoof** [comment]
Every time game is patched you need to reinstall patch from UMM.
