### ISSUE TITLE
Eldritch Smite not knocking down enemies anymore? 

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3436]
Thank you all for this wonderful mod,  but I remember that maybe a dozen of releases ago the eldritch smite invocation did knock down enemies. 
Citing xge: 
> Once per turn when you hit a creature with your pact weapon, you can expend a warlock spell slot to deal an extra 1d8 force damage to the target, plus another 1d8 per level of the spell slot, and you can knock the target prone if it is Huge or smaller.

Is it removed accidentally or not?

**Comment by ThyWoof** [comment]
I cannot remember ever having knocking down there. @EnderWiggin , did you ever implement that?

**Comment by HIEROT** [comment]
Maybe 1.4.33.84 and earlier has this feature,  let me check code lol

**Comment by HIEROT** [comment]
Alright the code says no.  Mandela effect?  I don't really know but I remember clearly at that time I was playing a blade pact warlock and knocking prone monsters. Maybe I can implement this.

**Comment by ThyWoof** [comment]
Be our guest. Will close this one
