### ISSUE TITLE
Thorny Vines should be affected by Spell Sniper.

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3441]
Even though it's a melee attack, Thorny Vines should still be affected by Spell Sniper, since its effect is to double the range of all spells that make any kind of attack rolls. However, this currently isn't working.

Thorny Vines's description ingame states that it is a "ranged spell attack against the target".
It should be a "melee spell attack". I believe the spell is coded correctly, but the description is wrong.

The description also does not say the range of the spell. Unfortunately, the spell's range tooltip just says "melee hit", and provides no information about its range.

**Comment by ThyWoof** [comment]
Thorn Vines was coded as a melee spell attack to avoid DIS when within 5 feet. It's an extended behavior that'll also allow a range 6 cells attack. Unfortunately I cannot fix both so by design decided to go with the more common "wanna use it at melee range".

Won't change.
