### ISSUE TITLE
Long Mace +3 dont have correct stats

### ISSUE THREAD

**Issue by Majber** [SolastaMods/SolastaUnfinishedBusiness#3442]
I crafted Long Mace +3, and it dont have +3 to attack and +3 to dmg. Its just have normal Long Mace stats.
Screen below, for comparision Thundering Long Mae have correct stats.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8217598/4bba2548-2304-47ce-a534-f5624388ff1d)

**Comment by ThyWoof** [comment]
share a save please.

**Comment by Majber** [comment]
Here is save,1st char have this weapon:
[QuickSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11691910/QuickSave_2.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d13d24d1-9c4b-416f-8c21-914eaf99228d)

fixed in dev. thanks
