### ISSUE TITLE
Cantrips gained from Spell Sniper don't get the damage bonus from Potent Cantrip

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3443]
Potent Spellcaster (Druid) grants a damage bonus to any Druid cantrip in your repertoire.
Spell Sniper (Druid) lets me pick cantrips from the Druid spell list.

Cantrips learned from the Spell Sniper feat don't get this bonus even though they seem to be druid spells.

**Comment by ThyWoof** [comment]
fixed in dev.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/575ebaa8b62e110317e67205a0eabcd943529822
