### ISSUE TITLE
Starting Palace of Ice Issue

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3447]
Finished Crown of the Magister with a party of 5 member, and when i try to import that party to Palace of Ice, it only loads 4 party members, but not the 5th one.

**Comment by HIEROT** [comment]
You can export all characters and start palace of ice with these characters instead of that save

**Comment by ThyWoof** [comment]
Sharing your save also helps

**Comment by Geriboys** [comment]
[Modded.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11696688/Modded.zip)

**Comment by ThyWoof** [comment]
also what is the mod version?

**Comment by Geriboys** [comment]
1.5.52.0

**Comment by ThyWoof** [comment]
I cannot even import this save. It aborts on me. I suggest opening the save, resting, canceling any infusion items if you have them and then try import.
