### ISSUE TITLE
Duel-wielding with Shadow Blade spell

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3448]
When you cast the Shadow Blade spell and you have a second weapon in you off-hand, the off-hand weapon will have advantage on attack rolls as well, if you are in dim light or darkness.

**Comment by ThyWoof** [comment]
Can I have the save for debug?

**Comment by Geriboys** [comment]
Sorry, didn't reported bugs before today, here it is
[Modded.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11696692/Modded.zip)

**Comment by ThyWoof** [comment]
fixed in dev.
