### ISSUE TITLE
+2 Monk Clothes (+2 AC/Saves) not applying bonuses

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#3451]
I just finished creating the +2 Monk Outfit of Survival (+2 AC and Saves) and equipped it, but am not getting the +2 bonuses.  I know it's not because the outfit is being treated like armor because if it was, my AC would drop by 3 (from 10+5Dex+5Wis to 10+5Dex+2 from outfit).  Please note that my Monk gets +2 anyways from Paladin Aura and the Monk Focus Necklace (+1 Ki and +1 AC)

1.5.52
UB 1.5.52.0
[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11699289/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
It won't stack with Unarmored defense. Shouldn't have created this item.
