### ISSUE TITLE
General Cursor Inaccuracy

### ISSUE THREAD

**Issue by Connormsmith** [SolastaMods/SolastaUnfinishedBusiness#3452]
Since the updating to the latest version of the mod, there are general cursor inaccuracies in out of combat movement, interactions, and targeting.

For example, with only one character selected clicking on a specific tile will usually position you on a neighbouring tile instead, as if you are the 4th character in a group action.

I cannot interact with bags on the ground as a result, I open doors whist standing to the left/right of them.

3 other users I play online with have this issue, initially I thought it may be a desync issue, tried solo on the same save, same issue. I then thought it may be a Palace of Ice map issue as I just started the campaign, tried a base CoTM save solo, same issue. Tried a save that I created without mods but with the mod installed, same issue.

After uninstalling the mod the cursor returned to normal behaviour.

Please let me know if you need any more info or have any suggestions.

**Comment by ThyWoof** [comment]
I need your save please.

**Comment by Connormsmith** [comment]
[BRAND NEW ADVENTURE.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11699546/BRAND.NEW.ADVENTURE.zip)


Attached - BRANDNEWADVENTURE - This is the Palace of Ice save where I first noticed the issue

The quicksave is a vanilla save that I loaded up to do some further testing.

**Comment by ThyWoof** [comment]
Are both saves at same location on POI campaign?

**Comment by Connormsmith** [comment]
No, the quicksave is from the main CotM campaign, which i created before installing any mods a few weeks ago.

**Comment by ThyWoof** [comment]
So I won’t be able to get to a deterministic conclusion. Given the game was updated yesterday, and they did a bunch of changes on POI, I believe you should report this issue to TA unless you can show us a non modded save at the same location as the issue you are reporting.

**Comment by Connormsmith** [comment]
OK, in that case I will give you this example.

[Test Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11701792/Test.Save.zip)

Here is a save where if I have the mod installed, i experience the inaccuracy issue. When uninstalling the mod the cursor behaves as normal.

I can also send over videos of this as it is easily replicated on my end.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/b8984766-6d74-46f1-8f6c-e673bf88cdb9)

I cannot replicate on mine. Opened the save, using one hero, clicking around and they are indeed getting to where I click.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/64a7c5ef-04e0-4b20-866b-6ed39a81d892)

Also no problem with aiming.

I cannot help if I cannot reproduce.

**Comment by Connormsmith** [comment]
Hi, after doing some more testing, its seems it is a setting within the mod that I have toggled that is affecting this.

After reverting to the default settings of UB and reloading, the issue no longer persists.

I am currently in the process of toggling the settings 1 by 1 and restarting inbetween each to see if I can find the specific setting that is causing this issue for myself. 

Below is my settings file:

[Wawaweewa.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11702149/Wawaweewa.zip)

If I can identify the specific setting I will update this issue.

**Comment by Connormsmith** [comment]
After enabling each setting individually and testing each time, I could not identify the issue.

I then reloaded the settings that I thought that were causing the issue, but those now seem to work????

Sorry for sending you on a wild goose chase.

Here is a clip of the issue I was experiencing, just for my own sanity that something was happening.

https://streamable.com/yrf2t7

Again, no idea what fixed it. But it seemed to resolve after resorting to default setting and reapplying the settings which I had on the previous file I had sent.

I will be playing with my group later on, hopefully I can just send over the settings file that I have and that will resolve any issues.

**Comment by Knitby** [comment]
For those who came across this problem as well, apparently, the issue was in the "Formation Set" options under Interface. I had this issue as well and saw this report so I gave the settings.xml posted by @Connormsmith a try. All you have to do is just play around with the formation set to make it so that the movement is accurate to the area that the cursor clicked.
