### ISSUE TITLE
Regrowth on Ancient Forest Druid doesn't display power button

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3455]
I don't see any way of using the feature. Am I missing something?

Save files:
[bug report.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11702935/bug.report.zip)

Screenshot:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/8b00e483-c69d-432b-81a0-dedf1fa3dfef)

**Comment by ThyWoof** [comment]
This mod is huge and such a summarized context doesn’t help. Please tell me what you did, what you expected and what happened with step by step to reproduce on above save.

**Comment by miridistress** [comment]
My apologies.

At level 2, the Circle of the Ancient Forest druid is supposed to gain an ability called Regrowth that grants a pool of hit points that can be used to heal people, like the Paladin's Lay on Hands feature.

In this save file, I started in a game where I jumped from level 1 to level 3 very quickly. I levelled my character as normal, but the character never gained a button on the actions toolbar I can press to activate the healing.

**Comment by ThyWoof** [comment]
Strange that Ranger Light Bearer uses the same pattern and button displays there.

**Comment by miridistress** [comment]
That is strange. Were you able to reproduce the bug?

**Comment by miridistress** [comment]
Thanks a lot!

**Comment by ThyWoof** [comment]
Still no idea why only Druids cannot show this power. Will keep researching.

**Comment by kosocku** [comment]
I don't know if it was the new update, or if there is something else going on (like a UB setting) that's affecting it, but I tried creating a new character at lvl 2 and have the ability to use Regrowth
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/122100625/69b1de16-c1c0-4317-be0d-4204b5bb597d)
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11714476/Save.zip)

**Comment by ThyWoof** [comment]
What?

**Comment by kosocku** [comment]
I get the Use Power button from Gameplay > General > Creation > enable "Use the Help action to all playable races" option, and it was showing there as usable, where it's not even showing as an option for yourself and miridistress.

**Comment by ThyWoof** [comment]
Can you share your settings?

**Comment by kosocku** [comment]
I THINK I did this right.  Haven't tried before
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11714490/Save.zip)

**Comment by ThyWoof** [comment]
@EnderWiggin 

Created 2 Druids from scratch. Didn't have Help action toggle selected on first one.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/14f129c6-2608-4940-8868-27457b453d5a)

Second one correctly presents the button.

[DruidMissingPower.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11714519/DruidMissingPower.zip)

**Comment by kosocku** [comment]
Gotta step out for an hour or so, but hope that helped!
