### ISSUE TITLE
Bladesinger's Dance of Defense doesn't work?

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3464]
Bladesinger wizards Dance of Defense feature doesn't seem to work. White Dragon used its breath weapon on the wizard, the wizard succeeded the Con save and used a lvl 6 spell slot to negate 30 damage. However, the breath weapon had 61 damage originally, i succeeded on the save, so it got halved to 30. This is only just succeeding on the save, but that 30 damage reduction is nowhere to be seen from the Dance of Defense.
Minerva is the Bladesinger of the party, so the log can be used on the picture
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/116584266/15107992-ede8-4eef-8e36-0e50f9275da9)
Save file: 
[moodded poi.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11708454/moodded.poi.zip)

**Comment by ThyWoof** [comment]
The way combat log displays damage reduction is a bit odd. Was blade dancing active on her? Can you share another screenshot?

**Comment by EnderWiggin** [comment]
Can this be some vanilla issue that prevents multiple damage reductions to apply?

**Comment by Geriboys** [comment]
Yes, Blade Dancing was indeed active, otherwise it wouldn't give me the option to reduce the damage. And sorry i already past that encounter so much, even my auto saves are past that. But i will try to recreate the situation by traveling and triggering random encounters see if the results are the same and share screenshots. Although its Palace of Ice campaign, i don't know if this info helps at all, but might be useful.

**Comment by Geriboys** [comment]
Blade Dancing is indeed active:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/116584266/c8e7ae76-7769-4d5c-a5ec-0abd5e9ef5a9)

White Dragon is doing the Poison Breath (lol) and i have the option to reduce the damage. I will only use a 2nd level spell slot, so the damage reduction is only 10:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/116584266/f13b0bf1-2750-47db-a313-3fd6463ecba9)

The original damage would be 59, but the blade dancer (Minerva) succeeded on the saving throw, so halves the damage to 29, but still no damage reduction to be found from the Dance of Defense:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/116584266/1c05733a-9ea3-4ebd-8d1f-ac6c3ebdd9a2)

**Comment by EnderWiggin** [comment]
please provide save file made in that (or similar) battle for ease of reproducing.

**Comment by Geriboys** [comment]
Here it is
[AutoSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11710355/AutoSave_2.zip)

**Comment by ThyWoof** [comment]
Thanks. Will take a look

**Comment by ThyWoof** [comment]
@EnderWiggin , very strange. found this:

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c9f310e1-8868-4c91-a9ff-ca3961dfb801)

why it's showing the reduced damage on other heroes? I chose a level 5 spell for the -25.

**Comment by EnderWiggin** [comment]
oh.... so I was right doubting that current implementation is valid. It adds negative damage bonus to the first damage form. So it will affect everyone

**Comment by ThyWoof** [comment]
Fixed in DEV.
