### ISSUE TITLE
Savage Barb Locks up game

### ISSUE THREAD

**Issue by Cocalus** [SolastaMods/SolastaUnfinishedBusiness#3468]
Solasta V 1.5.52 - Public (All DLC)
Unfinished Business 1.5.52.1
On the "Devilish Deals" campaign from the steam workshop

If my savage barb hits three times I get a instability warning and the game stops letting me interact other than a few menus like loading, and esc.
Most likely explained by the NullReferenceException in the "Player" log

The only bug I was having before (which maybe the campaign), is clicking on items to loot often didn't work. But I could work around that since the second character would be on top of the item, and I could pickup through their menu.

[bug_report.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11711333/bug_report.zip)

**Comment by ThyWoof** [comment]
I suggest getting to a save off battle and taking a long rest. It looks like there is a current effect on Barb trying to apply a power that got removed on last version. You can also rollback to 1.5.52.0 to finish this battle, take the rest and then update again.

**Comment by Cocalus** [comment]
Long rest didn't help but trading out the offhand weapon fixed it
