### ISSUE TITLE
Monk Way of survival - lvl 11 feature "unmoving strength" adding double con modifier

### ISSUE THREAD

**Issue by Onlynoobss** [SolastaMods/SolastaUnfinishedBusiness#3470]
The level 11 feature for Way of Survival Monk (unmoving strength) is adding twice the con modifier to damage with the mod installed instead of just the con modifier.

With Mod active -Unmoving strength adds +4 damage with a +2 con modifier
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/136149966/4b133ef1-b4f3-429e-94cc-b491a84790d0)

Without Mod active -Unmoving strength adds +2 damage with a +2 con modifier
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/136149966/d2512649-7264-43c3-bc1d-f590af7ffc6d)

**Comment by ThyWoof** [comment]
I can confirm we have one patch on method that calculates these additions. Indeed when this patch is disabled it works correctly. Still haven’t found a fix.

**Comment by ThyWoof** [comment]
Issue was found. To be fixed in dev.
