### ISSUE TITLE
[1.5.52.1] Flanking with the tabletop rules should not give advantage 10ft away with reach weapons

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#3475]
The TT flanking rules require that the attacker and ally on the opposing side be both adjacent to the target. Currently, a character using a reach weapon has advantage 2 squares away, which they shouldn't.

**Comment by ThyWoof** [comment]
We decided to keep reach on attacker by design.

**Comment by Andargor** [comment]
> We decided to keep reach on attacker by design.

Could this be a house rule option? It doesn't match what we are used to in TT.
