### ISSUE TITLE
[1.5.52.1] Flanking does not work properly with creatures larger than medium

### ISSUE THREAD

**Issue by Andargor** [SolastaMods/SolastaUnfinishedBusiness#3476]
Currently, flanking does not provide advantage properly with creatures larger than medium, only certain squares seems to provide it. It should allow advantage according to the position of the attacker and at least one ally on the entire opposite sides of the creature, or diagonals.

I am still willing to review the code and propose a PR to implement it properly.

See this guide: https://www.dndlounge.com/flanking-5e/

Diagram showing where it applies or not (only medium and large shown, but should apply to Huge, Gargantuan and Colossal too):

![flanking-5e-squares-examples](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/fe327dea-d0ad-4ea4-af86-0e31190dc101)

**Comment by ThyWoof** [comment]
It won’t trigger on row 3, col 2 scenario. Which on above scenarios it isn’t working?

**Comment by Andargor** [comment]
Just looking at the Large creatures, and skipping reach weapon tests:

### Should grant advantage, but doesn't

![mzReNz9](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/0460b16f-4631-415a-be5d-036b9a8ce34f)

![KZ11C2L](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/39cb1564-6ea3-4c82-bde1-aaccdec7ad54)
![WaIGDS8](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/cdf6ebcf-05fc-4d82-a29e-d0198f7c4a18)

### Grants advantage but shouldn't

![WaIGDS8](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/cdf6ebcf-05fc-4d82-a29e-d0198f7c4a18)

**Comment by ThyWoof** [comment]
How tall is that monster? You’re flying. Depending on height attack is coming from a diagonal and won’t trigger.

**Comment by ThyWoof** [comment]
Game is also a bit odd as it uses the height as well to determine sides. Can you test with races like human, elf, etc.?

**Comment by Andargor** [comment]
Test #2, fairy flight dismissed, oddity in the diagonal. Monster is large, by definition it's a cube, so 10ft tall in this case.

### Works

![iZDiaZb](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/b119d02f-1371-41ba-93ec-3621e80e39e2)

### Does not work

![wnKUHAL](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/0978c384-b59f-4701-a623-59f74efec96b)

### Does not work

![X75Jwh5](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/ae97f5bf-b09a-480c-92a7-2302e75b6d45)


### Does not work

![l0tzTKm](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/a7700e6e-6a7b-42ee-b008-f33797012381)

**Comment by Andargor** [comment]
> Game is also a bit odd as it uses the height as well to determine sides. Can you test with races like human, elf, etc.?

Additional test for medium size opponents, or the attackers should be human or elf?

**Comment by ThyWoof** [comment]
I’ll add some log messages on next release for debugging. What is flanking does is first determine the attack direction. It uses in game logic to find from which side attack is coming. It looks for friends on opposite sides. My hunch is I cannot leverage this side determination logic because of game oddities on height

**Comment by ThyWoof** [comment]
Also can you pull and use DEV? Setting for reach added

**Comment by Andargor** [comment]
> Also can you pull and use DEV? Setting for reach added

Sure I'll try it out.

**Comment by Andargor** [comment]
Also, your comment about height makes it a n interesting problem, since flanking can occur in 3D: top/bottom and diagonals

**Comment by Andargor** [comment]
> Also can you pull and use DEV? Setting for reach added

The reach setting works. For fun, I'll see if I can come up with an algorithm for 3D flanking

**Comment by ThyWoof** [comment]
Consider enabling DEBUG panel under tools. Once open, there is an option there to render the game in different modes. I believe one of them will simply render the cubes on the scenario. Quite useful instead of monsters. Also added the logging but need to enable on settings.xml.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/a1ed4517-65a6-41b3-b49f-3d6766910459)
indeed this is incorrect.

**Comment by ThyWoof** [comment]
> Also, your comment about height makes it an interesting problem, since flanking can occur in 3D: top/bottom and diagonals

reason why I leveraged the in game method to determine sides.

**Comment by ThyWoof** [comment]
https://math.stackexchange.com/questions/3775806/finding-the-side-of-a-cube-intersecting-a-line-using-the-shortest-computation is a good start but won’t handle diagonals

**Comment by ThyWoof** [comment]
please pull DEV and check if above fix is sound.

**Comment by Andargor** [comment]
> please pull DEV and check if above fix is sound.

On medium targets, was fine in 3D, for Large the following cases failed, did not check top/bottom:

![6LpHsoy](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/4ca4ee46-3e16-4689-8c63-617985973fef)

![SgGbUfb](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/f0bb7aed-1841-4f82-ad10-5f1f79b21ae9)

![irOhfE3](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/6f6cdd58-2cb7-4c00-bb26-a7bafb8f062b)

![2vRH0AW](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/5ea454ed-ec7f-44c4-9451-0ab6822d9d9f)

![qcLuvNA](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/7e077312-3050-495e-aab1-23183baf77ad)

**Comment by Andargor** [comment]
This is a lot harder than I expected 😄 

I am looking into two solutions:
- Using a better function than CellFlags.InvertSide to determine what is opposite (not that it can have three ORed flag components, e.g. Top | South | East). It's inelegant but explicit
- The math approach, LocationBattleBoundingBox could be interesting since it contains all size info

Going to bed, will look at it tomorrow

**Comment by Andargor** [comment]
Also, almost forgot, the Large creature's location is one square even though it occupies two by two squares, so that when you determine the side of the attacker or allies, if you are not next to that "anchor" location, you will get two side components, e.g. South and West, even if you are on the flat side of the creature and not a diagonal, since you are offset from the "anchor" location.

**Comment by ThyWoof** [comment]
I'm working on a new test considering all cells on all 3 contenders but need to optimize it a bit. tomorrow will push.

**Comment by Andargor** [comment]
I pulled out an old math algorithm which seems to work for all sizes EXCEPT the case of Row3 Col2, it's annoying.

As a second step, there should be consideration for an attacker that is larger than medium, any of its squares on the defender side might be valid for flanking. Currently I am using the center of the location, which may not work in all cases for a large attacker, would probably need to walk the squares on the defender side

**Comment by ThyWoof** [comment]
Have you checked the latest implementation. It seems to be working on these scenarios. I’m dev only

**Comment by Andargor** [comment]
> Have you checked the latest implementation. It seems to be working on these scenarios. In dev only

Fails on these tests, again I think it's because the location for large creatures is one of the four squares it occupies, so determining sides can be unreliable, unless you make sure the side that the attacker and ally are on take this into account (i.e. use the closest square to them)

![nQ1pwEu](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/0fbc16f0-3a29-4d5a-a5fa-cabefb9cdd2f)

![UCaNokT](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/e14cf71f-6e34-4f00-ab10-df4895015bef)

![TzX7ke0](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3580755/35b4ee0b-9f27-427b-9631-e410a22803ed)

**Comment by Andargor** [comment]
I am starting to doubt the validity of case Row3 Col2. The rule says:

> When in doubt about whether two friendly characters flank an opponent in the middle, trace an imaginary line between the two friendly characters’ centers. If the line passes through opposite borders of the opponent’s space (including corners of those borders), then the opponent is flanked.

I'm doing it with math, center to center, and Row3 Col2 does not and should not work (you can just draw a line from the center from the attacker to ally, and see it doesn't cross opposite sides). So in that regard, the guide I quoted seems to be wrong.

I'll test and clean up my code and post a PR, if you wish to use it. It's not pretty for the moment but it's usable.

**Comment by ThyWoof** [comment]
Issue is this code executes every time the cursor is on enemy on refresh. It’s to be very optimized or game will slow down on FPS.

**Comment by Andargor** [comment]
> Issue is this code executes every time the cursor is on enemy on refresh. It’s to be very optimized or game will slow down on FPS.

Yeah I'll be using your cache code and making sure it breaks out without going through N iterations.
