### ISSUE TITLE
Missing link for Soul Empower

### ISSUE THREAD

**Issue by ITCronin** [SolastaMods/SolastaUnfinishedBusiness#3479]
Hi,
Since the change to warlock soulblade, I haven't had a button in-game for Soul Empower though it says I do in my character sheet.  If I'm just not understanding a rule right (likely) can you plea
![MissingSoulEmpower1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/68248291/3599474c-1790-473e-8fb8-c332a31414b6)
![MissingSoulEmpower2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/68248291/b4bd7cf7-149c-4bff-a4da-62061e632804)
se educate me?  If I could get some help with this issue, I'd appreciate it.

**Comment by ThyWoof** [comment]
It became a passive power. If not working on your hero please Respec.

**Comment by ITCronin** [comment]
thank you
