### ISSUE TITLE
Widen Spell increases AoE size inconsistently

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3480]
I've come across an odd issue.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/0ddff7b5-099d-4253-9dac-1dbe8b803cec)

Here is a size comparison of "Burst of Radiance" (which is always centered on the caster). Instead of expanding 5 feet in every direction, it expands 5 feet only to the north and east.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/b84d391a-256e-450f-b906-1ca51042760a)

Here is a size comparison of "Earth Tremor". It expands 5 feet in all directions.

I suspect this happens because "Burst of Radiance" is a cube AoE and "Earth Tremor" is a cylinder. If it's possible to alter the code so that cube AoEs are widened by 10 feet instead of only 5 feet, I think that should fix this.

**Comment by ThyWoof** [comment]
Sure, can you give a hand and test cone and sphere as well?

**Comment by miridistress** [comment]
Cone and sphere work as expected.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/c5135300-0aac-48ab-885d-cecff4749d5d)

Sphere expands 5ft in every direction

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/fe11bc18-aace-4709-adee-cc33635f0332)

Cone becomes 5ft longer

**Comment by ThyWoof** [comment]
Great. So only cube is the exception. Easy fix.

**Comment by miridistress** [comment]
Thanks!
