### ISSUE TITLE
Action surge giving different effects

### ISSUE THREAD

**Issue by zeinterrupter** [SolastaMods/SolastaUnfinishedBusiness#3482]
On my fighter sometimes the action surge will give him 3 extra attacks and other times it gives him only 1 extra attack and that's it, no shove or any other type of action either.

[save file.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11713736/bug.zip)

**Comment by ThyWoof** [comment]
This is a know limitation we currently have. If you get granted an extra attack from any caster feature that does that or momentum this will happen. Won't be fixed.

**Comment by onlygamesandlife** [comment]
so we can use action surge before, and use attacks from the action surge action to trigger momentum etc., and those will properly give the attack (seemed to be a problem fixed earlier in the changelog), but we can't get the action surge attacks after triggering momentum etc.? Just to be sure when I should be using action surge or not, ty.
