### ISSUE TITLE
Arcane Warrior no Arcane Weapon

### ISSUE THREAD

**Issue by Ezeael** [SolastaMods/SolastaUnfinishedBusiness#3486]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135539756/e8a47d9f-add7-4982-8e4f-7c0c23555dd0)

**Comment by ThyWoof** [comment]
Respec.

**Comment by Ezeael** [comment]
Did not help.

**Comment by ThyWoof** [comment]
It became a passive power… check you main attack status
