### ISSUE TITLE
Movement issue

### ISSUE THREAD

**Issue by Quazimofo1** [SolastaMods/SolastaUnfinishedBusiness#3489]
Hello All,

I'm running into an issue with the latest version of UB. 

The issue is that when I click a point for the character/characterss to move they move a cell 2 spaces away from where I've clicked, this makes it not able to interact with tunnels to crawl through or click on loot. Below are two screenshots of the character before movement and after I click on a place to move

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/126178757/c65a83ca-2fca-4477-b5f1-7d6d77b79c27)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/126178757/51dc0925-3ce1-4502-a3b5-d4a6e03d8f5c)

closing solasta and re-launching it and disabling the mod and starting a new adventure using pre-gen characters/non UB made characters seems to resolve this issue but as soon as I enable the mod I cannot load any other saved games or save the currently playing game

this all started after uninstalling UB and reinstalling as Solasta was refusing to play due to mods causing issues. 

I've uninstalled and reinstalled Solasta, and then installed UB using Unity Mod Manager as shown on this page and the issue remains.

I believe this might be something on my end (or I'm just doing something wrong) as I have not found any other posts online for this exact issue. If this is a simple me issue I do apologize. 

[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11715327/Solasta.zip)

I've sipped up the solasta folder located at C:\Users*YOUR_USER_NAME\AppData\LocalLow\Tactical Adventures\Solasta

let me know if there is anything else I can provide

_Originally posted by @Quazimofo1 in https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/3488_

**Comment by ThyWoof** [comment]
Are you using any custom formation? If so make sure you always have a hero on line 1, column 3 on custom formation panel.

**Comment by Quazimofo1** [comment]
I did hit reset on formations under interface game UI and the issue remained I've just now clicked the 3rd column row 1 and have it highlighted as red

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/126178757/e2a5b57c-0148-4c86-8018-5b62609160f0)

and this seemed to fix it. Thank you so much! It seems it was me just being a little dumb
