### ISSUE TITLE
Multiplayer Desync on Journal update

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3492]
Seems that we get a red mod instability warning every time the journal updates in our multiplayer game. Could also have something to do with the campaign we are playing (Morrow's Deep), but I doubt it.

I will try and catch a save next time we hand in a quest, consider this a heads up

**Comment by ThyWoof** [comment]
All I need are log files from all players as soon as it happens. Everyone must get off game and grab latest player.log.

**Comment by ThyWoof** [comment]
Any updates on fetching the files I need?

**Comment by MartinBrandstrup** [comment]
We haven't had time to do a session yet and we will need to do a quest with a handin so probably gonna be a minute sorry :(

**Comment by MartinBrandstrup** [comment]
I hope this is the correct log file and that it contains what you need
Also can't exclude the possibility that it contains mod instability from other sources. We had a few today. Possibly connected to the new Symbol spell.

Player 1:
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11746590/Player.log)

Player 2:
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11746613/Player.log)

**Comment by MartinBrandstrup** [comment]
A small correction also: it appears to give instability warnings not only on journal updates but also during and at end of conversations without journal entries

**Comment by ThyWoof** [comment]
Please share these with TA. It looks like this particular campaign has some issues on dialogues. Not coming from the mod.
