### ISSUE TITLE
inventor issue with bag of holding ability.

### ISSUE THREAD

**Issue by knotu187** [SolastaMods/SolastaUnfinishedBusiness#3496]
one of the players in my multiplayer match is having a issue where every time we reload the game (due to desync) it puts a random item in the slot where the bag of holding was and it has to be redone each time is this normal? or a bug? i  will attach screen shots when i can get some from the player its happening to.

**Comment by ThyWoof** [comment]
I don’t believe this is caused by the mod. You should report to TA as we don’t touch inventory at all in MP.
