### ISSUE TITLE
Warcaster + Marshal not procing with Sorc metamagic on

### ISSUE THREAD

**Issue by Kyzane** [SolastaMods/SolastaUnfinishedBusiness#3497]
Warcaster is not procing cantrip attacks for opportunity attacks with a Marshal fighter in party on a sorc with metamagic. also when it does proc it requires a ranged weapon equipped. seems to be hit or miss on when it does work but almost always involves toggling metatmagic off to get it to work at all

Playing the workshop campaign Blackrock
Unfinished Business version 1.5.52.3
Solasta version 1.5.52

[Warcaster+Marsh.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11716505/Warcaster%2BMarsh.zip)

**Comment by EnderWiggin** [comment]
Seems that if character can't hit attacked enemy with their current enemy, they won't be offered reaction, and thus won't be able to use warcaster reaction. Will look if possible to fix.

**Comment by EnderWiggin** [comment]
I was wrong - there's already check for cantrips only for Warcasters, but for some reason sometimes all cantrips report that they can't hit.

**Comment by EnderWiggin** [comment]
Oh, figured it out - if enemy has any cover from the caster they won't be eligible to use cantrip, will fix

**Comment by Kyzane** [comment]
awesome thanks for all you do and I'll keep submitting bugs when I see them
