### ISSUE TITLE
Tactician Strategy: Overcome doesnt work after the first time

### ISSUE THREAD

**Issue by radium989** [SolastaMods/SolastaUnfinishedBusiness#3501]
I killed several enemies over the course of 3 rounds with my Tactician. The only time Strategy: Overcome procced and gave me back a gambit dice was the first time. Later rounds where the tactician dropped an enemy did not yield any dice.

Edited to add that I was down to only 2 out of 5 dice so it wasn't because I was at my limit.

**Comment by EnderWiggin** [comment]
please attach save file where this can be reproduced

**Comment by radium989** [comment]
[QuickSave_5.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11725270/QuickSave_5.zip)


You'll need to subscribe to this community map i use for testing character builds: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2898343661

**Comment by radium989** [comment]
Thank you!
