### ISSUE TITLE
Ritual Spell casting unavailable 

### ISSUE THREAD

**Issue by seameth** [SolastaMods/SolastaUnfinishedBusiness#3508]
This is a continuing problem for me. 
Doesn't seem to matter which race I choose, when I choose a Wizard, Ritual Casting is unavailable to me. 
I have respec'd and created brand new characters in different campaigns. Doesn't seem to matter which race I choose. I have ritual casting for my Cleric?

Not sure if this is a problem with the base Game or UB.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/9d72a74a-becb-46a6-aa2d-3b518e340d1b)

[No Ritual Casting Wiz.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11725615/No.Ritual.Casting.Wiz.zip)

**Comment by ThyWoof** [comment]
This is a base game problem AFAIK. TA will release another patch this week where I expect this to be fixed.

**Comment by ThyWoof** [comment]
closing this as indeed many non mod players report the same. Please reopen if after next game patch you still face it. I believe TA will release it tomorrow or Friday at most.
