### ISSUE TITLE
Divine Sorcerer's Sacred Flame unaffected by Potent Spellcasting feat

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3515]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/954bf1bf-238b-4394-855e-cfbeab38c09b)

Divine Sorcerer's Sacred Flame doesn't get the damage boost from the Potent Spellcasting (Sorcerer) feat.

The other Sorcerer cantrips on Spider's spell list function correctly, even ones from the expanded spell list, such as Burst of Radiance. This is reflected both on the tooltip and in the damage dealt by the cantrip in-game.

I have not tested cantrips that the character doesn't have access to. I do not know of an easy way of editing a character's spells so things like this can be more easily tested (that would be a nice feature to add, though!)

[bug report.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11738723/bug.report.zip)

Here are my saves.

**Comment by ThyWoof** [comment]
Indeed logic isn’t taking auto prep spells into consideration. To be fixed once I’m back to game computer.
