### ISSUE TITLE
Haste interaction with Spell Fighting subclass feature

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3519]
Wonky interaction with Spell Fighting feature (free spell after a kill) from Arcane Fighter.
After using haste on yourself and getting a kill the game will interpret your haste bonus action as a bonus spell and it will allow you to use your extra spell (or a second/third cantrip) instead of a normal haste action. This also seems to be the case if drinking a potion of speed.
I cannot exclude that the usage of cantrips is guilty as well.
How to reproduce: As can be seen in the save file Jade has just used a regular melee attack to kill a low health opponent and has thus triggered Spell Fighting.
She is currently on her 2nd attack of her first main action. ->
Use your cantrip attack to finish first main action. ->
This should now be the Spell Fighting Action and another spell or Cantrip is available. Using a spell here skips the haste action but using another cantrip leads to ->
This is now the Haste action I presume, which the game thinks is another spell casting action. A second spell or third Cantrip is available but none of the other regular haste actions are.

[Haste Spell.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11747443/Haste.Spell.zip)

An unrelated bug testable with this same save, but a lot more irregular:
Sometimes Mobility does not appear to trigger. It could either be because of flight or because of Rope it Up Fighting Style. To replicate would probably need to spend a few turns and/or reloads to find a scenario where it does not trigger properly.

**Comment by EnderWiggin** [comment]
most likely last action is actually from Spell Fighting - we made a patch some time ago to sort all 'triggered after kill' actions to the end of the action list, because otherwise they broke interactions with Action Surge.

**Comment by MartinBrandstrup** [comment]
Well fair, but regardless this interaction allows 3 cantrips per turn which seems like a bug

**Comment by EnderWiggin** [comment]
Currently released version of UB has change that makes Haste action able to cast spells, so if only problem is that you can cast extra cantrip - then it is known and will probably be addressed in one way or another in the next release

**Comment by MartinBrandstrup** [comment]
Update: It seems that this change is the issue and it might have nothing to do with the Arcane Fighter subclass.
With haste allowing spells it seems that all casters regardless of subclass can do multiple cantrips after a haste now.

**Comment by ThyWoof** [comment]
Closing this one as we're already working on a fix for all these extra attacks interactions. Should be on next release (not before Friday).
