### ISSUE TITLE
Multiplayer POI unable to level to 10

### ISSUE THREAD

**Issue by raiefmastah** [SolastaMods/SolastaUnfinishedBusiness#3520]
multiplayer 4 players , i am hosting POI shared unfinished business mod , none of us can get past level up screen it says mod unstable and freezes when we each get to level 2 no save file because game couldn't be started , settings on mod screen shot
all classes subclasses active and spells under suggested
![Uploading 352818650_322
![Uploading 3528
![Uploading 352853963_213
![Uploading 352804
![Uploading 348387419_1288427468451916_3220081769204600764_n.jpg…]()
![Uploading 348386906_645365407120063_4280772563717504383_n.jpg…]()

266_1133846681340106_2750268920956375228_n.jpg…]()
222478291259_5280147323133916860_n.jpg…]()
59971_249978497727334_3682440606069944358_n.jpg…]()
999800401
![352837907_780931646860237_7069068134064577962_n](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135657863/3ed1655e-b7a7-48cb-bf54-9ccfb152c807)
242_1724965797292927316_n.jpg…]()

![352828529_244778754975704_617871609256457643_n](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135657863/27bcab3c-d157-4dfe-a973-faffe6a7caad)

**Comment by ThyWoof** [comment]
We need your player log otherwise nothing we can do.

**Comment by raiefmastah** [comment]
how do i find that?

**Comment by raiefmastah** [comment]
this?
Mono path[0] = 'G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Managed'
Mono config path = 'G:/Steam/steamapps/common/Slasta_COTM/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.37f1 (019e31cfdb15)
[Subsystems] Discovering subsystems at path G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3060 (ID=0x2504)
    Vendor:   
    VRAM:     12129 MB
    Driver:   31.0.15.3168
Begin MonoManager ReloadAssembly


[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.25.5.0.
[Manager] OS: Microsoft Windows NT 10.0.19045.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] Mods path: G:\Steam\steamapps\common\Slasta_COTM\Mods.
Fallback handler could not load library G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-000001B9587DA110.dll
Fallback handler could not load library G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-000001B910963980.dll
[Manager] Injection successful.
- Completed reload, in  0.622 seconds
<RI> Initializing input.

New input system (experimental) initialized
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.861800 ms
WwiseUnity: Wwise(R) SDK Version 2021.1.4 Build 7707. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Setting Plugin DLL path to: G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data\Plugins\x86_64 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Sound engine initialized successfully. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 11530.
Total: 17.029200 ms (FindLiveObjects: 0.455700 ms CreateObjectMapping: 0.210900 ms MarkObjects: 16.328200 ms  DeleteObjects: 0.033700 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 11530.
Total: 17.959600 ms (FindLiveObjects: 0.589700 ms CreateObjectMapping: 0.228700 ms MarkObjects: 17.130300 ms  DeleteObjects: 0.010500 ms)

[Manager] Parsing mods.
[Manager] Reading file 'G:\Steam\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.5.52.5'. Loading.
[SolastaUnfinishedBusiness] Language es detected.
[SolastaUnfinishedBusiness] Language it detected.
[SolastaUnfinishedBusiness] Language ja detected.
[SolastaUnfinishedBusiness] Language ko detected.
[SolastaUnfinishedBusiness] Language zh-CN-Unofficial detected.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Light SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Bold SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Light SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Bold SDF loaded.
[SolastaUnfinishedBusiness] Active.
[SolastaUnfinishedBusiness] Loading time 4.33 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.


[Manager] Spawning.
[Manager] Checking updates.
[SolastaUnfinishedBusiness] 3629 en translation terms loaded of 3629 provided.
[SolastaUnfinishedBusiness] 0 en translation fixes loaded.
Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Screen/&InvocationPoolSpellMasteryHeader, in object Title in parent ProficiencySectionHeader 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Screen/&InvocationPoolSpellMasteryHeader, in object Label in parent ProficiencyToggle (PoolElement) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[SolastaUnfinishedBusiness] [Error] additional names cannot load: .
Missing translation for key=Environment/&ArcticTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&CoastTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&DesertTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&ForestTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&GrasslandTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&MountainTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&LightSourceFireElementalTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&LightSourceFireElementalTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&AdditionalDamageBrandingSmiteTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Increase one of your mental attributes by 1, to a maximum of 20.
You gain the ability to cast the shield of faith, protect vs evil & good, and protection from poison spells once per long rest and you can cast these spells with your spell slots. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Equipment/&Chainshirt+1_Description 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Equipment/&DLC3_Chainshirt+2_Description 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[SolastaUnfinishedBusiness] enabled in 00:00:25.5090799.
Unexpected timestamp values detected. This can occur in H.264 videos not encoded with the baseline profile. Timestamps will be skewed to correct the playback for G:/Steam/steamapps/common/Slasta_COTM/Solasta_Data/StreamingAssets/BackgroundMovie.MP4 
(Filename:  Line: 0)

Joystick connected ("Controller (XBOX 360 For Windows)"). 
(Filename:  Line: 1456)

**Comment by ThyWoof** [comment]
Yes but you need to reproduce the issue, exit game and share after that. This file always get overwritten whenever you start a game. Also please attach the file don’t paste full contents as hard to read.

**Comment by raiefmastah** [comment]
ok i dont have all my players currently they're at work will it work with 2 players? and how do i get the file

**Comment by ThyWoof** [comment]
Check the wiki page please on how to properly report bugs

**Comment by raiefmastah** [comment]
reproducing currently 
multiplayer poi 
cataclysm difficulty 
modded half dark elf rogue , modded inventor shadow gnome,modded kobold monk , devil tongue warlock mephis ancess

hit start game 
go to level up , hit next , crash due to mod instability 
[](url)
[solasta crash.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11748676/solasta.crash.txt)
![352784510_774078870996197_7144862028013697290_n](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135657863/c5e450cd-34b1-406e-a73b-4b4fe89a9632)

**Comment by ThyWoof** [comment]
Rest on that save before trying to import.

**Comment by raiefmastah** [comment]
![Uploading image.png…]()
no option to rest its requiring a level up

**Comment by ThyWoof** [comment]
Get me the log please.

**Comment by raiefmastah** [comment]
This is the log
[solasta crash.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11748966/solasta.crash.txt)

**Comment by ThyWoof** [comment]
Do you have any save I can use to debug? I truly believe this can be fixed with a RESPEC but wanna be sure.

**Comment by raiefmastah** [comment]
i got it to work i made all other players disconnect while doing level up process and intro , then re connect after at camp and everything is working now. but the intro sequence doesnt while in multiplayer due to crash on level up

**Comment by raiefmastah** [comment]
[new game.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11752144/new.game.zip)
