### ISSUE TITLE
Weapon Master Weapon Spec

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3521]
My guess is that the feature does not look at class level as it is supposed to but at character level. My level 12 Barb/3 Fighter has +2 in the feature

[Weapon Spec not Class Level.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11749661/Weapon.Spec.not.Class.Level.zip)

**Comment by EnderWiggin** [comment]
Judging by code that seems intended, even though weird. @ThyWoof , please confirm if this is intended. If so we need to clarify description so there's no doubt in how it works.

**Comment by ThyWoof** [comment]
Will check. I believe it should be char level for consistency.

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/0652d0695341a423102b5d793de9e27451329d89/SolastaUnfinishedBusiness/Subclasses/MartialWeaponMaster.cs#L284 should use GetClassLevel. @EnderWiggin , can you add this fix to open tweaks PR?
