### ISSUE TITLE
Cleric subclass Smith not getting smith tools proficiency

### ISSUE THREAD

**Issue by chlorosadamas** [SolastaMods/SolastaUnfinishedBusiness#3523]
Created a Cleric Smith and can't use smith tools.  The character tab shows the "Bonus Proficiencies" feat that gives proficiency in smith tools and heavy armor, but only the heavy armor shows up on the proficiencies tab.

Solasta: 1.5.52
UB: 1.5.52.5

**Comment by ThyWoof** [comment]
fixed in dev.
