### ISSUE TITLE
Error item use

### ISSUE THREAD

**Issue by TomasWarchol** [SolastaMods/SolastaUnfinishedBusiness#3525]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/112191629/88231292-a613-421f-8120-fa09f37b511f)

The error occurs when clicking on the use of an item.
I took all the items off the team and only the crown was left.

I did another test and put any item on a character without a crown. The error occurs every time "use item" is used, no matter what item is equipped.

Items cannot be used. The selection window does not appear.

Game 1.5.74
UB 1.5.52.5

**Comment by TomasWarchol** [comment]
Player log:

`Mono path[0] = 'E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data/Managed'
Mono config path = 'E:/SteamLibrary/steamapps/common/Slasta_COTM/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.37f1 (019e31cfdb15)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
    Vendor:   
    VRAM:     6043 MB
    Driver:   31.0.15.3598
Begin MonoManager ReloadAssembly


[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.25.5.0.
[Manager] OS: Microsoft Windows NT 10.0.19045.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] Mods path: E:\SteamLibrary\steamapps\common\Slasta_COTM\Mods.
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-00000282DF6EE090.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-00000282DC40A040.dll
[Manager] Injection successful.
- Completed reload, in  0.691 seconds
<RI> Initializing input.

New input system (experimental) initialized
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.850800 ms
WwiseUnity: Wwise(R) SDK Version 2021.1.4 Build 7707. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Setting Plugin DLL path to: E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data\Plugins\x86_64 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Sound engine initialized successfully. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 18.494300 ms (FindLiveObjects: 0.424900 ms CreateObjectMapping: 0.150800 ms MarkObjects: 17.879300 ms  DeleteObjects: 0.038900 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 18.480300 ms (FindLiveObjects: 0.652000 ms CreateObjectMapping: 0.150800 ms MarkObjects: 17.663000 ms  DeleteObjects: 0.014200 ms)

[Manager] Parsing mods.
[Manager] Reading file 'E:\SteamLibrary\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.5.52.5'. Loading.
[SolastaUnfinishedBusiness] Language es detected.
[SolastaUnfinishedBusiness] Language it detected.
[SolastaUnfinishedBusiness] Language ko detected.
[SolastaUnfinishedBusiness] [Error] Loading the font bundle E:\SteamLibrary\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\UnofficialTranslations/JapaneseHanSans.unity3d.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Light SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Bold SDF loaded.
[SolastaUnfinishedBusiness] Active.
[SolastaUnfinishedBusiness] Loading time 3,85 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.


[Manager] Spawning.
[Manager] Checking updates.
[SolastaUnfinishedBusiness] 3629 en translation terms loaded of 3629 provided.
[SolastaUnfinishedBusiness] 0 en translation fixes loaded.
Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Prop/&PrisonFenceDestroyedTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Screen/&InvocationPoolSpellMasteryHeader, in object Title in parent ProficiencySectionHeader 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Screen/&InvocationPoolSpellMasteryHeader, in object Label in parent ProficiencyToggle (PoolElement) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[SolastaUnfinishedBusiness] [Error] additional names cannot load: .
Missing translation for key=Environment/&ArcticTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&CoastTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&DesertTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&ForestTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&GrasslandTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Environment/&MountainTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&LightSourceFireElementalTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&LightSourceFireElementalTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&AdditionalDamageBrandingSmiteTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Localization requested on an empty string 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&ConditionAffinityCircleLandLandsStrideTitle 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Increase one of your mental attributes by 1, to a maximum of 20.
You gain the ability to cast the shield of faith, protect vs evil & good, and protection from poison spells once per long rest and you can cast these spells with your spell slots. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Equipment/&Chainshirt+1_Description 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Equipment/&DLC3_Chainshirt+2_Description 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[SolastaUnfinishedBusiness] enabled in 00:00:26.7043831.
Unexpected timestamp values detected. This can occur in H.264 videos not encoded with the baseline profile. Timestamps will be skewed to correct the playback for E:/SteamLibrary/steamapps/common/Slasta_COTM/Solasta_Data/StreamingAssets/BackgroundMovie.MP4 
(Filename:  Line: 0)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 3 Unused Serialized files (Serialized files now loaded: 18)

Unloading 82785 unused Assets to reduce memory usage. Loaded Objects now: 331075.
Total: 1042.160700 ms (FindLiveObjects: 22.037700 ms CreateObjectMapping: 27.994300 ms MarkObjects: 964.993700 ms  DeleteObjects: 27.134700 ms)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 134)

Unloading 1002 unused Assets to reduce memory usage. Loaded Objects now: 382415.
Total: 1076.548800 ms (FindLiveObjects: 22.572500 ms CreateObjectMapping: 16.110200 ms MarkObjects: 1036.704100 ms  DeleteObjects: 1.161700 ms)

Retrieving current value of attribute <ProficiencyBonus> while it is not up to date 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Retrieving current value of attribute <ProficiencyBonus> while it is not up to date 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at SolastaUnfinishedBusiness.Patches.UsableDeviceFunctionBoxPatcher+Bind_Patch.UpdateUsabilityForPoisoner (UsableDeviceFunctionBox box, RulesetItemDevice usableDevice, RulesetDeviceFunction rulesetDeviceFunction) [0x00034] in <c00b55dab25b431e8d5368017e31c8b1>:0 
  at SolastaUnfinishedBusiness.Patches.UsableDeviceFunctionBoxPatcher+Bind_Patch.Postfix (UsableDeviceFunctionBox __instance, RulesetItemDevice usableDevice, RulesetDeviceFunction usableDeviceFunction) [0x00008] in <c00b55dab25b431e8d5368017e31c8b1>:0 
  at (wrapper dynamic-method) UsableDeviceFunctionBox.UsableDeviceFunctionBox.Bind_Patch1(UsableDeviceFunctionBox,GuiCharacter,RulesetItemDevice,RulesetDeviceFunction,DeviceOverchargePanel,UsableDeviceFunctionBox/DeviceFunctionEngagedHandler,ActionDefinitions/ActionType,bool,UnityEngine.RectTransform)
  at DeviceFunctionSelectionLine.Bind (GuiCharacter guiCharacter, RulesetItemDevice usableDevice, UsableDeviceFunctionBox+DeviceFunctionEngagedHandler deviceFunctionEngaged, DeviceOverchargePanel deviceOverchargePanel) [0x00167] in <c6e8f1cc618344fc8a7c62958aa1ec8a>:0 
  at DeviceSelectionPanel.Bind (GuiCharacter guiCharacter, DeviceSelectionPanel+DeviceFunctionCancelledHandler deviceFunctionCancelled, UsableDeviceFunctionBox+DeviceFunctionEngagedHandler deviceFunctionEngaged) [0x0011a] in <c6e8f1cc618344fc8a7c62958aa1ec8a>:0 
  at CharacterActionPanel.SelectDeviceFunction () [0x0006c] in <c6e8f1cc618344fc8a7c62958aa1ec8a>:0 
  at (wrapper dynamic-method) CharacterActionPanel.CharacterActionPanel.OnActivateAction_Patch0(CharacterActionPanel,ActionDefinitions/Id,GuiCharacterAction)
  at CharacterActionPanel.OnActivateAction (CharacterActionItemForm actionItemForm) [0x0002a] in <c6e8f1cc618344fc8a7c62958aa1ec8a>:0 
  at CharacterActionItemForm.OnActivateCb () [0x0001d] in <c6e8f1cc618344fc8a7c62958aa1ec8a>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00010] in <85d1d3e7744a4a47b5f51883bf40bba2>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00022] in <85d1d3e7744a4a47b5f51883bf40bba2>:0 
  at UnityEngine.UI.Button.Press () [0x0001c] in <9f30921337344626969c2730b25da744>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00009] in <9f30921337344626969c2730b25da744>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <9f30921337344626969c2730b25da744>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00063] in <9f30921337344626969c2730b25da744>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent()
UnityEngine.EventSystems.StandaloneInputModule:Process()
InputPointerModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: <c00b55dab25b431e8d5368017e31c8b1> Line: 0)

`

**Comment by ThyWoof** [comment]
fixed.
