### ISSUE TITLE
Loot Drops

### ISSUE THREAD

**Issue by Fatadder** [SolastaMods/SolastaUnfinishedBusiness#3527]
NB this may not be a mod issue!

For a while I owned only Solasta and completed the campaign with a vanilla party.  Got Unfinished Business played through COTM campaign again with custom characters and had way more fun.  A while ago I acquired Lost Valley and everything else except the latest Palace Of Ice, I didn't want to start again on vanilla so I created some characters via UB and got going.  It took a while but I began to notice that I couldn't pick up loot drops from enemies pretty frequently.

I switched off the mod (I think) and tried with a vanilla crew, you have to get to the first fight with the bear in the tutorial, nope can't pick up the loot drop from the bear.  I play through Steam and there was an update today for Solasta, but that hasn't fixed it.

I'm posting about this here because I *think* there are some committed players here who may have some insight.   Sorry for the static if I'm posting in the wrong place.

**Comment by ThyWoof** [comment]
Open mod UI, Interface / Game UI, formations. Ensure there is always a hero on line 1, column 3. Nothing on line 1, columns 1 and 2. This will fix.
