### ISSUE TITLE
Inventor's Alchemy Bombs not working

### ISSUE THREAD

**Issue by emymonteiro** [SolastaMods/SolastaUnfinishedBusiness#3528]
**The versions of Solasta and this mod.**
Game 1.5.74
Mod 1.5.52.5

**A list of other mods you have installed [you shouldn't have any].**
- Ruins of Ilthismar ( It's a campaing mod from steam workshop )

**A short description of the bug.**
Well, apparently the game has updated about ( today / yesterday ) , and the game stopped to reconize the alchemy bombs from inventor's and it can't be used in combat anymore.

**A step-by-step procedure to reproduce it.**
Start a game with Inventor ( granadier ) which have level to use the bombs and try to use it.

**The save, character and log files.** 
[bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11761913/bug.zip)

The specific character is "Gibber" , an Kobold Inventor, but I've sended all characters.

Here's a link with a video showing the problem:
[Video](https://youtu.be/0Rs1YocO2c8)

**Comment by VessValyren** [comment]
Can confirm also not working for me, can't play my current play through.

**Comment by VessValyren** [comment]
The update the was just released fixed it.

**Comment by emymonteiro** [comment]
> The update the was just released fixed it.

Thanks it works, I'm closing the issue
