### ISSUE TITLE
Way of the Dragon Monk Subclass - Reactive Hide Not Working

### ISSUE THREAD

**Issue by VessValyren** [SolastaMods/SolastaUnfinishedBusiness#3529]
The versions of Solasta and this mod.
Game 1.5.74
Mod 1.5.52.5

A list of other mods you have installed [you shouldn't have any].

 None

A short description of the bug.
The Reactive Hide Feature for the Way of the Dragon Monk Subclass is not triggering on reactions.

**Comment by VessValyren** [comment]
Tested it on the most recent update:
Game 1.5.74
Mod 1.5.74.0

Still not working on reactions.

**Comment by ThyWoof** [comment]
Share save please.

**Comment by VessValyren** [comment]
I don't have a save for it, was testing out the sub-classes in a test campaign.  Do you want me to make a lvl 10 party in Palace and send that?

**Comment by VessValyren** [comment]
[Solasta Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11763312/Solasta.Save.zip)

Here I made a quick PoI Campaign with the monk and did the first combat and it didn't trigger a reaction when he was hit in melee.  Ranged attacks still trigger the deflect arrows however.

**Comment by ThyWoof** [comment]
Thanks. I should have a fix for next release.

**Comment by ThyWoof** [comment]
I cannot test on an user location. Need the JSON file...

**Comment by ThyWoof** [comment]
Fixed locally.
