### ISSUE TITLE
Metamagic point cost higher than it should

### ISSUE THREAD

**Issue by DenisFolcher** [SolastaMods/SolastaUnfinishedBusiness#3532]
[Hello,]([url](url))
On the same game i have two characters, see the save : [001.zip]
[001.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11772408/001.zip)
1 sorcerer with 11 levels of sorcerer only (lets call it A),
and 1 sorcerer dual classed with 6 levels of sorcerer and 3 of bard (lets call it B).

when i cast a twinned haste (at with a level 3 spell slot) with A, it costs me 3 metamagic points as it should (1 per level)
when i cast a twinned haste (at with a level 3 spell slot) with B, it costs me 5 metamagic points.

Nb: i got an Idea regarding the cause: 
The other class of B us Bard of life who has a power that passively enhance the spell level of transmutation and necromancy school by 2.
Haste IS level 3 and transmutation but without any upcast benefits.
Si m'y Idea IS that despite having no benefits haste IS upcasted AT 5 therefore twinning it costs 5 metamagic points.

**Comment by ThyWoof** [comment]
As usual we cannot act without a save. Yeah, I could had created such heroes but that takes time and usually when I do I cannot reproduce.

**Comment by DenisFolcher** [comment]
Hello, i updated with a relevant save

**Comment by ThyWoof** [comment]
Thanks, will take a look

**Comment by ThyWoof** [comment]
Game code automatically use the upcast. So Haste doesn’t get it? In addition to Haste any other spell should not get auto upcast? I suck on dnd rules

**Comment by kosocku** [comment]
No, while you can use a higher-lvl spell slot to cast Haste, it does NOT benefit from upcasting, so unless it is a Bard spell (which it can't be at Bard 3) it should not be upcast using the Bard feature.

Possible fix: Only have the Bard of Life feature work on spells learned from levelling Bard?

**Comment by DenisFolcher** [comment]
simply base the metamagic cost on the initial spell slot level, not the final. Sounds fair to me, as the +2 is ought to be a bonus not an hindrance.

**Comment by ThyWoof** [comment]
This was by design to allow dead master Multiclass. Won’t change.

**Comment by DenisFolcher** [comment]
Thank you for your so Quick answer and as a long Time dnd and rpg fan,
congratulation on your awesome work!

Le sam. 17 juin 2023 à 01:42, Paulo Monteiro ***@***.***> a
écrit :
