### ISSUE TITLE
When first unlearning an Inventor infusion, then deciding to keep it, the previously selected infusion still gets unlearned

### ISSUE THREAD

**Issue by Nocull** [SolastaMods/SolastaUnfinishedBusiness#3537]
We are running a multiplayer game where one of my friends is playing an inventor. He wanted to unlearn an infusion, but then realized there was nothing he wanted to swap it out for so instead decided to ignore it (pressing change, then pressing ignore). However he still unlearned that infusion. On the next level up the same thing happened again, leaving him with 2 infusions at level 4.

**Comment by ThyWoof** [comment]
We couldn’t reproduce on a SP session. Very minor issue so won’t fix.
