### ISSUE TITLE
No recipe for shortsword +1 in vendor

### ISSUE THREAD

**Issue by Majber** [SolastaMods/SolastaUnfinishedBusiness#3538]
I dont know if its UB or vanilla foult but there is no recipe for shortsword +1 in Circe Gerardoirin vendor

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8217598/5e9672c1-a7a9-460b-bcca-06e8e6056cf8)

**Comment by ThyWoof** [comment]
It’s vanilla, we don’t have any shortsword in mod.
