### ISSUE TITLE
Divine Heart Sorcerer can summon Divine Blade but can't use it due to lack of proficiency

### ISSUE THREAD

**Issue by night44** [SolastaMods/SolastaUnfinishedBusiness#3539]
Solasta and this mod are both up to date, no other mods installed. 

The first character in this save is a Divine Blade who has cast Divine Blade (level 8 Cleric spell) in various situations. The spell works, but the weapon it summons cannot be used by this character due to lack of proficiency. 

In this save, I have already summoned it, all you have to do is look at the weapon in the first character's hand.

[Divine Blade bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11772864/Divine.Blade.bug.zip)

**Comment by night44** [comment]
Actually, I just tested it and a Cleric can't use it either. So this might be a TA issue?

**Comment by ThyWoof** [comment]
Definitely. I’ll report to TA but in case they cannot fix it I believe we can add a condition to the spell granting this temp proficiency on long swords.

**Comment by kosocku** [comment]
I'm not a coder, as we've already established, but if you're worried about how powerful the kit could become with proficiency to swords, could you classify the spell as a new weapon proficiency (Spell Swords, or Bastard Swords, or something similar) and just have the spell grant proficiency for that type of weapon instead?  Would be very hard to abuse that.

**Comment by ThyWoof** [comment]
There is one more patch in the oven from TA. Issue reported. If not fixed there please reopen after next game patch so I don’t forget.
