### ISSUE TITLE
crash when clicking multiplayer button immidiately on a fully fresh install

### ISSUE THREAD

**Issue by AmericaYea** [SolastaMods/SolastaUnfinishedBusiness#3540]
started running into the issue when half our group started crashing when updating today we all reinstalled and now half of us crash when trying to join a multiplayer session. isolated the issue to the current install of unfinished buisiness and completely deleted all settings files and redownloaded, the issue persists. Rolled back to old version then re updated from the site and no dice. unity mod manager works just fine by itself(still reinstalled it by uninstalling deleting the entire unity mm folder and redownloading and unzipping that and the unfinished buisiness zip) so that's not the cause here.

I'll be checking back tomorrow or the day after for a fix as I've tried everything I could think of including a verify and a full wipe and redownload of even my settings and the cloud please and thankyou I know it's a lot of trouble tracking down issues like this sometimes.

please find included 1 png picture of the error via print screen and paint

![errorsolasta1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/136861009/0ad46aab-e29f-454a-a50f-1ef1acb3ab5e)

**Comment by AmericaYea** [comment]
only dlc I'm missing are the ost and supporter packs, game is installed in a steam library on a G: drive a samsung ssd graphics drivers were working properly with unfinished business in the previous update and without unfinished buisiness in this update

**Comment by AmericaYea** [comment]
to clarify that error happens with all default solasta settings and all default unfinished buisiness settings

**Comment by ThyWoof** [comment]
Check your game files. Not this mod.

**Comment by AmericaYea** [comment]
> Check your game files. Not this mod.

already did that as I said a verify then a full reinstall after wiping everything including my cloud files and saves. is the error from something else? should I report this on the main solasta forum when literally everything works untill I install this mod?

**Comment by AmericaYea** [comment]
heck I even wiped the mod manager files too
