### ISSUE TITLE
Distant Hand Monk

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#3542]
### Discussed in https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/3541

<div type='discussions-op-text'>

<sup>Originally posted by **charlesewatkins** June 16, 2023</sup>
I thought bows were supposed to be treated as monk weapons for a DHM, but that's not what I'm seeing. This is on a multiclassed Raven Rogue, which seems like a good combination.</div>

**Comment by ThyWoof** [comment]
Distant hand is working without issues on my end. Got a save?

**Comment by charlesewatkins** [comment]
[DHMbug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11779189/DHMbug.zip)

Here's a save. The first character is a Raven Rogue 9/Distant Hand Monk 3. Notice her shortbow is flagged as not being a monk weapon.

**Comment by ThyWoof** [comment]
fixed in DEV but you'll need to respec after we release the fix.

**Comment by charlesewatkins** [comment]
My, that was fast. You are awesome. Can't say how much I enjoy your work.
