### ISSUE TITLE
War Dance

### ISSUE THREAD

**Issue by Xurtan** [SolastaMods/SolastaUnfinishedBusiness#3545]
Is it me, or is it simply not rolling concentration checks to keep it rolling? The die isn't showing up and it's consistently breaking every single attack, regardless.

**Comment by ThyWoof** [comment]
Subclass has been refactored. Check new descriptions.

**Comment by Xurtan** [comment]
I did see that it worked differently, but it does still say in the description that it should make a concentration check. See: https://i.imgur.com/nNI8evo.png here. Currently it doesn't do that, it just ends. See: https://i.imgur.com/213knfN.png here vs here for another case of concentration: https://i.imgur.com/c3tHk3s.png; it's just not showing up/rolling, near as I can tell. Or am I reading the description wrong entirely?
