### ISSUE TITLE
Squat Nimbleness feat bug

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3547]
Squat Nimbleness (character is a dwarf) doesn't give proficiency/epertise in Athletics/Acrobatics as the text says.

I wanted to take this feat at lv 1 (char generation; playing with the UB option to get a feat at lv 1), but got no option to pick a proficiency (Acrobatics) or take the upgrade to expertise. (I already had proficiency in Athletics).

**Comment by EnderWiggin** [comment]
@ThyWoof not sure if intended, but Squat Nimbleness adds only Athletics if you chose STR version and adds only Acrobatics if you chose DEX version. If intended then it should be worded better.

**Comment by Frobbles12** [comment]
Hm, good to know. The wording is indeed wrong then. It is also not helpfull that one doesn't see the impact of feats taken on the ability values and proficiencies immediately, but that is another topic. Thanks for pointing out the intended ruling, EnderWiggin!

**Comment by ThyWoof** [comment]
Fixed desc in DEV.
