### ISSUE TITLE
Thorny Vines is Melee Range?

### ISSUE THREAD

**Issue by CEDSS** [SolastaMods/SolastaUnfinishedBusiness#3548]
I don't think it's going to be pulling anything at this range. Should probably be 30 ft. range, or 6 in-game cells.

![Thorny Vines Melee](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/43633721/4bb2dd01-7607-4aec-a16a-02f60e24016d)

The following code is from [SolastaUnfinishedBusiness](https://github.com/SolastaMods/SolastaUnfinishedBusiness/tree/master)/[SolastaUnfinishedBusiness](https://github.com/SolastaMods/SolastaUnfinishedBusiness/tree/master/SolastaUnfinishedBusiness)/[Spells](https://github.com/SolastaMods/SolastaUnfinishedBusiness/tree/master/SolastaUnfinishedBusiness/Spells)
/[SpellBuildersCantrips.cs](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/master/SolastaUnfinishedBusiness/Spell/SpellBuildersCantrips.cs)

Line 705 of the file is where the problem seems to be, gotten from the master branch at the time of the making of this issue thread, version 1.5.74.1.

    internal static SpellDefinition BuildThornyVines()
    {
        var spriteReference = Sprites.GetSprite("ThornyVines", Resources.ThornyVines, 128);

        return SpellDefinitionBuilder
            .Create("ThornyVines")
            .SetGuiPresentation(Category.Spell, spriteReference)
            .SetSpellLevel(0)
            .SetSchoolOfMagic(SchoolOfMagicDefinitions.SchoolTransmutation)
            .SetVocalSpellSameType(VocalSpellSemeType.Attack)
            .SetCastingTime(ActivationTime.Action)
            .SetEffectDescription(EffectDescriptionBuilder
                .Create()
                .SetTargetingData(Side.Enemy, RangeType.MeleeHit, 6, TargetType.IndividualsUnique) //Is it supposed to be a melee hit?
                .SetParticleEffectParameters(VenomousSpike)
                .SetEffectAdvancement(EffectIncrementMethod.CasterLevelTable, 5,
                    additionalDicePerIncrement: 1)
                .SetEffectForms(
                    EffectFormBuilder
                        .Create()
                        .SetDamageForm(DamageTypePiercing, 1, DieType.D6)
                        .Build(),
                    EffectFormBuilder
                        .Create()
                        .SetMotionForm(MotionForm.MotionType.DragToOrigin, 2)
                        .Build())
                .Build())
            .SetCustomSubFeatures(new ModifyMagicEffectThornyVines())
            .AddToDB();
    }

**Comment by ThyWoof** [comment]
Yes to avoid DIS on melee but you can still attack at range.
