### ISSUE TITLE
Crit Rule Issues

### ISSUE THREAD

**Issue by adrian111ortiz** [SolastaMods/SolastaUnfinishedBusiness#3549]
Problems occurred in multiplayer, tested in the same world on singleplayer problems persist.

Crit rule 3 doesn't properly multiply damage modifiers (Z element in the given formula), on a crit instead only damage dice (XdY) are doubled.

Crit rules aren't followed by enemies or npc allies when set regardless of 1 or 3. (2 not tested)

**Comment by ThyWoof** [comment]
Please attach save and screenshots stating the issue.

**Comment by adrian111ortiz** [comment]
[Save File](https://drive.google.com/file/d/1BZSt4o2XlY5jLlFzcYbMkXCMdZwHzx2X/view?usp=sharing)

Crit rule 3 was set for Ally and Enemy Creatures

Enemy Crit - Didn't double rolled damage or modifier.
![EnemyCrit2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17015741/08f294d2-ace8-4ae4-8cf4-a7f1a9e3e331)

NPC Crit - Didn't double rolled damage or modifier.
![NPCCrit](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17015741/725a8df8-ddc8-4120-a994-9eb3f80507f4)

PlayerCrit - Doubles rolled damage but not modifier.
![PlayerCrit](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17015741/954d4498-3410-4b90-b7b5-749d5e21fc94)
