### ISSUE TITLE
Controller does not work properly when multiclassing

### ISSUE THREAD

**Issue by distraughtklownz** [SolastaMods/SolastaUnfinishedBusiness#3550]
When multiclassing and attempting to choose different spells/actions with the controller UI, the option to move between options does not move normally. It appears to jump to hidden menu options and will sometimes highlight an visible option in a way that it's toolbar appears, but it is not usable. This behavior does not happen until the character has multiclassed into at least 1 other profession and a subset of those each professions' skills appear within the actions/spells menus during combat. This behavior does not appear at all with the mouse and keyboard UI.

**Comment by ThyWoof** [comment]
Controllers aren't supported currently. Will add support in the long term. Revert back to keyboard and mouse.
