### ISSUE TITLE
Weapon master subclass issue

### ISSUE THREAD

**Issue by lovewinseverytime** [SolastaMods/SolastaUnfinishedBusiness#3557]
Focused Strikes for Weapon Master Fighters cannot be activated.

**Comment by ThyWoof** [comment]
Please check how to properly report issues. A save is mandatory and screenshots always nice to have.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/0aff3f26-8a6b-4f1c-938f-9f2e80a7e072)
