### ISSUE TITLE
Merciless fighting style - fear effect wearing off immediately after the pc who caused it ends their turn instead of after the npc's next turn

### ISSUE THREAD

**Issue by Kyzane** [SolastaMods/SolastaUnfinishedBusiness#3558]
Good afternoon,

the fear effect from merciless is wearing off on the end of turn when the character who caused it ends their turn instead of after the npc's who got feared''s turn comes up.

Merciless is on the barbarian fighter as their fighter fighting style choice.

Workshop campaign: Diabloasta
version of game 1.5.74
UB version 1.5.74.2
[Merciless fighting style issue.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11780619/Merciless.fighting.style.issue.zip)

**Comment by ThyWoof** [comment]
fixed in dev.
