### ISSUE TITLE
Thorny vines is suddenly melee range

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#3559]
[QuickSave_4.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11781087/QuickSave_4.zip)
![grafik](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/131542731/23a5f69a-7260-4a7a-a27f-4312efcf9c97)
It used to be a ranged spell attack.

**Comment by CEDSS** [comment]
To be fair, the description of this spell should be changed from "Make a ranged spell attack against the target." to a more accurate "Make a melee spell attack against a target up to 30 feet away from you." to avoid further confusion.

It should work as a melee spell attack with a range of 30 feet, does it not? The melee attack roll is to avoid disadvantage when you have enemies at melee range.

Funnily enough, making a melee spell attack at up to 30 feet range is mechanically identical to the original [Thorn Whip](http://dnd5e.wikidot.com/spell:thorn-whip) 

I made a separate issue on this spell recently, here: #3548 as I also thought the spell had melee (5 ft.) range.

**Comment by EnderWiggin** [comment]
It actually works properly, just shows range as melee without range. Going to fix tooltip to show range for melee and touch spells/powers if their range is longer than 1 tile.

**Comment by ZheToralf** [comment]
> It actually works properly, just shows range as melee without range. Going to fix tooltip to show range for melee and touch spells/powers if their range is longer than 1 tile.

That would be helpful, thanks. I was probably a bit to far away for it, but since the description did not include any range, I didn't know that.

**Comment by ThyWoof** [comment]
fixed in dev.
