### ISSUE TITLE
Paladin Aura of Protection: Cloak of Dandy not adding up

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3570]
As the title says: Not sure whether this is a bug in the main game or related to UB at all, but what happened to my Pally (lv 6, 16 CHA) when I slapped on (and attuned) the Cloak of the Dandy (==>CHA=19) was that the Aura of Protection bonus stayed at +3. In my opinion it should have gone up to +4, shouldn't it? Leaving the character screen, saving and loading didn't change this, so it doesn't seem to be an update problem with the user interface.

I am playing a mod (Temple of Evil) right now, should this matter.

**Comment by ThyWoof** [comment]
Please report to TA. Not this mod.
