### ISSUE TITLE
Oath of Demon Hunter cannot be found

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3573]
I updated the game and the mod to the latest version (1.5.74.3), read the change log and it says we have an Oath of Demon Hunter now. Problem is, it doesn't show up anywhere. I don't find an option to turn it on or off in the mod menu (at the Classes and Subclasses section), and doesn't show up when i try to make a character and look at the subclass options (unless it isn't a paladin subclass).

**Comment by ThyWoof** [comment]
Need to enable beta content in mod.
