### ISSUE TITLE
intermitent issues on Focused Strikes

### ISSUE THREAD

**Issue by lovewinseverytime** [SolastaMods/SolastaUnfinishedBusiness#3579]
Ver 1.5.74.4
No other mods

Playing multiplayer, I found that the bonus action power for the weapon master subclass "Focused Strikes" randomly stops working. I saved the game when it was not working and after reloading the game in single player, I found that it was working again. Cause of the issue is unknown.

[Ticket.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11806178/Ticket.zip)

**Comment by ThyWoof** [comment]
It's very hard to test or debug MP issues. Please reopen the ticket if you're able to reproduce in single player.
