### ISSUE TITLE
Clicking on ground is targeting square right next to it

### ISSUE THREAD

**Issue by Terragnome** [SolastaMods/SolastaUnfinishedBusiness#3580]
Experiencing an issue where clicking on the ground causes character to walk to an adjacent square. The click target seems to be off, and also prevents picking up dropped items

**Comment by zeinterrupter** [comment]
check this issue here for a solution, i believe it is the same we had https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/3452

**Comment by ThyWoof** [comment]
yep, same.
