### ISSUE TITLE
Focused Strikes stops working

### ISSUE THREAD

**Issue by lovewinseverytime** [SolastaMods/SolastaUnfinishedBusiness#3583]
Reopening the following ticket

https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/3579 

Ver 1.5.74.4
No other mods

Playing multiplayer, I found that the bonus action power for the weapon master subclass "Focused Strikes" randomly stops working. Sometimes, when I save the game and reload it works, but often it just does not work even with multiple reloads in single player. 

[ticket 2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11812382/ticket.2.zip)

**Comment by lovewinseverytime** [comment]
well, I rebooted the game, it worked and then stopped working again. If you are trying it out, please note that it is an intermittent issue.

**Comment by EnderWiggin** [comment]
what do you mean "stops working"? Power button is inactive? It is clickable but no effect? There's effect, but no advantage? Is it on position 2 of the powers list when it stops working? We got some reports of similar happenings for other powers.
