### ISSUE TITLE
Inventor Artillerist - Cannon Power not refreshing/castable

### ISSUE THREAD

**Issue by Connormsmith** [SolastaMods/SolastaUnfinishedBusiness#3586]
I am currently having an issue where I cannot seem to cast the cannon power or sacrifice spell slots in order to do so.

I have tried short/long resting, travelling and reloading.

Is there anything I can try short of respecing?

Please let me know if you need any more info. (save attached)

[AutoSave_4.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11827879/AutoSave_4.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/326e44ab-69a6-4ce6-81b3-4479198f8918)
cannot reproduce on my end with your save.

**Comment by Connormsmith** [comment]
Hi Thy, just to clarify, when you click this power to do you get the 5 turret options?

Thanks

**Comment by Connormsmith** [comment]
I just updated to the new patch, and this seemed to fix this.
