### ISSUE TITLE
Hex in multiplayer seems bugged

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3607]
I was watching a streaming, the warlock can apply hex (level 1 spell) each turn even though the current target is not dead.
Unfortunately I am now unable to play the game so no save for now

**Comment by ThyWoof** [comment]
This is by design. We allow retargeting the effect. Not sure if can be done only after first is dead.

**Comment by EnderWiggin** [comment]
Retargeting is by design, but it should only trigger if current target is dead. I tested and was working correctly when implemented, maybe something changed or there's indeed some MP problem.
