### ISSUE TITLE
Life Bard - Deadmaster Wizard multiclass problem

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3608]
I have a Deadmaster wizard and i got 3 levels into bard so i can get that Life Bard feature which auto upcast Transmutation and Necromancy spells. Problem is, the undead summon spells are necromancy spells and the Life bard feature doesn't upcast them.
If it is intended to only upcast bard spells, then please update its description.

Version: 1.5.92.0
Here is the save file:
[bugreport.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11851145/bugreport.zip)

**Comment by ThyWoof** [comment]
fixed in dev.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/83b35aaa-94ab-409c-ace3-d6e1bde03d3b)
