### ISSUE TITLE
Undead summon + Marshal fighter Coordinated Attack issue

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3609]
Undead summons summoned by the Deadmaster wizard doesn't get the option to attack the same creature the Marshal fighter hits. They have a reaction to do the opportunity attack, but the option simply not presented.

Version: 1.5.92.0
Here is the save file:
[bugreport summons.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11851170/bugreport.summons.zip)

**Comment by ThyWoof** [comment]
This is by design to avoid abusing summons. Will consider state this on description.
