### ISSUE TITLE
Life Bard's Reality Bending feature + Vampiric Touch spell issue

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3610]
I am already posting too many issues with my Deadmaster wizard + Life bard multiclassed character, but here is another one. Wizard casts Vampiric Touch spell on 4th level. Reality Bending feature upcast it to lvl 6 for at the time of casting, meaning it will deal damage as if it would be the lvl 6 variant, even tho i spent a 4th level spell slot. The problem is, after the first round when i use Vampiric Touch again (as it is a 1 minute concentration spell which i can reuse as an action), it will return back to being a 4th level spell, dealing damage as if it was cast at 4th level. This tells me that the problem is with the Life Bard's Reality Bending feature and not the spell, in which case i would have reported this to Solasta game devs.

Version: 1.5.92.0
Here is the save file:
[vampiric touch.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11852615/vampiric.touch.zip)

**Comment by ThyWoof** [comment]
This is an engine limitation at the moment.

**Comment by Geriboys** [comment]
Oh, i see. In that case, Heat Metal should suffer the same fate than Vampiric Touch then.
