### ISSUE TITLE
Inventor Thunder Gauntlet not applying Spirit Shroud damage

### ISSUE THREAD

**Issue by ShaunH321** [SolastaMods/SolastaUnfinishedBusiness#3613]
Title - hitting with the gauntlet doesn't apply the extra 1d8 damage. 
![faolan](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/43081184/db248951-5474-4e2d-ab8a-25acf2f93874)
[TestFaolanSpiritShroud.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11853964/TestFaolanSpiritShroud.zip)

**Comment by ThyWoof** [comment]
fixed in dev.

**Comment by ShaunH321** [comment]
Hey, can I ask what "fixed in dev" means? After updating still not applying the damage when attacking.
