### ISSUE TITLE
Weapon Master - Fighter: Wrong interaction between "Momentum" and "Action Sourge"

### ISSUE THREAD

**Issue by Emelion1** [SolastaMods/SolastaUnfinishedBusiness#3618]
When playing a Weapon Master Fighter above 5th level, "Action Surge" should grant more than one attack, since the normal attack action grants more than one attack.
But if "Momentum" triggered and granted you a free extra attack and you activate "Action Surge" after taking this extra attack, "Action Surge" only grants one attack during its attack action.

**Comment by EnderWiggin** [comment]
Try enabling `Interface->Game UI->Enable action switching` and report back. Requires `Gameplay->Tools->Enable beta content` to be on to see that option.

**Comment by Emelion1** [comment]
Yes, this seems to help.
