### ISSUE TITLE
Raven feature "Killing Spree" causes desync in MP

### ISSUE THREAD

**Issue by ThyWoof** [SolastaMods/SolastaUnfinishedBusiness#3624]
### Discussed in https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/3621

<div type='discussions-op-text'>

<sup>Originally posted by **rpavlicek** June 24, 2023</sup>
I've tested this multiple times:
- UB ver 1.5.92.0
- Campaign: POI, 2 players (in the same physical room)
- One character is a level 9 Raven (Rogue), Level 2 Ranger

When the "Killing Spree" class feature triggers, I am able to take a second shot, but the other player does not see anything happening with that second attack. 

On a side note, whenever it triggers, it automatically puts the character in attack mode. You can cancel this to move around, and still attack later. I find this odd, but not a big deal.

The only workaround for now is to finish my turn then save/reload (or don't use the second attack).

If anyone has suggestions on how I can test this further please reply.</div>

**Comment by EnderWiggin** [comment]
oh, I know what's the problem
