### ISSUE TITLE
Sudden Death + Improved critical hit not triggering on a 18 roll.

### ISSUE THREAD

**Issue by gutenhuu** [SolastaMods/SolastaUnfinishedBusiness#3626]
Hi there, hope you're all doing great, and thanks for the awesome mod.
While using the Sudden death dagger from PoI (you crit on 19 and 20) the "Ïmproved crit" feat is not triggering on a 18 roll. 
Save attached for reference; Thanks!
[PoI_Mission1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11857962/PoI_Mission1.zip)

**Comment by EnderWiggin** [comment]
Oh, TA nerfed that dagger worse than I thought. Pre-1.5.92 it was SET Critical Threshold to 18. Now it is Force 19 if it is lower - meaning that dagger mod is removed from initial calculations, then after all modifiers applied it checks if current value if higher than 19 and sets to 19 if so. In this case feat makes it 19 and then this mod is not applied. We definitely need to revert dagger's nerf.
