### ISSUE TITLE
College of Life Bard doesn't get +2 on Enhanced Ability

### ISSUE THREAD

**Issue by night44** [SolastaMods/SolastaUnfinishedBusiness#3629]
Latest version of mod and Solasta. 

College of Life Bard has Reality Bending, which makes Necromancy and Transmutation spells cast 2 levels higher, and it seems to work for other applicable spells so far. Except for Enhanced Ability - it's Transmutation so I should be casting it as a level 4 spell and able to target 3 allies.

In this save, my level 4 Bard is the last character. Try to cast Enhanced Ability and you'll see it only affects 1 ally.

[Life Bard bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11858421/Life.Bard.bug.zip)

**Comment by ThyWoof** [comment]
this is a vanilla limitation and a very small use case to justify a patch. won't fix.
