### ISSUE TITLE
Wings disable with inventory management

### ISSUE THREAD

**Issue by ManBroCalrissian** [SolastaMods/SolastaUnfinishedBusiness#3636]
Tested with both Fairy and Feral Tiefling. Switching weapon, adding arrows into "quiver" slots, and looting bags disables wings. Drinking potions and applying poisons works normally without disabling flight.

Game version: 1.5.92
UB Version: 1.5.92.2

**Comment by ThyWoof** [comment]
We need a save and screenshots please.

**Comment by ManBroCalrissian** [comment]
Saw the fix. Thank you!
