### ISSUE TITLE
No attack roll, harvest and skillcheck msgs anymore after respec in log

### ISSUE THREAD

**Issue by Frobbles12** [SolastaMods/SolastaUnfinishedBusiness#3638]
After respeccing a character the log window doesn't show messages related to the respecced character anymore. I have seen this for all messages types regarding harvesting plants, skill checks and attack rolls in combat. No log entries, while they do still show up for all characters not having been respecced.

This basically renders respec unusable atm. because you can't e. g. decide whether to initiate a smite for your Paladin when the attack roll (critical or not?) is not displayed in the log, to give just one example.

This issue has been introduced in one of the last versions of UB; a week or so ago these things were working.

**Comment by ThyWoof** [comment]
We need a save an screenshots please.

**Comment by EnderWiggin** [comment]
problem is that some listeners are not setup after respec. Save game right after respec and load it - then it should work.

**Comment by Frobbles12** [comment]
No savegame needed, it happens with every savegame as long as the character you respec is lv 10+. Experienced it yesterday in a mod, today in Palace of Ice. Screenshots don't make sense because as I said, no skill checks and attack rolls get displayed anymore, haha. Just use whichever savegame you have yourself, ThyWoof, respec and start combat.

**Comment by ThyWoof** [comment]
Share your save. I’m not in the business of creating a save game for every reported issue. Help us help you.

**Comment by Frobbles12** [comment]
Okay, may take an hour or so. Just stand by...

**Comment by ThyWoof** [comment]
Now you understand I’m not in the saves business. Whenever I test myself it simply works.
