### ISSUE TITLE
Changeing weapons makes Fairy and Wild Tiefling fall

### ISSUE THREAD

**Issue by IvanAtlanticus** [SolastaMods/SolastaUnfinishedBusiness#3642]
UB version: 1.5.92.2
Game version: 1.5.92
When Fairy and Wild Tiefling are flying, changeing weapons would make them fall. The following is screen recording. You can download and watch them.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/90498118/32731228-f82c-4263-9747-0f51b084fe91

https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/90498118/f51c6e7c-1e3d-480d-be0d-7854699a39d5

**Comment by ThyWoof** [comment]
Already fixed in dev. Thanks
