### ISSUE TITLE
Shapechange spell does not work when metamagic is enabled

### ISSUE THREAD

**Issue by SKramarz** [SolastaMods/SolastaUnfinishedBusiness#3644]
Mod Version 1.5.92.2
Casting ShapeChange no longer brings up the list of transformation options, it just does the animation for casting the spell, consumes the 9th level slot and nothing happens.

[RiceInIce.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11860334/RiceInIce.zip)

**Comment by SKramarz** [comment]
Tried it without metamagic toggled on and it worked normally so it looks like the issue is specifically happens after the metamagic options show up, even if you hit ignore to not use one.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/a91df408-953c-45c7-b4fa-e03dabcc3b24)

**Comment by ThyWoof** [comment]
fixed in DEV.
