### ISSUE TITLE
Incorrect pickup location

### ISSUE THREAD

**Issue by matt4653** [SolastaMods/SolastaUnfinishedBusiness#3653]
Persistent pickup bug ever since installing the mod a couple of weeks ago, I've worked around it but it's now causing a game-breaking problem since I can't complete the forced long rest before the final stage.

Version: Bug has been present since 1.5.74, and is still present in 1.5.92
Mod version: 1.5.92.3 (current)
Other mods installed: None
Present in vanilla install: No
Bug: Pickup location is not correct (clicking on a loot drop or location actually sends character to an adjacent cell)
Procedure: Most clicks on loot drops with an individual character send them one cell to the left, right, above or below. If entire party is selected, pickup doesn't happen automatically but can be manually initiated by the second party member. This was especially problematic in the Family Reckoning quest (couldn't exit house when clicking door after search) and in the final stage before Aer Elai, inside the princess' time bubble (clicking to take a long rest tries to force party outside bubble, which returns No Path to Destination). 

Save, character and log file attached in zip. 
[Solasta files.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11875374/Solasta.files.zip)

**Comment by ThyWoof** [comment]
https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/3488
