### ISSUE TITLE
This armour with att should probably add +3 to AC

### ISSUE THREAD

**Issue by Majber** [SolastaMods/SolastaUnfinishedBusiness#3658]
It probably should be 15AC,first value.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8217598/868d8c02-8946-4b45-b9b3-59f81096fa66)
How its now:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8217598/151f04f3-2171-4cfe-9ae9-bc41eb39d693)

**Comment by ThyWoof** [comment]
Is this armor vanilla?

**Comment by ThyWoof** [comment]
Can I have your save?

**Comment by Majber** [comment]
Sure, here is save, this armour is on Character named Raven, not attuned atm.
[after.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11886332/after.zip)

**Comment by ThyWoof** [comment]
This seems to be a game bug. Let's wait for a fix. Meanwhile I found a small issue on "Remove att requirements". On next release you could enable that setting so at least you can get the +3 AC on this armor. There are other items in game presenting same behavior.
