### ISSUE TITLE
Can't increase Sorcerery points on Sorcerer only

### ISSUE THREAD

**Issue by Lyvewyrez** [SolastaMods/SolastaUnfinishedBusiness#3659]
Hi There. Have 2 issues, but main one is with Sorcerer, the in game value for sorcerery points won't change using the party editor for Sorcerer only. Any other class can increase or decrease no issues.

Second issue, more minor, is that I'm stuck with all spells being available to any caster, even after turning off that feature. Not sure how to fix it.

Any help is greatly appreciated, thanks!

**Comment by ThyWoof** [comment]
Unfortunately party editor is in beta and the original developer isn’t working on it. Nothing I can do about it. Share a save for the second issue.

**Comment by ThyWoof** [comment]
Unfortunately there isn't much I can do to help here. This save file is corrupted. Probably reason why you're seeing all the spells.
