### ISSUE TITLE
Spirit Shroud is incorrectly refactored

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3661]
It should apply to each attack roll hit including wapons and spells.
[rule reference](https://www.dndlounge.com/spirit-shroud-5e/#:~:text=So%20while%20a%20spell%20like%20eldritch%20blast%20works,because%20magic%20missile%20is%20not%20a%20spell%20attack.)
commit related: 0f527fea97858d3ff6428dd531161c21e6722615
(It seems that the sprites effect of spirits circling is also lost)

**Comment by ThyWoof** [comment]
Does it work if you remove the custom subfeature and the weapon required property?

**Comment by HIEROT** [comment]
The damage works if you remove
```
.SetAttackOnly()
```
and get .SetAttackOnly() back.
But the I can't immediately digure out why sprites are lost.
