### ISSUE TITLE
mod instability when you create spell slot from sorcery points and cancel realizing that you don't have enough points

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3669]
If you use create spell slot and cancel because you don't jave enough points, the game gets stuck.
If the cause is not obvious, i will try to provide a save.
Guessing this is related to action refund because you didn't use that bonus aaction if you cancel creating spell slot.

**Comment by ThyWoof** [comment]
please share save and step-by-step to reproduce. or your player.log next time it happens.

**Comment by ThyWoof** [comment]
any updates?

**Comment by HIEROT** [comment]
> any updates?

Will try to reproduce this and inform you later
