### ISSUE TITLE
Starting Ice Palace with level 1 characters gets stuck during first level up

### ISSUE THREAD

**Issue by jrbuda** [SolastaMods/SolastaUnfinishedBusiness#3671]
Started Ice Palace campaign with 2 level 1 characters in a multiplayer game. Tried to level up, game locks up.
Version: 1.5.92.5
Mods: Only UB
Repro steps:
Create level 1 character in main menu, start a multiplayer game, change campaign to Ice Palace, game starts and click level up, eventually locks up (see pic)
I apologize for the character names, was running a joke campaign with friends. 
No save file for this one since the campaign did not start
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11913194/Player.log)
[Characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11913204/Characters.zip)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/47678481/0d946c2e-2389-4184-b23e-c308ea5c2d5d)

**Comment by ThyWoof** [comment]
Not caused by the mod. This pop will display regardless of that. Try to not fly over the level up screen.
