### ISSUE TITLE
Turn order desyncing

### ISSUE THREAD

**Issue by jrbuda** [SolastaMods/SolastaUnfinishedBusiness#3673]
Version: 1.5.92.5, multiplayer game
Mods: UB
Description: Sometimes when combat starts, the turn initiative is desync'd for players causing the game to stall/lock up
Repro in this specific case: Snuck into combat, warlock cast a spell to get surprise round, initiatives desync'd. Host has all characters in one order, other players have a different order. When characters get out of order, the game locks up entirely.
[characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11923022/characters.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11923024/Player.log)
[save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11923032/save.zip)

**Comment by jrbuda** [comment]
We reloaded the save and tried the same combat but not sneaking/surprise round and it looks like it functions properly.

**Comment by ThyWoof** [comment]
Which are the other characters class wise and level?

**Comment by jrbuda** [comment]
[characters-other.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11923570/characters-other.zip)
Here are the character files for the other two from my second player

**Comment by jrbuda** [comment]
It only seems to happen when we try to sneak. Going to try some different scenarios to reproduce it again

**Comment by jrbuda** [comment]
Happens more often if you play with more players

**Comment by jrbuda** [comment]
I am finding a ton of complaints online about initiative desyncing in the base game, this is possibly not mod related but we did only start seeing this issue once we put the mod in. 
I also get a popup when I start the game that says solasta found an instability in the mod even after fresh install

**Comment by ThyWoof** [comment]
This pop up will always display on an error if you have the mod installed regardless of the mod. Nothing we can do about it and end up getting the wrong idea mod is fault.

On second issue it looks like you have one or more saves or one or more characters causing that. Usually deleting all saves and heroes and bring them back one by one allows you to find the bad ones.


Closing as desync isn’t mod related.
