### ISSUE TITLE
Stuck in the 2nd tutorial

### ISSUE THREAD

**Issue by Ishazamo** [SolastaMods/SolastaUnfinishedBusiness#3674]
Hello, 

When i play with the mod installed, i can't reach the rock needed to continue the second turorial because the game make me start the fight at a wrong place. 

See screenshot below. 

I only have Unfinished Business installed and i have already uninstall-reinstall my game.
![Capture d'écran 2023-06-30 225849](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/138257653/45004493-0536-4dcd-9e48-262b18500228)

Thx for your help.

**Comment by ThyWoof** [comment]
Won’t fix. It’s the tutorial.
