### ISSUE TITLE
Issue with flight through doorways

### ISSUE THREAD

**Issue by tyrannodorkus** [SolastaMods/SolastaUnfinishedBusiness#3680]
**The versions of Solasta and this mod.**
1.5.92.5

**A list of other mods you have installed [you shouldn't have any].**
Unfinished Business

**A short description of the bug.**
There's some strange bug I've been seeing recently while flying, you can't go through doorways. I don't know if that is caused by UB or base game, but just wanted to report an issue that came from this.

As a dragonborn using the racial feat for wings, when I used that while in a doorway, I was stuck there and couldn't move anywhere. There doesn't seem to be anyway to drop that dragonborn flight, and dispel magic didn't seem to work. Would there be a way to add a dismiss or toggle to that feature? Or if fixing the door issue would be ideal if caused by UB. But a dismiss or toggle would work too.

**A step-by-step procedure to reproduce it.**
Move inbetween a set of doors, and activate flight. All movement squares will no longer show as there is no more path for you to take.

**The save, character and log files.**
[Palace of Ice.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11926973/Palace.of.Ice.zip)
Dorian Megalogon

**Comment by ThyWoof** [comment]
It’s a vanilla bug. Let’s wait for an official patch.
