### ISSUE TITLE
Ranger Hellwalker subclass Enduring Sting not scaling

### ISSUE THREAD

**Issue by VessValyren** [SolastaMods/SolastaUnfinishedBusiness#3691]
The versions of Solasta and this mod.
Game 1.5.74
Mod 1.5.92.8

A list of other mods you have installed [you shouldn't have any].

None

A short description of the bug.

The Hellwalker subclass grants the Ranger the Enduring Sting cantrip as an action.  However it does not scale at level 5, 11, or 17 in damage dice like the actual cantrip.  

[Hellwalker Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11932143/Hellwalker.Save.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f876b54c-f1a2-49c3-b5a4-1ccbb389c7fa)
