### ISSUE TITLE
Converting spell/sorcery points trigger the menu for everyone while in multi-p.

### ISSUE THREAD

**Issue by Darkhain** [SolastaMods/SolastaUnfinishedBusiness#3695]
Each time I try to convert spell or sorcery point to one an other, it triggers the menu for everyone in the group in multiplayer (as the host at least), and it's giving the point they are converting for it.
[pûuxu3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11935995/puuxu3.zip)

**Comment by ThyWoof** [comment]
As far as I can tell it’s a known game issue.
