### ISSUE TITLE
Scaling on Path of the Light Improved Illuminating Strike Radiant Damage not increasing

### ISSUE THREAD

**Issue by BPLDigs** [SolastaMods/SolastaUnfinishedBusiness#3707]
Just hit level 10 with a Half-Orc Barbarian and the Radiant damage from Improved Illuminated Strike is still only 1d6.

Context: Level 10 Half-Orc Barbarian with Great Weapons Fighting Style. Using a Punisher Maul and the following Feats: Devastating Strikes, Follow up Strike, Hammer the Point. 

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/31557970/6a5954bb-88df-479f-a099-6becd36cdeed)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/31557970/8168c84f-5644-4e70-a1e9-64d14f6b63b2)

**Comment by ThyWoof** [comment]
Do you have a save?

**Comment by ThyWoof** [comment]
It indeed has 1 dice at 10. It’ll be 2 from 11. Will fix.
