### ISSUE TITLE
[BETA] Bardic Inspiration during battle (1.5.92.9)

### ISSUE THREAD

**Issue by OneFrustratedCoder** [SolastaMods/SolastaUnfinishedBusiness#3713]
Bardic Inspiration always works outside of battle. 

But during battle, after adding a Bardic Inspiration status to the target (as a bonus action), the game seems to be waiting for something else to happen. But all of the buttons are gone.

After my saved character failed, I tested it with a pre-generated lvl 1 bard on a new campaign. Bardic Inspiration works without the mod. It breaks when the mod is turned on.

**Comment by OneFrustratedCoder** [comment]
I need to do more testing. I just tried with empty settings and it worked. 

I'll figure out which setting breaks it and come back with a better description.

**Comment by OneFrustratedCoder** [comment]
<EnableActionSwitching>true</EnableActionSwitching>

Breaks Bardic Inspiration during battles.

**Comment by ThyWoof** [comment]
@EnderWiggin

**Comment by ThyWoof** [comment]
do you have a save we can use on QA?

**Comment by EnderWiggin** [comment]
@OneFrustratedCoder does it show error popup?

**Comment by EnderWiggin** [comment]
seems to me same issue as was with rage - it spends BA twice. We need to patch CharacterActionGrantBardicInspiration to use power as `PowerFree` and not as `PowerBonus` since action itself uses up BA.

**Comment by EnderWiggin** [comment]
Or we can set `classNameOverride` of `GrantBardicInspiration` to some custom name and create new character action class instead of making patch. Or even just try setting it to "UsePower" and see if that works?

**Comment by ThyWoof** [comment]
Please share a save I can use to test

**Comment by OneFrustratedCoder** [comment]
Here's a save file. 
[broken.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11970602/broken.zip)

**Comment by OneFrustratedCoder** [comment]
> @OneFrustratedCoder does it show error popup?

Nope.

**Comment by ThyWoof** [comment]
Too late 🙃, fixed already.

**Comment by OneFrustratedCoder** [comment]
Thanks for the great work everyone!
