### ISSUE TITLE
Focused strikes doesn't seem to label as advantage

### ISSUE THREAD

**Issue by Pop000100** [SolastaMods/SolastaUnfinishedBusiness#3714]
Focused Strikes doesn't label attacks as advantage in the event log. It is multiplayer but I control the character that has it and it appears in my log.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11955198/Player.log)

**Comment by ThyWoof** [comment]
unfortunately cannot reproduce on my end. Weapon Master had a lot of QA time before release. Code is sound so it might be some strange MP interaction like others in vanilla game.
