### ISSUE TITLE
bug. Weapon Specialization

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#3722]
![1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/7f6705d1-ed34-4d33-adc8-2cb6b94bb749)
Unless I've misunderstood, only one bonus effect should be applied to one weapon type, but multiple are applied.

![2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/3077c14d-d47d-45bc-9de4-79d03a5f28af)
Other subclasses have this problem too.

**Comment by ThyWoof** [comment]
Can you share these heroes or save?

**Comment by kdgmo** [comment]
https://drive.google.com/file/d/1rl7TTo6eaZX5Iav3Z_sBYFJCRK0Va4mx/view?usp=drive_link
savefile

**Comment by ThyWoof** [comment]
Make link public

**Comment by kdgmo** [comment]
open link.

**Comment by ThyWoof** [comment]
there isn't much I can do with a save in a location. Share the heroes instead or a save in a campaign.

**Comment by ThyWoof** [comment]
Probably fixed.
