### ISSUE TITLE
bug. bonus feat level 2/6/10/14/18 bug

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#3723]
fighter&rogue bug.
[enable both attribute scores increase feat secletion]  A bug occurs when the option is disabled.
![2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/3e4fb24e-1fea-4f9a-8e97-d887dd97852d)
![4](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/d0992cee-e07f-4c48-876a-aba64269ac7d)
![5](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/3164036d-1b55-403a-9a16-6e206f18ff3b)
When this option is enabled, the contents of this screenshot are correct, but when the option is disabled, this is clearly a bug.
If the option is disabled, the fighter's level 6/14 rogue should only add 1 feat at level 10.

**Comment by ThyWoof** [comment]
Did you restart after changing the option?

**Comment by kdgmo** [comment]
of course.

**Comment by ThyWoof** [comment]
Fixed
