### ISSUE TITLE
Not fix. bonus feat level 6/10/14 fighter&rogue bug

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#3732]
I checked with the latest version and it still hasn't been fixed.

![1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/9f758eb7-3f5a-45ec-a242-767f4bb29fb7)
![2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/a131e7ec-0866-44f5-a803-d920fb481e01)
![3](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/927b6a7e-e5b2-4673-a72f-7b7db649c267)

I've tried various settings to check, but the problem is still there.
![4](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/927946d9-cf09-46e4-8271-0043c4a0ec12)
With this setup, bonus feats should have been 1 instead of 2.

**Comment by ThyWoof** [comment]
Fighters get additional feats at 6 and 14. Rogues at 10. If you enable the mod settings they will add up to what is already there. This isn’t a bug but lack of understanding on how these settings work.
