### ISSUE TITLE
Malakh ancestry not showing full details in character creation

### ISSUE THREAD

**Issue by ManBroCalrissian** [SolastaMods/SolastaUnfinishedBusiness#3733]
The base features for the class are shown, but you are unable to scroll down to reveal the sub-race features for Herald, Guardian, and Judgement Malakhs. 

Very excited to see Aasim....err, I mean, Malakhs in the game!

**Comment by ThyWoof** [comment]
We could use the same strategy to leverage the additional features selection UI in the mod to allow the selection there. Like we do for optional ranger choices.

**Comment by otearaisu** [comment]
> We could use the same strategy to leverage the additional features selection UI in the mod to allow the selection there. Like we do for optional ranger choices.

@ThyWoof Is this different from FeatureSet? Because I've tried it already it doesn't work in race features above level 1.

**Comment by ThyWoof** [comment]
> > We could use the same strategy to leverage the additional features selection UI in the mod to allow the selection there. Like we do for optional ranger choices.
> 
> @ThyWoof Is this different from FeatureSet? Because I've tried it already it doesn't work in race features above level 1.

something very similar to what I'm coding now for Arcane Archer:

```
    private static void CreateArcaneArcherChoices(params FeatureDefinitionPower[] powers)
    {
        foreach (var power in powers)
        {
            var name = power.Name.Replace("Power", string.Empty);
            var guiPresentation = power.guiPresentation;

            _ = CustomInvocationDefinitionBuilder
                .Create($"CustomInvocation{name}")
                .SetGuiPresentation(guiPresentation.Title, guiPresentation.Description)
                .SetPoolType(InvocationPoolTypeCustom.Pools.ArcaneArcherChoice)
                .SetGrantedFeature(power)
                .SetCustomSubFeatures(HiddenInvocation.Marker)
                .AddToDB();
        }
    }
```

create a similar loop for the 3 different race features. create another single feature and grant it at level 3:

```
        var invocationPoolArcaneArcherChoice1 = 
            CustomInvocationPoolDefinitionBuilder
                .Create("InvocationPoolArcaneArcherChoice1")
                .SetGuiPresentation(Category.Feature)
                .Setup(InvocationPoolTypeCustom.Pools.ArcaneArcherChoice, 1)
                .AddToDB();
```

You'll need a new invocation pool definition for this particular race as well.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c286e56c-f461-42bf-aca7-74d29df5dca3)
here is how it looks like on level up.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/82baa247-ee05-4284-9dff-cba635998056)
couldn't find anything wrong with feature sets. will go this direction.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/05ac7710-bf75-41eb-8117-5792f1302a57)
