### ISSUE TITLE
Mystic Arcanums Missing POI

### ISSUE THREAD

**Issue by OmniDaemon** [SolastaMods/SolastaUnfinishedBusiness#3734]
As requested on [the reddit post](https://www.reddit.com/r/CrownOfTheMagister/comments/14stf1p/mystic_arcanums_missing_unfinished_business/), here is the save where the Mystic Arcanums are missing.

[WarlockSave.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11974733/WarlockSave.zip)

**Comment by ThyWoof** [comment]
can you please be more specific on what's missing? choice on level up? spell on casting UI? or spell on Inventory panel?

**Comment by OmniDaemon** [comment]
Only the Mystic Arcanums in the casting UI are missing both in combat and out. I can select the spells in level up and see them in the inventory panel just fine, but I can't cast them.

**Comment by ThyWoof** [comment]
I’m away from game computer so will ask more questions before I can look at the save. What is the warlock level?

**Comment by OmniDaemon** [comment]
Level is 13. I recall seeing the sixth level Mystic Arcanum when I reached level 11 in casting list, but I've noticed them missing at least since I got level 13 in Palace of Ice
