### ISSUE TITLE
Paladin Fairies cannot fly

### ISSUE THREAD

**Issue by Guilty-Man** [SolastaMods/SolastaUnfinishedBusiness#3740]
As title says, Fairy Paladins do not have the Flight power, only the paladin powers.
Also, paladin free-hand. Even with a holy symbol, the paladin cannot cast with a shield.

**Comment by ThyWoof** [comment]
please fully read the power description before opening an issue. "Because of your wings, you have a flying speed equal to your walking speed. You can't use this flying speed if you're wearing medium or heavy armor."
