### ISSUE TITLE
Bug with using feat "War Caster" when triggered by subclass "Marshal"

### ISSUE THREAD

**Issue by aToO57** [SolastaMods/SolastaUnfinishedBusiness#3750]
SolastaUnfinishedBusiness Version : 1.5.92.12
UserCampaign: https://steamcommunity.com/sharedfiles/filedetails/?id=2687348727

Description:
> The game bug when using ranged reaction from the feat "War Caster" when it trigger by the subclass "Marshal" with "Coordinated Attack".

A step-by-step procedure to reproduce it:

> - Attack with "Za Roth" 
> - Select a ranged reaction with "Pimelith" (Eldritch Blast)

 [yendor11.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11992372/yendor11.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11992371/Player.log)

And there is climb issue on character "Pimelith"
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17197835/382901b5-f291-4a99-beaa-96d6210130ca)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1839074e-ff2d-4afa-95e9-7ee5d9852cb5)
@EnderWiggin, it's indeed not getting a rulesetSpellEffect.

changed title as climb issue isn't caused by mod but by custom location.

**Comment by aToO57** [comment]
Hello @ThyWoof,

I don't know if it work as intented, but the spell use the current weapon as base.

If use a spell (Eldritch Blast) with a dagger equip i get a disaventage for long range attack.

No disaventage if i switch to a crossbow.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17197835/deec44fa-0d72-40e9-aed4-cb573e2177f8)

**Comment by aToO57** [comment]
And by the way thank for the quick fix !
