### ISSUE TITLE
Cleric + Divine Heart Sorcerer Multiclass

### ISSUE THREAD

**Issue by Lasso0fTruth** [SolastaMods/SolastaUnfinishedBusiness#3751]
If a Divine Heart Sorcerer multiclasses into cleric they're unable to learn any of the spells from their expanded spell selection that Divine Heart gives them. The cleric spells are unable to selected and listed as known through a multiclass.

**Comment by ThyWoof** [comment]
use the option under multiclass to allow relearn cantrips or spells from other repertoires.
