### ISSUE TITLE
Artillerist Inventor's Refund Cannon Power doesn't work

### ISSUE THREAD

**Issue by DocShambler** [SolastaMods/SolastaUnfinishedBusiness#3752]
I'm currently playing Lost Valley with with Unfinished Business 1.5.92 12 installed. I'm running into the following issue.

I have an Inventor - Artillerist, and the Refund Cannon power is bugged. If the first summoned cannon expires, I have no way of getting it back unless the party takes a long rest. The save I've included is just after one such instance where the cannon has expired.

[Refund Cannon Bugged.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11994273/Refund.Cannon.Bugged.zip)

**Comment by ThyWoof** [comment]
Fixed in DEV. Thanks for the save.
