### ISSUE TITLE
Pugilist fighting style 

### ISSUE THREAD

**Issue by MarinerEarendil** [SolastaMods/SolastaUnfinishedBusiness#3759]
version 1.5.92.12 and no other mods

Pugilist fighting style while wielding a 2H weapon allows for a bonus action unarmed attack but not a shove. When changing the configuration to a 1H weapon, the shove option is there.

Save: 
[morrows deep.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11997556/morrows.deep.zip)

Reproduce: advance initiative order to "Beren" character. Compare "Maul +1" weapon configuration to "Javelin" configuration.

**Comment by ThyWoof** [comment]
@EnderWiggin , we currently have this patch:

```
        [NotNull]
        [UsedImplicitly]
        public static IEnumerable<CodeInstruction> Transpiler([NotNull] IEnumerable<CodeInstruction> instructions)
        {
            //PATCH: Support for Pugilist Fighting Style
            // Removes check that makes `ShoveBonus` action unavailable if character has no shield
            static bool True(RulesetActor actor)
            {
                return true;
            }

            var isWearingShieldMethod = typeof(RulesetCharacter).GetMethod("IsWearingShield");
            var trueMethod = new Func<RulesetActor, bool>(True).Method;

            return instructions.ReplaceCalls(isWearingShieldMethod,
                "GameLocationCharacter.GetActionStatus",
                new CodeInstruction(OpCodes.Call, trueMethod));
        }
```

game code has this check:

`actionId == ActionDefinitions.Id.ShoveBonus && !this.RulesetCharacter.IsWearingShield()`

wondering if this patch is still relevant.

**Comment by ThyWoof** [comment]
so forcing true there will never make the shove bonus action avail.

**Comment by ThyWoof** [comment]
cannot open ZIP file. Says it's invalid. Can you share a new one?
