### ISSUE TITLE
Unable to save game

### ISSUE THREAD

**Issue by 5cr4mb1ed3gg5** [SolastaMods/SolastaUnfinishedBusiness#3765]
With the new update I have encountered an issue where I cannot create a new save. I have tried new games with custom and pregen characters. I am still unable to create new save files for either, when I disable the mod I am. It appears the save screen is getting frozen while overlaying the paused screen. This was working fine with the previous mod file. I am playing Palace of Ice, if that makes a difference

**Comment by 5cr4mb1ed3gg5** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/121354380/ad3e0753-faca-4b30-b1d3-cbb3c2f73896)

**Comment by sztrzask** [comment]
Hi man. It usually helps when you include save game and Solasta log, both Player and Player-prev.

Log files can be found here: 
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/4059524/8d00bf9a-1c93-4671-a94e-8d8e99f7b293)

And that files are next to folder called `Saves` where save games are

**Comment by 5cr4mb1ed3gg5** [comment]
I just reverted back to the .12 update, Everything is working fine.

**Comment by 5cr4mb1ed3gg5** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/121354380/87b8a722-ce47-483d-8fd4-75f658dd27a0)

**Comment by 5cr4mb1ed3gg5** [comment]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12006305/Player.log)

**Comment by 5cr4mb1ed3gg5** [comment]
I just did a fresh update from .12 so I could send you these files. I hope these are what you are looking for and I hope they help.

**Comment by ThyWoof** [comment]
If it works on v12 and it doesn't on v14 it means you have one or more saves / heroes with a Monk Distant Hand and or a Malakh race.

**Comment by 5cr4mb1ed3gg5** [comment]
I had a Malahk race (judgement) character and disappeared after the update to .14. The entire save file disappeared too. I dont have that character anymore nor have a way to locate it and have not created a distant hand monk. 

I did note the changes in the change log.

**Comment by ThyWoof** [comment]
These saves and heroes still exist in your computer and are leading to this.

**Comment by 5cr4mb1ed3gg5** [comment]
Thats what it sounds like to me as well. I honestly have no idea where I would look. They are not in the game file. Sorry I am sorta new to all this

**Comment by ThyWoof** [comment]
Start the game and then alt tab to windows. Type %APPDATA%\LocalLow\Tactical Adventures\Solasta on windows explorer. Your saves and heroes are there.

**Comment by ThyWoof** [comment]
Delete them while game is running. Only after that alt tab back to game and close game

**Comment by 5cr4mb1ed3gg5** [comment]
Okay, I did that and there were no new characters. Only the ones I made today. I erased all saved games that I made within the last few days, went back to the game and closed it. I updated back to .14 and reopened the game and it seems like it solved all the issues. I thank you for helping me and Im sure other people will benefit from this too. I was pulling my hair out
