### ISSUE TITLE
Tempest Monk Doesn't get Disengage after Flurry of Blows

### ISSUE THREAD

**Issue by Smite-Sion** [SolastaMods/SolastaUnfinishedBusiness#3767]
I play POI campaign, with new party. So instantly levelled all characters to level 10.
I am currently on 1.5.92.12, I didn't had a respec location yet for Malakh race
[Tempest Monk Debug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12005820/Tempest.Monk.Debug.zip)

**Comment by ThyWoof** [comment]
fixed in v14.
