### ISSUE TITLE
Sunbeam is crashing the game

### ISSUE THREAD

**Issue by Daard** [SolastaMods/SolastaUnfinishedBusiness#3769]
After cast of Sunbeam spell a popup window appears, ui disappears and I can't save or load game. How to solve this issue?

**Comment by ThyWoof** [comment]
**How to report issues**

- The versions of Solasta and this mod.
- A list of other mods you have installed [you shouldn't have any].
- A short description of the bug.
- A step-by-step procedure to reproduce it.
- The save, character and log files.

**Check the folder %APPDATA%\LocalLow\Tactical Adventures\Solasta** for the info we need.

**Comment by NeatWolf** [comment]
I ran into a similar issue in multiplayer: if either the host or client cast such spell, it de-synchs the game 100% of the times.
I believe it's a regression as previously (approximately 1-2 weeks ago maybe?) didn't happen and worked as a charm.
The only issue was that you could cast the spell and also use the Sunbeam UI card/button to attack again in the same turn.
I can't attach a save atm but will do tomorrow.

**Comment by ThyWoof** [comment]
> I ran into a similar issue in multiplayer: if either the host or client cast such spell, it de-synchs the game 100% of the times.
> I believe it's a regression as previously (approximately 1-2 weeks ago maybe?) didn't happen and worked as a charm.
> The only issue was that you could cast the spell and also use the Sunbeam UI card/button to attack again in the same turn.
> I can't attach a save atm but will do tomorrow.

How to report issues

The versions of Solasta and this mod.
A list of other mods you have installed [you shouldn't have any].
A short description of the bug.
A step-by-step procedure to reproduce it.
The save, character and log files.
Check the folder %APPDATA%\LocalLow\Tactical Adventures\Solasta for the info we need.

**Comment by Daard** [comment]
I have attached required data. 

 "Version": "1.5.92.14",
  "GameVersion": "1.5.92",
  "ManagerVersion": "0.24.0",
  Only UB

[Solasta copy.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12025019/Solasta.copy.zip)

**Comment by sztrzask** [comment]
There is no log file in the zip you provided

**Comment by Daard** [comment]
Yes, there are not logs in my folder. Do I need to add a toggle for this anywhere?

**Comment by ThyWoof** [comment]
Closing this issue as it lack proper assets to debug. I need one single save file, step by step to reproduce. I you simply zip all you have and throw on us it won't work.
