### ISSUE TITLE
Update UB 1.5.92.14 breaks backwards Palace of Ice save compatibility

### ISSUE THREAD

**Issue by NeatWolf** [SolastaMods/SolastaUnfinishedBusiness#3773]
I can't leave more details atm but upgrading from .12 to .14 makes all saves in the Palace of Ice folder incompatible.

Restarting the whole campaign fixes the problem [but it's far, far from ideal]. Saves from later on in the game trigger the "issue with mods" error dialogue.

Reverting the game to .12 is impossible from .14's UB interface. Needs to be d
[Palace of Ice.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12018503/Palace.of.Ice.zip)
one externally.

Reverting to a version .12 fixes the issue. 

Attaching all save in the campaign. "ShamboCoop.sav" is the latest.

**Comment by ThyWoof** [comment]
Have you read the changelog before update?

**Comment by NeatWolf** [comment]
I always do - did I miss something so macroscopic I didn't notice? Recently the changelog became also the what's new and what's next - could you please elaborate?

**Comment by NeatWolf** [comment]
Even after respeccing the character as a human, it still breaks the load menu if at least 1 save uses a previous version.
Is that the expected behaviour?
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/6001560/bfc1dc47-07e6-4ff1-ad9f-63ba25ff43be)
I don't get it tho - I'm not using beta releases. This change's quite gamebreaking! 😅

**Comment by sztrzask** [comment]
> it still breaks the load menu if at least 1 save uses a previous version.

From the release notes:

> RESPEC any Malakh race hero **or save** before update

**Comment by NeatWolf** [comment]
I see. So it was intended to be a breaking change. Of course I can't be respeccing previous savegames of the whole campaign so I will need to move them elsewhere - even if they're not actively loaded they do prevent the game from working correctly.

Thanks for the clarification, I'm closing this as won't fix/works intended.
