### ISSUE TITLE
Multiclassing and proficiencies

### ISSUE THREAD

**Issue by Daard** [SolastaMods/SolastaUnfinishedBusiness#3777]
If I take one level of martial class after caster I will not get armour and weapons proficiencies. This issue makes me level up in a specific way and this could be very inconvenient. 

For example: if I want to sorcerer X / bard X / paladin 2 my goal is to get extra attack as much faster, 
- I will take after level 6 two levels of paladin for smites and heavy armour prof. But I will not get this heavy armour prof in current state of the mod. 
- Two levels of paladin at first and then X bard or  X sorcerer levels will slow my character a lot, because I will get extra attack only on level 8. 
- This character will also not receive profs in saving throws. 
Paladin / bard should have dev, wis, cha profs in saving throws
Paladin / sorcerer - con, wis, cha profs in saving throws

**Comment by sztrzask** [comment]
That's the correct behaviour. In 5e multiclassing doesn't give you proficiencies.
