### ISSUE TITLE
Mac UMM install instructions need to be updated for cases when files in zip are older than base files

### ISSUE THREAD

**Issue by coined** [SolastaMods/SolastaUnfinishedBusiness#3783]
The instructions in the Mac section of https://github.com/SolastaMods/SolastaUnfinishedBusiness/wiki/Install say:

_Paste here the contents folder from the clipboard. CHOOSE MERGE!_

"Merge" keeps the _newer_ of the two files when there is a conflict. Unfortunately, that means that if the game has recently been installed, the merge keeps the version of UnityEngine.UIModule.dll from the base Steam installation, rather than the version from the downloaded zip file, which will have an older timestamp (in my case Dec 26, 2022).

I recommend updating the Install file to indicate that when installing UMM on a mac you may need to manually copy UnityEngine.UIModule.dll from the zip file over the original.

**Comment by ThyWoof** [comment]
This is a comm mod. Would you provide new instructions so I can update wiki?
