### ISSUE TITLE
Lockup deletes save

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#3787]
Lately, I've been getting random lockups that have the side effect of deleting the most recent save. I'm current on both Solasta and UB and this started about two updates ago. Could be a Windows bug as I also recently did updates there.

I realize this is not much to go on, since I obviously can't furnish a save file. But I thought I should report it in case others are seeing it.

I've resorted to double save files and restarts, but this is a particularly irritating bug.

**Comment by ThyWoof** [comment]
Can you share a player log next time it happens?

**Comment by ThyWoof** [comment]
Thanks for the update. Will close this one.

**Comment by charlesewatkins** [comment]
Oh no. It happened again. Here's the log.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12089828/Player.log)

**Comment by ThyWoof** [comment]
I couldn’t find any errors specific to this problem but found some heroes having trouble loading. You must delete them. Search file for all occurrences of “exception when loading” and delete all these files. Remember you have to delete them while game is running. Close the game after.
