### ISSUE TITLE
Oath of Thunder interaction with Ranged Expert feat

### ISSUE THREAD

**Issue by VitFall** [SolastaMods/SolastaUnfinishedBusiness#3798]
Oath of Thunder allows you to make ranged attacks with a warhammer. Ranged expert allows you to make a bonus action one-handed ranged attack after taking the attack action.

Currently, Ranged Expert doesn't work with Oath of Thunder. Taking the attack action doesn't allow you to make an additional throwing attack as a bonus action. Should it?

**Comment by ThyWoof** [comment]
Ranged expert won’t interact with Thunder.

**Comment by VessValyren** [comment]
Know its closed but just to give Vitfall more clarity, Ranged Expert specifically says Ranged Weapons, thrown weapons are not considered Ranged Weapons in 5e: https://roll20.net/compendium/dnd5e/Weapons#content 

Thrown weapons are Simple Melee or Martial Melee weapons that have the thrown tag.  But this is not the same as Ranged Weapons as you can see they also have their own category of Simple Ranged and Martial Ranged weapons.  So anytime it says "Ranged x" or in this case "make one-handed ranged bonus attack" it would have to be a weapon from the Ranged categories.  

So a Dart and a Hand Crossbow would work in Solasta.
