### ISSUE TITLE
Desync in Multiplayer after mod update 

### ISSUE THREAD

**Issue by Ishazamo** [SolastaMods/SolastaUnfinishedBusiness#3801]
Hello, 
I'm sorry to bother you with something trivial like this, but I don't quite understand. 

I'm playing with a friend in multiplayer, and as soon as we update the mod, the game desynchronizes us at the first fight, making the game unplayable. I send, after the maj, the "config" of the mod to my friend. 

I've tried to find a solution here or on the internet in general, but I haven't found anything yet. 

If this helps, we're playing the "Crown of the Magister" campaign. 

Thank you very much for your future answers.

**Comment by ThyWoof** [comment]
fixed on v1.5.94.0.
