### ISSUE TITLE
Solasta detected an instability...

### ISSUE THREAD

**Issue by ithiluath** [SolastaMods/SolastaUnfinishedBusiness#3828]
This time the message was different than usual and said to send this info to you guys.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12138075/Player.log)
running UB 1.5.94.1 and latest solasta release.

**Comment by ithiluath** [comment]
found this as well
[Player-prev.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12138091/Player-prev.log)

**Comment by ThyWoof** [comment]
This seems to be related with the power to identify items after rest. Please disable that meanwhile.

@EnderWiggin , check this:

```
Uploading Crash Report
Exception: [Tactical - Invisible for players] Cannot reconcile RulesetEffect PowerAfterRestIdentify.
```

**Comment by geolas94** [comment]
i get the instability warning message in the main menu, directly when i start the game. the only bug i have encountered so far is that sometimes the save/load buttons grey out.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12185006/Player.log)

**Comment by ThyWoof** [comment]
Open your log, search for exception when loading, and delete all malformed heroes in your heroes pool.
