### ISSUE TITLE
Spells using the wrong ability scores

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#3831]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/a7bb3867-35fa-461a-9b42-d4e761f785ef)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135241209/c237f12c-177c-4f8c-8195-f5d7e1049c6c)

My cleric (Varaike) cast Protect Threshold as a cleric spell, yet it appears to be using her Intelligence for the save DC instead of Wisdom for some reason.

Similarly, my Inventor (Alfonsel) is trying to use Sanctuary as an inventor spell, but it appears to be using wisdom to calculate the DC rather than Intelligence as it should.

Neither character is multiclassed or has spells from any other source than their class spell list.
I don't know if other spells are affected, but I'll report back if I notice any more.

Alfonsel was respec'd at one point from a character named Parrick, so forgive the mismatched filenames.

[bug report.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12138834/bug.report.zip)

**Comment by miridistress** [comment]
Small update: The Protect Threshold bug appears only to happen when Protect Threshold is cast as a ritual.

**Comment by ThyWoof** [comment]
Does it happen with any other ritual vanilla spell?

**Comment by miridistress** [comment]
Are there any other ritual spells in the game with saving throws or attack rolls associated with them? I can't think of any.

**Comment by ThyWoof** [comment]
There isn’t much I can do here as this is a vanilla limitation. Will remove ritual to avoid any confusion.

**Comment by miridistress** [comment]
> There isn’t much I can do here as this is a vanilla limitation. Will remove ritual to avoid any confusion.

A workaround that would let you keep it as a ritual might be to lower the damage a bit and remove the saving throw so that creatures simply take a set amount of damage when they cross, rather than saving to halve it.
