### ISSUE TITLE
Not able to use Sunlit blade cantrip with reach weapon such as Polearms at 1 space away

### ISSUE THREAD

**Issue by gutenhuu** [SolastaMods/SolastaUnfinishedBusiness#3832]
The title is self-explanatory; Thanks for all the hard work folks; Really appreciate the mod. Attached a save for reference.

[AutoSave_9.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12138969/AutoSave_9.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/2766209f-0fcb-4eb1-a042-7922643b4091)

**Comment by gutenhuu** [comment]
@ThyWoof you used the cantrip on an adjacent enemy. When you try to use it one space away the cantrip says the target is out of reach (even though the long mace has the range to attack. This was possible on previous version of the mod)

**Comment by ThyWoof** [comment]
I know. Wrong screenshot
