### ISSUE TITLE
Moonbeam vanishes after wild shaping; It retains concentration but the spell itself vanishes.

### ISSUE THREAD

**Issue by gutenhuu** [SolastaMods/SolastaUnfinishedBusiness#3833]
The title is self-explanatory; Thanks for all the hard work folks; Really appreciate the mod. Attached a save for reference.

[AutoSave_9.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12138981/AutoSave_9.zip)

**Comment by ThyWoof** [comment]
@EnderWiggin , moonbeam adds a special action. Wondering if we need to copy over this particular condition.

**Comment by Kranay** [comment]
It's not just moonbeam actually.
What I have noticed is, when you cast Daylight and then take a wildshape, despite Daylight not requiring concentration, the effect vanishes as well.
Here is the save if you need one.

[ongoing_effects_wildshape_bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12165890/ongoing_effects_wildshape_bug.zip)

**Comment by Kranay** [comment]
Tested it with the mod disabled, still the same. Seems like a vanilla bug.

**Comment by ThyWoof** [comment]
Closing as nothing we can do at the moment. Will revisit once we start tackling wildshape Multiclassed.
