### ISSUE TITLE
Inventor infusion stacks with existing item bonus

### ISSUE THREAD

**Issue by JMavrelos** [SolastaMods/SolastaUnfinishedBusiness#3834]
this also happens with enhance defense,
e.g.
if you have a +2 item (weapon/shields/armor) and infuse it as a level 10 inventor, it becomes a +4

**Comment by EnderWiggin** [comment]
This is a known limitation/issue at the moment. Will try to make it use higher of the bonuses when have time.

**Comment by ThyWoof** [comment]
won't fix.
