### ISSUE TITLE
Save DC calculated incorrectly. 

### ISSUE THREAD

**Issue by Lyondes776** [SolastaMods/SolastaUnfinishedBusiness#3838]
When using the mods custom subclasses for fighter and paladin the save DC for the subclass abilities is stuck at 14. Despite the calculations for those DCs resulting in them needing to be higher. 
For the fighter the tactians gambit DC is supposed to equal 8+prof+str/dex/int (whichever is highest). The profiency bonus for the character is 6, and the characters strength mod is 6 as well thanks to a magic tome. So the DC should be 20, but is instead 14. 
The same is happening for the channel divinity save DCs for the mods paladin oaths. 
Doing palace of ice, 4 person party, worked fine until today

**Comment by ThyWoof** [comment]
Care to share a save and the mod version ?

**Comment by ThyWoof** [comment]
Fixed in dev
