### ISSUE TITLE
Ethereal Knell tooltip displays incorrectly and cannot be cast

### ISSUE THREAD

**Issue by Anabad** [SolastaMods/SolastaUnfinishedBusiness#3841]
When hovering over the "Ethereal Knell" cantrip the tooltip appears in the bottom left rather than above the spell and is overlayed with text from other tooltips. 

![solasta_bug](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/17071292/1d42c2d4-79b7-4ac5-989d-d060726cefc8)

When the spell is clicked the targetting pointer does not appear, and nothing seems to happen. I have attached the player log in case it contains relevant info.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12141829/Player.log)

**Comment by ThyWoof** [comment]
fixed in DEV.

**Comment by Anabad** [comment]
Damn that was fast! Thanks!
