### ISSUE TITLE
Missing FeatAdeptMetamagicQuickenedSpell 

### ISSUE THREAD

**Issue by Mormagill** [SolastaMods/SolastaUnfinishedBusiness#3842]
I tried continuing on my runthrough of the main campaign after a half a year or so Hiatus. Downloaded the latest version of the game and the Unfinished business mod.

Git failure when starting:
Exception: [Tactical - Invisible for players] Impossible to find item FeatAdeptMetamagicQuickenedSpell - 6ba9b4ac-5630-54b0-9d4b-29e6025eaaa8 in database.

I activated all the feats in the mod. Any suggestions?

**Comment by ThyWoof** [comment]
You need to delete all your saves and heroes to start clean. A lot has changed in the mod.
