### ISSUE TITLE
Fencer and Soul Blade Warlock Longsword interaction

### ISSUE THREAD

**Issue by Goosetipher** [SolastaMods/SolastaUnfinishedBusiness#3843]
Game 1.5.94
Mod 1.5.94 and .1

I noticed this a couple of days ago and checked it again with the new version. When a soul blade warlock with fencer is granted their bonus attack, that attack appears to not benefit from Charisma to roll/damage. I observed this with longswords: a +1, a +2, and frostburn. Curiously, it appears to work just fine with Shadow Blade.

**Comment by ThyWoof** [comment]
Do you have a save?

**Comment by ThyWoof** [comment]
no need. Soulblade is explicitly excluding CHA attribute on bonus attacks. It's written like this as we interpreted the rules. Asking others to confirm if we should filter out bonus or not.

**Comment by ThyWoof** [comment]
Remembered now what we did. We only allow the bonus to offhand if you have Two Weapon FS. By design.

**Comment by Goosetipher** [comment]
Thank you. Apologies for wasting y'all's time

**Comment by Goosetipher** [comment]
Suppose that means that Shadow Blade interaction is bugged, though? It does
appear to apply the cha bonus to the bonus action attack from fencer.

**Comment by ThyWoof** [comment]
Ended up adding an exception for fencer. On next release

**Comment by Goosetipher** [comment]
Thank you for the update.
