### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Lord-Camembert** [SolastaMods/SolastaUnfinishedBusiness#3844]
Hi,

UB displayed an instability warning on a random encounter map and asked me to share my Player.log and save file. You can find them in attachment.

My CotM 3 is the last save prior to the message.
My CotM clvl 4 is the first save following it.

[CotM.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12146070/CotM.zip)

Let me know if you need more data or info.

Regards,
- Cam

**Comment by ThyWoof** [comment]
fixed in DEV. Thanks
