### ISSUE TITLE
Updated UB and can't start my game.

### ISSUE THREAD

**Issue by DehVader** [SolastaMods/SolastaUnfinishedBusiness#3849]
Hi fellas.
I'm playing the new dlc and, after updating my UB to 1.5.94.3, my game does not load anymore.
![failed to load](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/140473936/7ae0fb09-7be3-47e7-91e0-6a4120f2368a)
Game version is 1.5.46.
to be fair, there was a message saying there may some instability issues, for like, 4 or 5 of those UB updates.
If i take the mods off( UB and Always Alt), then i can enter the game, but all i can load are my old saves, and no PoI saves.
I was kinda far in the campaign, and felling bad for loosing my save. My Solasta also is an "unofficial" version, so, stuck in this version.
Really apreciate any help i can get, i'm farly unfamiliar with this.
Thx.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12156903/Player.log)
[https://drive.google.com/file/d/1MkpBsoxb29pjyrXEsPeVX8dIIkh_nUmV/view?usp=sharing](url)

**Comment by ThyWoof** [comment]
Update your game to latest version.
