### ISSUE TITLE
[1.5.94.4] Circle of the Eternal Grove Bug

### ISSUE THREAD

**Issue by Kranay** [SolastaMods/SolastaUnfinishedBusiness#3856]
There is an issue with Verdancy and Seed of Life conditions on a druid.
Off the battle both of them works just fine, however during the battle their effects work only on other allies.
When a druid apply either of them on himself, as soon as his turn begins, nothing happens. The round count just keeps going on the effect tooltips, but they just hang there even when the count comes to zero. And if the battle ends, all the remaining counts (if they were above zero) finally take effect.

Here is the save just prior the druid turn.

[eternal_grove_druid_bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12170297/eternal_grove_druid_bug.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/2be9d8e3-b2be-4039-942f-d63da5995928)
I cannot open your save. It tells me you should had respeced at some point and this is a consequence of that.

**Comment by Kranay** [comment]
That doesn't seem to be the case, as I reproduced the bug.
Here is the save from the very start of POI campaign, I made a new druid from scratch.

[eternal_grove_druid_bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12190991/eternal_grove_druid_bug.zip)
