### ISSUE TITLE
Korean font issue

### ISSUE THREAD

**Issue by akintos** [SolastaMods/SolastaUnfinishedBusiness#3857]
current font assetbundle `KoreanHanSans.unity3d` lacks essential glyphs to properly display Korean translaiton.

since you already have proper [KoreanCharCode.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaFontAtlas/Assets/KoreanCharCode.txt) and Korean SDF font assets, i think you should rebuild the font assetbundle.

the glyph `셋` is already in the `KoreanCharCode.txt` and [NotoSansKR-Regular SDF.asset](https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaFontAtlas/Assets/NotoSansKR-Regular%20SDF.asset) file but not in the `KoreanHanSans.unity3d` shipped with the mod.

**Comment by ThyWoof** [comment]
I'm using the same unity3d asset here: https://github.com/team-waldo/SolastaKoreanMod/blob/master/SolastaKoreanMod/sourcehansans.unity3d

I haven't built that myself as not much knowledge on how to do that.

**Comment by akintos** [comment]
[sourcehansans.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12180976/sourcehansans.zip)

Sorry, that one is super outdated. please use this one.
