### ISSUE TITLE
[1.5.94.4] Elemental Adept [Fire] doesn't apply to Flaming Sphere

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#3862]
This seems like one that can't be fixed or might be intended, but Flaming sphere doesn't reroll 1's for its fire damage, either when its owner tells it to attack with a bonus action, or when a creature just stands in it for too long.

![sphere](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/20961335/d60e74b1-57c9-41a0-a43d-88fa22c93ce7)

[Spheres.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12172685/Spheres.zip)

[Save is from this campaign.](https://steamcommunity.com/sharedfiles/filedetails/?id=2983894647)

**Comment by ThyWoof** [comment]
This is a game engine limitation on recurring effects. Won’t be fixed.
