### ISSUE TITLE
[1.5.94.4] Circle of the Forest Guardian Druid - Level 6 power War Magic is nonfunctional

### ISSUE THREAD

**Issue by KKDavion** [SolastaMods/SolastaUnfinishedBusiness#3863]
- Version: 1.5.94.4
- Other Mods: None
- Short Description: The power "War Magic" which provides an attack as a bonus action whenever a spell or cantrip is cast is nonfunctional. Attempting to use a cantrip (such as sunlit blade) or a spell (such as fog cloud) in the provided save doesn't then grant the option to make an attack as a bonus action.
- Potential Solutions: One would be to make the power function as the text describes. However, I would suggest standardizing the abilities given out by the mod. For example, Arcane Fighter & Bladesinger wizards get the power "Cantrip Attack" which allows for an extra attack to be replaced by a cantrip. This I've tested to function in another game, & would be an equivalent ability to replace "War Magic" with.
- Steps to Reproduce: Create a level 6 Circle of the Forest Guardian Druid & attempt to make an attack as a bonus action after casting a spell or cantrip.
[Saves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12175884/Saves.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/76854f5c-e3e7-45d5-a4fb-cb7b470b5ade)
Cannot reproduce with your save. Casted a cantrip and got my bonus attack.

**Comment by KKDavion** [comment]
Unsure what the discrepancies between our builds are, as I continue to have this issue. Gif (mp4 :/) attached below providing a short reproduction of the issue. Redownloading the public build, reverifying Solasta, & trying on a different machine with the same save shows the same issue. Would appreciate advice on what could be wrong.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/32150450/e43bc1c6-9165-43f3-b882-f369d41c61c9
