### ISSUE TITLE
Inventor: Grenadier new recharge feature not working correctly

### ISSUE THREAD

**Issue by VessValyren** [SolastaMods/SolastaUnfinishedBusiness#3865]
The ability is called Refund Alchemy Charge, it lets you pick level 1 to level 5 spell slots to sacrifice for equivalent alchemy charges.  

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/136754388/6a6ffd50-094d-43b1-bac8-03d1cd838c9a)

I used it in a fight and got the charges, but then was unable to use it again.  

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/136754388/013f5903-12bd-4709-a888-4bdc39eb0643)

It shows up when out of combat.  I did a long rest and it still would not allow me to use it in combat again.

[Grenadier Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12178271/Grenadier.Save.zip)

Steps to recreate:

1. Use some charges of your bombs, in combat use the bonus action to recharge.  
2. Next turn bonus action option to recharge is missing, spend more charges and still each turn after its gone.

Leave combat, it reappears.  Short Rest/ Long Rest still shows out of combat but never comes back once in Combat.

**Comment by ThyWoof** [comment]
fixed in dev.
