### ISSUE TITLE
Game Warning! - Solasta has detected an instability

### ISSUE THREAD

**Issue by Austanza** [SolastaMods/SolastaUnfinishedBusiness#3866]
Hello, I'm not very skilled in coding and I'm not sure what the issue was, but I was asked to place a report here with some documents

At first, I ran into an issue where I was unable to save/load the game, but restarting it solved the problem, but it's come up again

Please let me know if I'm missing something or need to provide anything else, and thank you!

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12180091/Player.log)

**Comment by ThyWoof** [comment]
Try Respec your arcane archer.
