### ISSUE TITLE
Multiplayer Instability

### ISSUE THREAD

**Issue by encursion90** [SolastaMods/SolastaUnfinishedBusiness#3868]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12184220/Player.log)

A party of 4 attempted to load a previous save, and we were presented a mod instability warning, that said for all players to relaunch Solasta, and report the bug. We relaunched and the error repeated. We ignored it and played anyway, but there were weird glitches like desyncs, and loss of character control.

**Comment by ThyWoof** [comment]
Unfortunately this log doesn’t have any error message.
