### ISSUE TITLE
Dispel Evil and Good. Freeeeze

### ISSUE THREAD

**Issue by night2876** [SolastaMods/SolastaUnfinishedBusiness#3873]
I found this bug ... i know you don't produce other patch but this is blocking - When you cast dispell evil and good and use the dismissal action to an undead the game freeze ....
[Mauro_-_Winter.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12196212/Mauro_-_Winter.zip)

**Comment by ThyWoof** [comment]
It only happens with hirelings so avoid this spell or power with them.
