### ISSUE TITLE
Fast aim doesnt seem to reset

### ISSUE THREAD

**Issue by Pop000100** [SolastaMods/SolastaUnfinishedBusiness#3876]
I was only able to use marksmen's fast aim once. still only get to attack 2 twice instead of twice and a bonus action.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/cec9e9c8-37f6-4400-8770-6fedddca04e0)
we don't touch fast aim at all in the mod. only provide translations for it. it's a vanilla bug.
