### ISSUE TITLE
Reckless Attack doesn't provide advantage with monk/barbarian multiclass.

### ISSUE THREAD

**Issue by Zanthras9** [SolastaMods/SolastaUnfinishedBusiness#3885]
I currently have a monk 9/barbarian 3 character. Whenever reckless attack is selected, the character does not receive advantage on their attack. The save file is attached to the zip. It is entirely possible I am missing a rule somewhere, but I can't figure it out. The ztech.zip file is my xml settings for UB. I am using version 1.5.94.5
[.Reckless Not Work.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12208343/Reckless.Not.Work.zip)
[ztech.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12208345/ztech.zip)

**Comment by EnderWiggin** [comment]
Reckless Attack gives advantage to attacks that use STR. Your monk/barb has 20 in both. Monks use DEX for attacks if it is better or same as STR. So in this case advantage is not granted.

**Comment by Zanthras9** [comment]
That makes sense. Thanks for the help.
