### ISSUE TITLE
Eldritch Smite Soft Locks on Gargantuan Creatures

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#3886]
Solasta Version: 1.5.94
UB Version: 1.5.94.4
Description: When using Eldritch Smite on a gargantuan creature, game soft locks.

Reproduce: Have Eldritch Smite, hit gargantuan creature, use Eldritch Smite, Game soft locks.
Expected: Damage from attack, damage from Eldritch Smite, damage from other sources, enemy NOT knocked prone.

Save File:
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12208450/AutoSave_1.zip)

Character in question has both Smite and Eldritch Smite is the first one to go in initiative. Tested with basic warlock on other various gargantuan creatures. Still does not work correctly on those either.

Note: Eldritch Smite works as expected on Huge or smaller creatures immune to the prone condition.

**Comment by Pikachar2** [comment]
If whoever is working on it has questions, go ahead and ping/@ me on discord (Pikachar) and i'll try to do what I can to answer anything.

**Comment by EnderWiggin** [comment]
BTW, that save file throws multiple errors on load and correct character was _last_ to act.

**Comment by Pikachar2** [comment]
Good to know. That autosave had my initiative in a different order than everyone else I was playing with, and it sounds like you got their initiative order. I should probably just do a reinstall of both the mod and the game just to get a clean slate then.
