### ISSUE TITLE
Spirit animal Eyebite instantly ends without a test.

### ISSUE THREAD

**Issue by LizDragoness** [SolastaMods/SolastaUnfinishedBusiness#3888]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/123353916/e1702455-0955-4831-b142-e46e6667d695)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/123353916/43da1328-bc00-41a2-a2e7-0d6e15982fae)

The Wizard spell version works normally, but the status effect for the animal ability ends as soon as you have cast it, without any checks.

**Comment by LizDragoness** [comment]
[A.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12215464/A.zip)
because I got reminded about this in my other bug report, a save with the party, so far, the eyebite instantly ends on both the wolf and the eagle, haven't tried the bear yet, but expect the same.

**Comment by ThyWoof** [comment]
fixed
