### ISSUE TITLE
Inventor: Vitriolist charges

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#3890]
Using latest Solasta and UB mod version.

Started a new game, party has a Vitriolist Inventor.
Problem 1: Description doesn't say anything about how many charges i have on my Vitriolic Mixture feature.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/116584266/0169f755-c592-485a-a107-63199fe066e2)

Problem 2: Charges aren't indicated on the power tab. I keep on using them and the option just suddenly disappears after some uses, suggestion it has a limited number of uses.

Save file here:
[domino2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12210001/domino2.zip)

**Comment by VessValyren** [comment]
Sorry its Int Mod + PB per long rest.  If you mouse over each individual Mixture youll see the uses.  But mousing over the main Mixture button that lets you pick a mixture doesnt show it right now.
