### ISSUE TITLE
Instability warning and game lockup when entering Fortress of the Shield.

### ISSUE THREAD

**Issue by Lord-Camembert** [SolastaMods/SolastaUnfinishedBusiness#3891]
Hi,

As per the subject. Attached are the player.log and the save file right before the issue. Hopefully it's something you can fix. Thank you for your work!

[CotM 3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12210027/CotM.3.zip)

- Cam

**Comment by ThyWoof** [comment]
Something related to daylight. Try removing this effect with a rest before trying to enter this location.
