### ISSUE TITLE
Physical perfection blocks Unbrekable body over 50% health

### ISSUE THREAD

**Issue by LizDragoness** [SolastaMods/SolastaUnfinishedBusiness#3895]
My way of survival monk regenerates 0 HP on the start of her turn, saying she's over full health and over half health, at 116/156
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/123353916/dfbd1e52-ae0d-44da-8a30-7d43a99b4c05)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/123353916/40512768-7f64-4394-bb2f-f4a43e3709d3)

**Comment by HiddenHax** [comment]
Please post a save containing that character. Makes it easier for devs to fix bugs.

**Comment by LizDragoness** [comment]
[A.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12215397/A.zip)
Apologies, a save with the relevant party, to replicate the bug, take a hit as the monk in combat, it should not regenerate any health on the start of her turn.

**Comment by ThyWoof** [comment]
won't fix.
