### ISSUE TITLE
Instability Warning at Launch of Game

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#3896]
Getting an instability warning that says I should provide my player.log and save file. There is no save file, cause I'm not currently playing any campaigns. I'm building one. So I have attached a copy of the player.log and hope that helps. 
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12217578/Player.log)

**Comment by ThyWoof** [comment]
You have some invalid heroes in your pool. Search log for “exception” to find out which hero files you should delete.

**Comment by TragicSeriously** [comment]
Alright. Thank you.

**Comment by TragicSeriously** [comment]
This did not resolve the issue and the player.log remains the same after deleting the two .chr files for the characters referenced in the log. I'm seeing a bunch of missing translations in the log? I don't code so I may be way off, but it seems like there is something going on there?
