### ISSUE TITLE
Barbarian Clothes do not provide any AC bonuses.

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#3897]
I tried all of them, just the barbarian clothes however. I have not tried other classes such as the Monk, Druid, Warlock or Wizard. (Am I forgetting one? Idk...) Just wanted to point it out. Nothing major.

**Comment by HiddenHax** [comment]
Not sure if I'm missing the point, but Barbarian Clothes aren't supposed to grant any additional AC. They are just regular clothes that grant usual AC of 10 + DEX (or 10 + DEX + CON if Barbarian).

**Comment by TragicSeriously** [comment]
Then you have the set that do provide bonuses. Barbarian Clothes of Survival should grant +2 AC and +2 to Saves. No AC is given.

**Comment by ThyWoof** [comment]
Barbarian clothes won’t stack with other AC improvements like unarmed defense. Honesty they are meaningless. Not a bug but by design.
