### ISSUE TITLE
Still getting the Instability Warning at Launch

### ISSUE THREAD

**Issue by TragicSeriously** [SolastaMods/SolastaUnfinishedBusiness#3899]
You have some invalid heroes in your pool. Search log for “exception” to find out which hero files you should delete.

_Originally posted by @ThyWoof in https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/3896#issuecomment-
1659263125_

**Comment by TragicSeriously** [comment]
Sorry but this did not resolve the issue. Characters files deleted and it changed nothing. Log remains the same. 
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12222787/Player.log)

**Comment by TragicSeriously** [comment]
Update**I stopped Steam from replacing the deleted .chr files and that does resolve the exceptions for those characters. Still seeing some stuff in the log, but I'm unsure if these are to be expected or if there is still an issue going on?
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12222831/Player.log)

**Comment by ThyWoof** [comment]
These messages are normal.
