### ISSUE TITLE
Eldritch Step Distance

### ISSUE THREAD

**Issue by Goosetipher** [SolastaMods/SolastaUnfinishedBusiness#3900]
Game 1.5.94
UB: 1.5.94.5

It appears as though the eldritch invocation Eldritch Step allows for a 20-25 foot teleport. 25 (5 cells) if travelling in on the x/y axis, 20 if deviating therefrom.

[Eldritch Step teleports 20.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12223743/Eldritch.Step.teleports.20.zip)

**Comment by ThyWoof** [comment]
There isn’t much we can do on how game calculates distance. Won’t fix.

**Comment by Goosetipher** [comment]
To be clear, I'm not quibbling about the fluctuation in distance, I get that is just a bit funky. The description for the ability says 30 ft, so I figured it should be 30 ft in a straight line instead of 25. I looked back at my comment and it never mentioned the description - my bad.
