### ISSUE TITLE
Bladedancer lvl 10 ability description missing on reaction prompt text - English

### ISSUE THREAD

**Issue by Goosetipher** [SolastaMods/SolastaUnfinishedBusiness#3901]
1.5.94
1.5.94.5

![missing description](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/140292398/1161cdca-f85d-41b0-a331-73615bc57638)

**Comment by ThyWoof** [comment]
Please share a save.

**Comment by Goosetipher** [comment]
[to test damage reax.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12234962/to.test.damage.reax.zip)

It appears that the reaction prompt won't be offered at all if the attack is shieldable. I tried to test it again by passing on a shield spell prompt, but it did not then give me an option to mitigate the damage. Makes sense, since shield would fully mitigate at the lowest cause, but I thought I would mention it for testing purposes.

I've only had the option pop up to mitigate aoe damage.

**Comment by ThyWoof** [comment]
fixed.
