### ISSUE TITLE
Error and I can't save

### ISSUE THREAD

**Issue by Mavroz** [SolastaMods/SolastaUnfinishedBusiness#3904]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12235145/Player.log)
Hi, I'm not sure what's going on but Solasta gives me an error with the mod and won't let me save or load until I exit the game and re-enter.
Which is kind of annoying to me because I'm playing in iron mode.
I had never thrown any errors.
I attached the player.log that the error says has the information, I think.
Sorry if I didn't understand well, English is not my native language.

**Comment by ThyWoof** [comment]
Can I also have the save? I speak Spanish, Portuguese and Italian if you prefer any other language.

**Comment by Mavroz** [comment]
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12240255/Save.zip)
Ahí esta el ultimo autosave. El error sale siempre que cambio de mapa. No se que puede ser porque casi siempre uso la misma configuración.

**Comment by ThyWoof** [comment]
Unfortunately cannot reproduce. Try RESPEC'ing your bard.
