### ISSUE TITLE
Instability warning when entering maps

### ISSUE THREAD

**Issue by geolas94** [SolastaMods/SolastaUnfinishedBusiness#3906]
i fairly commonly get the instability warning when entering a new map. player log says the error has to do with the identify on rest ability. i can confirm that this last warning came on entering a map after identifiying on rest before traveling via worldmap. i will check if it happens every time i enter a map after using rest identify.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12239904/Player.log)

**Comment by ThyWoof** [comment]
That’s key info, thanks. Can I also have the save pls?

**Comment by EnderWiggin** [comment]
were you using identify while resting in location, or while travelling on a global map?

**Comment by HIEROT** [comment]
instablilities in recent seem to have the same origin.  the player log says different ruleseteffect cannot be reconciled and throws serialization exceptions

**Comment by geolas94** [comment]
[AutoSave_5.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12249303/AutoSave_5.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12249305/Player.log)
here is the auto save and corresponding log.
i was rest identifiying in a previous location, then entered the world map, and the error occurs upon entering a location from the world map.

**Comment by ThyWoof** [comment]
Is this an Ironman or multiplayer campaign?

**Comment by Csatadi** [comment]
It appears in non-ironman single player for sure. And it's quite common.

**Comment by geolas94** [comment]
> Is this an Ironman or multiplayer campaign?

non-ironman singleplayer

**Comment by ThyWoof** [comment]
cannot consistently reproduce.
