### ISSUE TITLE
Warcaster substituted cantrips used with sentinel do not trigger movement speed reduction.

### ISSUE THREAD

**Issue by Castone22** [SolastaMods/SolastaUnfinishedBusiness#3908]
Base Character Build:
Soul blade warlock, dip into fighter for bonus feats and polearm master fighting style, take sentinel feat and warcaster feat, use any type of polearm as a weapon.

Expected Behavior: Enemy gets within 2 of you, you get an opportunity attack from polearm master, and can substitute eldritch blast as a reaction. Enemy gets knocked back per connecting eldritch blast, and gets locked in place by sentinel since they were hit by an opportunity attack.

Actual Behavior: Enemy gets within 2 of you, you get an opportunity attack from polearm master and can substitute and eldritch blast as a reaction.  Enemy gets knocked back per connecting eldritch blast, then sentinel movement lock does not trigger.

**Comment by ThyWoof** [comment]
won't fix.
