### ISSUE TITLE
Instability after leveling up

### ISSUE THREAD

**Issue by AviRubinoff** [SolastaMods/SolastaUnfinishedBusiness#3916]
After completing the level up process, I got a popup saying the game had detected an instability and asked that I share the logs and save file with the Unfinished Business community. I think this is the right place to do that; if not, let me know where is. I did notice that after the instability message appeared, the game could no longer make saves.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12286522/Player.log)
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12286524/AutoSave_1.zip)

**Comment by HIEROT** [comment]
another power after rest identify

**Comment by ThyWoof** [comment]
avoid using PowerAfterRestIdentify for now. Unfortunately cannot reproduce at all.
