### ISSUE TITLE
Acidic Hand Crossbow not working properly

### ISSUE THREAD

**Issue by ghostscript3r** [SolastaMods/SolastaUnfinishedBusiness#3917]
Acidic Hand Crossbow always does 1d6 damage instead of 1d6 + 1d8. Tryed with normal bolts or magic ones and tried with or without bonus damage feats.

I'm using Solasta 1.5.94 and UB 1.5.94.5 - no other mod

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/aa42eef0-33d6-469b-9934-d600b4f76ebd)

everything is right with hand crossbows.
