### ISSUE TITLE
Instability warning during battle

### ISSUE THREAD

**Issue by geolas94** [SolastaMods/SolastaUnfinishedBusiness#3919]
i got a instability warning after missing with one of two beams from the new eldritch surge warlock, the ability to add STR to dmg was active.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12300585/Player.log)
do you want me to upload the save? its from the against the giant custom campaign.

**Comment by ThyWoof** [comment]
@HIEROT

**Comment by HIEROT** [comment]
will inspect this but currently busy _(:з」∠)_

**Comment by ThyWoof** [comment]
@HIEROT , any chances we could fix this one?

**Comment by HIEROT** [comment]
@ThyWoof Maybe this weekend. I have my system reinstalled and the develop env is well gone.

**Comment by HIEROT** [comment]
@ThyWoof  Tested and assume it's caused by not enough reserving points after attack, but it I cannot reproduce the bug. My invocation is correctly toggled off without errors.

**Comment by ThyWoof** [comment]
What could lead to that? Anything you could do to avoid the exception?

**Comment by HIEROT** [comment]
@ThyWoof  The function where the exception is throwed only has two lines:
'''csharp
		this.activeGroup.gameObject.SetActive(this.Invocation.IsPermanent() && this.Invocation.Active);
		this.inactiveGroup.gameObject.SetActive(this.Invocation.IsPermanent() && !this.Invocation.Active);
'''
I assume activeGroup and inactiveGroup are invalid hence the exception. It might has something to do with serialization bugs as they are SerializeField, or it has something to do with other parts of the mod which I didn't enabled and are meddling with the action bar and make it invalid at the time of OnActionExecutionHandled.

**Comment by ThyWoof** [comment]
I recently fixed a serialization issue. Will assume it also fixed this bug. Will close for now.
