### ISSUE TITLE
Instability: Cannot reconcile RulesetEffect PowerMartialArcaneArcherBurstingArrow

### ISSUE THREAD

**Issue by scalen121** [SolastaMods/SolastaUnfinishedBusiness#3920]
Hit after getting the arcane archer feat, activating it, and saving. I have a save before activating it that seems to be ok

[AutoSave_1.sav.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12309323/AutoSave_1.sav.txt)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12309324/Player.log)

**Comment by ThyWoof** [comment]
cannot consistently reproduce.
