### ISSUE TITLE
Instability Issue - 2x

### ISSUE THREAD

**Issue by Charrua13** [SolastaMods/SolastaUnfinishedBusiness#3922]
Solasta version: 1.5.94

Mod version 1.5.94.6

No other mods installed

When: in battle and just after battle. 
What: "Solasta has detected an instability. Please ask every player to close the game, grab the file <file name> and share these logs and stave file. 

How to reproduce - It didn't reliably reproduce, at some point in game play the system would bug, everything would load slowly, and then I got the message. Specifically, the game would start lagging the animation at some points (particularly when enemies roll). It wasn't associated with any particular character as far as I'm aware. 

[Player-prev.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12326310/Player-prev.log)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12326311/Player.log)
[My most recent save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12326315/My.most.recent.save.zip)

**Comment by ThyWoof** [comment]
fixed
