### ISSUE TITLE
Instability Warning when opening game still

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#3928]
I'm getting the Instability warning when I load the game as well.  I know there was a previous "ticket" opened on it, and the suggestion was to delete the characters that pop up in the player.log file with "Exception when loading...".  For me, there are 5:

Exception when loading C:/Users/Phil/AppData/LocalLow/Tactical Adventures/Solasta\Characters\Cami.chr. System.Exception: An exception has been thrown during the deserialization of an element of type Snapshot (serialization type: Snapshot) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at RulesetCharacterHero+Snapshot.SerializeAttributes (IAttributesSerializer serializer, IVersionProvider versionProvider) [0x0019d] in <10624896cb4e451583b5b6d9ca571f3a>:0 
  at BinarySerializer.SerializeElement[T] (System.String elementName, T value, Serializer+SerializationOption serializationOptions) [0x001c8] in <10624896cb4e451583b5b6d9ca571f3a>:0 
   --- End of inner exception stack trace ---
  at BinarySerializer.SerializeElement[T] (System.String elementName, T value, Serializer+SerializationOption serializationOptions) [0x0045e] in <10624896cb4e451583b5b6d9ca571f3a>:0 
  at Serializer.SerializeElement[T] (System.String elementName, T value) [0x00000] in <10624896cb4e451583b5b6d9ca571f3a>:0 
  at CharacterPoolManager.EnumeratePool () [0x000ec] in <10624896cb4e451583b5b6d9ca571f3a>:0 . 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
Exception: [Tactical Invisible For Players] Impossible to load character.

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
CharacterPoolManager:EnumeratePool()
<AsyncCreateCharacterTemplates>d__12:MoveNext()
TA.Coroutine:Run()
RuntimeState_Booting:Update()
FiniteStateMachine:Update()
Runtime:Update()
RuntimeManager:Update()
 
(Filename:  Line: -1)

Cannot find element HalfElfVariant in database CharacterRaceDefinitionDatabase 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

The exact same thing is listed for the other 4 Characters: Dothan, Ilofared, Lila, and Ophelie.

The problem is that I delete the character files from the Character folder, but when I load the game, I get the same exceptions for the same 5 characters, and when I check the Character folder they are all showing again, but none of them are showing in-game (since they come up as "impossible to load character".  Close the game, delete the character files, reload the game, same exceptions showing and once again they're listed in the character list.

I've tried turning off the Half-Elf option on the mod and then deleting the characters, no change.

I've deleted every save file for every game except for my most recent play-through of CoTM (which I know doesn't have any of those characters) and then deleting the character files, no change.

Game always loads with the same instability warning for UB and telling me to send you the player.log file, which is attached.

As a matter of fact, I've added both the player.log and the player-prev.log file, just to show the lack of change from deleting the Character files causing the exception.

Alost forgot: Game is 1.5.94
UB 1.5.94.7

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12328568/UB.Bug.reports.zip)

**Comment by otearaisu** [comment]
disable steam sync save

**Comment by kosocku** [comment]
That did the job...kind of...
