### ISSUE TITLE
Instability warning and game crash when loading games

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#3930]
After correcting the previous instability issues by disabling the Steam syncing saves to it's cloud, I have a new one:

Now, when I try to load a saved file, my game crashes, giving the same instability warning and message about sending the player.log file.

Still 1.5.94 and 1.5.94.7

[UB Bug reports.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12329406/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
You have very old saves prior POI. They won’t work. Have to delete them as well.
