### ISSUE TITLE
Could not serialize attribute on save

### ISSUE THREAD

**Issue by tbabic** [SolastaMods/SolastaUnfinishedBusiness#3935]
When casting a longstrider on character and then saving and loading a game (in caer clyflen), I'm getting an error:
Could not serialize attribute on save. It looks like the attribute is empty/ null however, as it's not printed out.

![20230814150205_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/5815039/96a007f1-dc26-41ff-935d-3a4bf4213019)

**Comment by TyrasNistru** [comment]
Happening to me almost all the time after last update, but doesn't seem to be causing any other issue aside from the warning.

**Comment by ThyWoof** [comment]
Thanks for the confirmation. Will remove popup from fix.

**Comment by ThyWoof** [comment]
fixed in dev.
