### ISSUE TITLE
Wizard class level 16 - 2 ability score choice bug

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#3938]
Hi, latest version of mod .94.7. Just scrolling through and saw wizard get 2 ability score choice instead of 1 at level 16.
![IMG_3302](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/9156490/1fb252d5-9e13-4bdc-a881-fe472aa9a729)

**Comment by ThyWoof** [comment]
fixed.
