### ISSUE TITLE
Inventor Guardian Armor, Level 15 slow effect doesn't process save request properly. 

### ISSUE THREAD

**Issue by jsprunck** [SolastaMods/SolastaUnfinishedBusiness#3942]
As per the title, the Inventor Guardian Armor feature at Level 15 doesn't actually run the check on save vs slow - enemies always fail the save.   While nice for the player, I don't believe this is working as intended.

**Comment by ThyWoof** [comment]
Do you have a save we can use to debug?

**Comment by ThyWoof** [comment]
fixed in DEV
