### ISSUE TITLE
Instability Detected when loading save that has an active Guardian of Faith on the field.

### ISSUE THREAD

**Issue by TyrasNistru** [SolastaMods/SolastaUnfinishedBusiness#3943]
When I load my save (right after the battle on the bridge at the start of the Palace of Ice campaign), I got an instability warning. Seems like something wrong with the guardian of faith that I have summoned in the battle, that was still active when I saved.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12455249/Player.log)
[Save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12455275/Save.zip)

**Comment by ThyWoof** [comment]
Active effect GuardianOfFaith does not have valid entity implementation. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
Exception: [TACTICAL INVISIBLE FOR PLAYERS] Corrupted activeEffect tried to register (check logs).

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
GameLocationEnvironmentManager:RegisterGlobalActiveEffect(RulesetEffect, Boolean)
GameLocationEnvironmentManager:PostLoadCharacterActiveEffect(RulesetEffect)
GameLocationCharacter:PostLoadPostSectors_ActiveEffects()
GameLocationCharacterManager:PostLoadPostSectors()
GameLocation:PostLoad()
SessionState_LoadingSave:LocationPostLoading()
<LoadLocationAsync>d__152:MoveNext()
TA.Coroutine:Run()
GameLocationManager:Update()

**Comment by ThyWoof** [comment]
Not related to UB.
