### ISSUE TITLE
Action Switching Bar Causes Crashes

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#3945]
When 'Enable Action Switching Bar' is enabled, occasionally the game will crash or softlock. It's not particularly consistent.
This issue causes loading issues in multiplayer games and they can't sync correctly.

I don't have a test save for this, as my last one i just disabled it and continued on.

@Pikachar on UB discord channel if you have more questions.

**Comment by ThyWoof** [comment]
got a log we can check?
