### ISSUE TITLE
Lizzaria doesn't appear with mod

### ISSUE THREAD

**Issue by akorn** [SolastaMods/SolastaUnfinishedBusiness#3951]
I played a singleplayer campaign as well as a multiplayer game with the mod enabled and both times, Lizzaria didn't appear when she should have; the fight with the dark apprentices in the Bone Keep took place, but the dialogue with Lizzaria didn't trigger. (I only know where it should have triggered by watching YouTube videos.) One affected playthrough was with the Steam version, the other with GOG.

I have no idea whether this is a bug in the vanilla game or the mod, though; there were also other issues with this quest (the subtask "look for another way in" can be triggered by returning to the courtyard after confronting Mardracht and standing in front of the main gate, but there is no way to progress beyond this point save via the debug console; also, reentering the keep through one of the other wells again leads to faction attitude increases).

I don't plan a third playthrough, especially not without the otherwise wonderful mod, so I can't really promise more information; I'm submitting this report in the hope that it's helpful.

**Comment by ThyWoof** [comment]
We don't touch any campaign at all with the mod. Most likely a vanilla bug introduced in their last patch.
