### ISSUE TITLE
Lvl 7 Spellshield War Magic isn't working with some cantrips

### ISSUE THREAD

**Issue by Kazzius** [SolastaMods/SolastaUnfinishedBusiness#3959]
The Fighter spellshield's level 7 ability war magic says that after casting a spell or cantrip, that they can attack with their main weapon as a bonus action. After casting some cantrips I find that the war magic does activate and work correctly, but for some cantrips it doesn't activate at all.

I've tested it with the annoying bee, and the firebolt cantrip and it did work. When trying to use it with sunlit blade and resonating strike, war magic didn't activate and I couldn't use the bonus action to attack.

They are cantrips, so I assumed it should work, but is it specifically not supposed to work with the cantrips that include a weapon attack? In that case should it be listed in the description?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/9c049769-4850-47c7-8605-65ff02eb6b10)
fixed in DEV.
