### ISSUE TITLE
Forceblade Sorcerer and Distant Hand Monk not getting magical attacks

### ISSUE THREAD

**Issue by zeelok1** [SolastaMods/SolastaUnfinishedBusiness#3960]
Both of these classes have a feature that says their attacks should be considered magical for the purposes of overcoming resistances. But I'm not seeing that reflected in the inventory and their attacks are still being resisted by enemies such as the Skeleton Sorcerer who have resistance.

I also have a Blade Caller Rogue in my party and their daggers are properly counting as magical, both in the inventory and when attacking.

![forceblade](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/109606293/2c671390-944c-4d08-843e-354c5608f7d8) ![monk](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/109606293/1b7f700b-2477-4138-853b-dfeaff75eb9f)

Save: [bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12506747/bug.zip)

Versions: Solasta v1.5.94, mod v1.5.94.12

**Comment by ThyWoof** [comment]
fixed [here](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/e1169eab597d4b1759dcde3467aca2d3ccff45c6). Thanks.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/3f283a4e-cc63-4a05-8af5-9d0a9737900b)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/6f1ad72b-ef0e-4cae-b1bd-8a9c926f868d)
