### ISSUE TITLE
Thunder Paladin not getting full range with a +1 warhammer

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#3962]
Hello. My Thunder Paladin is 3rd level and has a +1 warhammer. It states that he should have a range on warhammer attacks of 20/60 but even at 15 range ( 3 squares) I'm getting disadvantage on my throws because it's considered a "long range attack".  Wonder if the code isn't recognizing it because it's a +1 warhammer? Please fix! Thanks!

**Comment by ThyWoof** [comment]
share your save.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5a00114e-a86a-48d1-8147-bf34e503740f)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/7f6e9899-d119-45f1-9d4f-6f66c558ca91)
added "thrown" tag to attack.

**Comment by Bawookles** [comment]
Hi, there!

So the problem was fixed and will be in a new UB update? Sorry I was late
on this, here's my save file if you still want it.

Thanks,
Brooks
