### ISSUE TITLE
Stone's Endurance not reducing damage by the right amount

### ISSUE THREAD

**Issue by zeelok1** [SolastaMods/SolastaUnfinishedBusiness#3965]
I have a character with Stone's Endurance from the Oligath race and it doesn't appear to be reducing the damage by the amount shown in the combat log. In this image it says it will reduce the damage by 13, but it only reduces by 9.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/109606293/19ee19c3-50a5-45d3-8786-2d2cbacea9be)

Save: [stoneendurancebug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12514549/stoneendurancebug.zip). Once it gets to the enemy turn the Orc Chieftain should attack the Barbarian and they still have a use of Stone's Endurance left.

Versions: Solasta v1.5.94, mod v1.5.94.12

**Comment by ThyWoof** [comment]
Not a bug. The enemy had a +4 bonus damage.
