### ISSUE TITLE
Furious Defense counters Danger Sense

### ISSUE THREAD

**Issue by Pop000100** [SolastaMods/SolastaUnfinishedBusiness#3968]
If STR save is more then 5 greater then DEX, then furious defense is statistically similar.
If it is smaller then Furious Defense will lower your odds.

It either needs to not trigger or give advantage to the relevant STR saves.

**Comment by MarinerEarendil** [comment]
Raging Barbarian should have advantage on all Strength saves, for character stats assuming +2 dex and eventually capping out at +5 strength  and+5 proficiency the save should go from +2 with advantage to +10 with advantage.
If Rage isn't giving advantage to Strength saves that is a bug.

**Comment by ThyWoof** [comment]
any DEX saving that is now converted to STR will be rolled with advantage. on next release.
