### ISSUE TITLE
Infinite loading with arcane fighter wizard in group

### ISSUE THREAD

**Issue by Hettikus** [SolastaMods/SolastaUnfinishedBusiness#3974]
I have an Arcane Fighter Wizard in my group. After the update when I try to load the save game it says one of the characters is corrupted and is stuck at loading.

**Comment by ThyWoof** [comment]
Please always read change log before an update. RESPEC was required before update on Arcane Fighter.

**Comment by Hettikus** [comment]
I'm sorry, does it mean i need to basically reset the char before i load the game? (i've read the changelog)
