### ISSUE TITLE
Game will auto-save but won't quick save

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#3977]
Hi, there. 

I don't know if this is a UB issue or not but I've suddenly gotten situations where the game won't allow me to quick save at all. The game will still autosave with a new map or combat. Don't know if one of my UB characters or races is causing the problem. 

I tried dragging in my .sav file into this window but it said the file type is not supported. 

Thanks,
Brooks

**Comment by ThyWoof** [comment]
Please always read change log before an update. RESPEC was required before update on some subs.

**Comment by Bawookles** [comment]
It was happening before the update and I don't have any subs that I was
told to RESPEC in the change log.
