### ISSUE TITLE
Thunder Paladin at disadvantage at 4 cells range with throwing hammer

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#3986]
Hi, there. 
I'm on the latest edition of UB at 1.5.94.13 but once again my Thunder Paladin is getting disadvantage with trying to throw his hammer at 4 cells (20 feet) range. I've tried with both his Lightbringer warhammer and a +1 warhammer and the result is the same. 

Thanks, 
Brooks

QuickSave_12.sav

**Comment by Bawookles** [comment]
Hmm, can't seem to save .sav file in this github window.

**Comment by HiddenHax** [comment]
Post the save in .zip folder please.

**Comment by Bawookles** [comment]
Here it is. Thanks.

**Comment by Bawookles** [comment]
[QuickSave_12.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12566991/QuickSave_12.sav.zip)

**Comment by ThyWoof** [comment]
distance 20 ft. no DIS:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c67ff2ab-18f3-42b1-95ea-abcf69637dd7)

distance 25 ft. DIS:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/7dc37343-a758-4ecb-9051-f3cc7dc31b45)

it works as expected.

**Comment by Bawookles** [comment]
That's not what I was getting in my game at all. There's something buggy
with the subclass. I was 4 squares away and I was getting disadvantage.

**Comment by ThyWoof** [comment]
Uninstall / reinstall mod. Only explanation is you aren’t using the latest mod version or somehow your DLL haven’t updated properly. This is the 2nd time I check this, first on my save, second on yours. This class works as supposed.

**Comment by Bawookles** [comment]
Okay. I think it's possible it is due to the option in UB: "Use official
distance calculation to be based on distance from one creature's cube to
another" in the Gameplay/Rules option.
