### ISSUE TITLE
"Corrupted" save

### ISSUE THREAD

**Issue by TheRedSojourner** [SolastaMods/SolastaUnfinishedBusiness#3998]
Attempting to load a .12 save file after updating to .13/.14 returns a message informing that the save is corrupted and can't be loaded (save can be safely loaded in .12 by using the rollback feature). The game must then be crashed to exit.

Please provide documentation on what to do in these situations and how to correctly update, or notify if we should not update at all.

**Comment by ThyWoof** [comment]
All changes are documented on change log which you can access from mod UI. Unfortunately there are some game breaking changes and we point them out with “RESPEC required on …” as very first entry on changelog.

You need to rollback to 12, can do that from mod UI as well but will need to rollback twice if at 14.

On 12 Respec off any subclasses that got highlighted as “need RESPEC”.

once so upgrade and RESPEC back to them.

**Comment by TheRedSojourner** [comment]
Understandable. Can we hope to see some improvements to the respec feature in the future, or to additive changes to avoid class-swapping shenanigans?
