### ISSUE TITLE
Blinded condition still allow AoO even with rule ticked on

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#4001]
Not sure if Undeads are not affected by Blind condition fully, but they definitely get disadvantage to attack (and I get advantage on attack against them). However, when moving out of range they still do AoO.

![20230912084304_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/9156490/04aa4aa4-7acb-48be-a4e0-57fcff958454)
![20230912084436_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/9156490/4c9816a0-5daa-40af-b576-2fd901d977e1)

**Comment by NathanNN** [comment]
[Palace of Ice.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12588433/Palace.of.Ice.zip)

**Comment by ThyWoof** [comment]
@HIEROT , who wrote this feature? I cannot remember, lol.

**Comment by EnderWiggin** [comment]
@NathanNN when this option was turned on? Before blinding the enemy or after? I see that is is supposed to modify Blind condition by adding shocked action affinity that _should_ prevent reactions, including AoO.

**Comment by EnderWiggin** [comment]
Also need a save in combat - provided save is not in one and I have no idea how to trigger combat you've been in.

**Comment by NathanNN** [comment]
I turned on that rule ever since I downloaded this mod a long time ago. The Blinded condition is not from a spell, but the Holy Aura spell effect of the Cleric so maybe that is why? The new Holy Aura spell from Palace of Ice said that anyone attack you that fail the saving throw would go Blind.

**Comment by ThyWoof** [comment]
That might be it. Will check these conditions hierarchy and if possible to validate parent instead.

**Comment by HIEROT** [comment]
@ThyWoof I didn't, but it shocks me to see that this setting adds shock effect to blinded lol.

**Comment by ThyWoof** [comment]
In reality game doesn’t have support for this but found out a similar behavior already implemented on mobile feat. Will give it a try.

**Comment by ThyWoof** [comment]
probably fixed but above save isn't in battle for easy testing.
