### ISSUE TITLE
Smith Cleric attack with Spiritual Weapon prevents turn from ending

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4002]
Don't know if this is just a problem with the Smith Cleric or with other clerics now. When I use my bonus action to attack with a spiritual weapon, after the attack, the Cleric's toolbar does not reappear so there's no way of ending the Cleric's turn, so the combat is just frozen there. I've tried using the keyboard commands "N" and "Return" to end the Cleric's turn and that doesn't work either. 

Save filed attached.
[Spiritual Weapon.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12593699/Spiritual.Weapon.sav.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/29113430-982c-4830-9737-0918284dc491)
tried twice with your save and couldn't reproduce. What's your game and mod versions? Care to share a player.log with the error next time it happens?

**Comment by Bawookles** [comment]
Solasta version is current. Mod is current version 94.14

How do I share the player.log and error? I'm on Mac stream version. Maybe
that has to do with it as the Mac version always has weird bugs. But I've
always used Spiritual Weapon before and never had this problem where the
cleric's turn just gets stuck.

Thanks.
