### ISSUE TITLE
Unable to level up Weaponsmith Inventor after lvl 11 due to screen cutoff

### ISSUE THREAD

**Issue by ZHSimon** [SolastaMods/SolastaUnfinishedBusiness#4008]
After a particularly grueling set of battles in which I exhausted pretty much every resource my Inventor had at his disposal, I was pleased to see that the party leveled up! I was _less_ pleased to see that the 'Level up' button was below the fold at 1920x1080 resolution, given how many things he was refreshing on a long rest. Would it be possible to add a scrollbar or something in cases like this?

![Can't level up](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3298651/d041507f-e753-480b-b7ff-2ceeb0713b23)

**Comment by ThyWoof** [comment]
There is an option under mod UI / interface to fix that. Cannot remember on top of my head but should be pretty obvious as mention level up.

**Comment by ThyWoof** [comment]
It’ll not display the pre level box on the step where you need to click the buttons.
