### ISSUE TITLE
Ranger Survivalist - Disabling Strike applying to self instead of target

### ISSUE THREAD

**Issue by VintageRed** [SolastaMods/SolastaUnfinishedBusiness#4011]
When my survivalist ranger attacks an enemy the disabling strike appears to be applying to himself rather then the enemy that he has hit.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/145232796/cd027f0b-107e-4642-b469-a865fdc04df9)

**Comment by ThyWoof** [comment]
already fixed on v15. thanks.

**Comment by VintageRed** [comment]
Thank you for the prompt response. I appreciate your work to support your mod users.
