### ISSUE TITLE
Battle cleric Decisive Strike

### ISSUE THREAD

**Issue by ninfaty** [SolastaMods/SolastaUnfinishedBusiness#4022]
The dmg type of the added die was bludgeoning when the weapon dmg die was piercing. This was with a light crossbow at lvl 4.

**Comment by ThyWoof** [comment]
Screenshots and save always help.

**Comment by ThyWoof** [comment]
Decisive strike is vanilla and there isn’t anything in desc that suggests it must use weapon damage. Not a bug.

**Comment by ninfaty** [comment]
I'll keep everything in mind next time. Thanks!
