### ISSUE TITLE
Audacity Bard using Whirl loses magical weapon property on damage

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4032]
Weird thing comes up when my Audacity Bard uses a "Whirl" option, her attack with a magical weapon loses the magical weapon tag and the damage resistant enemy (an Elemental in this example) shows that it is resistant to the slashing damage. When I make her second attack without the whirl, the enemy is not resistant to the slashing damage. 

Save files attached showing the before and after of the Whirl attack. 
[Audicity Bard.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12705833/Audicity.Bard.sav.zip)
[Audicity Bard 2.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12705834/Audicity.Bard.2.sav.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/9a173f1c-3fe2-4b20-ab79-95cd5dccc23a)
thanks. fixed in dev.

**Comment by ThyWoof** [comment]
also fixed all other similar problems with:

- Arcane Archer bursting area damage
- Booming Blade move damage
- College of Audacity whirl damage
- Guardian Aura HP swap damage
- Path of The Elements elemental conduit wildfire damage
- Quivering Palm damage
- Way of The Dragon reactive hide damage
