### ISSUE TITLE
Burning blade secondary damage 

### ISSUE THREAD

**Issue by chlorosadamas** [SolastaMods/SolastaUnfinishedBusiness#4033]
"flames leap to second target, dealing fire damage equal to your spellcasting ability modifier"

The secondary damage uses the int modifier as a sorcerer, warlock or cleric (with sorc/warlock magic initiate).
I think it's supposed use your charisma modifier for sorcerer and warlock.  

Solasta: 1.5.94
UB: 1.5.94.16
PS Thanks for the quick work on the Burning Blade fixes in the last patch

**Comment by ThyWoof** [comment]
Fixed in dev.

**Comment by ThyWoof** [comment]
Can you install https://github.com/SolastaMods/SolastaUnfinishedBusiness/discussions/4031 and confirm on your end?
