### ISSUE TITLE
Frequent Desyncs in Multiplayer + Stability Warning on Startup

### ISSUE THREAD

**Issue by doriantsai** [SolastaMods/SolastaUnfinishedBusiness#4035]
Hi SolastaMods, 

I'm currently playing a 6-character multiplayer setup in Palace of Ice and experience frequent desyncs during battle, usually seems to be from a triggered reaction (eg, sentinel or the twin blade reaction), but has also occurred when another player's turn has not started. Desyncs have occurred be during 4-player game in Crown of the Magister. 

Notably, I get a stability warning whenever I startup Solasta (eg, at the main menu before loading a game).

Below is the zipped up player.log and current save game file.

Hope this helps and love the awesome modding done. 

[SubmittingIssueToUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12707563/SubmittingIssueToUnfinishedBusiness.zip)

**Comment by ThyWoof** [comment]
Your log has lots of errors. I suggest:

1. check integrity of game files
2. Reinstall mod from zero
3. While game is running, delete on windows any hero that name appears in the log

these are causing the issues. Most likely you’ve missed reading the changelog about what had changed.
