### ISSUE TITLE
Mirror image appears to not be working

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4051]
The spell casts and the duplicates are seen on the portrait, but they never seem to prevent hits.

In this save, take the flying character Eran up near the archers and cast Mirror Image. They and the wraith will take pot shots at her and every one that isn't a miss will do damage while all three duplicates remain up.

Thanks.
[train trestle fight.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12730233/train.trestle.fight.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/91f556e2-3cdd-477a-86e4-69be88c802c9)

**Comment by qeltar** [comment]
Thanks!
