### ISSUE TITLE
Instability on Loading Save File

### ISSUE THREAD

**Issue by MarinerEarendil** [SolastaMods/SolastaUnfinishedBusiness#4054]
Instability warning upon loading save file on 1.5.94.17.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12739458/Player.log)
[red_crow_test_backup.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12739459/red_crow_test_backup.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1ceb5326-d946-494a-9ee6-452c18bff426)
not much I can do here. Seems to be an issue with the custom campaign itself.

**Comment by MarinerEarendil** [comment]
Interestingly the game ran fine even after the error, I let the campaign creator know. Sorry for false report.
