### ISSUE TITLE
Gravity sinkhole description or implementation incorrect

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4056]
Spell says "enemies" but it has friendly fire.

**Comment by ThyWoof** [comment]
Please add a save file on any issue opened.

**Comment by qeltar** [comment]
I mean it's a description in the mod, it's not save-specific, but here you go.
[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12740546/AutoSave_3.zip)

**Comment by ThyWoof** [comment]
Desc says “crush your enemies” but if you open extended tooltip you will clearly see it targets all. Won’t change desc.
