### ISSUE TITLE
Game instability mostly when exiting an area 

### ISSUE THREAD

**Issue by SavoySrb** [SolastaMods/SolastaUnfinishedBusiness#4060]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12751347/Player.log)

**Comment by ThyWoof** [comment]
Without more context it’s really hard to help. Need a save file and steps to reproduce. Also need the mod version number.

**Comment by SavoySrb** [comment]
I am on mod version 1.5.94.18 and i first downloaded and installed the mod on .16, i had the same problem from the beginning. The warnings and crashes ampere random to me, sometime during combat, but most when i travel form area to area or leave an area
Hera are the save files
[Save files.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12751713/Save.files.zip)

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12751837/SolastaUnfinishedBusiness.zip)

Can you replace the DLL inside the UB folder with the one attached. Please let me know if issue is fixed.

**Comment by ThyWoof** [comment]
seems to be related with Arcane Archer. On location changes there is no more game location characters and it's resulting into a null check. Fixed all similar occurrences across the mod.

**Comment by ThyWoof** [comment]
also keep in mind there are 2 WIP 6th level spells. Don't use them.

**Comment by SavoySrb** [comment]
I replaced the DLL and tested it, looks like it fixed the problem. Thank you for the help

**Comment by ThyWoof** [comment]
Awesome! Thanks for confirming.
