### ISSUE TITLE
100% Reproducible - Combat Softlock after using reaction Smite

### ISSUE THREAD

**Issue by jdo1980** [SolastaMods/SolastaUnfinishedBusiness#4067]
100% reproducible bug.  After attacking and hitting an enemy and using the reaction to Smite, the attack hits and then the game soft locks.  Damage is applied but then nothing happens after that.  Turns don't continue on to other characters.

Using Oath of Dread Paladin.

**Comment by ThyWoof** [comment]
Thanks. Still need your save and player log to simplify debug and QA.

**Comment by ThyWoof** [comment]
Reason is bugs are never about a particular feature but about the interaction of it with others. Without a save I’m under Aksha spells.

**Comment by jdo1980** [comment]
Sorry, should have included from the start.

Attached is save right before hitting the target and choosing reaction to smite where it soft locks.  Attached is the log after it soft locks.
[prehit.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12775674/prehit.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12775676/Player.log)

**Comment by ThyWoof** [comment]
It was merciless. To be fixed on v20.

**Comment by jdo1980** [comment]
Ok, thank you for taking the time to take a look!
