### ISSUE TITLE
Bard - College of Harlequin - Combat Inspiration doesn't grant to-hit bonus

### ISSUE THREAD

**Issue by KetilK-cloud** [SolastaMods/SolastaUnfinishedBusiness#4073]
As the title says, the College of Harlequin bard subclasses Combat Inspiration ability doesn't give any to-hit bonus. The extra movement speed is working correctly, however.

Sadly, we've been away from the game for a while, so uncertain when the issue might have started, version wise, but we are running 1.5.94.19.

Attached is a savegame with the Harlequin having a turn immediately.
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12778785/AutoSave_1.zip)

Thanks for any help with this, and for all the work done with the mod! Appreciate you!

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f0decf67-a301-49c5-9350-39e2a2c100f6)
fixed. thanks.
