### ISSUE TITLE
Paladin can't use "Take Aim" bonus action

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4074]
I've got the latest patch .19

I have a Paladin with the "Take Aim" feat and yet when I go to my bonus actions, there's no option there for the Take Aim feature. 

Save attached. 

[Paladin.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12779827/Paladin.sav.zip)

**Comment by ThyWoof** [comment]
Isn’t Take Aim vanilla? Have you tested without the mod installed on any test location to confirm if a vanilla bug or caused by the mod?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/342c5049-0ad6-48b1-8946-6ca8f7620d2d)
you must be wielding a ranged weapon for take aim action to be active.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c8a8b157-62ba-4902-924f-07850adf1042)

**Comment by Bawookles** [comment]
Shoot, so it won't work on a thrown weapon like the Thunder Paladin's
warhammer? Damn, that's why I got it so I wouldn't always have disadvantage
on my throws. A thrown weapon is a ranged attack, after all.

**Comment by ThyWoof** [comment]
By design I don’t change vanilla behavior. If it works with a dagger then it’s a bug on Paladin sub. Otherwise it’s what it’s. By the way this is a terrible feat anyways.

**Comment by Bawookles** [comment]
Yeah, okay thanks. I was just trying to make the Thunder Paladin more
playable since he's always got disadvantage on his throws past 4 squares.
