### ISSUE TITLE
Cooperative game stops working after casting a spell

### ISSUE THREAD

**Issue by edoenges** [SolastaMods/SolastaUnfinishedBusiness#4077]
I'm currently playing Palace of Ice with my brother. As soon as one of us casts a spell, the game complains of an error occurring and then various things stop working (can no longer save the game, cannot move on the characters, etc.). The first time it happened we attempted to light a torch using firebolt, the second time was when casting fireball.

See the attached the Player.log file for the crash report.

(Filename: <ca435398de644834a3b7cc4cf547bace> Line: 0)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12786368/Player.log)

**Comment by ThyWoof** [comment]
Thanks. This was caused by the new patches to support elemental orb. New version will come out today.
