### ISSUE TITLE
Consistent soft lock when interactibles are caught in AoE spell area

### ISSUE THREAD

**Issue by malonkey1** [SolastaMods/SolastaUnfinishedBusiness#4079]
I've been getting a soft lock where any time I use an AoE damage spell (specifically shatter and fireball, I haven't gotten a chance to try others) and any kind of interactible, like a container, wall torch, or the like, the spell goes through, but the UI doesn't come back on-screen and I can't end turn with Enter, locking up the game. This soft lock is consistent and happens every time for me.

[Player.log attached](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12788361/Player.log)

**Comment by malonkey1** [comment]
Small update, I tried a cone and this did not happen. It may only be spherical AoEs.

**Comment by ThyWoof** [comment]
You should update your mod to latest v21.

**Comment by malonkey1** [comment]
Oh, I see, there was another update today.
