### ISSUE TITLE
Mericless fighting style crashes

### ISSUE THREAD

**Issue by Grfilet** [SolastaMods/SolastaUnfinishedBusiness#4080]
[Merciless-Crash.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12796159/Merciless-Crash.zip)

Solasta version 1.5.94 - Public, all DLCs
Mod Version 1.5.94.21

Crash when killing enemy while having mericless fighting style

Repro :
One shot last bandit in encounter with regular attack + paladin smite (in this case 1 lvl spell slot)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/9385dbb1-58dd-4cca-8fcb-b8e79e3b74cf)
fixed. thanks for save.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12798820/SolastaUnfinishedBusiness.zip)
here so you can continue your game. replace the DLL in folder with this one.
