### ISSUE TITLE
The eldritch surge battlefield shorthand bug

### ISSUE THREAD

**Issue by SavoySrb** [SolastaMods/SolastaUnfinishedBusiness#4083]
If you gain a spell form the Battlefield shorthand versatility and do not use it before a long rest it stays permanently in your spellbook
[Player log and save file.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12818349/Player.log.and.save.file.zip)

**Comment by HIEROT** [comment]
will check it, are you using the newest version of this mod?

**Comment by SavoySrb** [comment]
Solasta 1.5.94
UB 1.5.94.21
I had the same problem on older mod versions, I just forgot to post it

**Comment by HIEROT** [comment]
oh i see. i forget to do the clearing after long rest lol. will be fixed in the next release (and the subclass is also revamped to make it smoothier and easier to play)
