### ISSUE TITLE
Unfinished business won't initialize

### ISSUE THREAD

**Issue by SgtOutKast** [SolastaMods/SolastaUnfinishedBusiness#4096]
I followed the instructions for installation as outlined in the nexusmods page, and I have the mod installed on UMM. When I launch COTM, UMM launches as well, but has nothing listed in the opening screen, and the mod acts as though it is not installed. I've uninstalled, and reinstalled a couple of times, and I have a clean install of COTM and UMM. What did I miss?

**Comment by ThyWoof** [comment]
There isn’t much help we could offer without screenshots and your player log file.

**Comment by ThyWoof** [comment]
Closing for lack of data.

**Comment by SgtOutKast** [comment]
Sorry, just saw this. What do you need screenshots of?
