### ISSUE TITLE
Game freezes whenever Discordance Monk uses Deflect Missiles

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4098]
Using the latest .22 patch. Whenever my Discordance Monk uses Deflect Missiles, whether she passes on throwing it back or throws it back, the game just freezes at that point. 

I've attached a game save just before a goblin always tries to hit her with a ranged attack. If I use Deflect Missiles on it, it just freezes the game. 

[QuickSave_18.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12837368/QuickSave_18.sav.zip)

**Comment by ThyWoof** [comment]
fixed, thanks.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/34a243e8-5fb4-46d9-988d-07f53b07f818)
