### ISSUE TITLE
Malakh Angelic Form Softlock

### ISSUE THREAD

**Issue by RollForChaos** [SolastaMods/SolastaUnfinishedBusiness#4100]
In game and in testing through character creation Angelic Form is unlocking on class level 3 rather than character level 3.  If a character reaches level 3 in 4 separate classes it will softlock as there are no remaining forms to unlock.

**Comment by ThyWoof** [comment]
I need your save file to confirm and fix bug.

**Comment by RollForChaos** [comment]
Attempting to level up the druid class to 3 should give you the same softlock results when it prompts you to select a fourth angelic form.

Additional issue.  When mousing over the Use Medicine power gained from Healer feat it creates an instability.  Player log is included as well for that. 


[MalahkSL.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12838512/MalahkSL.zip)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12838521/Player.log)

**Comment by ThyWoof** [comment]
[Uploading SolastaUnfinishedBusiness.zip…]()

let me know if this fixes first reported issue.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12838527/SolastaUnfinishedBusiness.zip)

let me know if this fixes level up on malakh.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/51b8b3e9-5b29-4102-b33e-8600593038b5)
second one confirmed fixed.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/0b102a76-6da3-41b6-b494-8b631eef468f)
first one as well. thanks for save.
