### ISSUE TITLE
Dread Paladin Loses Extra Attack on a hit and kill

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4106]
Using current .22 patch.

My 5th level Dread Paladin loses his Extra Attack if he hits and kills with the first hit. Don't know if he also loses it if he misses or doesn't kill on the first hit. Saved file attached.

[Dread Paladin.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12841674/Dread.Paladin.sav.zip)

**Comment by ThyWoof** [comment]
Enable action switch to be able to use the first extra attack.

**Comment by Bawookles** [comment]
I enabled that. It still happens.

**Comment by ThyWoof** [comment]
Will check then.

**Comment by Bawookles** [comment]
It's possible it's only affecting characters with Extra Attack who can also
cast spells. I was seeing it sometimes with my Audacity Bard as well. It
seems almost random when it happens. If you hit, you lose your Extra
Attack, if you miss, you still get it.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d1e0fdab-8978-44bd-a719-62eb974116ec)


![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5c6692a4-557e-4f74-a197-119314bc1d66)

seems to be half-way fixed. was expecting only 1 attack left on 2nd SS.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/4f312390-2d90-4319-a2b0-dc8af07ad685)
fixed.

**Comment by Bawookles** [comment]
Thank you for all your work!
