### ISSUE TITLE
Merciless Fighting Style Removes Extra Attack on Kill

### ISSUE THREAD

**Issue by RollForChaos** [SolastaMods/SolastaUnfinishedBusiness#4107]
This is likely the issue the Dread Paladin player was having.  When you have the Merciless Fighting Style and kill a creature it will remove any remaining attacks you had as part of that attack action.  It doesn't appear to matter if you have 2 attacks per action or 6 attacks per action.  Action Surge will suffer from the same loss of remaining attacks.

[Merciless.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12841923/Merciless.zip)

**Comment by ThyWoof** [comment]
That helps. Thanks

**Comment by ThyWoof** [comment]
I cannot open a save made on locations. It's to be on any campaign.

**Comment by RollForChaos** [comment]
I didn't even think about that.  Do you want me to put a campaign save together for you?  I don't mind to do it, but I won't have time until after sleep and work.
