### ISSUE TITLE
Exception: [Tactical - Invisible for players] Impossible to find item

### ISSUE THREAD

**Issue by neomanyouth** [SolastaMods/SolastaUnfinishedBusiness#4134]
Not certain if this is an issue with UB, I'm finding it difficult to tell where the issue originates from based on the logs so apologies if posting here is incorrect.

I'm playing the Island of Domination mod. Whenever I load the  game it warns that there's an instability error, logs attached. The missing item or whatever does seem to be referencing values in the IoD JSON.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12921726/Player.log)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12921727/Player.log)

**Comment by ThyWoof** [comment]
Thanks for the report. I need your save to confirm if the fix works...

**Comment by ThyWoof** [comment]
That item is indeed missing from campaign. Please report to author.

**Comment by neomanyouth** [comment]
Great thanks for looking at this!
