### ISSUE TITLE
[1.5.94.27] Sucker Punch damage remains at 1d6 on level 9

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#4140]
Save is from [This Campaign](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591)
[action surge and sucker punch.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13034121/action.surge.and.sucker.punch.zip)

**Comment by ThyWoof** [comment]
seems to be an engine limitation. rolled back these changes and back to 2d6 across all levels.
