### ISSUE TITLE
[1.5.94.27] Spirit Shroud continues to Hinder enemies long after the spell ends

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#4141]
We used Spirit Shroud two fights and two short rests ago, and the effect that Hinders enemies that start their turns within 10 feet is continuing to trigger even when concentrating on something else entirely.  The Damage bonus from it is not applying, only the Hinder effect.

Save is from [This Campaign](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591)
[hinder.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13034128/hinder.zip)

**Comment by torporous** [comment]
Can also target people with Malediction when we switch back to concentrating on Spirit Shroud

**Comment by torporous** [comment]
And Stench continues to effect the party long after killing all the stinky guys.  Seems to be a similar issue.
[stench.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13034385/stench.zip)

Going through an area transition gets rid of the stench, haven't confirmed whether the spell effects go away or not.

**Comment by ThyWoof** [comment]
Fixed, thanks
