### ISSUE TITLE
[1.5.94.27] Action Surge lasts for the rest of the fight

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#4142]
After using action surge, I continue to have Two full actions every turn for the rest of the fight.

Save is from [This Campaign](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591)
[action surge and sucker punch.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13034125/action.surge.and.sucker.punch.zip)

**Comment by ThyWoof** [comment]
Fixed, thanks
