### ISSUE TITLE
[1.5.94.27] Aegis Assault always knocks everything prone

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#4143]
The way it's worded, it seems like it should ask whether I want to knock prone, knock back, or neither.

And in any case, always succeeding without any rolls or checks, even against minotaurs and giants seems a bit too strong.

Save is from [This Campaign](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591)
[aegis assault.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13034606/aegis.assault.zip)

**Comment by ThyWoof** [comment]
this was a typo on description. FYI I'll demote this sub for a better implementation of it. Won't happen until December.
