### ISSUE TITLE
5th Level Distant Hand Monk Activates Stunning Strike on a ranged attack

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4147]
My 5th level Distant Hand Monk activates her stunning strike ability on a ranged attack. Not only should she not have the ability to stun from ranged until 11th level, but there is no way of turning off the stunning strike on her first ranged attack as the stunning strike button isn't even initially visible in her action toolbar, thus she wastes 1 ki point on the stunning strike on her first ranged attack. 

Save attached.
[monk.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13044650/monk.sav.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/b2e58154-d83a-4f67-bcfd-28c840d0f53e)


I believe this is expected. What I need to do is update vanilla description on stunning strike to be "with a monk weapon attack".

On level 11 you get a pop up for Stunning Arrows.

**Comment by Bawookles** [comment]
Oh, yeah. I picked longbow as the monk specialization weapon and that's what she's using. So you're saying ANY monk that picks a ranged weapon as their monk specialization weapon would get stunning strike with that weapon as soon as they reach level 5?? Huh, interesting.

**Comment by ThyWoof** [comment]
I’m discussing this internally with the dnd experts. I’ll let you know. What’s your take? Should or should not?

**Comment by Bawookles** [comment]
Doesn't matter to me, it's just that if you are going to allow a ranged stunning strike at 5th level for any monk subclass that takes a ranged weapon as their monk specialization weapon, then it makes the Distant Hand monk's 11th level ability pretty lame. Either drastically improve the 11th level Distant Hand monk or make it so no monk can get a ranged stunning strike at 5th level.

**Comment by ThyWoof** [comment]
We got to same conclusion and you have good points on effects applied. Will fix the first part and have it on next release. Will ask the team to redesign the distant hand effects.

**Comment by ThyWoof** [comment]
Fixed. It will only allow on distant from level 11

**Comment by Bawookles** [comment]
Thanks!

If I can make any recommendation regarding Distant Hand monk skill progression, I think it should be something like:

Level 3: Distant Hand Combat (same as already on there, proficiency with bows, bows are a monk weapon, and don't get disadvantage on range attacks in melee. Incidentally, for some reason this ability no longer shows up in the character description bit for Open Hand Monk when you are creating a character, even though the DH monk does get this).

Flurry of Arrows 

Level 6: Ki-Empowered Arrows, Stunning Arrows (getting this at level 6, one level after you get stunning strike instead of 6 levels after you get stunning strike, so it makes sense for the ranged character. Otherwise you are taking the best ability a monk has and saying "but you can't do this at range until late in the game, ranged character." Leaving it until level 11 makes the subclass a bit contradictory)

Level 11: "Force Arrows: Your arrow attacks deal an additional 1d4 force damage". (This is to get a DH monk's dpr up to a regular monk's dpr that took pugalist as a fighting style, when a DH monk should have taken archery as a fighting style).

Level 17: "Quivering Arrow" (This would be equivalent to the Open Hand monk's Quivering Palm ability but would be triggered by an arrow hit)

Just my suggestions for Distant Hand monk! Thanks for all you do! I donated $20 via paypal a few days back.

Level 11:
