### ISSUE TITLE
Permanent Flurry of Blows

### ISSUE THREAD

**Issue by SemBerretty** [SolastaMods/SolastaUnfinishedBusiness#4148]
Most of the monk features like Flurry of Blows and patient defense remain permanent until combat is over.
This also counts for action surge (for PC's and enemies) and maybe more things too.
Attached is my save file
[FlurrySave.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13047289/FlurrySave.zip)

**Comment by Joramius** [comment]
I have the same issue with loads of timed features and buffs. Concentration spells won't stop (not manually, not through damage, not by casting another concentration spell, not by expiring), characters are continuously rolling for stench even though there are no enemies, the Inventor's Defensive Field is staying up, etc.

My save file is of the workshop campaign "The Forsaken Isle". The nearby Flame Wall and the other effects have persisted through concentration loss, unconsciousness and a short rest.

[bugged.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13047702/bugged.zip)

**Comment by ThyWoof** [comment]
One bad refactor unleashed hell in mod. Fixed in dev and waiting for Qa to give a go.
