### ISSUE TITLE
[1.5.94.29] Failing the Spirit Guardians save doesn't trigger Seize the Chance

### ISSUE THREAD

**Issue by torporous** [SolastaMods/SolastaUnfinishedBusiness#4153]
Our party doesn't cause a lot of saving throws, but we've had the opportunist rogue's reaction trigger on Doomblade Cut before.  It's not cooperating with Spirit Guardians cast from a Wardenblade though.

[seize spirit guardians.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13062197/seize.spirit.guardians.zip)
Save is from [This Campaign](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591)

**Comment by ThyWoof** [comment]
Unfortunately this is a game engine limitation. Game can only react to first saving on an attack or magic effect action. I'll consider change the description to make it clear.
