### ISSUE TITLE
[1.5.94.30] Cannot leave the Residence

### ISSUE THREAD

**Issue by briang** [SolastaMods/SolastaUnfinishedBusiness#4159]
In the quest "Path to Glory" the party are gifted the Residence. I can enter it, but cannot exit it again. I *think* this is due to the blue teleporter thing being 2x2. I have 6 in my party and obviously they cannot fit in the 4 squares of the exit grid.

**Comment by ThyWoof** [comment]
Please read https://www.reddit.com/r/CrownOfTheMagister/comments/zyrb34/unfinished_business_6_player_issues/

**Comment by briang** [comment]
Works perfectly. Thanks
