### ISSUE TITLE
Subclass Selection Display Issue in Unfinished Business Mod: Overflow and Scrollbar Solution

### ISSUE THREAD

**Issue by nextas-ben** [SolastaMods/SolastaUnfinishedBusiness#4160]
Debug Info:

- [Latest Version] (Both)
- No Mods (Only Unfinished Business)

I'm not sure if it's a bug that can be fixed by modding, but I've noticed that when selecting a subclass during character creation or leveling up, after clicking on a subclass that has many powers and advantages at level 1 or 3, the text in the right container where the full summary is displayed overflows outside the box. Although the vanilla version doesn't have this issue, I believe the developer was careful with the content length to prevent overflow. However, Unfinished Business has much more text with formatting, such as spells, etc., which triggers the overflowing issue.

Could you  add a scrollbar within this container to enable full reading of the subclass summary just like there is one during the race and class selection? Or is it something only the game developer can do?

thank you for the mod BTW!

**Comment by ThyWoof** [comment]
Too much work for such a small benefit. It won’t happen, sorry.
