### ISSUE TITLE
Unarmed strikes with flurry og blows don't work with Pugilist "Fighting style"

### ISSUE THREAD

**Issue by Sebbelutti** [SolastaMods/SolastaUnfinishedBusiness#4168]
Debug Info:

[Latest Version] (Both) (1.5.94.31)
No Mods (Only Unfinished Business)

As the title says, when i use the "Flurry of Blows" bonus action from the monk while i'm wildshaped as any of elementals as a druid, i don't get procs from the Pugilist fighting style. 

Could you make this fighting style viable with the elementals wildshapes?

Thank you a ton in advance. I love the mod and what it has made the game into.

**Comment by ThyWoof** [comment]
I need a save for QA…

**Comment by Sebbelutti** [comment]
Of course, here is the zip file.
[Short Rest Party Crown.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13216492/Short.Rest.Party.Crown.zip)

**Comment by Sebbelutti** [comment]
I've noticed that when i use Flurry of Blows while in wildshape, the unarmed strikes doesn't get the benefits of the lvl 6 circle of the night feature "Primal Strike", which makes my attacks in beast form counts as magical. I've attached a picture of my druid in wildshape form attacking a bludgeoning resistant enemy. My druid is currently wearing the "Forceful Gauntlets" because i wanted to test if that item helped with my damage on the unarmed strikes while in beast form. However it sadly doesn't and neither does the "Primal Strike" feature. Can you look into this also? 

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/149318022/09396db9-19be-49ad-bd9d-77bb2d1ca9d8)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/28c9d473-c358-4f50-b721-34168285317a)
I cannot test Elemental with this save. It's a level 5 hero. Did some basic tests and interaction with pugilist seems correct. I can even shove as a bonus action.

**Comment by ThyWoof** [comment]
I probably fixed the 2nd request but need a good save for QA.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13246502/SolastaUnfinishedBusiness.zip)

Can you replace your mod DLL with this one and confirm if all reported works now?

**Comment by Sebbelutti** [comment]
Thank you for testing the issue. I'll test the pugilist feat when i get to a point where i can wildshape into elementals. For now i've tested Flurry of Blows in wildshape, and it works with the new DLL you made, so thank you very much for that. That change made it a whole lot more rewarding to use Flurry of Blows.

Regarding the initiative bonus that didn't use either the wildshape's or druid's dexterity, was that not possible to fix? I've found out that the initiative bonus works with some of the wildshapes, but not all, if that help? I can try to find out which of the wildshapes that uses the dexterity bonus, if you want me to look at it?

**Comment by ThyWoof** [comment]
first time you mention issues with "initiative bonus".

**Comment by ThyWoof** [comment]
I'll close this one. Please open a new ticket if you face any issues with initiative bonus while in WS with a proper save please.
