### ISSUE TITLE
Thunderous Smite Showing DC 0

### ISSUE THREAD

**Issue by Armaghost** [SolastaMods/SolastaUnfinishedBusiness#4171]
version: 1.5.94.31

I've been having an issue as an Oath of Thunder Paladin where Thunderous Smite has dished out DC 0 checks (see image). I've remade the character a few times to test out and same issue. Once in a while it'll do a proper DC check but I can't figure out why it won't otherwise.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/56660476/bbe730c2-1486-4098-8ebd-91fa093e27f1)

**Comment by ThyWoof** [comment]
We need a save please.

**Comment by Armaghost** [comment]
[thunderous smite.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13230494/thunderous.smite.zip)


Here you go :) Hope this helps.
