### ISSUE TITLE
Battleborn ASI bug and extra darkvision

### ISSUE THREAD

**Issue by HiddenHax** [SolastaMods/SolastaUnfinishedBusiness#4176]
- With flexible races mod feature on, the race doesn't allow you to pick your own stats. The attributes are also visually all mixed and CON is missing (should still be present but greyed out iirc) with and without flexible races option enabled (screenshot below).
- There is extra darkvision feature added on race. Warforged originally don't have darkvision.

![Screenshot_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/97951552/7bee9052-d4a4-4188-a7ce-a77b97e06b8a)
[Battleborn_Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13246112/Battleborn_Test.zip) - Save here if needed.

**Comment by ThyWoof** [comment]
@otearaisu
