### ISSUE TITLE
Wildling Climbing feature, visual attribute bugs + Claw idea

### ISSUE THREAD

**Issue by HiddenHax** [SolastaMods/SolastaUnfinishedBusiness#4177]
- Climbing isn't mentioned on character creation screen. Would probably be good to include this there for players. It also seems that the way it was implemented has given the race spider climb instead of climbing speed.
- There is this displacement of stats sometimes appearing on the race with flexible attributes mod option on:
![Screenshot_2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/97951552/c947a3a1-8a59-40b9-8027-14314a81c4ce)

- Regarding Claws, perhaps a toggle to deal normal unarmed damage instead so monks can switch between the two without needing to be gimped when fighting skeletons for example.

[Wildling_Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13246227/Wildling_Test.zip) - Save if needed.

**Comment by ThyWoof** [comment]
@otearaisu

**Comment by otearaisu** [comment]
@HiddenHax Misunderstood the spider climb, but I think it's ok to give it to the race, since climb speed isn't much used in Solasta. Will just add it in the description.
