### ISSUE TITLE
Minor tweaks to Rogue

### ISSUE THREAD

**Issue by Nathan-ES** [SolastaMods/SolastaUnfinishedBusiness#4180]
There is a minor bug with Rogues whereby they are awarded their 18th level feature Elusive at level 19 by mistake.

I've attempted to make a branch with a change that should fix the issue (committed to my branch), but I'm having build errors so I can't test it myself.

I also wanted to add an option to remove the spell school restrictions from Shadowcaster Rogue's spellcasting, but I can't see a way to do that in the code, so I'd appreciate any pointers on how I might go about that.

**Comment by ThyWoof** [comment]
issue fixed and settings to remove school restrictions from Shadowcaster and Spellblade added to the mod.

**Comment by Nathan-ES** [comment]
Wow, thank you. I wasn't expecting this, and so quickly too. I shall eagerly await the next release!
