### ISSUE TITLE
Tundra Tiger Wildshape

### ISSUE THREAD

**Issue by Sebbelutti** [SolastaMods/SolastaUnfinishedBusiness#4186]
Why does Tundra Tiger Wildshape hyave +5 in damage to the "Bite" attack and then +4 to the "Claw" attack?

Is this intended? If so, does that mean that one of the attacks use DEX and the other STR? If that is the case, then i think that there generally are issues the with Tundra Tiger climbing, as i can't climb up stuff that requires a bare minimum of STR.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/149318022/89a8166a-5710-4970-94b8-2cbf29bb8a54)

**Comment by Sebbelutti** [comment]
Here is a save file for testing (Druid is in the orc arena and about to fight one of the orc chieftains):
[Tundra Tiger WS.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13261112/Tundra.Tiger.WS.zip)

**Comment by ThyWoof** [comment]
Please ask the game developer. We don’t touch Tundra tiger at all.
