### ISSUE TITLE
Instability warning when opening game

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#4195]
I recently installed the mod and was tweaking the settings. After saving, an instability warning appeared; this continues to open every time now.

I saw someone had a similar issue where it was marked as resolved with the dev saying to delete all characters that trigger "Exception while loading" in the player log. I have done this, as well as deleted all relevant save files from the game folder, but they continue to appear in the player log and regenerate themselves in the folder as well.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13326829/Player.log)

**Comment by HiddenHax** [comment]
You need to delete the characters in the game itself, not folder. This is why the characters keep reappearing.

**Comment by LuckyTortellini** [comment]
They're not visible within the game for me to delete.

**Comment by ThyWoof** [comment]
open the game, alt-tab to windows explorer, delete these heroes from their respective folder, close the game. Otherwise the cloud service will bring them back.
