### ISSUE TITLE
Psychic Whip failed save leads to enemy turn freeze

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#4200]
When I use Psychic Whip and the enemy fails their save, once it's their turn they don't move or otherwise take any actions and the "Enemy Turn" banner stays up. The music still continues. I believe this started happening after I completed the battle right before obtaining the Crown. 

[PsychicWhip_EnemyFreeze.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13347188/PsychicWhip_EnemyFreeze.zip)

**Comment by ThyWoof** [comment]
Do you have action switch enabled? Can you share a save just before the enemy turn?

**Comment by LuckyTortellini** [comment]
I do have action switch enabled and here's a save from right before the enemy's turn:

[PsychicWhipFailFreeze.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13356745/PsychicWhipFailFreeze.zip)

**Comment by ThyWoof** [comment]
Enemy is issuing a Dash action (main) in this scenario. Most likely to issue a move action after which gets denied by the spell logic. It's a hard one to fix but will keep looking.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13401206/SolastaUnfinishedBusiness.zip)

Better I can do here is not enforce the NoMove condition if the enemy tries a Dash first. Better this than a frozen game. Please replace your mod DLL with this one.

**Comment by alkdnvwoeivn** [comment]
I just had this same problem. Enemy failed psychic whip, then on their next turn took the dash action then won't end their turn. Is it still ok to use the DLL you posted over a year ago to fix this problem?

**Comment by ThyWoof** [comment]
No. Always use latest. Do you accelerate enemy turns with space bar by any chance? If so, try avoiding that.

**Comment by alkdnvwoeivn** [comment]
No, I'm pretty sure I didn't do that. I'll try using psychic whip again and see if it happens again
