### ISSUE TITLE
why not using 5e name

### ISSUE THREAD

**Issue by jk2l** [SolastaMods/SolastaUnfinishedBusiness#4204]
it's quite confusing some subclass/spells use official 5e names but some use some random name. Like you get booming blade for booming blade, but UB have "burning blade" for greenflame blade. and I am not even sure is it copy right issue, because if it is copy right wont it mean "booming blade" should not be allowed too?

Is it possible to have settings to have proper 5e name?

**Comment by ThyWoof** [comment]
good call. will rename booming blade.
