### ISSUE TITLE
Inventor spellcasting with hands occupied

### ISSUE THREAD

**Issue by Balfuset790** [SolastaMods/SolastaUnfinishedBusiness#4216]
So, this may not be an actual bug, but from what I've read in numerous places it's implied that Inventors are able to cast spells with both hands occupied - ignoring Somatic components. I have an Inventor in my current party and even with a magical weapon (which was suggested on Reddit as a potential solution) they still get the error of 'no free hands for somatic components'. Is this supposed to be acting this way? Or are they supposed to be able to cast spells with both hands occupied as the guides and one of the builds on the wiki suggests?

**Comment by ThyWoof** [comment]
AFAIK it doesn't. All it does is give focus if your weapon is infused.
