### ISSUE TITLE
Instability.

### ISSUE THREAD

**Issue by Vexillen** [SolastaMods/SolastaUnfinishedBusiness#4218]
An instability happens right after I go in the Giant Cave in Lost Valley. Loaded 3 times happened every time.

This happened after I leveled my party up to 6 and infused Boots of Striding.

Party, 
Inventor Weaponsmith.
Warlock Soulblade
Monk Tempest
Paladin Thunder

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13494922/Player.log)

**Comment by ThyWoof** [comment]
Can I have the save before getting there?

**Comment by Vexillen** [comment]
I overwrite the save, trying to fix it. I thought the player.log was enough for troubleshoot, sorry. But it didn't happen again after I respec the inventor.
