### ISSUE TITLE
Game Breaks Whenever I Wild Shape

### ISSUE THREAD

**Issue by Blabooer** [SolastaMods/SolastaUnfinishedBusiness#4222]
Every time I use Wild Shape in this save file, the druid doesn't transform and the game breaks. If I'm in combat, it just never progresses. If I'm out of combat, I can no longer control the druid, but everyone else still moves fine? Issue has persisted through multiple restarts.

Druid is Circle of the Night with multiclassing.

Save File: [Lair of the Lich.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13506723/Lair.of.the.Lich.zip)
Workshop Campaign: https://steamcommunity.com/sharedfiles/filedetails/?id=2815549531

**Comment by ThyWoof** [comment]
some bad interaction with crystal defense.

**Comment by ThyWoof** [comment]
fixed in DEV.
