### ISSUE TITLE
Release 1.5.94.36 zip file has incorrect filename

### ISSUE THREAD

**Issue by BlackPhoenix** [SolastaMods/SolastaUnfinishedBusiness#4227]
The zip file for Release 1.5.94.36 has an error in the filename: "1.**4**.94.36".

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3641980/ea3e00ad-99af-481f-a2f8-0e9d02e05699)

**Comment by ThyWoof** [comment]
fixed. thanks.
