### ISSUE TITLE
Crash when trying to light a torch

### ISSUE THREAD

**Issue by rune74** [SolastaMods/SolastaUnfinishedBusiness#4254]
Good day had a crash in a tomb at the castle. Including crash report and save file.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13806256/Player.log)
[QuickSave_7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13806258/QuickSave_7.zip)

**Comment by ThyWoof** [comment]
How did you try to light the torch? Using a spell attack? Which spell?

**Comment by rune74** [comment]
I used the firebolt spell. I a torch lights it fine and doesn't crash.

**Comment by ThyWoof** [comment]
fixed on v40 to be released in the next 12-24 hours.
