### ISSUE TITLE
Heavy Armor Expert (not working in MP)

### ISSUE THREAD

**Issue by rpavlicek** [SolastaMods/SolastaUnfinishedBusiness#4259]
This feat will display that it applies damage reduction of `3`, but the actual damage roll is not reduced at all.

This seems to happen in multiplayer

**Comment by rpavlicek** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/7076002/1b8c7a8a-596e-4994-92e2-7db2aecdc500)

**Comment by ThyWoof** [comment]
Can you share a screenshot of the combat log with also the tooltip on damage details?

**Comment by rpavlicek** [comment]
I will try to get one later today when I play MP

**Comment by rpavlicek** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/7076002/154f7a38-9068-4156-bf20-deeeb2fa4dc2)

**Comment by rpavlicek** [comment]
A slightly different one with only -1 damage

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/7076002/26da7aff-c4fb-4097-92fb-c4d489a2ca47)

**Comment by ThyWoof** [comment]
What happens here is game consolidates the bonus damage. There is no way to show on tooltip bonus - 3.

It’s working correctly based on these monsters attack bonuses.

**Comment by rpavlicek** [comment]
So there is a +X and -3 that is combined into a new number? I understand however, in single player, I would see a -3. I'll have to test it again to see.

**Comment by ThyWoof** [comment]
Please. This has been reported a few times main reason why I added the additional heavy armor message to log. As I cannot test in MP wasn’t sure if an issue there. Good to confirm this same battle in SP.

**Comment by ThyWoof** [comment]
hi, have you been able to confirm if same results in SP?

**Comment by ThyWoof** [comment]
Please reopen if you ever face this in single player.
