### ISSUE TITLE
Unable to proceed The ID

### ISSUE THREAD

**Issue by rune74** [SolastaMods/SolastaUnfinishedBusiness#4262]
Game crashes after banter with characters before the chest near the statues in base game questline. Unable to proceed the game at all.

Including log and save file.  
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13853962/Player.log)
[new test1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13853965/new.test1.zip)

**Comment by ThyWoof** [comment]
This is a vanilla game bug. Reason you see the pop up is because the mod intercepts any issue, vanilla or not. It's safe to proceed here. This particular location is missing an asset that causes this.
