### ISSUE TITLE
I cannot save the game

### ISSUE THREAD

**Issue by Csatadi** [SolastaMods/SolastaUnfinishedBusiness#4275]
I cannot save the game. Not ironman mode.

![Solasta save game bug](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/87618461/88807bdc-fd11-41d5-bb02-eff175a50c39)

**Comment by Csatadi** [comment]
version 42

**Comment by ThyWoof** [comment]
Not related to the this mod. If people were not able to save their games because of it, this section would flow with complaints. Probably something specific to this scene or your install.
