### ISSUE TITLE
Heroic Infusion + Shared Spell gives TempHP to the Caster

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4276]
When casting Heroic Infusion with Shared Spell (Ally Only) the tempHP goes to the caster instead of the target. 
In this case: Caster is Artemis, target was Ekko. 
Ekko receives all the effects of Heroic Infusion except the tempHP which gets applied to Artemis.

Save file is at start of combat.

[PalaceOfficeCombat.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13914529/PalaceOfficeCombat.zip)

**Comment by ThyWoof** [comment]
Some mod content is fully coded as vanilla features aren’t enough. This is the case with this spell. Did a quick check and need to validate all spells on below list also work with this metamagic.

![IMG_5700](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5ca773ae-676e-4008-83c5-00b09134536c)

**Comment by ThyWoof** [comment]
After an initial check on which spells use vanilla and which use custom, above list is down to. Will check each one and find a way to support Shared Spell.

- Spike Barrage
- Mirror Image
- Flame Arrows
- Heroic Infusion
- Ring of Blades

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d56ebd9c-ab43-4526-b735-17bb63357bca)
Ally only fixed.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d077ca78-bb2a-4d8b-876f-812ade8687e1)
Ally and self fixed.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/dacb829b-9917-49ef-9ab4-8d4ae1840d48)
Ring of Blades working using caster attack bonus. Wizard has Shared Spell and casted on Cleric. Cleric on attack uses WIZ INT + PB as it should.

**Comment by ThyWoof** [comment]
Confirmed Illusory duplicates was already working. Both ring of blades and heroic infusion fixes will be on next release.
