### ISSUE TITLE
Coordinated Attack gambit seems to make "dsyncing" in co-op frequent

### ISSUE THREAD

**Issue by freedeau** [SolastaMods/SolastaUnfinishedBusiness#4279]
First off, amazing mod!  Our group has been using UB with a ton of Solasta modules and it's great!  Keep up the great work!

Unfortunately, our co-op group keeps hitting "dsync" issues (almost every battle) when we have a character with Coordinated Attack gambit.  I attached a recent log from when I was hosting and the game crashed out to desktop during a battle where Coordinated Attack was used and it caused a "dsync" event.  I put details for the specific instance below, but we have seen this occur during several different custom Workshop modules and the Palace of Ice campaign as well. (i.e. doesn't seem to be module specific)  The workaround is to simply save/load the game to get everyone synched up again.

I think all you need to reproduce this is to have a character with Coordinated Attack, play co-op, and trigger the ability in combat.  We rarely get through a combat where it doesn't happen.  Having 4 or more players might make it more frequent (not sure) but we usually have 4 players.

I am not sure if there is an official definition of "dsyncing" in Solasta, but what I mean is during co-op games, when one or more players are seeing a different game state from the other players.

I attached a recent log and save where we were playing the "Lost heir of Kerran Keep" module: https://steamcommunity.com/sharedfiles/filedetails/?id=2930765458

We were in a battle, Coordinated Attack occurred, players got "dsynched" and then I loaded the game (while we were all still in the game) from an earlier save, and then it crashed on load.  I am not sure the crash has anything to do with getting out of sync because we normally reload when that happens and it loads fine.

4 players, all on Windows
latest Solasta version: 1.5.94
latest UB version: 1.5.94.42

I realize this is not ideal debugging info, but please let me know if there is a better way to capture useful data as the issue happens.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13935130/Player.log)
[TiFlLiFr 4.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13935210/TiFlLiFr.4.zip)

Cheers!

**Comment by freedeau** [comment]
Thanks for the quick response!  I can absolutely test out changes.  Please let me know if there are any specific steps you'd like us to go through.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13953124/SolastaUnfinishedBusiness.zip)
you and all players need to manually replace the mod DLL under GAME_FOLDER\Mods\SolastaUnfinishedBusiness.

Try again with this new version and let me know if any better.

**Comment by Thaladar** [comment]
Just to add.  We have noticed this desync the last few MP sessions as well.  We did some extensive testing on this during a long 2-hour battle last night.  We have 6-players.  Some data points:
- If the Marshal triggers Coordinated Attack and only one player chooses to attack (all others pass or ineligible), no desync.
- If the Marshal triggers Coordinated Attack and two (or more) players choose to attack, desync occurs
This happened every time during the battle.  

We will load the DLL above for our next MP session and see if it solves the issue for us.

**Comment by ThyWoof** [comment]
The only change I did recently was enforce the order of reactions based on order of clicks. This was mainly to support a collateral scenario under single player. If above DLL still fails then I’ll add a protection to avoid that under a MP session.

**Comment by freedeau** [comment]
Great, thx!  We should be able to test this out this week, hopefully tonight, and I'll report back.

**Comment by ThyWoof** [comment]
[Uploading SolastaUnfinishedBusiness.zip…]()
fix on this DLL. please confirm it's sound.

**Comment by freedeau** [comment]
We were able to get together tonight and got some more data...

## Test 1
Save File: The same one I posted earlier
Log File: Patched-4player-kerran-keep.log
loaded 4 player co-op game
dsync happened after 2 players reacted to CA (one person didn't get the prompt when they should have)
We reloaded a save (to resync)
dsync still happened, even when only having one person react to CA and others pass

We also tried playing this same save with just 3 people (4 characters), and we didn't get a dsync after using CA.  Unfortunately, I forgot to grab the log file for this run. :(


## Test 2
Save File: TiFlLiFr 42dll.sav (attached in the zip)
Log File: Unpatched-v42-4player-kerran-keep.log
We reverted dll back to v42 version
Loaded earlier save prior to end battle
Fought a different battle, careful to only have one person react to CA and others pass
We all stayed synched for the whole battle
Note: We have had previous battles where it doesn't dsync when using CA, just rare

[4player-kerran-keep-dsync-logs.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13958881/4player-kerran-keep-dsync-logs.zip)


I'd like to also test from a brand new game (we ran out of time tonight) using a character with CA, just in case our existing save game has an impact when combined with your patched dll... unless you think this is irrelevant.

I doubt it matters, but there was also a recent update to the module we are playing ("The lost Heir of Kerran Keep") which led to a content version mismatch; I loaded the new module version.

Lastly, I am a dev, so if attaching a debugger to get more info would help, please let me know.

**Comment by freedeau** [comment]
Oh, and thanks again for taking a shot at this... The effort is definitely appreciated. ❤️

**Comment by Thaladar** [comment]
So, this is now fixed? From the tests above, it seemed like desyncs were still occurring even with the modified DLL.

**Comment by freedeau** [comment]
It is not fixed from our testing.  I am willing to debug more if needed, but we just save/load when it happens as a workaround.
