### ISSUE TITLE
Arcane Recovery with multiclass uses character level instead of Wizard level

### ISSUE THREAD

**Issue by BlackPhoenix** [SolastaMods/SolastaUnfinishedBusiness#4281]
Arcane Recovery should allow a wizard to recover a number of level-spell slots equal to half his wizard level. However, the game currently uses the character level.

For example, a Fighter 12/Wizard 2 should have only 1 spell slot to recover, but Arcane Recovery allows recovery of 7 spell slots.

**Comment by ThyWoof** [comment]
Care share your save?

**Comment by BlackPhoenix** [comment]
I'll have to create a new one - I'm in a multiplayer game and another player handles the save games. But I reproduced the issue locally. I'll generate one and attach it here.

**Comment by BlackPhoenix** [comment]
@ThyWoof here is a save file.
[ArcaneRecoveryBug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13941959/ArcaneRecoveryBug.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/6f4b6c69-2899-46c9-a792-da9a57d57274)
I used all wizard spells on above save but not getting offered any arcane recovery. this is strange. Mod has been handling Arcane Recovery under MC for years now.

Can you confirm you get the arcane recovery prompt on short rest?

**Comment by ThyWoof** [comment]
* cannot reproduce on a Wizard/Figher
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/e5d9d94c-b345-4fc0-9e1e-b98b02c809a9)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/a813e05f-1105-4f87-b155-1c402fe62197)


* cannot reproduce on a Rogue/Wizard
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/9dc37863-b2bd-421c-803b-7cc741e7cb24)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/361f44b0-0027-4dc4-9777-e5fcd5531da7)

not sure why it's not working for you. Care share your settings file?

**Comment by ThyWoof** [comment]
Cool and sorry as I’m a single developer working on a mod that is huge. Will take a look why this stopped working as it’s implemented back in 2022.

**Comment by BlackPhoenix** [comment]
No problem - thanks for doing this! Plus, it's not even like it was game breaking! :)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/935ab911-68d9-4b6a-a068-9e977e238551)

**Comment by ThyWoof** [comment]
check #4279 for an updated DLL with this fix in case you wanna confirm on your end.
