### ISSUE TITLE
Instability

### ISSUE THREAD

**Issue by Csatadi** [SolastaMods/SolastaUnfinishedBusiness#4283]
You asked for the log, here you are.
Illusion stone right after crossing the gate in the maze and the cutscene played.
![Solasta UB bug](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/87618461/4c1c17d5-1c67-4031-852e-52f4731feb76)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13952308/Player.log)

**Comment by ThyWoof** [comment]
This is a vanilla bug that UB is catching. Safe to proceed.
