### ISSUE TITLE
War Dancer Momentum not proccing frequently after latest patch

### ISSUE THREAD

**Issue by Trickflo** [SolastaMods/SolastaUnfinishedBusiness#4292]
Hello I'm experincing a wierd issue, it seems that since the latest update momentum is only very rarely proccing I played about four hours with my brother today and momentum only ever procced a few times, on my brothers game it procced more often then on mine but still not very often which caused some desync issues when I killed the mob on his screen with the momentum damage but not on my screen since there wasn't any. After we wrapped up I created four bards to do some testing to try and determine the cause on all four it didnt proc more then half of the time(either worked the whole round or didnt proc at all) but some it procced less, the one it procced the least on was the one that was a mirror of my multiplayer character which was a dark kobold with elven precision and hammer the point feats. The one it procced the most on was a Wildling  with blade expert and apothecary. Yesterday it seemed to proc every time on my multiplayer character. In all cases the extra attack from improved war dance did proc just not the momentum debuf or damage.

**Comment by ThyWoof** [comment]
There isn’t much I can do if you don’t share a save before the desync, steps to reproduce, and logs on your end. Please share this data and I’ll check if anything is wrong.

**Comment by Trickflo** [comment]
Thanks for the reply heres a copy of the save at the start of a fight and the log the character in this save file is Trickflo and to reproduce the error activate war dance and attack momentum strike should pop up after every attack but isn't proccing more often then it is.
[ubLV.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14029979/ubLV.zip)
[WDLostValley.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14029977/WDLostValley.txt)


Here's the file I used to try and isolate variables in the Dun Cuin user campaign because that was the easiest way for me to start a campaign with four level 6 bards it procced more often here but still not every time on any of the bards. 

[WARDANCER.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14029899/WARDANCER.log)
[Bard Test.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14029921/Bard.Test.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/899dcd9e-0f75-4a53-bc82-cdd86ceb632c)
it seems to be something wrong with vanilla distance calculation method I used in a previous commit. Can you enable official distance calculations on mod UI and let me know if any better?

**Comment by Trickflo** [comment]
Thanks! Played for about an hour so far and it's procced every time. Aprrieciate the assistance.

**Comment by ThyWoof** [comment]
fix for vanilla scenario will be on next release. meanwhile, mod distance calculation is better anyways.
