### ISSUE TITLE
Ethereal Step No Longer Works

### ISSUE THREAD

**Issue by jlk493** [SolastaMods/SolastaUnfinishedBusiness#4298]
Doesn't work in or out of combat, no matter the distance, but other teleportation spells and powers like Misty Step and Rift Step do.

**Comment by ThyWoof** [comment]
Does it happen with lighting and obscurement rules off?

**Comment by jlk493** [comment]
> Does it happen with lighting and obscurement rules off?

Yes. I had them off originally, then toggled on and off to experiment based on your comment. Made no change either way.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/7e0d37ff-44da-4e3e-8ff8-4b5e03b0d4e5)
fixed.
