### ISSUE TITLE
Bug and files

### ISSUE THREAD

**Issue by Celebrindal68** [SolastaMods/SolastaUnfinishedBusiness#4304]
Do I put the files and report the bug here? Thanks.

**Comment by ThyWoof** [comment]
You can attack any zip file here. Might also be good to state first what the issue is. Depending on it, save files might not be required

**Comment by Celebrindal68** [comment]
When leveling up a multiclass character it either refuses to do anything or it refuses me to pick an existing class to level.
I have a party of 4 bards, multiclassed as: bard-fighter, bard-thief, bard-cleric, bard-mage. The cleric and mage ones have been leveling fine but the fighter and thief ones have had issues. 
The fighter one I was forced to take 2 additional levels of fighter so now the class is 3/3. For the next level I wanted to take bard and it refuses to let me pick the option.
The thief one when I click on level up does nothing.
As a side point when casting spells it has been allowing me to upcast past my current spell levels and I think if I remember right it will even allow me to do so when in theory i've used all my slots for the day.
Let me know if you want the files or not.
I'm playing the Dragons Domain workshop item and have all of the DLC. Thanks

**Comment by Celebrindal68** [comment]
Ok updated to .47 and it allowed me to level. But something still seems off as the fighter wasn't given a choice of a new spell but the thief was. When I look at the spells for the two characters the both show the same number of known spells but the thief does show 2 slots for 3rds even though 3rds were not given as an option to select spells. As they both just hit 4th bard I don't think they have 3rds.

In addition the feat/stat levels are off. It's applying a stat choice for example when one of the classes hits 4 vs character overall level of 4.
Hope this all helps ;-)

**Comment by ThyWoof** [comment]
Check how multiclass rules work RE: spell slots. https://5thsrd.org/rules/multiclassing/

Having slots of higher levels is expected behavior. You can use them to upcast spells.

**Comment by Celebrindal68** [comment]
> Check how multiclass rules work RE: spell slots. https://5thsrd.org/rules/multiclassing/
> 
> Having slots of higher levels is expected behavior. You can use them to upcast spells.

Fair nuff, not 100% familiar with 5th.. but even so 6/1 bard/ftr 6/1 bard/thief should have same slots and levels. Fighter doesn't have the 3rds but the thief does.

**Comment by ThyWoof** [comment]
Which race did you use? Any feat or fighting style added? Which Bard sub?

**Comment by ThyWoof** [comment]
multiclass has been stable for years now. No matter what I do I cannot repro what you said.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/744a0c6f-bb23-4180-9945-c9c443669544)

cannot do much without your heroes, save, screenshots.

**Comment by Celebrindal68** [comment]
Let me see if my save file will do it.
