### ISSUE TITLE
Kinesis does not haste caster

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#4312]
The Warlock invocation Kinesis is described as hastening both the caster and a companion. As of 1.5.94.46 it is only hastening the companion. If this is a deliberate change, then the description needs to be updated.

**Comment by ThyWoof** [comment]
Honestly I dunno. Is there anything similar in TT?

**Comment by ThyWoof** [comment]
It’s based of the haste spell which doesn’t allow select self. What’s incorrect there is it should allow a second target to be selected. Will fix but keeping caster out.

**Comment by charlesewatkins** [comment]
Looks like the issue is back with 1.5.97.0. Kinesis only affects one target again. (And I may not remember correctly, but it seems that the original implementation did not use up a spell slot.)

If this is part of a general rebalancing, it should be included in the notes. Also, mention the deletion of the fighting style feats.
