### ISSUE TITLE
Burning Blade causes instability issues and crashes when playing multiplayer 1.5.94.48

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4315]
Hello,

Playing the game on multiplayer and just updated the mod per the update. Ever since the update casting Burning blade that targets 2 units the game throws an instability error and then combat is stuck. The first hit resolves but it seems to be stuck on resolving the second hit. 

Here is the log
[Player-prev.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14106497/Player-prev.log)

**Comment by GrayTechGH** [comment]
Experienced
[Burning Blade UB Logs and Settings and save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14106582/Burning.Blade.UB.Logs.and.Settings.and.save.zip)
 the same issue as above on a single player campaign.

**Comment by ThyWoof** [comment]
Thanks. Already fixed in dev.
