### ISSUE TITLE
Burning Blade crash

### ISSUE THREAD

**Issue by SonoTheDoc** [SolastaMods/SolastaUnfinishedBusiness#4316]
Hello everyone and thank you for the wonderful work you do every day. 

I've got the Steam version with all DLC's (1.5.94 Public), UMM 0.27.10 with UB 1.5.94.48 
I found this error: I was fighting an Orc Raid (AutoSave_5) when hitting an Orc with the Artificer's Burning Blade cantrip , the game freezes due to instability.

Thank you for your time

[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14109929/Solasta.zip)

**Comment by ThyWoof** [comment]
already fixed in DEV. thanks
