### ISSUE TITLE
Paladin Oath of Thunder can use Channel Divinity: Thunderous Rebuke event when they have no uses of Channel Divinity available

### ISSUE THREAD

**Issue by BlackPhoenix** [SolastaMods/SolastaUnfinishedBusiness#4317]
The Paladin Oath of Thunder 3rd level ability allows them to retaliate when struck in melee. This uses their Channel Divinity ability.

However, it appears that the game doesn't check that the Channel Divinity ability is available. Save game attached: just end turn (or heal), waiting for the goblins to inflict damage in melee.

Reaction is offered even though it has no uses left:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3641980/ac6cff9e-c1d1-4e86-9877-5e867faa2ab3)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3641980/fe7730b0-cb8f-40b3-9f05-63103f97e92c)

I finished the battle with -4 Channel Divinity available:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/3641980/421fe077-b95c-4d78-9447-e47ab42ef5d8)

[ThorChannelDivinityBug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14115412/ThorChannelDivinityBug.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/ebf89ebf-9c5e-47d5-852d-8cd9a4cb6659)
fixed. thanks for the save.
