### ISSUE TITLE
Twinned Resonating Blade

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#4335]
Resonating Blade allows you to use Twinned Spell it, but when Twinned Spell is used, only the first target is attacked and the sorcery point is wasted.

**Comment by ThyWoof** [comment]
please share a save.

**Comment by miridistress** [comment]
[bugfix.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14171038/bugfix.zip)
Sorry for not including this earlier. The campaign used is called "Lifting the Siege".
