### ISSUE TITLE
Different visibility for different spells

### ISSUE THREAD

**Issue by Csatadi** [SolastaMods/SolastaUnfinishedBusiness#4336]
Sometimes I cannot aim malediction at an enemy but I can shoot it with eldritch blast. The game writes about visibility not range.

Same place for both cases.
All UB visibility features used. Version 50.
![solasta malediction cannot see](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/87618461/d87b5692-4c84-4162-bbe9-bfb975e9498d)

![solasta blast sees](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/87618461/d9b47e79-a334-4b3b-a51e-38c6cbf5594e)

**Comment by ThyWoof** [comment]
please share a save.

**Comment by Csatadi** [comment]
Mod: Lifting the Siege
Steam version if it does matter.
My settings included.

malediction issue:
target the guy on the stairs.sav
another malediction.sav

melee visibility  issue
not perceived melee.sav

[malediction.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14172247/malediction.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/152f8dab-bbf5-4116-9a6e-39eff65c690a)
this is correct. Both are unlit but Paladin has Darkvision.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/479fa077-4cac-453a-8b50-d65391d96a84)
I also don't see anything incorrect here. The enemy you cannot target is at a lower plane.
