### ISSUE TITLE
infinite impish wrath

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4341]
no matter the attack type the number of uses never decreases

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14182563/Player.log)

[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14182569/AutoSave_3.zip)

**Comment by ThyWoof** [comment]
Already fixed in dev, thanks
