### ISSUE TITLE
War caster granting bonus attack after main weapon attack

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4344]
Bow Mastery Feat is granting a Bonus Action attack when attacking with a Longbow or even Sword and Shield.  

If this is intended, 1) it is broken powerful and 2) the description of the feat should be updated.

However, I recommend that it only allow a bonus action attack with a shortbow and only if main action attack was with a shortbow.  Otherwise, this feat is bonkers broken powerful.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/151783107/a5873e7e-15e6-40a8-9b6d-872a10f416c6)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/fe309767-323e-4dbc-a10b-813c8d94d71f)
It's coded exactly the way you've recommended. I cannot reproduce the issue locally. Something else is granting this 2nd attack. I need your save.

**Comment by Thaladar** [comment]
Yep.  You are right.  It's not the Bow Mastery Feat.  But the War Magic feature of the Fighter Spell Shield class.  It is supposed to only grant a Bonus Action attack after casting a Spell or Cantrip.  But it's granting a Bonus Action attack after attacking (hitting?)  with any weapon and not casting any spells.
[Test Bow Mastery 2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14188705/Test.Bow.Mastery.2.zip)
