### ISSUE TITLE
Inaccurate/Uneven Half-Caster Spell Slots

### ISSUE THREAD

**Issue by jlk493** [SolastaMods/SolastaUnfinishedBusiness#4357]
Ignoring my Bardlock, my party includes:

- Paladin 3 / Sorcerer 1
- Inventor 3 / Fighter 1
- Ranger 3 / Druid 1

The Paladin and the Ranger consistently have one more spell slot than the Inventor, even though that shouldn't be the case, based on this calculator: https://fexlabs.com/5eslots/

Right now, Inventor has 3 Lvl 1 slots, while the others have 3 Lvl 1 slots. Inventor has 0 Lvl 2 slots, but the other two have 2 Lvl 2 slots. At higher levels, I've noticed that Paladin and Ranger will get a higher level spell slot that the Inventor doesn't. For example, they may get a 4th level slot before they have access to 4th level spells, but Inventor doesn't. That's great for upcasting some of their existing spells, but it feels unfair. 

Sometimes it evens out in terms of spell slot level, but it never evens out in number. For example, their spell slots look like this at level 6:
- Paladin | 4 Lvl 1 | **3 Lvl 2** 
- Inventor | 4 Lvl 1 | **2 Lvl 2** 
- Ranger | 4 Lvl 1 | **3 Lvl 2**

Level 12:
- Paladin | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **1 Lvl 4**
- Inventor | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **0 Lvl 4**
- Ranger | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **1 Lvl 4**

Level 16:
- Paladin | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **3 Lvl 4** | **1 Lvl 5**
- Inventor | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **2 Lvl 4** | **0 Lvl 5**
- Ranger | 4 Lvl 1 | 3 Lvl 2 | 3 Lvl 3 | **3 Lvl 4** | **1 Lvl 5**

If anything, Inventor should probably have the higher slot number, since Artificers round up instead of down, unlike other classes. See, e.g.: https://rpg.stackexchange.com/questions/169189/how-does-multiclassing-work-for-an-artificer . My math could be wrong on that though. Regardless, it feels strange the Half-Caster who leans more towards spellcasting consistently has fewer spell slots than the Half-Caster who lean more towards martial ability. 

This is true regardless of whether I play Authentic mode, Scavenger mode, or Cataclysm mode. Might be different in Story mode, since I've noticed that crunches numbers differently, at least in terms of HP.

Not sure what data would be helpful here, but here are screen shots for Lvl 16:

![P1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/143850354/91f88b56-ea90-4b45-8d14-dabd7b907c61)

![A1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/143850354/b52f7e72-e853-46ca-b722-577546d3fcd4)

![R1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/143850354/ed04a0c3-c56b-453b-9302-34bc1be23e35)

**Comment by ThyWoof** [comment]
Inventor / Fighter only get slots from inventor. All other MC get slots from both classes. Reason why a Paladin / Sorcerer will have more slots at some point. This is something I wrote more than 3 years ago and as far as I can tell it works by the letter. I used the same spreadsheet you suggested on my tests. Indeed inventor gets slots on 1st level but rather than that it has the same scale as half casters like Paladin or Ranger.

**Comment by ThyWoof** [comment]
Indeed there is something odd at level 5. Should be 2 slots on all scenarios.

**Comment by ThyWoof** [comment]
I believe https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/5a76311f981eb5616c74fff091eab4579cdae4ee/SolastaUnfinishedBusiness/Models/SharedSpellsContext.cs#L273 is round up not round down reason why we see these results. Should be as easy as slide this array right
