### ISSUE TITLE
Crashing on rest for both 1.5.94.53 and 1.5.94.52

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4360]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14304527/Player.log)

I *think* it has to do with the replicate magic item ability with the inventor. Updated to 53 today and leveled up, made a replica of an item equipped it, crashed on rest. rolled back to .52, crashed on rest again.

updated to .53 again to an old save before i replicated the item and was able to rest fine. I'm pretty sure the replica item is breaking somehow.

**Comment by jlk493** [comment]
What item did you try to replicate?

**Comment by ThyWoof** [comment]
Do you have the save? Unable to fix without one.

**Comment by orangepeelpanda** [comment]
gloves of missile snaring. 

here is the save
[bunnybearmoor.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14307598/bunnybearmoor.zip)

**Comment by ThyWoof** [comment]
Not related with the replicated item but failing when trying to refresh the half plate +1

**Comment by orangepeelpanda** [comment]
huh, refresh as in? I have light cast on it, does that mean it will fix itself if i cast light on something else? or is it the inventor +1?

**Comment by ThyWoof** [comment]
Try that please. I’ll get back to this later tonight

**Comment by orangepeelpanda** [comment]
tried the following things: still not fixed:

cast light on a different item
recast light on the half plate +1
sold the item to a vendor
tried resting in a different zone 

yet other items with the same infusion don't have the same issue.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1a26983c-fe5b-4775-841a-fd4a993ae9cb)

was able to rest after dropping any item with light cast on it on floor. Not sure why your save has this bug. won't fix as it happens in vanilla code.

**Comment by ThyWoof** [comment]
Bracers of Storm, The Half and the Full-Plate.

**Comment by orangepeelpanda** [comment]
yeah turning off the light cantrip then resting worked fine, i think maybe it has to do with the items casting light either ring of lightbringer or brightwall. thanks!
