### ISSUE TITLE
CloseQuarter does not work as intended sometimes in 1.5.94.53

### ISSUE THREAD

**Issue by tlpwka** [SolastaMods/SolastaUnfinishedBusiness#4361]
Works fine in 1.5.94.52 works fine.
In 1.5.94.53 sometime d6 is used instead of d8 (as saved)
[QuickSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14316839/QuickSave_3.zip)
[settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14316913/settings.zip)

**Comment by ThyWoof** [comment]
It’s very hard to debug sometimes. Do you have a deterministic step by step procedure?

**Comment by tlpwka** [comment]
> It’s very hard to debug sometimes. Do you have a deterministic step by step procedure?

I will test again tomorrow
