### ISSUE TITLE
Inventor Quick Wit doesn't appear to work

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4364]
![solasta quick wit](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/66443840/972af7c2-d7ff-4373-9af6-b5593fd54617)

see attached SS. 

Quick Wit should at 5 to the saving throw.

I rolled an 8, then a +6 from Dex (+4) and Studed Armor of Survival (+2) for a total of 14. a +5 from quick wit would have made it a 19 and should have been a save.

**Comment by ThyWoof** [comment]
Already fixed in dev, thanks
