### ISSUE TITLE
Taking spell marksman stops me from saving

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4365]
I leveled up, took spell marksman, couldn't save (save button was greyed out) 

98. - Spell Marksman
You learn one cantrip that requires an attack roll. Choose the cantrip from the bard, cleric, druid, sorcerer, warlock, or wizard spell list. When you cast a spell that requires you to make an attack roll, the spell's range is doubled. Your ranged spell attacks ignore half cover and three-quarters cover.

This feat.

**Comment by ThyWoof** [comment]
I cannot repro on my end. Unless you provide a save I cannot help.
