### ISSUE TITLE
Smite triggers inconsistently

### ISSUE THREAD

**Issue by Sextilidan** [SolastaMods/SolastaUnfinishedBusiness#4367]
Started a new playthrough yesterday.  
Level 3-4 Paladin character, I noticed I am very rarely getting Smite prompts when I perform a melee weapon attack and have spell slots available (maybe 1 in 8 attacks).  
After doing some reading I saw that this has been an UB issue in the past, perhaps the latest update impacted something, as I did not notice this behaviour yesterday.

**Comment by ThyWoof** [comment]
Please check under wiki how to properly report issues. Nothing I can do without at least a save.

**Comment by Sextilidan** [comment]
[No Smite Troubleshooting.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14331634/No.Smite.Troubleshooting.zip)

**Comment by Sextilidan** [comment]
UB version 1.5.94.54 
Solasta Version 1.5.94

**Comment by robvoid** [comment]
Did you turn on the option "only smite on crit"?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f84343be-693f-4e74-beda-0c7132027b17)
I was able to smite 3 times in a row. maybe fixed already on my dev build?

**Comment by ThyWoof** [comment]
I believe this bug was related with the issue on distance calculation. Instead of considering a cube within 5ft it's doing a cross. try on your end to attack not from diagonal to confirm, please.

**Comment by Sextilidan** [comment]
Thank you for looking into it.  
Can confirm that attacking diagonally does not trigger the smite prompt, but if I move once sell so that I have a common edge with the enemy cell, the Smite prompt comes up.  

I also remember at least 2 previous encounters where I was trying to prioritize a target that was diagonal from the paladin to clear up the area for Wizard and Ranger to move through and was frustrated that it didn't trigger.  
As soon as the priority target was dead I'd attack the nearest enemy, which happened to be non-diagonal, and I'd ask myself "why does it trigger now when I no longer need to burst this target?"  

I didn't even notice it had to do with the enemy positioning until you mentioned it.  

Would you like me to carry out any testing on Javelin smites?

**Comment by ThyWoof** [comment]
Fixed in dev.
