### ISSUE TITLE
cant

### ISSUE THREAD

**Issue by ArtelosX** [SolastaMods/SolastaUnfinishedBusiness#4369]
Im using the last version of the mod the before that one i was able to paly whit no problem's now when i open the game ther is and error massage that pop up and i cant continue play any old save and only open a new one 
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14335994/Player.log)
Mod version: 1.5.94.54
game Version: last one exist
![error 2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/160534698/453e8d00-b08c-403f-9019-d19b9b67aee9)
![error](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/160534698/9db24d01-2c5b-4ae3-873e-4d2ff750f4bb)

**Comment by ThyWoof** [comment]
Martial Defender was removed from mod. You should always read changelog before update. Only fix is to rollback to the version before it’s removed, respec hero of defender and into guardian (defender replacement) and then update again.

**Comment by ArtelosX** [comment]
thank you. 
can you tell me to what version do i need to rollback to?
