### ISSUE TITLE
Follow up to #4361: CloseQuarter don't work as intended sometimes in 1.5.94.54

### ISSUE THREAD

**Issue by tlpwka** [SolastaMods/SolastaUnfinishedBusiness#4370]
In current save:

- if sneak attack is made in saved position (triggered by subclass feat), CloseQuarter work as intended
- if sneak attack triggered by presence of an ally close to enemy, sneak attack still D6

1.5.94.52 still have consistent results D8 instead of D6 in both situations.
Kind regards.
[QuickSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14345789/QuickSave_2.zip)

**Comment by ThyWoof** [comment]
Had some issues with distance calc. This has been fixed in dev afaik. Can you confirm if close quarters work if not attacking from diagonal?

**Comment by tlpwka** [comment]
Yes, you are correct, work fine if not attacking from diagonal.

**Comment by ThyWoof** [comment]
Fixed in dev
