### ISSUE TITLE
Level 2 Smites not available

### ISSUE THREAD

**Issue by Sextilidan** [SolastaMods/SolastaUnfinishedBusiness#4372]
Hello again,

I am using the .dll with the hotfix for the diagonal smites.  
My paladin has reached level 5 and has 2 Level 2 spell slots available, but when I land a hit only Level I spell slot appears on the Smite prompt.

Attached is a save file in the middle of the paladin's turn. You can attack the  nearby enemy to observe the smite prompt.

[No Level 2 Smite.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14351018/No.Level.2.Smite.zip)

**Comment by ThyWoof** [comment]
Fixed in dev
