### ISSUE TITLE
Paladin / Warlock Spell Slot Delay

### ISSUE THREAD

**Issue by Soltronus** [SolastaMods/SolastaUnfinishedBusiness#4376]
I was leveling my Paladin 4 / Warlock 1 today to Paladin 5 / Warlock 1 when I noticed that my character did not gain any 2nd level spell slots. I could still select and choose 2nd level paladin spells to prepare, but had no slots to cast them.

In the character creator, I was able to replicate this result. Paladin spell slots, when multiclassed with Warlock, seem to come 1 level later than expected.

Pal 6 / War 1, for instance, has 2 2nd level spell slots, for instance.

**Comment by ThyWoof** [comment]
fixed in DEV.
