### ISSUE TITLE
Gloom Blade not working after updating.

### ISSUE THREAD

**Issue by GrowlingScarab7** [SolastaMods/SolastaUnfinishedBusiness#4378]
Was playing on version 1.5.94.53 and the gloom blade toogle was working just fine for necrotic damage. Updated to 94.55 and now even though its turned off, im not doing any necrotic damage with sneak attack.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/571f4c2c-e950-442a-9fc9-9ebf56725cc7)
there is nothing wrong with gloomblade.

**Comment by GrowlingScarab7** [comment]
My mistake, i reread the skill and saw it only applies to melee. Sorry about that. But that begs the question. My rogue has been using a bow all campaign and was doing necrotic damage on sneak attacks. Why would they even happen in the first place.
