### ISSUE TITLE
Feature request - reveal map fog of war

### ISSUE THREAD

**Issue by ixxbxxx** [SolastaMods/SolastaUnfinishedBusiness#4380]
Hi devs would you consider incorporating the above feature? What I mean is that for the area map (default hotkey 'm') that the entire map is shown rather than explored areas only.

Thank you!

**Comment by ThyWoof** [comment]
What’s the use case here?

**Comment by ThyWoof** [comment]
enable the cheats option under general / tools. use the official game cheat menu from there.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f9a251b6-fe7a-447b-b81a-99456499212e)

**Comment by ixxbxxx** [comment]
Thanks but this only partially works i.e. on the main screen the fog of war is removed but not on the map screen ('m' shortcut). Is it even possible to reveal fog of war on the map screen too?
