### ISSUE TITLE
Unable to learn spell in multi class of Paladin

### ISSUE THREAD

**Issue by jk2l** [SolastaMods/SolastaUnfinishedBusiness#4382]
If i try to learn spell from Paladin class during warlock level (e.g. Spirit Nimbus) it grey out and say spell known in paladin class. But my character level is warlock 5/ paladin/2 so it shouldn't know that spell already. Also i don't plan to take my paladin level to level 9. so it effectively denied my character access to the spell.

**Comment by jk2l** [comment]
p.s. this can sort of work around by disable this spell off Paladin spell list. so Warlock can learn it

**Comment by ThyWoof** [comment]
Use the option that allow re learn spells from other classes on mod UI.
