### ISSUE TITLE
Holding Shift doesn't use Warlock Spell slots when creating Sorcery Points

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4391]
Holding Shift doesn't use Warlock Spell slots when creating Sorcery Points.
Issue: Whenever my Sorcerer + Warlock holds shift when clicking the 'Convert' button to try to use the Warlock slots to create sorcery points, the game spends my regular spell slots
Result: White spell slots spent
Expected: Pact slots spent.
[Palace_Office_4.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14470293/Palace_Office_4.zip)

**Comment by ThyWoof** [comment]
This save isn’t good anymore on latest dev build as ring mail recipes got removed. I’ll keep on my radar and create a new save to test.
