### ISSUE TITLE
Exception when Inspecting or Using PreGen Characters

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4402]
I just performed a fresh installation of the game and the mod.
Without the mod, I can inspect any of the characters or start a new campaign just fine.
With Unfinished Business, I see the new icons for these characters, but if I try to inspect or use them, the game throws an exception.

Exception: "
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
"
There's my log. The exception in the stack trace isn't too far down into it.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14530973/Player.log)

**Comment by Pikachar2** [comment]
Quick comment: Characters created with this fresh install with UB seem to work fine. But if I import any old characters or use any of the pregenerated ones, I get the exception.

**Comment by ThyWoof** [comment]
Check my answer on other ticket. If you compiled from dev ring mail got removed. Most
Likely the cause.

**Comment by Pikachar2** [comment]
Fresh install from latest Release. And none of the characters i was using had ringmail.

**Comment by ThyWoof** [comment]
Delete your pre gens char folder and let game rebuild them.

**Comment by Pikachar2** [comment]
I have done that multiple times. Same effect.

**Comment by Pikachar2** [comment]
After much debugging. It turns out that the version of Unity Mod Manager I had was too new. 
Does NOT Work: Version: 0.27.11
Works: Version 0.24.2.0

Is there some way we can update the install guide to use this specific version?

**Comment by ThyWoof** [comment]
no.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/79a0a3f3-2c3e-41f1-8ca8-2b97f8c2923e)

problem is in your computer. I use 27.8. Haven't updated but 100% sure it'll work with 27.11.

**Comment by Pikachar2** [comment]
Can't just be my computer. I had 4 people with the same issue as me.

**Comment by Pikachar2** [comment]
Latest UMM "Updated Harmony to 2.3.1.1"
Would that cause an issue?
I just installed 0.27.9b (the previous to the latest) and it worked fine. So, there's an issue with that Harmony update.
