### ISSUE TITLE
Summons falls to death

### ISSUE THREAD

**Issue by Michael-Loke** [SolastaMods/SolastaUnfinishedBusiness#4404]
Did not happen in prior versions. Example: During combat, Inventor summons Protector and it dies immediately after summoning

Protector enters the battle.
Protector fell to their death.
Protector is now Dead

Have seen it on other class summon as well. Maybe intermittent (with failures more common than success)

**Comment by ThyWoof** [comment]
Without your save how am I expect to debug?

**Comment by ThyWoof** [comment]
Tried on my end as usual it works. CRPG games are very complex. All it takes is your hero have something that wasn’t considered and causing issues with this power. Again, nothing I can do without a save. UB is coming to an end so time matters. Get me your save ASAP otherwise if indeed a bug it won’t make on next release and probably not fixed anymore.

**Comment by Michael-Loke** [comment]
Save file

**Comment by Krayte** [comment]
I am seeing this also.  Every time I summon something I get prompted to cast Feather Fall by my Wizard.  If I don't the summon moves randomly a few squares over and falls over (sometimes off cliffs or whatnot.  If I cast Feather Fall then the summon stays where it is most times.  This is happening on 2 different plays throughs both is Lost Valley.
[QuickSave_5.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14548765/QuickSave_5.zip)

**Comment by ThyWoof** [comment]
I don't know what to say. Is this a custom or official campaign? I can confirm the bug on your save but not on mine.

I exported the Wizard and tested on my QA locations, different heights, and all works.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/58df7827-ee4b-4f53-b5d2-1368b749cac2)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/682d7cbb-ba2f-468f-8f73-1f0cf7f23913)
was able to repro on my end. It only happens during combat. Very strange.

Was this working on v55?

**Comment by ThyWoof** [comment]
@EnderWiggin , any ideas why this might be happening?
