### ISSUE TITLE
Can't load into game. girlfriend with same mod version can load into the same save.

### ISSUE THREAD

**Issue by Davidjans** [SolastaMods/SolastaUnfinishedBusiness#4406]
Hello, 
After switching from desktop to laptop whenever i load into my campaign or load any character into the selection during new adventure it gives me the error prompt. Whenever i create a new character it does allow me to select them into the new adventure selection.
If i uninstall unifinished buisiness it does allow me to select the pregen characters again. 
Whats weirder is that my girlfriend who is on the same game and mod version can fully load into the save file. (exporting her settings and importing them into mine doesn't fix it either)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14545958/Player.log)

**Comment by ThyWoof** [comment]
Your umm version isn’t compatible. Downgrade umm to 27.9

**Comment by Davidjans** [comment]
Well fuck thats about the only thing i didn't try. Thanks !
