### ISSUE TITLE
Impish Wrath causes game to crash.

### ISSUE THREAD

**Issue by Krayte** [SolastaMods/SolastaUnfinishedBusiness#4407]
If Impish Wrath is on (on an Imp obviously), after a successful melee hit with main weapon the game throws an error and the game stops allowing anymore actions.  Quit and reload game results in a CTD.  You can start it back up and load the save and turn it off to stop the error from occurring.
![2024-03-09_20-05-24](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/42162713/b94bc86b-55a8-4a4d-8315-5ce6c95ef661)

**Comment by ThyWoof** [comment]
fixed already in DEV branch. thanks.
