### ISSUE TITLE
Can't start game after Steam update

### ISSUE THREAD

**Issue by SonoTheDoc** [SolastaMods/SolastaUnfinishedBusiness#4410]
Hello everyone and thank you for the wonderful work you do every day.

I've just update to the 1.5.97 Public Steam version (with all DLC's), and whenever I try to start a new adventure or load a previous one, the game stop me with the "instability error"

I'm using UMM 0.27.11 with UB 1.5.94.56, any suggest?

Thank you for your time.

[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14551226/Solasta.zip)

**Comment by ThyWoof** [comment]
Don’t use umm 27.11. Not compatible as it updated harmony. Latest good one is 27.9
