### ISSUE TITLE
ATTENTION: latest UMM compatible version is 0.27.10. DON'T USE ANYTHING ABOVE

### ISSUE THREAD

**Issue by technochitlin** [SolastaMods/SolastaUnfinishedBusiness#4415]
0.27.10 seems to be NLA. Any suggestions?

**Comment by ThyWoof** [comment]
what the hell is NLA? Please no acronyms.

**Comment by UWImban** [comment]
"no longer available"
Anyway, just use 0.27.7.0, which is available.

**Comment by ThyWoof** [comment]
Thanks for clarifying. All UMM versions are available on nexus.
