### ISSUE TITLE
Circle of the Moon Druid can only wild shape once per short rest

### ISSUE THREAD

**Issue by Killerrez** [SolastaMods/SolastaUnfinishedBusiness#4418]
Solasta Latest Steam version 1.5.97 (is that right? or is the top right of the main menu displaying the mod version?)
Mod version 1.5.97.0
No other mods

A Circle of the Moon druid can only Wild Shape once per short rest. I started a new game just to be sure and confirmed that you can only Wild Shape once per short rest. 

Step 1: Wild Shape
Step 2: Un-Wild Shape (losing Wild Shape due to damage also works to recrate the bug.)
Step 3: Try to Wild Shape and notice that you can't.

[Character and save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14593895/Character.and.save.zip)

My log folder is empty and I don't know how to make a log file. I'm sorry.

**Comment by ThyWoof** [comment]
Depending on shape it’ll consume 2 points. Is it happening with any shape?

**Comment by Killerrez** [comment]
> Depending on shape it’ll consume 2 points. Is it happening with any shape?

On all three of the first shapes you can use yes. It shows they only use one.
