### ISSUE TITLE
Impish Wrath crashing

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4422]
here's the log and the save file, you have the pass turn and use the rogue on turn 2, activate impish wrath and hit a creature.

[imp wrath.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14602154/imp.wrath.log)
[impishwrath.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14602174/impishwrath.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/00406d64-4477-4983-bc68-28887fd37472)
cannot repro using your save. I suggest you check your game files, etc.
