### ISSUE TITLE
The Sorcerer metamagic ability and UI dissapears after reloading the save

### ISSUE THREAD

**Issue by Sunas99** [SolastaMods/SolastaUnfinishedBusiness#4423]
Solasta v-1.5.97
UB v-1.5.94.56

After learning metamagic on a sorcerer, saving and loading the game leads to the metamagic abilities to disappear from the UI and the character itself. 
**Please note this also seems to affect other features - example the fighting style that gives 1 gambit die Superior technique also is missing from a ranger character in another save.**
Only the sorcerer save was added as this was the most tested:
- The bug does not occur without the mod, 
-it does not seem to matter what class or race or metamagic you pick even if you pick the solasta original specific ones
steps to repro:
1. Make a sorcerer and reach lvl 3 
2. Rest and level up to choose metamagic options
3. Save and load after completing char 
Notice that the metamagic UI is missing and the ability is also missing from character profile

Extra note - I did receive an instability error when i restarted the Solasta game.

player log - [Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14602564/Player.log)
save file - [after reset.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14602574/after.reset.zip)
UB configuration-[Config.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14602589/Config.zip)

**Comment by ThyWoof** [comment]
Sorry but I cannot support 1.5.94.56 anymore. Update to latest version and open a new issue if problem persists. Keep in mind changelog is your best friend if you need to RESPEC anything.
