### ISSUE TITLE
Add more stronger feat

### ISSUE THREAD

**Issue by H0NGL0NG** [SolastaMods/SolastaUnfinishedBusiness#4433]
Solasta is stop update,
so should we add more stronger feat,
if u concern break the balance,
set the level limitation,
such as lv8 give rare feat[blue],
lv16 give legendary feat[red].

**Comment by H0NGL0NG** [comment]
rare feat:
1,fly
2,will not Prostrate
3,spide climb
4,will not blind

legendary feat:
1,all spell dice the biggest
2,action roll always get advantage
3,save roll always get advantage
4,add 1 action,add 1 reaction,add 1 reflex action

**Comment by ThyWoof** [comment]
Thanks for the suggestions but I don’t plan to add anything non tabletop anymore.
