### ISSUE TITLE
Game not loading saved files

### ISSUE THREAD

**Issue by LaserBeetle** [SolastaMods/SolastaUnfinishedBusiness#4434]
I'm using Solasta and the mod versions 1.5.97.0, but did try to remove the error using UB version 1.5.94 and 1.5.97.1

When trying to resume a gaming session by loading a saved game, I get the inconsistency error message and the game just stays on the loading screen forever.

I open the game, close the mod window, click Continue (or Load Game, neither work) and try to resume playing, when the error message appears and the loading screen never ends.

I can't seem to upload all of the files you asked for, so I'm attaching the UB folder with everything in it.

[Solasta - Copy.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14627186/Solasta.-.Copy.zip)

**Comment by ThyWoof** [comment]
Please check change log. On 1.5.97.0 I had to remove ring mail recipes and items. Most likely one of your heroes have a ring mail. Downgrade to 1.5.95.56, remove these items, upgrade and try again.

**Comment by LaserBeetle** [comment]
Right, that seems weird because I started playing on 1.5.97.0, but I'll try. However, I can't seem to find 1.5.95.56 on your releases, the earliest is 1.5.94.56, I'll try that since it must be the one you were going for.

**Comment by ThyWoof** [comment]
It’s the same error message related with umm 27.11. Try umm 0.24.x
