### ISSUE TITLE
Ranged Expert feat missing and not documented as being removed in change log. Broken? Removed?

### ISSUE THREAD

**Issue by KDark99** [SolastaMods/SolastaUnfinishedBusiness#4436]
Game version 1.5.94Final & 1.5.97Final (tried both)
mod version 1.5.94.33 has Ranged Expert feat in mod feats list and works in game.
mod version 1.5.97.1 Ranged Expert feat is no longer listed in mod nor shows in game.

**Comment by ThyWoof** [comment]
Renamed probably as many other blueprints on 1.5.97.0. Some incorrectly got hidden but came back on 97.1.

**Comment by KDark99** [comment]
I have looked through all of the feats of the latest version and none of them now show a description of the effect of allowing ranged attacks when in melee without disadvantage that Ranged Expert had. So something is missing.
