### ISSUE TITLE
Power Attack Bug

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#4444]
Power Attack results in null reference.
Just use the bugged hero and turn on power attack. The game freezes when a combat starts.
[Characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14721386/Characters.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/062e5e5a-7a94-4b47-baab-af35d321b401)

cannot repro at all using mentioned hero.
