### ISSUE TITLE
grenadier subclass acid bombs not working correctly

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4446]
it only applies to the acid bomb variation. precise attack does not require the constitution save and all 3 forms of attack will inflict acid burn and then is immediately removed on same instance.
this is not happening with any of the other elemental types

[acidbomb.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14726317/acidbomb.zip)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14726319/Player.log)

**Comment by ThyWoof** [comment]
precise attacks don't require save AFAIK. all bombs use same method to build precise. all that changes is damage type. Others fixed.
