### ISSUE TITLE
Merciless Fighting Style Causes Instability

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4448]
Occasionally when killing an enemy, an instability will pop up.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14733954/Player.log)
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14733956/AutoSave_1.zip)

Again, it's not consistent. In that save, a wolf was killed after an Ogre and the instability appeared upon the wolf's death. 
The game doesn't stop or anything, but the warning pops up.

**Comment by ThyWoof** [comment]
Found something related to merciless. Did a minor change on my end but hard to test. Please test on next release and reopen this if still an issue.
