### ISSUE TITLE
War Caster Attacks of Opportunity not resolving until enemy is done moving.

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4456]
War Caster Attacks of Opportunity do not resolve until enemy is done moving.

Expected: Spell Attack of Opportunity resolves before enemy leaves melee range.
Actual: Spell resolves when enemy finishes moving.
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14738266/AutoSave_1.zip)

Character with War Caster is: Cleric (name: Gideon)
Spell Usually used: Booming Blade

**Comment by ThyWoof** [comment]
This is a game engine limitation. If I make it resolve before the attack isn’t computed. Nothing I can do here.
