### ISSUE TITLE
player.log file shared as requested

### ISSUE THREAD

**Issue by ballentinems2** [SolastaMods/SolastaUnfinishedBusiness#4464]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14781616/Player.log)

**Comment by ThyWoof** [comment]
Pretty hard without a context. Can you please explain what happened?

**Comment by ThyWoof** [comment]
Well, don’t use umm 0.27.12. Check all warnings about it on Reddit, nexus and install page here on wiki.
