### ISSUE TITLE
artificer infusions not canceling and not working 

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4469]
terminated the add minor elemental (acid) and returning weapon then applied bloody and returning weapon instead to same weapon am still getting acid damage from previous infusion and bloody will only apply if weapon is thrown. also the icon for bloody is just a white square

1st result attack in melee range
![Screenshot (33)](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/143920371/dba58902-b3ee-4bdc-a4b1-814530b3a7cb)

2nd attack thrown
![Screenshot (34)](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/143920371/2cc770ea-ddfe-48b4-908a-a80ec60147b7)

neither one of those should be applying acid damage anymore
And to clarify, those were 2 separate 1st attacks for their turn not a 2nd attack on the same turn 

[bloody clash.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14795597/bloody.clash.zip)

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14795606/Player.log)

**Comment by ThyWoof** [comment]
@EnderWiggin , can you give a hand here?

**Comment by ThyWoof** [comment]
I cannot repro this except for the square icon on a brand new save.
