### ISSUE TITLE
Certain character actions disappear from UI upon load

### ISSUE THREAD

**Issue by WeaponsPrime** [SolastaMods/SolastaUnfinishedBusiness#4475]
Encountered on Sorcerer with metamagic (the button simply disappeared) and Artificer with infusions (the button disappeared, no infusions were present in the character tab, no could be unlearned upon levelup).
Mod version: 1.5.97.2
Save file (sorcerer only, dropped the artificer one): [3-1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14808895/3-1.zip)
Log file: [Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14808905/Player.log)

**Comment by ThyWoof** [comment]
Read the wiki, install page. Validate your UMM version.
