### ISSUE TITLE
bug - fighting styles are now selectable as bonus feats

### ISSUE THREAD

**Issue by ixxbxxx** [SolastaMods/SolastaUnfinishedBusiness#4477]
Not sure since which version but fighting styles are now listed as selectable bonus feats i.e. whenever you reach a level where you can select a bonus feat, the fighting styles show up in the list of feats e.g. 'two weapon fighting' 'great weapon fighting' 'archery' etc.

Clearly you don't need a save game to test as it is even replicable in the main menu by leveling up a character to a level where you can select a bonus feat e.g. 4, 8, 12 (or 10 for rogue).

**Comment by ThyWoof** [comment]
Clearly you haven't enabled feat groups on mod UI. No bugs here.

**Comment by ixxbxxx** [comment]
Yes I haven't enabled it but why must I enable it, I thought every option is 'optional'? So you mess up the default feats to include fighting styles and this isn't a bug? The only way to 'fix' this for me is to disable the mod but that doesn't seem like the right solution - mess up the default game but it's not a bug. Strange.
