### ISSUE TITLE
Windigo Lunger fails to increase reach after cantrip attack

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#4483]
Say you have a spellblade sorc and cast booming blade as your first attack, but your reach for second attack is only 5 ft regardless of lunger feature.
[bugchar.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14814335/bugchar.zip)

**Comment by HIEROT** [comment]
i am not very familiar of this set of mechanics so want to see if it's easier for you to check it

**Comment by ThyWoof** [comment]
I would check https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/dev/SolastaUnfinishedBusiness/Behaviors/UpgradeSpellRangeBasedOnWeaponReach.cs

**Comment by HIEROT** [comment]
this part is fine, the second normal weapon attack is bugged.

**Comment by ThyWoof** [comment]
Only one of the cantrip attacks has a second attack. That one specifically says within 5 ft of first target. It seems to work as expected

**Comment by HIEROT** [comment]
no i mean the sorc with lunger has multiple attack feature so he can attack 2 times in a main action and can replace one of his attack with a cantrip. after the cantrip is cast, he can no longer reach enemy within 10 ft for the second attack.

**Comment by ThyWoof** [comment]
This is very strange as lunger should trigger on any attack. Unless some cache issues or improper attack mode modification. Will have to debug that.

**Comment by ThyWoof** [comment]
not sure I can repro:

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/620722ad-37b3-4345-9b46-60241533c7b0)
this is correct. Sorcerer has reach 2 and cannot get to Thug.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5074bcc2-bab4-41ea-b0b7-050d72e2f16f)
used Booming Blade on Orc. After that can still target Orc for a 2nd attack.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1a52b125-468f-4318-a62a-f4c5eb0c87b4)
was able to attack.
