### ISSUE TITLE
fighting styles now become feats? how is this not a bug? 

### ISSUE THREAD

**Issue by ixxbxxx** [SolastaMods/SolastaUnfinishedBusiness#4484]
![20240331141323_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/38359791/e8683eef-a393-4fec-b300-42145f181182)

**Comment by ThyWoof** [comment]
You refuse to share logs. 3rd time you open the same issue nobody else can reproduce. Blocked from github.
