### ISSUE TITLE
Aura of Life stays in place when wildshaping

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4488]
Moon Druid cast Aura of Life and then Wildshaped into Gorilla and ran to meet an enemy. Aura stayed in the original place the character was at and did not move with character.

Druid: Cassandra
[TheBoyz Combat.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14818296/TheBoyz.Combat.zip)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14818299/Player.log)

**Comment by ThyWoof** [comment]
Vanilla was cancelling any spell when WS. Mod touches that to allow Wall type spells to work. Won't fix this one as wildshape was a hack introduced by the original game developer. Quite difficult to patch.
