### ISSUE TITLE
Merciless Causing Instability

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4489]
When character with merciless kills an enemy, the first time per fresh load it causes an instability.
Mod Version: 1.5.97.2

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14818375/Player.log)

Character: Thor
Closest save I had before the fight. It's the one in the crown room against the fire Elementals.
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14818377/AutoSave_1.zip)

**Comment by ThyWoof** [comment]
Unfortunately this one is very situational. Cannot repro so something with this particular hero or save. Won't fix.

**Comment by Pikachar2** [comment]
In that first save, it's not triggering at all either. None of the enemies are making the saving throw for fear. 
In this new one it's not triggering from the square of the downed target, but from the square of the character with the Merciless fighting style. 
[MercilessCombat2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14819038/MercilessCombat2.zip)
It's the Paladin's turn (the character with the Merciless Fighting Style). If you kill the enemy from where he's at, Merciless does not trigger. If you move to the square where he's got a goblin on 3 sides, and kill the low hp enemy, the remaining two make the save.
I want to try to see if there's a multiplayer aspect to the crash I'm having, but I wont be able to test that until tomorrow evening.

**Comment by Pikachar2** [comment]
I managed to get somebody to test just before work. And it looks like it's a multiplayer issue.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14823653/Player.log)
Same save as the above comment.
