### ISSUE TITLE
vitrolist subclass adding pb acid damage to all attacks

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4491]
[acid.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14824196/acid.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/cb6e9fe0-ff7e-47e3-bc6e-dff4dbe9ca92)
fixed.
