### ISSUE TITLE
Game fails to load save game, gives error message.

### ISSUE THREAD

**Issue by BeardlessDwarf** [SolastaMods/SolastaUnfinishedBusiness#4495]
Went through the game with 1.5.97.2. Updated to 1.5.97.3. Previous save file refuses to load.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14843427/Player.log)
[A.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14843456/A.zip)
[Characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14843482/Characters.zip)

**Comment by ThyWoof** [comment]
You have used an incompatible UMM version at some point. This error message is the same caused by that. I suggest fully removing the mod and UMM from game and reinstall umm 0.27.10 and mod from zero.

**Comment by ThyWoof** [comment]
There might also be a chance these heroes and saves are broken if you ever used a bad umm version. If after above you still face the issue there isn’t much else I can do to help.

**Comment by BeardlessDwarf** [comment]
Yes, I previously used the latest UMM version, which is 0.27.13, and that was the issue.
