### ISSUE TITLE
Interface de Feitiços Bugando

### ISSUE THREAD

**Issue by Rs-Gui** [SolastaMods/SolastaUnfinishedBusiness#4499]
Olá tudo bem, sou novo na area de mods, estava jogando com a classe de feitiçeiro e me deparei com um problema... Estava jogando com alguns mods e meu feitiçeiro tinha feitiços demais e isso acabou bugando a interface de feitiços. (basicamente alguns feitiços acabam ficando para fora da tela) não sei exatamente como consertar isso mas creio que um sistema de rolagem na interface dos feitiços ja seja otimo, por exemplo na "aba" de feitiços de nivel 1 apareçam no maximo 6 feitiços e os demais apareçam rolando uma barra para o lado ou para baixo igual fazemos para ver o resto de uma pagina que estamos lendo na web

![bug](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/165702743/aff19ac5-4e2f-411b-8dff-4919df3e1f4f)

**Comment by ThyWoof** [comment]
Você não deveria ter tantos feitiços. A interface não foi feita para isso. Basta não abusar na atribuição de feitiços no mod.

**Comment by Rs-Gui** [comment]
ok, apenas uma sugestão.
