### ISSUE TITLE
Sem Gasto de feitiços

### ISSUE THREAD

**Issue by Rs-Gui** [SolastaMods/SolastaUnfinishedBusiness#4500]
Uma sugestão, poderia existir alguma opção de não gastar espaços de feitiços, por exemplo eu podeira conjurar infinitos feitiços de nivel um desde que eu jogue infinitos turnos (lançando um feitiço em cada turno porém tendo espaços de magia infinitos)

**Comment by ThyWoof** [comment]
Thanks for suggestion but very low priority.

**Comment by Rs-Gui** [comment]
Poderia me dar um caminho sobre o que estudar em programação para conseguir fazer essa alteração?
