### ISSUE TITLE
2024 Controller Issue: Battle Unplayable Choosing Powers/Spells (Spell Broken)

### ISSUE THREAD

**Issue by AverageVideoGameJoe** [SolastaMods/SolastaUnfinishedBusiness#4501]
**UMM version: 0.27.10.0
Mod version: 1.5.97.3
Solasta Version: 1.5.97.0**

Controller: Xbox Series X controller / PS4 Pad / PS5 Pad

Hello,

I have successfully installed UB into my game; my current saves however do not allow me to select spells appropriately during battle or exploration with a controller; this "bug" was previously reported in older issues here at Github, and I believe has something to do with how multiline display is handled for the game (I'm just trying to use vanilla spells at this rate). I've had to turn off the mod completely to restore original functionality (https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/2680). Rollbacking did not do anything either.

The rest of the mod works fine/as intended. Please let me know if there's a workaround I can deploy; I'm only generally able to play a controller for my PC games and would love to play with the UB mod more.

See attached for available logs/save data.
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14864998/Player.log)

Save file: 
https://ufile.io/54nkvj9m

LEt me know if there's specific log files you need. Thank you!

**Comment by AverageVideoGameJoe** [comment]
Just to clarify: This issue still occurs having the mod installed w/ no enabling of settings.

**Comment by ThyWoof** [comment]
This issue also happens in vanilla depending on how the spells are laid out. Unfortunately won’t fix.
