### ISSUE TITLE
Savegames broke due to UMM auto updating

### ISSUE THREAD

**Issue by smiledozer** [SolastaMods/SolastaUnfinishedBusiness#4502]
Yeah so UMM updated automatically, and since there only was a prompt inside the mod ui to update UB with no warning that an update would break my saves, i've lost everything. I am very sorry that happened.

That's probably just life, so my question is, what do i do then? i can't find an older version of UMM, so am i just locked out from using UB until you find a fix for it? And why would you add the possibility to update within UMM, knowing that would obliterate peoples saves? thanks

**Comment by ThyWoof** [comment]
Only reason for your saves to be broken is if you used an incompatible version of Umm. Unfortunately the big bold notice stating that isn’t read by everyone which leads to that.

I didn’t obliterate your save. You did by not fully reading the install instructions. All UB versions are also available under releases and you can also rollback from mod UI.

remember, “the price of freedom is eternal vigilance”. Don’t blame others for your own faults. Take responsibility in life.

**Comment by ThyWoof** [comment]
Also mod won’t update umm install. User must click update for that to happen
