### ISSUE TITLE
Two characters from four always overlap when talking

### ISSUE THREAD

**Issue by FanFanMi** [SolastaMods/SolastaUnfinishedBusiness#4503]
The versions of Solasta and this mod.
SolastaUnfinishedBusiness-1.5.97.3.zip
GOG 1.5.97

A list of other mods you have installed [you shouldn't have any].
UB and that's it. 

A short description of the bug.
Each time I am in a dialogue, two of the characters overlap eachother, like in the following printscreen: https://prnt.sc/bULDk8DJexog
On the left the girls are overlapping, it happened in multiple saves since I keep restarting. To be noted, I've edited the hell of the characters before starting the game, not in the save, including using Cheat Engine so I don't have to take all spells. 

A step-by-step procedure to reproduce it.
Chat with a merchant, or whatever person you want, it happens often for me. The screenshot is from talking with the merchant Priest of Maraike in front of the Legacy Council.

The save, character and log files (check HINT below).
[MAIsave2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14877727/MAIsave2.zip)
[Characters.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14877729/Characters.zip)
[Solasta.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14877743/Solasta.zip)

PS: Seems to me that my former wife has a quarrel with a former girlfriend and keep stepping on eachother :))

**Comment by FanFanMi** [comment]
Lol, after having this in multiple saves, somehow after restarting the game it doesn't happen anymore.... Wot!!!

**Comment by ThyWoof** [comment]
Don’t enable the option under game UI that renders hero 5 and 6 on narrative sequence.

**Comment by ThyWoof** [comment]
The other option that will provoke that in official campaigns is the recently added use hero with higher skill.

**Comment by FanFanMi** [comment]
Thanks mate, will try it tomorrow.

**Comment by FanFanMi** [comment]
Hero with higher skill option fixed it. Thank you.
