### ISSUE TITLE
Barbarian rolling wrong save

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#4506]
My level 2 barbarian (i.e. no subclass yet) was attacked with Sacred Flame. He rolled a Strength save with advantage. The advantage is correct (barb feature) but it should have been a Dexterity save.
![barb](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/129558095/dedf282b-1efc-46d8-9890-ea63813ad071)
[barb_save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14898729/barb_save.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/66545aa6-bcba-4240-a687-702161c84417)
fixed.
