### ISSUE TITLE
Enhanced Arcane Focus not ignoring cover as described

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#4507]
My artificer has the Enhanced Focus infusion on his own staff. He took a 3/4 cover penalty (-5 to attack roll). Description of the feature is that it ignores cover.

Will test for partial cover (normal penalty is -2 to attack roll, which should be ignored).

[artificer_save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14898744/artificer_save.zip)
![artificer](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/129558095/7a5f9232-5c6d-4e62-87a2-bca3f646a968)

**Comment by x2f01101011** [comment]
Can confirm issue occurs with half cover (-2 penalty) as well. In attached screenshot, disadvantage is correct (artificer has adjacent enemy) but cover penalty should not be happening.
[partial_cover.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14898922/partial_cover.zip)

**Comment by ThyWoof** [comment]
Fixed.
