### ISSUE TITLE
Celestial Warlock's 1st level ability is missing

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#4515]
Healing Light, the ability that generates a pool of healing hit dice, is missing and can't be used as of the latest update. You can see this for yourself on a 1st level character, but I also have this save file at level 8 that you can reference.

[dark promise.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14952482/dark.promise.zip)

**Comment by ThyWoof** [comment]
Share a player log as well.

**Comment by miridistress** [comment]
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14952696/Player.log)
