### ISSUE TITLE
battle master overcome strategy not awarding dice on ally kill before next turn

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4521]
this is the only one i've been able to/had time to re-create so far of the couple that i mentioned the other day. 

[no dice.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14984971/no.dice.zip)

in that situation there, the bandit has already been damaged by a superiority dice type attack, just need to finish him off before the fighter's turn

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/f0fcc7d6-b1e4-444d-928f-1671cc11a8eb)
fixed

**Comment by PrOZacKU3** [comment]
But that's showing the fighter killed the enemy not an ally. It's still working properly if the fighter gets the kill. Actually on that note, it doesn't matter what round the enemy gets killed by the fighter, it will still add a dice. I don't know if it's supposed to be on the same turn or not for that part, the description just says kill an enemy hit by superiority dice, or an ally before next turn
