### ISSUE TITLE
Wendigo loses bonus melee range after cantrip attack

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4523]
I am currently playing a level 9 Wendigo Fighter - Eldritch Knight.

If you only use melee attacks, you can attack from 10 feet.  If you use a cantrip, your melee range is reduced to 5 feet, for remaining actions and bonus action.  This lasts until next turn, you action surge, change weapon set, or opening inventory and picking up/dropping the weapon back in its slot.

[My Mod Settings](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14995534/xanthic.xml.zip)

[Current Map (Dun Cuin)](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14995552/Dun.Cuin.json)

[Save on supplied map](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14995594/bugged.sav.zip)
```
To reproduce;
load supplied save
perform a cantrip attack
attempt to use melee attack and see that game wants to move you
swap weapon set and see that you can attack from original position again
```

Edit: This is with latest mod version

**Comment by ThyWoof** [comment]
this is current a limitation we have. a best workaround is to open/close the inventory panel. the attack gets refreshed this way as well. won't fix.
