### ISSUE TITLE
Mountain Warlock Barrier of Stone

### ISSUE THREAD

**Issue by MarinerEarendil** [SolastaMods/SolastaUnfinishedBusiness#4525]
Level 6 Mountain Warlock Barrier of Stone does not seem to reduce incoming damage.  Seemed to work fine before level 6 so maybe there is a difference when the ability gets changed?

To reproduce just use the ability after an ally gets hit.  Current mod version (1.5.97.4)

[AutoSave_3.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14998586/AutoSave_3.zip)

**Comment by ThyWoof** [comment]
I haven't tested at all as a quick static check on code told me power at 6 wasn't applying the cond from power at 1.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/001615a6-6fd3-40c4-b4a8-08c424bb3aee)
