### ISSUE TITLE
Hurl Flame (Produce Flame) doesn't benefit from Potent Spellcaster

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#4541]
Hurl Flame doesn't benefit from Potent Spellcaster, and if you hold the flame and then throw it later, the spell doesn't benefit from the increased damage dice from your character level, either.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15052501/Player.log)
[Character.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15052503/Character.zip)

Log and character file included.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/a46a5717-3915-47c5-b324-f8364c0f11c1)
