### ISSUE TITLE
Lvl 14th Path of The Reaver Barbarian Feature dont work

### ISSUE THREAD

**Issue by Sebbelutti** [SolastaMods/SolastaUnfinishedBusiness#4552]
The lvl 14 "Corrupted Blood" subclass feature doesnt seem to work on enemies and instead trigger on myself i take the ekstra necrotic damage each time and enemy strikes me. 

[Corrupted Blood not working.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15112156/Corrupted.Blood.not.working.zip)

**Comment by ThyWoof** [comment]
Fixed in dev. Wrong order on attack method. Thanks.
