### ISSUE TITLE
Lvl 14th Thespian Bard feature dont work

### ISSUE THREAD

**Issue by Sebbelutti** [SolastaMods/SolastaUnfinishedBusiness#4553]
Whenever i kill a creature and the surrounding enemies roll a WIS saving throw, they dont take two bardic dice in damage when they fail the save.

I've attached a test area map i made where i tried it out

[test area.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15112817/test.area.zip)
[Improved Terrific Performance.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15112823/Improved.Terrific.Performance.zip)

**Comment by ThyWoof** [comment]
Won’t be able to look into this until later today. From a quick check code is using a vanilla attr to replace dice. Can you also share screenshots and logs? Step by step to repro?

**Comment by Sebbelutti** [comment]
I just tested it again with a lvl 20 bard, so no multiclassing should interfere. As you can see from my screenshot i've attached, my bard kills a Bulette which triggers "Terrific Performance" on the Storm Giant & Greymane Minotaur. The Storm Giant then fails the saving throw and gets frightened but doesnt take any additional damage.
![20240425230255_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/149318022/35e74be2-9f7c-4504-abab-6dc7e69cd87e)

**Comment by ThyWoof** [comment]
Can these enemies perceive the Bard? I believe this is the case here.

**Comment by ThyWoof** [comment]
Found the problem. Passing the wrong power here. Easy fix:
https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/862335b4b613633e0758ecff9efe7441d11d9f60/SolastaUnfinishedBusiness/Subclasses/CollegeOfThespian.cs#L169
