### ISSUE TITLE
Switching off UB and opening campaign created using it destroys campaign

### ISSUE THREAD

**Issue by RecklessCharger** [SolastaMods/SolastaUnfinishedBusiness#4558]
So I created a campaign using unfinished business. I am also playing a separate multiplayer game without it with friends. I forgot to reenable UB before opening my own campaign and now the UB campaign appears to have been destroyed (hours of work). I didn't hit save when I opened the campaign without UB enabled so don't understand why its altered it. Anyway I can save my campaign or is it lost?

**Comment by RecklessCharger** [comment]
This is using UB 1.5.97.5

**Comment by ThyWoof** [comment]
Game will automatically delete any assets it cannot find from campaigns on game load. Best you can do is check the backups UB makes on campaigns whenever you save them. Backups folder next to mods folder.

**Comment by RecklessCharger** [comment]
Ok thanks. I already did this before you commented. I found UserContentBackup in my Steam>steamapps>common>Slasta_COTM>Mods>UserContentBackup folder and copied the most recent version with a larger file size to AppData > LocalLow > Tactical Adventures > Solasta > UserContent > Campaigns, then renamed it as appropriate. This seems to have worked. Any idea when Solasta saves the backups (and how long are they kept)? I think you should perhaps include a warning in the documentation about this. As it happens I also have a backup on an external drive but its a few days out of date so and the UserContentBackup is actually more recent (earlier today).
