### ISSUE TITLE
bug) Fighting Style Dueling

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4559]
Fighting Style Dueling: "When you are wielding a melee weapon in one hand and no other weapons..."
But it's not working properly right now.
![1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/b28202cc-7cbf-414b-b82a-fbd90606856e)
![2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/6d5919be-56d6-4ccd-b6a4-b6585b3e9ffa)
![3](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/67a06f67-b7ef-467f-b93a-06bac29cf8e4)
![4](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/c6704f0e-a518-46ec-9a1f-2f404726418c)
![5](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/42b0f50b-07a7-4e4f-918f-eba9389866f9)

Contrary to what is stated, a duel does not work if the opposing hand is empty.

**Comment by ThyWoof** [comment]
I cannot help without a save or hero.

**Comment by kdgmo** [comment]
https://drive.google.com/file/d/10vJlTPCGwKUYM2g1ee1AtnDB7S3iy9af/view?usp=drive_link
save file
