### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by yingyue599** [SolastaMods/SolastaUnfinishedBusiness#4560]
The game crashes when opening a new adventure, Ice Palace, and importing a save
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15137492/Player.log)

**Comment by ThyWoof** [comment]
Only workaround is try to rest on save and get rid of any effects before trying to import. If that doesn’t work export the heroes using ctrl shift e and start a new game with them.
