### ISSUE TITLE
Crusader's Mantle freezes game

### ISSUE THREAD

**Issue by resumeman** [SolastaMods/SolastaUnfinishedBusiness#4567]
I used Crusader's Mantle for the first time (several times, in different locations). Upon activating it,  I go the "Solasta has detected an instability" dialogue and the action never completes (the UI never comes back).

[Mantle.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15173811/Mantle.zip)

**Comment by ThyWoof** [comment]
It looks like the effect chosen for this spell is causing that. Effect removed.
