### ISSUE TITLE
Druid Wildshape cannot select the type of melee attack.

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4568]
The brown bear has two types of melee attacks, but can only attack one type when transformed. In the case of a transformation that attacks twice, you can only attack with a different type after the attack.
![1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/36f026fa-800f-4d73-b693-9ab147a77223)
![2](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/0bf62378-9e1d-4999-82ce-5bf44c2b16da)
![3](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/8d13dffe-6627-431d-9261-1cb0808a5871)

https://drive.google.com/file/d/1R96Frak8qCNrR1dFNs7G7fXZ2lhq0c1X/view?usp=drive_link

**Comment by ThyWoof** [comment]
This is vanilla. Not related with mod.
