### ISSUE TITLE
Followed install instructions but am recieving "error" and "needs restart" on the UnityModManager window

### ISSUE THREAD

**Issue by hugh-jaccident** [SolastaMods/SolastaUnfinishedBusiness#4574]
![image_2024-05-04_001737356](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/168841600/772a4627-c0c4-4a10-94e5-d46ee5d580ed)
my game install is brand new so there are no logs or characters, and I honestly can't figure out how to check what version of the game I have, mod version is 1.5.97.5

**Comment by ThyWoof** [comment]
You haven’t followed the instructions otherwise you would had avoided installing an incompatible UMM version. There is a link on install guide for the one that works.

**Comment by hugh-jaccident** [comment]
I used the link on the install guide, it leads me to that version of UMM, I even uninstalled and reinstalled to make sure.
