### ISSUE TITLE
It is better to have Shield Expert as a feat rather than a fighting styles.

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4579]
Shield Expert performs worse than Monastic Shield Training.
Still, it takes up Fighting Styles rather than just one feat.
If this is a feat, it can be used in conjunction with Two-Weapon Fighting, which must be used simultaneously.
Monastic Shield Training does not require two-weapon fighting.

**Comment by ThyWoof** [comment]
You can always pick a FS as a feat. Won't change.
