### ISSUE TITLE
Artificer Quick Wit

### ISSUE THREAD

**Issue by baemaximus22** [SolastaMods/SolastaUnfinishedBusiness#4583]
In a friend's game At level 7 you gain Quick wit free action for Artificer/Inventor explaining that you can use a reaction if an ally fails a saving throw lower than intelligence modifier up to (intelligence modifier) times per long rest. Using +4 modifier has only allowed me only two reactions as if its using it twice in that same reaction when showing at least 4 slots on screen. Solasta version 1.5.97 no other mods installed
Enemy attacks ally with a saving throw following
Use quick wit reaction for a successful saving throw
Quick wit appears twice in combat log followed by the result of the reaction
![twice quik wit](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/169104865/6f9a45f2-c72a-4c22-a9cf-1eee462ba2af)
![plus 4 modifier](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/169104865/99c19c1b-5966-4f1f-852b-ee0cbebb2a44)
![Quick witty](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/169104865/46dd031c-c88b-4cbe-b747-015ef1311ea0)
[Baemaximus.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15227430/Baemaximus.zip)

**Comment by ThyWoof** [comment]
fixed, thanks.

**Comment by baemaximus22** [comment]
Its fixed, thank you so much!
