### ISSUE TITLE
The game keeps forgetting which heroes are to be controlled by the AI

### ISSUE THREAD

**Issue by apeanobono** [SolastaMods/SolastaUnfinishedBusiness#4587]
Steps to reproduce:
1- enable "heroes controlled by the computer" and set which heroes are to be controlled by the AI
2- move to a different area by traveling on the world map or using a door that trigger a loading screen.

Expected result:
the game remembers which heroes are to be controlled by the AI

Actual result:
The game forgets which heroes are to be controlled by the AI and defaults to all heroes controlled by the player

**Comment by ThyWoof** [comment]
This is expected as each combat could have a different set of heroes. Not a bug.

**Comment by apeanobono** [comment]
I see. 
Would it be possible to add a way for the game to remember which heroes are set as AI controlled?
It is quite annoying to have to re-toggle the settings every time.
