### ISSUE TITLE
Wither and Bloom is all bloom no wither

### ISSUE THREAD

**Issue by PeppersBoop** [SolastaMods/SolastaUnfinishedBusiness#4588]
Latest version of Solasta + Latest version of UB 1.5.97 (My coop partner posted an issue yesterday for the flash of genius issue)

No other mods

Wither and bloom, regardless of level, ally, fight, map, etc, only gives the bloom portion of hit die usage and never the damage.

Step by step to reproduce> Possible need multiplayer, target ally with wither and bloom,  ally must use bloom quickly or the game seems to break and not do anything (we worked out that if the ally instantly clicks their hit die it works flawlessly, but breaks if they delay), hit die used and target heals > no damage on any  nearby targets.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/169193713/6973d564-3af1-4eec-9fb4-eb22ec81a6a5)

A screenshot incase it helps

**Comment by ThyWoof** [comment]
Share this save pls. Also, does quick wit work now?

**Comment by PeppersBoop** [comment]
I sent it via discord, hope thats okay as github is telling me its not supported. Quick wit works great now! thank you vm

**Comment by ThyWoof** [comment]
I’ll try to fetch from there. You can always zip to attach here.

**Comment by PeppersBoop** [comment]
[two save zip.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15239996/two.save.zip.zip)

That makes alot of sense! Sent now, the autosave is in the middle of battle in m yscreenshot, and the other save is the start of our day near razan and stuff

**Comment by ThyWoof** [comment]
Indeed I cannot repro at all in my end. Could it be a MP issue but I cannot test MP. Cannot fix.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/2e370114-d7a3-4b41-9ff3-e2afc24bfbaf)

**Comment by ThyWoof** [comment]
I know but as I mentioned before, I have no way to test any MP scenario. Better not use it in MP sessions until I get a good log to determine the issue.

**Comment by ThyWoof** [comment]
Still not fixed in v8 but today was able to start a MP session. V9 will have the fix.

**Comment by PeppersBoop** [comment]
Oh wow I wasn't expecting a fix, was going to be entirely okay if it was undoable and leave it for single player! This is fantastic news, if there is anything I can do to help with any files or testing needed please let me know!

**Comment by ThyWoof** [comment]
All I need is confirm baleful under MP. This one is sound.
