### ISSUE TITLE
Error trying to level Sorcadin

### ISSUE THREAD

**Issue by resumeman** [SolastaMods/SolastaUnfinishedBusiness#4592]
This has actually happened in the past as well - but I've also done it successfully.

I have a paladin, took 2 levels of warlock, and then 1 of mana painter sorcerer. I tried to level to 2 Sorc, and I got the game instability warning. Character was going from 15>16.
(turned out the adventure was over - after leveling up the campaign exited)
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15257897/Player.log)

**Comment by ThyWoof** [comment]
Fixed
