### ISSUE TITLE
Can't save (some campaigns)

### ISSUE THREAD

**Issue by resumeman** [SolastaMods/SolastaUnfinishedBusiness#4593]
So just after I posted my last issue the campaign ended, so I tried to start a new one. 

I tried the second Shire Child (Southern Belle). I am unable to save. Bringing up the menu the save button is greyed out. Just hitting F5 a message "cannot save now" appears.

I tried a couple of other scenarios including Devilish Deals - same problem. Then I tried the *older* Shire Child and I *was* able to save. I started the main campaign and also was able to save.

[Player - (shire2).log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15258509/Player.-.shire2.log)

**Comment by ThyWoof** [comment]
Not this mod. I suggest check with the campaign author.
