### ISSUE TITLE
Baleful Scion: Inconsistent behavior

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4594]
Noticed some issues in 6 character MP with multiple players having the feat.  1 player consuming the other players charge, 1 player only getting damage, other player only getting heals.  1 player being able to get the damage bonus every round even without charges.

So I tried to replicate in single player, however I am only able to replicate the heal with no damage.  This is the default Palace of Ice campaign with 6 characters and single player

Heal received, consumed last charge on that character, no bonus damage.  This is the 4th round of combat, the previous 3 Baleful Scion charges worked as expected on all 6 characters.
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/c600b1c7-b8a9-45e1-852a-ab9f440d2a8a)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/4aeb31a2-872b-40aa-b6dc-3dc59c787c5f)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/287c66c4-29d2-40b5-8263-a0a5e1a79428)

Example of expected combat log
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/e0de538c-2cea-4a42-a42e-b621bba41ac7)

Save: [baleful_scion_test.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15260005/baleful_scion_test.sav.zip)
Config: [Settings.xml.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15260041/Settings.xml.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/cc81873a-726b-4763-bfca-fc84ed3a979d)
I've changed the approach, and so far so good, but won't be able to test MP.

**Comment by ThyWoof** [comment]
I'll need help testing in MP. Please open a new issue if it still persists after I release next version.

**Comment by ThyWoof** [comment]
Wasn’t able to test this one under MP in v8? Can you confirm it’s fixed?
