### ISSUE TITLE
corrupteds save

### ISSUE THREAD

**Issue by franxisfaxz** [SolastaMods/SolastaUnfinishedBusiness#4601]
saves corrupted mid gameplay when trying to load
 
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15283631/Player.log)
[Saves.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15283637/Saves.zip)

**Comment by franxisfaxz** [comment]
doing some digging it appears the save only corrupts when saving mid-fight, otherwise it loads as normal

**Comment by ThyWoof** [comment]
Do you have GWM feat on any of the heroes?

**Comment by franxisfaxz** [comment]
nope

**Comment by ThyWoof** [comment]
Indeed I cannot open then. No good log message either. Nothing I can do to help.
