### ISSUE TITLE
[Devastating Strikes] feat  needs correction in Korean

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4602]
The description of the feat does not fit in Korean.
The correct Korean translation is below.
대검, 대도끼, 망치를 사용한 공격은 특히 치명적이며, 이들 중 하나를 사용할 때 다음과 같은 이점을 얻습니다.
 • 무기 공격은 숙련도 보너스와 동일한 추가 피해를 줍니다.
 • 치명타를 입힐 때마다 추가 무기 주사위를 굴리고 해당 공격에 대한 대상 생물의 저항을 무시합니다.
When the feat was changed, it appears that the content of the changed feat was not translated into Korean.
https://drive.google.com/file/d/1avHN9YcUnGrUh5xwsb15dmoHBRy0c3In/view?usp=drive_link

**Comment by ThyWoof** [comment]
All translations are done with Google. I need help from native speakers pushing these changes. I don’t speak KO. I have people help from RU and CN. Please consider help fixing KO.
