### ISSUE TITLE
Wizard Spell Mastery

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#4606]
(Found previous discussion at https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/85)

> The first two 1st and 2nd-level wizard spells that you prepare can be cast at their lowest level without expending a spell slot.

This feature does not seem to be working. I have tried preparing spells in different orders but the game never seems to recognize my choices. I have the Spell Mastery button on my toolbar, but the only spell that ever appears on it is Misty Step (which I have from Fey Teleportation). Also, since Misty Step is the only spell it recognizes, I don't have the Spell Mastery button available for main actions in combat.

In the attached save file, the wizard has taken Misty Step as a duplicate in addition to getting it from Fey Teleportation (I was experimenting). But, the issue occurred prior to me doing this too.

[spell_mastery.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15287631/spell_mastery.zip)

**Comment by x2f01101011** [comment]
Here's a save updated to the latest UB.

[spell_mastery2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15287749/spell_mastery2.zip)

**Comment by x2f01101011** [comment]
It seems like reaction spells do not work with the feature. I was able to get Blindness to appear but not Shield or Elemental Infusion.

**Comment by ThyWoof** [comment]
Rewriting this and signature with a much less intrusive way of selecting spells.
