### ISSUE TITLE
Witch Bolt range error

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4608]
When casting a witch bolt, the range is 12. When casting as an action without consuming a spell slot, the range is 6.
Additionally, simply moving around without taking action breaks your mental focus.

**Comment by ThyWoof** [comment]
Both ranges are correct at 30ft. If you or enemy are more than a given distance apart you will lose concentration. Only issue I found was bonus action removing concentration. Fixed.
