### ISSUE TITLE
Chaos Bolt can cause "Game Warning"  when twinned and one misses

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4609]
This is occurring in MP with the sorc controlled by the host.  semi-reliably causing a Game Warning when one of a twinned chaos bolt misses and the other hits

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/98dbd0ad-d721-4fe3-8920-f5a1d054cd64)

[Settings.xml.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15307984/Settings.xml.zip)

[Player.log.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15307991/Player.log.zip)

[QuickSave_2.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15307996/QuickSave_2.sav.zip)

[The West Marches of Solasta (Level 1-20).json.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15308001/The.West.Marches.of.Solasta.Level.1-20.json.zip)

**Comment by ThyWoof** [comment]
this works perfectly under SP. Hours of test. Unfortunately, game in MP changes the order / duplicates some events. Very hard to support 2 different "games". Won't fix.
