### ISSUE TITLE
Creed of Arun (Con), War Caster and Flawless Concentration do not grant advantages on concentration checks while shapeshifted

### ISSUE THREAD

**Issue by Kalleculated** [SolastaMods/SolastaUnfinishedBusiness#4613]
This might be some engine limitation and also present in the vanilla game, I assume shapeshifting is just some bandaid implementation. However, if you shapeshift and have one of those three feats, you will not be given the advantage on concentration checks (and probably neither on all con checks for creed of arun) while being shapeshifted. Looking at RAW, I guess warcaster might not work while shifted, even though the general consensus seems to be that it does. However, creed of arun should definitely work and it would also just make sense from a gameplay perspective to get the advantage.

The part where you do not need to roll when receiving lower than 10 damage for flawless concentration works though, so there is that.

**Comment by ThyWoof** [comment]
Indeed Druid was a hack by TA. Game engine limitation. Won’t fix.
