### ISSUE TITLE
Shield Bash erro and Portraits cannot be used in Korean.

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4616]
In the latest version of Shield Bash, updated today, hits and damage do not increase with increasing shield rating.

So I experimented to see if I could use portraits in English. But I still couldn't use Portrait. I think there's something wrong with the font.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/7ce0bcf6-08db-4b2c-a9ac-c6ccba59ca98)
Shield Bash fixed.

fixed KO mod UI on Portraits setting.
