### ISSUE TITLE
Squat Nimbleness not fully functioning

### ISSUE THREAD

**Issue by VintageRed** [SolastaMods/SolastaUnfinishedBusiness#4620]
The 'squat nimbleness' feat for shorties doesn't appear to be working correctly. It doesn't give the +1 to movement speed. It does, however, appear to give the other two effects (+1 to STR or DEX and athletics or acrobatics skill proficiency) - but my shorties are still slow. I guess two out of three ain't bad, but it makes it a much less useful feat for my vertically challenged party members!

**Comment by ThyWoof** [comment]
Save and logs?

**Comment by ThyWoof** [comment]
fixed in dev.
