### ISSUE TITLE
Solasta has detected an instability

### ISSUE THREAD

**Issue by fr0** [SolastaMods/SolastaUnfinishedBusiness#4623]
This error happens every time I start the game.

Attached the log file.

The log file also mentions some specific character files, which I also attached.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15359047/Player.log)
[Korragos.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15359048/Korragos.zip)
[Henry.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15359049/Henry.zip)

Solasta 1.5.97
UB 1.5.97.9

**Comment by ThyWoof** [comment]
At some point you had a wrong umm version installed which broke one or hero files. Henry is one of them. Need to get rid of this file but while game is open.
