### ISSUE TITLE
A History of Violence - Character Freezing

### ISSUE THREAD

**Issue by jlk493** [SolastaMods/SolastaUnfinishedBusiness#4627]
To complete the Wanderer background quest, you have to knock crates down from the ceiling with arrows, bolts, or cantrips. Whenever I try with any of those, not only does the crate not fall but the character who tried to shoot it down can no longer move--they get stuck in place. I turned off the game completely and reloaded, only to face the same issue. Have also had issues recently where casting Eldritch Blast in a fight would cause the caster's turn to not end, but that was resolved by closing out the game.

**Comment by ThyWoof** [comment]
Do you have a save where I can shoot to repro?

**Comment by jlk493** [comment]
> Do you have a save where I can shoot to repro?

Yes, how can I send. Was just about to post the log.

**Comment by jlk493** [comment]
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.37f1 (019e31cfdb15)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1660 Ti (ID=0x2182)
    Vendor:   
    VRAM:     5966 MB
    Driver:   31.0.15.5134
Begin MonoManager ReloadAssembly


[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.27.6.0.
[Manager] OS: Microsoft Windows NT 10.0.22631.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] IsSupportOnSessionStart: False.
[Manager] IsSupportOnSessionStop: False.
[Manager] Mods path: C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-00000266D6FD90B0.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-00000266D6C55040.dll
[Manager] Injection successful.
- Completed reload, in  0.615 seconds
<RI> Initializing input.
New input system (experimental) initialized
XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 1.174900 ms
WwiseUnity: Wwise(R) SDK Version 2021.1.4 Build 7707. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data\Plugins\x86_64 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Sound engine initialized successfully. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 18.308300 ms (FindLiveObjects: 0.572000 ms CreateObjectMapping: 0.257700 ms MarkObjects: 17.368800 ms  DeleteObjects: 0.109200 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 21.076600 ms (FindLiveObjects: 0.844200 ms CreateObjectMapping: 0.402200 ms MarkObjects: 19.814000 ms  DeleteObjects: 0.015500 ms)

[Manager] Starting.
[Manager] Parsing mods.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.5.97.9'. Loading.
[SolastaUnfinishedBusiness] Language es detected.
[SolastaUnfinishedBusiness] Language it detected.
[SolastaUnfinishedBusiness] Language ja detected.
[SolastaUnfinishedBusiness] Language ko detected.
[SolastaUnfinishedBusiness] Language ru-Unofficial detected.
[SolastaUnfinishedBusiness] Language zh-CN-Unofficial detected.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Light SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset NotoSansJP-Bold SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Light SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Regular SDF loaded.
[SolastaUnfinishedBusiness] Font asset SourceHanSansK-Bold SDF loaded.
[SolastaUnfinishedBusiness] Active.
[SolastaUnfinishedBusiness] Loading time 5.98 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.


[Manager] Spawning.
[Manager] Checking updates.
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename:  Line: 308)

[SolastaUnfinishedBusiness] 5518 en translation terms loaded of 5518 provided.
[SolastaUnfinishedBusiness] 0 en translation fixes loaded.
[SolastaUnfinishedBusiness] enabled in 00:00:29.2504621.
Unable to recover prop blueprint: Throne 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unable to recover prop blueprint: Throne 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unable to recover prop blueprint: Throne 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unexpected timestamp values detected. This can occur in H.264 videos not encoded with the baseline profile. Timestamps will be skewed to correct the playback for C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/StreamingAssets/BackgroundMovie.MP4 
(Filename:  Line: 0)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 4 Unused Serialized files (Serialized files now loaded: 20)

Unloading 88742 unused Assets to reduce memory usage. Loaded Objects now: 271990.
Total: 1045.353400 ms (FindLiveObjects: 19.632800 ms CreateObjectMapping: 20.139100 ms MarkObjects: 975.097300 ms  DeleteObjects: 30.480300 ms)

The referenced script (Unknown) on this Behaviour is missing! 
(Filename:  Line: 199)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 145)

Unloading 1601 unused Assets to reduce memory usage. Loaded Objects now: 356365.
Total: 1119.348100 ms (FindLiveObjects: 24.648300 ms CreateObjectMapping: 18.215700 ms MarkObjects: 1075.492800 ms  DeleteObjects: 0.987600 ms)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Trying to register marker #0 but already exists in quest step Quest_Background_Wanderer_Quest - 03_ExploreTheMines (gadget: LD_Gadgets_QuestMarker_ExploreTheMines) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at SolastaUnfinishedBusiness.Feats.OtherFeats+CustomBehaviorMageSlayer+<OnPhysicalAttackBeforeHitConfirmedOnEnemy>d__3.MoveNext () [0x00061] in <2ca431c8f97a4c87bbb3dbee7568e6b7>:0 
  at TA.Coroutine.Run () [0x00019] in <14069e0776c443f6af77ee3eeee86525>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:Update()
 
(Filename: <2ca431c8f97a4c87bbb3dbee7568e6b7> Line: 0)

Unloading 2 Unused Serialized files (Serialized files now loaded: 24)

Unloading 154 unused Assets to reduce memory usage. Loaded Objects now: 290391.
Total: 1126.697200 ms (FindLiveObjects: 19.062900 ms CreateObjectMapping: 11.495700 ms MarkObjects: 1093.802800 ms  DeleteObjects: 2.335000 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 12)

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 289877.
Total: 1014.184900 ms (FindLiveObjects: 14.679100 ms CreateObjectMapping: 11.495900 ms MarkObjects: 987.436300 ms  DeleteObjects: 0.571000 ms)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 20)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 290364.
Total: 998.514900 ms (FindLiveObjects: 15.356200 ms CreateObjectMapping: 12.565400 ms MarkObjects: 970.108000 ms  DeleteObjects: 0.484600 ms)

The referenced script (Unknown) on this Behaviour is missing! 
(Filename:  Line: 199)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 147)

Unloading 1593 unused Assets to reduce memory usage. Loaded Objects now: 374776.
Total: 1148.507600 ms (FindLiveObjects: 21.754800 ms CreateObjectMapping: 16.005200 ms MarkObjects: 1109.912100 ms  DeleteObjects: 0.835100 ms)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Trying to register marker #0 but already exists in quest step Quest_Background_Wanderer_Quest - 03_ExploreTheMines (gadget: LD_Gadgets_QuestMarker_ExploreTheMines) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at SolastaUnfinishedBusiness.Feats.OtherFeats+CustomBehaviorMageSlayer+<OnMagicEffectBeforeHitConfirmedOnEnemy>d__2.MoveNext () [0x00061] in <2ca431c8f97a4c87bbb3dbee7568e6b7>:0 
  at TA.Coroutine.Run () [0x00019] in <14069e0776c443f6af77ee3eeee86525>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:Update()
 
(Filename: <2ca431c8f97a4c87bbb3dbee7568e6b7> Line: 0)

Unloading 1 Unused Serialized files (Serialized files now loaded: 24)

Unloading 154 unused Assets to reduce memory usage. Loaded Objects now: 291834.
Total: 1153.948900 ms (FindLiveObjects: 21.583600 ms CreateObjectMapping: 14.055700 ms MarkObjects: 1113.996800 ms  DeleteObjects: 4.310300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 12)

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 291320.
Total: 1019.638500 ms (FindLiveObjects: 15.096200 ms CreateObjectMapping: 11.690500 ms MarkObjects: 992.351300 ms  DeleteObjects: 0.500000 ms)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 20)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 291807.
Total: 1015.287600 ms (FindLiveObjects: 15.633400 ms CreateObjectMapping: 12.150100 ms MarkObjects: 986.456400 ms  DeleteObjects: 1.045100 ms)

The referenced script (Unknown) on this Behaviour is missing! 
(Filename:  Line: 199)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 147)

Unloading 1593 unused Assets to reduce memory usage. Loaded Objects now: 376219.
Total: 1111.782800 ms (FindLiveObjects: 20.712000 ms CreateObjectMapping: 16.321800 ms MarkObjects: 1073.647900 ms  DeleteObjects: 1.100400 ms)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Trying to register marker #0 but already exists in quest step Quest_Background_Wanderer_Quest - 03_ExploreTheMines (gadget: LD_Gadgets_QuestMarker_ExploreTheMines) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

NullReferenceException: Object reference not set to an instance of an object
  at SolastaUnfinishedBusiness.Feats.OtherFeats+CustomBehaviorMageSlayer+<OnPhysicalAttackBeforeHitConfirmedOnEnemy>d__3.MoveNext () [0x00061] in <2ca431c8f97a4c87bbb3dbee7568e6b7>:0 
  at TA.Coroutine.Run () [0x00019] in <14069e0776c443f6af77ee3eeee86525>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:Update()
 
(Filename: <2ca431c8f97a4c87bbb3dbee7568e6b7> Line: 0)

**Comment by ThyWoof** [comment]
zip and attach. Also please don't paste logs. Attach them as well otherwise impossible to read on small devices.

**Comment by jlk493** [comment]
I don't know how to export saves.

The log says:

"The referenced script (Unknown) on this Behaviour is missing!
(Filename: Line: 199)

The referenced script on this Behaviour (Game Object '') is missing!
(Filename: Line: 334)"

**Comment by ThyWoof** [comment]
Without a save I cannot help, sorry.

**Comment by jlk493** [comment]
> Without a save I cannot help, sorry.

Or you could explain how to export saves.

**Comment by jlk493** [comment]
> To complete the Wanderer background quest, you have to knock crates down from the ceiling with arrows, bolts, or cantrips. Whenever I try with any of those, not only does the crate not fall but the character who tried to shoot it down can no longer move--they get stuck in place. I turned off the game completely and reloaded, only to face the same issue. Have also had issues recently where casting Eldritch Blast in a fight would cause the caster's turn to not end, but that was resolved by closing out the game.

Attached.

[Movie.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15369138/Movie.zip)
