### ISSUE TITLE
A History of Violence - Character Freezing (Save Attached)

### ISSUE THREAD

**Issue by jlk493** [SolastaMods/SolastaUnfinishedBusiness#4628]
**OLD TEXT**

To complete the Wanderer background quest, you have to knock crates down from the ceiling with arrows, bolts, or cantrips. Whenever I try with any of those, not only does the crate not fall but the character who tried to shoot it down can no longer move--they get stuck in place. I turned off the game completely and reloaded, only to face the same issue. Have also had issues recently where casting Eldritch Blast in a fight would cause the caster's turn to not end, but that was resolved by closing out the game.

**NEW TEXT**

You have to go the area with the East Cart loader, which is unexplored in the save but will take less than 3 seconds to get to if you just click on the right side of the map. Hop down the scaffolding and try to shoot the crates.

[Movie.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15369125/Movie.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/8122c939-fcb8-4f28-96f2-94ba0011bff0)
fixed
