### ISSUE TITLE
Widened Earthquake causes game warning

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4632]
This log/screenshot is from single player.  Doesn't require being in a fight, if you attempt to cast a widened earthquake with Claudia it causes the warning.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/c069a48c-d909-47ed-be66-516ec7fec56e)
[Player.log.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15375837/Player.log.zip)
[QuickSave_5.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15375850/QuickSave_5.sav.zip)
[The West Marches of Solasta (Level 1-20).json.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15375865/The.West.Marches.of.Solasta.Level.1-20.json.zip)
[Settings.xml.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15375867/Settings.xml.zip)

Edit this may be related to Claudia having some permanent metamagic effects https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/4634

**Comment by HiddenHax** [comment]
Bug confirmed on that save.

**Comment by ThyWoof** [comment]
Won’t debug / fix anything else on this save. Couldn’t repro with another hero.

**Comment by ThyWoof** [comment]
Fixed this
