### ISSUE TITLE
Stealthy doesn't promote proficient stealth to expert

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4633]
Respecced an Arcane Scoundrel Rogue (Shadow Gnome)  due to other issues, chose the stealthy feat at level 8 and did not receive stealth expertise.  Additionally tooltip references "Stealthy" instead of "stealth" in 3rd bullet point.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/2c5dca69-c429-4466-b817-a36ff9f8ba55)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/be8a1fa5-9fc0-4c64-8c18-565b0f5ed67b)

Edit: Additionally stealth is missing from skills according to the editor (did not check value at level 1)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/390d508a-0c6b-4dfb-b1dd-2e66a1a51837)

**Comment by HiddenHax** [comment]
Just checked this with a fresh character and expertise in Stealth is properly granted.
