### ISSUE TITLE
Haunted Soul Sorcerer has permanent metamagics

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4634]
This is on single player, default Palace of Ice.

If you attempt to cast greater invisibility with Drusilla, it automatically is twinned spell and doesn't consume sorcery points.  If you attempt to cast "use power" -> "Vengeful Spirits" it automatically has Widened Spell active, even though you cannot usually activate metamagic on it.  Every spell is automatically twinned,  every spell is also automatically Widened and allows you to apply it again.

[Settings.xml.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15377306/Settings.xml.zip)
[Drusilla.chr.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15377310/Drusilla.chr.zip)
[Settings.xml.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15377312/Settings.xml.zip)
[meta_haunted.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15377330/meta_haunted.sav.zip)

Normal Fireball
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/11c20ed2-965e-49aa-8b32-cdc8768b4246)

Haunted Soul default
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/64a84817-0042-4e5b-aa13-1785abb84eb9)

Haunted Soul with widened active
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/f0f21557-16dd-4926-a8da-c783e90b7073)

**Comment by HiddenHax** [comment]
Cannot replicate Widened Fireball being default, but the rest of the things mentioned can be replicated on that save.

**Comment by ThyWoof** [comment]
Have you ever used party editor on above save?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/e9bb847a-fd36-4760-b5dc-11f2a4d9c0b2)
cannot repro on a brand new hero. not sure what happened with your save. won't fix.

**Comment by ThyWoof** [comment]
Don’t use the party editor.

**Comment by ThyWoof** [comment]
Fixed as well
