### ISSUE TITLE
Arcane Scoundrel not proccing Arcane Backlash after Counterspell

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4635]
In multiplayer, haven't tested single player.  Countered the monster's cast, did not hit them with arcane backlash

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/892ef3c2-35d5-41d1-b340-9c8667d1dba1)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/a11c29af-4120-45f9-83f9-5f583f03527f)

**Comment by HiddenHax** [comment]
Tested in single player both the power and normal Counterspell cast on level 13 feature. Arcane Backlash did damage in both scenarios.
