### ISSUE TITLE
Artificer Battlesmith Force Jolt doesn't double on crit

### ISSUE THREAD

**Issue by Franavu** [SolastaMods/SolastaUnfinishedBusiness#4636]
The force jolt power of the Artificer Battlesmith subclass Force Jolt ability (2d6 force damage added to one attack per round) doesn't seem to double the dice on a critical hit. Save and screenshot added.

[Forcejolt_save.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15380252/Forcejolt_save.zip)
![Force Jolt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/170356853/d9aa2865-05f1-4b74-b46c-ea0e3458153d)

**Comment by ThyWoof** [comment]
this is a game engine limitation whenever a power has a D20 roll and a dice advancement table. It also happens on Force Ballista and all enhanced arrows on Martial Arcane Archer.

cannot fix.
