### ISSUE TITLE
Forge Cleric level 17 Blessed Metal not providing Fire damage Immunity

### ISSUE THREAD

**Issue by Xan-Asc** [SolastaMods/SolastaUnfinishedBusiness#4637]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/050e48f2-e956-4fbc-ac65-548d737d73ad)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/119889093/ea4e91d2-9a6a-497b-99ab-cbc180eaecba)

Skeptagon does not have any talents or items that ignore fire resistance.

**Comment by HiddenHax** [comment]
Bug confirmed on that save.

**Comment by ThyWoof** [comment]
Probably only triggering on weapon attacks. Easy fix to add magic effects.
