### ISSUE TITLE
Gravity sinkhole spell not moving affected creatures correctly

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4638]
I cast this spell a couple of times now but every time the creatures fail their save they only move a square (5ft). Using the latest version (dogs bark, caravan passes)

Boa mod, meu caro.

**Comment by ThyWoof** [comment]
Share a save pleas

**Comment by RodrigoMamedeCosta** [comment]
Does any save do, or do you need me to be in combat, spell prepared, etc?

**Comment by ThyWoof** [comment]
Get me a save in combat before I can cast it. It will help a lot.

**Comment by RodrigoMamedeCosta** [comment]
[Gravity.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15417062/Gravity.zip)

Perhaps not the best fight since the minotaurs occupy two squares (and apparently move two squares), but there are regular enemies there. No one ever approaches the center of the sphere, they just get shoved.

**Comment by RodrigoMamedeCosta** [comment]
By the way, Thunderstep is allowing me to teleport allies with me that are way beyond touch range. You should be able to test it in the same save.

**Comment by ThyWoof** [comment]
thunderstep range fixed and gravity sinkhole probably fixed at least on above save.
