### ISSUE TITLE
Apothecary  bug

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4648]
[You gain proficiency with herbalism kit and medicine, or expertise if already proficient.]
However, herbalism kits are not expertise
Medicine works normally.

**Comment by ThyWoof** [comment]
Not a bug if you already have the tool.

**Comment by kdgmo** [comment]
It's about becoming proficient with tools, not expertise.
Then it seems like the description needs to be modified. If you just read the text, you can see that even the tools are given  expertise.
