### ISSUE TITLE
Corrupted Save - A History of Violence Background Quest

### ISSUE THREAD

**Issue by jlk493** [SolastaMods/SolastaUnfinishedBusiness#4650]
Following up on my last thread:

https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/4628

The data for the save is now corrupted, and the Solasta forums have been taken down as Tactical Adventures is working on their next project.

Save attached. Please do not be dismissive and actually explain what I should do if it's something on my end. I've already tried Googling and those solutions didn't work.

[Movie.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15422683/Movie.zip)

**Comment by ThyWoof** [comment]
Most likely related with entries in combat log related to lucky feat. You will need an older save, preferably after a long rest where these entries in combat log aren’t there.

Don’t open a 3rd ticket. I cannot babysitter every single player out there. This is a hobby.
