### ISSUE TITLE
Cleric and Divine Soul spell list issue

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4662]
I am doing the classic Tempest 2 + Sorcerer X, but with Divine Soul so I can have spirit guardians. Unfortunately, I cannot select higher level cleric spells for my sorcerer spells because it says I already know all the cleric spells, invalidating Divine Soul cleric spell selection.

**Comment by ThyWoof** [comment]
There is a checkbox under multiclass to allow re learn spells from other classes
