### ISSUE TITLE
Booming Blade + Warcaster not working together

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4663]
If Booming Blade is cast as a reaction spell, the attack only happens after the victim reaches their destination and the sheathed condition only gets applied afterwards, meaning that it doesn't trigger with their movement away from the caster.

**Comment by ThyWoof** [comment]
Always a good idea to search closed issues to verify if anything has been reported before. Cannot fix. Engine limitation.

**Comment by RodrigoMamedeCosta** [comment]
I have no idea what the code looks like, but if there a way to identify whether a spell was cast as a reaction vs action then adding something like "if reaction then damage applied immediately" might work.

Thanks anyway!
