### ISSUE TITLE
Retinue Touched not giving the spells

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#4665]
[retinue_touched_bug.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/15505700/retinue_touched_bug.zip)
I have taken the feat but the spells are nowhere to be found. My character is Farryn.

**Comment by ThyWoof** [comment]
All these feats require an existing spell repertoire. Your hero is a Monk without any.

**Comment by ZheToralf** [comment]
I did not know that. Could you please add that to the description?
