### ISSUE TITLE
MonkHeightenedMetabolism interation with way of freedom

### ISSUE THREAD

**Issue by robvoid** [SolastaMods/SolastaUnfinishedBusiness#4667]
way of freedom level11 ability grants 3 flurry of blow attacks. MonkHeightenedMetabolism sets unarmed attacks to 3. Since way of freedom is a vanilla subclass, not sure how it works? would it be "set to 3" or "add 1"?

**Comment by HiddenHax** [comment]
Should be 4 with that mod option on.

**Comment by ThyWoof** [comment]
thanks. this is still in DEV with QA. to be fixed.
