### ISSUE TITLE
Suggestion: Add Backgrounds to the Wiki

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4674]
Can we get the Backgrounds added to the Wiki?  I was trying to remember all the additional backgrounds, particularly the ones that grant a specific Cantrip.  But really, all the backgrounds would be nice to compare which gives which Skill, Proficiency or additional benefit.  Thanks.

**Comment by ThyWoof** [comment]
![{1DCC1E54-CF30-43BD-848D-B1B7ACDD62D8}](https://github.com/user-attachments/assets/01ce1b80-c0e7-4498-8a03-0d4b37e73523)
