### ISSUE TITLE
The ability Rift Strike of Riftwalker does NOT affect the attacker

### ISSUE THREAD

**Issue by xwh129** [SolastaMods/SolastaUnfinishedBusiness#4675]
When being melee attacked, Rift Strike banishes the user instead of the attacker, which goes against the description.

**Comment by ThyWoof** [comment]
do you have a save I can use in QA? Zip and attach pls.

**Comment by xwh129** [comment]
> do you have a save I can use in QA? Zip and attach pls.

Here is the save where I found the problem.
[RiftStrike_Test.zip](https://github.com/user-attachments/files/15533715/RiftStrike_Test.zip)
After loaded, just end the turn straitforward and you will see when Rift Strike triggered in enemy's turn, it is self-banishment.
