### ISSUE TITLE
Several quicken spell issues

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4679]
1. If a sorcerer character is hasted, after doing the first action to cast a cantrip, I cannot use sorcery points to bonus action quicken a spell. 
I'm just not able to quicken a spell in general after my action,

2. After quickening a cantrip before using my action, I cannot then use my main action to cast a leveled spell (which I think I should be able to according to the rules).

3. After quickening a cantrip (only tried booming blade), I can then repeat the quicken metamagic for another cantrip infinitely (well, until I ran out of sorcery points at least.) So I got 3 bonus actions in one round.

**Comment by HiddenHax** [comment]
1. That's how the game works in vanilla. If it cannot detect the caster to be able to cast a spell, it cannot "edit" a spell to make it work with metamagic. I suggest casting a quickened spell immediately on turn start if planning to quicken anything.

2. That's according to RAW rules. If you cast *any* spell, be it cantrip or leveled using your bonus action, you cannot cast anything except cantrip with your main action.

"A spell cast with a bonus action is especially swift. You must use a bonus action on your turn to cast the spell, provided that you haven't already taken a bonus action this turn. You can't cast another spell during the same turn, except for a cantrip with a casting time of 1 action."

3. Definitely a bug. Please provide a save with your sorcerer.

**Comment by RodrigoMamedeCosta** [comment]
[Smiteless paladin.zip](https://github.com/user-attachments/files/15628376/Smiteless.paladin.zip)

Here is the save. Playing Shadows over Brightreach. In one ruond, Ludriq can bonus action booming blade, bonus action booming blade, bonus action booming blade, action booming blade. Neat.

Also, worse than that, I can't smite with the Paladin. I reset the chosen spells when multiclassing and maybe that was it (since smite may be an invisible selected spell).  But then I respec'd the character and the smite is still not showing up (either the crit toggle or the option to smite when I hit). Not sure what is up. Do I need to open a new issue?

**Comment by EnderWiggin** [comment]
> Edit 2: There is also a sorlock in that save and I can't quicken an eldritch blast infinitely. So it's not a general quickened cantrip issue. I haven't tried other cantrips besides these two.

the issue was specifically with "blade" cantrips - ones that make you attack with your weapon. Although, not 100% sure why only quickened cantrip skipped action spending
