### ISSUE TITLE
Mind sharpener not providing advantage on concentration checks

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4684]
In this save, the cleric Bjarki has a bless going. Open the debug interface and select "Wound 10HP" and it does 15 because of cataclysm mode and no advantage roll occurs.

I then added in Flawless Concentration via the Party Editor and it works there.

[QuickSave_3.zip](https://github.com/user-attachments/files/15586678/QuickSave_3.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5d76e972-32c9-4c76-af19-9f5ca39073aa)
