### ISSUE TITLE
Monk Heightened Metabolism and Zen Archery Monk

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4685]
Hi, there. 

Just wanted to make a suggestion. Since the new "Monk Heightened Metabolism at level 10" feature in update 1.5.97.12 gives 3 attacks with flurry of blows instead of two, would it be possible to give the Zen Archery monk two ranged attacks with flurry of blows instead of just one at level 10 with Heightened Metabolism?

Otherwise it kind of makes that subclass nerfed by 10th level, because it would make more sense to choose 3 melee attacks over 1 ranged attack with flurry of blows. Thanks!

**Comment by ThyWoof** [comment]
Good call. We missed that one

**Comment by ThyWoof** [comment]
from subclass designer:

Whole point of Zen Archery was to combine ranged and melee, not exclusively go ranged in every scenario. Giving an additional weapon attack is an insane buff when you take into account +2/3 to all bow attacks and damage on every bow attack granted literally 1 level later + Sharpshooter, enchanted arrows and possible bow enchantments into account, and super strong level17 which benefits from all above.

won't change, sorry.
