### ISSUE TITLE
Instability Detected?

### ISSUE THREAD

**Issue by Stolcor** [SolastaMods/SolastaUnfinishedBusiness#4686]
I'm playing the game just fine and I suddenyl get a popup saying there's an instability issue, so I need to close the game and grab the file I've attached. Well, here that is.

I've had this issue with multiplayer and with solo playing.

I have Windows 11 home
Solasta with all DLC
Latest version of UB

[Player.log](https://github.com/user-attachments/files/15688074/Player.log)

**Comment by ThyWoof** [comment]
I need your save before it happens. Nothing in log point to this mod.

**Comment by ThyWoof** [comment]
Uploading Crash Report
Exception: [Tactical - Invisible for players] Incorrect move position index, character is not on the path.

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
<ExecuteImpl>d__10:MoveNext()
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:Update()

Definitely not the mod
