### ISSUE TITLE
Monk evasion not working and fireball dealing bludgeoning damage.

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4688]
The mob should toss a fireball at the monk right after the current turn ends. 

[before fireball.zip](https://github.com/user-attachments/files/15743906/before.fireball.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/4a74ca38-ca35-49e6-9c2c-147d6a29301e)


there's something odd about this save or campaign. I cannot repro when I export your Monk and test in another location.

**Comment by qeltar** [comment]
It was freshly respec'ed, not sure if that would matter. 

It's Artyoan's Forsaken Isle fwiw.

Did you see it in my save?

Might just be one of those oddities.

**Comment by ThyWoof** [comment]
Oh, it happens 100% of the times there. Nothing I can do on this one.

**Comment by qeltar** [comment]
Must be just one of those oddities. I haven't seen it before either. Thanks for looking.
