### ISSUE TITLE
Artificier/Wizard Multiclass dosn`t get proper spell slots

### ISSUE THREAD

**Issue by nextentlligods** [SolastaMods/SolastaUnfinishedBusiness#4691]
My character Artificier 1/ Wizard 2 only gets 3 Lv1 spell slots and not any Lv2 spell slot, which should have 4 for lv1 and 2 for lv2.
![Artificier](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/61521367/1133c20a-150a-4a96-9d3f-df78131c235f)
![wizard](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/61521367/9718b8d5-747f-4081-a11c-672f5e010b73)

**Comment by ThyWoof** [comment]
You are getting 3 slots which is correct. Learn more at https://fexlabs.com/5eslots/

**Comment by nextentlligods** [comment]
But Rulebook said that multi-classed artificier levels should be halved and rounded up then add to determine total available spell slot available. So Artificier 1/ Full-Caster X will maintain the spell slots just the same as a single-classed full caster.
Optional Rule: Multiclassing

If your group uses the optional rule on multiclassing in the Player’s Handbook, here’s what you need to know if you choose artificer as one of your classes.

> Ability Score Minimum. As a multiclass character, you must have at least an Intelligence score of 13 to take a level in this class, or to take a level in another class if you are already an artificer.
> 
> Proficiencies Gained. If artificer isn’t your initial class, here are the proficiencies you gain when you take your first level as an artificer: light armor, medium armor, shields, thieves’ tools, tinker’s tools.
> 
> Spell Slots. Add half your levels (rounded up) in the artificer class to the appropriate levels from other classes to determine your available spell slots.

(Eberron: Rising from the Last War pg. 54)

[https://rpg.stackexchange.com/questions/169189/how-does-multiclassing-work-for-an-artificer](url)
