### ISSUE TITLE
Crashes related to spike growth

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4694]
Decided to put this here instead of Discord for better tracking since I'm still having crashes when using spike growth in long fights.

At first I thought it was related to using it with entangle, but I just had a fight where I didn't use entangle, the fight finished and now it's crashing trying to drop concentration on the spike growth. I'll share a few saves in replies.

**Comment by qeltar** [comment]
This is a mid-fight save and crashes if you drop concentration on the spike growth and then the entangle.

However, just bringing up the cheat menu and doing "Kill all enemies" will also crash it.
[Uploading QuickSave_5.zip…]()

**Comment by qeltar** [comment]
This fight I did just now completed successfully but dropping concentration on the spike growth causes a crash.
[AutoSave_5.zip](https://github.com/user-attachments/files/15748348/AutoSave_5.zip)

**Comment by qeltar** [comment]
One more quick note.. spike *by itself* seems to work fine. The problems seem to come in when it is combined with another concentration AOE like entangle, wall of fire, etc.

**Comment by ThyWoof** [comment]
fixed
