### ISSUE TITLE
Instability when using whirlwind attack

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4696]
Should happen immediately when you activate it on this save.
[QuickSave_4.zip](https://github.com/user-attachments/files/15750372/QuickSave_4.zip)
[QuickSave_4.zip](https://github.com/user-attachments/files/15750372/QuickSave_4.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/503fb11d-a612-44b0-8e3b-b0fe60f1d7aa)

probably fixed on DEV.

**Comment by qeltar** [comment]
Confirmed fixed in .14. Thank you.
