### ISSUE TITLE
Empowered spell on DoT spells

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4699]
So I empowered a wall of fire and every time the spell procs 1s and 2s are rerolled. That in itself is a questionable interpretation of the rules of the metamagic.

But while the wall of fire is active, if I cast any damaging spells, they get empowered as well.

In this Shadows over Brightreach save I cast an empowered wall of fire with Borwes, a square around the 4 characters, then I did a shocking grasp and it was empowered as well:

[AutoSave_3.zip](https://github.com/user-attachments/files/15751298/AutoSave_3.zip)

**Comment by RodrigoMamedeCosta** [comment]
Also, I'm not sure Dawn should be interacting with wall of fire.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/161524095/6dffcac6-efd8-45df-9818-b0957231b39f)

**Comment by RodrigoMamedeCosta** [comment]
Same save, Truesight from an item is not letting me see through a darkness spell (don't know if a truesight spell would have the same problem)

**Comment by HiddenHax** [comment]
Can confirm that there are problems with Wall of Fire (recurrent concentration spells) and Empowered metamagic in mod.
Proxies rolling saves has also been noted.
Although, what's with the Truesight? I opened the save and the only Truesight item I found is in inventory (Gem of Seeing) and nobody has it attuned so it doesn't do anything that way. Was there something I missed?

**Comment by RodrigoMamedeCosta** [comment]
Sorry, it was in the same gameplay but a couple of hours after, after attuning it (to the Paladin, the only one without Devil sight. It said "you can't see that character" or something, it wasn't about the advantage.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d2de3786-7222-47d9-ad28-5580d6fd7861)
proxies rolling saves might be fixed

**Comment by ThyWoof** [comment]
> Sorry, it was in the same gameplay but a couple of hours after, after attuning it (to the Paladin, the only one without Devil sight. It said "you can't see that character" or something, it wasn't about the advantage.
> 
> Oh, and I think the second issue is because the daylight spell is supposed to dispel magical darkness and this assumption is being made for Dawn. However, besides the fact that it's acting as a general dispel (I'm assuming), Dawn does not dispel magical darkness but instead illuminates magical darkness (any affected areas are not dark), at least according to what I can find.

The Daylight spell does not create actual sunlight, unlike spells like Sunbeam and Sunburst.
The spell does not affect creatures that are sensitive to sunlight, such as vampires.
The spell can be used to counter or dispel any darkness spell of equal or lower level.
The spell’s effects are blocked if the area is covered by an opaque object, such as a bowl or helm.
The spell can be used to illuminate areas of magical darkness, but the prevailing light conditions will return once the spell’s effects wear off.

**Comment by RodrigoMamedeCosta** [comment]
Maybe I phrased it incorrectly but it was Dawn that was acting in those
manner (dispelling darkness) and should not.

**Comment by ThyWoof** [comment]
Description clearly says it can be used to counter or dispel any darkness spell of equal or lower level. It does that. I disagree it should not dispel darkness.

**Comment by RodrigoMamedeCosta** [comment]
Perhaps I am confused, but this is Dawn's description:

> The light of dawn shines down on a location you specify within range. Until the spell ends, a 30-foot-radius, 40-foot-high cylinder of bright light glimmers there. This light is sunlight. When the cylinder appears, each creature in it must make a Constitution saving throw, taking 4d10 radiant damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw whenever it ends its turn in the cylinder. If you’re within 60 feet of the cylinder, you can move it up to 60 feet as a bonus action on your turn.

And this is what I think you're thinking about, daylight:

> A 60-foot-radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet.
> If you chose a point on an object you are holding or one that isn’t being worn or carried, the light shines from the object and moves with it. Completely covering the affected object with an opaque object, such as a bowl or a helm, blocks the light.
> If any of this spell’s area overlaps with an area of darkness created by a spell of 3rd level or lower, the spell that created the darkness is dispelled.

Maybe I'm consulting the wrong source, is Dawn in solasta supposed to have different rules?

**Comment by ThyWoof** [comment]
hmm. correct. for whatever reason google was giving this wrong desc.

I usually use http://dnd5e.wikidot.com/spell:dawn and forgot to go there.

**Comment by RodrigoMamedeCosta** [comment]
Google has been experimenting with AI answers lately, and they are baaaaad. Thanks for all the work!
