### ISSUE TITLE
Crashes with Sunbeam Spell

### ISSUE THREAD

**Issue by Stolcor** [SolastaMods/SolastaUnfinishedBusiness#4707]
When I go to cast Sunbeam, I get the "instability detected" message that tells me to report it to UB. 

High elf wizard casts sunbeam and I lose the HUD.
EDIT: Happens when trying to use Focused Spell Metamagic during combat. Doesn't seem to happen otherwise.

[Player.log](https://github.com/user-attachments/files/15797909/Player.log)
[Lich 4.zip](https://github.com/user-attachments/files/15797911/Lich.4.zip)

**Comment by Stolcor** [comment]
Solasta Version: 1.5.97 with all DLC except supporter pack
UB Version: 1.5.97.14

**Comment by ThyWoof** [comment]
fixed
