### ISSUE TITLE
Freeze on Sweeping Strike 

### ISSUE THREAD

**Issue by resumeman** [SolastaMods/SolastaUnfinishedBusiness#4708]
I was having the concentration freeze in .14 and reverted to .12.

I'm playing a BattleMaster ftr with sweeping attack. When I use the maneuver, the game freezes. Interestingly, it appears if I attack *first*, then do the maneuver for my second attack, it works without freezing. Only tried the latter twice tho.
[Player - 2nd swp freeze.log](https://github.com/user-attachments/files/15799313/Player.-.2nd.swp.freeze.log)

**Comment by ThyWoof** [comment]
no save file and no errors in log. Please open a new ticket if it happens again, and ensure you get me a save to test.
