### ISSUE TITLE
Dawn procced multiple times + other issues

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4711]
Dawn procced multiple times in one enemy round. Same enemy got hit multiple times at the end of their round and then died. Maybe it would have kept happening forever if the enemy had not died.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/161524095/684dffa2-f745-48ee-b8d4-61fc7a02e002)

Other issues: Wrath of the storm (rebuke) can proc on attacks on other characters other than tempest cleric.

During the same fight there were a couple of freezes. I have darkness, dawn and insect plague up, one of the freezes was when a dryad entered an empowered insect plague, but was also going to end the turn in Dawn. Dryad just kept running in place. Log folder is empty.

Also, DoT it's still empowering every time dice are rolled.

[Shadows over Brightreach](https://github.com/user-attachments/files/15836730/AutoSave_5.zip)

**Comment by RodrigoMamedeCosta** [comment]
Here is a couple of logs, I wrongly trying to find them under the logs directory, oddly enough. Crashes keep happening in this fight.

[Player.log](https://github.com/user-attachments/files/15846604/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/15846605/Player-prev.log)

**Comment by RodrigoMamedeCosta** [comment]
@HiddenHax

This was marked as closed but it seems like the only issue that was solved was the wrath of the storm. However, I'm still getting issues with what I think is the mod, as the error I keep getting in the log is the same. I was going to go to the mod page to report it and noticed you're the author.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/161524095/8385c468-a25f-4827-a24c-63e3edd38e16) This is followed by the crash report message (quit, etc.) and sometimes the hud disappearing.

Here is the latest log.](https://github.com/user-attachments/files/15855823/Player.log)

**Comment by ThyWoof** [comment]
Fixed in dev. Not released. If you wanna test using QA builds get into official game discord.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/15859481/SolastaUnfinishedBusiness.zip)

can you test all reported issues using above? Need to start from zero. If a spell is already cast it won't work.

**Comment by RodrigoMamedeCosta** [comment]
I replaced the dll in the mod folder with that one and tested the same fight.

Dawn causing infinite hits on dryads: fixed
Dawn dispelling darkness: fixed
Wrath of the storm: Not tested
Empowered metamagic on DoT spell: Didn't see any rerolls during an empowered wall of fire, but also didn't see a reroll on the first hit (the casting) of Insect Plague (and there was a 2 which perhaps would have been rerolled). Not sure if intended to not even work when casting.
