### ISSUE TITLE
Globe of Invulnerability doesn't stop 5th level spells

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4712]
With 0.10 and 0.11, Globe of Invulnerability stopped 5th level spells (eg Cone of Cold) as expected.  With 0.12, Cone of Cold goes through Globe of Invulnerability. 

Saved Game for testing attached.  
[Globe Invulnerability.zip](https://github.com/user-attachments/files/15841157/Globe.Invulnerability.zip)

**Comment by ThyWoof** [comment]
Very strange as mod doesn’t touch globe and respective proxy at all. Will take a look

**Comment by ThyWoof** [comment]
possibly fixed but will need to test from zero (no global cast before hand)
