### ISSUE TITLE
Cult Fanatic / Concentration Glitch

### ISSUE THREAD

**Issue by Hanyo99** [SolastaMods/SolastaUnfinishedBusiness#4715]
I saw this issue listed yesterday, but no potential release coming through as of yet, so I'm posting it as well, to make sure people know it's still being a problem. When attacking someone maintaining concentration (in my case I'm seeing it most often with Shied of Faith), it prompts the mod instability issue and will not let you complete the combat round. 

I saw someone had listed a way they were able to fix it, but I don't know if that required messing with the source and re-compiling or if it's already being incorporated into the main release but I'm hoping to see it fixed soon, I can't move forward on my Iron Man Campaign run if it isn't fixed! 

Thank you guys for all that you do. 

[Player.log](https://github.com/user-attachments/files/15845550/Player.log)

**Comment by ThyWoof** [comment]
Fixed in DEV.
