### ISSUE TITLE
Commander level 15 class features do not work.

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4716]
https://drive.google.com/file/d/1fcXIDsd25I5BLHsNE1LiyRjjFNUQwReN/view?usp=drive_link

**Comment by ThyWoof** [comment]
location saves won't work. Must be a campaign. Also, cannot find anything wrong here. Mod doesn't touch this sub.

**Comment by kdgmo** [comment]
> 위치 저장이 작동하지 않습니다. 캠페인이어야 합니다. 또한 여기서 잘못된 점을 찾을 수 없습니다. Mod는 이 하위 항목을 건드리지 않습니다.

The mod doesn't touch any class features, but it doesn't work when you learn the Slash feat, which has a similar mechanic. If you haven't learned the Slash feat, it will work normally.
