### ISSUE TITLE
Lucky feat does not prevent other reaction 

### ISSUE THREAD

**Issue by Red-Kai** [SolastaMods/SolastaUnfinishedBusiness#4719]
when using Lucky feat to successfully evade an attack - other reactions (like shield spells) are still presented to block the attack although the attack is now a miss (due to luck re-roll).

**Comment by ThyWoof** [comment]
I need a save to test. Even better if before this triggers

**Comment by Red-Kai** [comment]
Saves are hard since this depend on the battle, but here is a screenshot showing it . the fighter got hit ,and used luck point to force a re-re-roll
 the attacker re-rolled a 3 which is a miss . nevertheless the attacker reaction pop to suggest to use twin blade reaction although the attack is now a miss (3 instead of 17)
<img width="1462" alt="Lucky" src="https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/51976411/f741827e-b55a-4ec2-ac3f-f08e132b8f5d">

**Comment by ThyWoof** [comment]
probably fixed in DEV. Can you compile it and give a try?

**Comment by ThyWoof** [comment]
Yep

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/15859480/SolastaUnfinishedBusiness.zip)
use this one. latest DEV build from minutes ago.

**Comment by ThyWoof** [comment]
Definitely fixed in dev.
