### ISSUE TITLE
Issue with playing Ruins of Ilthsmar using Mod

### ISSUE THREAD

**Issue by OGCatGirlGamer** [SolastaMods/SolastaUnfinishedBusiness#4720]
We've run into a few issues with this particular user created campaign, but the last update have caused us to come to a complete halt. There are cult fanatics in the campaign that when we attack the game just freezes. We've tried powering through the area from different angles and get stuck repeatedly when attacking these fanatics. It doesn't matter how we attack, wither its simple mele or spell the game locks up. Can't save, can't continue the PCs turn, can't end the PCs turn. Most of the time an instability error appears and asks to report the problem along with the player log. We've also tried rolling back the mod version, but nothing happens after you agree to roll it back.

Mod Version 1.5.97.14
Solasta Version 1.5.97

![UFBMod Error](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/172940769/ff1d47fb-e55d-411d-8353-0050a3b92fad)
[Player.log](https://github.com/user-attachments/files/15855590/Player.log)

**Comment by OGCatGirlGamer** [comment]
Here's the latest save.
[061124B.zip](https://github.com/user-attachments/files/15855657/061124B.zip)

**Comment by OGCatGirlGamer** [comment]
Here's the latest save file
[Save_061424B.zip](https://github.com/user-attachments/files/15855663/Save_061424B.zip)

**Comment by ThyWoof** [comment]
don't use v14. It's broken. Have to manually reinstall v12.
