### ISSUE TITLE
Goliath psi warrior combo causes Stone's Endurance to be prompted before Kinetic Shield

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4721]
Obviously this doesn't make sense.

This save shows it, but it can take a while for the Bandito to roll the right number.
[QuickSave_3 (2).zip](https://github.com/user-attachments/files/15857634/QuickSave_3.2.zip)

**Comment by qeltar** [comment]
While you're in the neighborhood, this is probably an easy fix.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/75136132/17af186f-294f-43b1-8987-e5fde758d05b)

**Comment by ThyWoof** [comment]
fixed
