### ISSUE TITLE
3rd level Ravager Barbarian is not getting advantage with reckless attack

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4723]
My 3rd level ravager barbarian is no longer getting advantage on his attack with reckless attack. I realize he now has the subclass attribute "Frenzy" which gives extra damage with a reckless attack, but that power description says nothing about him losing advantage on his reckless attack. If he does, that kind of blows! 

Attached is a save right after he has given himself reckless attack and before he has attacked. Try it out, no advantage on the swing. 

Thanks.
[Reckless.sav.zip](https://github.com/user-attachments/files/15859847/Reckless.sav.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1c114ed7-27c9-42b8-a520-a1ad8c80804f)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/a46441a1-1333-4617-a8d5-b85ab7879d45)

???

**Comment by Bawookles** [comment]
Hmmm. I don't know why it isn't working for me. There's that toggle for "buff and debuff reckless attack on the start of your next turn" in UB, I wonder if that is doing something....

**Comment by ThyWoof** [comment]
Does this hero have reach?

**Comment by Bawookles** [comment]
Yeah, because it's the Wendigo race. Would that effect it?

**Comment by Bawookles** [comment]
Ahh, I see what you mean now. The advantage from reckless attack only happens when my Wendigo barbarian is adjacent to the enemy, not when he's attacking from reach. I'm hoping you can fix that for the Wendigo race.

Thanks!

**Comment by ThyWoof** [comment]
Fixed already. To be released soon

**Comment by Bawookles** [comment]
Thanks much!
