### ISSUE TITLE
Crashing when ever we get into combat

### ISSUE THREAD

**Issue by Vichnikov** [SolastaMods/SolastaUnfinishedBusiness#4725]
It has been crashing basically every time we get into combat.  We have UB 1.5.97.14 installed and using Unity Mod manger 0.27.3.0.
[Crash file.txt](https://github.com/user-attachments/files/15860382/Crash.file.txt)

**Comment by ThyWoof** [comment]
Use v12 or wait for v15 to be released tomorrow. V14 has a bug on concentration checks.
