### ISSUE TITLE
Lizardfolk Feeding Frenzy doesn't work

### ISSUE THREAD

**Issue by Tylron** [SolastaMods/SolastaUnfinishedBusiness#4730]
As stated, the Lizardfolk Feeding Frenzy bonus action attack just simply doesn't do anything. I've tried it in a multiplayer and singleplayer lobby. I've tried it while wielding no weapon, having 1 free hand, and while having both hands occupied. I've tried it as multiple different classes on fresh characters, even. After that, I reinstalled the mod entirely and UMM as well (I am on v.12 and have been) and even had other people test it and it didn't work on their end either.

I've attached our save file for convenience but it should be easy to make a fresh Lizardfolk and test it on your end regardless.

[Feeding Frenzy Test.zip](https://github.com/user-attachments/files/15862412/Feeding.Frenzy.Test.zip)

**Comment by ThyWoof** [comment]
already fixed in dev.
