### ISSUE TITLE
Crash while loading save

### ISSUE THREAD

**Issue by Pop000100** [SolastaMods/SolastaUnfinishedBusiness#4737]
Claims data corruption but I know that isn't it verified files.
[Save And Log](https://github.com/user-attachments/files/15881165/Desktop.zip)

**Comment by ThyWoof** [comment]
Is this in battle? If so can you try a save before entering one?

**Comment by Pop000100** [comment]
Yes and the previous save works

**Comment by ThyWoof** [comment]
I removed some blueprints that would happen in battle only. Thanks for confirming.
