### ISSUE TITLE
(Minor) Hexblade Soul Hex is being overly generous with its heal

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4738]
It's healing based on total character level rather than worlock level.

Load this save and drop a piano on the bandito to see it. Should be 6 rather than 9.

[QuickSave_1.zip](https://github.com/user-attachments/files/15890687/QuickSave_1.zip)

**Comment by ThyWoof** [comment]
Indeed. Easy fix: https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/d7aa22fe7d8bf58376e187d32d64aa13b0fb6ba6/SolastaUnfinishedBusiness/Subclasses/PatronSoulBlade.cs#L289
