### ISSUE TITLE
Strategic Reposition cancels Invisibility

### ISSUE THREAD

**Issue by hmarcbower** [SolastaMods/SolastaUnfinishedBusiness#4742]
Using Strategic Reposition when under the effects of Invisibility ends the Invisibility spell.

**Comment by ThyWoof** [comment]
I need your save to take any action.

**Comment by Thaladar** [comment]
You can use this save to see the issue.
[Strategic Repo test.zip](https://github.com/user-attachments/files/15906167/Strategic.Repo.test.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/7f6771ff-0a23-4fa5-9f60-2e8969c797e3)
fixed as well as Coordinated Attack gambit.
