### ISSUE TITLE
Circle of moon elemental WS only consuming 1 WS usage point

### ISSUE THREAD

**Issue by qeltar** [SolastaMods/SolastaUnfinishedBusiness#4743]
[pre 12.zip](https://github.com/user-attachments/files/15905315/pre.12.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/fe323a21-964c-426c-aa5c-0d6639306d39)
fixed.
