### ISSUE TITLE
Metamagic Adept bug?

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#4744]
I have a sorcerer and picked metamagic adept to get more sorcery points and additional metamagic options.
After I picked this feat, I (level 4) had 5 socrery points. (4 from sorcerer, 1 from the feat)
After a long rest, I now only have 4 sorcery points. 

Isariel is my character
[metamagic_adept_bug.zip](https://github.com/user-attachments/files/15906451/metamagic_adept_bug.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/06b79d60-dbc1-4e4a-b589-a3d2f8dd9c40)
not sure how you got there but the feat wasn't present on mentioned hero. I added it back using Party Editor. Do the same on your end and should be good to go.
