### ISSUE TITLE
Path of the Yeoman Barbarian not getting advantage on reckless attacks

### ISSUE THREAD

**Issue by ChaoticEvul** [SolastaMods/SolastaUnfinishedBusiness#4750]
Level 8. I've attached a screenshot I think. I'm raging, the creature is lit, I'm half sylvan elf anyways. I'm not threatened in any way. But I'm not getting advantage. What's worse, I was getting advantage a while ago but it just stopped for some reason.

Furthermore, I just went into the next battle. I clicked on reckless attacks first and I had advantage. As soon as I raged I lost advantage.

![2024-06-20 22_30_54-Solasta22](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/173426699/455cc80b-41d0-41b2-bf37-f816edb74abd)

**Comment by ThyWoof** [comment]
I cannot debug a screenshot. Got a save?

**Comment by ChaoticEvul** [comment]
One sec
Furthermore, I just went into the next battle. I clicked on reckless attacks first and I had advantage. As soon as I raged I lost advantage.

**Comment by ChaoticEvul** [comment]
[Save and log.zip](https://github.com/user-attachments/files/15922119/Save.and.log.zip)

**Comment by otearaisu** [comment]
Strange, I can replicate this on your save, but when I try to create a new game with a Yeoman Barbarian, I can get the Reckless attack advantage normally.

**Comment by ChaoticEvul** [comment]
I didn't have this problem originally either. Reckless was working fine. This is a problem for me from like level 6 on. I don't know if there is a bugged item or ability interaction going on somewhere. Furthermore, sometimes it sill works properly, so I don't know what's going on. I could try to respec into it again but rolling those stats again is going to suck.

**Comment by otearaisu** [comment]
Did you update versions while playing this campaign?

**Comment by otearaisu** [comment]
I think got the issue now, your Str and Dex are the same. The Reckless attack only works for Strength-based attacks. Not sure when the game decides to use Dex or Str when they are the same.

**Comment by ChaoticEvul** [comment]
That makes sense, it started around the time I used an Asi to increase my unarmored defense. So, I'm guessing I'm going to have to either respec a lower dex or wait until I get a tome or item to increase my strength.
