### ISSUE TITLE
Old Tactics feat blocks combats when it triggers

### ISSUE THREAD

**Issue by StalkerVagrant** [SolastaMods/SolastaUnfinishedBusiness#4752]
Bug Report

Unfinished business: 1.5.97.15
UMM: 0.27.10
No other mods.

Old Tactics feat reaction blocks combat. 
The enemy is already tripped and it's next in turn. Just have to click end turn.

[Old Tactics.zip](https://github.com/user-attachments/files/15928036/Old.Tactics.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/1c49a74a-b4bf-4146-887d-e96777ab60fc)
cannot repro on latest DEV build. should be fixed on v16 then.
