### ISSUE TITLE
Stealthy feat doesn't grant stealth expertise if you already have proficiency

### ISSUE THREAD

**Issue by mark-elder** [SolastaMods/SolastaUnfinishedBusiness#4753]
In the description of the stealthy feat, it says "You gain proficiency with Stealthy skill or expertise if you are already proficient." I presume it means Stealth.

Character I found it on: Wildling Spy Rogue, lvl 1. 14 dex score, stealth proficiencies from race and background, stealthy feat.

Expected result: Character should have +6 stealth. +2 from dex, +2 from proficiencies, +2 from stealthy feat.
Actual result: Character has +4 stealth, and no expertise icon. Just proficiency. Therefore, the stealthy feat must not give expertise.

**Comment by ThyWoof** [comment]
Share your save

**Comment by mark-elder** [comment]
[lost valley 1.zip](https://github.com/user-attachments/files/15930236/lost.valley.1.zip)

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/e7b2978e-9f75-421e-a33e-198d63ba2736)
cannot repro on latest v15 release. ensure you always update your mod version.
