### ISSUE TITLE
Drow light sensitivity inside darkness

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4754]
Probably should have noticed this sooner, but if a drow is suffering from light sensitivity, casting and being inside the Darkness spell does not stop it. I think it should.

**Comment by ThyWoof** [comment]
are you using the mod option that changes lightning rules? can you do this check with option on/off and share results? Pls also share your save with steps to repro.

**Comment by ThyWoof** [comment]
I cannot proceed here without a save for QA...

**Comment by ThyWoof** [comment]
No follow up. Closing

**Comment by RodrigoMamedeCosta** [comment]
Sorry, quite busy, no time to play. I will reopen if I have a chance.
