### ISSUE TITLE
Steel wind strike positioning not working

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4755]
Steel wind strike is not allowing me to do the last part of the spell: _You can then teleport to an unoccupied space you can see within 5 feet of one of the targets you hit or missed_. If that's not possible maybe teleporting to a square adjacent to the last picked target would be the same mechanically. Right now the caster just stays in the same place.

[QuickSave_1.zip](https://github.com/user-attachments/files/15936346/QuickSave_1.zip)

**Comment by ThyWoof** [comment]
Steel wind strike will only allow teleporting to the floor. All your enemies are flying on this scenario. Spell works as it should but in this particular case you won't get teleport offered as there is no place to teleport to.
