### ISSUE TITLE
"Bloody" artificer infusion ignores rogue subclass/features that alter sneak attack rules

### ISSUE THREAD

**Issue by mark-elder** [SolastaMods/SolastaUnfinishedBusiness#4761]
The wording of "Bloody" is: 
_Once per turn, when you hit with an attack with this weapon, that meets the same requirements as sneak attacks, deal an additional 2d6 damage.
Only one additional damage infusion can be active per weapon._

And if you consider the requirements of sneak attacks as being: Using a finesse/ranged weapon AND target is adjacent to an enemy of theirs, OR you have advantage, this works as intended.

However, if you have a rogue feature that modifies how sneak attack works, the Bloody infusion doesn't care.
For example, if you are a Hoodlum subclass rogue, your sneak attacks work differently. You get the Heavy Beating feature, which allows you to use sneak attack with non-finesse weapons, e.g. the weapon check component is removed. 

The Bloody infusion does not care about this feature, and still does it's own finesse/ranged weapon check. So you can't use it with the Hoodlum rogue subclass. :(

**Comment by ThyWoof** [comment]
Thanks for detailed explanation and save. I believe I can fix that for all custom rogue sneak attacks including 2 modded subs and the vanilla one.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/5f40d76c-ea30-48d3-b1d8-fbde620a2f3c)

**Comment by mark-elder** [comment]
amazing @ThyWoof. appreciate ya.
