### ISSUE TITLE
Baleful Scion damage continues on but healing stops

### ISSUE THREAD

**Issue by hmarcbower** [SolastaMods/SolastaUnfinishedBusiness#4763]
Using Baleful Scion and Fire Bolt. First fire bolt that hits triggers the Baleful Scion damage (1d6+2 Necrotic) and the healing (1d6+2 healing).  Then turn off the power so it doesn't trigger the second use (only a 4th level character for the test).  On next round, cast Fire Bolt again and, if hit, still does the 1d6+2 Necrotic damage and cites it's from Baleful Scion, but no healing is handed back to the caster on the subsequent rounds. 

The save is at the point where the sorcerer is ready to cast for the first time, so cast fire bolt until a hit triggers baleful scion, turn off the power, then keep casting Fire Bolt on subsequent rounds to see the damage continue.

Originally tested on .9, retested and issue persisted using DLL for v.16

[balefulsciontest.zip](https://github.com/user-attachments/files/16007839/balefulsciontest.zip)

**Comment by ThyWoof** [comment]
fixed in DEV. thanks.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/73245d6b-d274-4f0e-84c4-94279d07f9d2)
