### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4764]
https://drive.google.com/file/d/19apI7lIvZkPIDJTxT1lbPWuri7ibrgJX/view?usp=drive_link

improved effects that rely on spell damages target to also trigger on Call Lightning, and Delayed Fireball
-> I checked with the latest version. I understand that this option is not an option to set.

If my interpretation of this is correct, I understand that the options that trigger as spell damage will work.
However, the options that should be activated when damage is inflicted by a spell are still not activated.

We experimented with call lighting as an example. Even if you still damage an enemy with Call Lightning, the Circle of Balance level 10 ability no heal option will no longer appear on the enemy.
![4](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135420589/623b0231-d08c-4a6b-8e26-08ff09d5c278)

**Comment by ThyWoof** [comment]
Thought it would be an easy fix. Too much work to handle a scenario with one sub and 2 spells. Given it’s a vanilla issue won’t try any more fixes.

**Comment by kdgmo** [comment]
> Thought it would be an easy fix. Too much work to handle a scenario with one sub and 2 spells. Given it’s a vanilla issue won’t try any more fixes.

Can you tell me how to do it? I would like to at least fix this spell, Collightening.
