### ISSUE TITLE
Cannot Load

### ISSUE THREAD

**Issue by gaberybe** [SolastaMods/SolastaUnfinishedBusiness#4766]
Another user and I have been posting on the reddit for Solasta the last few months, and this is an issue that both of us are having and no one has a solution to as of yet. Here's hoping you might have an idea of how to fix it.

The issue is with opening Solasta and getting the Unfinished Business mod to work with Unity Mod Manager. I followed the steps included in the install guide, and have tried 4 different versions of UMM (.25, .26, .27, .27.10) and even got it to show on the mod manager screen when starting the game, I am using the most updated version downloaded yesterday 6/27/2024 version 1.5.97.16  But each time it gives an error report like the one I included as an attachment here. The UMM says "Ok" as the status before opening Solasta, but in the menu that pops up in-game the icon is red, with exclamation marks (which indicates I need to restart it, which I have done 10-15 times). When I check the logs, it says 0/1 mods loaded successfully and produces some version of what is included in the attachment.

![UB Error Report](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/174152895/f07c5292-6159-430f-9187-f5a956258de5)

**Comment by ThyWoof** [comment]
Your log has all indications of a pirate copy of the game. Buy the game and it will work.
