### ISSUE TITLE
Suggestion: Take proficiency into account in wildshape mental saves

### ISSUE THREAD

**Issue by Franavu** [SolastaMods/SolastaUnfinishedBusiness#4768]
It looks like there's a vanilla issue with druids, where on mental saves (int, wis, cha) in wildshape, the pc stats are used when they should (when higher), but proficiency isn't added.

save with level 11 Circle of the Moon Druid with proficiency in int and wis for reference: 
[Moon Druid.zip](https://github.com/user-attachments/files/16045506/Moon.Druid.zip)

**Comment by ThyWoof** [comment]
indeed vanilla doesn't do that. It only does for kindred spirits.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/0174643b-9417-4986-921c-c2ca7bc28056)
fixed but RESPEC will be required to get the new blueprint added at level 2.
