### ISSUE TITLE
Sunbeam with Focused Metamagic freezes game

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#4773]
Solasta 1.5.97
UB 1.5.97.17
No other mods

When casting Sunbeam with Focused Metamagic in this moment, it triggers the instability detected pop up and the game freezes. As far as I saw this does not happen with any of the other Metamagic options this character has available for Sunbeam (Quickened, Heightened, Subtle), while casting the spell without any Metamagic, or while casting any other spell with or without Metamagic. 

[UB_SunbeamFocusedFreeze.zip](https://github.com/user-attachments/files/16048898/UB_SunbeamFocusedFreeze.zip)

**Comment by ThyWoof** [comment]
![Uploading image.png…]()
fixed. thanks for save.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/55c8ebb2-bd77-4b4b-946c-ef0e4104015c)
fixed. thanks for save.
