### ISSUE TITLE
A few comments on Suggested tabletop spells

### ISSUE THREAD

**Issue by x2f01101011** [SolastaMods/SolastaUnfinishedBusiness#4777]
Artificer:
- Mordenkainen's Faithful Hound appears on Suggested spell list, but should not.
- Skill Empowerment does not appear on Suggested spell list, but it should be.

Cleric:
- Skill Empowerment appears on Suggested spell list, but should not.

Sorcerer:
- Skill Empowerment does not appear on Suggested spell list, but it should be.

Warlock:
- Skill Empowerment appears on Suggested spell list, but should not.

**Comment by ThyWoof** [comment]
Thanks. Fixed Skill Empowerment but Mordenkainen's Faithful Hound indeed belongs to Artificer per http://dnd5e.wikidot.com/spell:mordenkainens-faithful-hound
