### ISSUE TITLE
Coming back to Solasta after a year+ away...why is multiplayer now unusable?

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaUnfinishedBusiness#4781]
--WTH?  I tried to play with my kid, and Solasta desyncs less than 2min into any combat!!!  The only advice I found said to make sure you cap your FPS to 60, which I did on both our machines in NV control panel, specifically for Solasta.exe.  We both are using identical UB settings, and Solasta preferences (i exported my files).  It's so frustrating that there's not one f'n modern multiplayer DnD game, besides BG3 which is too R-rated for little kids.  Anyone else share my experience with UB desyncs?  Any multiplayer specific UB recommendations?  Otherwise my return to Solasta will be very short-lived.  Thanks.

**Comment by ThyWoof** [comment]
![](https://miro.medium.com/v2/resize:fit:300/1*iduCUtONBI7vgFEJb1lJPw.png)

you need to properly share logs to get help.

**Comment by gobsmacked1** [comment]
OK, uploaded my two most recent logs plus our UB xml settings.  Thanks.

[Player.log](https://github.com/user-attachments/files/16117988/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16117989/Player-prev.log)
[UBSettings.txt](https://github.com/user-attachments/files/16117990/UBSettings.txt)

**Comment by ThyWoof** [comment]
There isn’t a single error in these logs. I suggest you check advices from official discord comm on how to run MP. I have QA members testing this on a weekly basis and no desyncs reported by them.

**Comment by gobsmacked1** [comment]
There are only two articles on the official Solasta discord server mentioning the word, "desynchronization".  They're from May of 2022 and are mainly about how they've allegedly 'fixed it' in a patch that has since been deprecated, or telling people to use the beta branch, that's also deprecated.  I will say the game is perfectly stable in single-player with the exact same campaign, characters, save files, settings, etc.  Played for 3+ hours last night.  Not a single crash (in single-player).  Whatever instability is happening only triggers in  multiplayer, and usually within 1-3min of combat.  Not sure how to force UB to log desynchs for you to see what I mean.  It doesn't even seem to be player actions or reactions that triggers a desynch...a simple wolf walking toward the sleeping party caused the one where I provided the log.  If you know of any secret support article on how to stabilize MP games, we're all ears and we'll try it again.  Thanks.

**Comment by ThyWoof** [comment]
You should ask this question there.
