### ISSUE TITLE
Palace of Ice cold weather detrimental effects are not removed by campfire and magical items

### ISSUE THREAD

**Issue by Evilgrill** [SolastaMods/SolastaUnfinishedBusiness#4782]
[cold.zip](https://github.com/user-attachments/files/16119728/cold.zip)
Solasta version 1.5.97 GOG
UB version 1.5.9.17

The entire part standing next to campfire in a blizzard are frozen and chilled. I tried fireball them and found they suffer disadvantage on saving throw.
Boots of winterland, Anvil and ring of cold resistance are carried by each of them but they also do not do anything.

**Comment by Evilgrill** [comment]
In vanilla, the campfire remove chilled from cold weather normally. I could not test anything else.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/d7b793bc-4e26-42a7-9382-d9adb8850382)
there is nothing wrong here. this is how game works. whenever you move, gotta wait 6 seconds for these to refresh.

**Comment by Evilgrill** [comment]
This happens due to my mod setting. I changed to mod zappastuff and it works fine. I do not know what cause it.
