### ISSUE TITLE
Remorhaz heated body does not work

### ISSUE THREAD

**Issue by Evilgrill** [SolastaMods/SolastaUnfinishedBusiness#4784]
https://solastacrownofthemagister.fandom.com/wiki/Remorhaz
Solasta version 1.5.97 GOG
UB version 1.5.9.17
[remorhaz.zip](https://github.com/user-attachments/files/16120395/remorhaz.zip)

I have not tested if it works properly in vanilla, but they do not reflect 3d6 fire when hit by melee with UB mod installed. The battle log says something about it but there is no effect.

**Comment by ThyWoof** [comment]
mod doesn't touch this monster. Please confirm in vanilla first.

**Comment by Evilgrill** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/64213237/aea6eb46-c317-4e07-abb7-0ac18dcab6d8)
In vanilla, it works normally.

**Comment by ThyWoof** [comment]
Please share this save as well.

**Comment by Evilgrill** [comment]
It is a custom dungeon that I edited the base game one to test it. I do not know if you need the map.

Custom dungeon
[remo test.json](https://github.com/user-attachments/files/16122567/remo.test.json)
Save
[remosave.zip](https://github.com/user-attachments/files/16122624/remosave.zip)

**Comment by ThyWoof** [comment]
@HIEROT , can you give me a hand here. No idea why it's happening.

**Comment by HIEROT** [comment]
i can inspect it tonight but you know i don't attach debuggers just inspect code so no gurantee here(

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/270b3b0f-5af3-4f64-89fb-42d927d2cf0a)
fixed ;-)
