### ISSUE TITLE
MP Healing potions cause error/soft crash, unable to heal with potions

### ISSUE THREAD

**Issue by AmberSeorn** [SolastaMods/SolastaUnfinishedBusiness#4786]
[Healing Potions Bugged MP.zip](https://github.com/user-attachments/files/16122140/Healing.Potions.Bugged.MP.zip)

Per title, during MP play potions are unusable and cause a soft crash and error log that's been attached. Both players are using the same settings (exported/imported.) When either player loads up the same save in solo play they can use a potion fine, however it bugs when it's done in MP.

Save game is set right before a Cleric is set to use a potion. Again, potion works fine in SP, but in MP it crashes out.

**Comment by ThyWoof** [comment]
Are you using a potion from inventory or from action bar? Can you test both scenarios in MP? I have no ways to test MP myself.

**Comment by ThyWoof** [comment]
any updates on the tests?

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/674e41d9-fab1-4111-91e4-2b2b4fb044e1)
was able to test this one with a friend and no issues on latest DLL.
