### ISSUE TITLE
Battlemaster Superiority Dice not restoring

### ISSUE THREAD

**Issue by Stolcor** [SolastaMods/SolastaUnfinishedBusiness#4790]
The battlemaster does not gain his superiority dice back on a short rest. There's no crash or anything, just a simple loss of feature.

I tried creating a new battlemaster, leveling him up to 3 to get the sublcass, then starting a new campaign in Westmarches. He doesn't even start with the dice and short resting does nothing.
[Solasta 6_9_2024 2_11_29 PM.zip](https://github.com/user-attachments/files/16133759/Solasta.6_9_2024.2_11_29.PM.zip)

**Comment by ThyWoof** [comment]
This has been fixed in v17… Are you sure you have the latest version installed?

**Comment by Stolcor** [comment]
Was just coming to list version:

I just tried it in v18. I first noticed it in v16, rolled back to 15 to play, but then it broke again in v18 I think

**Comment by ThyWoof** [comment]
Ok. Will take a look.
