### ISSUE TITLE
The total number of maneuvers from the fighting style "Superior Technique" and the Battle Master subclass don't stack anymore

### ISSUE THREAD

**Issue by nickgoulet** [SolastaMods/SolastaUnfinishedBusiness#4798]
I updated the game earlier today to the latest update and went from I believe 4 maneuver dies to 1. The new changes seem to overwrite the number of dies, but the fighting style single die is set after the subclass. The character is a Barbarian / Fighter with Superior Technique fighting style and the Battle Master subclass.

**Comment by ThyWoof** [comment]
Need to update to latest and respec to get battle master pool fixed.
