### ISSUE TITLE
Ring of Blades doesn't add spell attack modifier

### ISSUE THREAD

**Issue by Swofty** [SolastaMods/SolastaUnfinishedBusiness#4799]
UB version 1.5.97.19

Ring of Blades is supposed to be a spell attack, but it currently doesn't include the spell attack modifier. My guess is that `BuildRingOfBlades()` in SpellBuildersLevel06.cs could use a call to `SetUseSpellAttack()`.

[ringofblades_atkmod.zip](https://github.com/user-attachments/files/16155871/ringofblades_atkmod.zip)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/8569010/1994b123-b2ba-4023-973f-7b75c689a491)

**Comment by ThyWoof** [comment]
not that simple. Power doesn't exist on hero progression so SetUseSpellAttack() won't help here.

```
            // __instance is required by Artillerist which has powers tied to caster
            var summoner = user.GetMySummoner();

            if (summoner != null)
            {
                user = summoner.RulesetCharacter;
            }

            var repertoire = user.GetClassSpellRepertoire(user.FindClassHoldingFeature(featureDefinitionPower));

            if (repertoire == null)
            {
                return;
            }
```

**Comment by ThyWoof** [comment]
will need to get this from condition to determine which spell / repertoire were used originally.
