### ISSUE TITLE
Blast Exclusive's beam count is not calculated properly

### ISSUE THREAD

**Issue by nickgoulet** [SolastaMods/SolastaUnfinishedBusiness#4801]
I'm using a 6 Bard / 4 Warlock and I have 1 beam at the moment. It should be 3 when reading the description. I believe a parenthesis is messing up the formula in ComputeAdditionalBeamCount

**Comment by ThyWoof** [comment]
@HIEROT

**Comment by nickgoulet** [comment]
I created a pull request if it can help

**Comment by ThyWoof** [comment]
Thanks. Once get confirmation from author this was the original intent will merge

**Comment by robvoid** [comment]
”You gain Eldritch Blast as a bonus cantrip. The number of beams is derived by your determination calculated as: [Warlock levels] - 2 * [Other Classes levels]. You can cast 2 beams when your determination >= 3, 3 when >= 8, 4 when >= 13 and 5 when >= 18.“

in your case, 4 - 2*6 = -8，shuild be 1

**Comment by nickgoulet** [comment]
You're absolutely right, read it as [Warlock levels - 2] * [Other Classes levels] for some reason. Would've been pretty damn strong too early
