### ISSUE TITLE
Problems with Arcane Archery in update 19

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#4805]
After updating to .19, I've experienced some problems with Arcane Archery. I've seen target deaths reported before choice of arrows. Hits that go directly to a burst without asking. Bursts that do not go off. And lock ups after choosing to use an Arcane shot. Seems something has gone amiss.

**Comment by ThyWoof** [comment]
I have been refactoring the mod backend lately to get rid of some fishy non reentrant code to better support MP.

I indeed touched this sub. Easy fix on next release.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/16185872/SolastaUnfinishedBusiness.zip)

Locate the mod DLL under your Solasta game folder, mods/Solasta Unfinished Business and replace with above DLL. Let me know if any better.
