### ISSUE TITLE
Fairy spell DC using CHA instead of spell casting ability

### ISSUE THREAD

**Issue by Evilgrill** [SolastaMods/SolastaUnfinishedBusiness#4809]
Solasta  1.5.97
UB 1.5.97.19

[passwithouttraceandfairydc.zip](https://github.com/user-attachments/files/16193966/passwithouttraceandfairydc.zip)
From http://dnd5e.wikidot.com/lineage:fairy
Intelligence, Wisdom, or Charisma is your spellcasting ability for these spells when you cast them with this trait (choose when you select this race).

Wiz fairy 18 INT 10 cha 3 proficiency 11 DC from 8 base + 3 prof. INT should be used to calculate DC.
Cleric fairy 18 WIS 8 cha 3 proficiency 10 DC from 8 base -1 CHA +3 prof. WIS should be used to calculate DC.
Sorc fairy 18 cha 3 proficiency 15 DC from 8 base + 4 CHA + 3 prof.

**Comment by ThyWoof** [comment]
by design. game won't learn higher level spells if the feature is in a feature set. it is CHA only.
