### ISSUE TITLE
Pass without trace incorrect bonus stealth

### ISSUE THREAD

**Issue by Evilgrill** [SolastaMods/SolastaUnfinishedBusiness#4810]
Solasta 1.5.97
UB 1.5.97.19

[passwithouttraceandfairydc.zip](https://github.com/user-attachments/files/16194051/passwithouttraceandfairydc.zip)
First two people in the turn order get +20 stealth bonus. Last two get +10 stealth.
Everyone should get only +10 stealth.

**Comment by ThyWoof** [comment]
Are you using lighting and obscurement rules in mod?

**Comment by Evilgrill** [comment]
No

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/d91c95a6-6e3a-4c61-8fe5-ff859e3cc111)
I cannot repro with empty mod settings.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/9f901ff1-6fe8-4397-9da6-9ae80fa565f6)

**Comment by Evilgrill** [comment]
![image](https://github.com/user-attachments/assets/efd747e1-85d7-4182-82b4-12c777514d85)
Empty setting and this time 3 guys are getting +20 stealth. I do not know what trigger it anymore. 
[empty.zip](https://github.com/user-attachments/files/16201151/empty.zip)

**Comment by ThyWoof** [comment]
Do you have a screenshot displaying the tooltip? This is the only way to confirm the parts adding to that total.

**Comment by Evilgrill** [comment]
Tooltips always show +10, but the battle log are +20.

**Comment by hmarcbower** [comment]
Can confirm that this happened to us as well.  Same thing, except I wasn't sure there was an order to it. tooltip showed +10, roll in the battle log showed +20.  I just recreated it as well:

![image](https://github.com/user-attachments/assets/7c0924e2-aa89-4516-8cc4-81f96f748faa)

If it makes a difference, this was cast from a Glitter Jacket item.

**Comment by ThyWoof** [comment]
very hard to identify the source without a proper tooltip. Could be anything but certainly not from Pass Without Trace. Even took the time to check for any occurrence of the word 10 in entire code base and there isn't anything touching stealth at all. not the mod.
