### ISSUE TITLE
Arcane Scoundrel Lvl 13 ability Arcane Backlash not working in MP (and weird in SP)

### ISSUE THREAD

**Issue by hmarcbower** [SolastaMods/SolastaUnfinishedBusiness#4812]
In single player, the Arcane Scoundrel will immediately and without interaction cast Counterspell on the first spell it can. I assume that's the free one at max level (see question below about that), as it doesn't use up a 3rd level spell slot (currently the highest level spell slot available to the character.  Additionally, no other character was offered to counterspell (a wizard and a warlock, both with counterspell). This did do sneak attack damage to the caster.

After that in the same fight, no prompt ever occurs for Counterspell for any character - except one time where the warlock was offered the chance to counterspell when their target tried to cast Shield.  But multiple lightning bolts before that went without a counterspell option.  Subsequent situations where counterspell should have been offered were not. Once the enemy was dealt with, started up another combat without resting.

In the second combat, the Arcane Scoundrel again immediately and without prompting counterspelled the first two spells that he could, using up his 3rd level slots and doing sneak attack damage on both uses. No other character was offered the chance to counterspell, and after the Arcane Scoundrel ran out of slots no counterspell was offered or triggered for him.

Now, in multiplayer, Counterspelling seems to work correctly (in that multiple characters are prompted to use it, including the Arcane Scoundrel), but there is no sneak attack damage done at all when the AS uses counterspell.

In case the way I was doing the testing has affected the single player experience, I spawned combatants from the bestiary and pasted them in, under my control (so I could force them to cast a lot of lightning bolts for testing).

currently at release 1.5.97.9 (and see no mention of this item being addressed in the release notes). The sav attached has a party I was using for testing the above.
[s152.zip](https://github.com/user-attachments/files/16203129/s152.zip)

Question about "max level" of the free use of Counterspell - is that max level like 9, or max level castable by the Arcane Scoundrel (3 in this case)?  The language in the wiki just says "you cast Counterspell at its highest level". I assume that's the max level the character can cast, but language could use a tweak if that's the case.

**Comment by ThyWoof** [comment]
It can counter up to level 3 spells and level 4 by the time it’s capable of casting level 4 ones (I believe it’s 18th on a 1/3 caster).

Rogue gets spell as a bonus one on progression as well as the power. All vanilla code. Vanilla indeed looks for powers or spells that can counter otherwise some monster powers wouldn’t be able to do so.

in other words this is pure vanilla so whatever happens here most likely happens without UB. Nothing I can do about.

**Comment by hmarcbower** [comment]
Except the Arcane Scoundrel is UB, and it seems to break Counterspell when the option exists for the AS to do it - like it checks with the AS, and if he can't do it, then nobody gets to. And there's still something broken about the free use one and then being able to use his additional ones in SP.  In MP, it does seem to at least prompt for counterspell, but then it doesn't do damage.  So I can't see that this is purely a vanilla problem since vanilla Counterspell obviously works fine - even right up until the AS reached 13th level it seemed to work fine.  I'm going to go test one more scenario - what happens if the AS is out of view of the caster... do other characters get a chance then.

**Comment by hmarcbower** [comment]
Never got that far - counterspell seemed to be working, though still an automatic use by whoever has counterspell (not sure how it decides order), but when the AS got his second Backlash use in, the goblin shaman died. As it proceeded to the next in initiative (a goblin shaman) I got a game warning.  The only entry that it put in the player log about it was this:

```
Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Removed invalid personal GameLocationEffect 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at GraphicsLocationSeeThroughManager.Update () [0x001cc] in <e6f6f336136b4c2991fe6af09dc40bd9>:0 
 
(Filename: <e6f6f336136b4c2991fe6af09dc40bd9> Line: 0)
```

I'm not sure if the GameLocationEffect lines were part of the crash or not (there were five entries and five goblin shaman left... coincidence perhaps), but that last bit was the last set of lines in the player.log when the error occurred.  Clearing the error I lost the action bar for the active creature (goblin shaman), and had to ALT-F4 as it wouldn't exit properly.  Maybe all this weirdness is just because I am trying to run the single player tests with UB-fabricated bad guys that I'm also controlling.

**Comment by ThyWoof** [comment]
Gotta let the engine control the enemy for a proper test for sure.

**Comment by hmarcbower** [comment]
Yep, just tested and when the engine controls the bad guy, it prompts for counterspell. Whew. And in SP it did do the proper damage. So I think the only remaining thing would be in multiplayer where it's not doing the sneak attack damage. Any thoughts on that?  I know that the sneak attack damage on other turns is working (we have a character that does Coordinated Attack, and if he's in the right position, gets his sneak attack on those).
