### ISSUE TITLE
Arcane Scoundrel Backlash not doing sneak attack damage in Multiplayer

### ISSUE THREAD

**Issue by hmarcbower** [SolastaMods/SolastaUnfinishedBusiness#4814]
Seems to work perfectly in single player. Multiplayer it doesn't do the sneak attack damage.  Will try to get player.log file from next session if that is helpful. No visible error thrown and no message in the log window.

**Comment by ThyWoof** [comment]
try this in SP and MP and let me know if fixed.
[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/16238989/SolastaUnfinishedBusiness.zip)

**Comment by hmarcbower** [comment]
Is this the dll for v.19?  I tried single player with the QA release for v.20 (which I gather is .19 plus a final few fixes listed in Discord) and it was OK. I'll see if I can rope someone into a MP test with me. :)

**Comment by ThyWoof** [comment]
Use this one on MP test.
