### ISSUE TITLE
[1.5.97.20] Bugs on metamagic shared spell

### ISSUE THREAD

**Issue by 25A2gEx** [SolastaMods/SolastaUnfinishedBusiness#4817]
Dear developer,

I found a bug when using the metamagic shared spell on an ally：when casting see invisibility or fire shield, the pointer can only choose an enemy instead of an ally. But there is no such bug when casting see invisibility on both an ally and self.

Moreover, in this save, when I tried to cast Draconic Transformation or shapechange, the system would report error and nothing happened. After that the caster could not move or take any action. But there is no bug when casting shapechange on both an ally and self using metamagic shared spell.

I attached the save in which the caster is named AAAtest.

[save.zip](https://github.com/user-attachments/files/16314164/save.zip)

During another test in my custom map, Draconic Transformation and shapechange worked without bug. But after casting shapechange on an ally using metamagic shared spell, the ally got transformed correctly but then the caster could not move or take any action (the system also reported error). Again there is no bug when casting shapechange on both an ally and self.

I also attached the save2 in which the caster is named test-mage.

[save2.zip](https://github.com/user-attachments/files/16314388/save2.zip)

**Comment by ThyWoof** [comment]
First issue is an easy fix. It looks like some vanilla blueprints have an incorrect target type. Will force it to always be ally if metamagic used.

here as an example: https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/614006bbac9e8fee2ee08d015265276100cba904/Diagnostics/OfficialBlueprints/SpellDefinition/SeeInvisibility.json#L45

**Comment by ThyWoof** [comment]
first one fixed here: https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/08260c117aa07ca5c429ec1cfbae6e1c68a5d36d

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/bc87017a-6177-423a-954a-7399e959a7da)
shape change, ally only, fixed.

**Comment by ThyWoof** [comment]
Fixed issue with Draconic Transformation which in fact was caused by Focused spell. All fixed. Thanks for reporting.
![image](https://github.com/user-attachments/assets/bf36dc40-b2ef-48bc-804f-3bb6daaa6215)
