### ISSUE TITLE
Suggestion: Add Tides of Chaos second paragraph to the ability for Wild Magic Sorcerer

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4820]
You've recreated the Wild Magic Sorcerer from the players handbook pretty much word for word BUT you kind of left out the thing that really made wild magic sorcerers fun and usable as a subclass.

The second paragraph of the "Tides of Chaos" ability is this:
**Any time before you regain the use of this feature, the DM can have you roll on the Wild Magic Surge table immediately after you cast a sorcerer spell of 1st level or higher. You then regain the use of this feature.**

Without this feature, the wild magic surge just happens too seldomly (only 1 out of 20 times when casting a non-cantrip) for the subclass to really register at all. If by using the Tides of Chaos ability means that your next non-cantrip spell will automatically cause a wild magic surge AND give you the Tides of Chaos feature back before a long rest, THAT's what really makes the wild magic sorcerer usable. 

I never met a DM in pen and paper D&D that didn't allow for this effect, because otherwise the wild magic sorcerer is extremely tame and not a beneficial subclass to pick. 

Thanks!

**Comment by ThyWoof** [comment]
Thanks for suggestions. This sub is still in Alpha and there will be a lot of QA before we release to ensure it adapts well to a computer game.

**Comment by Bawookles** [comment]
Cool! It would be interesting to see how you've interpreted the "Wild Magic Surge" table. Obviously some stuff on there would just not be adaptable or relevant to Solasta, like your height changing a few inches or you getting older/younger, etc.

**Comment by ThyWoof** [comment]
1 – **Chaos** - Trigger a random Wild Surge effect (except this one) at the start of each of your turns for the next minute. 
2 – **Fireball** - You cast a 3rd level Fireball centered on self. 
3 – **Healing** - You regain 2d10 hit points. 
4 – **Burning** - Each creature within 20 feet of you (including you) catches on fire. 
5 – **Teleport** - You can teleport up to 60 feet to an unoccupied space of your choice that you can see as a free action before your turn ends. 
6 – **Frightened** - You become frightened until the end of your next turn. 
7 – **Invisibility** - You become invisible for the next minute. The invisibility ends if you attack or cast a spell. 
8 – **Random Poison** - A random creature within 60 feet of you becomes poisoned for 1 hour. 
9 – **Spell Slot** - You regain your lowest-level expended spell slot. 
10 – **Maximize Spell** - Maximize the damage of the next damaging spell you cast within the next minute. 
11 – **Random Flight** - A random creature within 60 feet of you can fly for a minute. 
12 – **Grease** - You cast Grease centered on self. 
13 – **Mirror Image** - You cast Mirror Image. 
14 – **Wild Healing** - Each creature within 30 feet of you (other than you) takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt. 
15 – **Mass Invisibility** - Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell. 
16 – **Action Surge** - You can take one additional action immediately. 
17 – **Piercing Vulnerability** - You and all creatures within 30 feet of you gain vulnerability to piercing damage for the next minute. 
18 – **Resistances** - You gain resistance to all damage for the next minute. 
19 – **Lightning Strike** - Up to three creatures you choose within 30 feet of you take 4d10 lightning damage as a free action before your turn ends. 
20 – **Refill Sorcery** - You regain all expended sorcery points.

**Comment by ThyWoof** [comment]
I’m not doing 100 of them 😂

**Comment by Bawookles** [comment]
Ah, cool! Well, in truth, there's only 50 possible ones on the Wild Surge table! And maybe 1/3 of those are not applicable to the game.

**Comment by ThyWoof** [comment]
Tides of chaos if implemented as is will be a pain to play with lots of reactions pop up.

What if Tides auto reroll any 1s on attacks, checks, and savings?

Whenever it happens, wild surge is triggered?

**Comment by Bawookles** [comment]
That sounds like a pretty good idea. I do wonder though if the wild magic surge will still happen too rarely for it to be much of a factor. Maybe if you roll a 1 or a 2 on attacks, checks, and saving throws? Maybe also have Wild Magic Surges happen on a roll of 1-2 on a d20 for any time you cast a non-cantrip spell.

I can see your point about all the reaction pop-ups that would ask you if you want to use Tides of Chaos and that being annoying, but the Tides of Chaos feature is meant to give the Wild Magic sorcerer an actual advantage at doing stuff like attacks and saves. With your concept, they still fail their save or attack but they get the Wild Magic surge (which may be a non-beneficial result). 

What if when they roll a 1-2 on an attack, check, or save, they then automatically are successful on that roll but it causes a wild magic surge? Then they are getting some benefit to the ability while still getting the randomness of the wild magic surge.

Without their being some benefit..... then it's kind of like "why play a Wild Magic sorcerer? Just to watch random stuff occasionally happen that may or may not be a benefit to you?"

**Comment by Bawookles** [comment]
The simple truth is a Wild Magic sorcerer is gonna have to deal with a lot of reaction pop-ups anyway for their 6th level "Bend Luck" feature.

**Comment by ThyWoof** [comment]
Bend luck isn't that problematic as it only triggers if abs(delta) <= 4. I like the idea of 1-2s, we were discussing that already internally. Also like the idea of auto succeed to get something back.
