### ISSUE TITLE
Verdancy doesn't seem to work

### ISSUE THREAD

**Issue by nickgoulet** [SolastaMods/SolastaUnfinishedBusiness#4826]
When the druid heals another ally, the verdancy buff will appear on the druid instead of the healed ally and disappear on the druid's next turn. When the druid heals himself, the verdancy buff appears on himself and disappears on his next turn, without the extra healing.

[Verdancy.zip](https://github.com/user-attachments/files/16334946/Verdancy.zip)

**Comment by nickgoulet** [comment]
The campaign used in the save file is the Forge of Annihilation

**Comment by nickgoulet** [comment]
Removing the booleans from the EffectFormBuilder.ConditionForm for the verdancy EffectForms seem to have done the job

**Comment by ThyWoof** [comment]
fixed. thanks.
