### ISSUE TITLE
Solasta detected an instability when creating a new multiplayer campaign

### ISSUE THREAD

**Issue by DiogoSFernandes** [SolastaMods/SolastaUnfinishedBusiness#4827]
Solasta asked me to grab this file and send it here. The screen that tells me to close the game and grab Player.log appears when I try to initiate a new campaign (Morrows Deep) with my friend.
[Player.log](https://github.com/user-attachments/files/16354523/Player.log)

**Comment by ThyWoof** [comment]
Does it happen with brand new heroes? It looks like some of these heroes are incompatible.

**Comment by DiogoSFernandes** [comment]
> Does it happen with brand new heroes? It looks like some of these heroes are incompatible.

Yep, we just created the characters. I think we may have configured the mod differently, could that be the reason?

**Comment by ThyWoof** [comment]
All users must have exactly same settings.
