### ISSUE TITLE
Feature Request: Bulk Crafting Assistance/QOL 

### ISSUE THREAD

**Issue by BlackHatCS** [SolastaMods/SolastaUnfinishedBusiness#4828]
With all the buffs to craft speed for artificers, the inability to queue multiple items makes things... slow... Might there be a way to suppress the item completion notifications (so we can click interrupt) and/or auto-interrupt on completion?

**Comment by ThyWoof** [comment]
There is a slider on mod UI to decrease the time it takes to craft. This is the best we can do.
