### ISSUE TITLE
BUG: Cold Resistance does not give Chill/Frozen resistance when checked.

### ISSUE THREAD

**Issue by BlackHatCS** [SolastaMods/SolastaUnfinishedBusiness#4829]
Even when checked it still seems to apply.

Multiplayer game, no additional mods, version 1.5.97.22, resistance applied via infusion on armor. Quit game entirely and reloaded to confirm.

**Comment by ThyWoof** [comment]
Save and logs please.

**Comment by ThyWoof** [comment]
Any chance to share a save?

**Comment by ThyWoof** [comment]
No save, nothing I can do.
