### ISSUE TITLE
It's not about a problem, but rather to say thank you

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4830]
I'm new here and I don't speak English well, but I'm here to thank the mod team. I love Solasta and bought all the expansions, but something was missing, that something was Unfinished Business. Seriously, you are my heroes. I don't know if I can request something from the mod or if I'm doing it in the right place, but is it possible to make a request? I loved the addition of the pike and the hand crossbow, I would love if the mod also added the whip and sling weapons.

**Comment by ThyWoof** [comment]
I wish but nobody in the team knows how to create custom models. There isn’t anything in game we could reuse for whips or slings.

**Comment by Arcanis2** [comment]
What a shame. Still, it's okay, your work is fantastic.
