### ISSUE TITLE
Spells become unavailable when casting a spell at max spell slot level on some classes

### ISSUE THREAD

**Issue by igor-k-jp** [SolastaMods/SolastaUnfinishedBusiness#4835]
Solasta version: 1.5.97 
UB mode version: 1.5.97.23

Playing Ice Palace 
After casting a spell at max slot level all spells except cantrips become unselectable (blacked) until long rest.
Confirmed with Sorcerer and Druid class.
Doesn't happen with Paladin class

How to reproduce:
Select sorcerer, click Cast Spell, select a spell (ex. Fire Ball), cast at max level
Click Cast Spell again - all spells of level 1 and up are blacked

(the save file is attached)
[QuickSave_2.zip](https://github.com/user-attachments/files/16415470/QuickSave_2.zip)

**Comment by ThyWoof** [comment]
you can only cast 1 levelled spell per turn...

**Comment by ThyWoof** [comment]
cannot repro.
![image](https://github.com/user-attachments/assets/c2607dc6-7d07-4d25-b388-31729fb640ae)


with variant spell rules.
![image](https://github.com/user-attachments/assets/f37f7b75-2039-4a2e-8836-3b15bf6d257d)
