### ISSUE TITLE
[1.5.97.24] Bugs on metamagic shared spell/Shapechange/Symbol

### ISSUE THREAD

**Issue by 25A2gEx** [SolastaMods/SolastaUnfinishedBusiness#4837]
Dear developer,

After casting shapechange on the familiar using metamagic shared spell (say transformed into a dragon) during a battle,  both the dragon and familiar’s icons were on the top of the screen. It seemed that a dragon was added to the battle instead of replacing the familiar. The familiar became unseen but still acted every turn. But we lost the control of it. After the battle we got two familiars and one of them was still uncontrollable. Moreover after all this if one wanted to load save or log out, the system would report instability and get stuck.  There was no such kind of bug if the shapechange is not casted during a battle. 

Also there is no such bug when casting shapechange on a teammate using metamagic shared spell. However in both cases not only the caster but also the teammate (or the transformed familiar）got the concentration icon. I feel like that only the caster needs to concentrate.

The above situation is included in test3.sav and the caster is named AAAtest.

Another minor issue is about the spell Symbol. In test4.save a symbol spell had been casted under an enemy. If one skipped a couple of rounds until the symbol was triggered, the system would report instability. But everything worked well.

By the way, I cannot see the newly added 9th spells Invulnerability and Psychic Scream when upgrading a lv17 wizard to lv18 (or a bard from lv17 to lv18 using magic secret).

[save.zip](https://github.com/user-attachments/files/16426989/save.zip)

**Comment by ThyWoof** [comment]
Don’t cast shape change on a familiar. This scenario isn’t considered.
