### ISSUE TITLE
Experienced bugs

### ISSUE THREAD

**Issue by lanlixia** [SolastaMods/SolastaUnfinishedBusiness#4838]
Sorry if this isn't the right place to report issues, I couldn't find a better place from the readme instructions. 

Solasta version: 1.5.97
UB version: 1.5.97.24
No other mods installed

I ran into three issues on my current save:
1. **I get disadvantage to hit prone enemies with melee attacks instead of advantage.** An enemy fell prone on grease, but when I hovered over to attack, it showed disadvantage. When I rolled, it did roll with disadvantage. 
2. **The Stalwart Front/Sentinel feature on my Guardian Fighter doesn't stop an enemy's movement on opportunity attacks.** Relevant whenever an enemy leaves the fighter's threat range. 
3. **The Sanctuary spell doesn't make an enemy roll for wisdom before their attack deals damage.** I get the same results casting the spell with a cleric or an artificer. It does consume a spell slot, and the status effect ends when the recipient makes an attack or casts a spell (including healing, which I found odd). 

I can't upload the save or character files here, so if you need them, let me know where to email, upload, etc. and I'll do it asap.

Keep up the good work!

**Comment by ThyWoof** [comment]
You can upload any ZIP file here. ZIP your saves and logs.

Need a screenshot for 1 as cannot repro. Preferably with the tooltip displaying all ADV/DIS components on attack.

Probably fixed 2 already.

Saving Throw is coded on 3.
![image](https://github.com/user-attachments/assets/fa56dc0b-7972-43c9-b1b0-eba476228cf1)

**Comment by lanlixia** [comment]
Included:
- 2 screenshots, one pre attack and one post, with the tooltip and action log
- 4 character files, Forephiel is the relevant fighter
- wasn't sure what the necessary logs are, so I included the 2 Player.log files

[disadv_prone.zip](https://github.com/user-attachments/files/16464282/disadv_prone.zip)

**Comment by ThyWoof** [comment]
You are doing a ranged attack with your knife reason why you get DIS.

**Comment by HiddenHax** [comment]
Were you more than 5ft away? If so:

Prone
- A prone creature’s only option is to, unless it stands up and thereby ends the condition.
- The creature has disadvantage on attack rolls.
- **An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.**

**Comment by ThyWoof** [comment]
Also cannot repro Sanctuary. 2 was the only issue indeed and got fixed.
