### ISSUE TITLE
Bonus Action Attack from Polearm Master isn't adding strength modifier bonus to damage

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4839]
The bonus action attack for Polearm Master is not adding other damage bonuses like Strength modifier.
![image](https://github.com/user-attachments/assets/42bcadc2-1c9b-425c-9e91-092ca1fe6b34)

When Great Weapon Master is turned on, it adding +10 from Great Weapon Master but still not adding Strength to the Bonus Action attack.  It should be.
![image](https://github.com/user-attachments/assets/239e393d-3d52-4166-bb5d-73acd4b875d5)

**Comment by ThyWoof** [comment]
fixed.
