### ISSUE TITLE
Great Weapon Master and Polearm Master interaction issue

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4840]
Polearm Master says when you take the Attack Action you get a Bonus Action attack using d4 as the damage die.

Great Weapon Master says that when you get a critical hit or take an enemy to 0, you get a Bonus Action attack.  This attack should use the normal weapon damage die.

But currently, when you kill a creature (and presumable when you get a critical hit), the Bonus Action attack is still a d4 (from Polearm Master) instead of d10 (from Great Weapon Master)

![image](https://github.com/user-attachments/assets/85379d9a-f58e-4147-ad8b-6eb3f204115f)

Update: Confirmed issue on Critical Hits as well. 
![image](https://github.com/user-attachments/assets/4ec6786e-67b8-4356-9e26-82c89f50247f)

**Comment by ThyWoof** [comment]
fixed
