### ISSUE TITLE
Sentinel still bugged

### ISSUE THREAD

**Issue by lanlixia** [SolastaMods/SolastaUnfinishedBusiness#4845]
Sentinel features were not fixed with newest update. 

1. "sentinel_test.sav" tests the Sentinel's stopping ability with the opportunity attack. 
![hit1](https://github.com/user-attachments/assets/c0fe5435-fa35-4f0c-9517-6a6be0d405a0)
The fighter is a wendigo, which has +5 reach, so the enemy should have been stopped one square away, however they were not stopped, as shown in the screenshot "hit1.png" and save file "sentinel_test_hit_no_stop.sav".

2. "sentinel_test2.sav" tests the Sentinel's retaliation ability when an ally is attacked. 
![hit2](https://github.com/user-attachments/assets/ca8fa276-3be1-4f0b-b30e-f96e433c9136)
The ally was attacked four times from an adjacent square, but there was no prompt for an opportunity attack. Shown in screenshot "hit2.png" and the save file "sentinel_test_ally_attack.sav".

Solasta Version: 1.5.97
UB Version: 1.5.97.25
No other mods
Campaign: Palace of Ice (Official)

[sentinel.zip](https://github.com/user-attachments/files/16489232/sentinel.zip)

**Comment by ThyWoof** [comment]
Use Party Editor to manually grant the Sentinel feat to this hero. Somehow UI says you have the feat but you really don't.

![image](https://github.com/user-attachments/assets/8d70da5a-75e5-44ee-9b6a-e4adb730c81e)

scenario 1:
![image](https://github.com/user-attachments/assets/9dbe6077-b773-43a4-9008-acc5752a90ed)

scenario 2:
![image](https://github.com/user-attachments/assets/ae28b316-9889-49ea-89ef-b829668d6c5c)


it works as it should.
