### ISSUE TITLE
Masterful Whirl doesn't seem to be working

### ISSUE THREAD

**Issue by resumeman** [SolastaMods/SolastaUnfinishedBusiness#4846]
When I have it selected, the reaction dialog pops up but the text in the button looks like code. I click the button, do the attack, and it seems like only the regular weapon damage is being done.

[Player.log](https://github.com/user-attachments/files/16490079/Player.log)
[whirl.zip](https://github.com/user-attachments/files/16490088/whirl.zip)

**Comment by ThyWoof** [comment]
You are using 1.5.97.19. I only support the latest version of the mod.
