### ISSUE TITLE
Sunlit Blade Cantrip - Highlight fades immediately

### ISSUE THREAD

**Issue by 007quick** [SolastaMods/SolastaUnfinishedBusiness#4851]
When my bard casts sunlit blade and hits, the target is highlighted but the enemy looses the status right after the attack finishes resolving.
Newest version of Solasta and Mod (1.5.97.25)
No other mods installed.
Characters were all created just this week with a fresh install of the mod.
The save will load on my bard's turn and you can use the cantrip and observe the problem.
[Save and logs.zip](https://github.com/user-attachments/files/16537880/Save.and.logs.zip)

**Comment by ThyWoof** [comment]
Already fixed in dev, thanks

**Comment by 007quick** [comment]
Awesome.  Thanks!  You do great work!
