### ISSUE TITLE
variant spell point rules

### ISSUE THREAD

**Issue by MasterYaro27** [SolastaMods/SolastaUnfinishedBusiness#4853]
When using the "variant spell points" rule, using a 6th spell causes all spells to be unavailable. Only thing I can think of is that it uses the single lvl 6 spell slot which uses all of the spell slots.

Hopefully pictures below work and show what I mean. 

![1096530_343](https://github.com/user-attachments/assets/361e43f8-28d0-4625-96e5-45c076375d67)
![1096530_344](https://github.com/user-attachments/assets/e56effdf-acaa-43e9-b4b5-579a58b248dc)
![1096530_345](https://github.com/user-attachments/assets/52e21f1c-0ea4-48bf-921a-e35a3892dbb4)
![1096530_346](https://github.com/user-attachments/assets/330e0dc0-0d87-412b-baf9-bd05151c0a5f)

**Comment by ThyWoof** [comment]
Already fixed in DEV, thanks
