### ISSUE TITLE
Time Stop: Broken interactions

### ISSUE THREAD

**Issue by jk2l** [SolastaMods/SolastaUnfinishedBusiness#4855]
I noticed two broken interactions:

1. If the target is down at 0hp, Time Stop don't stop time, and after they get healed they can move
2. The time stop target have Time Stop condition removed if they take any damage. It is like they just simply "Sleep" and get wake up once get attacked. It does not sound like the spell doing what it intended to do

**Comment by HiddenHax** [comment]
In original spell (which this one was made after), if you affect any of time-stopped creatures with _anything_, the whole spell ends, not just the condition on one of creatures.
Doesn't have much practical use I can think of in Solasta as majority of all interactions you do are with creatures, whereas on TT you can manipulate the environment in whatever way you wish as long as you don't touch affected creatures.

The desc is incomplete and needs updating in any regard.
https://roll20.net/compendium/dnd5e/Time%20Stop#content

**Comment by ThyWoof** [comment]
This spell was written a long time ago by another modder. Back then we didn't have the right tools to make it work as vanilla. I believe I can fix that to work by the letter.

**Comment by ThyWoof** [comment]
fixed.
