### ISSUE TITLE
'Clothing' of survival doesn't give +2 AC

### ISSUE THREAD

**Issue by 007quick** [SolastaMods/SolastaUnfinishedBusiness#4856]
My group noticed this a while back and I thought it might have been fixed by now but the description on the various clothings of survival indicates that it should give +2 AC but it does not.  It does give the increased save rolls.  We saw this on a barbarian clothing and monk clothing in the past.  My current playthrough has a wizard and monk with the clothing and the bug persists.

**Comment by ThyWoof** [comment]
They indeed won't stack with any other source of natural armor. It won't get fixed as fix would require players to RESPEC. Don't use them.

**Comment by 007quick** [comment]
Sounds good.  Thanks
