### ISSUE TITLE
Monk - Way of Survival - Patient Defense - No bonus unarmed attack

### ISSUE THREAD

**Issue by 007quick** [SolastaMods/SolastaUnfinishedBusiness#4857]
If I do a Flurry of Blows, I get:
Regular Attack
Regular Attack
Unarmed Attack
Flurry Attack
Flurry Attack

If I do a Patient Defense (Way of Survival gives a special version) I get:
Regular Attack
Regular Attack

This could be intended behavior but I suspect that choosing either flurry or defense should be the same 'type' of action so should result in 5 attacks vs 3 attacks.

This save is setup that you can activate one ability or the other and then attack with my monk immediately to observe.

I suspect that the patient defense is using up the bonus action when it is not supposed to.

[Monk issue.zip](https://github.com/user-attachments/files/16564025/Monk.issue.zip)

**Comment by ThyWoof** [comment]
Flurry and Patient Defense are BA. There is nothing wrong here. Way of Survival only give ADV on attacks if you use Patient Defense.

**Comment by 007quick** [comment]
Are you sure?

If Patient defense is using the bonus action and therefore just 2 x attacks (or whatever your base number is) is accurate, why does activating flurry still allow me to take a bonus action unarmed attack?  If they both use a bonus action I would expect that activating flurry results in:
Regular attack
Regular attack
Flurry Attack
Flurry Attack

Since the unarmed attack is a bonus action.

**Comment by ThyWoof** [comment]
You probably have a feat allowing that.

**Comment by 007quick** [comment]
Oh, I do have Pugilist. Even still, if Pugilist grants a bonus attack in one scenario, shouldn't it do the same in the other?

**Comment by 007quick** [comment]
That does make sense.  It is still worth picking up for a monk for the extra d4 damage and occasional ki-less attacks.  Here is a screenshot of my monk settings within the mod if it helps.
<img width="560" alt="Screenshot 2024-08-10 081727" src="https://github.com/user-attachments/assets/170fa9d5-c3ac-4567-9c1c-53df1ed87988">
