### ISSUE TITLE
Solasta has detected an instability.

### ISSUE THREAD

**Issue by Lemagex** [SolastaMods/SolastaUnfinishedBusiness#4867]
Adding logs here as per the in-game message.
Steps:
Traveling (slow)
Combat begun (spotted by warlock)
Initiative rolled, initiative not used correctly.
Error.
[Player.log](https://github.com/user-attachments/files/16594540/Player.log)
[AutoSave_17.zip](https://github.com/user-attachments/files/16594542/AutoSave_17.zip)

**Comment by EnderWiggin** [comment]
This save is inside city upon return. Do you have a save file during travel, or before it?

**Comment by Lemagex** [comment]
I do not, I purged the game / leftover files after this to try fix it, and now it's not happened since.
