### ISSUE TITLE
Strike of Chaos in Mischief Cleric not activating nor showing a charge

### ISSUE THREAD

**Issue by wjdecker** [SolastaMods/SolastaUnfinishedBusiness#4870]
Mischief Cleric Channel Divinity: Strike of Chaos, Level 2+
Not triggering, nor is it showing as having a charge

Solasta (current) 1.5.97
UB (current) 1.5.97.26
Custom dungeon - Diablolasta (shouldn't be relevant)
[Player.log](https://github.com/user-attachments/files/16602951/Player.log)
[IM_GJSVpJOFEKtYoeD0WsxKQM_3.zip](https://github.com/user-attachments/files/16602952/IM_GJSVpJOFEKtYoeD0WsxKQM_3.zip)

**Comment by EnderWiggin** [comment]
That's really weird - your cleric has only level 1 features. Not sure how that might have happened. I've tried re-speccing and that character was fine after that.
You can try this yourself - enable Re-spec under Interface Settings, then open Credits->Party Editor and press Long rest button there.

**Comment by ThyWoof** [comment]
If you go way too fast on level up this could happen. Vanilla issue.
