### ISSUE TITLE
de-synchs in coop have greatly increased

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#4872]
Since the recent updates, I've been experiencing a lot more de-synch events playing coop. We've always had these, maybe two or three during a session, but now they come so often we can't finish a battle. When a new turn starts, about half the time my guest sees a completely different chain of events. Or when it's supposed to be his turn, there is no active character on his screen. There does not seem to be a pattern to it, but you can almost count on it when my guest has to respond to an opponent action, such as a counterspell.

I have looked at the Photon status chart and there have been a very few outages on the US West server, but not enough to suggest this is a Photon failure, even though some of the de-synchs are reported as Photon outages. Almost always, an immediate reload will succeed after getting this.

We are at update level 25, currently playing Tomb of Doom by d36williams with 6 characters. We've also tried other campaigns with four characters and have had the same problem. We have not tried playing without UB.

This may not be relevant, but I thought I might mention it. On a new Solasta startup, the first time my guest joins a multiplayer game, he is incorrectly assigned one of the host's characters. I'll assign him three characters, but when play starts, he also has control of one of mine. I can also control that character. On a restart, the problem is gone. We have lived with this for a long time.

**Comment by ThyWoof** [comment]
Can you please use v26 and share feedback on desyncs?

**Comment by charlesewatkins** [comment]
We will do this on Saturday.

**Comment by charlesewatkins** [comment]
Found time for a quick test run this afternoon after both of us updated to v26. Sorry to report the problem is still there. De-synch every time my guest's turn came.

**Comment by ThyWoof** [comment]
Charlie, pls share this save.

**Comment by ThyWoof** [comment]
Charles, Can you unzip attached file, replace the DLL on all players computers, and test again?

[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/16640437/SolastaUnfinishedBusiness.zip)

**Comment by ThyWoof** [comment]
Please reopen if v27 doesn't fix it
