### ISSUE TITLE
Problem with Armor of Agathys spell.

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4873]
When I kill a creature with Armor of Agathys or Fire Shield damage, the Fiend's Dark One's Blessing feature does not activate. Is this a bug? Is it possible to fix?

**Comment by ThyWoof** [comment]
Do you already have temp hit points? Armor grants some and I believe the higher wins.

**Comment by kosocku** [comment]
my understanding of 5e RAW is that if you have temp HP (like from AoA) and you get temp HP from another source, you decide which you keep.  So, I guess the interaction in this situation would be to proc a choice box (similar to when a Paladin hits with Divine Smite always active) asking if you want to keep AoA temp hp or replace with new?

**Comment by HiddenHax** [comment]
Or better yet, THP could be automatically replaced with new value from Dark One's Blessing if current remaining THP(after the hit) is lower than the one that'd be gained from Dark One's Blessing.

But regarding OPs post, I think they meant that Dark One's Blessing never activates with damage reflection features like the two mentioned above, which is a bug.

**Comment by Arcanis2** [comment]
@ThyWoof 
Do you already have temp hit points? Armor grants some and I believe the higher wins.

I tested it with both situations. Killing the creature on its turn while still having AoA THP and also killing the creature without having any more THP. I also tested only the fire shield, but in neither of these tests I was able to gain the Dark One's Blessing THP.

@kosocku
kosocku commented 5 hours ago
my understanding of 5e RAW is that if you have temp HP (like from AoA) and you get temp HP from another source, you decide which you keep. So, I guess the interaction in this situation would be to proc a choice box (similar to when a Paladin hits with Divine Smite always active) asking if you want to keep AoA temp hp or replace with new?

My interpretation of the RAW is the same as yours kosocku. But I don't know how difficult it would be to program this in UB.

@HiddenHax
HiddenHax commented 4 hours ago • 
Or better yet, THP could be automatically replaced with new value from Dark One's Blessing if current remaining THP(after the hit) is lower than the one that'd be gained from Dark One's Blessing.

HiddenHax I personally prefer the lower AoA THP than the higher Dark One's Blessing THP because I use damage resistance tactics (blade ward) and then I deliberately provoke attacks of opportunity on enemies to deal damage with AoA, Fire Shield and Hellish Rebuke. The Dark One's Blessing THP would only enter my tactic after all AoA THP is gone.

But regarding OPs post, I think they meant that Dark One's Blessing never activates with damage reflection features like the two mentioned above, which is a bug.

Exactly. What bothers me is the fact that I can't gain Dark One's Blessing THP when I kill a creature with reflected damage.

Edit: But I think that Dark One's Blessing in vanilla should already cover THP scenarios, and fix for above would just include activating Dark One's Blessing on kill with reflection features (which as posted above don't currently seem to work with it at all)

**Comment by ThyWoof** [comment]
can confirm Fire Shield is a vanilla bug. Anything that SpendPower will fall into same issue. Looking for a fix.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/74d634ae-ab2d-42d6-97ef-fc5c7558e03a)
fixed.

**Comment by Arcanis2** [comment]
fixed for anything that kills an enemy with a SpendPower action. This includes both reported issues and a bunch more vanilla and modded.

You rock! 

Thanks a lot ThyWoof
