### ISSUE TITLE
Warlock Maddening Hex Error

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4874]
[Vexing Hex.log](https://github.com/user-attachments/files/16631605/Vexing.Hex.log)

[AutoSave_4.zip](https://github.com/user-attachments/files/16631666/AutoSave_4.zip)

I think when the warlock uses maddening hex it throws this error

Error Context : Name = PowerInvocationVexingHexDamage, SourceGuid = 177, Level = 0, ActionType = Main, SourceType = Power, EffectSourceType = Power, SaveDC = 0, SourceAbility = Charisma, SchoolOfMagic = , MetamagicOption =  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Exception: [TACTICAL INVISIBLE FOR PLAYERS] null GameLocationEffect in CharacterActionMagicEffect.ExecuteImpl().

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
SolastaUnfinishedBusiness.Patches.<ExecuteImpl>d__1:MoveNext()
TA.Coroutine:Run()
GameLocationActionManager:UpdateImpl()
GameLocationActionManager:FixedUpdate()

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/73ac5363-6773-4c8d-876d-83ea76d3bccc)
cannot repro on v26 in DEV. Probably fixed.
