### ISSUE TITLE
Clothing Armor of Survival and Monk Unarmored defense

### ISSUE THREAD

**Issue by Boler-Kavint** [SolastaMods/SolastaUnfinishedBusiness#4887]
Solasta Version: 1.5.97.

UB version: 1.5.97.27

Other mods: the Forsaken Isle custom campaign

Short description: a character with the monk's "Unarmored Defense" feature does not benefit from the +2 AC bonus of any Clothes of Survival armor. When a character that doesnt have this feature wears an armor such as "Sorcerer Armor of Survival" or "Monk Clothes of Survival", their AC breakdown lists a base of 12 that is affected by AC increasing effects properly, which corresponds to the 10 base AC being increased by 2 due to the effect of the Armor's enchantment.

However, when a monk wears such an armor, the indicated AC doesnt increase. When hovered over, the AC breakdown lists a base AC of "10 + wisdom modifier", ie on a monk character with 20 wisdom, the AC breakdown says "base AC 15". Our guess is the bonus from the feature overwrites the Armor's enchantment's effect.

[bugreport_material.zip](https://github.com/user-attachments/files/16651696/bugreport_material.zip)

**Comment by ThyWoof** [comment]
These won’t stack and removing these items now would cause issues on current saves. Won’t fix, don’t use them.
