### ISSUE TITLE
still having frequent de-synchs

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#4891]
As of update 27, in coop play every move by a guest player results in a de-synch.

**Comment by ThyWoof** [comment]
I need the logs please

**Comment by charlesewatkins** [comment]
Here is a recent save. There is a battle beyond the secret door. 
[a1.zip](https://github.com/user-attachments/files/16853671/a1.zip)

**Comment by charlesewatkins** [comment]
Is there anything we can do to help identify the source of the problem? If you need a possible fix tested, we'll be happy to oblige. Could we maybe load DLLs for the prior versions to see where the problems began?

**Comment by ThyWoof** [comment]
I’m waiting for someone from discord server to help me test this on a MP session.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/cb3f228c-c294-4a06-bd20-cb374a9c151a)
I was able to open and use this save without issues in MP. Not sure what else to suggest. Maybe ask every player to check game files.

**Comment by HiddenHax** [comment]
A common source of problems includes settings.xml mismatch and file corruptions.
Verifying game files for each player, making sure all players run identical mod version and making sure .xml is identical for all players is important.

**Comment by ThyWoof** [comment]
![{78044F4D-26E2-4D69-A1E9-7C029E5D58F7}](https://github.com/user-attachments/assets/a20a9a04-eb4f-4dbb-8b46-b642b69422d1)
this is the latest feedback I got from the QA folks who help with MP. v31 haven't caused any issues over a 2hrs session.

I suggest check game files on all players computers, and ensure everyone is using same settings.
