### ISSUE TITLE
Null pointer error on death

### ISSUE THREAD

**Issue by otwk** [SolastaMods/SolastaUnfinishedBusiness#4892]
I have the newest version (1.5.97.27) of Unfinished Business installed, and I am getting a consistent "Game Warning!" about an instability, followed by the game getting stuck (as I am in control of a downed character, and cannot switch to the next), when any character dies by failing a death saving throw on their turn.

I have all UB options disabled ("empty" preset). [I have to have the mod because I respecced one of my characters.]

This happens regardless of if it is the respecced character, or one that the mod has not touched at all, and it only happens when they fail a death saving throw, not through taking damage while in the dying state.

The issue appears to be a null pointer exception in this function: 
SolastaUnfinishedBusiness.Patches.BattleState_TurnReady_ExecuteDeathSavingThrow+<Postfix>d__0.MoveNext ()

An example log is attached; it says something about concentration, but this happens regardless of concentration (as it also affects at least 1 character who can't cast any spells).
[Player.log](https://github.com/user-attachments/files/16693498/Player.log)

Update: I made a local copy of the mod and followed the guide to edit and install it with VS; after completely removing the ExecuteDeathSavingThrow patch function, the error still persists. So it appears to originate from a function that is not mentioned in the stacktrace.

**Comment by ThyWoof** [comment]
Share this save please
