### ISSUE TITLE
Swords Bard blade flourish broken in .27?

### ISSUE THREAD

**Issue by VanBurenPhilips** [SolastaMods/SolastaUnfinishedBusiness#4895]
I was playing a Bard/College of Swords and noticed the blade flourish toggle disappeared from his dashboard mid-adventure. Didn't make the connection at the time, but it happened when the latest update dropped. Made some dummy characters to try to figure out what was wrong, and it seems blade flourishes just don't work under ver .27 (for me).

(the button is missing from the dashboard, and since I *think* the default setting is 'off,' flourishes never trigger. On an old save, where I had them switched on, flourishes will trigger, but the button is gone)

I rolled back to .26 and everything was back to normal, working properly again. Updated and rolled back again a couple of times to check and yep, same results. Asked on steam forums to see if anyone else would check, no dice so far, so the sample size is just me, but here ya go.

Thanks for an excellent mod, btw

[Player.log](https://github.com/user-attachments/files/16709089/Player.log)

**Comment by EnderWiggin** [comment]
I think this _should_ be fixed in next release. Fix was made several days ago, so will be in next version.

**Comment by VanBurenPhilips** [comment]
Thanks :)
