### ISSUE TITLE
Cant get it to work.

### ISSUE THREAD

**Issue by Affix111** [SolastaMods/SolastaUnfinishedBusiness#4905]
I just bought the game on steam. I installed it and all the DLC, i laucnhed the game and then quit. I went to the github page and followed the instructions on how to install Unfinished business with the Mod manager. 

I launch the game and the mod manager UI comes up but the status symbol is RED and not green. Iv checked the instructions and dont know what could be wrong, Iv tried the lates mod version and the one before that.

Any ideas?

**Comment by ThyWoof** [comment]
Share a screenshot of the game main page with the mod UI opened on logs tab.

**Comment by Mephizzzle** [comment]
Hi, I think you need to downgrade you Unity Mod Manager, latest version (0.28.2) doesnt seem to be working with UB at the moment. (0.27.7.0 does work)

**Comment by Herteby** [comment]
> Hi, I think you need to downgrade you Unity Mod Manager, latest version (0.28.2) doesnt seem to be working with UB at the moment. (0.27.7.0 does work)

Thanks! I was in the same exact situation and it fixed it for me.
