### ISSUE TITLE
Maddening hex still broken

### ISSUE THREAD

**Issue by orangepeelpanda** [SolastaMods/SolastaUnfinishedBusiness#4907]
[AutoSave_3.zip](https://github.com/user-attachments/files/16808836/AutoSave_3.zip)
[Player.log](https://github.com/user-attachments/files/16808837/Player.log)

still got this error when I used maddening hex in co op mode. non-host uses the maddening hex and it throws this error.

**Comment by ThyWoof** [comment]
There isn't much else I can do here. Error complains about an attack action. v28 has an small issue with spells so might be it. If not fixed in v29 won't get fixed.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/7390f0b5-db58-403f-9645-07ddd1d231dc)

![image](https://github.com/user-attachments/assets/0b64ed3c-ad53-4d66-a780-fe13950ecc98)

this was on v29, no issues at all on your save.
