### ISSUE TITLE
Warding bond Vanilla bug?

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4908]
Is it possible to enable Warding Bond Spell to the Cleric list?

In the Vanilla game it is possible to find scrolls with this spell in random lots, but no character is able to use.

I believe they first created the spell and then in the last minute they made a decision to remove from the game, but ended up leaving remnants that did not remember erasing.

It would be nice if there is a lost code inside the game with this spell somewhere for you programming gods to restore to UB.

**Comment by ThyWoof** [comment]
This spell hasn't been completed in game. Should ignore these scrolls.
