### ISSUE TITLE
Cauterizing Flames heal bug

### ISSUE THREAD

**Issue by miridistress** [SolastaMods/SolastaUnfinishedBusiness#4909]
Circle of Wildfire 10th level ability Cauterizing Flames only heals targets up to 50% health. It's not supposed to have that limitation.

I don't have a save file to give you this time, I'm sorry. I just remembered it was an issue in an old campaign a couple of patches ago and it hasn't been fixed yet.

**Comment by ThyWoof** [comment]
Thanks. No need, one line change: https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/e1ee274df3dbb41ce2e23b512e1f38646a908e9a/SolastaUnfinishedBusiness/Subclasses/CircleOfTheWildfire.cs#L88
