### ISSUE TITLE
Power Attack feat cancels Bladestorm feat

### ISSUE THREAD

**Issue by Csatadi** [SolastaMods/SolastaUnfinishedBusiness#4912]
Hi,
The hero started with Bladestorm. I took him Power Attack at level 6. The options of Bladestorm no longer appear in the menus during fights, neither the multiattack nor the attack from bonus action. He also has Sentinel, that works.
Do you need saves?

**Comment by ThyWoof** [comment]
I would try a RESPEC first and avoid going too fast on level up.

**Comment by Csatadi** [comment]
What do you mean exactly? I tried to remove the feat in the party editor and add it again. No success.

**Comment by Csatadi** [comment]
I found there is a Respec option. It didn't help. Rolling back to version 28 didn't help. Reinstalling UB, verifying Solasta files on Steam didn't help. Going back to quite old saves didn't help.
Actually the Bladestorm feat went wrong, regardless what I choose at leveling, for example ability scores.
When I start a new campaign, Bladestorm works.

**Comment by ThyWoof** [comment]
Glad it works on a new campaign. I couldn’t find any issues on my end.
