### ISSUE TITLE
New suggestion about grappling

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4914]
First, create a new tab next to shove (or even inside it), with the name "grapple".

Grapple would have a range of 1 square to apply a new negative condition to the creature that fails this skill test contest (athletics vs athletics/acrobatics).

Two new conditions would be created:

1 - Grappled:
Sets the grabbed creature's speed to 0.

2 - Grappling:
Create a new tab to moves the grabbed creature 1 square in a direction (north, south, east, west) without the right to a saving throw, but with a cost: reducing 10 feet of the grabber's movement for each square the creature moves. When the grabber's movement reaches 5 or 0, they are unable to move the grabbed creature.

The grappled and grappled condition ends when the grabbed creature is knocked out or when the grabber is incapacitated.

It's not the same as the rules in the dnd5e book, but it was the best I could think of to be similar and fit here in Solasta.

Is this idea too difficult or is it possible?

**Comment by ThyWoof** [comment]
Will take a look. Working on Dissonant Whispers and Command spells for next release.

**Comment by Arcanis2** [comment]
I love you ThyWoof  *-*

**Comment by ThyWoof** [comment]
![](https://pbs.twimg.com/media/DdIUEk-X0AEdKeC.jpg)

**Comment by ThyWoof** [comment]
WIP.
