### ISSUE TITLE
Respec.

### ISSUE THREAD

**Issue by tonphu** [SolastaMods/SolastaUnfinishedBusiness#4915]
So, apparently, if you decided to use the Respec in a multipart adventure, it will NOT allow you to update your character at the end of the adventure. Anyway to fix this issue manually? Also: random 'quest' items are dropping from creatures with no actual quest assigned, Is there any way to force a character to drop these using the mod? *I resorted to the respec to do this. I love the options and the new characters/races. 
Took some time to figure out how to get it to work. If anyone has a 'tutorial video' on how to install and use it, you might want to link it in the Help Me file.

**Comment by ThyWoof** [comment]
I would need a small test save with one room where I can exit and get offered an export. Can you pls setup one using a campaign?

**Comment by tonphu** [comment]
From before the respec, after the respec, or both?

**Comment by ThyWoof** [comment]
Both.
