### ISSUE TITLE
Stuck in Gem Quest: The Mind of the Master

### ISSUE THREAD

**Issue by LordBandai** [SolastaMods/SolastaUnfinishedBusiness#4917]
Crash report after the cutscene in the chest room with the giant statues (before the elementals spawn). After finishing the fight I can't enter the next room and am basically stuck in this limbo.

Playerlog says it cannot load the dragon / person in the next room.

Wondering if this is a me issue or something that can potentially happen to everyone.

[Player.log](https://github.com/user-attachments/files/16919863/Player.log)

**Comment by ThyWoof** [comment]
Vanilla bug, safe to ignore.
