### ISSUE TITLE
Buggy AC after respeccing character

### ISSUE THREAD

**Issue by boatschl** [SolastaMods/SolastaUnfinishedBusiness#4920]
1. I downloaded the latest UMM and installed the latest UB (from Nexusmods). 
2. I booted the vanialla game, only activated the respec option and hit Save
3. I loaded up my save file and respecced all characters after a long rest. The save game immediately afterwards is attached.

--> The issue: AC is broken, e.g. on the Sorc it should be 13 + 4, but in the ingame UI shows 40 (the tooltipp is correct). Verifying in combat shows that none of my characters can be hit anymore.

[after respec.zip](https://github.com/user-attachments/files/16935672/after.respec.zip)

Please let me know if I you need any additional info. Thanks

**Comment by ThyWoof** [comment]
Thanks for save and details. Will check.

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/9112e7fa-e007-46aa-9928-8a7185533fea)
not sure how you got into this state but in your save hero is adding a bunch of health modifiers to AC. I RESPEC again on main end and was able to fix. I'm using v30 DEV so give it a try on v29. If same results wait for v30 release.
