### ISSUE TITLE
Power attack doesnt work with unarmed attacks

### ISSUE THREAD

**Issue by Master999999999** [SolastaMods/SolastaUnfinishedBusiness#4921]
Power attack active and monk attacks are not unaffected.

**Comment by ThyWoof** [comment]
Each game is unique. Imagine if I have to setup a hero/save for each reported issue? Please do better, share your save, screenshots, mod and game version, steps to repro.

**Comment by ThyWoof** [comment]
For example, if I had to choose which one to tackle first. This or https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/4920

**Comment by ThyWoof** [comment]
![image](https://github.com/user-attachments/assets/77ea47d2-cdee-4e60-89f7-6a7745fda6b4)
