### ISSUE TITLE
1.5.97.30 not working...

### ISSUE THREAD

**Issue by eviper007** [SolastaMods/SolastaUnfinishedBusiness#4938]
Updated to 1.5.97.30 using the built-in updater.  After restarting the game, the mod refuses to turn on.  Mod icon says it's turned off, Settings are disabled, and the red icon signifying the need to restart is always on regardless of how many times the game is restarted.

**Comment by kosocku** [comment]
Enderwiggin already has a fix put up to be reviewed by one of the other Devs before updating

**Comment by VanBurenPhilips** [comment]
For those who already updated to .30, what will our update process be?

(since we're unable to open UB settings - we can't get to the update or rollback buttons)
