### ISSUE TITLE
Aasimar Light Cantrip requires Universal Spell Focus

### ISSUE THREAD

**Issue by Thaladar** [SolastaMods/SolastaUnfinishedBusiness#4950]
Aasimar race gets Light Cantrip.  But with an Arcane or Divine Focus, there is an error to equip a Spell Focus.  Only with a Universal Spell Focus equipped can you cast Light.  Request that any focus (or at least Divine, given the background of the Aasimar race) meet the requirements to cast.

**Comment by ThyWoof** [comment]
will reuse light monk no focus on Aasimar instead.
