### ISSUE TITLE
Multiclass Ranger-Fighter has no Superiority Dice available in POI Import

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#4952]
Solasta 1.5.97
UB 1.5.97.31
No other mods

Imported a finished UB Crown of the Magister save into Palace of Ice and the game says my mutliclass Ranger-Fighter has no Superiority Dice available as if I had used all of them. If I select the option to take a short rest, Superiority Dice does not show up as a feature that will recover upon rest completion (It just says None).

Superiority Dice showed up as normal in POI when I selected a Fighter 1 from the character creator and levelled her up and when I selected a Ranger 1 and levelled her up into a multiclass Ranger-Fighter.

[POI_NoSuperiorityDiceMulticlass.zip](https://github.com/user-attachments/files/17093293/POI_NoSuperiorityDiceMulticlass.zip)

**Comment by ThyWoof** [comment]
RESPEC this hero. There were changes in superiority dice over the last months.
