### ISSUE TITLE
Respec AC Bug

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#4953]
Solasta 1.5.97
UB 1.5.97.31
No other mods

Same issue as #4920, AC jumped to a much higher number after completing RESPEC within game file. Looking at the Party Editor shows the same +1 Health issue that you found in the other player's file.

[RespecACBug.zip](https://github.com/user-attachments/files/17111050/RespecACBug.zip)

Thanks for all your work on the mod!

**Comment by ThyWoof** [comment]
Is this a before or after save?

**Comment by LuckyTortellini** [comment]
After Respec, did you want a before file and log as well?

**Comment by ThyWoof** [comment]
Yes

**Comment by LuckyTortellini** [comment]
Before files can be found at #4952

**Comment by Jeff-The-Geek** [comment]
Just bumping this, ran into same issue in .31 yesterday with a bunch of "+1 health". interestingly, every character I respecced has some form of +1 health buff to AC, one with a LOT, but the other two with  just a few (x2 and x3 respectively). 
[SolastaACIssue.zip](https://github.com/user-attachments/files/17137205/SolastaACIssue.zip)

**Comment by ThyWoof** [comment]
very strange we cannot repro at all. We added some additional logging, and will also have a pop up, whenever we identify these wrong modifiers on AC. This should allow us to find the source of the problem. Will share latest DEV build soon here, and counting on you to RESPEC, and hopefully get to the bug, and share logs.
