### ISSUE TITLE
Game stopped launching

### ISSUE THREAD

**Issue by Seruvv** [SolastaMods/SolastaUnfinishedBusiness#4954]
Solasta 1.5.97
UB 1.5.97.31
No other mods

I installed the mod as instructed. 
Started Solasta, selected the options in the mod that required restarting the game (level 20, multiclassing and something else). 

Now every time I click to start Solasta, I get this error and the application gets stuck on the loading screen.

[Player.log](https://github.com/user-attachments/files/17129413/Player.log)
<img width="448" alt="{4973BEF9-E9A4-441B-B266-6BF7E1989E1E}" src="https://github.com/user-attachments/assets/ac3dbc7a-ebf9-4a0e-94fd-4b77a4fb19b6">

**Comment by ThyWoof** [comment]
Mod on boot, tries to create a documents folder under the SolastaUnfinishedBusiness folder. Something on your end is preventing that. I would check if you have the game in a read only drive, as well as manually create the documents folder there. Let me know.

**Comment by ThyWoof** [comment]
any update?

**Comment by Seruvv** [comment]
Good evening!
Thank you for your reply. I solved the problem yesterday by deleting the
mod from the game folder and installing it again.

I would like to ask about one more problem, my friends have an error when
leveling up, when we start the Palace of ice add-on, and we start leveling
up characters, they get an error when multiclassing.

We are going to try it again tomorrow and I can send the error logs.

Translated with DeepL.com (free version)

чт, 26 сент. 2024 г. в 18:39, Paulo Monteiro ***@***.***>:
