### ISSUE TITLE
Multiplayer multiclass level Up Instability error

### ISSUE THREAD

**Issue by DreadfulGreyWolf** [SolastaMods/SolastaUnfinishedBusiness#4956]
Mod Manager 0.27.10
1.5.97.31
Couldnt find where to check the game version, but its from steam.
No other mods

Issue when leveling up a character in a multiplayer game with Multiclass option enabled.
Leveling up a character in a multiplayer game with the same host and character with Multiclass option disabled doesn't cause the issue.

We are testing in Palace of Ice DLC Campaign with level 1 Mephisto Tiefling Wizard. Right after i choose the spells for the lvl2, the game freezes with Instability error. On the background of the error stays the following screen![solasta_bug](https://github.com/user-attachments/assets/83e79748-2c33-46dc-8616-0e95e1030bb4)

We cant progress past this issue, since the level up screen freezes, hence there is no saved game. 

[Zara.zip](https://github.com/user-attachments/files/17155765/Zara.zip)
[Player.log](https://github.com/user-attachments/files/17155745/Player.log)

**Comment by ThyWoof** [comment]
Level up outside POI. Unfortunately, the level up there is full of vanilla bugs. If trying to import heroes from another save, simply import them, and do level up on location map.

Can you confirm this is the case?

**Comment by DreadfulGreyWolf** [comment]
Issue remains when trying to level up pregen characters(rogue, fighter) in multiplayer Crown Of the Magisters Campaign. 
It even remains, after everyone except the host leave the game, making the game an offline game for the host.

**Comment by ThyWoof** [comment]
Can you open a new POI campaign, using heroes you create, to confirm it indeed breaks?

vanilla heroes should not be used in POI as they are lacking some features as well.

**Comment by DreadfulGreyWolf** [comment]
Custom characters in POI campaign is what the original issue is about.
We tested Crown of the Magister campaign based on your question regarding save import to POI,

**Comment by ThyWoof** [comment]
Pressed comment too soon? Ok to assume it indeed works with custom heroes, and if you avoid the new level up introduced on POI, and use location level up instead, all works as it should?

**Comment by DreadfulGreyWolf** [comment]
No. It doesnt work.
Leveling in multiplayer in Crown of the Magister Campaign causes the same issue as leveling in Palace of Ice Campaign. Both with custom heroes and Multiclass enabled. 

Host was able to level up heroes in POI pre-campaign level up section, after all other players left.
But location leveling in POI with the same above conditions after players reconnected didnt work either. 

Just for general info:
We bypassed the issue by having host level up all characters alone in POI pre-campaign level up section, starting the campaign, saving it. After that we all disabled multiclass and were able to continue. Location leveling with multiclass disabled worked fine. We are now all be leveling in the last class host leveled up before disabling multiclass. 

Its hell of a workaround and is pain in the ass.

**Comment by DreadfulGreyWolf** [comment]
Will you reopen the issue or shall i open a new one with the reference to this #4956?

**Comment by ThyWoof** [comment]
There isn’t much I can do to help here. Ensure you all have the same settings. There is a team in QA that cannot repro this.

**Comment by DreadfulGreyWolf** [comment]
Settings are copied from the host file. 
Does Mod manager version matter? Should all players have the same Mod manager version?
What version of the mod manager is the last supported?

**Comment by ThyWoof** [comment]
Nope. Here is a re-confirmation from QA crew:

![image](https://github.com/user-attachments/assets/567c9a72-e415-4425-8002-9d90afedb05f)

**Comment by DreadfulGreyWolf** [comment]
I see. 
Could the issue be caused due to all players not having the same DLC? 
E.g. i dont own POI and create a Tiefling character in the campaign, which is hosted by a player with the DLC.
