### ISSUE TITLE
Find Familiar spell

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#4957]
Dismissing my familiar from the Find Familiar spell seems to consistently cause an instability warning. Idk if this can just be ignored. I haven't noticed any adverse effects afterwards or anything. I don't wanna risk something breaking in the campaign later down the road. Just reporting this here because of the warning.
![image](https://github.com/user-attachments/assets/f85b48b2-ef37-4154-8c86-ea5ef28a7b19)
[Test.zip](https://github.com/user-attachments/files/17155855/Test.zip)
The zip folder contains the log and save file.

**Comment by ThyWoof** [comment]
It’s the mod trying to refresh the action panel on a dead or dying character. Won’t cause any issues on your save. To be fixed on next release.

**Comment by lovemachine44** [comment]
I understand, thank you.
