### ISSUE TITLE
oath of thunder paladin interactions: mjolnir

### ISSUE THREAD

**Issue by BlazeGamma** [SolastaMods/SolastaUnfinishedBusiness#4958]
I was trying out the oath of thunder paladin subclass because it sounded like a fun Thor spinoff, and I found an interaction with my other abilities that I can't really figure out if its intentional or not.
Mjolnir has a weapon requirement of war hammer type weapons that reads: "You have disadvantage to attacks with any  other weapon type different from war hammers" 
which makes sense, because thor, mjolnir, hammer, etc... however as per the text reads this should only apply to weapon attacks, and also I still have a war hammer equipped anyway, but the interaction seems to also be affecting some spells/abilities that cause damage to enemies like the paladn's own channel divinity: divine bolt, as well as the sacred flame spell he has. Here's some screenshots that show the disadvantage modifier showing up on the target preview on the left side.

![image_2024-09-27_113128085](https://github.com/user-attachments/assets/5e233398-534f-4457-ac31-b63daf335bb1)
![image](https://github.com/user-attachments/assets/498b3ca7-cc77-450a-803c-821a9141cf7f)

**Comment by ThyWoof** [comment]
Please share your save to simplify debug, fix, qa

**Comment by BlazeGamma** [comment]
here's a copy of the save file, not sure if you only require this or something else as well.
[solasta save fle.zip](https://github.com/user-attachments/files/17167324/solasta.save.fle.zip)

**Comment by ThyWoof** [comment]
It looks like Odin messed up. Will check.
