### ISSUE TITLE
Wild Magic Sorcerer "Bend Luck" gives bonuses to opponent's rolls

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4959]
Unless the little combat stat box is giving out errors, it seems that the Wild Magic Sorcerer's ability "Bend Luck", which should give a bonus to friendly rolls and a penalty to opponent rolls, is giving a bonus to opponent rolls.

I've attached two saved files, one the "Before Bend Luck" save where my cleric is about to hit a big bug with his lightning bolt wand (so before the bug can roll the save for the lightning bolt), and the "After Bend Luck" save where you can see the stat box saying that the Wild Magic Sorcerer gave a BONUS to the bug's save against the lightning bolt. 
[Before Bend Luck.sav.zip](https://github.com/user-attachments/files/17171393/Before.Bend.Luck.sav.zip)

[After Bend Luck.sav.zip](https://github.com/user-attachments/files/17171395/After.Bend.Luck.sav.zip)

**Comment by ThyWoof** [comment]
Already fixed in DEV branch, thanks for reporting
