### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by skalra631** [SolastaMods/SolastaUnfinishedBusiness#4961]
Solasta 1.5.97
UB 1.5.97.31
No other mods

Hi since installing UB I have an issue where sometimes the X menu (attack, cast spell etc) and when I have dialog options the controller doesn't seem to pick up the squares. Eg if I press x, attack is highlighted, if I tap right it used to go to the disengage option. Now I will have to tap a few times to get it to move, sometimes it doesn't even highlight the box. 

Mouse works fine but I'd prefer to use the controller

**Comment by ThyWoof** [comment]
It’s a known issue. Won’t be fixed as mod was written without a controller in mind.
