### ISSUE TITLE
Artificer Minor/Major Elemental Infusions

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#4962]
I don't normally use either infusion, so it may just be the descriptive text, but the Minor Elemental Infusion adds an additional 1d6 of the chosen element type, and the Major only adds 1d4 of the chosen element type?  Shouldn't that be the other way around?  You can't stack Infusions on a weapon, so it's not like the 2 lots of extra damage can stack.

I don't have a save file, as I was just creating characters for a Custom campaign and noticed the text seems to be backwards.

**Comment by ThyWoof** [comment]
Minor is once per turn. Major has no restrictions reason why.
