### ISSUE TITLE
New problem with Armor of Agathys

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4964]
Hi guys, sorry to reopen this topic, but I started playing with my warlock in a new campaign and noticed a malfunction in the Armor of Agathys spell.

The AoA is sometimes causing 0 damage. Other times the spell works as it should. Playing a little more I noticed a certain pattern in the bug.

I'm not a programmer, but I'll tell you what I think is happening:

1 enemy hits the attack
2 enemy damage is calculated
3 AoA causes damage if there are still temporary hit points after the enemy's damage, otherwise it causes 0 damage

So I had 5 THP and suffered 3 damage, the AoA worked, but the next attack the enemy hits me with 4 damage, the enemy won't suffer damage from the AoA.

I believe the spell works by causing cold damage before calculating the damage suffered by the warlock.

1 enemy hits the attack
2 AoA deals damage if there are still temporary hit points
3 enemy damage is calculated

Is it possible to solve this?

**Comment by kosocku** [comment]
This was always my understanding of Armor of Agathys as well: As long as you have temp HP **when** you get hit (not after you get hit), the creature attacking you takes the cold damage.  The exact wording on the spell is "If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage"
