### ISSUE TITLE
Exploration with find familiar and dancing lights

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4966]
There are situations that I believe are a little strange.

When I send the dancing lights spell forward to an area with fog of war, the lights float in a "dark sea" and even stranger is the fact that enemies always start the battle when dancing lights approach, even if they can't see it (do the lights make noise when they dance? lol).

Is it possible to change the dancing lights spell to reveal fog of war and not start battles automatically?

For the find familiar spell, there is nothing wrong with it, but I think it would be really cool if the familiar could have the chance to find traps or secret doors with its perception.

**Comment by ThyWoof** [comment]
after some research, the amount of work required doesn't justify the benefits.
