### ISSUE TITLE
Desynchronization issue with Dissonant Whispers in multiplayer (6 players)

### ISSUE THREAD

**Issue by DannixStarSl** [SolastaMods/SolastaUnfinishedBusiness#4969]
When a Bard casts Dissonant Whispers in a 6-player multiplayer game, the Host sees the enemy fleeing, but other players cannot see the enemy’s movement, causing desynchronization.

**Comment by ThyWoof** [comment]
Thanks for reporting but nothing I can do if you don’t properly reports it. Game and mod versions, saves before and after, logs right after. I got a deal with Gandalf. He doesn’t develop, I don’t do magic 😝

**Comment by DannixStarSl** [comment]
Game Version:1.5.97
Mod Version:1.5.97.32

sorry I didn't provide the information clearly

**Comment by ThyWoof** [comment]
You need to wait for the upload to finish after dragging files on here... Both links above take me nowhere.

**Comment by DannixStarSl** [comment]
Finished upload.
Sorry I haven't used the issue reporting feature before, so I'm not very familiar with these.

**Comment by Arcanis2** [comment]
> Thanks for reporting but nothing I can do if you don’t properly reports it. Game and mod versions, saves before and after, logs right after. I got a deal with Gandalf. He doesn’t develop, I don’t do magic 😝

I disagree. Gandalf may not develop, but for me, everything Thywoof does, is magic. Or a miracle if you prefer.

**Comment by ThyWoof** [comment]
This spell uses the enemy brain to determine the movement location based on fear behavior. If I remember correctly only the host runs enemies combat brains as this is a non deterministic process. I need to learn how to pass brain decisions to other clients. Might take a bit longer to fix. Meanwhile, don’t use it as confirmed it breaks MP.
