### ISSUE TITLE
Unprepared spells after receiving items from another character

### ISSUE THREAD

**Issue by WowieCowie** [SolastaMods/SolastaUnfinishedBusiness#4970]
My cleric's (Cleric 7 / Fighter 2) prepared spells goes from 11/11 to 3/11 after receiving items from another character that were looted from a container. Giving them items that were crafted don't appear to affect their spells, but both recently and previously looted items do.

Solasta Version: 1.5.97
UB Version: 1.5.97.32

[BeforeUnpreparedSpells.zip](https://github.com/user-attachments/files/17220035/BeforeUnpreparedSpells.zip)

[AfterUnpreparedSpells.zip](https://github.com/user-attachments/files/17220034/AfterUnpreparedSpells.zip)

**Comment by seunAdeks** [comment]
I second this message in that after every encounter some of the prepared spells go away.

**Comment by Krypt-Onyx** [comment]
[Spells gone.zip](https://github.com/user-attachments/files/17257988/Spells.gone.zip)
Solasta Version: 1.5.97
UB Version: 1.5.97.32
Same issue. Only really noticed in the last couple of days after our Battle Cleric (Imai Orimaynot) got Level 2 Spells.
We found this thread and gathered 3 Saves in the Zip file.
Between #2 and #3, Sparkles the Battle Wizard gave a Ring to the Cleric and the Spells disappeared.
