### ISSUE TITLE
Solasta UB instability and crash

### ISSUE THREAD

**Issue by Aldarion88** [SolastaMods/SolastaUnfinishedBusiness#4971]
Running the latest Solasta 
UB 1.5.97.32
UMM 0.27.10.0

Game loaded to Main menu, game loaded the latest save.
After Respecing character in adventure Temple of Evil.
Reroll went withou any problems. Picking up items from ground. Saving.

But if i want to load the game it get an error.
[Player-prev.log](https://github.com/user-attachments/files/17230816/Player-prev.log)

Please assist.

Thank you.
Aldo

**Comment by ThyWoof** [comment]
I cannot be of any assistance without a save.

**Comment by ThyWoof** [comment]
Chances are these saves are broken. Please ensure you keep the save before RESPEC. I remove the previous hero from the game but it looks like I’m missing a collection or 2.

**Comment by jmatz33** [comment]
Ahh -- so you want the Previous Save (ie: before I respec'd).  Sorry -- I've attached that as well.

I *only* respec'd the bard in this case (to a College of Lore bard subclass).  If you want the breakdown of what choices I picked I can *probably* redo it the same (minus stats).

[Day 2.zip](https://github.com/user-attachments/files/17264337/Day.2.zip)

**Comment by ThyWoof** [comment]
I rolled back the changes that were causing this as won’t have time over the next weeks. New release with fix comes tmrw.
