### ISSUE TITLE
About grapple

### ISSUE THREAD

**Issue by Arcanis2** [SolastaMods/SolastaUnfinishedBusiness#4972]
I spent an entire afternoon testing the possibilities with the grapple. 

You guys are amazing! I just wanted to thank you for the work, this new option is really fun.

I noticed that you made the grabbed enemy kind of teleport to the hero's last position. Very clever.

My only regret was when I tried the "cheese grater" combo. 
But I think that asking to add a condition to the spike growth spell to cause damage when a creature teleports to it could be complicated.

Anyway thank you very much.

**Comment by ThyWoof** [comment]
Looking into this but will require more time to think about a good solution. Won’t mod this week but asked others in the team to continue from where I’ve stopped.

**Comment by Arcanis2** [comment]
> Looking into this but will require more time to think about a good solution. Won’t mod this week but asked others in the team to continue from where I’ve stopped.

No problem, you and your team are fantastic anyway. Hope all is well out there. Stay in the light!

**Comment by ThyWoof** [comment]
Implemented.
