### ISSUE TITLE
Can you add the option to auto-save after every round?

### ISSUE THREAD

**Issue by jmatz33** [SolastaMods/SolastaUnfinishedBusiness#4974]
Playing multiplayer (3 peeps, 4 characters) we often get desync'd for some reason.  It essentially hangs the game and we have to reload the latest save (which is usually the start of combat).  The problem is if we are in round 5 or 6 when this happens, well, it's not ideal.

I don't know why it soft locks, but between the 3 of us, 2 of us are usually "up to date" on whose turn it is while one person is behind and that's when it soft locks.  We've waited about 5 minutes before killing/restarting.

We mostly have gotten into the habit of quick-saving when it's someone's turn (can't do it on an enemy's turn) but we also will forget.  So having an option of it auto-saving at the start would be really convenient.

I can also send logs/etc when we get to this desync/soft lock.  I just don't know if the logs would be helpful.

Awesome Mod, of course!

**Comment by ThyWoof** [comment]
Very hard to debug MP reason why I have a QA team that does it on a weekly basis. Over the last weeks the only report is about the chromatic orb spell which I’m looking at.

ensure everybody check their game files, everybody using same mod version and settings file. Also, one with better computer must host.

Happy gaming.

**Comment by ThyWoof** [comment]
Open a ticket next time it happens. Proper way to fetch log is everybody closes game as soon as desync happens, fetch log files before starting game again. Have the save with logs helps a lot.

**Comment by ThyWoof** [comment]
I’m also aware most of these issues are caused by some non-reentrant code UB still might have. Problem is find it in a mod this big, that started way before MP was a thing in vanilla. Main reason why logs matter a lot.

**Comment by jmatz33** [comment]
OK - will do.  Just to double check -- the log file in this case is still "Player.log" in the Solasta dir (since I have no logs in the Solasta/Logs dir).

Also note, when we reload the save, it doesn't get "stuck" again (most likely because the computer AI picks some different actions).  If I could figure out how to get it stuck every time I'd do that, but randomness rears its ugly head here.
