### ISSUE TITLE
story npc spell issue causing "instability"

### ISSUE THREAD

**Issue by BlazeGamma** [SolastaMods/SolastaUnfinishedBusiness#4976]
So I recently got the palace of ice dlc and started that, got a bit into the story etc and soa  fight starts and now I have 6 party members, my own 4 and then 2 tacked-on npcs that are story important... so I tried casting a spell with the cleric dwarf one and all of a sudden I get this message saying "Solasta has detected an instability. Please ask every player to close the game.." and so forth, screenshot below. Thought that was weird since this isn't a multiplayer campaign, I'm playing solo and just happen to have 2 units in my party that just aren't my own. I reload the autosave at the fight start and even a save just before getting into the actual fight but every single time I try to cast any spell with either of the two npcs the message pops up.

howeverrrrrr
I messed around with it for a bit, being the asshole I am... and noticed that:
1: powers still work. the rogue has powers, shadow dodge, which to me appears to be working normally
2: if I UPCAST a spell that can do so to a higher spell level, like bless or color spray, then it will work, just not if I cast it normally at its base level.
3: if you notice one spell slot of the third level on the cleric in the screenshot missing, that was from a counterspell she cast, which seemed to also work normally from my perspective.

heres the screenshot of what it says, also adding in the log file it mentions, and a save on that npc rogue's turn with the cleric getting a turn right after an enemy turn. If needing more into, let me know.

![image_2024-10-06_011355185](https://github.com/user-attachments/assets/8abde7a9-490c-4c0a-b697-dd11085f54d8)
[Player.log](https://github.com/user-attachments/files/17268267/Player.log)
[ice 4.zip](https://github.com/user-attachments/files/17268322/ice.4.zip)

**Comment by ThyWoof** [comment]
Already fixed in dev. New release comes out tmrw

**Comment by BlazeGamma** [comment]
very nice, thanks my dude.
