### ISSUE TITLE
AOE Spell Damage

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#4980]
I don't remember if this is a vanilla issue or not, and I don't think it happens all the time, but sometimes the damage roll for an aoe damaging spell like burning hands, does a different damage roll per enemy hit.
![image](https://github.com/user-attachments/assets/cd9de147-44af-40b6-8666-853cd68f4c01)
In this case the eagle (now dead) was hurt for 2+1+2. Where as the bear was hurt for 2+4+3. My understanding of how the aoe spells work is that you roll the damage once and all enemies hit take the same amount of damage. 

I don't think this is a new issue but I couldn't find another issue topic with this problem. I'll attach a save file of course but it's after the attack was made.
[Test.zip](https://github.com/user-attachments/files/17275329/Test.zip)

**Comment by lovemachine44** [comment]
I just attempted it again on a new encounter and all the damage rolls were the same for 3 different enemies. So ya, I'm not sure what triggers the damage desync.

**Comment by ThyWoof** [comment]
Beyond our control. Game doesn’t have anything that touches that and indeed a simple restart can fix stuff.

**Comment by lovemachine44** [comment]
Sounds like a base game problem, ok thanks!
