### ISSUE TITLE
Green-flame blade scaled dmg bug

### ISSUE THREAD

**Issue by Geriboys** [SolastaMods/SolastaUnfinishedBusiness#4982]
Solasta: 1.5.97
UB: 1.5.7.33 (could be present since .32)
Mod: The Red Crow (Six-man) campaign

After reaching level 17 with a character, Green-Flame Blade reaches its final scaling damage. However after level 17 the damage on the initial damage (3d8) is fine, but the secondary damage to the second target (3d8+casting modifier) is bugged and only does the casting modifier damage without the 3d8 additional damage. The problem is not present on lower levels (atleast for the best of my knowledge).
The issue is present in both singleplayer and multiplayer as well, and also with 2 different characters as well.
I remember that this issue was not present around version .28-.29, not sure if this info helps at all.
[damage report.zip](https://github.com/user-attachments/files/17284410/damage.report.zip)
![1](https://github.com/user-attachments/assets/6ba62d99-83ea-49ce-9636-bebb1441c842)
![2](https://github.com/user-attachments/assets/a5d20517-594e-4edd-b9e9-0fab60773c2b)
![3](https://github.com/user-attachments/assets/f9a7b703-d837-4073-8abd-714bdaaac3b4)

**Comment by ThyWoof** [comment]
In fact it broke lower levels too. Need to add a dice advancement here https://github.com/SolastaMods/SolastaUnfinishedBusiness/blob/cf3d908cb765ac1cc7008d58d67c0e93d4e00945/SolastaUnfinishedBusiness/Spells/SpellBuildersCantrips.cs#L1067 as the dice compute method multiply by zero.
