### ISSUE TITLE
some crash and druid's "circle of moon" lagging, help plz

### ISSUE THREAD

**Issue by Meowkuss** [SolastaMods/SolastaUnfinishedBusiness#4983]
When appears:
Some "desync" or lag when you shapeshift to any of animals. Crash appears randomly.
Appears only in multiplayer. When this happens any dice rolls not showing.
Problem only with druid.
Also bug with petals when you casting shapeshift they bugged.
Desync appears because of ring that give you fall damage immunity. idk if it appears with other rings or other equipment.
About crash i have no info.

Save files: https://drive.google.com/file/d/1-6f40YO15-Queaoyp40u3qrM-E7wdhSf/view?usp=sharing
Player log of my friend(other): https://drive.google.com/file/d/13YSt5R5QlHI9d3unXNDJOG4jKp-mADak/view?usp=sharing

My Player.log:

Mono path[0] = 'C:/Games/Solasta Crown of the Magister/Solasta_Data/Managed'
Mono config path = 'C:/Games/Solasta Crown of the Magister/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.37f1 (019e31cfdb15)
[Subsystems] Discovering subsystems at path C:/Games/Solasta Crown of the Magister/Solasta_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   
    VRAM:     4004 MB
    Driver:   31.0.15.5244
Begin MonoManager ReloadAssembly

[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.24.0.0.
[Manager] OS: Microsoft Windows NT 10.0.19045.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] Mods path: C:\Games\Solasta Crown of the Magister\Mods.
Fallback handler could not load library C:/Games/Solasta Crown of the Magister/Solasta_Data/Mono/data-000001E8D8364B40.dll
Fallback handler could not load library C:/Games/Solasta Crown of the Magister/Solasta_Data/Mono/data-000001E8DB340040.dll
[Manager] Injection successful.
- Completed reload, in  7.857 seconds
<RI> Initializing input.

New input system (experimental) initialized
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.991600 ms
WwiseUnity: Wwise(R) SDK Version 2021.1.4 Build 7707. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Setting Plugin DLL path to: C:/Games/Solasta Crown of the Magister/Solasta_Data\Plugins\x86_64 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Sound engine initialized successfully. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 16.428800 ms (FindLiveObjects: 0.339900 ms CreateObjectMapping: 0.186300 ms MarkObjects: 15.849600 ms  DeleteObjects: 0.052500 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 15.365200 ms (FindLiveObjects: 0.568600 ms CreateObjectMapping: 0.244200 ms MarkObjects: 14.529200 ms  DeleteObjects: 0.022300 ms)

[Manager] Parsing mods.
[Manager] Reading file 'C:\Games\Solasta Crown of the Magister\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.5.97.33'. Loading.
[SolastaUnfinishedBusiness] Unofficial translations support disabled.
[SolastaUnfinishedBusiness] Active.
[SolastaUnfinishedBusiness] Loading time 3,24 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.

[Manager] Spawning.
[Manager] Checking updates.
Init 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

-Mod.IO: Mod.IO helper initialized 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

-Gaming-Galaxy: Failed to sign in for reason FAILURE_REASON_GALAXY_SERVICE_NOT_AVAILABLE 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[SolastaUnfinishedBusiness] 6061 ru translation terms loaded of 6063 provided.
[SolastaUnfinishedBusiness] 0 ru translation fixes loaded.
[SolastaUnfinishedBusiness] DELETE THESE TERMS:
[SolastaUnfinishedBusiness] Tooltip/&TargetMustNotBeSurprised must be deleted from ru translation assets
[SolastaUnfinishedBusiness] Tooltip/&TargetMustUnderstandYou must be deleted from ru translation assets
[SolastaUnfinishedBusiness] enabled in 00:00:31.7137456.
Unexpected timestamp values detected. This can occur in H.264 videos not encoded with the baseline profile. Timestamps will be skewed to correct the playback for C:/Games/Solasta Crown of the Magister/Solasta_Data/StreamingAssets/BackgroundMovie.MP4 
(Filename:  Line: 0)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 3 Unused Serialized files (Serialized files now loaded: 17)

Unloading 82932 unused Assets to reduce memory usage. Loaded Objects now: 304573.
Total: 779.287100 ms (FindLiveObjects: 13.426100 ms CreateObjectMapping: 9.007100 ms MarkObjects: 735.454300 ms  DeleteObjects: 21.399200 ms)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 138)

Unloading 3627 unused Assets to reduce memory usage. Loaded Objects now: 414944.
Total: 809.122700 ms (FindLiveObjects: 16.549300 ms CreateObjectMapping: 6.339600 ms MarkObjects: 785.139500 ms  DeleteObjects: 1.093800 ms)

Removed 58 invalid renderers from the culling data. Please regenerate culling with new meshes. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Couldn't find character with monsterDefinition Master_Dackin. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 3 Unused Serialized files (Serialized files now loaded: 45)

Unloading 95463 unused Assets to reduce memory usage. Loaded Objects now: 337348.
Total: 912.060000 ms (FindLiveObjects: 18.368100 ms CreateObjectMapping: 12.279000 ms MarkObjects: 849.483100 ms  DeleteObjects: 31.929400 ms)

Missing translation for key=Feature/&Emptystring 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Missing translation for key=Feature/&Emptystring, in object LocationName in parent NameGroup 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 138)

Unloading 2822 unused Assets to reduce memory usage. Loaded Objects now: 346667.
Total: 923.918000 ms (FindLiveObjects: 14.324300 ms CreateObjectMapping: 6.107800 ms MarkObjects: 901.173400 ms  DeleteObjects: 2.312100 ms)

Reaction 1 was not found in client simulation state. This is probably due to a desync, or mashing the button. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 45)

Unloading 36100 unused Assets to reduce memory usage. Loaded Objects now: 342861.
Total: 912.773700 ms (FindLiveObjects: 14.154100 ms CreateObjectMapping: 9.776900 ms MarkObjects: 879.928800 ms  DeleteObjects: 8.913300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 34)

Unloading 9 unused Assets to reduce memory usage. Loaded Objects now: 342334.
Total: 881.634600 ms (FindLiveObjects: 14.567800 ms CreateObjectMapping: 7.448500 ms MarkObjects: 859.190400 ms  DeleteObjects: 0.427500 ms)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 40)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 342817.
Total: 832.532700 ms (FindLiveObjects: 12.508100 ms CreateObjectMapping: 5.618300 ms MarkObjects: 814.097600 ms  DeleteObjects: 0.308300 ms)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 138)

Unloading 468 unused Assets to reduce memory usage. Loaded Objects now: 349966.
Total: 832.611700 ms (FindLiveObjects: 14.415200 ms CreateObjectMapping: 6.127000 ms MarkObjects: 811.666300 ms  DeleteObjects: 0.402800 ms)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Look rotation viewing vector is zero 
(Filename:  Line: 85)

Look rotation viewing vector is zero 
(Filename:  Line: 85)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackImpact on character WildShapeDireBear[9686]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event HitAnimationEnd on character Tiger_Drake[9631]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackAnimationEnd on character WildShapeDireBear[9686]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 44)

Unloading 40452 unused Assets to reduce memory usage. Loaded Objects now: 348173.
Total: 862.707000 ms (FindLiveObjects: 16.945900 ms CreateObjectMapping: 7.963000 ms MarkObjects: 827.691000 ms  DeleteObjects: 10.106700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 33)

Unloading 9 unused Assets to reduce memory usage. Loaded Objects now: 347656.
Total: 1023.033300 ms (FindLiveObjects: 34.256100 ms CreateObjectMapping: 9.552400 ms MarkObjects: 978.816500 ms  DeleteObjects: 0.407900 ms)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Operation GetGameList (217) not allowed on current server (GameServer) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 1 Unused Serialized files (Serialized files now loaded: 39)

Unloading 58 unused Assets to reduce memory usage. Loaded Objects now: 348235.
Total: 844.850200 ms (FindLiveObjects: 13.119600 ms CreateObjectMapping: 5.896600 ms MarkObjects: 825.415800 ms  DeleteObjects: 0.417800 ms)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WwiseUnity: There are multiple AkWwiseInitializationSettings objects instantiated; only one will be used. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 2 Unused Serialized files (Serialized files now loaded: 137)

Unloading 468 unused Assets to reduce memory usage. Loaded Objects now: 355389.
Total: 864.995500 ms (FindLiveObjects: 30.775900 ms CreateObjectMapping: 8.493800 ms MarkObjects: 825.294300 ms  DeleteObjects: 0.431200 ms)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackImpact on character WildShapeDireBear[9657]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackAnimationEnd on character WildShapeDireBear[9657]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event MonsterWeaponSwapped on character WildShapeDireBear[9657]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackImpact on character WildShapeDireBear[9657]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event HitAnimationEnd on character Tiger_Drake[9634]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WaitForEvent() aborted. Waiting too long for event AttackAnimationEnd on character WildShapeDireBear[9657]. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Couldn't recover character used in action from player c4ed77f4-8c05-415a-ade5-6f5af4e98afe in player 22771cdc-c752-4563-a01b-719eb7514c5d. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at TA.AI.Activities.Attack+<ExecuteImpl>d__4.MoveNext () [0x00266] in <e6f6f336136b4c2991fe6af09dc40bd9>:0 
  at TA.Coroutine.Run () [0x00019] in <e6f6f336136b4c2991fe6af09dc40bd9>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
TA.Coroutine:Run()
AiLocationManager:UpdateImpl()
AiLocationManager:FixedUpdate()
 
(Filename: <e6f6f336136b4c2991fe6af09dc40bd9> Line: 0)

Unloading 1 Unused Serialized files (Serialized files now loaded: 44)

Unloading 38097 unused Assets to reduce memory usage. Loaded Objects now: 349804.
Total: 906.211600 ms (FindLiveObjects: 16.466200 ms CreateObjectMapping: 6.977200 ms MarkObjects: 872.405400 ms  DeleteObjects: 10.362300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 33)

Unloading 9 unused Assets to reduce memory usage. Loaded Objects now: 349288.
Total: 864.422900 ms (FindLiveObjects: 13.911400 ms CreateObjectMapping: 6.480900 ms MarkObjects: 843.506400 ms  DeleteObjects: 0.523800 ms)

Setting up 3 worker threads for Enlighten.
  Thread -> id: 2e3c -> priority: 1 
  Thread -> id: 3fcc -> priority: 1 
  Thread -> id: 3fb8 -> priority: 1 
[Manager] Destroying when exit.
GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by ThyWoof** [comment]
Internet etiquette 101: never ever paste the contents of any text file on a post. Please attach them. Doing so completely break anyone using a mobile device to get any sense of it. Which is currently the case. I suggest you close this ticket and open a new one with a proper log file and save file attached. You need to zip save files before attaching them.

I simply cannot read above on a mobile device. Thanks.
