### ISSUE TITLE
character creation instability on cleric-maraike-nature

### ISSUE THREAD

**Issue by BlazeGamma** [SolastaMods/SolastaUnfinishedBusiness#4984]
so I was messing around with character creator, where I'm sure most of us actually spend our time playing the game..... right?

so I was looking over the nature cleric and I swapped back to read another domain, then went back to nature and that caused the instability message to pop up. even selecting nature, going forward to choose a background, and then going back to deity/domain selection will cause the message to appear, and then it will leave the deity choice part of the screen blank. this will cause the next and previous buttons on the lower right to stop working. cancel on the lower left still works.

![image_2024-10-08_191642054](https://github.com/user-attachments/assets/f6f2427d-5978-4787-9430-c35b629bfe85)

this is the part that goes 'blank' on going back to deity from background selection.
![image_2024-10-08_192931187](https://github.com/user-attachments/assets/cbbf0a4b-2845-46f4-93c8-255bd03ebe7b)
[Player.log](https://github.com/user-attachments/files/17300129/Player.log)

**Comment by ThyWoof** [comment]
Don’t go back and forth on level up UI. This has never been stable in vanilla and we do our best there. I won’t fix vanilla in this scenario. As far as you know what you need, keep moving ahead.
