### ISSUE TITLE
Multiplayer game with 6 characters allows host to select only 2

### ISSUE THREAD

**Issue by levyavi** [SolastaMods/SolastaUnfinishedBusiness#4985]
Multiplayer game with 6 characters allows host to select only 2. The guest can select 3.
Mod version - 1.5.97.33
Game version - 1.5.97

You can see in the screenshot the MP screen. The host can select 2 chars. The 3rd char is reserved.

Since it is when creating the game no saves are available.

![Screenshot 2024-10-09 23 01 20](https://github.com/user-attachments/assets/a7901c14-fdbd-4fba-911b-b43a264941cc)

![Screenshot 2024-10-09 23 00 53](https://github.com/user-attachments/assets/e0164563-10cf-461e-81ae-e2bb0846f4ba)

**Comment by ThyWoof** [comment]
I’ll try to fix this once back home but cannot promise a fix as very hard to debug MP. As soon as I stop on a breakpoint the session desyncs

**Comment by levyavi** [comment]
Thanks!
I will try it.

**Comment by levyavi** [comment]
If there is a workaround, maybe just adding a comment next to "Override Party Size" bar.
Saying that for 5-6 multiplayer you should start a save in Single Player.

**Comment by ThyWoof** [comment]
![{CFC4EAD6-E4BA-4533-B6E8-F48CADC3FCEE}](https://github.com/user-attachments/assets/acd17096-966a-40e2-ab23-b2c923274829)
party of 6

![{D8D51DCF-2D2F-45DA-BE7C-290901020AFC}](https://github.com/user-attachments/assets/ba280fba-40a0-49eb-b5b7-e56a8c3f75e0)
party of 5

![{B847A59D-4898-415E-A3E9-D00E397E9BE0}](https://github.com/user-attachments/assets/2f9adfb4-4538-496a-acd1-d2c5ef698cd8)
party of 4

![{7BC46108-ED9E-4029-95BE-E139D54D3BFF}](https://github.com/user-attachments/assets/4ff50f66-58f1-4e6e-8f20-d6ebffe7790b)
party of 3

![{89026AB8-730F-4828-9FD0-CD9C011C85BC}](https://github.com/user-attachments/assets/1091ceef-4414-4aee-ae83-bee639d237b9)
party of 2

![{D14B1006-2D87-4818-A788-1B9D997E2445}](https://github.com/user-attachments/assets/1f455450-3817-44df-9616-982827e15456)
party of 1

seems to be fixed.
