### ISSUE TITLE
Ready Attack Stalling

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#4986]
In the past I realize there have been situations where the AI would stall for a bit and then resume as normal. 

For the combat I'm currently in, if I ready an attack for more than 1 character then the AI stalls indefinitely. I tested this out, to make sure it wasn't just taking a long time and would then resume, by giving it about 30 mins while I went to go do something else.

Is there a workaround for this (other than just not readying an attack on more than one character)? It could be something more specific but I'm not sure. If this isn't a known issue and there is no true workaround, I can attach a save file.

**Comment by ThyWoof** [comment]
Is this something you could try to reproduce on a save without the mod installed? We don’t touch AI at this level in the mod. Max we do is create new brains on very specific spell scenarios.

**Comment by lovemachine44** [comment]
Sure I can try to reproduce it w/out the mod. Question first though: will not having the mod installed mess up any premade characters that were made w/ the mod?

**Comment by lovemachine44** [comment]
Further update. The issue is not necessarily with multiple people readying an attack for one enemy. The issue is the readied attack triggering from more than one character for a single enemy, while they are in the same spot.
Ex. If the enemy triggers one readied attack then moves forward 1 space to trigger another, there is no issue. Only stalls if triggered from the same space.

It's sounding more like this is something related to a base game engine issue.

**Comment by ThyWoof** [comment]
@EnderWiggin , you have more experience with ready attacks. Would our extensions to allow/force cantrips be part of the problem?

**Comment by kosocku** [comment]
I've had numerous combats where multiple PCs have readied attacks and hit the same target with all of them without the target moving.  I'm only using .32 (I haven't played in a week(ish), but I've never had it stall for more than 10-15 seconds after the first readied attack.  As a matter of fact, the most I get stalls currently is when I quicken a spell and then attack with a cantrip (usually Eldritch Blast, because I almost always multi-class my Sorcerer with a few levels of Warlock for the Sorcery Point burn)

**Comment by lovemachine44** [comment]
That's amount of time is more typical for me too. This is definitely an outlier situation.

**Comment by ThyWoof** [comment]
I was able to get a save with the soft lock after first ally ready an attack.

**Comment by ThyWoof** [comment]
[ReadyActionSoftLock.zip](https://github.com/user-attachments/files/17352704/ReadyActionSoftLock.zip)

**Comment by ThyWoof** [comment]
![{2017A93E-4CB2-4A5B-9989-247E08305E5D}](https://github.com/user-attachments/assets/6ef1ad32-4861-482e-8ff1-ea98d9c49caa)
fixed
