### ISSUE TITLE
Circle of Wildfire (Druid) Enhanced Bond bug

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#4987]
Enhanced Bond is currently calculating the bonus damage incorrectly (2d8 instead of 1d8) for Conjure Bonfire.  It is also (at least as far as conjure bonfire is concerned) incorrectly applying even on a successful save. 

In addition, the damage applies to all three rolls from scorching ray, but that might be a limitation of the engine to differentiate a single roll.  There, at least, it's limited to a single d8 each time, which tells me it may be amending each die in the roll instead of applying once per spell.

**Comment by DocEast** [comment]
Save file and character file attached.  Version is latest of both solasta (with all dlc) and UB.  
[Grapplefun.zip](https://github.com/user-attachments/files/17346798/Grapplefun.zip)
[Johnny.zip](https://github.com/user-attachments/files/17346804/Johnny.zip)

**Comment by ThyWoof** [comment]
Share a screenshot confirming the dice number is incorrect. Cannot repro at all. The saving issue is confirmed.

**Comment by ThyWoof** [comment]
Should be able to fix collateral cases like scorching ray

**Comment by ThyWoof** [comment]
- fixed enhanced bond getting affected by spell damage die advancement

![{8FEADC26-F4EB-4376-8058-2F663FE487F8}](https://github.com/user-attachments/assets/fcb01fa4-3952-44ec-ace6-82bef7f11133)

- fixed fist target logic [only for fire damage. most likely healing is adding to all instances of spell]
- improved combat log to avoid showing message on a save

**Comment by DocEast** [comment]
Thank you for your swift work!  Just took the requested screenshot before seeing you updated this with the fixes without me.
