### ISSUE TITLE
Grappling allies (bug?) (potential option?)

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#4988]
Characters will check against grapples from allies, even when the intent is to help.  This isn't necessarily a bug, but it would be nice to have the option to disable these contested checks.  (Yes, I want to abuse the druid's wildfire spirit to have him fly my druid around, but it also applies to hazardous terrain.)

**Comment by ThyWoof** [comment]
no need for an option. Makes sense. Fixed.
