### ISSUE TITLE
Monk isn't getting extra Pugalist damage when a weapon is equipped

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4989]
Interesting bug where if the monk has the Pugalist fighting style (+1d4 extra damage with unarmed strikes), they do not get the extra +1d4 damage from Pugalist if they chose to attack with unarmed strike while they have a weapon equipped. Save file attached, in this example, the monk has a shortbow equipped but when choosing to attack with unarmed strike, they do not get the Pugalist extra damage. 

Thanks.

[Monk pugalist.sav.zip](https://github.com/user-attachments/files/17345452/Monk.pugalist.sav.zip)

**Comment by ThyWoof** [comment]
cannot repro at all. Ensure you have the latest mod version.
