### ISSUE TITLE
Grappling no longer works with Knock Prone shove

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#4992]
[Farra.zip](https://github.com/user-attachments/files/17377086/Farra.zip)
[Johnny.zip](https://github.com/user-attachments/files/17377087/Johnny.zip)
[Sorven.zip](https://github.com/user-attachments/files/17377088/Sorven.zip)
[Unit.zip](https://github.com/user-attachments/files/17377089/Unit.zip)
[Grappleerror.zip](https://github.com/user-attachments/files/17377078/Grappleerror.zip)
As of the latest update, grappling will no longer allow characters to shove (knock prone) the grappled character (presumably because the grapplee is hidden-flying).  The combo of grapple + shove being about 90% of the utility of grappling an enemy, this is a cause of some concern.  Files above, screenshot below.  (The contested roll goes off normally, but the enemy fails to get the prone condition.)
![GrappleKnockProneError](https://github.com/user-attachments/assets/f17b7f32-5ec3-4bdf-87a5-cc43188ff3ed)

**Comment by ThyWoof** [comment]
Fixed in dec
