### ISSUE TITLE
Circle of Wildfire (Druid) Enhanced Bond Errors

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#4993]
2 errors with enhanced bond:

1.  When applying to a non-cantrip spell, it's using a d12 instead of a d8.
2.  It is applying to only a single creature even when the damage roll should apply to multiples.  (This may be an unavoidable side-effect of how damage is done for multiple entities.)

Screenshot provided.
![EnhancedBondErrors](https://github.com/user-attachments/assets/8a6dc5e9-4356-44a8-9974-36ca223b3109)

**Comment by ThyWoof** [comment]
D12 is a left over from my tests. It should only apply the additional damage to first hit creature AFAIK.

**Comment by DocEast** [comment]
According to the wording, it should apply the extra damage to the roll, not a creature... but then again, this might not be implementable in Solasta (in which case, first hit creature is probably the best compromise).

**Comment by ThyWoof** [comment]
It’s possible. Rule is add to one die roll only. Area spells roll same die for all enemies so they should have it. To be fixed
