### ISSUE TITLE
Settings wiki page is broken

### ISSUE THREAD

**Issue by bagley2014** [SolastaMods/SolastaUnfinishedBusiness#4995]
The [Settings](https://github.com/SolastaMods/SolastaUnfinishedBusiness/wiki/Settings) page on the wiki is broken. To be fair, I don't think you can find it anywhere aside from the list of all the wiki pages, so it's probably fine to just remove the page.

It looks like the images were removed in https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/79078320fde23075f2176597e37b103f55d7561a and never replaced. If those images are still good, maybe they can just be re-added.

I stumbled across the Settings page trying to find out what else the mod offers aside from character and monster options (I had seen mention of a 6 player mode elsewhere) so I'd love to see this page or another page updated to contain that info, if possible.

**Comment by ThyWoof** [comment]
I’m counting on volunteers to do so. Deleted the page meanwhile.
