### ISSUE TITLE
Monk Pugalist Damage Bonus Absent (Now With Screenshots!)

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4997]
I know I've submitted this problem before, but I'm bringing more evidence! 

This is with the current UB version 1.5.97.34

I've attached a ZIP with both the game save and two screenshots. With screenshot "Pugalist damage bonus is absent with weapon in slot", you can see how the pop-up on the unarmed attack ("bare hands") has no additional +1d4 damage from Pugalist.

With the screenshot "Pugalist damage bonus is present with no weapon in slot", you can see the additional +1d4 damage from Pugalist added to the unarmed attack. This is because the shortbow is no longer in the weapon slot.

So there's some error with a  monk when having a weapon in the slot and choosing an unarmed attack that it's not adding the pugalist bonus damage to the unarmed attack when it should. 

Thanks. 
[Archive.zip](https://github.com/user-attachments/files/17415583/Archive.zip)

**Comment by ThyWoof** [comment]
Pugilist has been demoted from mod on next release. It won’t break your game but won’t get offered anymore. Reason why won’t fix it. Please consider the new Brawler and Grappler feats.

**Comment by Bawookles** [comment]
I'd ask you to please consider keeping it. Even though it's a little buggy, it's still by far the best "fighting style" option for a monk. I didn't take it as a feat, I took it as a fighting style during level up. Thanks.
