### ISSUE TITLE
Wildfire Druid's Cauterizing Flames do not work on creatures Large+

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5000]
> When a Small or larger creature dies within 30 feet of you or your wildfire spirit [...]

It should trigger on any creature of at least small size, but only seems to be working on creatures that occupy 1 space.

eg.
![Bandit (medium)](https://github.com/user-attachments/assets/be70affd-c769-40e2-aef1-394f94ac85ec)

![Ogre Zombie (large)](https://github.com/user-attachments/assets/91a6a2ec-e2bf-49a3-a3f3-c048eec9faa0)

![Giant Ape (huge)](https://github.com/user-attachments/assets/58c0dc4b-8635-4753-af44-12423b0148ac)

**Comment by ThyWoof** [comment]
Indeed I put a check in code. I read it incorrectly when coding. Fixed
