### ISSUE TITLE
Druid/Barbarian Multiclass -- inconsistent number of Rages when wildshaped.

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5001]
For a Druid/Barbarian Multiclass, when you become a beast by wildshaping the number of rages shown is less than the number of rages you should have available. For example, see the below images. This also occurs when you have 1 remaining usage, which is unavailable to you while you are wildshaped (so, for example you have to rage first then wildshape to use the last one).

Before Wildshaping: 4 rages available
![image](https://github.com/user-attachments/assets/bd2b8d54-bce7-443e-8649-6302c0dc70f9)

While in Wildshape: 3 rages available.
![image](https://github.com/user-attachments/assets/f641d325-6a91-4a3b-b873-c92cd1745179)

I apparently cannot attach the save file here. Do we have some standardized means of adding a save file, other than just in the Discord?

**Comment by ThyWoof** [comment]
Can you take your hero to Barb 8 and confirm how many rages you see under WS?

**Comment by BShennette** [comment]
At Levels Druid2/Barbarian 1, in wildshape form it shows 2 Rage usages
2/3 shows 3 usages (same, before and after transformation)
2/6 shows 3 usages (should be 4)
2/8 same as 2/6
2/12 shows 3 usages (should be 5)
2/17 shows 3 usages (should be 6)

Seems like it's just capping at 3.

**Comment by ThyWoof** [comment]
Confirmed it correctly collects all rage modifiers on monster but for whatever reason, further on, only considers the set modifier to 3 and ignore all other additions.
