### ISSUE TITLE
Taking 0 damage causes a Concentration check

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5006]
If you take damage, but the damage is reduced to 0 either by a feature or immunity to a damage type, you are still forced to roll a DC10 Concentration save for any spell you are concentrating on, and can lose the spell.

That feels like something that should not happen.

**Comment by ThyWoof** [comment]
As usual need save and logs.

**Comment by ThyWoof** [comment]
I don't have any save to test... will push a fix. please confirm it got fixed.
