### ISSUE TITLE
Stunning fist issues (Monk)

### ISSUE THREAD

**Issue by Nyhilist** [SolastaMods/SolastaUnfinishedBusiness#5010]
Solasta: 1.5.97
Unfinished Business:1.5.97.35
No other mods installed

NEW bug (as of latest version) - can confirm that it did not occur prior to this.
When a Monk uses Flurry of Blows, two things FAIL to occur:
- If you try to use Stunning strike, it does not work: the monster does not need to make a save at all - also does not use your Ki point - so just not triggering;
- Bonus unarmed damage not being added to Flurry of Blows attacks when it should be (second damage number);
- In order to reproduce, simply perform two standard attacks In this case at lvl 16), then trigger Flurry and turn on Stunning Strike...
[Player.log](https://github.com/user-attachments/files/17519824/Player.log)

**Comment by HiddenHax** [comment]
Save with the monk is needed as well. Log alone will not do.
