### ISSUE TITLE
No attack roll when stacking Bardic Inspiration and Precision Attack

### ISSUE THREAD

**Issue by LuckyTortellini** [SolastaMods/SolastaUnfinishedBusiness#5014]
Solasta 1.5.97
UB 1.5.97.35

No other mods

Stacking Bardic Inspiration and Precision Attack resulted in a roll that met the AC of the enemy (Vrockling, AC 15) but did not result in a damage roll in the dialogue box. Afaik enemy's health did not change.

[BardicPrecisionAttack.zip](https://github.com/user-attachments/files/17539123/BardicPrecisionAttack.zip)

![BardicPrecisionAttack](https://github.com/user-attachments/assets/3779ef97-860b-4cf0-83f9-da2bb11ea72f)

**Comment by ThyWoof** [comment]
Unfortunately that’s a limitation with bardic inspiration. It would require a lot of refactor in vanilla to make it stack.

**Comment by ThyWoof** [comment]
you should be happy you use UB. Bard is quite broken in vanilla. it doesn't add the attack roll modifier to the attack delta at all if coming from a bard dice.
