### ISSUE TITLE
Globe of invulnerability does not work sometimes

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#5018]
[Globe_of_Invulnerability_Bug.zip](https://github.com/user-attachments/files/17563222/Globe_of_Invulnerability_Bug.zip)

From what I have seen it seems that AOE spells with recurring effects (for example dawn), ignore the globe on first cast, but the recurring effect is blocked. If you load the save, you should see that we were hit by dawn after I casted globe.

Also, thank you for your continous development of this mod. It is awesome.

**Comment by ThyWoof** [comment]
Endurance, hope, living with uncertainty, remembering the past, the ability to rebuild, and strength of belief. This has been my life as a modder

**Comment by Arcanis2** [comment]
> Endurance, hope, living with uncertainty, remembering the past, the ability to rebuild, and strength of belief. This has been my life as a modder

And don't forget to add "I help people be happier with my work". I love u ^^

**Comment by ThyWoof** [comment]
did some research on my end. it looks like a vanilla bug as code only checks immunity on the spell impact point. that works well when targets are actors but not in dawn case. can you give a quick try on your end, and check if casting dawn on top of an actor will make that actor immune on first cast?

**Comment by ThyWoof** [comment]
@ZheToralf , do you have a save at the beginning of the battle? Enemies aren't casting Dawn anymore

**Comment by ZheToralf** [comment]
Unfortunately not, a friend of mine hosted the game, but I can ask him for it.

**Comment by ThyWoof** [comment]
the other strange thing on above save is it isn't saving for some level 5 spells. I checked vanilla code and indeed it's doing < instead of <= to check for inv.

**Comment by ThyWoof** [comment]
![{02445D33-795D-4B3E-B4A8-9226AFA1CA9B}](https://github.com/user-attachments/assets/718932ff-ac93-4164-9b9c-a891df84f805)
no need for save. setup a test room. what I can find is exactly the opposite.

**Comment by ThyWoof** [comment]
![{0E8EFD5D-5DFB-490D-B73B-77438C08A2BF}](https://github.com/user-attachments/assets/feb75561-3f82-4142-b776-ca3eeea9baa9)
good news, seems to be fixed on my end. will do additional tests and this issue will close when a push the fix.

**Comment by ThyWoof** [comment]
![{5657E16B-5428-4074-8B7C-E1593D3DF396}](https://github.com/user-attachments/assets/d4c1ba0a-6e3a-4c2a-8863-94fd11004302)
also fixed the fact vanilla wasn't considering globe to grant immunity at level 5 (using < instead of <= on check).
