### ISSUE TITLE
Unfinished Business UI missing Interface button

### ISSUE THREAD

**Issue by Cloverdung** [SolastaMods/SolastaUnfinishedBusiness#5023]
The last Unfinished Business Version that displays the Interface button for me is 1.5.97.34.

When I upgrade to UB 1.5.97.35 or 1.5.97.36, the Interface button is no longer displayed.

The only top-level buttons displayed are Gameplay, Character, Encounters, and Credits & Diagnostics after 1.5.97.34.

Solasta v1.5.97 Public
Mod Manager v0.27.10.0
Unfinished Business v1.5.97.34 through 1.5.97.36

**Comment by ThyWoof** [comment]
Do you read the change logs in between updates? These are now under official game settings

**Comment by Cloverdung** [comment]
I do. I went back and re-read the change log for 1.5.97.35 looking for a
reference to the Interface button.

Apparently,

   - moved some mod settings to be offered under game official UI [check
   GUI, and keyboard sections]


equals
   -Moved Interface tab (and maybe other things) to the official game
amongst existing choices (Settings > GUI and Keyboard).

-cloverdung
