### ISSUE TITLE
Spells: 2024 Suggestions

### ISSUE THREAD

**Issue by HiddenHax** [SolastaMods/SolastaUnfinishedBusiness#5028]
A collection of mostly simple 2024 PHB spell changes that could be implemented under latest 2024 section of mod settings:

**Magic Weapon.** Cast as a Bonus Action instead of an Action, concentration is removed, and you now get a +2 bonus from level 3-5 spell slots instead of level 4-6. https://www.aidedd.org/spell/magic-weapon
**Power Word Kill.** Now deals 12d12 psychic damage if the target has more than 100 hp. https://www.aidedd.org/spell/power-word-kill

Edit: Implemented changes are deleted from above list.
Edit: Removed any increase range suggestions as can cause issues in Solasta.

**Comment by EnderWiggin** [comment]
For range increases we need to consider that Solasta has quite confined fights and spaces, so increasing something to full 100+ft is not really needed. Maybe bump those spells couple tiles, double at most if they were quite short ranged.

**Comment by BShennette** [comment]
For reference, the _lightning bolt_ spell has a range of 100ft line (rangeParameter=20) and UB's settings have "Normal Vision range [only in battles]" of 12, 24, and 48. Having spells at range 100+ may not go unnoticed in those cases.

**Comment by ThyWoof** [comment]
Mind Sliver. Damage raised from d4s to d6s. => already in mod.
Power Word Heal. Range increased from Touch to 60 feet. => already in mod.

Not worthy doing Blindness. Range increased to 120 ft for the mentioned reasons.

Added False Life to existing heal spells setting
Removed Somatic from Power Word Heal.
Updated Armor of Agathys.

**Comment by DocEast** [comment]
Is the True Strike rework in the list already or is that something that should be posted here?  For that matter, a QA was mentioned in another thread... can I get a link to that before I start making 2024 suggestions?

**Comment by ThyWoof** [comment]
True Strike 2024 added.

**Comment by ThyWoof** [comment]
Arcane Sword, Circle of Death, Flame Strike, Ice Storm, Vicious Mockery added.
It looks like vanilla already adds spell casting ability to bonus damage on flame blade. Need confirmation.

**Comment by ThyWoof** [comment]
Divine Favor, Lesser Restoration, Stone Skin added.

**Comment by ThyWoof** [comment]
Magic Weapon, Power Word Kill added.
