### ISSUE TITLE
Evoker Subclass feature Sculpt Spell

### ISSUE THREAD

**Issue by FluffyTrain** [SolastaMods/SolastaUnfinishedBusiness#5030]
Evoker Subclass feature Sculpt Spell doesn't protect allies if the caster has the Elemental Adept (Fire) feat. There is also the Elemental Master feat that might cause the same issue.

Edit: After further testing, it doesn't always do it... no idea why.

**Comment by ThyWoof** [comment]
Probably because of the sequence. Will try to add damage immunity to all damage types as well so at least no damage. Not sure if I’ll be able to fully remove the new damage added there

**Comment by FluffyTrain** [comment]
> Probably because of the sequence. Will try to add damage immunity to all damage types as well so at least no damage. Not sure if I’ll be able to fully remove the new damage added there

Only one of my 4 Evokers does that, always the same it seems.

**Comment by ThyWoof** [comment]
Share the save for QA please. Need to ZIP in order to attach here

**Comment by FluffyTrain** [comment]
I tried again, but this time it didn't replicate the issue. Everything worked fine.

In any case, here is the save file:
[Evoker Save Z-Goon.zip](https://github.com/user-attachments/files/17613271/Evoker.Save.Z-Goon.zip)

**Comment by FluffyTrain** [comment]
Further testing works fine. For my part the ticket is closed.
