### ISSUE TITLE
Just Wondering: Face and Eye Options Went Away?

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#5034]
I just noticed in the most recent update that the additional face options and the alternative eye shapes/colors have gone away. Was this intentional or a mistake? Thanks.

**Comment by HiddenHax** [comment]
Look for them in the official game settings.

**Comment by ThyWoof** [comment]
![{B145F25D-A6D9-4F0C-9F55-2843E673C90C}](https://github.com/user-attachments/assets/07fafb80-e724-4b64-a808-72049e18a8dc)

it's always a good practice to read the change log. These are now under official settings.
