### ISSUE TITLE
[Bug] [Artificer] "Terminate Infusions" not propagated in multiplayer.

### ISSUE THREAD

**Issue by Domochevsky** [SolastaMods/SolastaUnfinishedBusiness#5036]
The setup: Multiplayer, three players, I am _not_ the host.
I play as an Artificer (Artillerist). When I terminate my infusions during a short or long rest this is not propagated to the other players. They can still see my infusions sitting where they are. But I can spend them anew as normal. (Essentially replacing them on the other player's gear one after another for them as well if I re-spend all of them.)

This is likely leading to an inconsistent state between us if I don't make sure we're all on the same page, infusion-wise.

**Comment by ThyWoof** [comment]
Possibly fix this one as stop power wasn't getting added to Artificer progression. Most likely the root cause but cannot test. Please reopen this one after you get a chance to test this scenario on next release.
