### ISSUE TITLE
Paladin can choose up to level 5 spells at level 1

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#5039]
Perhaps because of the new "Enable Spellcasting at Level 1" for the Paladin, when that is chosen and she takes a long rest, she can select anywhere up to level 5 spells to memorize. Granted, if anything is memorized above level 1 spells, she won't be able to cast them, but these all shouldn't be available to pick. 

Screenshot and save game attached. 

Thanks

[Archive 2.zip](https://github.com/user-attachments/files/17656571/Archive.2.zip)

**Comment by ThyWoof** [comment]
Found the source issue but still procuring a good solution. Spell points is causing it regardless if on or off.
