### ISSUE TITLE
Unable to load save after latest update

### ISSUE THREAD

**Issue by Pleb24** [SolastaMods/SolastaUnfinishedBusiness#5040]
Hello,

Solasta is unable to load my saves after the latest update to Unfinished Business 1.5.97.37. The game says, "Solasta has encountered an instability." I have verified the game files in Steam. I haven't played since March 21, 2024, so my save was made with a long outdated version of UB and I haven't updated UB between Mar 21 and today.

Not sure how to attach my save, but here is the player log:
[Player.log](https://github.com/user-attachments/files/17667398/Player.log)

I haven't yet tried to revert to the Mar 21 version of UB to see if that fixes it. Any other suggestions?

Thank you and I appreciate the mod greatly otherwise.

**Comment by ThyWoof** [comment]
Many has changed since March. Your current saves or heroes won’t be compatible anymore. You will need to delete them directly in windows explorer while game is running.
