### ISSUE TITLE
Haste not giving extra Action

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#5044]
Playing Palace of Ice (first time through).  Cast Haste with my Paladin/Warlock, and while it gave the extra movement, it did not give an extra action.
[UB Bug reports.zip](https://github.com/user-attachments/files/17685873/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Is action switching enabled? Do so if not to really be able to fully use haste

**Comment by kosocku** [comment]
Yes, action switching is enabled

**Comment by HiddenHax** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/1b748f1d-b380-4eef-baf9-ff11062daf9c)
![Screenshot_3](https://github.com/user-attachments/assets/a63497bf-2c5e-4fc9-be06-78407b4fd5b5)
Works perfectly fine on my end with action switching on.

**Comment by HiddenHax** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/023286ad-d1c6-4200-88fd-d8a6292380ad)
![Screenshot_5](https://github.com/user-attachments/assets/226777a8-2bdf-4555-94d4-d87f71b1b628)
Don't see any issues here either.

**Comment by kosocku** [comment]
It wasn't even giving me the spot with the two white icons.  I ended up re-installing the mod, seems to have fixed the issue.
