### ISSUE TITLE
Guardian Armorer Artificer's lvl 15 Perfected Armor slow effect stalls turn order

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#5048]
Seems to happen when a creature fails it's saving throw against the slow effect of the Thunder Gauntlets while my Artificer is concentrating on Expeditious Retreat.  I've noticed a delay on Quicken Spell on the Sorcerer before, but usually only for a few seconds before it picks up again.  This, however, I let sit for well over a minute without it ever coming back to the action bar so I could take a 2nd attack.  Save is after the Artificer's movement, having already casting ER.  Just have to make attacks.  
[UB Bug reports.zip](https://github.com/user-attachments/files/17693682/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Here is a perfect example why I always ask for saves, settings, etc. Issue isn't with your Artificer. It's the Opportunist in party that is breaking it.

**Comment by ThyWoof** [comment]
![{4BC6A581-366E-46C9-B488-14297610FDE8}](https://github.com/user-attachments/assets/2ffc8240-40c6-4946-8e62-6712e0f6402a)
fixed.
