### ISSUE TITLE
Post from Reddit for Zappa

### ISSUE THREAD

**Issue by Krayte** [SolastaMods/SolastaUnfinishedBusiness#5051]
Hey Zappa,

It's ZOMGLAZERS from Reddit with the de-sync issues post.  Here is my save file.
[Jon_Before Art change.zip](https://github.com/user-attachments/files/17720532/Jon_Before.Art.change.zip)

Thanks a ton for looking into this!

**Comment by ThyWoof** [comment]
I also need your settings file.

**Comment by ThyWoof** [comment]
![{E8781C1D-EF0B-4CBF-BA7E-BE42E7C7BB6B}](https://github.com/user-attachments/assets/b5cce0d6-5e86-4424-bfbc-74624e938cad)
![{03419616-C481-4CDF-A6DE-BD2AE86188F9}](https://github.com/user-attachments/assets/64fd1d8b-3cb5-4da7-b12e-2ea23d0dddc3)
![{2454B93D-3057-4796-9B21-F2827246F1ED}](https://github.com/user-attachments/assets/48797fed-9232-40e9-b51a-822d99aa1085)
![{E33615A2-51F4-4FE0-904E-BFF2ACDB485F}](https://github.com/user-attachments/assets/ee5beb10-af73-4ff8-a29c-561935932572)
![{606AD1DF-5D13-468A-AFA0-4E9F887282AF}](https://github.com/user-attachments/assets/6ccaf336-2dc0-4942-b7bd-2e0b327b0ebb)

all works on your save. I never got your settings. Won't have more time to dive into this. Most likely, an user error.

**Comment by ThyWoof** [comment]
screenshots are from different clients.

**Comment by ThyWoof** [comment]
![{E52B7B5F-06E4-4FFF-A1E6-624C952BDD03}](https://github.com/user-attachments/assets/c2922099-30f0-41a1-a8a4-2c0d1ab6a358)

![{559A580F-52A7-4DD8-B355-738A391840F1}](https://github.com/user-attachments/assets/75ee753c-0727-46e9-94b2-18d3e1df713d)

game continued, no desync.

**Comment by ThyWoof** [comment]
Sorry, these screenshots are from another issue

**Comment by ThyWoof** [comment]
There is a known issue with parties of 6, where some heroes get assigned to more than one player. I wasn't able to fix this one yet. For now, let your players know and ensure they don't control heroes they should not.
