### ISSUE TITLE
Word of Radiance not damaging enemies

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#5053]
[Word_of_radiance_bug.zip](https://github.com/user-attachments/files/17721594/Word_of_radiance_bug.zip)
Word of radience shows an area of effect around the character. But when I cast it, it does no damage. Additionally, the animation for the spell impact seems to proc at a completely different tile.

**Comment by BShennette** [comment]
Similarly, the _Thunderclap_ cantrip also does not appear to work.
