### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by patrikucarlsson** [SolastaMods/SolastaUnfinishedBusiness#5055]
I have installed, from Unitiy mod manager, UB.
However the mod does not work, or it rather is "not activated"
I get the message, see picture.

Feels like it has to do with "Unity program" or is it so?

![Installation problem Solasta](https://github.com/user-attachments/assets/3ff94623-f1b6-4ca2-8b0d-6caec6a607d0)

**Comment by ThyWoof** [comment]
Your UMM version isn’t compatible. Follow install instructions by letter with link to proper UMM.
