### ISSUE TITLE
What happened to War Dancer?

### ISSUE THREAD

**Issue by Rail1337** [SolastaMods/SolastaUnfinishedBusiness#5058]
Hey just curious, played this mod last time 1 year ago and there was a Bard subclass called War Dancer, it seems removed from the mod.
Is there a way to activate it or do I need to run an old version of the mod to have it?

Last entry was in version: 1.5.97.6 saying something about "hided"

**Comment by BShennette** [comment]
> [...] Old raven is weaker than this monstrosity. Momentum is impossible to balance so its going away for good. In fact... basically entire sub must go as there is nothing that can be done to balance it. [...]

from the UB Discord channel.

> removed College of War Dancer offering from mod UI [sorry Nd, way OP]

From 1.5.97.6 final QA build notes.
