### ISSUE TITLE
Fighter Battle master maneuver Aimed attack doesn't consume superiority dice or bonus action

### ISSUE THREAD

**Issue by Keerotron** [SolastaMods/SolastaUnfinishedBusiness#5059]
Heya!

I've been playing few campaigns with my friends and we noticed the fighter subclass battle master using maneuver named "Aimed attack" (which gives advantage on the next attack) doesn't consume any superiority dice or bonus action. Save file and mod settings attached

[aimedattack.zip](https://github.com/user-attachments/files/17791975/aimedattack.zip)

Huge thank you for the awesome mod!!!

Keero

**Comment by ThyWoof** [comment]
fixed already. thanks. https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/fc92b7d458be1345ace2c1517b91f1fb69d84b47
