### ISSUE TITLE
2024 Feat:  Magic Initiate

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#5060]
The 2024 version of Magic Initiate only allows for Wizard, Cleric, or Druid spell lists, but it lets you pick your spellcasting  ability for those spells (Int, Wis, or Cha) when you select the feat.  This is a very powerful change (especially for an origin feat) that would be nice to have.

**Comment by ThyWoof** [comment]
Feats will come after I finish subs and spells.

**Comment by ThyWoof** [comment]
In order to code this one correctly I’ll have to break backward compatibility. Won’t code these changes.
