### ISSUE TITLE
2024 Feat:  Alert

### ISSUE THREAD

**Issue by DocEast** [SolastaMods/SolastaUnfinishedBusiness#5061]
With the change to surprise in 2024, the Alert feat has had a major revamp.  Now it does two things:

1.  Add your proficiency to your initiative and 
2. Allow you to optionally swap your initiative with another player.

1) Would be trivial to implement, but I don't know if 2) can be done at all.  Nevertheless, I'm throwing it on the stack for 2024 changes until I know better.

**Comment by ThyWoof** [comment]
Feats will come after I finish subs and spells.

**Comment by jlk493** [comment]
> Feats will come after I finish subs and spells.

I'm guessing fighting styles will come after those. Any chance we'll see the _Blessed Warrior_ fighting style for Paladins or the _Druidic Warrior_ fighting style for Rangers?

**Comment by ThyWoof** [comment]
> > Feats will come after I finish subs and spells.
> 
> I'm guessing fighting styles will come after those. Any chance we'll see the _Blessed Warrior_ fighting style for Paladins or the _Druidic Warrior_ fighting style for Rangers?

These aren’t hard to code if I ignore the replace cantrip on level up. That’s a hard limitation engine has.

**Comment by jlk493** [comment]
> > > Feats will come after I finish subs and spells.
> > 
> > 
> > I'm guessing fighting styles will come after those. Any chance we'll see the _Blessed Warrior_ fighting style for Paladins or the _Druidic Warrior_ fighting style for Rangers?
> 
> These aren’t hard to code if I ignore the replace cantrip on level up. That’s a hard limitation engine has.

I think that helps to maintain balance actually. In 5e, Artificers can change their cantrips at every new level, and in the 2024 rules, all fullcaster classes can do this. If no one can change their cantrips in Solasta, that helps to keep things even. 

Citation: https://rpgbot.net/dnd-2024-5e-transition-guide-and-change-log-everything-thats-different-in-the-new-players-handbook/#:~:text=1.,you%20gain%20a%20Cleric%20level.

**Comment by ThyWoof** [comment]
> > > > Feats will come after I finish subs and spells.
> > > 
> > > 
> > > I'm guessing fighting styles will come after those. Any chance we'll see the _Blessed Warrior_ fighting style for Paladins or the _Druidic Warrior_ fighting style for Rangers?
> > 
> > 
> > These aren’t hard to code if I ignore the replace cantrip on level up. That’s a hard limitation engine has.
> 
> I think that helps to maintain balance actually. In 5e, Artificers can change their cantrips at every new level, and in the 2024 rules, all fullcaster classes can do this. If no one can change their cantrips in Solasta, that helps to keep things even.
> 
> Citation: https://rpgbot.net/dnd-2024-5e-transition-guide-and-change-log-everything-thats-different-in-the-new-players-handbook/#:~:text=1.,you%20gain%20a%20Cleric%20level.

Confirmed these are now on DEV.

**Comment by ThyWoof** [comment]
After reading both 2014 and 2024 alert, I prefer to stick with 2014 version. Won’t code this one.
