### ISSUE TITLE
Spells: More 2024 Suggestions

### ISSUE THREAD

**Issue by HiddenHax** [SolastaMods/SolastaUnfinishedBusiness#5064]
Round two of 2024 spell suggestions. Spells that are fundamentally changed in 2024 aren't included in this list.

~~**Aura of Vitality.** Now instead of bonus action, heal is a free action and can be used on the turn in was cast. https://5e.tools/spells.html#aura%20of%20vitality_xphb~~
~~**Banishing Smite.** School changed from Abjuration to Conjuration. https://5e.tools/spells.html#banishing%20smite_xphb~~
~~**Hunter’s Mark.** Now deals Force damage. https://5e.tools/spells.html#hunter's%20mark_xphb~~
~~**Mirror Image.** The method for determining if an illusion was hit has changed. https://5e.tools/spells.html#mirror%20image_xphb~~
~~**Power Word Stun.** The target’s speed is reduced to 0 for one turn if the target has more than 150 hp. https://5e.tools/spells.html#power%20word%20stun_xphb~~
~~**Ray of Sickness.** This spell currently doesn't exist in vanilla or mod but should be super simple to implement https://5e.tools/spells.html#ray%20of%20sickness_xphb~~
~~**Spare the Dying.** Now has 15-foot range, and the range doubles multiplicatively every time cantrips improve. https://5e.tools/spells.html#spare%20the%20dying_xphb~~
~~**Spider Climb.** Now allows you to add one additional target per upcast level. https://5e.tools/spells.html#spider%20climb_xphb~~
**Stinking Cloud.** Now also disallows Bonus Actions in addition to Actions. https://5e.tools/spells.html#stinking%20cloud_xphb
~~**Swift Quiver.** You now get to make the attacks on the same turn as part of the Bonus Action to cast the spell. https://5e.tools/spells.html#swift%20quiver_xphb~~
~~**Hideous Laughter.** The spell can now be upcast with +1 target per upcast. https://5e.tools/spells.html#tasha's%20hideous%20laughter_xphb~~
~~**Weird.** The initial damage is buffed to 10d10 and recurrent damage to 5d10. https://5e.tools/spells.html#weird_xphb~~
~~**Wrathful Smite.** Can now be upcast for +1d6 damage per spell level. https://5e.tools/spells.html#wrathful%20smite_xphb~~

**Comment by ThyWoof** [comment]
@HiddenHax, vanilla seems to be already preventing any action on Stinking Cloud. Found out a special behavior on action affinities that forces a save on turn initialization before any action can even be considered. Couldn't find anything differentiating from main or bonus. Can you confirm that?
