### ISSUE TITLE
Guardian Fighter does not get Second Wind charges

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#5065]
[second_wind_bug.zip](https://github.com/user-attachments/files/17821712/second_wind_bug.zip)
After a long rest, my guardian fighter (Ezio) does not have a charge for second wind. I am not sure if this bug is mod related but since I have a UB subclass, I thought I might bring it up.

The custom campaing is [Island of domination](https://steamcommunity.com/sharedfiles/filedetails/?id=2933306591&searchtext=island)

**Comment by ThyWoof** [comment]
Use refresh powers under credits / party editor and let me know if problem persists after long rest

**Comment by ThyWoof** [comment]
![{AFFDDF20-A6B1-480D-A365-B16D30E34CDB}](https://github.com/user-attachments/assets/a8f4bc9e-6510-4321-b1b4-c63e85a43114)
above tip worked for me.

**Comment by ZheToralf** [comment]
Not for me, I don't know what the problem is.

**Comment by ThyWoof** [comment]
Have you refreshed the powers as suggested?

**Comment by ZheToralf** [comment]
Yes I did. I'm at work now but I will try some stuff again later.

**Comment by ZheToralf** [comment]
[Zhe Toralf.zip](https://github.com/user-attachments/files/17835598/Zhe.Toralf.zip)
No matter how many times i press "refresh powers" or "long rest" It does not make a difference. I exported my Mod settings, maybe there is a setting that is different to your config? I can't think of anything else it could be.
