### ISSUE TITLE
Blind Fighting does not work on large enemies right next to me

### ISSUE THREAD

**Issue by ZheToralf** [SolastaMods/SolastaUnfinishedBusiness#5068]
I am in darkness (no darkvision), a troll right next to me My fighter has blind fighting but still has disadvantage on attacking the troll.

**Comment by ZheToralf** [comment]
A friend of mine hosted the game, I asked him for the save and will add it as soon as I get it.

**Comment by ThyWoof** [comment]
Game has this limitation. Distance calculation is done in a very odd way with large enemies. We tried to fix that in other places. Were you using the lightning and obscurement setting in mod?

**Comment by ZheToralf** [comment]
Yes, we have "lighting, obscurement and vision" enabled

**Comment by ZheToralf** [comment]
[BLIND_FIGHTING_BUG.zip](https://github.com/user-attachments/files/17879161/BLIND_FIGHTING_BUG.zip)
Finally got the save. Sorry it took so long.

**Comment by ThyWoof** [comment]
This is a very hard use case to fix because engine has some limitations. Sorry.

**Comment by ZheToralf** [comment]
It's okay. At least I now know what I can do to avoid it. Thanks for looking into it.
