### ISSUE TITLE
Stars Druid Chalice and Life Cleric Disciple of Life Bug?

### ISSUE THREAD

**Issue by tlcstar** [SolastaMods/SolastaUnfinishedBusiness#5070]
Hello! I might have found a bug:
Version: 1.5.97.39
Abilities: Circle of Stars Druid - Starry Form Chalice & Life Cleric - Disciple of Life

Description: 
My Life Cleric / Stars Druid casts Cure Wounds (lvl1) on another character while in Chalice form. It heals 1d8 + Spellcasting modifier. I think it should heal 1d8 + spellcasting mod + 2 (Disciple of Life). Additionally The Chalice bonus healing (1d8 + WIS) doesnt trigger.

Step by step: Use Starry Form Chalice. Use cure wounds on another character.
[log.txt](https://github.com/user-attachments/files/17852771/log.txt)
[chalicebug.zip](https://github.com/user-attachments/files/17852774/chalicebug.zip)
(Character File + Save)

Am I just missing something?

**Comment by kosocku** [comment]
Actually, it should be 1d8 + Wis mod +3 (Disciple of Life = 2+Spell slot lvl used)

**Comment by tlcstar** [comment]
Thanks, so Disciple of Life behaves like the tabletop and the description ingame is wrong: When casting a healing spell, the target regains additional HP equal to (2× spell level). 
It is different to the tabletop: Whenever you use a spell of 1st level or higher to restore hit points to a creature, the creature regains additional hit points equal to 2 + the spell's level.

Chalice still doesn't trigger though.
