### ISSUE TITLE
Hexblade's Soul Empowered not using Spellcasting Attribute

### ISSUE THREAD

**Issue by lsware94** [SolastaMods/SolastaUnfinishedBusiness#5074]
Version: 1.5.97.39

Description: Soul empower is granting magical weapon status to main hand and offhand with two weapon fighting style but does not change the attribute to charisma. So the attack and damage are still based off of strength or dexterity depending on the weapon.

Character Files:
[Soul_Empower_Bug.zip](https://github.com/user-attachments/files/17878244/Soul_Empower_Bug.zip)

Not sure if I am doing something wrong here or if there is some toggle for this feature but it is currently not functioning. I don;'t appear to have any log files and I have no other mods.

**Comment by ThyWoof** [comment]
Thanks for properly sharing assets. Fixed in DEV branch.
