### ISSUE TITLE
Telekinetic not giving abilities

### ISSUE THREAD

**Issue by Avalon1892** [SolastaMods/SolastaUnfinishedBusiness#5076]
I have no other mods installed.

Using version [1.5.97.39] on the recommended Unity Mod Manager version.

-------------

Bug:

When I got level 2 on a Shadar-Kai Wizard and took the Telekinetic [Int] feat, i did not receive the ability of it, only the ASI +1.
I tried using short and long rest to see if itll update, but no luck so far. Idk how i can fix this.

**Comment by ThyWoof** [comment]
Save? Logs? please reopen once you provide all assets we need.
