### ISSUE TITLE
Forceblade Sorcerer's "Arcane Weapon" bonus not working

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#5079]
Using the latest patch 1.5.97.39. Forceblade Sorcerer's "Arcane Weapon" feature is not working. His attack and damage bonuses are coming from his DEX rather than his CHA. Screen capture and save game attached. 

[Archive.zip](https://github.com/user-attachments/files/17910687/Archive.zip)

**Comment by ThyWoof** [comment]
Thanks for save. Already fixed in dev.
