### ISSUE TITLE
Guardian Armorer Artificer's Thunder Gauntlets using STR instead of INT for attack

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#5082]
Title says it all.  Noticed my +hit was low, then noticed my damaged was low.  Sure enough, using my +2 Str instead of my +6 Int for attacks and damage, nor is it applying my Power Attack (-3 hit, 3+PB to damage) to the +hit or damage.  At one point re-loaded and swapped to Infiltrator mode, and the Lightning Launcher there is using Str instead of Int too.
[UB Bug reports.zip](https://github.com/user-attachments/files/17954327/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
thanks for save, already fixed in DEV.
