### ISSUE TITLE
Path of the Yeoman Barbarian Features Not Working

### ISSUE THREAD

**Issue by TheHunted1** [SolastaMods/SolastaUnfinishedBusiness#5085]
The level 3 Feature is not using Strength nor does it add Rage damage to Longbows.
The level 6 Feature does not give Advantage to attack rolls with bows when using Reckless Attack. I don't know if the Brutal Critical part is working.

These issues exist in UB version 1.5.97.39 and Solasta version 1.5.97, with no other mods installed.

Reproducing the bug is easy, just level up a Path of the Yeoman Barbarian and shoot enemies with a bow. Activate Reckless to witness its lack of function, and use a Belt of Fire Giant Strength to notice that it isn't being helpful.

[Character](https://www.dropbox.com/scl/fi/x0qookvw9dvgod47d99lv/ArcherMax.chr?rlkey=qf0llsok9spk5o0jq5oevk6rt&st=gkfa4zvq&dl=0).

Log:
`Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.37f1 (019e31cfdb15)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2070 (ID=0x1f14)
    Vendor:   
    VRAM:     8019 MB
    Driver:   31.0.15.3713
Begin MonoManager ReloadAssembly

[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.24.2.0.
[Manager] OS: Microsoft Windows NT 10.0.22631.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.371.
[Manager] Game: Solasta.
[Manager] Mods path: C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods.
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-0000029AE2D7A190.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/Mono/data-0000029AE29E1570.dll
[Manager] Injection successful.
- Completed reload, in  0.610 seconds
<RI> Initializing input.
New input system (experimental) initialized
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.875700 ms
WwiseUnity: Wwise(R) SDK Version 2021.1.4 Build 7707. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data\Plugins\x86_64 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

WwiseUnity: Sound engine initialized successfully. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 28.388900 ms (FindLiveObjects: 1.114800 ms CreateObjectMapping: 0.613200 ms MarkObjects: 26.607600 ms  DeleteObjects: 0.052700 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 11533.
Total: 31.431200 ms (FindLiveObjects: 1.634200 ms CreateObjectMapping: 0.616700 ms MarkObjects: 29.163400 ms  DeleteObjects: 0.016300 ms)

[Manager] Parsing mods.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Slasta_COTM\Mods\SolastaUnfinishedBusiness\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[SolastaUnfinishedBusiness] Version '1.5.97.39'. Loading.
[SolastaUnfinishedBusiness] [Error] HarmonyLib.HarmonyException: IL Compile Error ---> System.FormatException: Method static System.Boolean RuleDefinitions::IsPositionImmuneToSpell(TA.int3 targetPosition, TA.int3 sourcePosition, System.Int32 spellLevel, System.Int32& totalSpellLevel) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) RuleDefinitions:RuleDefinitions.IsPositionImmuneToSpell_Patch1 (TA.int3,TA.int3,int,int&): IL_0230: call      0x00000071

  at HarmonyLib.Memory.DetourMethodAndPersist (System.Reflection.MethodBase original, System.Reflection.MethodBase replacement) [0x00021] in <6ad64e60db9e43e5a66782c0bcf0cc7d>:0 
  at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x0007b] in <6ad64e60db9e43e5a66782c0bcf0cc7d>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <6ad64e60db9e43e5a66782c0bcf0cc7d>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x00084] in <6ad64e60db9e43e5a66782c0bcf0cc7d>:0 
  at SolastaUnfinishedBusiness.Api.ModKit.ModManager`2[TCore,TSettings].Enable (UnityModManagerNet.UnityModManager+ModEntry modEntry, System.Reflection.Assembly assembly) [0x000a6] in <9711ca2b96284dd99e8ee4e6a42e0a78>:0 
[SolastaUnfinishedBusiness] Unofficial translations support disabled.
[SolastaUnfinishedBusiness] Active.
[SolastaUnfinishedBusiness] Loading time 3.11 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.

[Manager] Spawning.
[Manager] Checking updates.
[SolastaUnfinishedBusiness] 6326 en translation terms loaded of 6326 provided.
[SolastaUnfinishedBusiness] 0 en translation fixes loaded.
Cannot find element Opportunist in database CharacterSubclassDefinitionDatabase 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Exception when loading C:/Users/Gerar/AppData/LocalLow/Tactical Adventures/Solasta\Characters\Monklevel.chr. System.Exception: An exception has been thrown during the deserialization of an element of type Snapshot (serialization type: Snapshot) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at RulesetCharacterHero+Snapshot.SerializeElements (IElementsSerializer serializer, IVersionProvider versionProvider) [0x000b4] in <14069e0776c443f6af77ee3eeee86525>:0 
  at BinarySerializer.SerializeElement[T] (System.String elementName, T value, Serializer+SerializationOption serializationOptions) [0x00217] in <14069e0776c443f6af77ee3eeee86525>:0 
   --- End of inner exception stack trace ---
  at BinarySerializer.SerializeElement[T] (System.String elementName, T value, Serializer+SerializationOption serializationOptions) [0x0045e] in <14069e0776c443f6af77ee3eeee86525>:0 
  at Serializer.SerializeElement[T] (System.String elementName, T value) [0x00000] in <14069e0776c443f6af77ee3eeee86525>:0 
  at CharacterPoolManager.EnumeratePool () [0x000ec] in <14069e0776c443f6af77ee3eeee86525>:0 . 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Uploading Crash Report
Exception: [Tactical Invisible For Players] Impossible to load character.

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Trace:LogException(Exception)
CharacterPoolManager:EnumeratePool()
<AsyncCreateCharacterTemplates>d__12:MoveNext()
TA.Coroutine:Run()
RuntimeState_Booting:Update()
FiniteStateMachine:Update()
Runtime:Update()
RuntimeManager:Update()
 
(Filename:  Line: -1)

[SolastaUnfinishedBusiness] enabled in 00:00:31.5895048.
Unexpected timestamp values detected. This can occur in H.264 videos not encoded with the baseline profile. Timestamps will be skewed to correct the playback for C:/Program Files (x86)/Steam/steamapps/common/Slasta_COTM/Solasta_Data/StreamingAssets/BackgroundMovie.MP4 
(Filename:  Line: 0)

`

**Comment by ThyWoof** [comment]
The attribute stuff was introduced in v39 and already fixed. That monk you have is borked. Delete it.

**Comment by TheHunted1** [comment]
That Monk is deleted already. Are you sure the attribute stuff was fixed? That doesn't seem right on account of it currently not working.
