### ISSUE TITLE
Fighters Have Zero Max Uses on Second Wind

### ISSUE THREAD

**Issue by justEthaniguess** [SolastaMods/SolastaUnfinishedBusiness#5086]
I'm having similar issues with my mountaineer fighter to the issue in this ticket: https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/5065. My fighter from Against the Cult on Steam Workshop doesn't have any max charges for Second Wind so she never gets any uses back, even after a short or long rest. This is using the latest V1.5.97.39 (and V1.5.97 of Solasta).  I have found the following steps to reproduce this with a Fighter. Currently tested for Mountaineers and a Level 2 subclass-less fighter:

1. Set UB to not use the 5e 2024 rules for Second Wind if not done so already.
2. Open or create a new campaign with a Fighter created before V .39 of UB.
3. Level this fighter up (I have used the tools in UB to allow level-ups without XP and used UB to force a long rest, but this should also work if levelling up and long resting normally).
4. Fighter no longer has any uses of Second Wind. Their current uses when hovering over Second Wind will be '0/0', or it will not appear at all if your Fighter has no other abilities.

Using refresh powers and long resting does not fix the issue, downgrading to V.38 is the only fix for me once this issue occurs, but means I would not be able to update the mod anymore without avoiding this bug. I suspect this bug could have been accidentally introduced in the bug fix for the error with the 5e 2024 Second Wind from the latest patch, but can't say for certain. The bug only exists for the vanilla 2014 5e rule in the game.

I have no mods installed aside from UB, with the only other things downloaded being custom campaigns from Steam Workshop.

I've attached the save where I have experienced the bug, the log from the save and the Level 1 version of the character.

![image](https://github.com/user-attachments/assets/363a81c4-22cf-47c9-a9f5-dac2998d281a)
[Second Wind Bug.zip](https://github.com/user-attachments/files/17969539/Second.Wind.Bug.zip)

**Comment by ThyWoof** [comment]
fixed in v40 just released.

**Comment by justEthaniguess** [comment]
Awesome, works in v40 after a use of Refresh Powers! Thank you so much!
