### ISSUE TITLE
Some oversights with Warlock changes for 2024

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5088]
1) the Warlock invocation Eldritch Smite seems to have been mistakenly converted to consuming a Bonus Action, alongside the paladin's smites for the 2024 rules.

2) Pact of the Familiar invocation (2024) shows 0/0 uses available.

**Comment by BShennette** [comment]
[Test_GFB_PlusFireDmg.zip](https://github.com/user-attachments/files/17970282/Test_GFB_PlusFireDmg.zip)
Save to test.

**Comment by HiddenHax** [comment]
Bug confirmed. Eldritch Smite should be excluded as it has nothing to do with paladin smites.

**Comment by ThyWoof** [comment]
can I have a new ticket with a save for Pact of the Chain?
