### ISSUE TITLE
Green-Flame Blade not benefiting from Celestial Warlock/Draconic Sorcerer features extra dmg

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5089]
Green-Flame Blade does not benefit from either the Celestial Warlock's _Radiant Soul_ which grants +CHA dmg to spells that deal Fire or Radiant damage.

It also does not benefit from the Draconic Sorcerer's _Elemental Affinity_ feature which adds +CHA bonus damage to spells that deal Fire damage (Gold Dragon heritage, presumably the same if there were other blade cantrips that matched dragon heritages).

Certainly it does not apply to the initial hit's damage when Lv.5+ (deals +1d8 fire damage to initial target) -- but it may be the case that one of them (not both) are applying to the extra damage if there is a second enemy nearby. I had that scenario once, and it did deal 2x CHA damage on the second enemy instead of the 1x as expected from the spell alone.

**Comment by BShennette** [comment]
[Test_GFB_PlusFireDmg.zip](https://github.com/user-attachments/files/17970279/Test_GFB_PlusFireDmg.zip)
Save to test.

**Comment by ThyWoof** [comment]
Unfortunately, this will be a misery to fix. Blade Cantrips issue a weapon attack. We would require collect all spell attack modifiers, vanilla, and mod behaviors.

Cannot fix. sorry.
