### ISSUE TITLE
Pact of the Familiar Invocation (2024) shows 0/0 uses

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5091]
Mentioned in a previous issue, but separated to its own. Title explains, save can be found in the linked issue.

https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/5088

**Comment by ThyWoof** [comment]
![{A8AD066C-A917-494D-969D-4996EAE89493}](https://github.com/user-attachments/assets/6bd6609c-91ee-4489-80a5-59169e25a1bc)

trying to understand why game doesn't set this initial attribute to 1 when from 2024 invocation.

meanwhile, use party editor as above to increase your pact chain to 1.

**Comment by ThyWoof** [comment]
![{7ECE63C6-79FD-4607-AB12-CDAFE67B503C}](https://github.com/user-attachments/assets/b718b084-5997-44f5-9851-5a4bee458982)
indeed RefreshAttributeModifiersFromInvocations wasn't considering modifiers from sets
