### ISSUE TITLE
Sculpt Spell not working for spells that last multiple rounds?

### ISSUE THREAD

**Issue by NightOwlExe** [SolastaMods/SolastaUnfinishedBusiness#5092]
Before anything else, I want to give a **HUGE** thank you for this fantastic mod. It is bringing my friends and myself a lot of joy so far. I'm very happy that this project exists and I appreciate your work.

As I could not find any issues or discussions with this topic on other platforms so far, I decided to open a new issue. I hope this is fine.

It seems like the Sculpt Spell feature is only working on spells like Fireball or Lightning Bolt. On my end evocation spells with effects lasting for more than one round affect allies as usual (they still get damaged by it). Is this just an issue on my end or can anyone confirm this?

For the first case: Does anyone have an idea what can cause this problem?
For the second case: Is this behaviour intended or will/could it be changed? 

I thank you very much for your attention.

**Comment by HiddenHax** [comment]
Recurrent effects like Wall of Fire and such are very problematic to handle code-wise and would require extreme amount of work to fix. Unlikely that such things will get fixed tbh.

**Comment by NightOwlExe** [comment]
Thanks a lot for your quick answer! :)
That's very sad but also very understandable. c:
