### ISSUE TITLE
Blade Mastery and Longsword Finesse perk causes stuttering

### ISSUE THREAD

**Issue by doodooface** [SolastaMods/SolastaUnfinishedBusiness#5097]
So I have tested this extensively by giving one of my characters the perk Blade Mastery and/or Longsword Finesse, once the character has one or both perks would cause frames to drop when that character is moving around.

Once I remove the perk, the stuttering, when moving, is gone.

**Comment by doodooface** [comment]
Just tested this on the new 1.5.97.40, but this was happening on the few previous versions (from when I started playing).

**Comment by ThyWoof** [comment]
I would be rich if I made money every time someone reports without logs or saves.

Reopen once you provide all required files per “how to report bugs”, I hope you have read. Probably haven’t.

**Comment by doodooface** [comment]
Sorry about that, I was about to upload my savegame. But I wanted to try to repro with a new game and the stuttering didn't happen with the new game.

Let me try a few more things and report back if I can repro. Thank you.
