### ISSUE TITLE
Armorer Artificer not benefiting from Power Attack

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#5100]
My best guess at this point is that the Thunder Gauntlets of the Armorer Artificer are not being considered as melee weapons, so Power Attack isn't affecting the hit/damage of your attacks.
[UB Bug reports.zip](https://github.com/user-attachments/files/18046257/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Unfortunately I cannot test on provided save. Please get one in a battle, on artificer round.

**Comment by kosocku** [comment]
My apologies.  This should be a good one

[UB Bug reports.zip](https://github.com/user-attachments/files/18049788/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Fixed, thanks for save.
