### ISSUE TITLE
Request for infinite item stacking (or highest possible)

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#5113]
Not a bug or issue really, just not sure where else to request things.

I'm not sure why the base game already puts a limit on this, but I don't see any reason for limiting the number of items that can stack. If inventory squares were limited, this would make sense, but to my knowledge and experience playing so far, there is no limit to how many inventory squares you can fill up on any given character. Inventory is only limited by your carry weight.

So in light of that, I'd like request an inventory item stack increase mod option.

**Comment by ThyWoof** [comment]
This could open some collateral scenarios in other places. Won’t code this one.
