### ISSUE TITLE
Wizard/Sorcerer not using casting modifier on True Strike when first loading game

### ISSUE THREAD

**Issue by kosocku** [SolastaMods/SolastaUnfinishedBusiness#5114]
Whenever I load the game for the first time, and apparently before I take a short/long rest, both my Sorcerer and Wizard are not using their casting ability score when using True Strike.  After a rest or any sort, it seems like it works as it's supposed to.

[UB Bug reports.zip](https://github.com/user-attachments/files/18219409/UB.Bug.reports.zip)

**Comment by ThyWoof** [comment]
Are settings in zip? If not can you please share as well?

**Comment by kosocku** [comment]
It is now.  At least, I THINK I did it right

[UB Bug reports.zip](https://github.com/user-attachments/files/18225049/UB.Bug.reports.zip)
