### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Kindamir** [SolastaMods/SolastaUnfinishedBusiness#5115]
Hadn't played in several months so I went and updated to the latest UB version and now when I launch it errors that there is an issue with the mod.  I tried reinstalling the mod and the game.  I unsubscribed from all Steam Workshop items as a test and no change in behavior.  

![image](https://github.com/user-attachments/assets/cdf4a520-4e94-4a4f-b783-1ae19aad0e30)
![image](https://github.com/user-attachments/assets/689d2266-a9c6-4690-9eed-ebb2dd39f332)
[Player.log](https://github.com/user-attachments/files/18241526/Player.log)

**Comment by ThyWoof** [comment]
I cannot support you on mod version 1.4.*. It won’t be compatible with latest game version. You need to install latest version from releases.
