### ISSUE TITLE
Could not complete tutorial, disemngage from wolf 

### ISSUE THREAD

**Issue by Mormagill** [SolastaMods/SolastaUnfinishedBusiness#5117]
Solasta 1.97, latest
Mod manager 27.10
Mod 1.5.97.42

Enabled all the 2024 options and a bit more
Started main campaign
Tutorial mission 2, with wolves , pressed disengage,
all squares lighted up shows X cursor
unable to move
cannot cancel disengage
stuck
  
Save file:
[start.zip](https://github.com/user-attachments/files/18247140/start.zip)

**Comment by ThyWoof** [comment]
Known issue related with UB formation settings. I wont fix as UB users really don’t play the tutorial.
