### ISSUE TITLE
Disheartening Performance cause an instabitilty

### ISSUE THREAD

**Issue by WeiDe2512** [SolastaMods/SolastaUnfinishedBusiness#5120]
If you use Disheartening Performance on an enemy, combined with an effect like Hideous Laughter, and then attack that enemy while Hideous Laughter is still active due to Disheartening Performance, the game may detect an instability. This issue forces you to either load a save or quit the game. PS I am playing online

[Files.zip](https://github.com/user-attachments/files/18268084/Files.zip)

**Comment by ThyWoof** [comment]
Is this something you can also consistently reproduce on a single player game?

**Comment by WeiDe2512** [comment]
This is a solo run and I saved right before you attack with the monk

[Files solo.zip](https://github.com/user-attachments/files/18270592/Files.solo.zip)

**Comment by ThyWoof** [comment]
![{70C91C6D-25C5-4E02-80EF-BCD1ED15F4F0}](https://github.com/user-attachments/assets/65074437-be05-4366-a0be-2eb8a9a89d6a)
doing some initial tests with save after a fix to avoid vanilla enumeration changes. so far so good.
